### ISSUE TITLE
Issue Plex - Intro detection

### ISSUE THREAD

**Issue by chackl1990** [tteck/Proxmox#1007]
I am having a plexpass
Intro-Detection works on an Synolgy NAS (but the nas is slow so i watched this here, as i am running also a proxmox server)

the Intro-Detection is not working in my case.
in the logs "Plex Media Server.log" i get this lines:
```
Downloading document http://127.0.0.1:32400/library/metadata/XXX
downloadContainer: expected MediaContainer element, found html
IntroDetector: Failed to get metadata for: /mnt/media/XXX
```

then i ssh into the container to check:
```
# curl http://127.0.0.1:32400/library/metadata/XXX
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

then i entered 127.0.0.1 to advanced network config (IP with no auth):
still no luck

then i entered my network to advanced network config and with the network IP
curl http://x.x.x.x:32400/library/metadata/XXX
Status 200 - worked.

any hint you could give me?

Thank you!

**Comment by tteck** [comment]
Have you tried this
- Log in to the web interface of the Plex Media Server.
- Go to the server settings page.
- Click on the Network tab.
- Change the IP address under the "Custom server access URLs" section to "http://192.168.1.23:32400/" (or the desired IP address and port).
- Save the changes and restart the server.

**Comment by chackl1990** [comment]
you are a genius
did not try that and was not thinking about that it could be that.
Thank you!
