### ISSUE TITLE
Zigbee2MQTT update fails with unknown error

### ISSUE THREAD

**Issue by smarthomelawyer** [tteck/Proxmox#1009]
Ran the v5 script in the z2m LXC console to update Z2m to 1.30.0 and received the following unknown error:

Updating Zigbee2MQTT...‼ ERROR 1@365 Unknown failure occurred.

Any ideas what could be causing this? I also tried the old way with bash update.sh to no avail

**Comment by tteck** [comment]
Run the command `git stash` in the LXC console, then update.
https://github.com/tteck/Proxmox/issues/939

**Comment by smarthomelawyer** [comment]
Thank you!!

**Comment by mguedes71** [comment]
Many thanks!!

**Comment by tteck** [comment]
I incorporated this code into the update script.
```
echo "Initiating update"
if ! git pull; then
  echo "Update failed, temporarily storing changes and trying again."
  git stash && git pull || (echo "Update failed even after storing changes. Aborting."; exit 1)
fi
```
This should simplify the process.
