### ISSUE TITLE
NextcloudPi Installation Error in line 96

### ISSUE THREAD

**Issue by bedson87** [tteck/Proxmox#1016]
Hi,
I've always used your script and it worked fine, but today I got an error:
![prox_nextcloud_error](https://user-images.githubusercontent.com/37672068/216772936-cf9555e9-b613-469a-a772-0ecafe7fc389.png)

**Comment by tteck** [comment]
Thank you for reporting!
Fixed [351161b](https://github.com/tteck/Proxmox/commit/351161bc835e9f96b38508acf054d977e02af944)
