### ISSUE TITLE
Failed to create Jellyfin on Ubuntu 22.10

### ISSUE THREAD

**Issue by nacho-domatix** [tteck/Proxmox#1029]
**Describe the issue**

```
 - Creating LXC Container...+ pct create 210 fivetb:vztmpl/ubuntu-22.10-standard_22.10-1_amd64.tar.zst -features nesting=1 -hostname jellyfin -net0 name=eth0,bridge=vmbr0,ip=dhcp -onboot 1 -cores 2 -memory 4096 -unprivileged 0 -password ***** -rootfs local-lvm:16
unable to create CT 210 - unsupported Ubuntu version '22.10'
+ exit 'A problem occured while trying to create container.'
bash: line 131: exit: A problem occured while trying to create container.: numeric argument required
+ exit
```

**Comment by tteck** [comment]
No issue here

```
       __     ____      _____     
      / /__  / / /_v5__/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
 
Using Advanced Settings
Using Ubuntu Version: 22.10
Using Container Type: 0
Using Root Password: Automatic Login
Using Container ID: 114
Using Hostname: jellyfin
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Disable IPv6: Yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Jellyfin LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 114 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Hardware Acceleration
 ✓ Set Up Jellyfin Repository
 ✓ Installed Jellyfin
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Jellyfin should be reachable by going to the following URL.
             http://192.168.86.252:8096
```
Did you check to see if it downloaded the template?

**Comment by nacho-domatix** [comment]
I'll check it again, it worked with 22.04

**Comment by nacho-domatix** [comment]
__     ____      _____     
      / /__  / / /_v5__/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
 
Using Advanced Settings
Using Ubuntu Version: 22.10
Using Container Type: 0
Using Root Password: spidey
Using Container ID: 211
Using Hostname: jellyfin
Using Disk Size: 16
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Jellyfin LXC using the above advanced settings
 ✓ Using fivetb for Template Storage.
 ✓ Using local-lvm for Container Storage.
 - Updating LXC Template List..."my" variable $node masks earlier declaration in same scope at /usr/share/perl5/PVE/API2/Disks/ZFS.pm line 345.
 ✓ Updated LXC Template List
"my" variable $node masks earlier declaration in same scope at /usr/share/perl5/PVE/API2/Disks/ZFS.pm line 345.
"my" variable $node masks earlier declaration in same scope at /usr/share/perl5/PVE/API2/Disks/ZFS.pm line 345.
 - Creating LXC Container...unable to create CT 211 - unsupported Ubuntu version '22.10'
bash: line 131: exit: A problem occured while trying to create container.: numeric argument required

**Comment by nacho-domatix** [comment]
```
       __     ____      _____     
      / /__  / / /_v5__/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
 
Using Advanced Settings
Using Ubuntu Version: 22.10
Using Container Type: 0
Using Root Password: ****
Using Container ID: 211
Using Hostname: jellyfin
Using Disk Size: 16
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Jellyfin LXC using the above advanced settings
 ✓ Using fivetb for Template Storage.
 ✓ Using local-lvm for Container Storage.
 - Updating LXC Template List..."my" variable $node masks earlier declaration in same scope at /usr/share/perl5/PVE/API2/Disks/ZFS.pm line 345.
 ✓ Updated LXC Template List
"my" variable $node masks earlier declaration in same scope at /usr/share/perl5/PVE/API2/Disks/ZFS.pm line 345.
"my" variable $node masks earlier declaration in same scope at /usr/share/perl5/PVE/API2/Disks/ZFS.pm line 345.
 - Creating LXC Container...unable to create CT 211 - unsupported Ubuntu version '22.10'
bash: line 131: exit: A problem occured while trying to create container.: numeric argument required

```

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/591

**Comment by tteck** [comment]
Did you check `fivetb` to see if it downloaded the template?

**Comment by nacho-domatix** [comment]
![imagen](https://user-images.githubusercontent.com/28144115/217093890-cecda73c-9b4d-428e-a257-5ce82b3f0656.png)

Commented and no difference.

**Comment by nacho-domatix** [comment]
> Did you check to see if it downloaded the template?

How can I check?

**Comment by tteck** [comment]
fivetb > CT Templates

**Comment by tteck** [comment]
> ![imagen](https://user-images.githubusercontent.com/28144115/217093890-cecda73c-9b4d-428e-a257-5ce82b3f0656.png)
> 
> Commented and no difference.

IIRC, a reboot is required

**Comment by nacho-domatix** [comment]
Ok, I'll check soon, right now can't reboot the server :(

Thanks anyway.

**Comment by tteck** [comment]
Closing, but monitoring

**Comment by nacho-domatix** [comment]
Rebooting doesn't fix it. 

Regarding templates, that's what I see:

```
ls -la
total 703156
drwxr-xr-x 2 root root      4096 Feb  6 22:15 .
drwxr-xr-x 4 root root      4096 Aug 15 23:41 ..
-rw-r--r-- 1 root root 123216040 Mar 28  2022 debian-11-standard_11.3-1_amd64.tar.zst
-rw-r--r-- 1 root root 123187438 Dec 20 09:32 debian-11-standard_11.6-1_amd64.tar.zst
-rw-r--r-- 1 root root 214203058 Apr 25  2020 ubuntu-20.04-standard_20.04-1_amd64.tar.gz
-rw-r--r-- 1 root root 129824858 Apr 24  2022 ubuntu-22.04-standard_22.04-1_amd64.tar.zst
-rw-r--r-- 1 root root 129577718 Oct 21 17:00 ubuntu-22.10-standard_22.10-1_amd64.tar.zst

```

**Comment by tteck** [comment]
Line 345 should be removed as it is a duplicate entry and if it's not present, it won't cause an error.
The 22.10 template appears to be available.

**Comment by jwmann** [comment]
@tteck I'm getting similar issues with the Plex Media Server LCX script.

I chose advanced because I wanted to give it more CPU cores, followed pretty much everything else as default but I get
![jwm-2024-10-24@2211](https://github.com/user-attachments/assets/ae16216e-b815-4a56-bda8-1fa4701935fe)


I'm new to Proxmox so it's possible I'm missing something obvious. I'm not sure what `fivetb` is

**Comment by jwmann** [comment]
Seems like it downloaded the template?
![jwm-2024-10-24@2222](https://github.com/user-attachments/assets/c54891fd-f3d3-4460-9f98-3abbafb42ee5)

**Comment by jwmann** [comment]
I fixed the issue.
Turns out I had to update my PVE version from 8.2.2 to 8.2.7 

This thread helped me
https://forum.proxmox.com/threads/task-error-unable-to-create-ct-100-unsupported-ubuntu-version-24-04.146475/#post-713792

```shell
apt-get update
apt-get dist-upgrade
pveam update
```

I rebooted after the `dist-upgrade`

Worked smooth as butter afterwords
