### ISSUE TITLE
PVE version issue

### ISSUE THREAD

**Issue by sarus3749** [tteck/Proxmox#1039]
Hello.
I'm trying to use [haos-vm-v5.sh](https://github.com/tteck/Proxmox/blob/main/vm/haos-vm-v5.sh)
The script tells "Requires PVE Version: =>7.2"
I'm on the latest PVE 7.3.3. Should it be possible to use it ?

**Comment by tteck** [comment]
Please execute the command `pveversion` and share the resulting output.

**Comment by sarus3749** [comment]
Hello. I didn't know that but it seems it's not installed. I did not think about that because I installed it before on a LXC and it worked. Now I want to a real VM.
Do you know how to install ?

**Comment by tteck** [comment]
Can you please rephrase your question or provide more context so I can better understand what you need help with and how I can assist you?

**Comment by oOStroudyOo** [comment]
Hi @sarus3749 
I've just trialed this script on PVE 7.3-6 and it works fine.

Open up your PVE shell and type `pveversion` please and let us know which PVE Manager version you are running.
If you're PVE manager is below 7.2 then you can run `apt upgrade` to update it to latest version.

Thank you.

**Comment by sarus3749** [comment]
Well. Thank you for your answers.
At the begening I thought it was a pve version issue. In fact, I realized after that pve-management is not installed. I made a VM with debian. There is no pve-management on it and, I looked for it, it seems to be difficult to install.
Is there any way to use your script in this type of install ?

**Comment by tteck** [comment]
No, sorry.

**Comment by tteck** [comment]
I apologize for giving a definite answer before. To try it out, you could remove the pve_check function and see if it works.

**Comment by tteck** [comment]
Try
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/dev/vm/haos-vm-v5.sh)"
```
and see if that will work for you. The dev branch will be deleted in a few hours.

**Comment by sarus3749** [comment]
Hi.
Nothing happened with your link

*Adrien de SARRAN*
***@***.***


Le ven. 10 févr. 2023 à 15:23, tteckster ***@***.***> a
écrit :

**Comment by sarus3749** [comment]
Hi.
Nothing happened with the link you sent me.

**Comment by tteck** [comment]
I previously mentioned that the link would only remain active for a limited time, but it is now available again for a one hour period.

**Comment by sarus3749** [comment]
Well it's telling that : 
bash: ligne 262: pvesm : commande introuvable
This is because pve is not installed as I told. But I did not found how to install it.

**Comment by tteck** [comment]
It appears that the only option to execute these scripts is to have Proxmox as the operating system.

**Comment by sarus3749** [comment]
well this is the case. I don't understand this issue but thank you very much for your help
