### ISSUE TITLE
Paperless-ngx classifier error NLTK

### ISSUE THREAD

**Issue by MaxKuh** [tteck/Proxmox#1041]
Hi tteck, 

Thanks for the awesome scripts. I just installed paperless-ngx and migrated my old database (from paperless-ng, upgraded to ngx, exported and then imported to the LXC paperless). 

In the logs I see the following:
````
[2023-02-10 19:31:10,256] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /opt/paperless/consume

[2023-02-10 19:31:39,704] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-02-10 19:31:39,705] [DEBUG] [paperless.classifier] Gathering data from database...

[2023-02-10 19:31:41,734] [WARNING] [paperless.tasks] Classifier error:

**********************************************************************

  Resource [93mpunkt[0m not found.

  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk

  >>> nltk.download('punkt')

  [0m

  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:

    - '/usr/share/nltk_data'

    - ''

********************************
````

I then did the following, which seems to solve the issue:
`python3 -m nltk.downloader -d /usr/share/nltk_data punkt`

I am not aware of any issues that might cause, I guess you know better if that is an issue that needs to be solved. 

Cheers
Max

**Comment by MaxKuh** [comment]
Sorry, just saw there is already a solved issue regarding that point, although dealing with another part of the NLTK toolkit.
For me it is solved.

**Comment by tteck** [comment]
I have altered the script to retrieve "all" instead of only "stopwords.
`python3 -m nltk.downloader -d /usr/share/nltk_data all`
