### ISSUE TITLE
Import Scrtipt does not work

### ISSUE THREAD

**Issue by thgeese** [tteck/Proxmox#1048]
**Describe the issue**
Trying to import a backup from other installation. Got this error.

Traceback (most recent call last):
  File "/opt/paperless/src/documents/management/commands/document_importer.py", line 17, in <module>
    from documents.models import Document
ModuleNotFoundError: No module named 'documents'

**Comment by tteck** [comment]
Let me see if I've got this right: you have the paperless-ngx software running inside an LXC container and now you want to import a backup into paperless-ngx. Is that correct?

**Comment by tteck** [comment]
Maybe `pip install documents` ?
