### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by agekristian** [tteck/Proxmox#1050]
**Describe the issue**
[ERROR] in line 311: exit code 5: while executing command pvesm alloc $STORAGE $VMID $DISK0 4M &> /dev/null

![2023-02-12 21_55_40-proxmox - Proxmox Virtual Environment](https://user-images.githubusercontent.com/97913529/218336555-da3e8547-e591-438d-9838-3f7d6e3a4492.png)

The Proxmix server has 16g memory and 750g free hd

what am i doing wrong?

**Comment by tteck** [comment]
Verify if there is an unneeded (stray) `vm-103-disk-0` present, and if so, delete it.

![Screenshot 2022-10-26 7 00 35 PM](https://user-images.githubusercontent.com/21342670/218337232-ae103159-d297-4432-a341-f27f2b2aab44.png)

**Comment by agekristian** [comment]
Thanks fixed the problem. seems the problem occurs if i exit "_shell" while the script is running.

**Comment by tteck** [comment]
Yes, that's correct. You should not exit/leave the shell while the script is running as it will interfere with the execution of the script.
