### ISSUE TITLE
Cant install Podman Home Assistant Container LXC

### ISSUE THREAD

**Issue by cronner** [tteck/Proxmox#1052]
✓ Installed Podman
 - Pulling Home Assistant Image...
[ERROR] in line 9: exit code 125: while executing command "$@" > /dev/null 2>&1

Proxmox 7.3 all updated

**Comment by tteck** [comment]
This reference may assist you in locating the problem: https://github.com/tteck/Proxmox/issues/914#issuecomment-1381763061
No issues here.
```
                     ____            __                                      
                    / __ \____  ____/ /___ ___  ____ _____                   
                   / /_/ / __ \/ __  / __  __ \/ __  / __ \                  
                  / ____/ /_/ / /_/ / / / / / / /_/ / / / /                  
    __  __       /_/    \____/\__,_/_/ /_/ /_/\__,_/_/ /_/__              __ 
   / / / /___  ____ ___  ___  v5 /   |  __________(_)____/ /_____ _____  / /_
  / /_/ / __ \/ __  __ \/ _ \   / /| | / ___/ ___/ / ___/ __/ __  / __ \/ __/
 / __  / /_/ / / / / / /  __/  / ___ |(__  |__  ) (__  ) /_/ /_/ / / / / /_  
/_/ /_/\____/_/ /_/ /_/\___/  /_/  |_/____/____/_/____/\__/\__,_/_/ /_/\__/  
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: podman-homeassistant
Using Disk Size: 16
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.253/24
Using Gateway IP Address: 192.168.86.1
Disable IPv6: Yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Podman-Home Assistant LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Podman
 ✓ Pulled Home Assistant Image
 ✓ Installed Home Assistant
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Podman-Home Assistant should be reachable by going to the following URL.
         http://192.168.86.253:8123 
```

**Comment by cronner** [comment]
It's only this HA, HA lxc installs just fine


 - Pulling Home Assistant Image...+ podman pull docker.io/homeassistant/home-assistant:stable
Trying to pull docker.io/homeassistant/home-assistant:stable...
WARN[0000] "/run/user/0" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/0: no such file or directory: Trying to pull image in the event that it is a public image.


Storing signatures
  chmod /var/lib/containers/storage/vfs/dir/d9c479131df195aae6d8faec3aa85e50152b50bc2529a2fd67446c2e6dadc0b4/usr/local/lib/python3.10/site-packages/fontTools/varLib/__pycache__/merger.cpython-310.pyc: disk quota exceeded
Error: Error committing the finished image: error adding layer with blob "sha256:79206d5fb00e9199211caba4687c9ad80bee1b6d61383bf97c93271e3e167a24": error creating layer with ID "d9c479131df195aae6d8faec3aa85e50152b50bc2529a2fd67446c2e6dadc0b4": chmod /var/lib/containers/storage/vfs/dir/d9c479131df195aae6d8faec3aa85e50152b50bc2529a2fd67446c2e6dadc0b4/usr/local/lib/python3.10/site-packages/fontTools/varLib/__pycache__/merger.cpython-310.pyc: disk quota exceeded
++ error_handler 97 '$STD podman pull docker.io/homeassistant/home-assistant:stable'
++ local exit_code=125
++ local line_number=97
++ local 'command=$STD podman pull docker.io/homeassistant/home-assistant:stable'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m97\033[m: exit code \033[01;31m125\033[m: while executing command \033[33m$STD podman pull docker.io/homeassistant/home-assistant:stable\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m97\033[m: exit code \033[01;31m125\033[m: while executing command \033[33m$STD podman pull docker.io/homeassistant/home-assistant:stable\033[m\n'

[ERROR] in line 97: exit code 125: while executing command $STD podman pull docker.io/homeassistant/home-assistant:stable

**Comment by tteck** [comment]
~~`disk quota exceeded` are you using ZFS?~~
NVM, both are set to 16GB

**Comment by cronner** [comment]
Advanced settings and increased to 64gb then the install worked for me

**Comment by tteck** [comment]
ZFS?

**Comment by cronner** [comment]
yes ZFS

**Comment by tteck** [comment]
There you go, no Fuse Overlayfs setup in that LXC. Was you using Fuse Overlayfs in the Home Assistant Container LXC?

**Comment by cronner** [comment]
just did a promox 7.3 install, made ZFS storage, and tried the scripts, didn't do anything else was same for both.

**Comment by tteck** [comment]
If you need a simple, reliable file system for a small- to medium-sized system, EXT4 may be the better choice.

If you require advanced features for large-scale storage systems, ZFS may be the better option.

It's important to choose the appropriate file system before you proceed too far into using Proxmox.
