### ISSUE TITLE
Trilium Script Syntax Error 

### ISSUE THREAD

**Issue by bastian1607** [tteck/Proxmox#1057]
I get a syntax error when using the helper script for Trilium.

Using Default Settings
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: Automatic Login
Using Container ID: 106
Using Hostname: trilium
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Trilium LXC using the above default settings
bash: -c: line 359: syntax error in conditional expression

**Comment by tteck** [comment]
Thanks for reporting!
fixed

**Comment by bastian1607** [comment]
Confirmed. Installation completed now.
