### ISSUE TITLE
wiki.js script updating issue

### ISSUE THREAD

**Issue by kusunoki777** [tteck/Proxmox#1067]
https://github.com/tteck/Proxmox/blob/11aa80c9783e71fab22efbddca17fab4ee8106ed/install/wikijs-v5-install.sh#L112
https://github.com/tteck/Proxmox/blob/11aa80c9783e71fab22efbddca17fab4ee8106ed/ct/wikijs-v5.sh#L330
https://github.com/tteck/Proxmox/blob/11aa80c9783e71fab22efbddca17fab4ee8106ed/ct/wikijs-v5.sh#L338

storage for sqlite db points to /opt/wikijs/db.sqlite 
when updating via script in lxc console, db gets deleted all together
propose to change db path in default config.yml 
also need to rebuild sqlite3 after updating `npm rebuild sqlite3` and `systemctl start wikijs`

> These engines (MySQL, MariaDB, MS SQL Server and SQLite) will NOT be supported in the next major version of Wiki.js. Make sure you understand the implications of migrating your database to PostgreSQL if you plan on upgrading to 3.x+ in the coming years. 

the next major release will only support PostgreSQL, it might worth considering deploying PostgreSQL instead of sqlite for easier future upgrading.

**Comment by tteck** [comment]
Thanks for reporting!
Resolved the issue with the update process. As for transitioning to PostgreSQL, we will address that when it becomes necessary.
