### ISSUE TITLE
Dashy LXC default disk size might be to small

### ISSUE THREAD

**Issue by DevJulian1966** [tteck/Proxmox#1070]
Hi, after a Proxmox update this morning, my Dashy instance wasn't reachable via the browser.
After a bit of troubleshooting (Dashy.service wasn't running, couldn't be started --> error messages leading to low disk space) I resized the allocated disk size to 6GB. After that the service was starting normally with the container.

6GB might be oversized, but it seems that the default 3GB are a bit tight.

Maybe change the default to 4GB?

**Comment by tteck** [comment]
I agree. Fresh install:
![Screenshot 2023-02-17 7 10 30 AM](https://user-images.githubusercontent.com/21342670/219652921-bea065b3-6e27-4a28-be35-f1b9c5d76b92.png)
Made default 6GB
