### ISSUE TITLE
Link Backup install nao funciona

### ISSUE THREAD

**Issue by hacloudercb** [tteck/Proxmox#1071]
O link:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pbs-install.sh)"

Não está funcionando.

**Comment by tteck** [comment]
I apologize, but in order to assist you, could you please provide more details than simply stating "It's not working"? Also, please communicate in English.

**Comment by tteck** [comment]
I don't use PBS, but when I run the command I get:
```
This script will Perform Post Install Routines.
Start the PBS Post Install Script (y/n)?y

🛑  PVE Detected, Wrong Script!

root@server:~# 
```
