### ISSUE TITLE
Being able to change storage size on LXC Docker

### ISSUE THREAD

**Issue by user34756361233** [tteck/Proxmox#1074]
The current script has the following standard:
Default Settings: 2GB RAM - 4GB Storage - 2vCPU
When choosing advanced I can change a lot but can't choose other size of storage or storage location.
4 Gb is not enough for storage of multiple containers

kr

Han

**Comment by tteck** [comment]
Advanced settings 

![Screenshot 2023-02-18 1 58 41 PM](https://user-images.githubusercontent.com/21342670/219883456-10c587fb-09fa-487b-9707-57ce6d092ac7.png)

**Comment by user34756361233** [comment]
Thanks for the swift response, I had another check and indeed I oversaw the option. Will there be a future option to change storage location (shared storage for example)

Regards,

Han

**Comment by tteck** [comment]
If you have configured multiple storage locations for your containers, a menu will be displayed, prompting you to select the desired storage location.

![Screenshot 2023-02-20 4 41 11 AM](https://user-images.githubusercontent.com/21342670/220070339-a3e430ab-1c79-4462-89be-c98da6627c3d.png)

**Comment by user34756361233** [comment]
I do not see the menu, but have two types of storage (local zfs and nfs). For now if I disable local zfs for storage it's being created on nfs. Thx for the very useful scripts, I use a number of them a lot

kr

Han

edit: you will see the menu if going for default but not in advanced.

**Comment by tteck** [comment]
> you will see the menu if going for default but not in advanced.

If you have configured multiple storage locations for your containers, the menu to select the desired storage location will be displayed at the start of the container creation process.

To properly configure your storage locations, you need to specify the purpose of each storage location in the Datacenter section, under the Storage tab.

![Screenshot 2023-02-20 2 32 47 PM](https://user-images.githubusercontent.com/21342670/220186276-555b3711-646a-41ca-98b2-39af85e61c04.png)
