### ISSUE TITLE
TechnitiumDNS 8.0 needs .Net 6.0

### ISSUE THREAD

**Issue by Calimerorulez** [tteck/Proxmox#108]
Hi,

Just ran the update script for Technitium to upgrade to 8.0, and the following error showed when trying to start the service:

```
Mar 28 20:46:42 technitiumdns dns-server[2425]: It was not possible to find any compatible framework version
Mar 28 20:46:42 technitiumdns dns-server[2425]: The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
Mar 28 20:46:42 technitiumdns dns-server[2425]:   - The following frameworks were found:
Mar 28 20:46:42 technitiumdns dns-server[2425]:       5.0.15 at [/opt/dotnet/shared/Microsoft.NETCore.App]
Mar 28 20:46:42 technitiumdns dns-server[2425]: You can resolve the problem by installing the specified framework and/or SDK.
Mar 28 20:46:42 technitiumdns dns-server[2425]: The specified framework can be found at:
Mar 28 20:46:42 technitiumdns dns-server[2425]:   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=debian.11-x64
Mar 28 20:46:42 technitiumdns systemd[1]: dns.service: Main process exited, code=exited, status=150/n/a
```

I changed the update script manually from 5.0 to 6.0 and now Technitium starts fine.

**Comment by tteck** [comment]
Thank you for reporting this! Script has been corrected!

## Version 8.0
Release Date: 26 March 2022
- Added EDNS support [RFC 6891](https://datatracker.ietf.org/doc/html/rfc6891).
- Added Extended DNS Errors [RFC 8914](https://datatracker.ietf.org/doc/html/rfc8914).
- Added DNSSEC validation support with RSA & ECDSA algorithms for recursive resolver, forwarders, and conditional forwarders.
- Added DNSSEC support for all supported DNS transport protocols including encrypted DNS protocols (DoT, DoH, DoH JSON).
- Added DNSSEC zone signing support with RSA & ECDSA algorithms.
- Updated DNS Client to support DNSSEC validation.
- Updated proprietary FWD record which is used with Conditional Forwarder Zones for DNSSEC validation and HTTP/SOCKS5 proxy support.
- Updated Conditional Forwarder Zones to support working as a static stub zone to force a domain name to resolve via given name servers using NS records.
- **Upgraded codebase to .NET 6 runtime.**
- Query Logs App: Added wildcard search support for domain names.
- Fixed multiple issues with DHCP server.
- This release updates many API calls which may cause issues in 3rd party clients if they are not updated before deploying this new version. It is recommended to check the API documentation for changes before deploying this new release.
- Multiple other minor bug fixes and improvements.
