### ISSUE TITLE
Port 81

### ISSUE THREAD

**Issue by Scrat80** [tteck/Proxmox#1085]
I did the advanced setup option for NGINX. Entered in what it asked for, etc, etc. I get the message saying it should be reachable at port 81. I tried that, and.. it didn't work.

Looking through the code, I noticed there is no port option. I don't know if it's related. I'm gonna try the basic route, and see if it works.

Update: Doing the install in basic mode does not fix the problem.

**Comment by Scrat80** [comment]
The fix? Tell people to go to IP:81/login. You are not redirected to go there. It works with an advanced install.

Cheers.

**Comment by tteck** [comment]
Accessing port 81 should automatically redirect you to port 81/login.
