### ISSUE TITLE
PhotoPrism script licence issue

### ISSUE THREAD

**Issue by IndrekHaav** [tteck/Proxmox#109]
I noticed that your [PhotoPrism install script](https://github.com/tteck/Proxmox/blob/main/setup/photoprism-install.sh) is based on [IndrekHaav/photoprism-debian](https://github.com/IndrekHaav/photoprism-debian). In fact, other than the boilerplate stuff, the main installation steps are taken pretty much verbatim from my guide, as well as stuff like .env and service file contents.

While that's fine, I did want to point out that my guide is published under the MIT licence, which requires that the copyright notice be included in all copies and substantial portions thereof. I would appreciate it if you would add the required copyright notice and licence information to your script. Alternatively, a link back to my repo would also work, if you don't want to include the entire licence text.

Thanks!

**Comment by tteck** [comment]
```
inspired by https://github.com/IndrekHaav/photoprism-debian
in https://github.com/tteck/Proxmox/blob/main/setup/photoprism-install.sh
```

**Comment by tteck** [comment]
Since no software or associated documentation files of such software were copied,  repo link removed. Guides doesn't fall under MIT licence protection.
