### ISSUE TITLE
Meshcentral Script

### ISSUE THREAD

**Issue by DrLabel** [tteck/Proxmox#1092]
When I try your script for meshcentral I get :

    __  ___          __    ______           __             __
   /  |/  /__  _____/ /_  / ____/__  ____  / /__________ _/ /
  / /|_/ / _ \/ ___/ __ \/ /   / _ \/ __ \/ __/ ___/ __  / / 
 / /  / /  __(__  ) / / / /___/  __/ / / / /_/ /  / /_/ / /  
/_/  /_/\___/____/_/ /_/\____/\___/_/ /_/\__/_/ v5\__,_/_/   
 
Using Default Settings
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: Automatic Login
Using Container ID: 109
Using Hostname: meshcentral
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a MeshCentral LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 - Creating LXC Container...unable to create CT 109 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - --zstd --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/109/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 2
bash: line 137: exit: A problem occured while trying to create container.: numeric argument required
root@HomeServer:~#

**Comment by tteck** [comment]
No issues here
```
    __  ___          __    ______           __             __
   /  |/  /__  _____/ /_  / ____/__  ____  / /__________ _/ /
  / /|_/ / _ \/ ___/ __ \/ /   / _ \/ __ \/ __/ ___/ __  / / 
 / /  / /  __(__  ) / / / /___/  __/ / / / /_/ /  / /_/ / /  
/_/  /_/\___/____/_/ /_/\____/\___/_/ /_/\__/_/ v5\__,_/_/   
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 113
Using Hostname: meshcentral
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Disable IPv6: Yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a MeshCentral LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed MeshCentral
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

MeshCentral should be reachable by going to the following URL.
         http://192.168.86.252 
```
That's a mess. Is this a normal Proxmox VE install?

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.

**Comment by DrLabel** [comment]
Is a normal Proxmox install and all other scripts works .....

**Comment by DrLabel** [comment]
Ok its fixed after reboot every thing is working thanks for your time
