### ISSUE TITLE
nginx proxy manager

### ISSUE THREAD

**Issue by stress1ner** [tteck/Proxmox#11]
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 110: 'wget $WGETOPT -c $_npm_url/archive/v$_latest_version.tar.gz -O - | tar -xz'
Broken pipe
Broken pipe
HTTP/1.1 404 Not Found
invalid magic
short read
[error] 195 NULL: pct exec $_ctid -- sh -c "wget --no-cache -qO - $_raw_base/setup.sh | sh"

**Comment by tteck** [comment]
You're correct!
![Screenshot 2022-01-14 9 37 59 PM](https://user-images.githubusercontent.com/21342670/149606290-cfb6f81f-ccea-46b5-84b1-3c19dc062a2b.png)
[This is the only script in my repo that's not mine. There's an issue open on this](https://github.com/ej52/proxmox-scripts/blob/main/lxc/nginx-proxy-manager/README.md)
I thought there was no need to reinvent the ~~wheel~~ script, but now I will

**Comment by tteck** [comment]
Temporarily, you can install a Debian 11+ LXC (from this repo) increase disk size 1gb and run the below script in the console of the newly created LXC
```yaml
bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/wip/npm_start.sh)"
```
I should have everything completed soon

**Comment by tteck** [comment]
Fixed, thanks for reporting it
