### ISSUE TITLE
Update Zigbee2MQTT LXC to latest-dev

### ISSUE THREAD

**Issue by stefansoeberg** [tteck/Proxmox#110]
Is it possible to update to latest-dev, and if so, how?

The home assistant update menu is super delicious. But another solution is also fine

**Comment by tteck** [comment]
Yep, 
```
cd /opt/zigbee2mqtt
```
```
nano update.sh
```
Change to "git checkout dev"
```
echo "Updating..."
git checkout HEAD -- npm-shrinkwrap.json
git fetch
git checkout dev
git pull 
```
