### ISSUE TITLE
Technitium v11 issue - requieres ASP.NET Core Runtime

### ISSUE THREAD

**Issue by Unerreicht** [tteck/Proxmox#1104]
**Describe the issue**
After updating Technitium to v11 via script https://github.com/tteck/Proxmox/raw/main/ct/technitiumdns-v5.sh, DNS server fails to start.

As per changelog at https://github.com/TechnitiumSoftware/DnsServer/blob/master/CHANGELOG.md 
-> for v11.0, ASP.NET Core Runtime is a new dependency.

After manual installation server runs without any further issues

**Comment by tteck** [comment]
Thank you for bringing this to my attention!

I have made updates to the installation script for ASP.NET Core Runtime, and have also included a check during updates to ensure that the runtime is installed.
