### ISSUE TITLE
[ERROR] in line 311: exit code 5

### ISSUE THREAD

**Issue by DuckieNL** [tteck/Proxmox#1117]
Hi i got thies error.
how can i fix this?
here is the whole script i see in the shell
Using Default Settings
Using HAOS Version: 9.5
Using Virtual Machine ID: 100
Using Machine Type: i440fx
Using Hostname: haos9.5
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using MAC Address: 02:41:52:70:97:BA
Using VLAN: Default
Using Interface MTU Size: Default
Start VM when completed: yes
Creating a HAOS VM using the above default settings
 ✓ Using local-lvm for Storage Location.
 ✓ Virtual Machine ID is 100.
 ✓ https://github.com/home-assistant/operating-system/releases/download/9.5/haos_ova-9.5.qcow2.xz
 ✓ Downloaded haos_ova-9.5.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...
[ERROR] in line 311: exit code 5: while executing command pvesm alloc $STORAGE $VMID $DISK0 4M &> /dev/null

please advice how to fix this error.
and thanks in advance!
best regards
DuckieNL

**Comment by tteck** [comment]
Please check to see if there is a stray `vm-100-disk-0`, and if there is, remove it before running the script again.

![Screenshot 2022-10-26 7 00 35 PM](https://user-images.githubusercontent.com/21342670/222271413-40e2d998-534a-46ab-ae24-41699a84ccaf.png)

**Comment by DuckieNL** [comment]
You are amazing Sir!
i did hava a stray disk there probably from another vm i guess its up and running now thanks for the quick reply!
