### ISSUE TITLE
LXC - Tailscale

### ISSUE THREAD

**Issue by boomam** [tteck/Proxmox#1124]
**Describe the issue**
Running the install script for the Tailscale LXC creates the LXC, but does not complete.  
After asking for the LXC ID, it shows "Installing Tailscale", then drops to CLI without further input or note.  
Checking the Proxmox GUI, it shows an LXC created, but not named - equally it does not boot if manually started either.  

**Screenshots**
The below is what shows in the terminal session - 
````
root@prox01:~# bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/add-tailscale-lxc.sh)" -s 2001
  ______      _ __                __
 /_  __/___ _(_) /_____________ _/ /__
  / / / __ `/ / / ___/ ___/ __ `/ / _ \
 / / / /_/ / / (__  ) /__/ /_/ / /  __/
/_/  \__,_/_/_/____/\___/\__,_/_/\___/

This script will add Tailscale to an existing LXC Container ONLY
Did you replace 106 with your LXC ID? Proceed(y/n)?y
Installing Tailscale...
root@prox01:~#
```

**Comment by tteck** [comment]
The script does not create a new LXC container; rather, it adds Tailscale functionality to an existing LXC container.

**Comment by boomam** [comment]
Ok, i did suspect that, but that didn't work either - i'll post those logs too, shortly.

Could be worth additional clarity, as "To Install Talescale on an existing LXC" on the main description implies that thats an optional extra 'feature', perhaps having something in bold to show it differs from the other LXC scripts?

**Comment by boomam** [comment]
Error from within an LXC container - base template: Ubuntu 22.10-standard-amd64
```
  ______      _ __                __
 /_  __/___ _(_) /_____________ _/ /__
  / / / __ `/ / / ___/ ___/ __ `/ / _ \
 / / / /_/ / / (__  ) /__/ /_/ / /  __/
/_/  \__,_/_/_/____/\___/\__,_/_/\___/

This script will add Tailscale to an existing LXC Container ONLY
Did you replace 106 with your LXC ID? Proceed(y/n)?y
-s: line 53: /etc/pve/lxc/2001.conf: No such file or directory
‼ ERROR 1@53 Unknown failure occured.
root@tailscale-01:~#
```

**Comment by tteck** [comment]
I think you need to read the instructions again. You can't run the command in a LXC console.

**Comment by boomam** [comment]
Tried this every which way, error remains ;-)  
&nbsp;  
Regardless, i've just deployed it (tailscale) to my kube cluster instead, so I'm not too worried for my uses right now.
However, i'm happy to help provide additional logs if you want to diagnose further, if not, feel free to close the issue.
&nbsp;  
Comment on the clarity on your main page however remains, happy to put in a PR to add additional notes for clarity if you want?

**Comment by tteck** [comment]
```
  ______      _ __                __        
 /_  __/___ _(_) /_____________ _/ /__      
  / / / __ `/ / / ___/ ___/ __ `/ / _ \     
 / / / /_/ / / (__  ) /__/ /_/ / /  __/     
/_/  \__,_/_/_/____/\___/\__,_/_/\___/      
                                            
This script will add Tailscale to an existing LXC Container ONLY
Did you replace 106 with your LXC ID? Proceed(y/n)?y
Installing Tailscale...
Installed Tailscale
 ✔ Completed Successfully!
 Reboot 112 LXC to apply the changes, then run tailscale up in the LXC console
root@server:~# 
```
