### ISSUE TITLE
Filebrowser binds to 127.0.0.1

### ISSUE THREAD

**Issue by timdonovanuk** [tteck/Proxmox#1125]
**Describe the issue**

Often after running the Filebrowser install script it is not reachable at the url/port. I have this issue intermittently when installing Filebrowser in LXCs. It's about 50% whether it works or not.

After investigating, it seems like FB by default listens on 127.0.0.1 which is not reachable externally. It should be set to listen on 0.0.0.0.

E.g.

```
root@lxc-foo: ~# /usr/local/bin/filebrowser -r /
2023/03/06 15:01:32 No config file used
2023/03/06 15:01:32 Listening on 127.0.0.1:8080
```

^ Can't connect.

```
root@lxc-foo:~# /usr/local/bin/filebrowser -r / -a 0.0.0.0
2023/03/06 15:05:23 No config file used
2023/03/06 15:05:23 Listening on [::]:8080
```

^ All good now.

My request is to consider adding in -a 0.0.0.0 by default so it always listens on all IPs.

**Comment by tteck** [comment]
I've never had that issue. You can see in the script that the address to listen on is being set:
```
filebrowser config init -a '0.0.0.0' &>/dev/null
filebrowser config set -a '0.0.0.0' &>/dev/null
```
https://filebrowser.org/cli/filebrowser-config-init
https://filebrowser.org/cli/filebrowser-config-set

**Comment by tteck** [comment]
Did you delete the database `filebrowser.db` from root?

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.

**Comment by timdonovanuk** [comment]
> I've never had that issue. You can see in the script that the address to listen on is being set:
> 
> ```
> filebrowser config init -a '0.0.0.0' &>/dev/null
> filebrowser config set -a '0.0.0.0' &>/dev/null
> ```
> 
> https://filebrowser.org/cli/filebrowser-config-init https://filebrowser.org/cli/filebrowser-config-set

Hmm odd one then! Must be something else. Thanks anyway.

**Comment by timdonovanuk** [comment]
This is still a problem for me. In new containers, filebrowser usually doesn't work. If I kill the process and then restart it (using the exact same command (/usr/local/bin/filebrowser -r /) it _sometimes_ works. On a reboot, same thing, it binds to 127.0.0.1

```
root@lxc-photoprism:/# /usr/local/bin/filebrowser -r /
2023/04/14 21:52:05 No config file used
2023/04/14 21:52:05 Listening on 127.0.0.1:8080
```

¯\\_(ツ)_/¯

**Comment by tteck** [comment]
Try running the commands in the LXC console
```
filebrowser config init -a '0.0.0.0'
filebrowser config set -a '0.0.0.0'
```

**Comment by timdonovanuk** [comment]
Sorry man, IDK what to tell you but this is still a problem for me. I see in the script now it sets 0.0.0.0, and I can even see in the filebrowser config it's set to 0.0.0.0 but the service log still reports:

`Oct 12 18:13:23 lxc-paperlessngx filebrowser[1027]: 2023/10/12 18:13:23 Listening on 127.0.0.1:8080`

I am literally just using one of your other lxc scripts with no changes other than I guess setting a static IP, which I do via the script...

**Comment by tteck** [comment]
I can't replicate your issue.

**Comment by timdonovanuk** [comment]
Does yours say Listening on 127.0.0.1:8080? I'll investigate that if it doesn't. Cheers.

**Comment by tteck** [comment]
```
root@homeassistant-core:~# systemctl status filebrowser
* filebrowser.service - Filebrowser
     Loaded: loaded (/etc/systemd/system/filebrowser.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-10-10 16:53:39 EDT; 1 day 20h ago
   Main PID: 154 (filebrowser)
      Tasks: 6 (limit: 38245)
     Memory: 13.2M
        CPU: 88ms
     CGroup: /system.slice/filebrowser.service
             `-154 /usr/local/bin/filebrowser -r /

Oct 10 16:53:39 homeassistant-core systemd[1]: Started filebrowser.service - Filebrowser.
Oct 10 16:53:39 homeassistant-core filebrowser[154]: 2023/10/10 16:53:39 No config file used
Oct 10 16:53:39 homeassistant-core filebrowser[154]: 2023/10/10 16:53:39 Listening on [::]:8080
```
