### ISSUE TITLE
Alpine-Vaultwarden-v5

### ISSUE THREAD

**Issue by tteck** [tteck/Proxmox#1127]
This is my first time creating Alpine Linux Scripts. If you're finding it frustrating to build Vaultwarden on Debian due to long build times, then this solution is for you. Alpine has a Vaultwarden package that makes creating an LXC container much, much faster, and it uses minimal system resources, **256Mib RAM - 300MiB Storage - 1vCPU**. 
Please note that this is my first attempt, so I'm sure there's room for improvement.

To create a new Proxmox Alpine-Vaultwarden LXC, run the command below in the Proxmox Shell.
To Update Vaultwarden, or Show the Admin Token, run the command below in the LXC Console.
```
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden-v5.sh)"
```

**Comment by tteck** [comment]
Now in the main branch.

**Comment by nicedevil007** [comment]
Organizations seems to not be able to invite anyone else or show all the entries of the vault that I have imported to them. That was/is working on the default installation method.

**Comment by nicedevil007** [comment]
![image](https://user-images.githubusercontent.com/17103076/223511138-ba4b5f8a-4b17-4078-9a34-66f69934e5fe.png)

I can't get rid of the update info there

**Comment by nicedevil007** [comment]
Ok, moved this to discussion because issue is closed => https://github.com/tteck/Proxmox/discussions/1132

**Comment by pradt** [comment]
hi how do you use this  ? is this delivered as a template ?
