### ISSUE TITLE
Error when executing timedatectl set-timezone $tz

### ISSUE THREAD

**Issue by SplendidAppendix** [tteck/Proxmox#1133]
Receiving an _[ERROR] in line 50: exit code 1: while executing command timedatectl set-timezone $tz_ when using the keycloak-lxc script. Think this would be in reference to #1131

**Comment by tteck** [comment]
What's the output from `timedatectl | grep "Time zone" | awk '{print $3}'` when ran in the Proxmox Shell?

**Comment by tteck** [comment]
No issue here

```
    __ __                __            __  
   / //_/__v5__  _______/ /___  ____ _/ /__
  / ,< / _ \/ / / / ___/ / __ \/ __  / //_/
 / /| /  __/ /_/ / /__/ / /_/ / /_/ / ,<   
/_/ |_\___/\__, /\___/_/\____/\__,_/_/|_|  
          /____/                           

Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 113
Using Hostname: keycloak
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: Yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Keycloak LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Keycloak
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Keycloak should be reachable by going to the following URL.
         http://192.168.86.253:8080 
```
So, every script has the same code.

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.

**Comment by porchi** [comment]
This evening all scrips are ending with the same error:
`[ERROR] in line 49: exit code 1: while executing command timedatectl set-timezone $tz`
while this same morning I successfully installed a couple of utilities.
Anyway, thanks for your huge work.

**Comment by tteck** [comment]
@porchi What's the output from `timedatectl | grep "Time zone" | awk '{print $3}'` when ran in the Proxmox Shell?

**Comment by porchi** [comment]
I already checked that before and it was `Europe/Madrid`.

**Comment by tteck** [comment]
If the `tzdata` on Proxmox is not configured correctly, the container creation scripts will fail to set the time zone. To avoid this issue, I recommend running the command `dpkg-reconfigure tzdata` in the Proxmox Shell to ensure that `tzdata` is set up correctly.  

The script uses the variable `timezone=$(timedatectl | grep "Time zone" | awk '{print $3}')` to retrieve the time zone information from Proxmox. This variable is then exported as `export tz=$timezone` so that the install script can use it to set the container's time zone using `timedatectl set-timezone $tz`.

**Comment by porchi** [comment]
I ran `dpkg-reconfigure tzdata` before in case it was that but it still continued to give the same error. Very strange.

**Comment by tteck** [comment]
>I already checked that before and it was Europe/Madrid.

I am not aware of any issues that would cause the script to fail. Are you executing the command to create the script from within the Proxmox Shell or via SSH?

**Comment by porchi** [comment]
i've tried both

**Comment by tteck** [comment]
Based on the information you provided, the script is retrieving data from Proxmox and exporting it, so there should be no issues with it.  🤷🏻‍♂️

**Comment by tteck** [comment]
I'm going to reopen to increase visibility.

**Comment by SplendidAppendix** [comment]
To follow up, when I run `dpkg-reconfigure tzdata` it updates successfully, and the output of `timedatectl | grep "Time zone" | awk '{print $3}'` is `America\Chicago`. After doing that, I still get an error message when running the script. 

The only difference between your running the script and mine is that I am creating a privileged container.

**Comment by tteck** [comment]
Just created a privileged container, no issues.

**Comment by tteck** [comment]
@SplendidAppendix would you please try:
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/tz/ct/keycloak-v5.sh)"
```

**Comment by SplendidAppendix** [comment]
Still looks like I'm getting the same `[ERROR] in line 50: exit code 1: while executing command timedatectl set-timezone "${tz}"`

**Comment by tteck** [comment]
What's the output from `echo $LANG` when ran in the Proxmox Shell?

**Comment by SplendidAppendix** [comment]
> What's the output from `echo $LANG` when ran in the Proxmox Shell?

`en_US.UTF-8`

**Comment by tteck** [comment]
Unfortunately, I have run out of ideas. I hope that someone else will be able to provide assistance.

**Comment by SplendidAppendix** [comment]
> Unfortunately, I have run out of ideas. I hope that someone else will be able to provide assistance.

Is there a way to use a previous version of the scripts without the recent update for the timezone inclusion? Not really seeing a way to switch branches or tags.

**Comment by tteck** [comment]
No, sorry.
Have you tried running the script in verbose mode to see if it provides any additional information?

**Comment by tteck** [comment]
I have modified the code for setting the time zone. Could you please try it out and let me know if it works?
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/tz/ct/debian-v5.sh)"
```

**Comment by porchi** [comment]
> I have modified the code for setting the time zone. Could you please try it out and let me know if it works?
> 
> ```
> bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/tz/ct/debian-v5.sh)"
> ```

I have just tried this and has worked perfectly.

**Comment by yodaphone** [comment]
i'm also having this issue while trying to create a Unifi Controller LXC. have posted it on the discussions, running latest version of PVE 7.3-6

**Comment by CodingEmil** [comment]
The debian scripts works for me aswell. The Docker Scripts also still having the same error:
`[ERROR] in line 50: exit code 1: while executing command timedatectl set-timezone $tz`

**Comment by tteck** [comment]
Fixed https://github.com/tteck/Proxmox/commit/1f9b959a471b0f47fe5f2ce40726b9e455900883

**Comment by porchi** [comment]
Thank you very much!!
