### ISSUE TITLE
docker v5 - portainer, failure to install.

### ISSUE THREAD

**Issue by cadriel** [tteck/Proxmox#1138]
I attempted to install the docker LXC container, using advanced settings (zfs..).

It looks like Docker installed correctly, but portainer failed.

<img width="762" alt="Screenshot 2023-03-08 at 10 30 04 AM" src="https://user-images.githubusercontent.com/205520/223772421-b27cfc47-bf81-4e0e-a89f-00319297a1e2.png">

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/914#issuecomment-1381763061
Can't replicate the issue:

```
    ____             __            
   / __ \____  _____/ /_v5__  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: docker
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: Yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: No
Enable Fuse Overlayfs (ZFS): No
Enable Verbose Mode: No
Creating a Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker v23.0.1
Would you like to add Portainer? <y/N> y
 ✓ Installed Portainer https://api.github.com/repos/portainer/portainer/releases/93222507
Would you like to add Docker Compose? <y/N> y
 ✓ Installed Docker Compose v2.16.0
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```
Don't know why it rendered the version like that.

**Comment by cadriel** [comment]
Aah, should I attempt it again.. anything else I can do to help diagnose?

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/914#issuecomment-1381763061

Yes, run in verbose mode

**Comment by cadriel** [comment]
Interestingly I just ran it again - this time I left the root login as all defaults (Automatic) - and it worked fine.

<img width="518" alt="Screenshot 2023-03-08 at 10 50 48 AM" src="https://user-images.githubusercontent.com/205520/223776952-9f24eb64-8b43-411a-86d3-7ba4878bd2d7.png">

Im not sure if it was a glitch my side, or something else.
