### ISSUE TITLE
Zigbee2MQTT update script don't work

### ISSUE THREAD

**Issue by larod241** [tteck/Proxmox#115]
Hi there, 

A new version of zigbee2mqtt as been delivered today.

I've start the update script but it doesn't work : 
![Capture d’écran 2022-04-01 à 09 53 17](https://user-images.githubusercontent.com/20423481/161220432-ed58cdcc-16d1-4a7c-b738-92f975b730a9.png)

**Comment by tteck** [comment]
The update script is from Zigbee2MQTT, so no trickery done by me.
FWIW, I just updated mine (dev branch) without issue

**Comment by larod241** [comment]
April Fool !!!

I just analyzed a bit and it seems that it's my Adguard which is a little too aggressive... :D :D
Sorry for the inconvenience and thanks for the quick response.

**Comment by tteck** [comment]
No problem

**Comment by davidmerrique** [comment]
@larod241 @tteck I just tried this and ran into that error. 
I had to cd into `/opt/zigbee2mqtt` first. 
Perhaps the readme should specify that:

Run in the LXC console
 ```yaml
cd /opt/zigbee2mqtt
bash ./update.sh
 ```

**Comment by tteck** [comment]
You are correct. I corrected the instructions
