### ISSUE TITLE
Autlogin not working on Alpine

### ISSUE THREAD

**Issue by nicedevil007** [tteck/Proxmox#1151]
**Describe the issue**
Hey tteck again, just small bug that I noticed during my testing/debugging time with your new LXC script.
I said yes and then advanced on the first 2 questions and then left the password field empty.
After the creation of alpine linux LXC the autologin isn't working and it keeps me asking for credentials.

**Screenshots**
![image](https://user-images.githubusercontent.com/17103076/224486740-29040e00-58d6-4ef5-8b7f-d52e3212dc8d.png)

**Comment by nicedevil007** [comment]
Ok this is also the case for the default OS LXC => no autologin on Alpine LXCs (not that I ever recommend that or using it)

**Comment by tteck** [comment]
In the instructions:
"By default, the root password is set to `alpine`. If you choose to use advanced settings, you will need to define a password, autologin is currently unavailable."

**Comment by tteck** [comment]
Added to Alpine LXC instructions, was already in Vaultwarden LXC instructions.

**Comment by nicedevil007** [comment]
ah sry... reading should help most of the time :D just was used to how you did this stuff on other scripts :)
