### ISSUE TITLE
Error with install script for CasaOS

### ISSUE THREAD

**Issue by anand7825** [tteck/Proxmox#1154]
______                 ____  _____
  / ____/___ __v5______ _/ __ \/ ___/
 / /   / __ `/ ___/ __ `/ / / /\__ \ 
/ /___/ /_/ (__  ) /_/ / /_/ /___/ / 
\____/\__,_/____/\__,_/\____//____/  
                                     
Loading...
bash: line 363: install_script: command not found

[ERROR] in line 363: exit code 127: while executing command install_script

**Comment by tteck** [comment]
Thank you for bringing this to my attention! 
fixed
