### ISSUE TITLE
Docker LXC script fails during Installation with missing arch error

### ISSUE THREAD

**Issue by anishd19** [tteck/Proxmox#1158]
**issue**

* Trying to install Docker LXC with `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker-v5.sh)"
` 
* The script fails with `missing arch - internal error`
*  Using default settings without any customisation

```
msg_info "Starting LXC Container"
 - Starting LXC Container...pct start $CTID
missing 'arch' - internal error at /usr/share/perl5/PVE/LXC.pm line 607.
error_handler $LINENO "$BASH_COMMAND"

[ERROR] in line 439: exit code 255: while executing command pct start $CTID

```

**Screenshots**

![image](https://user-images.githubusercontent.com/5480962/224541667-780898e6-2fec-449a-9f7b-e695a40c3292.png)

![image](https://user-images.githubusercontent.com/5480962/224541813-f0d57d5c-4d12-4664-a107-7dc8f7885b6b.png)

**Comment by tteck** [comment]
I'm sorry, but I cannot replicate the issue you are experiencing. Have you attempted to use these scripts to create any other Linux Containers (LXCs)?

```
    ____             __            
   / __ \____  _____/ /_v5__  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 114
Using Hostname: docker
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Fuse Overlayfs (ZFS): no
Enable Verbose Mode: no
Creating a Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 114 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker v23.0.1
Would you like to add Portainer? <y/N> y
 ✓ Installed Portainer 2.17.1
Would you like to add Docker Compose? <y/N> y
 ✓ Installed Docker Compose v2.16.0
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by anishd19** [comment]
I have successfully created a few LXCs with these repo scripts.
* Ubuntu LXC
* Nginx Proxy Manager LXC
* Postgres LXC

**Comment by tteck** [comment]
Since the process for creating LXC containers is mostly consistent across all scripts, if you were able to create them successfully in the past, it suggests that the problem you're experiencing now might be related to recent updates to the script bring out setup-related issues on your end. 
Is it possible to create  LXC containers now other than the Docker LXC container?

**Comment by anishd19** [comment]
Thank you for swift response.

I am afraid Ubuntu LXC is failing as well. It is throwing a different error though.

```
   __  ____                __       
  / / / / /_v5__  ______  / /___  __
 / / / / __ \/ / / / __ \/ __/ / / /
/ /_/ / /_/ / /_/ / / / / /_/ /_/ / 
\____/_.___/\__,_/_/ /_/\__/\__,_/  
 
Using Default Settings
Using ubuntu Version: 22.04
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: Automatic Login
Using Container ID: 101
Using Hostname: ubuntu
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Ubuntu LXC using the above default settings
 - Starting LXC Container...Configuration file 'nodes/pve/lxc/101.conf' does not exist

[ERROR] in line 424: exit code 255: while executing command pct start $CTID

```

**Comment by tteck** [comment]
It seems that both errors occur during the execution of the `pct start $CTID` command. This suggests that there may be underlying issues with your Proxmox setup that need to be resolved before you can continue using scripts from this repository.

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.

**Comment by tteck** [comment]
Have you been able to identify what is causing the problem in your setup?
