### ISSUE TITLE
✗ No app Installation Found!

### ISSUE THREAD

**Issue by sliine** [tteck/Proxmox#1160]
Hi, I want to install some application, but I get this error
![image](https://user-images.githubusercontent.com/45786427/224560380-7549e1ff-ce34-4802-9ae4-6d00d6f2ff5a.png)
![image](https://user-images.githubusercontent.com/45786427/224560391-0e2d2a0b-acce-4780-9660-475ed1b44192.png)

**Comment by tteck** [comment]
My suggestion would be to carefully read and follow the instructions provided with the script.

**Comment by sliine** [comment]
> My suggestion would be to carefully read and follow the instructions provided with the script.
Well, even in the video showed
https://ae.s21.pp.ua/Xshell_nyOhhmjkBr.mp4

**Comment by tteck** [comment]
The instruction clearly states that to create a new Proxmox WireGuard LXC, you should run the command below in the Proxmox Shell. It is not clear what "root@CT115" refers to, as it is not something that you would name the node.

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.

**Comment by tteck** [comment]
Have you been able to identify and correct the mistake you made?
