### ISSUE TITLE
Error updating Vaultwarden

### ISSUE THREAD

**Issue by Builder-DE-TH** [tteck/Proxmox#1162]
On updating I got this error

`- Updating VaultWarden to 1.27.0 (Patience)...
[ERROR] in line 379: exit code 101: while executing command cargo build --features "sqlite,mysql,postgresql" --release &> /dev/null`

Updating the web vault also gave an error and made the app unavailable throwing a 502 bad gateway, I have since managed to get the web vault to update successfully.

Just wanted to warn others.
`

**Comment by tteck** [comment]
Did you increase the resources beforehand?

**Comment by tteck** [comment]
No issue here. Resources set to 8vCPU and 4096MiB RAM

```
 _    __            ____ _       __               __         
| |  / /___ ___v5__/ / /| |     / /___ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
                                                             

 ⚠️  Ensure you set 4vCPU & 4096MiB RAM Minimum!!! 

 ✓ Stopped Vaultwarden
 ✓ Updated VaultWarden
 ✓ Cleaned
 ✓ Started Vaultwarden
 ✓ 1.27.0 Update Successful

 ⚠️  Ensure you set resources back to normal settings 

```
```
 _    __            ____ _       __               __         
| |  / /___ ___v5__/ / /| |     / /___ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
                                                             
 ✓ Stopped Vaultwarden
 ✓ Updated Web-Vault
 ✓ Cleaned
 ✓ Started Vaultwarden
 ✓ v2023.2.0 Update Successful
```

**Comment by Builder-DE-TH** [comment]
> Did you increase the resources beforehand?

I did. 3vCPU and 3000 MiB.

I'll try it again later with higher settings.

**Comment by Builder-DE-TH** [comment]
OK. Tried it again with 4vCPU and 4400MiB.

Same error. Gives 502. Needs reboot to recover.

**Comment by tteck** [comment]
I would recommend opening the Proxmox GUI in another browser tab to monitor the system summary and determine if more resources need to be assigned to the LXC. For instance, my Intel(R) Core(TM) i5-8250U CPU requires 8vCPU to prevent it from exceeding 100% usage.

**Comment by tteck** [comment]
>Same error. Gives 502. Needs reboot to recover.

`systemctl start vaultwarden.service` will also work, without having to reboot.

**Comment by tteck** [comment]
Changed recommendation to 4vCPU & 4096MiB RAM minimum for update.

**Comment by tteck** [comment]
Another suggestion is to check the storage usage to ensure that you are not exceeding the allocated storage for the LXC.

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.
