### ISSUE TITLE
Pressing enter without choosing will cause an unbound variable

### ISSUE THREAD

**Issue by Forsskieken** [tteck/Proxmox#118]
Hi,
Tried several scripts on a Proxmox 7.1-11 PVE
Tried several scripts in a Turnkey-core container
Tried in shell from proxmox
Tried in putty
result always:
[ERROR] 1@206 Unknown failure occured.
What am I missing?

**Comment by tteck** [comment]
Proxmox or PiMox?

**Comment by Forsskieken** [comment]
Hi, I found my error or ...
I needed to answer every question also the ones where I agreed with the proposal.
example:
network configuration:
1) **DHCP**
2) Manual
I just hit enter as I was ok with DHCP..
So the script lacks a default answer....

**Comment by tteck** [comment]
Not correct, if you just hit enter, the default is DHCP. It pauses to let you manually change DHCP reservation

**Comment by tteck** [comment]
Sorry, I understand what you are saying! My bad

**Comment by tteck** [comment]
So, without a selection (1 or 2) and pressing enter it will cause an unbound variable.

**Comment by tteck** [comment]
Thank you for finding this issue and bringing it to my attention.
Issue was fixed in PR #119
