### ISSUE TITLE
Alpine Adguard - /etc/timezone error

### ISSUE THREAD

**Issue by towerhand** [tteck/Proxmox#1188]
I get an error when running the script inside the container with the root user.

Script:
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-adguard-v5.sh)"

Error:
Loading...
cat: can't open '/etc/timezone': No such file or directory
bash: -c: line 486: syntax error: unexpected end of file

EDIT: The same happens with the vaultwarden and grafana containers.

**Comment by towerhand** [comment]
The same happens with the alpine-vaultwarden container.

**Comment by towerhand** [comment]
Thank you. Your are so fast, I see you are already fixing them.

**Comment by tteck** [comment]
Thank you for bringing this to my attention!
All Alpine scripts _should_ be fixed now.
