### ISSUE TITLE
Alpine-Grafana; unbound Variable

### ISSUE THREAD

**Issue by roswitina** [tteck/Proxmox#1193]
/ ____/________ _/ __/___ _____v5____ _
 / / __/ ___/ __  / /_/ __  / __ \/ __  /
/ /_/ / /  / /_/ / __/ /_/ / / / / /_/ / 
\____/_/   \__,_/_/  \__,_/_/ /_/\__,_/  
 Alpine
 
Using Default Settings
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: alpine
Using Container ID: 117
Using Hostname: alpine-grafana
Using Disk Size: 0.5
Allocated Cores 1
Allocated Ram 256
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Alpine-Grafana LXC using the above default settings
bash: line 449: timezone: unbound variable
root@pve:~#

**Comment by tteck** [comment]
fixed
