### ISSUE TITLE
Filebrowser - refused to connect

### ISSUE THREAD

**Issue by oldfart101** [tteck/Proxmox#1200]
This site can’t be reached 192.168.1.103 refused to connect

Proxmox Virtual Environment 7.3-3

**Comment by tteck** [comment]
According to the instructions, you should access the File Browser interface at "IP:8080" using a web browser. Before adding File Browser to a container, ensure that the container is not already using port 8080 to avoid conflicts.
```
    _______ __     ____                                   
   / ____(_) /__  / __ )_________ _      __________  _____
  / /_  / / / _ \/ __  / ___/ __ \ | /| / / ___/ _ \/ ___/
 / __/ / / /  __/ /_/ / /  / /_/ / |/ |/ (__  )  __/ /    
/_/   /_/_/\___/_____/_/   \____/|__/|__/____/\___/_/     
                                                          
 ✓ Installed FileBrowser on debian
 ✓ Created Service
 ✓ Completed Successfully!

FileBrowser should be reachable by going to the following URL.
         http://192.168.86.253:8080 
```
![Screenshot 2023-03-20 8 28 33 AM](https://user-images.githubusercontent.com/21342670/226339212-e1850eab-c024-40cc-8494-c2194e8ff3c5.png)

**Comment by tteck** [comment]
By the way, the latest version of Proxmox Virtual Environment is 7.3-6

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.
