### ISSUE TITLE
Photoprism - failed to initialize the container

### ISSUE THREAD

**Issue by Erl-gry** [tteck/Proxmox#1209]
Hi,

I am having problems installing Photoprism. No matter what settings I change. The installation always aborts with the error that the LXC container cannot be started. Even after updating the proxmox node.
Attached is a screenshot of the error message.

![image](https://user-images.githubusercontent.com/97357317/226834023-48710786-1cf7-4ff3-8dab-4d6f3c3ba779.png)

When I start the LXC manually I get the following error message:
`
()
run_buffer: 322 Script exited with status 255
lxc_init: 844 Failed to run lxc.hook.pre-start for container "112"
__lxc_start: 2027 Failed to initialize container "112"
TASK ERROR: startup for container '112' failed`

I'm running Proxmox PVE 7.3-6 with kernel 5.15.102-1-pve.

Is there something I'm missing here?

TIA for your help!

**Comment by Erl-gry** [comment]
FYI
I've just run the Proxmox VE 7 Post Install script but the error still appears

**Comment by tteck** [comment]
I would _guess_ that the problem pertains to storage. After conducting a brief search on Google, I came across the following URL: https://forum.proxmox.com/threads/failed-to-run-lxc-hook-pre-start.33260/. The problem is not related to the script.

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.
