### ISSUE TITLE
Home Assistant OS VM

### ISSUE THREAD

**Issue by xtremeideaz** [tteck/Proxmox#121]
Hello, Need your help again. 

trying to migrate my HA installation to a HP Elitedesk 800 G2 mini. its  core i3 3.2ghz  240 SSD 16gb machine running Proxmox.   I used your script to install the HA VM but i get stuck at preparing..... forever. i have deleted the VM over 5 times and still get the same issue when reinstalling. I also tried the manual way without the script. same issue. 

any tips to sort this out? 

Please help

**Comment by tteck** [comment]
Did you enable virtualization and disable secure boot in the bios?
