### ISSUE TITLE
Haos script does not work on Proxmox 7.3-6

### ISSUE THREAD

**Issue by phulstaert** [tteck/Proxmox#1211]
I cannot get Haos to run on my new Proxmox 7.3-6 machine.

Tried both a new install of Haos as a restore from a backup of a working Haos install on a Proxmox 7.3-4 installation.
Both times I get the same symptom.

![image](https://user-images.githubusercontent.com/8971696/226926135-646dd7b2-ec2a-4682-a7ac-f30191bb3615.png)

Settings:

![image](https://user-images.githubusercontent.com/8971696/226926222-2e8249ce-5f45-41ae-ae6a-39508182c640.png)

![image](https://user-images.githubusercontent.com/8971696/226926312-86cacde6-e9d1-467d-bbd7-bc5945a4d3ec.png)

On my working Proxmox 7.3-4 install these are my settings:

![image](https://user-images.githubusercontent.com/8971696/226926498-6365c2f7-641e-4b82-a14b-13b1abf29d72.png)

![image](https://user-images.githubusercontent.com/8971696/226926559-d90bcb90-c01b-4d50-bd35-f83869365ebb.png)

I can see under OS Type there is Linux 6.x vs Linux 5.x; but I do not have the Linux 5.x option anymore under Proxmox 7.3-6.
I did try Linux 2.6; none; etc... All with no effect.

I have no clue what is going on here...

**Comment by tteck** [comment]
Ensure that your machine's BIOS settings have UEFI Boot and Virtualization enabled, while Secure Boot is disabled, especially if this is the first time you are running Proxmox on the machine.
