### ISSUE TITLE
build_container command not found

### ISSUE THREAD

**Issue by JimiHFord** [tteck/Proxmox#1221]
**Describe the issue**
It looks like the recent update broke something (going from debian-v5.sh to debian.sh)

**Screenshots**
<img width="673" alt="Screenshot 2023-03-22 at 7 03 47 PM" src="https://user-images.githubusercontent.com/1879448/227072480-2b7a03da-71f4-47af-a2cf-d7f52853aa0c.png">

**Comment by tteck** [comment]
I'm getting it also, working on it.

**Comment by tteck** [comment]
I can't find anything wrong!  `build_container` is there in the `debian.func` file. Everything was working in the next branch.

**Comment by JimiHFord** [comment]
I'm experimenting in my fork - we'll get to the bottom of this!

**Comment by tteck** [comment]
Ubuntu LXC works. 🤷🏻‍♂️

**Comment by JimiHFord** [comment]
very strange..

**Comment by tteck** [comment]
I'm lost for answers, I've looked over the code 100 times, can't find anything meaningful between `debian.func` and `ubuntu.func`, could it be something is up with github?

**Comment by JimiHFord** [comment]
I found the issue! I'm going to open up a PR

**Comment by tteck** [comment]
Direct to main branch

**Comment by tteck** [comment]
`ubuntu.func` and `docker.func` are working, while `alpine.func` and `debian.func` aren't. 🤷🏻‍♂️

**Comment by tteck** [comment]
now fix `alpine.func` lol

**Comment by JimiHFord** [comment]
@tteck lolol on it!!

**Comment by tteck** [comment]
found it

**Comment by tteck** [comment]
That was a rocky rollout. 😓

**Comment by JimiHFord** [comment]
it's all good! I'm going to open a PR that does some bash syntax checking - where would you like this? (I want to make sure that I stay the author if it gets merged to main)

**Comment by tteck** [comment]
I've noticed some pretty unusual things being submitted, so I've made it a rule that all pull requests should be directed to the pull-request branch instead of directly to the main branch. I'm not very familiar with how contributors work with Github.

**Comment by tteck** [comment]
This allows me an opportunity to review and test it before proceeding further.

**Comment by tteck** [comment]
It seems that if you make a commit to the pull-requests branch and I pull it into the main branch, you will be listed as a co-author. https://github.com/tteck/Proxmox/commit/f8c38b8177002b059d36c2dd826d514627b92232 I've noticed that Sergio is not listed in the contributors' list. Unfortunately, I don't know how to rectify this without pulling directly into the main branch, which I am hesitant to do.

**Comment by JimiHFord** [comment]
> It seems that if you make a commit to the pull-requests branch and I pull it into the main branch, you will be listed as a co-author. https://github.com/tteck/Proxmox/commit/f8c38b8177002b059d36c2dd826d514627b92232 I've noticed that Sergio is not listed in the contributors' list. Unfortunately, I don't know how to rectify this without pulling directly into the main branch, which I am hesitant to do.

Is there a pattern that lets you easily "temporarily" pull into a testing branch on a PR that targets main?
