### ISSUE TITLE
Container Default settings immediately errors after selecting default options (Multiple Scripts)

### ISSUE THREAD

**Issue by mon5termatt** [tteck/Proxmox#1225]
`Using Default Settings`
....
`Creating a NextCloudPi LXC using the above default settings`
` - Starting LXC Container...Configuration file 'nodes/mox/lxc/105.conf' does not exist`

`[ERROR] in line 422: exit code 255: while executing command pct start "$CTID"`

![image](https://user-images.githubusercontent.com/43628254/227116312-2f265ee9-ae97-4ead-9f1e-e2f99c0d308a.png)

**Comment by mon5termatt** [comment]
![image](https://user-images.githubusercontent.com/43628254/227117075-4b30c34e-330c-43bf-b82f-3ee9dfefb574.png)

**Comment by mon5termatt** [comment]
++ wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/dev/ct/create_lxc.sh
+ bash -c ''
+ LXC_CONFIG=/etc/pve/lxc/101.conf
+ '[' 1 == 0 ']'
+ '[' 1 == 0 ']'
+ msg_info 'Starting LXC Container'
+ local 'msg=Starting LXC Container'
+ echo -ne ' - \033[33mStarting LXC Container...'
 - Starting LXC Container...+ pct start 101
Configuration file 'nodes/prox/lxc/101.conf' does not exist
++ error_handler 422 'pct start "$CTID"'
++ local exit_code=255
++ local line_number=422
++ local 'command=pct start "$CTID"'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m422\033[m: exit code \033[01;31m255\033[m: while executing command \033[33mpct start "$CTID"\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m422\033[m: exit code \033[01;31m255\033[m: while executing command \033[33mpct start "$CTID"\033[m\n'

[ERROR] in line 422: exit code 255: while executing command pct start "$CTID"

**Comment by tteck** [comment]
fixed

**Comment by Esriel123** [comment]
I have the same or a similar Problem on the Wireguard LXC:

 ✓ LXC Container 106 was successfully created.
+ LXC_CONFIG=/etc/pve/lxc/106.conf
+ '[' 1 == 0 ']'
+ '[' 1 == 0 ']'
+ msg_info 'Starting LXC Container'
+ local 'msg=Starting LXC Container'
+ echo -ne ' - \033[33mStarting LXC Container...'
 - Starting LXC Container...+ pct start 106
run_buffer: 322 Script exited with status 5
lxc_init: 844 Failed to run lxc.hook.pre-start for container "106"
__lxc_start: 2027 Failed to initialize container "106"
startup for container '106' failed
++ error_handler 563 'pct start "$CTID"'
++ local exit_code=255
++ local line_number=563
++ local 'command=pct start "$CTID"'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m563\033[m: exit code \033[01;31m255\033[m: while executing command \033[33mpct start "$CTID"\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m563\033[m: exit code \033[01;31m255\033[m: while executing command \033[33mpct start "$CTID"\033[m\n'

[ERROR] in line 563: exit code 255: while executing command pct start "$CTID"

**Comment by Esriel123** [comment]
![Screenshot 2023-10-18 213439](https://github.com/tteck/Proxmox/assets/8888403/72cf1dcd-bbab-44e5-87a5-f47d13ac4449)

**Comment by Esriel123** [comment]
I got it working: it didn't like to be installed on a share

**Comment by zanagraf** [comment]
HellO, i've got the same error when try jellyfin and emby script. So i tried manual option, such as change the node name, but not better result.

I did full upgrade of my new (i'm a proxmox newbie) 8.2... but didn't work.

As i understood ssh was a bad idea, i did launch direct in navigator shell.
