### ISSUE TITLE
Node Red fails to install

### ISSUE THREAD

**Issue by Routout** [tteck/Proxmox#1226]
**Describe the issue**
Install with default settings

[ERROR] in line 422: exit code 255: while executing command pct start "$CTID"

**Comment by mon5termatt** [comment]
same

**Comment by mon5termatt** [comment]
its all scripts. somethings f*ked.

**Comment by Routout** [comment]
Proxmox task status:
`TASK ERROR: Configuration file 'nodes/pve/lxc/101.conf' does not exist`

**Comment by andremueller27** [comment]
same:

    ____  _______________  __      _       ____________ 
   / __ \/ ___/_  __/ __ \/ /_____| |     / / ____/ __ )
  / /_/ /\__ \ / / / /_/ / __/ __ \ | /| / / __/ / __  |
 / _, _/___/ // / / ____/ /_/ /_/ / |/ |/ / /___/ /_/ / 
/_/ |_|/____//_/ /_/    \__/\____/|__/|__/_____/_____/  
                                                        
Using Default Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 114
Using Hostname: rstptoweb
Using Disk Size: 4GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a RSTPtoWEB LXC using the above default settings
 - Starting LXC Container...Configuration file 'nodes/pve/lxc/114.conf' does not exist

[ERROR] in line 422: exit code 255: while executing command pct start "$CTID"

The Alpine Image works fine - all others that I have tested crash

**Comment by tteck** [comment]
fixed
