### ISSUE TITLE
 OMV script no longer completes

### ISSUE THREAD

**Issue by notHiks** [tteck/Proxmox#1238]
**Script hangs on installing OpenMedia Vault Patience**
Yesterday i was able to install omv but today i am no longer able to install as the script doesn't complete. .

**Screenshots**
![image](https://user-images.githubusercontent.com/66910081/227343591-d901075e-9b24-4bcc-955d-d6204b40f55f.png)

Its been on this screen now for 1.5 hours

Note: I did not update proxmox with the 22nd's build.

**Comment by tteck** [comment]
Run in Verbose mode to find what's hanging.

**Comment by notHiks** [comment]
running bash with -x didn't show much

![image](https://user-images.githubusercontent.com/66910081/227372751-609161b5-7b0f-4f4f-8a46-8efac703f901.png)

**Comment by tteck** [comment]
That's not verbose mode, go through Advanced settings to turn on.

**Comment by tteck** [comment]
Fixed https://github.com/tteck/Proxmox/commit/3abd2a9698a7cb3eb9d183d0eab1aed250bf9252
