### ISSUE TITLE
Alpine Vaultwarden - update error

### ISSUE THREAD

**Issue by larod241** [tteck/Proxmox#1242]
Hello, 
When I try to run the update script for the lxc alpine waultwarden, I get an error message: "⚠ User exited script "

I do use the site script: bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"

**Comment by tteck** [comment]
I am unable to reproduce the problem you are experiencing.

![Screenshot 2023-03-24 5 22 34 AM](https://user-images.githubusercontent.com/21342670/227478759-10c8c138-9f30-43f2-908c-e700ed6bec15.png)
![Screenshot 2023-03-24 5 23 17 AM](https://user-images.githubusercontent.com/21342670/227478806-14ff80d1-5f82-4cdd-a4ec-0f84654f19b3.png)

**Comment by tteck** [comment]
If the issue continues to persist, you may need to export your vaults, reinstall Alpine-Vaultwarden, and then import the exported vaults.

**Comment by larod241** [comment]
I re-create the alpine-vault Arden and import my vaults. 
It’s ok now. 
Very strange. 

Thanks for your work

**Comment by towerhand** [comment]
I got the same error with the alpine-adguard and alpine-grafana scripts. I will recreate it, but I figure to let you know @tteck.

**Comment by larod241** [comment]
Hum... 
Same for my Adguard Alpine CT to... there is a recent change that break something. I havent touch it for days !

**Comment by larod241** [comment]
<img width="916" alt="Capture d'écran 24 03 2023 à 17 54 57 PM" src="https://user-images.githubusercontent.com/20423481/227590717-a48096ad-b0a8-4b22-ad26-4e6a057aa454.png">
<img width="293" alt="Capture d'écran 24 03 2023 à 17 55 34 PM" src="https://user-images.githubusercontent.com/20423481/227590854-98e70a25-dbf8-461d-8fe5-4515ee6ede58.png">

**Comment by tteck** [comment]
The update portion now requires `apk add newt` for the whiptail menus

**Comment by larod241** [comment]
It dit the trick ! Thanks.

**Comment by tteck** [comment]
I'm going to add a check to see if `newt` is installed, if not, install it
