### ISSUE TITLE
Alpine-ESPHome LXC SSH Access for Root 

### ISSUE THREAD

**Issue by ntguest** [tteck/Proxmox#1254]
Remote access via ssh didn't works
![image](https://user-images.githubusercontent.com/69485846/227747849-a710de72-5fe0-474d-bb6c-7290fbbb4f6c.png)
settings
![image](https://user-images.githubusercontent.com/69485846/227747791-7f09016b-2cb7-46e9-a1b4-68d083ae5563.png)
only from console
![image](https://user-images.githubusercontent.com/69485846/227747824-123c2a23-9fac-482a-8a7f-bf4a890cd42e.png)

**Comment by tteck** [comment]
Run this command `sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" /etc/ssh/sshd_config` and reboot. Added to `alpine-install.func`

**Comment by ntguest** [comment]
thanks!
