### ISSUE TITLE
SSH check is broken

### ISSUE THREAD

**Issue by Reubertt** [tteck/Proxmox#1267]
/dev/fd/63: line 70: SSH_CLIENT: unbound variable
I don't know what it could be but I believe it's a problem with: misc/build.func
I was implementing a debian ct and it simply gave this error, I haven't tested if the error happens in other CTs.

**Comment by tteck** [comment]
Fixed https://github.com/tteck/Proxmox/commit/23d8d1b807038258cb4f62238d68aae9d291868d

**Comment by tteck** [comment]
Code fixed here https://github.com/tteck/Proxmox/commit/8bf03a6cb6d520094d6d659256291c9e934295fe so, `ssh_check` is back in use https://github.com/tteck/Proxmox/commit/b19b5e1039f38f4be9eefaa5872c9c32d577e609 Let me know if you have any issues.
