### ISSUE TITLE
VaultWarden LXC not updating.

### ISSUE THREAD

**Issue by xkpx64** [tteck/Proxmox#1270]
**Describe the issue** 
When using the provided cmd from your docs `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/vaultwarden.sh)"` 
It just flash the screen and outputs an error. Also tried with systemctl stop vaultwarden.
I'am using ArchLinux as base and so far no problems but this.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/5773378/228338400-1ecbacc6-f748-4229-9b48-01f6ce6cb680.png)

**Comment by tteck** [comment]
You're using the wrong script for Alpine-Vaultwarden, try

```
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"
```

**Comment by tteck** [comment]
Oh, you said Arch Linux not Alpine Linux, is this correct?

**Comment by xkpx64** [comment]
Yea, that's right, i tried Alpine Version too just in case but it's not working! Thanks for Fast Response Sir!

**Comment by tteck** [comment]
Unfortunately, there is no available solution for Arch Linux, as there is no installation path provided in this repository. However, in the case of Alpine-Vaultwarden, it is an `apk` package, so updating it is a straightforward process with the `apk update && apk upgrade` command.
