### ISSUE TITLE
Nginx Proxy Manager 2.10.1 crashes on upgrade with your script

### ISSUE THREAD

**Issue by jl-678** [tteck/Proxmox#1284]
The subject says it all. Your script is awesome and has worked perfectly for about a year. I just started to install 2.10.1, and the upgrade script throws no errors, but NPM refuses to run. When I check the log, I see the following repeated over and over:

```
Mar 31 17:27:02 npm systemd[1]: Started Nginx Proxy Manager.
Mar 31 17:27:02 npm node[280706]: [3/31/2023] [5:27:02 PM] [Global   ] › ℹ  info      Using Sqlite: /data/database.sqlite
Mar 31 17:27:02 npm node[280706]: [3/31/2023] [5:27:02 PM] [Global   ] › ℹ  info      Creating a new JWT key pair...
Mar 31 17:27:06 npm node[280706]: [3/31/2023] [5:27:06 PM] [Global   ] › ℹ  info      Wrote JWT key pair to config file: /data/keys.json
Mar 31 17:27:06 npm node[280706]: [3/31/2023] [5:27:06 PM] [Migrate  ] › ℹ  info      Current database version: none
Mar 31 17:27:08 npm node[280706]: [3/31/2023] [5:27:08 PM] [Global   ] › ✖  error     Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-
cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') cloudflare && deactivate
Mar 31 17:27:08 npm node[280706]: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
At this point NPM becomes unreachable. I cannot access the GUI and all reverse proxying fails too. The only solution I have found is to roll back to 2.9.22. (I snap the container before the upgrade.)

It seems that other people are having NPM problems too but many of those relate to MySQL. It also seems that permissions can be a challenge and so I am not sure if that is related to this.

TIA!

**Comment by tteck** [comment]
Try updating to v2.10.2 https://github.com/tteck/Proxmox/discussions/1282

**Comment by tteck** [comment]
My plan is to restrict the script to version 2.9.22, while any subsequent versions will undergo testing in the dev branch.

**Comment by jl-678** [comment]
Okay, thank you. I am going to hold off testing anything related to 2.10 until you qualify the 2.10.x branch. Will you let us know when the process is complete?

**Comment by nicedevil007** [comment]
tteck already updated the script on the dev branch, try it instead, it is working on multiple tests on my site:

```python
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/dev/ct/nginxproxymanager.sh)"
```

**Comment by tteck** [comment]
Now in the main branch.

**Comment by wokkeltje13** [comment]
I updated my instance and to version 2.10.2 but still the same issue: bad gateway
I read a lot of solutions regarding filesecurity on the mysql folder, but I can't find this folder. 
Am I missing something or how do you fix the latest nginx version?

**Comment by nicedevil007** [comment]
> I updated my instance and to version 2.10.2 but still the same issue: bad gateway I read a lot of solutions regarding filesecurity on the mysql folder, but I can't find this folder. Am I missing something or how do you fix the latest nginx version?

I have 5 instances running on my own nodes or on my friends nodes that were installed with the script from tteck and all of them work great after the update.
they can be rebootet and can receive new LetsEncrypt Certificates.

if I'm correct tteck isn't using the mysql database instead he is using sql-lite on his instance.

just take a look at line 142
https://github.com/tteck/Proxmox/blob/main/install/nginxproxymanager-install.sh

**Comment by wokkeltje13** [comment]
I changed the security on the file /data/database.sqlite without any difference.
proxy seems to be working (sites are accessible), but can't login to admin page. Keep getting "Bad Gateway", revert back to previous version and everything is working again.

When installing a new LXC, I can logon, maybe I need to just start over, 14 hosts is not that much config.

Why does the script not use the install procedure of the developer with the same DB engine?

**Comment by tteck** [comment]
Try running this command in the LXC console 
```
sed -i 's/include-system-site-packages = false/include-system-site-packages = true/g' /opt/certbot/pyvenv.cfg
```

**Comment by wokkeltje13** [comment]
tnx a lot, this solved the issue.

Can you explain what was wrong with my setup?

**Comment by tteck** [comment]
It just needed the Python interpreter to include packages installed in the global site-packages.

**Comment by jl-678** [comment]
Just to confirm, 2.10.2 installed fine, and I had the same GUI issue. The "sed" command above fixed the problem. TY!

**Comment by tteck** [comment]
The above `sed` command is now in the install/update script.

**Comment by LeidenSpain** [comment]
Hi,

I have the same version of NPM since I installed it (2.9.19).
What is the correct method to update it?

**Comment by tteck** [comment]
From the instructions:

![Screenshot 2023-04-16 10 08 57 AM](https://user-images.githubusercontent.com/21342670/232318753-23253c90-5760-4136-9a7d-bf37defb7210.png)

**Comment by LeidenSpain** [comment]
> From the instructions:
> 
> ![Screenshot 2023-04-16 10 08 57 AM](https://user-images.githubusercontent.com/21342670/232318753-23253c90-5760-4136-9a7d-bf37defb7210.png)

Sorry, I saw it later and that's why I deleted the question
thank you

**Comment by LeidenSpain** [comment]
To provide information:
running the script, and after waiting 10 minutes, the update looks like this:
![image](https://user-images.githubusercontent.com/45803748/232320085-196a9534-be17-4a41-983c-0a9d16207e7c.png)

After executing the command
`sed -i 's/include-system-site-packages = false/include-system-site-packages = true/g' /opt/certbot/pyvenv.cfg`
the same thing keeps happening

Any information I can give, ask me.

Regards


P.D.:
I just tried on another computer, with another line and another router, and it has worked for me.
I'll see what happens, but it seems to be something particular to my installation
