### ISSUE TITLE
Wrong configuration.yaml location for alpine-zigbee2mqtt.sh

### ISSUE THREAD

**Issue by diginatrium** [tteck/Proxmox#1294]
While trying to start zigbee2mqtt following the guide here https://tteck.github.io/Proxmox/ I get the following error:

Error: ENOENT: no such file or directory, open '/root/.z2m/configuration.yaml'

Solved the issue by creating a symlink from '/root/.z2m/'
 to '/etc/zigbee2mqtt/' mentioned in the tutorial.

Thought it might be worth to bring attention to it.

**Comment by tteck** [comment]
Thank you!

**Comment by manoloxxl** [comment]
Is it 

ln -s /root/.z2m/ /etc/zigbee2mqtt/


or

ln -s /etc/zigbee2mqtt/ /root/.z2m/

?

**Comment by manoloxxl** [comment]
It seems to be

ln -s /etc/zigbee2mqtt ~/.z2m

But still getting:
ln: /root/.z2m/zigbee2mqtt: File exists


And:
Error: ENOENT: no such file or directory, open '/root/.z2m/configuration.yaml'


Overall it seems that the Alpine Linux Zigbee2mqtt image is not working :(
