### ISSUE TITLE
Trying to install VS Code Server gives: "Can't Install on Proxmox"

### ISSUE THREAD

**Issue by wattsie** [tteck/Proxmox#1296]
Hi,
Awesome Repo...
Was going to quickly tried out VS Code Server, so tried to install [VS Code Server](https://code.visualstudio.com/docs/remote/vscode-server) as per [link](https://tteck.github.io/Proxmox/) using your script in the LXC console like many other of your awesome scripts, however fails with `"Can't Install on Proxmox" `
Executed: `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/code-server.sh)"`
Wondering if this is by design?
Have installed on a spare instance at the moment.

Sorry, lost the rest of the message.
The rest of the question was to look at the steps needed to use your scripts to build a container and complete the install like all the other excellent examples you have.

Many thanks.
Cheers.

**Comment by tteck** [comment]
The purpose is to carry out an installation on an already existing LXC container.
Hence "⚠️ run the command below in the LXC console."
