### ISSUE TITLE
Deployments throw erroneous 'internet not connected' error with IPv6 DHCP address

### ISSUE THREAD

**Issue by Coder84619** [tteck/Proxmox#1309]
**Describe the issue**
When deploying the Grafana LXC (not Apline) using DHCP, the install script shows an IPv6 address (which is fine, I have DHCPv6 enabled). However, it immediate gives me an "internet NOT connected" warning, I proceed anyway, DNS works fine and the install completes as normal. So it appears the internet detection logic has a bug. 

![image](https://user-images.githubusercontent.com/30213019/230747281-848cf434-4e2b-4996-95f2-f7ce7ec855a3.png)

**Comment by tteck** [comment]
```
  if ping -c 1 -W 1 1.1.1.1 &>/dev/null; then msg_ok "Internet Connected"; else
    msg_error "Internet NOT Connected"
    read -r -p "Would you like to continue anyway? <y/N> " prompt
    if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
      echo -e " ⚠️  ${RD}Expect Issues Without Internet${CL}"
    else
      echo -e " 🖧  Check Network Settings"
      exit 1
    fi
  fi
```
The provided code snippet does not specifically depend on IPv4 or IPv6, as it uses the IP address `1.1.1.1`, which can be accessed over both protocols. Therefore, it should work with IPv6 as well as IPv4, as long as the network connectivity is properly established over the chosen protocol.

**Comment by tteck** [comment]
It seems that the code checks for internet connectivity before your network has fully established a connection, resulting in a false negative.

**Comment by tteck** [comment]
Just a note, IPv6 uses a larger address space than IPv4, which can make it more complex to handle and process. This can result in longer processing times and slower connection establishment.

**Comment by Coder84619** [comment]
I would humbly suggest that if an IPv6 address is found then add a short wait (say 5 seconds) to allow the network to come up. I never see this delay issue with IPv4 DHCP addresses. Or, add logic that if the ping fails, wait 5 seconds and try again..then if that fails display a warning.

**Comment by tteck** [comment]
Does the command `hostname -I` when executed in the LXC console show both the IPv6 & IPv4 address?
