### ISSUE TITLE
Sonarr LXC script : Unable to add root folder Folder is not writable by user sonarr

### ISSUE THREAD

**Issue by KevinBoone90** [tteck/Proxmox#1315]
Created a Priviliged container with the LXC script and when trying to map a mounted drive, I get the following error:
Unable to add root folder Folder is not writable by user sonarr

I just installed Radarr via the exact same way without an issue, same for SABnzb
Mapped drives are visible and accessible 

![image](https://user-images.githubusercontent.com/89245209/230794444-093bf648-d30f-43cc-834e-65245e2b5ec5.png)

![image](https://user-images.githubusercontent.com/89245209/230794462-bb30cc31-fe3a-42f1-be22-aaae4dac9c6f.png)

![image](https://user-images.githubusercontent.com/89245209/230794520-22a9490e-d2c9-4b29-86b7-473193fb7724.png)

![image](https://user-images.githubusercontent.com/89245209/230794585-f545d8f4-fc49-4aaa-a77d-e0b7652bc3e7.png)

**Comment by KevinBoone90** [comment]
Also noticed the Sonarr CT is using the dev branch - might not be related. Radarr one is production version

![image](https://user-images.githubusercontent.com/89245209/230794697-295a6e1e-6f95-4764-b1e5-f37a8b55bd18.png)
![image](https://user-images.githubusercontent.com/89245209/230794719-3736f0d7-4125-4cfe-a951-d6ccf750defd.png)

**Comment by KevinBoone90** [comment]
moved to discussions

**Comment by freetextmike** [comment]
anycomments here?
same issue on sonarrr

**Comment by tteck** [comment]
@freetextmike https://github.com/tteck/Proxmox/discussions?discussions_q=sonarr

**Comment by freetextmike** [comment]
thanks tteck !

**Comment by vikdb** [comment]
Did you find a solution?
