### ISSUE TITLE
Fresh installation of Hassio VM on proxmox not work

### ISSUE THREAD

**Issue by twiti7** [tteck/Proxmox#1317]
I install fresh latest proxmox and used latest hassio 9.5 and it want boot

**Comment by tteck** [comment]
Did you ensure that UEFI Boot & Virtualization is enabled and Secure Boot is disabled in your machine’s BIOS?

**Comment by twiti7** [comment]
yes virtualization is enabled UEFI too and secure boot disabled

**Comment by tteck** [comment]
Tell me about your machine specs.

**Comment by twiti7** [comment]
It is DELL WYSE ZX0 Z90D7 1.65GHZ  8192 MB of RAM and 128 GB SSD. Everything was fine until I mage update of proxmox. So I try made fresh install and get all stuff from backup but now I can't start even Hassio.
It looks like here https://github.com/home-assistant/operating-system/issues/2357
