### ISSUE TITLE
Sonarr LXC script : Unable to add root folder Folder is not writable by user sonarr

### ISSUE THREAD

**Issue by KevinBoone90** [tteck/Proxmox#1321]
### Discussed in https://github.com/tteck/Proxmox/discussions/1316

<div type='discussions-op-text'>

<sup>Originally posted by **KevinBoone90** April  9, 2023</sup>
Hi all,

I Created a Privileged container with the LXC script and when trying to map a mounted drive, I get the following error:
Unable to add root folder Folder is not writable by user sonarr

I just installed Radarr via the exact same way without an issue, same for SABnzb
Mapped drives are visible and accessible 

![image](https://user-images.githubusercontent.com/89245209/230794444-093bf648-d30f-43cc-834e-65245e2b5ec5.png)

![image](https://user-images.githubusercontent.com/89245209/230794462-bb30cc31-fe3a-42f1-be22-aaae4dac9c6f.png)

![image](https://user-images.githubusercontent.com/89245209/230794520-22a9490e-d2c9-4b29-86b7-473193fb7724.png)

![image](https://user-images.githubusercontent.com/89245209/230794585-f545d8f4-fc49-4aaa-a77d-e0b7652bc3e7.png)

Also noticed the Sonarr CT is using the dev branch - might not be related. Radarr one is production version

![image](https://user-images.githubusercontent.com/89245209/230794697-295a6e1e-6f95-4764-b1e5-f37a8b55bd18.png)
![image](https://user-images.githubusercontent.com/89245209/230794719-3736f0d7-4125-4cfe-a951-d6ccf750defd.png)

Anyone know how to go from here or experiencing the same issues? Kind of new with Linux and Proxmox but eager to learn.

Thanks in advance
</div>

**Comment by tteck** [comment]
If this topic is already being discussed in the Discussions section, what is the reason for creating a new issue?

**Comment by KevinBoone90** [comment]
Sorry, created an issue to make you aware since other people had similar issues with root access to mounted drives. Thought I'd provide some info on the Dev branch as well
