### ISSUE TITLE
Installing Cronicle Primary Server...bash: line 43: SERV: unbound variable

### ISSUE THREAD

**Issue by nebakineza** [tteck/Proxmox#1322]
**Describe the issue**
Trying to install Cronicle Primary via PMX shell (via default and advanced method - unpriv & priv container types). All variations throw unbound var: 

`Installing Cronicle Primary Server...bash: line 43: SERV: unbound variable`

Tried on three nodes running Linux 5.15.104-1-pve {#}1 SMP PVE 5.15.104-1 (pve-7.4-3).

Please ask if any more information is required.

**Screenshots**
![image](https://user-images.githubusercontent.com/18736418/230871537-935a947e-1de1-4718-a178-46bfe32be37b.png)

**Comment by tteck** [comment]
fixed

**Comment by nebakineza** [comment]
Thank you for the quick fix.
