### ISSUE TITLE
Whoogle lxc update

### ISSUE THREAD

**Issue by anoo2niem** [tteck/Proxmox#1323]
**Describe the issue**
Currently running a whoogle lxc on 0.8.1, my instance is telling me there is an update available to 0.8.2.
Trying the script on my whoogle lxc;
 ✓ Updated Whoogle LXC
 ✓ Update Successfull

But still staying on 0.8.1.
I was under the impression that your scripts directly pull the latest build from the github page, if not, excuse me for the impatience. 

Thank u btw for providing these convenient scripts.

**Comment by tteck** [comment]
https://github.com/benbusby/whoogle-search/issues/982

**Comment by rollingafull** [comment]
whoogle 0.8.2 is not on pip repository also.

https://pypi.org/project/whoogle-search/

**Comment by tteck** [comment]
Since this problem is not related to the script, it is now considered closed.
