### ISSUE TITLE
Install script for Homepage doesn't work on fresh LXC

### ISSUE THREAD

**Issue by Seexelas** [tteck/Proxmox#1338]
**Describe the issue** :
When exucting the script on a Debian LXC container, I receive the error below.

*Screenshots** : ![image](https://user-images.githubusercontent.com/64669806/232329248-643e4221-9999-4b78-a03c-42fe067fc793.png)

Many thanks for the help,

Best regards,

Alexis

**Comment by tteck** [comment]
That's not how the script works.
Follow the instructions to install Homepage at https://tteck.github.io/Proxmox/

**Comment by Seexelas** [comment]
Oh ok, I understand my mistake... very sorry and thanks for the help :)
