### ISSUE TITLE
InfluxDB Script throws error

### ISSUE THREAD

**Issue by zee00100** [tteck/Proxmox#1354]
I get the following error when running the InfluxDB Script:

++ sed -n 's/.*\(debian-11.*\)/\1/p'
++ sort -t - -k 2 -V
+ '[' 1 -gt 0 ']'
+ TEMPLATE=debian-11-standard_11.6-1_amd64.tar.zst
+ pveam list local
+ grep -q debian-11-standard_11.6-1_amd64.tar.zst
+ DEFAULT_PCT_OPTIONS=(-arch $(dpkg --print-architecture))
++ dpkg --print-architecture
+ PCT_OPTIONS=(${PCT_OPTIONS[@]:-${DEFAULT_PCT_OPTIONS[@]}})
+ [[  -features keyctl=1,nesting=1 -hostname influxdb -net0 name=eth0,bridge=vmbr0,ip=dhcp -onboot 1 -cores 2 -memory 2048 -unprivileged 1 -password e0g26s7g  =~  -rootfs  ]]
+ PCT_OPTIONS+=(-rootfs $CONTAINER_STORAGE:${PCT_DISK_SIZE:-8})
+ msg_info 'Creating LXC Container'
+ local 'msg=Creating LXC Container'
+ echo -ne ' - \033[33mCreating LXC Container...'
 - Creating LXC Container...+ pct create 106 local:vztmpl/debian-11-standard_11.6-1_amd64.tar.zst -features keyctl=1,nesting=1 -hostname influxdb -net0 name=eth0,bridge=vmbr0,ip=dhcp -onboot 1 -cores 2 -memory 2048 -unprivileged 1 -password e0g26s7g -rootfs local-lvm:8
unable to create CT 106 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - --zstd --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/106/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 2
+ exit 'A problem occured while trying to create container.'
bash: line 137: exit: A problem occured while trying to create container.: numeric argument required
+ exit

**Comment by tteck** [comment]
No issue here

```
    ____      ______           ____  ____ 
   /  _/___  / __/ /_  ___  __/ __ \/ __ )
   / // __ \/ /_/ / / / / |/_/ / / / __  |
 _/ // / / / __/ / /_/ />  </ /_/ / /_/ / 
/___/_/ /_/_/ /_/\__,_/_/|_/_____/_____/  
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: 4-20-2023
Container ID: 113
Using Hostname: influxdb
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a InfluxDB LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up InfluxDB Repository
Which version of InfluxDB to install? (1 or 2) 2
 ✓ Installed InfluxDB
Would you like to add Telegraf? <y/N> 
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by tteck** [comment]
Try deleting the Debian 11 template (debian-11-standard_11.6-1_amd64.tar.zst) and let the script re-download it.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is now considered closed.
