### ISSUE TITLE
Plex script doesn't set apt signing key

### ISSUE THREAD

**Issue by lightmaster** [tteck/Proxmox#1359]
### A clear and concise description of the issue.

The Plex LXC script creates the keyring `/usr/share/keyrings/plexmediaserver.gpg`, but it does not set the apt source to use this keyring, resulting in this error message when updating packages in the LXC:

```
W: https://downloads.plex.tv/repo/deb/dists/public/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

### Please provide detailed steps to reproduce the issue.

1. Create Plex LXC using script
2. Access via console and try to update apt with `apt update`

**Comment by tteck** [comment]
```
root@plex:~# apt update
Hit:1 https://downloads.plex.tv/repo/deb public InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@plex:~# 
```
What am I missing?

**Comment by tteck** [comment]
https://support.plex.tv/articles/235974187-enable-repository-updating-for-supported-linux-server-distributions/
I see no changes. 🤷🏻‍♂️

**Comment by tteck** [comment]
Oh, you're using 22.04, try `mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d/`

**Comment by tteck** [comment]
https://manpages.debian.org/testing/apt/apt-key.8.en.html

fixed
