### ISSUE TITLE
Prometheus  tar file left after installation

### ISSUE THREAD

**Issue by MasterCATZ** [tteck/Proxmox#1360]
### A clear and concise description of the issue.

prometheus-2.43.0.linux-amd64.tar.gz  ~80mb
is still sitting there after installation
I would have thought this to be cleaned up after instalation 

rm -rf /root/prometheus-${RELEASE}.linux-amd64 /root/prometheus-${RELEASE}.linux-amd64.tar.gz

seems to miss it because it's in the / instead of in /root ? 

```
mkdir -p /etc/prometheus
mkdir -p /var/lib/prometheus
$STD wget https://github.com/prometheus/prometheus/releases/download/v${RELEASE}/prometheus-${RELEASE}.linux-amd64.tar.gz
$STD tar -xvf prometheus-${RELEASE}.linux-amd64.tar.gz
cd prometheus-${RELEASE}.linux-amd64
```

I guess adding cd /root was missed? 
```
mkdir -p /var/lib/prometheus
cd /root
$STD wget https://github.com/prometheus/prometheus/releases/download/v${RELEASE}/prometheus-${RELEASE}.linux-amd64.tar.gz
```

**Comment by tteck** [comment]
fixed
