### ISSUE TITLE
Update Zigbee2Mqtt on Alpine Linux LXC

### ISSUE THREAD

**Issue by julred** [tteck/Proxmox#1362]
### A clear and concise description of the issue.

I'd like to update to the latest zigbee2mqtt version (1.30).
I'm actually on V1.28
But I dont find any tutorial how to proceed this in Alpine Linux LXC

**Comment by tteck** [comment]
The latest available [package version](https://pkgs.alpinelinux.org/packages?name=zigbee2mqtt&branch=edge&repo=&arch=&maintainer=) is 1.28.2, and it will remain so until the maintainer releases an update.

**Comment by julred** [comment]
Can i manually Update to v1.30?

**Comment by tteck** [comment]
Not that I know of
