### ISSUE TITLE
Grocy Script Error

### ISSUE THREAD

**Issue by Chacsam** [tteck/Proxmox#1364]
## Config ##
Selected advanced parameters:
- Ubuntu 22.04
- 512Mb RAM
- 2Gb disk scape
- A fixed IP

## Feedback ##
` ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.11.222 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Installing PHP 8.1...
[ERROR] in line 22: exit code 100: while executing command "$@" > /dev/null 2>&1
`

Default Apache page is end result

**Comment by Chacsam** [comment]
Note: I just tried again with debian as OS instead of ubuntu and the script worked fine

**Comment by tteck** [comment]
> Advanced settings provide the option for users to switch between Debian and Ubuntu distributions. However, some applications or services, such as Deconz or Omada, may not be compatible with the selected distribution due to dependencies.

https://github.com/tteck/Proxmox/issues/914#issuecomment-1381763061
