### ISSUE TITLE
https://www.helper-scripts.com/

### ISSUE THREAD

**Issue by rstuke82** [tteck/Proxmox#1366]
Website https://www.helper-scripts.com/ is not working.  I just get a github 404 error.  Previous URL https://tteck.github.io/Proxmox just redirects to this same error.

![image](https://user-images.githubusercontent.com/16128402/234610796-569dcf34-fcb9-4baa-9c3a-e3cf45f89da1.png)

**Comment by takouhai** [comment]
This is probably because the `www` subdomain isn't pointing to `helper-scripts.com`. `helper-scripts.com` works and redirects to `https://tteck.github.io/Proxmox/`.

**Comment by tteck** [comment]
_Should_ be resolved now.

**Comment by takouhai** [comment]
Can confirm, visited in an incognito window and it worked just fine now. 👍

**Comment by tteck** [comment]
Thanks for reporting this!
