### ISSUE TITLE
nginx proxy manager stop after every restart 

### ISSUE THREAD

**Issue by anoureldin** [tteck/Proxmox#1368]
### A clear and concise description of the issue.

hello 
i restart the npm container it's stop 
i must update it to start again

**Comment by tteck** [comment]
Once you have rebooted the LXC, verify the status of the openresty and npm services using the commands `systemctl status openresty` and `systemctl status npm`.

**Comment by anoureldin** [comment]
root@nginxproxymanager:~#  systemctl status openresty 
* openresty.service - The OpenResty Application Platform
     Loaded: loaded (/lib/systemd/system/openresty.service; enabled; vendor preset: enabled)
     Active: inactive (dead)





root@nginxproxymanager:~# systemctl status npm
* npm.service - Nginx Proxy Manager
     Loaded: loaded (/lib/systemd/system/npm.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-05-19 10:09:46 UTC; 31s ago
    Process: 124 ExecStartPre=mkdir -p /tmp/nginx/body /data/letsencrypt-acme-challenge (code=exited, status=0/SU>
   Main PID: 126 (node)
      Tasks: 13 (limit: 76947)
     Memory: 71.5M
        CPU: 1.039s
     CGroup: /system.slice/npm.service
             |-126 /usr/bin/node index.js --abort_on_uncaught_exception --max_old_space_size=250
             |-143 /bin/sh -c certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --work-dir >
             `-144 /usr/bin/python3 /usr/local/bin/certbot renew --non-interactive --quiet --config /etc/letsencr>

May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [Setup    ] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [Setup    ] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [IP Ranges] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [IP Ranges] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [IP Ranges] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [IP Ranges] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [SSL      ] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [SSL      ] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [IP Ranges] <E2><80><BA> <E2><84><B9>  inf>
May 19 10:09:47 nginxproxymanager node[126]: [5/19/2023] [10:09:47 AM] [Global   ] <E2><80><BA> <E2><84><B9>  inf

**Comment by anoureldin** [comment]
also this problem happened after i add new network to LXC container

**Comment by anoureldin** [comment]
i start it with systemctl start openresty

but it take 3-5 minute to start

**Comment by tteck** [comment]
What version are you running?

**Comment by anoureldin** [comment]
nginx version: openresty/1.21.4.1
