### ISSUE TITLE
New Feature - Frigate 2 Container

### ISSUE THREAD

**Issue by diginfo** [tteck/Proxmox#1371]
### A clear and concise description of the issue.

Any plans to create a container for the latest frigate: https://github.com/blakeblackshear/frigate

**Comment by diginfo** [comment]
I already searched the issues before submitting: https://github.com/tteck/Proxmox/issues?q=frigate

All it came up with was this: https://github.com/tteck/Proxmox/issues/1331

And it did not seem relevant ?!

**Comment by tteck** [comment]
- If you have requests for features or scripts, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
