### ISSUE TITLE
docker LXC script fails

### ISSUE THREAD

**Issue by cpuks** [tteck/Proxmox#1372]
While trying to get new LCX container up and running I got this error:
```
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 0
Using Root Password: xxx
Container ID: 201
Using Hostname: docker-video
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Fuse Overlayfs (ZFS): yes
Enable Verbose Mode: no
Creating a Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using nvme for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 201 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.88.244 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies

[ERROR] in line 26: exit code 1: while executing command DOCKER_LATEST_VERSION=$(get_latest_release "moby/moby")
```

**Comment by tteck** [comment]
No issue here.

```
    ____             __            
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 0
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: docker
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Fuse Overlayfs (ZFS): no
Enable Verbose Mode: no
Creating a Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker v23.0.5
Would you like to add Portainer? <y/N> y
 ✓ Installed Portainer 2.18.1
Would you like to add Docker Compose? <y/N> y
 ✓ Installed Docker Compose v2.17.3
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by cpuks** [comment]
I've tried twice no luck - now after your msg it works - sorry but I didn't made this up - rebuilding system on new NUC but it's a few days since I pulled anything so no quotas hit or anything - let me work tonight and I'll post if I had any problems. Thanks

**Comment by tteck** [comment]
Since this issue is not related to the script, it is now considered closed.

**Comment by tteck** [comment]
Typically, the error you've provided suggests the presence of DNS problems, or github api issues.

The `DOCKER_LATEST_VERSION=$(get_latest_release "moby/moby")` command is purely informative and does not download anything.

This is the code snippet, with additional `echo` commands to verify the output.
```
get_latest_release() {
  curl -sL https://api.github.com/repos/$1/releases/latest | grep '"tag_name":' | cut -d'"' -f4
}

DOCKER_LATEST_VERSION=$(get_latest_release "moby/moby")
echo -e "Docker $DOCKER_LATEST_VERSION"
PORTAINER_LATEST_VERSION=$(get_latest_release "portainer/portainer")
echo -e "Portainer $PORTAINER_LATEST_VERSION"
DOCKER_COMPOSE_LATEST_VERSION=$(get_latest_release "docker/compose")
echo -e "Compose $DOCKER_COMPOSE_LATEST_VERSION"
```

**Comment by tteck** [comment]
By the way, I introduced the option to switch Linux distributions partly due to the Docker LXC, as some users favor Ubuntu over Debian. Glad to see the option is getting utilized.

**Comment by tylerobara** [comment]
> By the way, I introduced the option to switch Linux distributions partly due to the Docker LXC, as some users favor Ubuntu over Debian. Glad to see the option is getting utilized.

I just ran into this problem. After some testing, I noticed I was getting the following feedback from the command used in `get_latest_release` function
`curl -sL https://api.github.com/repos/docker/compose/releases/latest`

`{"message":"API rate limit exceeded for <MY IP>...."}`
Because the error response from GitHub does not contain `tag_name`, the get_latest_release function fails. When I find some time I will see about submitting a PR with a way to handle this response. The error goes on to say authenticated requests have higher rate limits so maybe there is a solution that includes that while retaining the ease of use for the scripts

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/1156

Run this to check version:
```
get_latest_release() {
  curl -sL https://api.github.com/repos/$1/releases/latest | grep '"tag_name":' | cut -d'"' -f4
}
DOCKER_LATEST_VERSION=$(get_latest_release "moby/moby")
echo "$DOCKER_LATEST_VERSION"
```

The command in the script, `sh <(curl -sSL https://get.docker.com)` will install the latest release

**Comment by GregHilston** [comment]
@tylerobara I'm experiencing the same API rate limit issue as you. Did you or @tteck have a recommended work around for this?

**Comment by tylerobara** [comment]
> @tylerobara I'm experiencing the same API rate limit issue as you. Did you or @tteck have a recommended work around for this?

Pretty sure I narrowed it down to Frigate, I killed it and DNS requests for GitHub went way down per PiHole. Not faulting frigate, I could have misconfigured something. Haven't gone back to properly troubleshoot.

**Comment by GregHilston** [comment]
@tylerobara I'm glad you mentioned this, as I'm trying to run this tteck proxmox LXC container to reinstall frigate. I have a `frigate` container running on my network as well, so i bet that's what's using my API calls.

Funny enough, I am also running pihole and just looked at the `Top permitted Domains`, and sure enough Github is at the top...

![image](https://github.com/tteck/Proxmox/assets/4227776/0c9d504d-7d8e-4eca-9d51-fd47e50858b4)

---

I solved this by killing my frigate application, and waiting 20m.
