### ISSUE TITLE
Alpine Zigbee2MQTT - unable to update

### ISSUE THREAD

**Issue by ohmgh** [tteck/Proxmox#1375]
Initially it only showed "User exited script". Searching past issues, added newt package as advised. Now it runs but only offers one option to check for update(as opposed to actually updating), and running that option doesn't seem to update at all:

bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-zigbee2mqtt.sh)"

![image](https://user-images.githubusercontent.com/49562013/235288686-561a6677-f874-4681-807b-ed6d056e8809.png)
![image](https://user-images.githubusercontent.com/49562013/235288721-237b0be9-4f8c-4f8e-93ca-6aad2a386cdd.png)
![image](https://user-images.githubusercontent.com/49562013/235288796-dca725c0-ee92-4c90-bd3a-77186c0394ff.png)

Any ideas? Thanks!

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/1362
