### ISSUE TITLE
paperless-ngx incorrect user:pass provided by script

### ISSUE THREAD

**Issue by aleguiss** [tteck/Proxmox#1376]
### A clear and concise description of the issue.

Installation completed successfully. Container starts, WebUI launches, script provides user:pass combination, WebUI login fail.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="640" alt="Screen Shot 2023-04-30 at 18 10 57 pm" src="https://user-images.githubusercontent.com/26011927/235366643-7fcd2e3b-cd01-4a7a-9417-b0466b6f1933.png">
<img width="489" alt="Screen Shot 2023-04-30 at 18 10 36 pm" src="https://user-images.githubusercontent.com/26011927/235366645-ce73c251-7e4e-43c6-ad6a-c75393282326.png">

### Please provide detailed steps to reproduce the issue.

Install LXC.
Acquire user:pass from script.
Try to login.

**Comment by tteck** [comment]
fixed
