### ISSUE TITLE
UptimeKuma Update script not running in LXC

### ISSUE THREAD

**Issue by nelssimo** [tteck/Proxmox#1380]
### A clear and concise description of the issue.

When I run the update script in the lxc it doesn't do anything it just skips to the next line.
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/uptimekuma.sh)"

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2023-05-01 at 8 50 37 PM](https://user-images.githubusercontent.com/66102389/235556530-6c14a9db-65aa-434e-9002-158ddde08859.png)

**Comment by tteck** [comment]
Network issues...
No problems here

![Screenshot 2023-05-01 8 54 43 PM](https://user-images.githubusercontent.com/21342670/235557088-5e8f5f0d-e8dd-4d80-8adc-7b8df1aa48a5.png)

**Comment by nelssimo** [comment]
Thanks for checking. I ended up recreating a new lxc instead.
