### ISSUE TITLE
Installation Error Paperless-NGX [ERROR] in lin 22: exit code 1: while executing command "$@" > /dev/null 2>&1

### ISSUE THREAD

**Issue by Schatten123** [tteck/Proxmox#1386]
### A clear and concise description of the issue.

Hello, during the installation of paperlessngx I get the following error message:

[ERROR] in lin 22: exit code 1: while executing command "$@" > /dev/null 2>&1

What am I doing wrong? can you help me this?

![asdasdasd](https://user-images.githubusercontent.com/3287351/235990696-fa08e40b-feeb-4cbb-b832-5bf177a939f8.jpg)

Thank you. :)

**Comment by rcwsr** [comment]
@Schatten123 how did you resolve this?
