### ISSUE TITLE
nginxproxymanager.sh update 

### ISSUE THREAD

**Issue by IT-Yohan** [tteck/Proxmox#1389]
### A clear and concise description of the issue.

Hello,
First, thank you a lot for your work. 

Since this [commit](https://github.com/tteck/Proxmox/commit/13e65979ee9d467798fdac89f9065f46827769b4) two weeks ago, the update process fail on my nginxproxy LXC.

Since the failure, even after reverting the commit, the script fail.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

The error is the following : 
`[ERROR] in line 168: exit code 1: while executing command systemctl enable -q --now openresty`

The command seems to run fine when not in the script context, i ran it as root.

After reverting the systemctl start openresty command shows : 
`May 03 22:49:39 nginxproxymanager systemd[1]: Starting The OpenResty Application Platform...
May 03 22:49:39 nginxproxymanager nginx[616]: nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-8/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsenc>
May 03 22:49:39 nginxproxymanager nginx[616]: nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
May 03 22:49:39 nginxproxymanager systemd[1]: openresty.service: Control process exited, code=exited, status=1/FAILURE
May 03 22:49:39 nginxproxymanager systemd[1]: openresty.service: Failed with result 'exit-code'.
May 03 22:49:39 nginxproxymanager systemd[1]: Failed to start The OpenResty Application Platform.`

### Please provide detailed steps to reproduce the issue.

run the : `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"` command.

**Comment by tteck** [comment]
That commit shouldn't affect anything.

```
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________ __  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                                      /____/                            /____/             
 
 ✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.10.2
 ✓ Setup Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Started Services
 ✓ Cleaned
 ✓ Updated Successfully
root@nginxproxymanager:~# 
```

**Comment by IT-Yohan** [comment]
Yeah the problem seems to be on my end then.
Thank you nonetheless

**Comment by tteck** [comment]
what does `nano /usr/local/openresty/nginx/conf/nginx.conf` show? (first 4 lines)

**Comment by IT-Yohan** [comment]
openresty nginx.conf :

``` 
# run nginx in foreground
#daemon off;
#pid /run/nginx/nginx.pid;
user root;
```

**Comment by tteck** [comment]
Looks correct. 🤷🏻‍♂️

**Comment by IT-Yohan** [comment]
Seems to be linked to [this](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/574).
It's late here i will try to fix it tomorow and post the fix there.

In any case thank you for your implication and quick support :)
