### ISSUE TITLE
Unable to update influxdb container

### ISSUE THREAD

**Issue by EnRav** [tteck/Proxmox#1391]
### A clear and concise description of the issue.

If I run the script `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/influxdb.sh)"` a an LCX container shell that was created by the script I got the message "No Influx installation found"

### Please provide detailed steps to reproduce the issue.

If i understand the scripts right, the installation creates a file named 
`/etc/apt/sources.list.d/influxdata.list`  ('/install/influxdb-install.sh' Line 28)
when the influxdb is installed but the update is looking for 
`/etc/apt/sources.list.d/influxdb.list` ('/ct/influxdb.sh' Line 55)

**Comment by hubrikt** [comment]
I still have this issue, after running command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/influxdb.sh)"`

<img width="703" alt="image" src="https://github.com/tteck/Proxmox/assets/89421789/0309071c-5b66-4c3b-aa91-1426a7ebf0af">

**Comment by tteck** [comment]
@hubrikt fixed

**Comment by hubrikt** [comment]
Correct!
<img width="703" alt="image" src="https://github.com/tteck/Proxmox/assets/89421789/13cbdaa4-6d37-49fd-a2de-78cf48f61087">

Thanks!
