### ISSUE TITLE
Monitor All brings core_mosquitto down on Homeassistant

### ISSUE THREAD

**Issue by jellevervloessem** [tteck/Proxmox#1397]
### A clear and concise description of the issue.

I receive the following error on Mosquito broker: "error: received null username or password for unpwd check"
it seems that the pinging of the MonitorAll is trying to much without any vauthentication.

Disabling the MonitorAll resolved the mosquito issues.

**Comment by tteck** [comment]
Pinging an IP address simply sends a small packet of data to the target device to check if it's reachable on the network. It doesn't involve any authentication process or data exchange that could cause the "null username or password" error to occur. This error typically occurs when a client attempts to connect to the Mosquitto broker without providing a valid username and password or with null values for these parameters.

**Comment by tteck** [comment]
The unpwd check is only triggered when a client sends its credentials to the broker during the connection process. Therefore, it would only occur if a client attempts to connect to the Mosquitto broker using a username and password, and it is not related to any external network activities such as pinging the broker's IP address.
