### ISSUE TITLE
Plex doesn't work

### ISSUE THREAD

**Issue by CubeComming** [tteck/Proxmox#1398]
### A clear and concise description of the issue.

So i an trying to install Plex on my Proxmox machine (default mode). And it seems to have a problem with the DNS connection. Now i have Tailscale installed on the main Proxmox system which might be a problem.
I also tried using the verbose mode but i'm not sure i'm doing it correctly.

Command i am using is:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/plex.sh)" which should be correctly copied...

The Container gets deployed but it never opens the port or starts plex as it seems. I can also not access the LSC Konsol as i would need the root login....

I tried changing DNS setting but that didn't help and the server changed it back shortly after.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Normal Run:
                     
Using Default Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 0
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: plex
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Plex LXC using the above default settings
build_container
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.2.141 
 ✓ Internet Connected
 ✗ DNS Lookup Failure
 ✓ Updated Container OS
 - Installing Dependencies...
[ERROR] in line 22: exit code 100: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

verbose mode:

root@server:~# bash -v "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/plex.sh)"
bash: #!/usr/bin/env bash
source <(curl -s https://raw.githubusercontent.com/tteck/Proxmox/main/misc/build.func)
# Copyright (c) 2021-2023 tteck
# Author: tteck (tteckster)
# License: MIT
# https://github.com/tteck/Proxmox/raw/main/LICENSE

function header_info {
clear
cat <<"EOF"
    ____  __             __  ___         ___          _____                          
   / __ \/ /__  _  __   /  |/  /__  ____/ (_)___ _   / ___/___  ______   _____  _____
  / /_/ / / _ \| |/_/  / /|_/ / _ \/ __  / / __ `/   \__ \/ _ \/ ___/ | / / _ \/ ___/
 / ____/ /  __/>  <   / /  / /  __/ /_/ / / /_/ /   ___/ /  __/ /   | |/ /  __/ /    
/_/   /_/\___/_/|_|  /_/  /_/\___/\__,_/_/\__,_/   /____/\___/_/    |___/\___/_/     
                                                                                      
EOF
}
header_info
echo -e "Loading..."
APP="Plex"
var_disk="8"
var_cpu="2"
var_ram="2048"
var_os="ubuntu"
var_version="22.04"
variables
color
catch_errors

function default_settings() {
  CT_TYPE="0"
  PW=""
  CT_ID=$NEXTID
  HN=$NSAPP
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET=dhcp
  GATE=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="no"
  VERB="no"
  echo_default
}

function update_script() {
if [[ ! -f /etc/apt/sources.list.d/plexmediaserver.list ]]; then msg_error "No ${APP} Installation Found!"; exit; fi
UPD=$(whiptail --title "SUPPORT" --radiolist --cancel-button Exit-Script "Spacebar = Select \nplexupdate info >> https://github.com/mrworf/plexupdate" 10 59 2 \
  "1" "Update LXC" ON \
  "2" "Run plexupdate" OFF \
  3>&1 1>&2 2>&3)

header_info
if [ "$UPD" == "1" ]; then
msg_info "Updating ${APP} LXC"
apt-get update &>/dev/null
apt-get -y upgrade &>/dev/null
msg_ok "Updated ${APP} LXC"
exit
fi
if [ "$UPD" == "2" ]; then
set +e
bash -c "$(wget -qO - https://raw.githubusercontent.com/mrworf/plexupdate/master/extras/installer.sh)"
exit
fi
}

start
build_container
description

msg_ok "Completed Successfully!\n"
echo -e "${APP} should be reachable by going to the following URL.
             ${BL}http://${IP}:32400/web${CL}\n": No such file or directory
root@server:~# 

DNS settings:
![grafik](https://user-images.githubusercontent.com/76119729/236678567-7aee5d48-fe68-4aee-bf18-51d521df07af.png)

### Please provide detailed steps to reproduce the issue.

Not sure how to.  
- You need tailscale installed on the main system
- trie to install plex via the script...

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/743
