### ISSUE TITLE
Unifi container : error on repo 

### ISSUE THREAD

**Issue by jbperrin88** [tteck/Proxmox#1399]
### A clear and concise description of the issue.

Hello , 

On unifi container , you use 'glennr' script with some repo list : 'deb http://ftp.nl.debian.org/debian stretch main'

Thio repo is archived so you need to change to 'deb http://archive.debian.org/debian stretch main'

Best regards !

**Comment by tteck** [comment]
fixed, https://github.com/tteck/Proxmox/commit/1c1f986cee64ffdc3c71d88191cf6c8fa70dea53 no longer using glennr
