### ISSUE TITLE
AMD MicroCode Script?

### ISSUE THREAD

**Issue by Fischje** [tteck/Proxmox#1404]
### A clear and concise description of the issue.

Nothing happends on AMD Systems, Ryzen and Epyc System here.
Maybee better describtion?

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://user-images.githubusercontent.com/562542/236868803-e8b04e25-8e86-4085-bb4d-a06513002eb7.png)

### Please provide detailed steps to reproduce the issue.

Startet MicroCode Script on my AMD hosts.

**Comment by tteck** [comment]
~Run this command `apt-get install -y amd-ucode` in the Proxmox VE shell and share the output~

**Comment by tteck** [comment]
~If you would be so kind and try again, I made changes.~

**Comment by tteck** [comment]
fixed https://github.com/tteck/Proxmox/commit/22a20617023edd67dfcd951d08e900021fe3d2b8

**Comment by Fischje** [comment]
yeah fixed. thanks!
