### ISSUE TITLE
monitor all just started arbitrarily rebooting my boxes

### ISSUE THREAD

**Issue by AskAlice** [tteck/Proxmox#1405]
### A clear and concise description of the issue.

From the moment it was installed it has been restarting my VMs and containers every 5 minutes
```
VM 109 is not running
Mon 08 May 2023 05:30:18 AM MDT: VM 109 is not running, starting...
Mon 08 May 2023 05:30:21 AM MDT: VM 110 is not responding, resetting...
Mon 08 May 2023 05:30:22 AM MDT: Pausing for 5 minutes...
VM 101 is not running
Mon 08 May 2023 05:35:32 AM MDT: VM 101 is not running, starting...
QEMU guest agent is not running
Mon 08 May 2023 05:35:37 AM MDT: VM 102 is not responding, resetting...
QEMU guest agent is not running
Mon 08 May 2023 05:35:43 AM MDT: VM 103 is not responding, resetting...
QEMU guest agent is not running
Mon 08 May 2023 05:35:51 AM MDT: VM 105 is not responding, resetting...
VM 107 is not running
Mon 08 May 2023 05:35:54 AM MDT: VM 107 is not running, starting...
VM 109 is not running
Mon 08 May 2023 05:35:57 AM MDT: VM 109 is not running, starting...
Mon 08 May 2023 05:36:00 AM MDT: VM 110 is not responding, resetting...
Mon 08 May 2023 05:36:01 AM MDT: Pausing for 5 minutes...
VM 101 is not running
```

All of these containers respond perfectly fine to pings. Seems like however you are resolving the ip address isn't working out, or something.

It also decided to start VMs that were not intended to run at all. very weird. If it's set to monitor 100 and 102, then why would it decide to start 101, 107 109.. etc

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.
```
❯ cat /etc/systemd/system/ping-instances.service
[Unit]
Description=Ping instances every 5 minutes and restarts if necessary

[Service]
Type=simple
# Include the CT/VM ID at the end of the line where ExecStart=/usr/local/bin/ping-instances.sh is specified,
# to indicate which CT/VN should be excluded. Example: ExecStart=/usr/local/bin/ping-instances.sh 100 102
ExecStart=/usr/local/bin/ping-instances.sh
Restart=always
StandardOutput=file:/var/log/ping-instances.log
StandardError=file:/var/log/ping-instances.log

[Install]
WantedBy=multi-user.target
```
_No response_

**Comment by tteck** [comment]
Your current configuration is configured to monitor all containers and virtual machines. To exclude specific instances from monitoring, you must append the CTID or VMID to the end of `ExecStart=/usr/local/bin/ping-instances.sh`.

To exclude the monitoring of instances 101, 107, and 109, you can append them to the command like this: `ExecStart=/usr/local/bin/ping-instances.sh 101 107 109`.

**Comment by tteck** [comment]
Virtual machines without the QEMU guest agent installed must be excluded.
