### ISSUE TITLE
Vaultwarden installation

### ISSUE THREAD

**Issue by aortmannm** [tteck/Proxmox#1407]
### A clear and concise description of the issue.

Hi, I try to install the vaultwarden lxc container and used the script in the proxmox shell as described. (Many other scripts of you worked me, the vaultwarden script is the first one that failes).

I tried default and advanced settings and hope you can help me.

A friend of mine used the same script some days ago and for him it's working.

Output of verbose script:

![image](https://github.com/tteck/Proxmox/assets/3414298/60db9a01-2fbd-477e-b2f8-f02e80a01299)
[vaultwarden compiling issue.log](https://github.com/tteck/Proxmox/files/11440727/vaultwarden.compiling.issue.log)

I attached some more as log that you can scroll up.

**Comment by tteck** [comment]
Adding additional resources can usually resolve an error that occurs during a cargo build.

**Comment by tteck** [comment]
> A friend of mine used the same script some days ago and for him it's working.

As the problem is unrelated to the script, it is now regarded as closed.
