### ISSUE TITLE
Uptime Kuma no longer runs after reboot

### ISSUE THREAD

**Issue by bshor** [tteck/Proxmox#1409]
I installed Uptime Kuma into an unprivileged LXC container running Debian using the latest script. It worked perfectly after a flawless installation. However, after rebooting the container, I can no longer run the application. The container itself appears to be functional; I can access the console without an issue.

Googling around I see some instructions to set up systemd services for restarting purposes, others describe using pm2. I assumed the script would have done one of these, but I can't see it. I tried pm2 but no luck on my end.

Any ideas?

**Comment by tteck** [comment]
What's the output of `systemctl status uptime-kuma`?

**Comment by tteck** [comment]
> I installed Uptime Kuma into an unprivileged LXC container running Debian using the latest script.

What does this mean?

**Comment by bshor** [comment]
> What's the output of `systemctl status uptime-kuma`?

Hmm. It looks ok?

```
root@uptimekuma:~# systemctl status uptime-kuma
* uptime-kuma.service - uptime-kuma
     Loaded: loaded (/etc/systemd/system/uptime-kuma.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-05-10 09:54:58 CDT; 50min ago
   Main PID: 118 (npm start)
      Tasks: 35 (limit: 18970)
     Memory: 229.0M
        CPU: 36.631s
     CGroup: /system.slice/uptime-kuma.service
             |-118 npm start
             |-177 sh -c npm run start-server
             |-178 npm run start-server
             |-227 sh -c node server/server.js
             `-229 node server/server.js

May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [SERVER] INFO: Connected
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [DB] INFO: Your database version: 10
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [DB] INFO: Latest database version: 10
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [DB] INFO: Database patch not needed
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [DB] INFO: Database Patch 2.0 Process
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [SERVER] INFO: Load JWT secret from database.
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [SERVER] INFO: Adding route
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [SERVER] INFO: Adding socket handler
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [SERVER] INFO: Init the server
May 10 09:55:02 uptimekuma npm[229]: 2023-05-10T09:55:02-05:00 [SERVER] INFO: Listening on 3001
```

**Comment by bshor** [comment]
> > I installed Uptime Kuma into an unprivileged LXC container running Debian using the latest script.
> 
> What does this mean?

I may be using the wrong words. What I mean to say is that I used the script from your site, and I chose an unprivileged container to install Kuma into. The install script worked and Kuma ran without a hitch from the 3001 port on the IP address of the LXC container.... until I rebooted.

**Comment by tteck** [comment]
So you ran this command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/uptimekuma.sh)"` from the Proxmox VE shell?

**Comment by bshor** [comment]
Correct.

> So you ran this command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/uptimekuma.sh)"` from the Proxmox VE shell?

**Comment by tteck** [comment]
Did the IP change?  Run this command `hostname -I` in the LXC console to confirm IP.

**Comment by bshor** [comment]
Ahhh ... that's a clue. hostname shows TWO ip addresses because I installed Tailscale into the LXC after starting it. And it comes up perfectly fine under the Tailnet IP address (100.xxx.xxx.xxx). So somehow I'm not able to access it from my local IP address (192.168....). So as you correctly surmised this is a me issue, not a script issue.

I do wonder why Kuma doesn't respond to the local IP address anymore ...

**Comment by tteck** [comment]
As the problem is unrelated to the script, it is now regarded as closed.
