### ISSUE TITLE
NginxProxyManager LetsEncryptPlugins not working

### ISSUE THREAD

**Issue by nicedevil007** [tteck/Proxmox#1410]
### A clear and concise description of the issue.

Hey tteck,

I wasn't sure if this is a new problem on the LXC with latest 2.10.2 or if this existed earlier but I'm not able to use the netcup plugin to get my wildcard certificate with your LXC container. I was hoping it will be fixed with NginxProxyManager 2.10.3 but it is not :(

I run the old fashioned way now to implement a docker container with default nginx setup and did the exact same entries for the plugin... there it worked like a charm on first try.

### Please provide detailed steps to reproduce the issue.

If I hit OK on the first run of nginx proxy to get my wildcard it first do the waiting procedure screen for about 30 sec - 60 sec and then it throws me back to the configure screen of the plugin with a red bar at the top without any issue / fault inside of it.

On the working installation with docker it was quite simple a 600 sec (yes 10 minutes) waiting to get the propagation of the dns settings on netcup. But then it just works.

**Comment by tteck** [comment]
I'm not sure this is a script issue, or a missing feature. Did you try running the command `pip install certbot-dns-netcup`?

**Comment by nicedevil007** [comment]
> 

I'm not sure as well but with this error here (yes did your pip command before) I can't tell you what is going on with the LXC :/

![image](https://github.com/tteck/Proxmox/assets/17103076/aedf7449-2881-448a-b0c2-9f1ee44df4e0)
