### ISSUE TITLE
"Can't Install on Proxmox" when trying to install Crowdsec. Also at end of Homepage

### ISSUE THREAD

**Issue by SpartanTech** [tteck/Proxmox#1412]
### A clear and concise description of the issue.

 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 - Installing Homepage (Patience)...
[ERROR] in line 22: exit code 1: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

And on Crowdsec it fails at the start. Ran the command -v pveversion and '/usr/bin/pveversion' returned.

This is the first time any of the scripts have failed on me. Have successfully created VMs, ubuntu LXC and syncthing LXC as well as Olivetin and Webmin

Did I do something wrong or do the scripts need updating?

**Comment by SpartanTech** [comment]
Why was this tagged? I read it but failed to see information related to my post

**Comment by SpartanTech** [comment]
Im still having issues. My first was trying to install Crowdsec on my machine running proxmox directly. I got the cant install on proxmox error.

Now I'm running it on my Docker host running Debian within proxmox and get this:
![image](https://github.com/tteck/Proxmox/assets/3395163/a03bd786-c093-444f-ba94-80bd820ba452)

**Comment by tteck** [comment]
Can't replicate your issue

```
   _____                      _  _____           
  / ____|                    | |/ ____|          
 | |     _ __ _____      ____| | (___   ___  ___ 
 | |    |  __/ _ \ \ /\ / / _  |\___ \ / _ \/ __|
 | |____| | | (_) \ V  V / (_| |____) |  __/ (__ 
  \_____|_|  \___/ \_/\_/ \__ _|_____/ \___|\___|

 ✓ Setup CrowdSec Repository
 ✓ Installed CrowdSec on debian
 ✓ Installed CrowdSec Common Bouncer
 ✓ Completed Successfully!
```

**Comment by batijo** [comment]
`root@server:~#   bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/crowdsec.sh)"`
`⚠️  Can't Install on Proxmox `

I'm also getting this error.
