### ISSUE TITLE
Error update container template

### ISSUE THREAD

**Issue by MJeka** [tteck/Proxmox#142]
If the container is a template, we get an error.
**Error:** you can't start a CT if it's a template.
**Script:** Proxmox LXC Updater

**Comment by tteck** [comment]
It's telling the truth, lol. I personally don't do templates, so it works as intended for my use. 
For your use, you may want to comment out everything pertaining to `[ "$status" == "status: stopped" ]` 
I may rewrite the script to skip templates if I find time. 
Could work in something like `pct config $container | grep -i template`?

**Comment by MJeka** [comment]
Thanks for your wonderful scripts!

**Comment by tteck** [comment]
Added option to skip stopped containers.
