### ISSUE TITLE
Remove FileBrowser

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#1421]
### A clear and concise description of the issue.

@tteck I'm sorry to ask, but I'm struggling with a problem with my PVE7 (https://forum.proxmox.com/threads/proxmox-restarts-randomly.116080/) 
After executing a `systemctl status`
I get a state of pve7 as being **degraded**
After checking it indicates after running `systemctl --failed` 
![image](https://github.com/tteck/Proxmox/assets/70786498/e481a9ed-8577-4cf5-a5cc-ebd1e812f250)
Hence, I want to remove this service. Can you help me with the right command(s).
Thank you so much,
Jens

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/688

**Comment by tteck** [comment]
updated
`systemctl stop filebrowser.service`
`systemctl disable filebrowser.service`
`rm -rf /usr/local/bin/filebrowser /root/filebrowser.db /etc/systemd/system/filebrowser.service`
