### ISSUE TITLE
Proxmox VE Kernel Clean

### ISSUE THREAD

**Issue by comfuzio** [tteck/Proxmox#1426]
### A clear and concise description of the issue.

Hi, i run this command as root on my proxmox server
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/kernel-clean.sh)"

![image](https://github.com/tteck/Proxmox/assets/30821243/a49b20a0-41a5-4296-9788-8e78d38b7d23)

It finds a lot of kernels that of course I want to remove, I press y.
It says it is removing 14 kernels...but if I run the command again, same thing happens!

I have 2 proxmox machines, 1 live in Hetzner (the print screen from there) and 1 at home that i will make cluster.
I can replicate the same issue on both
I remember in the past, the script said it doesn't support newer kernels and only 5.15. It doesn't say this any more so I assume it should be working with 6.2.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/30821243/ebec6cd6-9b28-4507-bbc6-8917252d2da6)

### Please provide detailed steps to reproduce the issue.

Run latest proxmox on latest 6.2 kernel
Login as root
run the command
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/kernel-clean.sh)"

**Comment by tteck** [comment]
It's because you're using the 6.2 kernel, I need to examine the code and incorporate additional blocks.
You can remove the unnecessary kernels by using the command `apt autoremove`.

**Comment by tteck** [comment]
Feel free to execute the script once more, as it has been updated to provide a clear explanation.
