### ISSUE TITLE
Tdarr with HW transcoding not working

### ISSUE THREAD

**Issue by zchesler** [tteck/Proxmox#1429]
I can't get tdarr to work on the LXC with vaapi or other QSV plugin. no matter what I try and what I do, Please advise.
I'm running proxmox on N5105 intel celeron miniPC which I understand that has QSV capabilities.

just being clear - LXC Tdarr works. but no iGPU transcoding.

log attached.
[c2Lt2RVXp-log.txt](https://github.com/tteck/Proxmox/files/11495722/c2Lt2RVXp-log.txt)

Thanks

_Originally posted by @zchesler in https://github.com/tteck/Proxmox/discussions/1278#discussioncomment-5924846_

**Comment by tteck** [comment]
Duplicate
