### ISSUE TITLE
LXC Updater Script => FreeSpace on Alpine

### ISSUE THREAD

**Issue by nicedevil007** [tteck/Proxmox#1430]
### A clear and concise description of the issue.

A picture tells more than 1000 words

![image](https://github.com/tteck/Proxmox/assets/17103076/b76e0a66-e30a-42ce-9f4e-ad64888f6096)

**Comment by tteck** [comment]
~I didn't think about Alpine. Does it stop the script?~
It doesn't stop the script from completing, until a solution is found, it will stand as is.

**Comment by tteck** [comment]
Alpine does not have a `/boot` directory

**Comment by nicedevil007** [comment]
Script isn't stopping just the feature is not working, why we are not using just the / directory?

**Comment by tteck** [comment]
Because it will not work that way. The feature simply isn't going to work for Alpine.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/c71f204e263f9ba80017b8377d638dc5571b5b5f
