### ISSUE TITLE
Home Assistant OS VM IP Address

### ISSUE THREAD

**Issue by rafny** [tteck/Proxmox#1431]
I noticed that the Home Assistant OS VM installation used docker and docker assigned an ip address on a different network 178* instead of the regular ones 192*.

Is there a way to either: not use docker, or customize the ip address being used?

**Comment by tteck** [comment]
You seem to be experiencing network issues.

**Comment by rafny** [comment]
> You seem to be experiencing network issues.

I have 6 other LXC's all under the same network with assigned static IP addresses. All I did was run the helper script on the host and the VM was assigned the 178.* IP. When I looked into the set-up, I saw that there was a docker interface with that IP. I'm just wondering how to get the VM on my same network as the other LXCs

**Comment by tteck** [comment]
Did you use default settings?

**Comment by tteck** [comment]
Since this does not seem to be a problem with the script, I recommend exploring the forums for assistance.
https://community.home-assistant.io/t/no-ip-address-showing/290149
