### ISSUE TITLE
Scrip Node Red Container: Time sync issue

### ISSUE THREAD

**Issue by Tokn59** [tteck/Proxmox#1437]
### A clear and concise description of the issue.

I installed Node Red using the script. This installs Node Red in a docker container. However for some reason, the time in the docker container does not correspond with the time of the host machine (Debian LXC)

**Comment by tteck** [comment]
> This installs Node Red in a docker container.

Wrong

> the docker container does not correspond with the time of the host machine

It is not a Docker container! 
Run this command  `dpkg-reconfigure tzdata`  to fix your issue.

**Comment by Tokn59** [comment]
You are absolutely right and I apologize. I am using some other scripts of you (BIG THANKS) and didn't check. The version of NR I am running does sit in a docker container. I will install a new version with your script !

**Comment by Tokn59** [comment]
Just installed NR via your script and it works perfectly ! Thank You !!!!!
