### ISSUE TITLE
Can't update Adguard and now failing to start

### ISSUE THREAD

**Issue by Trashprism** [tteck/Proxmox#1450]
### A clear and concise description of the issue.

After running the update script I get this error

error_handler $LINENO "$BASH_COMMAND"

[ERROR] in line 57: exit code 3: while executing command wget -qL https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz

After trying to run this Adguard ceases to work at all

**Comment by tteck** [comment]
1) Adguard Home should be updated from within the UI
2) No issue utilizing the manual update script
```
    ___       __                           __
   /   | ____/ /___ ___  ______ __________/ /
  / /| |/ __  / __  / / / / __  / ___/ __  / 
 / ___ / /_/ / /_/ / /_/ / /_/ / /  / /_/ /  
/_/  |_\__,_/\__, /\__,_/\__,_/_/   \__,_/   
            /____/                           
 
 ✓ Stopped AdguardHome
 ✓ Updated AdguardHome
 ✓ Started AdguardHome
 ✓ Cleaned
 ✓ Updated Successfully
root@adguard:~# 
```
3) Running this command `systemctl start AdGuardHome` should start Adguard Home

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/1086
> Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

**Comment by Stooovie** [comment]
Same. Running the update bash command in the LXC shell results in 
`[ERROR] in line 57: exit code 3: while executing command wget -qL https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz`
AdGuard cannot be updated from its GUI (Auto-update failed. Please [follow these steps](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update) to update manually.)

**Comment by tteck** [comment]
`systemctl start AdGuardHome` should start Adguard Home

**Comment by Stooovie** [comment]
It was due to no free space on device - I used the default 2GB and there's nothing else in the LXC but that's apparently not enough for some updates. Maybe it would be worth increasing the default.

**Comment by tteck** [comment]
That's for you to watch, different file systems may require more resources.

EXT4 file system, been running for a long time and still has enough storage
![Screenshot 2023-11-23 3 58 39 PM](https://github.com/tteck/Proxmox/assets/21342670/7fed8d4b-0092-4b26-84bd-ba6a6dc393d1)

**Comment by GauntPT** [comment]
I had the same issue after some time. Before all updates went smooth but after long time it was not possible any more due to the fact the the bootdisk was full.

The reason why my bootdisk runs full was query log, which was 1GB!
If you have the same issue, just delete querylog.json in /opt/AdGuardhome/data/querylog.json and make sure to shorten the time of logs.
2GB is more than enough with the proper configuration.

**Comment by Trashprism** [comment]
Just to update for future reference. This did end up being a storage issue.

**Comment by bejaranoo** [comment]
> I had the same issue after some time. Before all updates went smooth but after long time it was not possible any more due to the fact the the bootdisk was full.
> 
> The reason why my bootdisk runs full was query log, which was 1GB! If you have the same issue, just delete querylog.json in /opt/AdGuardhome/data/querylog.json and make sure to shorten the time of logs. 2GB is more than enough with the proper configuration.

this did the trick for me too, thanks!
Shame you have to dig to find this, the default configuration stores the query logs for 90 days, you can change it here:
Settings > General Settings > Logs configuration
likewise in the same menu youll find the button to clear the querylog and the update will now be successful.
btw @tteck its clear that this is not a script issue but maybe sticking this solution would be useful for a lot of people.
