### ISSUE TITLE
Nginx script not starting UI on port 81.  

### ISSUE THREAD

**Issue by dpackham** [tteck/Proxmox#1454]
### A clear and concise description of the issue.

The installation is completed after running the build script on the ProxMox host CLI, and there are no errors.

When I try to log in to the displayed URL, I get nothing.
Looking in the containers syslog, I see the following. and nothing is listening on port 81.  when I go to 80 I get an openresty page.

Jun  1 11:26:19 nginxproxymanager node[14608]: [6/1/2023] [11:26:19 AM] [Global   ] › ℹ  info      Backend PID 14608 listening on port 3000 ...
Jun  1 11:26:21 nginxproxymanager node[14608]: [6/1/2023] [11:26:21 AM] [SSL      ] › ✖  error     Error: Command failed: /usr/sbin/nginx -t -g "error_log off;"
Jun  1 11:26:21 nginxproxymanager node[14608]: nginx: the configuration file /usr/local/openresty/nginx/conf/nginx.conf syntax is ok
Jun  1 11:26:21 nginxproxymanager node[14608]: nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
Jun  1 11:26:21 nginxproxymanager node[14608]: nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
Jun  1 11:26:21 nginxproxymanager node[14608]:     at ChildProcess.exithandler (node:child_process:402:12)
Jun  1 11:26:21 nginxproxymanager node[14608]:     at ChildProcess.emit (node:events:513:28)
Jun  1 11:26:21 nginxproxymanager node[14608]:     at maybeClose (node:internal/child_process:1100:16)
Jun  1 11:26:21 nginxproxymanager node[14608]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
root@nginxproxymanager:/var/log# 

### Please provide detailed steps to reproduce the issue.

Just installed on proxmox 7x node cli.  used defaults and no errors on install

try to login with the given URL at end of install and nothing.  

try port 80 and see openresty page

look at /var/log/sysog for above error

**Comment by tteck** [comment]
Cannot replicate:

```
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________ __  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                                      /____/                            /____/             
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: nginxproxymanager
Using Disk Size: 4
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Nginx Proxy Manager LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python
 ✓ Installed Openresty
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Downloaded Nginx Proxy Manager v2.10.3
 ✓ Set up Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Created Service
 ✓ Customized Container
 ✓ Started Services
 ✓ Cleaned
 ✓ Completed Successfully!

Nginx Proxy Manager should be reachable by going to the following URL.
         http://192.168.86.253:81 
```

 
![Screenshot 2023-06-01 3 55 34 PM](https://github.com/tteck/Proxmox/assets/21342670/78df7771-dd6a-4d3d-9f86-76c74aca1c97)

Maybe try `IP:81/login`

**Comment by dpackham** [comment]
Nothing on IP:81/login. 

do you get this on port 80?

![Screenshot 2023-06-01 at 2 31 58 PM](https://github.com/tteck/Proxmox/assets/707522/ae28b7eb-b8fb-443e-b05f-741c3c71b4e1)

**Comment by tteck** [comment]
No:
![Screenshot 2023-06-01 4 36 45 PM](https://github.com/tteck/Proxmox/assets/21342670/dde7646b-b811-454a-9aab-ac20d3bb1158)

**Comment by dpackham** [comment]
hmmm.  ill nuke it again and try again

**Comment by dpackham** [comment]
Hmm same thing and same syslog error.  

Any ideas?  ProxMox 7.4-3 

<img width="1399" alt="Screenshot 2023-06-01 at 2 52 09 PM" src="https://github.com/tteck/Proxmox/assets/707522/4e7296e0-006c-4668-b088-17b8346c359e">

**Comment by dpackham** [comment]
Got it. 

I don't use IPv6, and this issue is that the error message indicates that the service is trying to start on the IPv6 address “[::]:80” and failed due to an unsupported address family. It means the machine does not have an IPv6 address set. All you need to do is edit the Ngnix configuration file to listen on the IPv4 address, as shown below.

Step 1: Open /etc/nginx/conf.d/default.conf
Step 2: Comment the below line:

listen [::]:80 default_server;

do this also for the :443 and :81 as well in the other two files in this dir

Now restart the nginx service and it should work.
![Screenshot 2023-06-01 at 3 31 42 PM](https://github.com/tteck/Proxmox/assets/707522/91ed65c4-4e4a-4495-982f-ea84a0ec1b43)

**Comment by tteck** [comment]
Since this does not seem to be a problem with the script, it is now considered closed.
