### ISSUE TITLE
Jellyfin LXC with debian

### ISSUE THREAD

**Issue by mnestor** [tteck/Proxmox#1456]
### A clear and concise description of the issue.

When installing jellyfin with a debian base the awk statement to grab the release version name fails because the variable name is not UBUNTU_CODENAME. It is VERSION_CODENAME

https://github.com/tteck/Proxmox/blob/2a80ed71842ddadbbdc98530c069a58704ad986b/install/jellyfin-install.sh#LL40C31-L40C31

```
root@jellyfin:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```

Since that fills in the jellyfin.sources file if it fills in blank then a later call to apt-get update fails. Just need to have it get the VERSION variable filled in and everything runs properly after that it appears. I did do all the rest of it manually though so not 100% certain.

**Comment by tteck** [comment]
> Advanced settings provide the option for users to switch between Debian and Ubuntu distributions. However, some applications or services, such as Deconz, grocy or Omada, may not be compatible with the selected distribution due to dependencies.

**Comment by tteck** [comment]
I have made a modification that potentially resolves the issue for Debian. https://github.com/tteck/Proxmox/commit/3f61e0739398de81e017ea7ba5e1a485b38e10b4
