### ISSUE TITLE
Unify 7.4 is out but script does nog pickup this version

### ISSUE THREAD

**Issue by wokkeltje13** [tteck/Proxmox#1457]
### A clear and concise description of the issue.

In my Unify console I receive the following message: Update to Network Application 7.4.156 available
The script however tells me no update available

**Comment by tteck** [comment]
The code of the script underwent refactoring three weeks ago to utilize the new unifi-repo.
I just performed a new install, and the application is up to date.

![Screenshot 2023-06-03 6 02 14 AM](https://github.com/tteck/Proxmox/assets/21342670/b757b948-470e-4233-9cd3-80ecd47d9cf9)
Backup, install a new UniFi LXC and restore.
https://github.com/tteck/Proxmox/issues/1449
