### ISSUE TITLE
RTSPtoWeb spelling mistake

### ISSUE THREAD

**Issue by Chrischi-** [tteck/Proxmox#1461]
### RTSPtoWeb spelling mistake

You have mixed up the S and the T by mistake.

For Example:
https://github.com/tteck/Proxmox/blob/11e0f3a8edd08f384154fd431dba6c55cfeec0f4/ct/rstptoweb.sh#L11-L15
https://github.com/tteck/Proxmox/blob/11e0f3a8edd08f384154fd431dba6c55cfeec0f4/ct/rstptoweb.sh#L21
https://github.com/tteck/Proxmox/blob/11e0f3a8edd08f384154fd431dba6c55cfeec0f4/CHANGELOG.md#L246
https://github.com/tteck/Proxmox/blob/11e0f3a8edd08f384154fd431dba6c55cfeec0f4/install/rstptoweb-install.sh#L30
https://github.com/tteck/Proxmox/blob/11e0f3a8edd08f384154fd431dba6c55cfeec0f4/install/rstptoweb-install.sh#L37

The correct name according to the GitHub repo is: 

`RTSPtoWeb`

Capital “RTSP”,
lower case “to” 
and “Web” capitalised at the beginning.

**_and by the way, thank you for this repository and the work it contains._**

**Comment by tteck** [comment]
lol... I sure did 🤦‍♂
Thanks for reporting, fixed

**Comment by Chrischi-** [comment]
@tteck 
you did it again ;)

https://github.com/tteck/Proxmox/blob/c735748faaf00134a9eb13b389cbf539ab70ae61/install/rtsptoweb-install.sh#L30

**edit:
you fixed it right afterwards**

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/c23de06e363959b92d4c55d43100717f72155589
