### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by alcirlima** [tteck/Proxmox#1465]
### A clear and concise description of the issue.

i try to put the command, but does not work.. absolutely nothing happens... does anyone know how to solve it?

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"

### Please provide detailed steps to reproduce the issue.

first i do this
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"

![image](https://github.com/tteck/Proxmox/assets/135899639/d06821df-68ed-4495-b102-7f2c8532a7ce)

**Comment by tteck** [comment]
It is likely that you are experiencing network problems, most likely related to DNS.

**Comment by tteck** [comment]
Since this problem is unrelated to the script, it is now considered closed.

**Comment by alcirlima** [comment]
thank you, it´s about DNS... now it´s ok!

I edited my dns, and put 8.8.8.8
