### ISSUE TITLE
How to upgrade to Python 3.11 in Home Assistant Core?

### ISSUE THREAD

**Issue by webmogul1** [tteck/Proxmox#1469]
### A clear and concise description of the issue.

I noticed that the script installs Python 3.11.2 but during upgrades it does not upgrades Python.

Is that by design or am I missing something?

**Comment by tteck** [comment]
To utilize Python 3.11 you will need to create a new Home Assistant Core LXC and restore a backup.

**Comment by webmogul1** [comment]
> To utilize Python 3.11 you will need to create a new Home Assistant Core LXC and restore a backup.

Thanks!!

**Comment by tteck** [comment]
Or, create a new Home Assistant Core LXC, use the [To copy data from Home Assistant Core to Home Assistant Core](https://github.com/tteck/Proxmox/tree/main/misc/copy-data) script, then copy over your MAC address. Shutdown the old LXC and start the new one

**Comment by webmogul1** [comment]
> Or, create a new Home Assistant Core LXC, use the [To copy data from Home Assistant Core to Home Assistant Core](https://github.com/tteck/Proxmox/tree/main/misc/copy-data) script, and copy over your MAC address. Shutdown the old LXC and start the new one

even better!
