### ISSUE TITLE
Should add a curl command check for your Proxmox Scripts 

### ISSUE THREAD

**Issue by tazboyz16** [tteck/Proxmox#1477]
### A clear and concise description of the issue.

Your scripts assume "curl" is installed by default for Proxmox LXC containers. You should add a if statement doing a ' command curl' check, to see if its installed prior to running the script 

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

having no curl command would assume your installer scripts completed and shows nothing but errors due to your Source to build.func

### Please provide detailed steps to reproduce the issue.

advised check

if ! command -v curl >/dev/null ; then
  echo "curl not installed. Installing curl"
  apt install curl -y
fi

**Comment by tazboyz16** [comment]
also it looks like your "start" function is broken too


start() {
  if command -v pveversion >/dev/null 2>&1; then
    if ! (whiptail --title "${APP} LXC" --yesno "This will create a New ${APP} LXC. Proceed?" 10 58); then
      clear
      echo -e "⚠  User exited script \n"
      exit
    fi
    install_script
  fi

  if ! command -v pveversion >/dev/null 2>&1; then
    if ! (whiptail --title "${APP} LXC UPDATE" --yesno "This will update ${APP} LXC.  Proceed?" 10 58); then
      clear
      echo -e "⚠  User exited script \n"
      exit
    fi
    update_script
  fi
}



Its currently showing "update XYZ appliance" vs install prompt on a fresh LXC installation

**Comment by tazboyz16** [comment]
Just tried the openwrt with no issues, is the motioneye install broken then?
Edit:
environment: line 160: pveversion: command not found
✗ This version of Proxmox Virtual Environment is not supported
Requires PVE Version 7.2 or higher
Exiting...
root@test-MotionEye:~# 

nvm on openwrt, I'm on 7.3-4

**Comment by tteck** [comment]
I presume you have successfully grasped how to utilize this repository for creating LXC containers for applications.
