### ISSUE TITLE
ssh_check fails when using tmux in pve console

### ISSUE THREAD

**Issue by wolfpackmars2** [tteck/Proxmox#1485]
### A clear and concise description of the issue.

when running any script in plain Proxmox shell, ssh_check does not warn that SSH has been detected.

When running any script in Proxmox shell using tmux, ssh_check warns that SSH has been detected.

First, I can't for the life of me figure out why ssh_check thinks SSH is detected. build.func appears to test if the SSH_CLIENT variable is set and if so, it determines that the current session is an SSH session.  However, I have checked my env while running tmux and there appears to be no SSH_CLIENT variable. By what magic is the script detecting the tmux environment?

Will running the scripts under tmux cause issues? I prefer to use tmux as sometimes my connections are unstable and having the shell get dropped in the middle of setting up a container causes containers to be created in a half baked state.

### Please provide detailed steps to reproduce the issue.

Start proxmox shell from web interface
start tmux
Install any script up to the point where ssh_check runs and receive warning that SSH has been detected.

**Comment by tteck** [comment]
The code snippet was introduced
## 2023-03-27
### Changed

- All Scripts
  - Incorporate code that examines whether SSH is being used and, if yes, offers a suggestion against it without restricting or blocking its usage.

The code snippet checks the existence and non-empty value of the `SSH_CLIENT` environment variable. In a local terminal session, this variable would not be set, so the condition would evaluate to false. However, when running inside a Tmux session, the `SSH_CLIENT` variable is often set, indicating that Tmux is being used within an SSH session.

Therefore, if the `SSH_CLIENT` variable is set (regardless of whether it's an SSH session or a local terminal session with Tmux), the code block following this condition will be executed.
