### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by zbuh** [tteck/Proxmox#1486]
Every script should have a note, explaining whats the expected update strategy.
Some apps have an internal update mechanism, other use the system package manager, others are compiled, etc...

**Comment by tteck** [comment]
> For questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/914#issuecomment-1376138884
