### ISSUE TITLE
Alpine Vaultwarden wont start after update.

### ISSUE THREAD

**Issue by luttman** [tteck/Proxmox#1487]
### A clear and concise description of the issue.

Updated Alpine Vaultwarden with the script 
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"
the server starts up but the service starts with an error 

alpine-vaultwarden:~# rc-status
Runlevel: default
 crond                                                                   [  started  ]
 networking                                                              [  started  ]
 vaultwarden                                                                [ failed ]

Tried to create a new instance but it gets the same error.

### Please provide detailed steps to reproduce the issue.

Install 
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"

and u will get the error.

**Comment by tteck** [comment]
I switched back to Alpine version 3.17 in order to determine if that resolves your problem.

**Comment by tteck** [comment]
> Updated Alpine Vaultwarden with the script
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"
the server starts up but the service starts with an error

All the script is doing is executing the commands `apk update && apk upgrade`

**Comment by tteck** [comment]
Looking at https://git.alpinelinux.org/aports/tree/testing/vaultwarden/vaultwarden.post-upgrade

**Comment by luttman** [comment]
Tried again with a "fresh" install
alpine-vaultwarden:~# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.0
Same error. 

`lpine-vaultwarden:/var/log# cat messages 
Jun 14 18:11:12 alpine-vaultwarden syslog.info syslogd started: BusyBox v1.36.1
Jun 14 18:11:12 alpine-vaultwarden daemon.info init: starting pid 378, tty '': '/sbin/openrc default'
Jun 14 18:11:12 alpine-vaultwarden cron.info crond[398]: crond (busybox 1.36.1) started, log level 8
Jun 14 18:11:12 alpine-vaultwarden daemon.info init: starting pid 405, tty '': '/sbin/getty 38400 console'
Jun 14 18:11:12 alpine-vaultwarden daemon.info init: starting pid 406, tty '/dev/tty1': '/sbin/getty 38400 tty1'
Jun 14 18:11:12 alpine-vaultwarden daemon.info init: starting pid 407, tty '/dev/tty2': '/sbin/getty 38400 tty2'
Jun 14 18:11:23 alpine-vaultwarden daemon.info supervise-daemon[646]: Supervisor command line: supervise-daemon vaultwarden --start --chdir /var/lib/vaultwarden --stdout /var/log/vaultwarden/access.log --stderr /var/log/vaultwarden/error.log --respawn-delay 2 --respawn-max 5 --respawn-period 1800 --user vaultwarden:vaultwarden /usr/bin/vaultwarden -- 
Jun 14 18:11:23 alpine-vaultwarden daemon.info supervise-daemon[649]: Child command line: /usr/bin/vaultwarden 
Jun 14 18:11:23 alpine-vaultwarden auth.info passwd: password for root changed by root
Jun 14 18:11:23 alpine-vaultwarden daemon.warn supervise-daemon[647]: /usr/bin/vaultwarden, pid 649, exited with return code 1
Jun 14 18:11:25 alpine-vaultwarden daemon.info supervise-daemon[657]: Child command line: /usr/bin/vaultwarden 
Jun 14 18:11:25 alpine-vaultwarden daemon.warn supervise-daemon[647]: /usr/bin/vaultwarden, pid 657, exited with return code 1
Jun 14 18:11:27 alpine-vaultwarden daemon.info supervise-daemon[659]: Child command line: /usr/bin/vaultwarden 
Jun 14 18:11:27 alpine-vaultwarden daemon.warn supervise-daemon[647]: /usr/bin/vaultwarden, pid 659, exited with return code 1
Jun 14 18:11:29 alpine-vaultwarden daemon.info supervise-daemon[661]: Child command line: /usr/bin/vaultwarden 
Jun 14 18:11:29 alpine-vaultwarden daemon.warn supervise-daemon[647]: /usr/bin/vaultwarden, pid 661, exited with return code 1
Jun 14 18:11:31 alpine-vaultwarden daemon.info supervise-daemon[663]: Child command line: /usr/bin/vaultwarden 
Jun 14 18:11:31 alpine-vaultwarden daemon.warn supervise-daemon[647]: /usr/bin/vaultwarden, pid 663, exited with return code 1
Jun 14 18:11:33 alpine-vaultwarden daemon.info supervise-daemon[665]: Child command line: /usr/bin/vaultwarden 
Jun 14 18:11:33 alpine-vaultwarden daemon.warn supervise-daemon[647]: /usr/bin/vaultwarden, pid 665, exited with return code 1
Jun 14 18:11:33 alpine-vaultwarden daemon.warn supervise-daemon[647]: respawned "/usr/bin/vaultwarden" too many times, exiting
Jun 14 18:11:40 alpine-vaultwarden auth.info login[667]: root login on 'tty1'
Jun 14 18:15:00 alpine-vaultwarden cron.info crond[398]: USER root pid 671 cmd run-parts /etc/periodic/15min`

All i can find in the logs.

**Comment by tteck** [comment]
Something has recently changed making the `/etc/conf.d/vaultwarden` or `/etc/init.d/vaultwarden` invalid would be my guess. However, I haven't had the chance to investigate further, but I might need to take out Alpine-Vaultwarden from the repository.

Maybe @nicedevil007 can look at it.

**Comment by nicedevil007** [comment]
Already fixed it on my site, was in contact on alpine gitlab ;)

Will fix it for all of you in a few days.

**Comment by tteck** [comment]
Fixed

**Comment by nicedevil007** [comment]
was just coming home to write the changes :)

here my original post for guys that are interested what have changed => https://gitlab.alpinelinux.org/alpine/aports/-/issues/15009#note_317523
