### ISSUE TITLE
Omada LXC installation error on PVE8

### ISSUE THREAD

**Issue by ohmgh** [tteck/Proxmox#1492]
Using default settings:
![image](https://github.com/tteck/Proxmox/assets/49562013/6ae07d59-fa4b-4df9-a501-0edb6d1b459d)

**Comment by tteck** [comment]
Yes, It appears that Ubuntu 20.04 is not an available template in PVE8

![Screenshot 2023-06-15 7 42 04 AM](https://github.com/tteck/Proxmox/assets/21342670/b132fcc2-75cb-44f5-8db6-267802971ac5)

Along with Debian 10, and any Alpine version below 3.18

**Comment by ohmgh** [comment]
Thanks for the quick response. Can the script be adapted to use later versions of the distributions?

**Comment by tteck** [comment]
I asked the question here:
https://forum.proxmox.com/threads/proxmox-ve-8-0-beta-released.128677/post-564403

**Comment by tteck** [comment]
Looking at it now...

**Comment by ohmgh** [comment]
cool! Thx a ton for the efforts!

**Comment by tteck** [comment]
> if there's popular demand we can add that again to the Proxmox VE 8 container template index.

Referencing the Ubuntu 20.04 template

**Comment by tteck** [comment]
Switched the installation distribution to Debian 11

```
   ____                      __     
  / __ \____ ___  ____ _____/ /___ _
 / / / / __  __ \/ __  / __  / __  /
/ /_/ / / / / / / /_/ / /_/ / /_/ / 
\____/_/ /_/ /_/\__,_/\__,_/\__,_/  
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: omada
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Omada LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Azul Zulu
 ✓ Installed MongoDB
 ✓ Installed Omada Controller
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Omada should be reachable by going to the following URL.
         https://192.168.86.253:8043 
```

**Comment by ohmgh** [comment]
Nice work, and thanks! 

I see Ubuntu 20.04 has also been  restored:

![image](https://github.com/tteck/Proxmox/assets/49562013/786e10f5-a33b-4fb5-a898-d3b77e7fb5e0)

**Comment by tteck** [comment]
Great! Now, Debian 11 and Ubuntu 20.04 can be used.

**Comment by tteck** [comment]
Now Debian 12 is compatible. https://github.com/tteck/Proxmox/commit/28f5363737e96155e2758071091ce5dd6d91ae15

**Comment by tteck** [comment]
Actually, it's now distribution agnostic.
