### ISSUE TITLE
Vaultwarden without https?

### ISSUE THREAD

**Issue by simpsonetti** [tteck/Proxmox#1494]
### A clear and concise description of the issue.

Hi, i run your script and it works quite good. All in the default way. Not advanced. 
But when i try to create an account, it says i have to changed to https. But i can't use https. 
Isn't it installed by default?
Regards

**Comment by tteck** [comment]
> But i can't use https.
Isn't it installed by default?

No
> ⚠️ Vaultwarden needs to be behind a proxy (Nginx Proxy Manager) to obtain HTTPS and to allow clients to connect.

![Screenshot 2023-06-15 8 31 27 AM](https://github.com/tteck/Proxmox/assets/21342670/c34d7a9b-bca3-49ad-a392-4c0f8ec9b3b4)
