### ISSUE TITLE
monitor-all restart VMs that have qemu-ga installed

### ISSUE THREAD

**Issue by dmshimself** [tteck/Proxmox#1496]
### A clear and concise description of the issue.

I have two VMs that have qemu-ga installed and both of these show IP  addresses on the Proxmox Management console as shown below.  One is an HA VM created by the excellent script and the other is an openwrt also created by the excellent script.  For the openwrt VM I manually installed qemu-ga and like the HA VM, it shows IP addresses on the Proxmox console.

However the monitor-all restarts them, even when they are running.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/6901481/2a4e0c37-395f-47a0-b811-c532a1b1739d)

### Please provide detailed steps to reproduce the issue.

I installed monitor-all, stopped it, edited in some excludes which do not include the VMs concerned, reloaded the daemon and restarted monitor-all.  The log is shown here.

Thu 15 Jun 16:26:55 BST 2023: Pausing for 5 minutes...
Thu 15 Jun 16:30:28 BST 2023: VM 102 is not responding, resetting...
Thu 15 Jun 16:30:43 BST 2023: VM 103 is not responding, resetting...
Thu 15 Jun 16:30:44 BST 2023: Pausing for 5 minutes...
Thu 15 Jun 16:36:10 BST 2023: VM 102 is not responding, resetting...

**Comment by tteck** [comment]
It is resetting an already running HAOS VM?

**Comment by dmshimself** [comment]
Yes and the openwrt one too

**Comment by tteck** [comment]
I'm not experiencing that kind of behavior with the HAOS VM. I observed that you mentioned the installation of the QEMU guest agent on the HAOS VM, but it is actually pre-installed.

![Screenshot 2023-06-15 12 26 54 PM](https://github.com/tteck/Proxmox/assets/21342670/fd81a9e9-7c6c-4465-b358-16068e479a29)

**Comment by dmshimself** [comment]
Yes agreed so I didn't add it to the HA VM, I only added qemu-ga to the openwrt vm.  Is there any more information I can 'force' out to the log to show what is going on?

**Comment by tteck** [comment]
what does the command `qm status 102` show?

**Comment by dmshimself** [comment]
# qm status 102
status: running

I wonder if it's anything to do with me having more than one network interface on each of these VMs.  Both have an eth0 and eth1 with different 192.168.x subnets

**Comment by tteck** [comment]
what does this snippet show?

```
IP=$(qm guest cmd 102 network-get-interfaces | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -E "192\.|10\.")
echo "$IP" 
```

**Comment by dmshimself** [comment]
echo "$IP" 
192.168.8.101
192.168.10.101

**Comment by tteck** [comment]
There is the issue.

**Comment by tteck** [comment]
It's trying to ping 192.168.8.101192.168.10.101

Based on your network setup, it seems that the current configuration of Proxmox VE Monitor-All will not function properly. If I find a solution, I'll inform you.

**Comment by tteck** [comment]
What does this snippet show?
```
IP=$(qm guest cmd 102 network-get-interfaces | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -E "192\.|10\." | head -n 1)
echo "$IP"
```

**Comment by tteck** [comment]
I made a commit [557f8dc](https://github.com/tteck/Proxmox/commit/557f8dcf463a7058b2143a52732d81b529791216) to hopefully resolve your issue, remove and re-add Proxmox VE Monitor-All

**Comment by dmshimself** [comment]
When I do that, the log file contains the following ...

```
Excluded instances: 
/usr/local/bin/ping-instances.sh: line 22: syntax error near unexpected token `)'
/usr/local/bin/ping-instances.sh: line 22: `      IP=$(qm guest cmd $instance network-get-interfaces | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -E "192\.|10\." | head -n 1))'
root@pve:~#

**Comment by tteck** [comment]
> | head -n 1))'

One too many `)`

**Comment by tteck** [comment]
fixed

**Comment by dmshimself** [comment]
Looking good!  I've leave it to run - many thanks for the amazingly fast fix
