### ISSUE TITLE
MQTT LXC script fails with Debian 12 Bookworm

### ISSUE THREAD

**Issue by anderl1969** [tteck/Proxmox#1502]
### A clear and concise description of the issue.

When choosing advanced options during install and then choosing Debian 12 "Bookworm" as OS for the container, the command `apt-get -y install mosquitto` fails.
With Debian 11 the script works fine

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/4c752c9d5001583694ea3bc8d0c944dc5d739ec6/install/mqtt-install.sh#L27

**Comment by tteck** [comment]
fixed
