### ISSUE TITLE
UniFi Application installation fails.

### ISSUE THREAD

**Issue by niklas389** [tteck/Proxmox#1503]
### A clear and concise description of the issue.

Installation of OpenJDK Headless fails regardless of chosen OS. Log attached:

 ✓ Installed Dependencies
+ msg_info 'Installing OpenJDK'
+ local 'msg=Installing OpenJDK'
+ echo -ne ' - \033[33mInstalling OpenJDK...'
 - Installing OpenJDK...+ apt-get install -y openjdk-11-jre-headless
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**Package openjdk-11-jre-headless is not available, but is referred to by another package**.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**E: Package 'openjdk-11-jre-headless' has no installation candidate**
++ error_handler 24 '$STD apt-get install -y openjdk-11-jre-headless'
++ local exit_code=100
++ local line_number=24
++ local 'command=$STD apt-get install -y openjdk-11-jre-headless'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m24\033[m: exit code \033[01;31m100\033[m: while executing command \033[33m$STD apt-get install -y openjdk-11-jre-headless\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m24\033[m: exit code \033[01;31m100\033[m: while executing command \033[33m$STD apt-get install -y openjdk-11-jre-headless\033[m'

[ERROR] in line 24: exit code 100: while executing command $STD apt-get install -y openjdk-11-jre-headless
++ [[ 24 -eq 24 ]]
++ echo -e 'The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.\n'
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

**Comment by tteck** [comment]
No issue here, clear your browser cache, then use default settings.

```
   __  __      _ _____ 
  / / / /__   (_) __(_)
 / / / / __ \/ / /_/ / 
/ /_/ / / / / / __/ /  
\____/_/ /_/_/_/ /_/   
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: unifi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Unifi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed OpenJDK
 ✓ Installed MongoDB
 ✓ Installed UniFi Network Application
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Unifi should be reachable by going to the following URL.
         https://192.168.86.253:8443 
```

**Comment by tteck** [comment]
Now Debian 12 is compatible.  https://github.com/tteck/Proxmox/commit/9ef8a4ae4fe9c9d59fc8af06a48e3670ccadcd6f

**Comment by tteck** [comment]
Actually, it's now distribution agnostic.
