### ISSUE TITLE
Pi-hole LXC: error while installing using debian 12

### ISSUE THREAD

**Issue by ramess18** [tteck/Proxmox#1505]
### A clear and concise description of the issue.

I was trying to install Pi-hole using Advanced settings. Detailed settings in attachment screenshot.

I'am getting this error:
[ERROR] in line 25: exit code 5: while executing command systemctl stop systemd-resolved

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/16610727/7b8a0f49-af7a-48a8-bd27-d34d9a1fdbd9)

**Comment by tteck** [comment]
fixed

**Comment by ramess18** [comment]
Thank you.
