### ISSUE TITLE
HA Core with Debian 12 needs libpcap

### ISSUE THREAD

**Issue by dmshimself** [tteck/Proxmox#1506]
### A clear and concise description of the issue.

In the process of transferring from an older HA Core LXC to a new one with Debian 12, I found that I got the following error in the HA system logs after startup.

```
Cannot watch for dhcp packets without a functional packet filter: libpcap is not available. Cannot compile filter !
```
A reboot didn't clear the error, but after installing libpcap manually in the LXC and the error went away.

### Please provide detailed steps to reproduce the issue.

Create a new HA core using Debian 12 and allow it to start up, then examine the log files

**Comment by tteck** [comment]
fixed

**Comment by dmshimself** [comment]
got to love your work :-)  Cheers
