### ISSUE TITLE
NGINX Proxy Manager LXC: error while installing using debian 12

### ISSUE THREAD

**Issue by X-Anonymous-Y** [tteck/Proxmox#1507]
### A clear and concise description of the issue.

I was trying to install NPM using Advanced settings. Detailed settings in attachment screenshot.

I'am getting this error:
[ERROR] in line 37: exit code 1: while executing command $STD pip3 install --upgrade setuptools

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/2701528/c0434d4b-8688-4004-8d63-5f0fa9fa0d04)

### Please provide detailed steps to reproduce the issue.

installed NPM:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"

EDIT:
i think you need here the pipx Package for virtual environments then you can use pipx insteed of pip3

**Comment by tteck** [comment]
~Could you perform a test on the bookworm branch, please?~
Moved to main branch

**Comment by X-Anonymous-Y** [comment]
> Could you perform a test on the bookworm branch, please?

I'll test it tomorrow if it's ok?  I'm going to work now. :)
