### ISSUE TITLE
Nginx Proxy Manager LXC update not working inside 

### ISSUE THREAD

**Issue by tomasz-soltysik** [tteck/Proxmox#1513]
### A clear and concise description of the issue.

When running `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"` inside existing Nginx Proxy Manager LXC Console, created using same script (but in PVE shell), it returns error about wget option L, it is unrecognized.
If I remove this option, another issue appears: /bin/ash: bash: not found
If I download _https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh_ to _update.sh_ file and run it using `. update.sh`, this is the result:
![image](https://github.com/tteck/Proxmox/assets/17692934/208c0e68-19b8-4c4b-804e-d20414eaebc3)

Should it be run in different place? Running in PVE shell would create new LXC.

**Comment by tteck** [comment]
Looks as if you are trying to update a ej52 installed Alpine version?

**Comment by tteck** [comment]
> another issue appears: /bin/ash: bash: not found

`/bin/ash` is Alpine. `wget` is not a standard installed package for Alpine.

**Comment by tomasz-soltysik** [comment]
Yes, it is running on Apline 3.16

I guess it means I installed it using different script and would have to reinstall using this one to have easy update option.
