### ISSUE TITLE
Issue when create CT Wireguard - Script get stuck

### ISSUE THREAD

**Issue by Baptiste-mrch** [tteck/Proxmox#1517]
### A clear and concise description of the issue.

I want to install Wireguard CT using the "bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/wireguard.sh)"
" command.
The script get stuck at "Installing WireGuard (using pivpn.io)...". I waited over a night and still, the script was running.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/62337736/f45da014-123c-437c-aeb8-05a1684f629b)

### Please provide detailed steps to reproduce the issue.

I already installed Wireguard, but due to simplicity and misconfiguration, I deleted the container and wants to reinstall it, but facing this issue.
I'm using the Proxmox shell interface, and not any SSH connection !

**Comment by tteck** [comment]
No issue here. It seems like there might be a DNS problem.

```
 _       ___           ______                     __
| |     / (_)_______  / ____/_  ______ __________/ /
| | /| / / / ___/ _ \/ / __/ / / / __ `/ ___/ __  / 
| |/ |/ / / /  /  __/ /_/ / /_/ / /_/ / /  / /_/ /  
|__/|__/_/_/   \___/\____/\__,_/\__,_/_/   \__,_/   
                                                    
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: wireguard
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Wireguard LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed WireGuard
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by tteck** [comment]
Use Debian 11

**Comment by Baptiste-mrch** [comment]
Works great now, thanks !
