### ISSUE TITLE
PVE* Upgrade failing 

### ISSUE THREAD

**Issue by cpcotton** [tteck/Proxmox#1519]
### A clear and concise description of the issue.

Current pve-manager/7.4-14/81b856fa (running kernel: 5.15.107-2-pve)
worked on other machines similar setups, thank you

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

if [ $(pveversion | grep "pve-manager/7.4-13" | wc -l) -ne 1 ]; then
  header_info
  msg_error "This version of Proxmox Virtual Environment is not supported"
  echo -e "  Requires PVE Version: 7.4-13"
  echo -e "\nExiting..."
  sleep 3
  exit
fi

**Comment by tteck** [comment]
fixed

**Comment by tteck** [comment]
Please confirm that it worked

**Comment by cpcotton** [comment]
Seems not working 
$(pveversion | grep -E "pve-manager/(7.4-13|7.4-14|7.4-15)") ]];   did not work
![image](https://github.com/tteck/Proxmox/assets/2354492/b71d34cb-2366-4eef-8df0-4eb02a919f0a)

**Comment by tteck** [comment]
removed pveversion check
