### ISSUE TITLE
Error message when updating Paperless NGX

### ISSUE THREAD

**Issue by Smile2Grow** [tteck/Proxmox#1520]
### A clear and concise description of the issue.

When updating Paperless NGX, I get the following error message: 

 ` ✓ Stopped Paperless-ngx
 - Updating to v1.16.2...
[ERROR] in line 86: exit code 1: while executing command /usr/bin/python3 manage.py migrate &> /dev/null`

It seems that the database migration does not go through.

**Comment by tteck** [comment]
The issue cannot be replicated.

```
    ____                        __                                     
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/                                         /____/        
 
 ✓ Stopped Paperless-ngx
 ✓ paperless-task-queue.service Exists.
 ✓ Updated to v1.16.2
 ✓ Cleaned
 ✓ Started Paperless-ngx
 ✓ Updated Successfully!

root@paperless-ngx:~# 
```

**Comment by tteck** [comment]
Note: ~Currently, Paperless-ngx will not run in Debian 12~

**Comment by bas89** [comment]
I'm having the same issue now, running Debian 12, which is the default distribution from the script, isn't it?

```
✓ Stopped Paperless-ngx
 - Updating to v2.4.3  -
[ERROR] in line 88: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null
```
But for my config it should be fine:
```
root@paperless-ngx:~# cd paperless-ngx/src/
root@paperless-ngx:~/paperless-ngx/src# /usr/bin/python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions
Running migrations:
  No migrations to apply.
```

**Comment by tteck** [comment]
Those are not the paths created from the script.

**Comment by bas89** [comment]
Yes, it was the temporary extraction path for updating purposes. I could track the issue down to running the migrate command in the right path (under /opt/), seeing the error it produces and fixing my config error. Afterwards, the update using your script went fine! Thanks.
