### ISSUE TITLE
Trying to update LXC container with SABnzbd and bash command

### ISSUE THREAD

**Issue by KevinBoone90** [tteck/Proxmox#1522]
### A clear and concise description of the issue.

   _____ ___    ____              __        __
  / ___//   |  / __ )____  ____  / /_  ____/ /
  \__ \/ /| | / __  / __ \/_  / / __ \/ __  / 
 ___/ / ___ |/ /_/ / / / / / /_/ /_/ / /_/ /  
/____/_/  |_/_____/_/ /_/ /___/_.___/\__,_/   
                                              
 - Updating SABnzbd...
[ERROR] in line 63: exit code 1: while executing command python3 -m pip install -r requirements.txt &> /dev/null

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/sabnzbd.sh)"

### Please provide detailed steps to reproduce the issue.

Update LXC container with bash command

**Comment by tteck** [comment]
The issue cannot be replicated.

```
   _____ ___    ____              __        __
  / ___//   |  / __ )____  ____  / /_  ____/ /
  \__ \/ /| | / __  / __ \/_  / / __ \/ __  / 
 ___/ / ___ |/ /_/ / / / / / /_/ /_/ / /_/ /  
/____/_/  |_/_____/_/ /_/ /___/_.___/\__,_/   
                                              
 ✓ Updated SABnzbd
root@sabnzbd:~# 
```

**Comment by tteck** [comment]
Debian 11 or 12?

**Comment by tteck** [comment]
If you have updated the LXC to Debian 12, run this command in the LXC console
```
rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED
```
then rerun the update

**Comment by KevinBoone90** [comment]
I think it's 12 not sure how to confirm, bit of a noob here 

Tried above command and then the update but got the same error message, however it did seem to update in some way since the SAB page states version 4.0.2
