### ISSUE TITLE
Container Default settings immediately errors after selecting default options Qbittorrent

### ISSUE THREAD

**Issue by vandieberg** [tteck/Proxmox#1524]
### A clear and concise description of the issue.

Error when trying to create container for qbittorrent with default settings

![error](https://github.com/tteck/Proxmox/assets/137370697/7fcac02c-1866-4d3d-8810-4d100d93de76)

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![error](https://github.com/tteck/Proxmox/assets/137370697/a60de6ed-515e-4b37-be7f-d7ef37c26617)

**Comment by tteck** [comment]
This is not an issue with the script, rather it stems from a storage problem.
