### ISSUE TITLE
MotionEye fails to install

### ISSUE THREAD

**Issue by zamojski** [tteck/Proxmox#1526]
### A clear and concise description of the issue.

 ✓ Installed FFmpeg
+ msg_info 'Installing MotionEye'
+ local 'msg=Installing MotionEye'
+ echo -ne ' - \033[33mInstalling MotionEye...'
 - Installing MotionEye...+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
+ pip install git+https://github.com/motioneye-project/motioneye.git@dev
Collecting git+https://github.com/motioneye-project/motioneye.git@dev
  Cloning https://github.com/motioneye-project/motioneye.git (to revision dev) to /tmp/pip-req-build-__oymih1
  Running command git clone --filter=blob:none --quiet https://github.com/motioneye-project/motioneye.git /tmp/pip-req-build-__oymih1
  Running command git checkout -b dev --track origin/dev
  Switched to a new branch 'dev'
  Branch 'dev' set up to track remote branch 'dev' from 'origin'.
  Resolved https://github.com/motioneye-project/motioneye.git to commit 019ee9e324cfc0cb37df089d2f79456f2b0a5036
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pillow
  Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 14.1 MB/s eta 0:00:00
Collecting babel
  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 13.0 MB/s eta 0:00:00
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 KB 11.7 MB/s eta 0:00:00
Collecting tornado
  Downloading tornado-6.3.2-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (426 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 426.9/426.9 KB 25.4 MB/s eta 0:00:00
Collecting pycurl
  Downloading pycurl-7.45.2.tar.gz (234 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.2/234.2 KB 26.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-16hkgw5f/pycurl_4198b19f63d34cd19198096c0e07505d/setup.py", line 229, in configure_unix
          p = subprocess.Popen((self.curl_config(), '--version'),
        File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-16hkgw5f/pycurl_4198b19f63d34cd19198096c0e07505d/setup.py", line 970, in <module>
          ext = get_extension(sys.argv, split_extension_source=split_extension_source)
        File "/tmp/pip-install-16hkgw5f/pycurl_4198b19f63d34cd19198096c0e07505d/setup.py", line 634, in get_extension
          ext_config = ExtensionConfiguration(argv)
        File "/tmp/pip-install-16hkgw5f/pycurl_4198b19f63d34cd19198096c0e07505d/setup.py", line 93, in __init__
          self.configure()
        File "/tmp/pip-install-16hkgw5f/pycurl_4198b19f63d34cd19198096c0e07505d/setup.py", line 234, in configure_unix
          raise ConfigurationError(msg)
      __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
++ error_handler 44 '$STD pip install git+https://github.com/motioneye-project/motioneye.git@dev'
++ local exit_code=1
++ local line_number=44
++ local 'command=$STD pip install git+https://github.com/motioneye-project/motioneye.git@dev'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m44\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD pip install git+https://github.com/motioneye-project/motioneye.git@dev\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m44\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD pip install git+https://github.com/motioneye-project/motioneye.git@dev\033[m'

[ERROR] in line 44: exit code 1: while executing command $STD pip install git+https://github.com/motioneye-project/motioneye.git@dev
++ [[ 44 -eq 24 ]]
+ exit

**Comment by tteck** [comment]
>Changing Linux distributions without confirming the proper functioning of default settings.

**Comment by tteck** [comment]
Use Debian
