### ISSUE TITLE
Post Install 8.0 Nag Screen Disabled

### ISSUE THREAD

**Issue by MoldyTaint** [tteck/Proxmox#1532]
### A clear and concise description of the issue.

The Post Install script used to have the option to disable the nag screen. It does not ask for that option anymore and has it still pop up.

### Please provide detailed steps to reproduce the issue.

Fresh 8.0 install

**Comment by tteck** [comment]
The script checks if it is already installed
https://github.com/tteck/Proxmox/blob/3624b67302001f29d7284e7ee9cd87412caf4134/misc/post-pve-install.sh#L139
try clearing browser cache

**Comment by MoldyTaint** [comment]
> The script checks if it is already installed
> 
> https://github.com/tteck/Proxmox/blob/3624b67302001f29d7284e7ee9cd87412caf4134/misc/post-pve-install.sh#L139
> 
> try clearing browser cache

Is it okay to run the post install script more than once? Or will it do some odd things trying to add the repos twice? I'll try running it again then

**Comment by tteck** [comment]
It will not hurt anything, but, if the no-nag is installed, it will not show up as an option.

**Comment by MoldyTaint** [comment]
I thank you for all your support with my stupid questions the last hour or two. It seems to not be showing now after running the script and rebooting after doing the ctrl+shift+r.
