### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by tammeryousef1006** [tteck/Proxmox#1539]
### A clear and concise description of the issue.

none

### Please provide detailed steps to reproduce the issue.

can you please make a script to upgrade from proxmox 7.4.15 to latest version 8

Best Regards

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/1472#discussioncomment-6137974

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/main/USER_SUBMITTED_GUIDES.md
