### ISSUE TITLE
Problem with script for Home Assistant LXC

### ISSUE THREAD

**Issue by ither** [tteck/Proxmox#154]
Hi, I tried to create an LXC container using the homeassistant-v3.sh script and I found that in the line 281 you are trying to use a "warn" command that probably was copy/pasted from a previous version. When I replaced the "warn" with "echo", the script runned fine.

I want also to use this opportunity to talk a couple things about your scripts, if I may:

- In general, great work, by the way!
- I think that the installation of portainer in this container and probably any other should be optional. I have already a portainer instance running and what I want is to install Portainer Agent, instead.
- I don't really like at all that I need to use the root user to connect to the LXC containers. I don't mind that you run the scripts as root for provisioning but you _really_ should create at least a non-root user with a password who can become root using sudo or similar. Please, do this. 

Thanks for all the great work!

**Comment by tteck** [comment]
Thanks for reporting that issue, non-ZFS here, so skipped over that one. Fixed now.
The optional Portainer & Docker Compose install is incorporated in the Docker LXC 
As for the non-root user, that's up to you to create those (`adduser whoever`)
