### ISSUE TITLE
Uninstall Proxmox VE Monitor-All

### ISSUE THREAD

**Issue by DrSpaldo** [tteck/Proxmox#1543]
Thanks for all your scripts and work on them. I would like to uninstall the Monitor-All script. I just can't work out how, or if I am missing something?

**Comment by tteck** [comment]
![Screenshot 2023-06-25 9 13 48 PM](https://github.com/tteck/Proxmox/assets/21342670/e46289e3-3e1e-47a9-864a-f24826bd0ab1)

**Comment by tteck** [comment]
![Screenshot 2023-06-25 9 22 17 PM](https://github.com/tteck/Proxmox/assets/21342670/4a71cc88-0fdc-43aa-b9a2-7c1e005fc5ba)

**Comment by DrSpaldo** [comment]
Haha, I am an idiot. Thanks
