### ISSUE TITLE
Nginx Proxy Manager LXC update not working in Debian 12

### ISSUE THREAD

**Issue by flix-one** [tteck/Proxmox#1544]
### A clear and concise description of the issue.

After upgrading to Debian 12 the update is not working anymore

The error message when starting the script inside the LXC container 

[ERROR] in line 131: exit code 1: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

Is there a problem with the Python Environment?

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.10.3
 - Setting up Enviroment...
[ERROR] in line 131: exit code 1: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null
```

### Please provide detailed steps to reproduce the issue.

Upgrade LXC container to Debian 12
Run Update script via bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"

**Comment by flix-one** [comment]
When running the line manually, the result is:

```
python3 -m pip install --no-cache-dir certbot-dns-cloudflare
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by tteck** [comment]
run `rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED`

**Comment by flix-one** [comment]
Thank you that worked!
Unfortunately, now I get the next error on line 137:

```
- Building Frontend...
[ERROR] in line 137: exit code 1: while executing command yarn install --network-timeout=30000 &> /dev/null
```

When I run it manually it seems to work?

```
~# yarn install --network-timeout=30000
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.06s.
```

**Comment by tteck** [comment]
what's the output of `node -v`?

**Comment by flix-one** [comment]
```
node -v
v18.13.0
```

**Comment by tteck** [comment]
Nginx Proxy Manager requires node v16
> Updating the LXC to Debian 12 manually could potentially cause a loss of functionality.

https://github.com/tteck/Proxmox/discussions/1498#discussion-5303045

The issue you're facing is not present in the Nginx Proxy Manager LXC script. I suggest looking for a solution there.
Since this issue is unrelated to the script, it is considered resolved.

**Comment by flix-one** [comment]
Solution:
[Install nvm](https://github.com/nvm-sh/nvm/blob/master/README.md#installing-and-updating)
`nvm install 16.20.1`
`nvm use 16.20.1`

**Comment by tteck** [comment]
`ln -sf /root/.nvm/versions/node/v16.20.1/bin/node /usr/bin/node`
the command creates a symbolic link named `node` in the `/usr/bin` directory that points to the `node` executable of Node.js version 16.20.1 installed in the NVM directory. This allows you to conveniently run the `node` command from anywhere in the system, regardless of the current working directory.
