### ISSUE TITLE
Visual Studio Code Server installation aborts with: 'Can't Install on Proxmox'

### ISSUE THREAD

**Issue by AlexanderKas** [tteck/Proxmox#1560]
Visual Studio Code Server aborts with: 'Can't Install on Proxmox'

**Comment by tteck** [comment]
That is correct, it's not allowed to install on the Proxmox host.
Run the command in a LXC console.

**Comment by fpillajo** [comment]
When installing, an error appears
![vscode](https://github.com/tteck/Proxmox/assets/39251738/b539d040-2b92-4526-b1aa-df41ff85e62a)

**Comment by tteck** [comment]
Install curl (`apt install -y curl`)

**Comment by fpillajo** [comment]
now another error appears
![vscode1](https://github.com/tteck/Proxmox/assets/39251738/91125950-add3-4432-b5da-671b6d00e262)

**Comment by tteck** [comment]
Try again

**Comment by fpillajo** [comment]
thanks for the help it was installed correctly
