### ISSUE TITLE
Sonarr Debian 12

### ISSUE THREAD

**Issue by LostPoE** [tteck/Proxmox#1569]
### A clear and concise description of the issue.

Sonarr does not look to be installed correctly when choosing Debian 12 via script.
lsof -i -P -n | grep LISTEN
Does not show 8989 listening after install.

**Comment by tteck** [comment]
What version of Sonarr does it install?

**Comment by tteck** [comment]
It shows listening, on Debian 12 here
```
lsof -i -P -n | grep LISTEN
systemd     1   root   39u  IPv6 4049585      0t0  TCP *:22 (LISTEN)
sshd      159   root    3u  IPv6 4049585      0t0  TCP *:22 (LISTEN)
master    343   root   13u  IPv4 4052056      0t0  TCP 127.0.0.1:25 (LISTEN)
mono     4197 sonarr    7u  IPv4 4061090      0t0  TCP *:8989 (LISTEN)
```

**Comment by LostPoE** [comment]
Re-installing.

**Comment by LostPoE** [comment]
Weird. Works now. Close ticket. Thanks!!!!

**Comment by tteck** [comment]
Changed repository, now Version 3.0.10.1567 (latest)

**Comment by LostPoE** [comment]
> Changed repository, now Version 3.0.10.1567 (latest)

Thanks again!

**Comment by divemasterjm** [comment]
> Changed repository, now Version 3.0.10.1567 (latest)

how can i update? with your script nothing happens
i update lxc to debian 12 manually and after update i've got
root@sonarr:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease                              
Hit:3 http://security.debian.org bookworm-security InRelease                               
Hit:4 https://apt.sonarr.tv/debian buster-develop InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: https://apt.sonarr.tv/debian/dists/buster-develop/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/de76bf329dacb14a9fce7461a741138af61aa71c

**Comment by divemasterjm** [comment]
> [de76bf3](https://github.com/tteck/Proxmox/commit/de76bf329dacb14a9fce7461a741138af61aa71c)

thanks, done and worked.
