### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by NasKar2** [tteck/Proxmox#1575]
I'm running proxmox 7.4-15 and get an error after running this command in the shell.
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)"

[ERROR] in line 415: exit code 5: while executing command pvesm alloc $STORAGE $VMID $DISK0 4M &> /dev/null

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/464 https://github.com/tteck/Proxmox/issues/885

**Comment by fjavimer** [comment]
I have the same problem. I have already put a message and I think it has to do with the Debian 12 update, but my programming level is very low

**Comment by fjavimer** [comment]
I am very new to proxmox, how can I create debian 11 LXC to avoid errors?

**Comment by tteck** [comment]
@fjavimer the OP is installing Home Assistant OS in a virtual machine. Your issues have nothing to do with this
