### ISSUE TITLE
n8n - [ERROR] in line 30: exit code 127: while executing command $STD npm install --global n8n

### ISSUE THREAD

**Issue by iMarkus** [tteck/Proxmox#1577]
### A clear and concise description of the issue.

n8n script is not able to finish installation when using Default or Advanced mode.

Script output is complaining about permission denied.

npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.20.1/lib/node_modules/n8n/node_modules/ssh2
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! sh: 1: node: Permission denied

### **Default mode log:**

Using Default Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 101
Using Hostname: n8n
Using Disk Size: 3GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a n8n LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 101 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.26 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Node.js
 - Installing n8n (Patience).../dev/stdin: line 24:  1995 Aborted                 "$@" > /dev/null 2>&1

[ERROR] in line 24: exit code 134: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

### **Default mode with verbose logging enabled:**

npm notice 
npm notice New major version of npm available! 8.19.4 -> 9.7.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
npm notice Run npm install -g npm@9.7.2 to update!
npm notice 
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.20.1/lib/node_modules/n8n/node_modules/ssh2
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! sh: 1: node: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-01T19_32_41_877Z-debug-0.log
++ error_handler 30 '$STD npm install --global n8n'
++ local exit_code=127
++ local line_number=30
++ local 'command=$STD npm install --global n8n'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m30\033[m: exit code \033[01;31m127\033[m: while executing command \033[33m$STD npm install --global n8n\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m30\033[m: exit code \033[01;31m127\033[m: while executing command \033[33m$STD npm install --global n8n\033[m'

[ERROR] in line 30: exit code 127: while executing command $STD npm install --global n8n
++ [[ 30 -eq 24 ]]
+ exit

### **Advanced mode last log lines:**

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice 
npm notice New major version of npm available! 8.19.4 -> 9.7.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
npm notice Run npm install -g npm@9.7.2 to update!
npm notice 
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.20.1/lib/node_modules/n8n/node_modules/ssh2
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! sh: 1: node: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-01T19_07_36_233Z-debug-0.log
++ error_handler 30 '$STD npm install --global n8n'
++ local exit_code=127
++ local line_number=30
++ local 'command=$STD npm install --global n8n'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m30\033[m: exit code \033[01;31m127\033[m: while executing command \033[33m$STD npm install --global n8n\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m30\033[m: exit code \033[01;31m127\033[m: while executing command \033[33m$STD npm install --global n8n\033[m'

[ERROR] in line 30: exit code 127: while executing command $STD npm install --global n8n
++ [[ 30 -eq 24 ]]
+ exit

### **Reproduce with:**

**Default mode:**
4096 memory

**Advanced mode with following settings:**
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/n8n.sh)"
Advanced
debian 11
debian
12 Bookworm
Privileged
**ROOT PASSWORD** (long pw. like 4234HUJkoku09ukilh!/)jjn)
400
n8n
5
4
4096
vmbr0
dhcp
no
blank
blank
blank
blank
blank
yes
yes
yes

**Comment by tteck** [comment]
fixed
