### ISSUE TITLE
Mariadb debain 12 script fails with the following

### ISSUE THREAD

**Issue by tworth04** [tteck/Proxmox#1580]
### A clear and concise description of the issue.

[ERROR] in line 23: exit code 1: while executing command $STD bash <(curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup)
++ [[ 23 -eq 24 ]]
+ exit

I ran this from within the proxmox shell.

**Comment by tworth04** [comment]
# [error] # See https://mariadb.com/kb/en/mariadb/mariadb-package-repository-setup-and-usage/#platform-support
++ error_handler 23 '$STD bash <(curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup)'
++ local exit_code=1
++ local line_number=23
++ local 'command=$STD bash <(curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup)'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m23\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD bash <(curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup)\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m23\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD bash <(curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup)\033[m'

[ERROR] in line 23: exit code 1: while executing command $STD bash <(curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup)

**Comment by tworth04** [comment]
ran the install script from their site...apparently it's not supported on bookworm yet...

curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash produces:

root@mariadb:~# curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash
# [error] Detected Debian but version (12.0) is not supported.
# [error] # The MariaDB Repository only supports these distributions:
#    * RHEL/Rocky 8 & 9 (rhel)
#    * RHEL/CentOS 7 (rhel)
#    * Ubuntu 18.04 LTS (bionic), 20.04 LTS (focal), and 22.04 LTS (jammy)
#    * Debian 10 (buster), & 11 (bullseye)
#    * SLES 12 & 15 (sles)
# [error] # See https://mariadb.com/kb/en/mariadb/mariadb-package-repository-setup-and-usage/#platform-support

**Comment by tteck** [comment]
fixed
