### ISSUE TITLE
PBS Cleanup doesn't work on PVE systems

### ISSUE THREAD

**Issue by lordratner** [tteck/Proxmox#1586]
### A clear and concise description of the issue.

I have PVE and PBS installed on the same server. It's a common setup endorsed by Proxmox. It looks like the PBS script looks for PVE and errors if it finds it. So you can't get rid of the subscription popup on PBS.

Desired change: The script should all be combined into one script. It checks for both PVE and PBS and has a flow for the three options:

1. PVE only
2. PBS only
3. PVE and PBS

Sources and popup suppression would be changed based on which of the three setups is detected. 

### Please provide detailed steps to reproduce the issue.

Install PVE and PBS on the same server. Then try to run the script.

**Comment by tteck** [comment]
> For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
That script needs to be updated to be used with PBS 3, it is PBS 2 only. I'll work on it.

**Comment by tteck** [comment]
Now compatible with both PBS 2 and PBS 3.

If you want to bypass the PVE safety, download the script and remove the following lines of code
```
if command -v pveversion >/dev/null 2>&1; then
    echo -e "\n🛑  PVE Detected, Wrong Script!\n"
    exit 1
fi
```
