### ISSUE TITLE
Can't install Technitium in advanced (to set static IP)

### ISSUE THREAD

**Issue by maccident** [tteck/Proxmox#159]
When attempting to use the v3 installer for technitium, I select "Advanced' then defaults for everything, except IP address and VLAN.

The install proceeds correctly, then the script bails out prior to completing.  Cannot log into the container via pve -> container console, as defaults chose automatic and it requests a password.

` ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.99.2
 ✓ Updated Container OS
 - Installing Dependencies...root@pve:~#`

**Comment by tteck** [comment]
Strange... so the network connected and the container updated, but failed installing dependencies which is only curl and sudo. 
I just tried again... same

**Comment by tteck** [comment]
Would you try 
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/v3/ct/technitiumdns-v3.sh)"
```
enter your IP as `192.168.99.2/24` and the Gateway IP is your router `192.168.99.1`

**Comment by tteck** [comment]
Fixed, thanks for reporting!

**Comment by maccident** [comment]
It still fails for me, in the same way.

**Comment by tteck** [comment]
after setting the static IP and Gateway IP?
you can use the main branch now

**Comment by maccident** [comment]
Yes, and that was trying twice, once each with https://github.com/tteck/Proxmox/raw/v3/ct/technitiumdns-v3.sh and https://github.com/tteck/Proxmox/raw/main/ct/technitiumdns-v3.sh

**Comment by maccident** [comment]
I'll give it a try again after dinner.  Thank you for responding so quickly.  I learned about your repo last night from Reddit, and was blown away.  

I greatly appreciate your work on this!

**Comment by maccident** [comment]
Just tried again 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/technitiumdns-v3.sh)"

failed in the same place, after the "Installing Dependencies..." text.

**Comment by tteck** [comment]
Are you setting the subnet mask?
when you set the static IP

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/162

**Comment by maccident** [comment]
Yeah, I'm specifying ip/netmask - 192.168.99.2/24 for the IP, and the gateway as just the IP

**Comment by tteck** [comment]
after it fails, click on the LXC and click network to see if the IP and gateway addresses are there

**Comment by tteck** [comment]
is the IP you are trying to use available?

**Comment by maccident** [comment]
Yes, it's a new vlan with only the gateway (at .1) so far.  This will be the dhcp server for the vlan.

**Comment by maccident** [comment]
The reason I'm using advanced, is that when I use the defaults and assign a static address / vlan - technitium complains that I'm using a dhcp address (which is true when I use the defaults, but not true when I reassign the host to a vlan, assign a static in pve, and reboot the container)

**Comment by tteck** [comment]
IPV6 is your issue. Disable IPV6 if possible
