### ISSUE TITLE
Problem with the "Plex Media Server LXC" entry

### ISSUE THREAD

**Issue by Dlay2017** [tteck/Proxmox#1597]
The install commandline string is missing, please add it. 

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/install/plex-install.sh)"`

I guess

**Comment by tteck** [comment]
Guess again.

**Comment by tteck** [comment]
```
    ____  __             __  ___         ___          _____                          
   / __ \/ /__  _  __   /  |/  /__  ____/ (_)___ _   / ___/___  ______   _____  _____
  / /_/ / / _ \| |/_/  / /|_/ / _ \/ __  / / __ `/   \__ \/ _ \/ ___/ | / / _ \/ ___/
 / ____/ /  __/>  <   / /  / /  __/ /_/ / / /_/ /   ___/ /  __/ /   | |/ /  __/ /    
/_/   /_/\___/_/|_|  /_/  /_/\___/\__,_/_/\__,_/   /____/\___/_/    |___/\___/_/     
                                                                                      
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 0
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: plex
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Plex LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Hardware Acceleration
 ✓ Set Up Plex Media Server Repository
 ✓ Installed Plex Media Server
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Plex should be reachable by going to the following URL.
             http://192.168.86.253:32400/web
```

**Comment by Dlay2017** [comment]
Only the update commandline is written in the entry, not the install string.

**Comment by tteck** [comment]
I'm not following what you're saying. I just created a new Plex LXC without issue.

**Comment by tteck** [comment]
## Exploring the Scripts and Steps Involved in an Application LXC Installation
https://github.com/tteck/Proxmox/blob/main/CODE-AUDIT.md

**Comment by Dlay2017** [comment]
![Screenshot 2023-07-09 020836](https://github.com/tteck/Proxmox/assets/26193050/e8f55c10-58b2-4352-b44d-d6bd0e01214f)

**Comment by tteck** [comment]
Apparently you don't understand the process of creating a Plex LXC. Follow the link that I provided above.

**Comment by tteck** [comment]
Oh, are you saying that I mistakenly used "update" instead of "Install" in the wording? If so, I can fix that.

**Comment by tteck** [comment]
Nope, just checked, all wording is correct.

**Comment by Dlay2017** [comment]
When i copy the cmd line 

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/plex.sh)"

to a fresh LXC container, it only provides the "update Plex" option, but the installation doesnt start, as it should, since the LXC is empty..

![image](https://github.com/tteck/Proxmox/assets/26193050/6d07e355-c2be-4f4a-93c0-18320555b5ec)

with proceed
![image](https://github.com/tteck/Proxmox/assets/26193050/54510f04-3468-436c-a121-1d5fd39d040c)

**Comment by tteck** [comment]
Read the instructions, both lines!

**Comment by tteck** [comment]
**To create a new Proxmox VE Plex Media Server LXC, run the command below in the Proxmox VE Shell.**

**Comment by Dlay2017** [comment]
Ah.. my fault.. sorry..
