### ISSUE TITLE
n8n webhook url

### ISSUE THREAD

**Issue by beautyfree** [tteck/Proxmox#1600]
### A clear and concise description of the issue.

I can't test/run telegraw trigger because my webhook url always localhost, but need to be some domain/ip accessable from the internet
<img width="509" alt="image" src="https://github.com/tteck/Proxmox/assets/656531/80181c98-cfc8-4202-8bb8-c481df7885e7">

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Look like we need to have an option to setup WEBHOOK_URL during installation https://docs.n8n.io/hosting/environment-variables/configuration-methods/#webhook-url

### Please provide detailed steps to reproduce the issue.

- Create telegram bot in @botfather and get accesss token
- Add credentials 
<img width="1055" alt="image" src="https://github.com/tteck/Proxmox/assets/656531/92f25e0b-916f-4200-9297-6811ca326933">
- Create telegram trigger in workflow 
<img width="805" alt="image" src="https://github.com/tteck/Proxmox/assets/656531/675bcfec-07fc-4054-88e1-6c506dbee17b">
- Try to test it (it will not get any events)

**Comment by tteck** [comment]
My assistance is focused on script-related inquiries, not on operational support for applications or services.

https://docs.n8n.io/hosting/environment-variables/environment-variables/#deployment

**Comment by xlucasfelix** [comment]
> My assistance is focused on script-related inquiries, not on operational support for applications or services.

The problem seems to be directly related to the way n8n is installed... we can't find the place where we can edit the .env file and during the installation we don't have the opportunity to define it either.

Even following the n8n documentation (running "export WEBHOOK_URL=https://n8n.example.com/") the installation ignores it completely and still has no way of defining a custom url for my domain.

I wish there was a review on this aspect, because I'm using the n8n through another installation (portainer) and everything works very well, I can even define the WEBHOOK_URL variable.

Anyway, thanks for the scripts, I hope this gets resolved or you can guide me on how to get around this

**Comment by tteck** [comment]
> The problem seems to be directly related to the way n8n is installed

https://docs.n8n.io/hosting/installation/npm/#install-globally-with-npm

> Even following the n8n documentation

https://docs.n8n.io/hosting/environment-variables/configuration-methods/

**Comment by xlucasfelix** [comment]
I managed to solve it, thanks to the first link you sent me, I managed to understand how it works and look for the correct folder where the file should be edited!

For future queries from other users, go to the `/etc/systemd/system` folder and edit the `n8n.service` file, including the variable `Environment="WEBHOOK_URL=https://n8n.example.com/"` just below `ExecStart=n8n start`

It worked here! Thanks tteck again!

Note: I believe that at the end of the installation there could be an instruction on the location of this file or something that could help users.

**Comment by beautyfree** [comment]
I have already managed it like @xlucasfelix described.

And it will be great if we can manage settings of webhook url during installation

**Comment by rewulff** [comment]
this issue costed me a day to figure out how to manage this.

thx a lot @xlucasfelix 

at least we need something like a guide how to se env.

otherwise we are lost...

**Comment by rewulff** [comment]
The issue continues when trying to use for example pupeteer.
When you install via npm install the n8n.service is unable to fin correct path witthout fiddling.

imho it's a script issue for sure. the installation differs from the documented way: "npm + pm2 service".

i this constellation n8n is sadly next to useless

**Comment by tteck** [comment]
Just do your own thing. The script works for many, including myself.

**Comment by zerneo85** [comment]
@xlucasfelix  I have been struggeling to get https working but no luck.  I have found the file you mentioned and the url has changed but i am unable to get https working. Did you get this up and running? My config is below

[Unit]
Description=n8n

[Service]
Type=simple
Environment="N8N_SECURE_COOKIE=true"
ExecStart=n8n start
Environment="WEBHOOK_URL=https://n8n.domain.com/"
Environment="N8N_EDITOR_BASE_URL=https://n8ndomain.com/"
Environment="N8N_PROTOCOL=https"
Environment=N8N_SSL_KEY=/var/ssl/domain-key.pem
Environment=N8N_SSL_CER=/var/ssl/domain-cert.crt
Environment=N8N_HOST=n8n.domain.com
[Install]
WantedBy=multi-user.target

**Comment by xlucasfelix** [comment]
@zerneo85 I use Cloudflared (Argo Tunnel), so I don't need to worry about configuring anything related to https, everything is already ready
