### ISSUE TITLE
Technitium DNS update script "STD: unbound variable"

### ISSUE THREAD

**Issue by Saik0Shinigami** [tteck/Proxmox#1608]
### A clear and concise description of the issue.

When running the update script it instantly fails out 

>Updating Technitium DNS...environment: line 65: STD: unbound variable

There's no other logging or output.

Looks like it's this line in your code.

`$STD bash <(curl -fsSL https://download.technitium.com/dns/install.sh)`

I don't see any lines assigning a value to this variable.

### Please provide detailed steps to reproduce the issue.

Open running Technitium LXC container. 

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/technitiumdns.sh)"`

**Comment by Saik0Shinigami** [comment]
Normal update script for Technitium works as expected.

`curl -sSL https://download.technitium.com/dns/install.sh | sudo bash`

This repo's script likely doesn't support updates in favor of just using normal script from technitium.

**Comment by tteck** [comment]
fixed
