### ISSUE TITLE
[Request, can help] Port some scripts to ruby

### ISSUE THREAD

**Issue by Xpl0itU** [tteck/Proxmox#1612]
### A clear and concise description of the issue.

Some scripts like the clean-lxcs.sh one depend on curl being installed, which isn’t installed by default in all systems, but the ruby interpreter is, so I think porting the scripts to something like ruby would be a great choice, it’s also similar to bash, so you won’t have a bad time maintaining them

I have some experience with ruby, so I can help porting some scripts too

**Comment by tteck** [comment]
It is unusual for a system that would utilize the "Proxmox VE LXC Cleaner" script to not have `curl` installed by default.
