### ISSUE TITLE
[ERROR] in line 427: exit code 255: while executing command qm start $VMID

### ISSUE THREAD

**Issue by mdsoares** [tteck/Proxmox#1613]
### A clear and concise description of the issue.

Every time I run the script, I get the error mentioned in the subject. As I'm not the most experienced person on the subject, I don't know what else to do!

### Please provide detailed steps to reproduce the issue.

This is my PVE log from the last try

Jul 13 23:10:34 pve login[648399]: ROOT LOGIN  on '/dev/pts/1'
Jul 13 23:11:38 pve qm[648612]: <root@pam> starting task UPID:pve:0009E5A5:014D341C:64B0769A:qmcreate:100:root@pam:
Jul 13 23:11:38 pve qm[648612]: <root@pam> end task UPID:pve:0009E5A5:014D341C:64B0769A:qmcreate:100:root@pam: OK
Jul 13 23:11:52 pve qm[648701]: <root@pam> update VM 100: -boot order=scsi0 -description # Home Assistant OS
### https://github.com/tteck/Proxmox
[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/D1D7EP4GF) -efidisk0 local-lvm:vm-100-disk-0,efitype=4m -scsi0 local-lvm:vm-100-disk-1,discard=on,ssd=1,size=32G
Jul 13 23:11:53 pve qm[648709]: <root@pam> starting task UPID:pve:0009E606:014D3A0F:64B076A9:qmstart:100:root@pam:
Jul 13 23:11:53 pve qm[648710]: start VM 100: UPID:pve:0009E606:014D3A0F:64B076A9:qmstart:100:root@pam:
Jul 13 23:11:53 pve qm[648710]: KVM virtualisation configured, but not available. Either disable in VM configuration or enable in BIOS.
Jul 13 23:11:53 pve qm[648709]: <root@pam> end task UPID:pve:0009E606:014D3A0F:64B076A9:qmstart:100:root@pam: KVM virtualisation configured, but not available. Either disable in VM configuration or enable in BIOS.
Jul 13 23:11:55 pve qm[648719]: <root@pam> starting task UPID:pve:0009E614:014D3AA8:64B076AB:qmstop:100:root@pam:
Jul 13 23:11:55 pve qm[648724]: stop VM 100: UPID:pve:0009E614:014D3AA8:64B076AB:qmstop:100:root@pam:
Jul 13 23:11:55 pve qm[648719]: <root@pam> end task UPID:pve:0009E614:014D3AA8:64B076AB:qmstop:100:root@pam: OK
Jul 13 23:11:55 pve qm[648725]: <root@pam> starting task UPID:pve:0009E616:014D3AF3:64B076AB:qmdestroy:100:root@pam:
Jul 13 23:11:55 pve qm[648726]: destroy VM 100: UPID:pve:0009E616:014D3AF3:64B076AB:qmdestroy:100:root@pam:
Jul 13 23:11:56 pve kernel: dm-7: detected capacity change from 67108864 to 0
Jul 13 23:11:56 pve kernel: dm-6: detected capacity change from 8192 to 0
Jul 13 23:11:56 pve qm[648725]: <root@pam> end task UPID:pve:0009E616:014D3AF3:64B076AB:qmdestroy:100:root@pam: OK
Jul 13 23:15:38 pve pveproxy[632688]: worker exit
Jul 13 23:15:38 pve pveproxy[889]: worker 632688 finished
Jul 13 23:15:38 pve pveproxy[889]: starting 1 worker(s)
Jul 13 23:15:38 pve pveproxy[889]: worker 649232 started
Jul 13 23:17:01 pve CRON[649432]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
Jul 13 23:17:01 pve CRON[649433]: (root) CMD (cd / && run-parts --report /etc/cron.hourly)
Jul 13 23:17:01 pve CRON[649432]: pam_unix(cron:session): session closed for user root
Jul 13 23:17:20 pve systemd[1]: session-195.scope: Deactivated successfully.
Jul 13 23:17:20 pve systemd[1]: session-195.scope: Consumed 40.113s CPU time.
Jul 13 23:17:20 pve systemd-logind[540]: Session 195 logged out. Waiting for processes to exit.
Jul 13 23:17:20 pve systemd-logind[540]: Removed session 195.
Jul 13 23:17:20 pve pvedaemon[881]: <root@pam> end task UPID:pve:0009E4C7:014D1B1D:64B0765A:vncshell::root@pam: OK
Jul 13 23:17:23 pve pveproxy[631297]: worker exit
Jul 13 23:17:23 pve pveproxy[889]: worker 631297 finished
Jul 13 23:17:23 pve pveproxy[889]: starting 1 worker(s)
Jul 13 23:17:23 pve pveproxy[889]: worker 649478 started
Jul 13 23:17:24 pve pvedaemon[881]: <root@pam> starting task UPID:pve:0009E907:014DBB22:64B077F4:vncshell::root@pam:
Jul 13 23:17:24 pve pvedaemon[649479]: starting termproxy UPID:pve:0009E907:014DBB22:64B077F4:vncshell::root@pam:
Jul 13 23:17:24 pve pvedaemon[880]: <root@pam> successful auth for user 'root@pam'
Jul 13 23:17:24 pve login[649482]: pam_unix(login:session): session opened for user root(uid=0) by root(uid=0)
Jul 13 23:17:24 pve systemd-logind[540]: New session 197 of user root.
Jul 13 23:17:24 pve systemd[1]: Started session-197.scope - Session 197 of User root.
Jul 13 23:17:24 pve login[649487]: ROOT LOGIN  on '/dev/pts/1'
Jul 13 23:17:28 pve systemd[1]: session-197.scope: Deactivated successfully.
Jul 13 23:17:28 pve systemd-logind[540]: Session 197 logged out. Waiting for processes to exit.
Jul 13 23:17:28 pve systemd-logind[540]: Removed session 197.
Jul 13 23:17:28 pve pvedaemon[881]: <root@pam> end task UPID:pve:0009E907:014DBB22:64B077F4:vncshell::root@pam: OK

**Comment by tteck** [comment]
Make sure that UEFI Boot & Virtualization is enabled and Secure Boot is disabled in your machine’s BIOS.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

https://www.derekseaman.com/2023/06/home-assistant-proxmox-ve-8-0-quick-start-guide.html
