### ISSUE TITLE
Keycloak admin interface never loads

### ISSUE THREAD

**Issue by ghost** [tteck/Proxmox#1618]
### A clear and concise description of the issue.

After a successful installation of Keycloak, the admin interface never loads.

I have searched the closed issues, searched Google, I have tried both installing via the Proxmox shell and Bitvise SSH client, I have tried both with Debian 11 and Debian 12, different configurations in advanced mode, tried visiting the https secure site and port, restarting the container, etc. I have used many other scripts from tteck so this is not a browser or router configuration issue.

The installation itself is successful and I can see and log in to the containers console, but http://192.168.X.X:8080/ will never load. I am aware the page says that the interface may take a few minutes, but it truly never loads after 10+ minutes, and plenty of resources. I'm baffled at why the page does not load.

**Comment by tteck** [comment]
fixed
