### ISSUE TITLE
v3 Script - Advanced Settings

### ISSUE THREAD

**Issue by tteck** [tteck/Proxmox#162]
![Screenshot 2022-04-21 10 30 31 AM](https://user-images.githubusercontent.com/21342670/164481349-110a3fbb-1d4f-4f8b-ac1d-b9128e004419.png)

11 settings can be defined
If a static IP is used, you must set a Gateway IP
Static IP requires CIDR Notation (/24)

![Screenshot 2022-04-27 9 10 53 AM](https://user-images.githubusercontent.com/21342670/165531884-856046d1-9182-4dd2-929a-5fefa33340e0.png)

9 settings can be defined

**Comment by maccident** [comment]
For reference:
```
Using Advanced Settings
Using CT Type Unprivileged
Using CT Password Automatic Login
Using CT ID 110
Using CT Name technitiumdns
Using Disk Size 2
Using 1vCPU
Using 512MiB RAM
Using Static IP Address 192.168.99.2/24
Using Gateway IP Address 192.168.99.1
Using VLAN Tag 100
Are these settings correct(y/n)? y

 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.99.2 2603:beef:beef:beef:beef:beef:beef:a241
 ✓ Updated Container OS
 - Installing Dependencies...root@titan:~#
```
(ipv6 address redacted)

**Comment by tteck** [comment]
I'm no network guy, but I'd guess IPV6 is the cause because the gateway is set for IPV4 `gw=<GatewayIPv4>` not `gw6=<GatewayIPv6>`

**Comment by maccident** [comment]
you think that might be why the installer is failing, or why technitium is confused about dhcp?

**Comment by tteck** [comment]
disable IPV6

**Comment by maccident** [comment]
I've disabled v6 on my dhcp server and trying again.  Interestingly enough, after the whole thing fails, the LXC container is not assigned to VLAN 100, but the static v4 address and gateway are set properly.

No longer do I see the v6 address in the progress text, but the install fails in the same place.

**Comment by maccident** [comment]
logs
```
Using Advanced Settings
Using CT Type Unprivileged
Using CT Password Automatic Login
Using CT ID 110
Using CT Name technitiumdns
Using Disk Size 2
Using 1vCPU
Using 512MiB RAM
Using Static IP Address 192.168.99.2/24
Using Gateway IP Address 192.168.99.1
Using VLAN Tag 100
Are these settings correct(y/n)? y

 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.99.2
 ✓ Updated Container OS
 - Installing Dependencies...root@titan:~#
```

**Comment by tteck** [comment]
Try again and see if the VLAN shows

**Comment by tteck** [comment]
![Screenshot 2022-04-18 1 23 45 AM](https://user-images.githubusercontent.com/21342670/163760299-197f5a57-ea1e-407e-aa4e-a90481496824.png)

**Comment by maccident** [comment]
It now works with IPv6 left enabled.
Thank you!

**Comment by rzimin** [comment]
Am I getting it right that the biggest difference for V3 scripts are those advanced options? And basically there is no need to recrate / adjust existing VMs?

**Comment by tteck** [comment]
Correct!

**Comment by andre68723** [comment]
Hi,

maybe a hint can be added for ipv4 and trailing `/24` ? 

```
Using Static IP Address 192.168.0.88
Using Gateway IP Address NONE
Using VLAN Tag NONE
Are these settings correct(y/n)? y
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 - Creating LXC Container...400 Parameter verification failed.
net0: invalid format - format error
```

**Comment by tteck** [comment]
and not to mention no Gateway IP Address
```
Using Static IP Address 192.168.0.88
Using Gateway IP Address NONE
```
https://github.com/tteck/Proxmox/issues/162#issue-1206599738

**Comment by andre68723** [comment]
yes, ended up in (no error) and a container which can't login and has no docker either.
but Gateway you already mentioned above

**Comment by tteck** [comment]
I'm not following. What are you attempting?

**Comment by andre68723** [comment]
error is clear, on my side. just asking for a hint in the shell, e.g.
`Enter a Static IP Address, or Press [ENTER] for Default: DHCP ` -> 
`Enter a Static IPv4 CIDR (/24) Address , or Press [ENTER] for Default: DHCP `
same for gw
`Enter a Gateway IP, or Press [ENTER] for Default: NONE`
`Enter a Gateway IP (mandatory if static ip is used), or Press [ENTER] for Default: NONE `
