### ISSUE TITLE
emqx not install

### ISSUE THREAD

**Issue by Traineratwot** [tteck/Proxmox#1620]
### A clear and concise description of the issue.

emqx not start install

I enter command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/emqx.sh)"`
but nothing do, 
![image](https://github.com/tteck/Proxmox/assets/41589091/734600cb-658b-4847-99af-5527be335a81)

**Comment by tteck** [comment]
That usually suggests a network issue, typically related to DNS. 

No issues here...
![Screenshot 2023-07-16 8 48 53 AM](https://github.com/tteck/Proxmox/assets/21342670/46844624-a046-4c97-9306-696b9e4ce094)

**Comment by tteck** [comment]
Since this issue is not directly related to the script it is considered closed.

**Comment by Traineratwot** [comment]
Thanks, you were right :)
