### ISSUE TITLE
Subscription nag in Proxmox 8 remains

### ISSUE THREAD

**Issue by Tech6767** [tteck/Proxmox#1622]
### A clear and concise description of the issue.

In Proxmox 8 running the script and saying yes to remove the "no valid subscription" message on every login, is not working. 

I have restarted, logged back in to proxmox and cleared my browser cache, the problem still persists.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/103525838/58575be2-6a13-4df0-acb0-d684cc5236a2)

### Please provide detailed steps to reproduce the issue.

Execute 
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"`

disable "subscription nag"
reboot
log back in

**Comment by tteck** [comment]
What is the output from running this command `apt --reinstall install proxmox-widget-toolkit`?

```
root@server:~# apt --reinstall install proxmox-widget-toolkit
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/200 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 80962 files and directories currently installed.)
Preparing to unpack .../proxmox-widget-toolkit_4.0.6_all.deb ...
Unpacking proxmox-widget-toolkit (4.0.6) over (4.0.6) ...
Setting up proxmox-widget-toolkit (4.0.6) ...
Removing subscription nag from UI...
root@server:~# 
```

**Comment by tteck** [comment]
I've just verified with another user who extensively tests the repository, and they have confirmed that there are no issues when removing the "No Subscription Nag."  🤷🏻‍♂️

**Comment by rollingafull** [comment]
Hi,

One thing that i think is not contemplated.

If PVE and PBS are instaled on same system, when try to remove PBS
subscription nag, PBS is detected as PVE and subscription nag is not
removed from PBS.

Thanks for the scripts.

Regads.

**Comment by Tech6767** [comment]
It does indeed seem like it is gone now. 

I also get the same output as you, when runnin `apt --reinstall install proxmox-widget-toolkit`.

Thanks for the quick reply, I am confused why it is working now, but that's good nonetheless.
