### ISSUE TITLE
Arch Linux Script is not working

### ISSUE THREAD

**Issue by tigertim08** [tteck/Proxmox#1625]
### A clear and concise description of the issue.

Hello, 

The script is telling me that I need PVE Version higher than 7.0 and then is exiting the script. But I'm on 8.0... 

`    ___              __       __    _                 
   /   |  __________/ /_     / /   (_)___  __  ___  __
  / /| | / ___/ ___/ __ \   / /   / / __ \/ / / / |/_/
 / ___ |/ /  / /__/ / / /  / /___/ / / / / /_/ />  <  
/_/  |_/_/   \___/_/ /_/  /_____/_/_/ /_/\__,_/_/|_|  
                                                      
Loading...
✗ This version of Proxmox Virtual Environment is not supported
Requires PVE Version 7.0 or higher
Exiting...
root@proxmox:~# pveversion -v

proxmox-ve: 8.0.1 (running kernel: 6.2.16-4-pve)
pve-manager: 8.0.3 (running version: 8.0.3/bbf3993334bfa916)
pve-kernel-6.2: 8.0.3
pve-kernel-5.15: 7.4-4
pve-kernel-6.2.16-4-pve: 6.2.16-5
pve-kernel-5.15.108-1-pve: 5.15.108-1
pve-kernel-5.15.83-1-pve: 5.15.83-1
ceph-fuse: 16.2.11+ds-2
corosync: 3.1.7-pve3
criu: 3.17.1-2
glusterfs-client: 10.3-5
ifupdown: 0.8.41
ksm-control-daemon: 1.4-1
libjs-extjs: 7.0.0-3
libknet1: 1.25-pve1
libproxmox-acme-perl: 1.4.6
libproxmox-backup-qemu0: 1.4.0
libproxmox-rs-perl: 0.3.0
libpve-access-control: 8.0.3
libpve-apiclient-perl: 3.3.1
libpve-common-perl: 8.0.6
libpve-guest-common-perl: 5.0.3
libpve-http-server-perl: 5.0.4
libpve-rs-perl: 0.8.4
libpve-storage-perl: 8.0.2
libqb0: 1.0.5-1
libspice-server1: 0.15.1-1
lvm2: 2.03.16-2
lxc-pve: 5.0.2-4
lxcfs: 5.0.3-pve3
novnc-pve: 1.4.0-2
proxmox-backup-client: 3.0.1-1
proxmox-backup-file-restore: 3.0.1-1
proxmox-kernel-helper: 8.0.2
proxmox-mail-forward: 0.2.0
proxmox-mini-journalreader: 1.4.0
proxmox-offline-mirror-helper: 0.6.2
proxmox-widget-toolkit: 4.0.6
pve-cluster: 8.0.2
pve-container: 5.0.4
pve-docs: 8.0.4
pve-edk2-firmware: 3.20230228-4
pve-firewall: 5.0.2
pve-firmware: 3.7-1
pve-ha-manager: 4.0.2
pve-i18n: 3.0.5
pve-qemu-kvm: 8.0.2-3
pve-xtermjs: 4.16.0-3
qemu-server: 8.0.6
smartmontools: 7.3-pve1
spiceterm: 3.3.0
swtpm: 0.8.0+pve1
vncterm: 1.8.0
zfsutils-linux: 2.1.12-pve1
root@proxmox:~# `

**Comment by tteck** [comment]
fixed

**Comment by squidds** [comment]
> fixed

Hey @tteck sorry if this has been asked before, but has the Arch LXC script been permanently removed from the repo? I'm only seeing Debian LXC, Ubuntu LXC, and Alpine LXC. Thanks!

**Comment by squidds** [comment]
Disregard, please, I see the explanation above.
