### ISSUE TITLE
Grocy can't access the latest release website

### ISSUE THREAD

**Issue by KimpiegamesYT1** [tteck/Proxmox#1629]
### A clear and concise description of the issue.

When trying to install grocy I got the error  
https://user-images.githubusercontent.com/76051904/254697137-12561c76-6a09-4890-8c07-dbc13be284f5.png

After making an git issue the owner said they don't guarantee any uptime for their website. Is it possible to fix this? with like the latest release from  github instead of their site? (https://github.com/grocy/grocy/releases)

https://github.com/grocy/grocy/issues/2273

### Please provide detailed steps to reproduce the issue.

Use the script

**Comment by KimpiegamesYT1** [comment]
Issue has been fixed by the website owner

**Comment by tteck** [comment]
I can switch to using their github for downloads if this continues to be a problem.

**Comment by KimpiegamesYT1** [comment]
Should not be a problem. Owner said downtime is minimal. I just tried it at the wrong time i guess. Thanks for the fast response.

**Comment by tteck** [comment]
fixed
