### ISSUE TITLE
Jellyfin dont see the files on NFS mount inside a LXC Jellyfin 

### ISSUE THREAD

**Issue by drm-gith** [tteck/Proxmox#1630]
### A clear and concise description of the issue.

Mounted a NFS share on a path inside LXC Jelly container on proxmox. The mount is good, i can navigate and see the files via terminal, but the Jellyfin aplication dont recognize the folders mounted on the path. I tried change the LXC folder permissions, but dont work. Tried make a user with the same UID e GUID on the TrueNAS, where the NFS share is configured, but again dont work. 
I also activate the NFS option on proxmox for that LXC, and install with a privileged container. But nothing is working. 
Any advices ?
Thanks in advance 

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

  bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jellyfin.sh)"

### Please provide detailed steps to reproduce the issue.

Install LXC Jelly with scriot above 
Install the nfs requeriments via terminal
Create a folder (neither on / or /mnt works)
mount the nfs share via /etc/fstab
acess jellyfin 
try add a folder inside the mount on library

**Comment by tteck** [comment]
- For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
