### ISSUE TITLE
Problem installing Grocy

### ISSUE THREAD

**Issue by mdepedrof** [tteck/Proxmox#1634]
When i try to install Grocy, I always get the same error: 
[ERROR] in line 37: exit code 8: while executing command wget -q https://releases.grocy.info/latest

Seems that the url has changed

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/20051127/59436a08-4d1f-49cf-8f70-251cce557c33)

### Please provide detailed steps to reproduce the issue.

paste the script on the shell of proxmox server, set the variables but always get this error.

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/1629

**Comment by tteck** [comment]
fixed
