### ISSUE TITLE
Cloudflared LXC - No Network

### ISSUE THREAD

**Issue by tobsowo** [tteck/Proxmox#1640]
### A clear and concise description of the issue.

I experienced no network installing Cloudflare

Creating a Cloudflared LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 117 was successfully created.
 ✓ Started LXC Container
 - Setting up Container OS...✗ No Network! ✗ No Network! ✗ No Network! ✗ No Network! ✗ No Network! ✗ No Network! ✗ No Network! ✗ No Network! ✗ No Network! ✗ No Network! 
✗ No Network After 10 Tries
 🖧  Check Network Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/5642737/78c5cc90-f57c-4a7d-b11c-b3fc97a0bee5)

**Comment by tteck** [comment]
I would assume that the error is evident – it appears to be related to network problems.

No issues here...

```
   ________                ________                    __
  / ____/ /___  __  ______/ / __/ /___ _________  ____/ /
 / /   / / __ \/ / / / __  / /_/ / __ `/ ___/ _ \/ __  / 
/ /___/ / /_/ / /_/ / /_/ / __/ / /_/ / /  /  __/ /_/ /  
\____/_/\____/\__,_/\__,_/_/ /_/\__,_/_/   \___/\__,_/   
                                                         
Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 112
Using Hostname: cloudflared
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Cloudflared LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.11 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Cloudflared
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by tteck** [comment]
The DHCP server is failing to assign an IP address to the container.

Since the problem does not seem to be caused by any issues with the script, it is now considered closed.
