### ISSUE TITLE
Issues with Proxmox8

### ISSUE THREAD

**Issue by angelgtc87** [tteck/Proxmox#1648]
Creating a Plex LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using SSD for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.0.14.94
 ✓ Internet Connected
 ✗ DNS Lookup Failure
 ✓ Updated Container OS
 - Installing Dependencies...
[ERROR] in line 24: exit code 100: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

**Comment by tteck** [comment]
> - When encountering the error message [ERROR] in line 24: exit code *: while executing command "$@" > /dev/null 2>&1, make sure to run the script in verbose mode to accurately determine the underlying issue.

**Comment by tteck** [comment]
> ✗ DNS Lookup Failure

It is highly probable that this is the underlying issue.

**Comment by angelgtc87** [comment]
okay, not sure why since my dns is working

Err:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libbrotli1 amd64 1.0.9-2build6
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libldap-2.5-0 amd64 2.5.11+dfsg-1~exp1ubuntu3
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2build4
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libssh-4 amd64 0.9.6-2build1
  Temporary failure resolving 'archive.ubuntu.com'
Err:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcurl4 amd64 7.81.0-1
  Temporary failure resolving 'archive.ubuntu.com'
Err:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 curl amd64 7.81.0-1
  Temporary failure resolving 'archive.ubuntu.com'
Err:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libldap-common all 2.5.11+dfsg-1~exp1ubuntu3
  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/brotli/libbrotli1_1.0.9-2build6_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.5-0_2.5.11%2bdfsg-1%7eexp1ubuntu3_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/r/rtmpdump/librtmp1_2.4%2b20151223.gitfa8646d.1-2build4_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libs/libssh/libssh-4_0.9.6-2build1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.81.0-1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.81.0-1_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-common_2.5.11%2bdfsg-1%7eexp1ubuntu3_all.deb  Temporary failure resolving 'archive.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
++ error_handler 17 '$STD apt-get install -y curl'
++ local exit_code=100
++ local line_number=17
++ local 'command=$STD apt-get install -y curl'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m17\033[m: exit code \033[01;31m100\033[m: while executing command \033[33m$STD apt-get install -y curl\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m17\033[m: exit code \033[01;31m100\033[m: while executing command \033[33m$STD apt-get install -y curl\033[m'

[ERROR] in line 17: exit code 100: while executing command $STD apt-get install -y curl
++ [[ 17 -eq 24 ]]
+ exit

**Comment by angelgtc87** [comment]
Just tried again and didn't set a domain name, and worked

Creating a Plex LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using SSD for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.0.14.124 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
