### ISSUE TITLE
Installation problem Radarr

### ISSUE THREAD

**Issue by jon4god** [tteck/Proxmox#1649]
### A clear and concise description of the issue.

Similar problem when installing Prowlarr LXC.
Sonarr, Plex and some others are installed without problems

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 106
Using Hostname: radarr
Using Disk Size: 4GB
Allocated Cores 2
Allocated Ram 1024
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Radarr LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 106 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 172.16.3.243 fd9b:9314:b9c4:4c97:bc66:2aff:fec9:5ef0 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Installing Radarr...
[ERROR] in line 24: exit code 8: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

**Comment by tteck** [comment]
> - When encountering the error message [ERROR] in line 24: exit code *: while executing command "$@" > /dev/null 2>&1, make sure to run the script in verbose mode to accurately determine the underlying issue.

**Comment by tteck** [comment]
BTW, no issue here...

```
    ____            __               
   / __ \____ _____/ /___  __________
  / /_/ / __ `/ __  / __ `/ ___/ ___/
 / _, _/ /_/ / /_/ / /_/ / /  / /    
/_/ |_|\__,_/\__,_/\__,_/_/  /_/     
                                     
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: radarr
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Radarr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Radarr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Radarr should be reachable by going to the following URL.
         http://192.168.86.253:7878 
```

**Comment by jon4god** [comment]
Oops! In verbose mode...

` ✓ Installed Dependencies
+ msg_info 'Installing Radarr'
+ local 'msg=Installing Radarr'
+ echo -ne ' - \033[33mInstalling Radarr...'
 - Installing Radarr...+ mkdir -p /var/lib/radarr/
+ chmod 775 /var/lib/radarr/
+ wget --content-disposition 'https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
--2023-07-27 21:06:17--  https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
Resolving radarr.servarr.com (radarr.servarr.com)... 172.64.111.8, 172.64.110.8, 2606:4700:e0::ac40:6f08, ...
Connecting to radarr.servarr.com (radarr.servarr.com)|172.64.111.8|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-27 21:06:18 ERROR 403: Forbidden.

++ error_handler 26 '$STD wget --content-disposition '\''https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'\'''
++ local exit_code=8
++ local line_number=26
++ local 'command=$STD wget --content-disposition '\''https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'\'''
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m26\033[m: exit code \033[01;31m8\033[m: while executing command \033[33m$STD wget --content-disposition '\''https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'\''\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m26\033[m: exit code \033[01;31m8\033[m: while executing command \033[33m$STD wget --content-disposition '\''https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'\''\033[m'

[ERROR] in line 26: exit code 8: while executing command $STD wget --content-disposition 'https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
++ [[ 26 -eq 24 ]]
+ exit`

**Comment by tteck** [comment]
The explanation is quite clear. The failure is occurring while attempting to resolve "radarr.servarr.com." DNS problems?

**Comment by jon4god** [comment]
Cloudflare DNS 
No problems before that. 
What are the recommended ones?
Can the fact that I'm territorially in Russia affect it?

**Comment by jon4god** [comment]
Yes, these installation links are blocked for access from Russia. Checked for other countries - everything is available.

With over 100 millon residents, it won't work.
