### ISSUE TITLE
Error Script Hyperion LXC

### ISSUE THREAD

**Issue by ViPeR5000** [tteck/Proxmox#1651]
### A clear and concise description of the issue.

error

`+ apt-get install -y hyperion
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hyperion : Depends: libpython3.10 but it is not installable
            Depends: libmbedtls12 but it is not installable
E: Unable to correct problems, you have held broken packages.
++ error_handler 29 '$STD apt-get install -y hyperion'
++ local exit_code=100
++ local line_number=29
++ local 'command=$STD apt-get install -y hyperion'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m29\033[m: exit code \033[01;31m100\033[m: while executing command \033[33m$STD apt-get install -y hyperion\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m29\033[m: exit code \033[01;31m100\033[m: while executing command \033[33m$STD apt-get install -y hyperion\033[m'

[ERROR] in line 29: exit code 100: while executing command $STD apt-get install -y hyperion
++ [[ 29 -eq 24 ]]
+ exit
`

**Comment by tteck** [comment]
> - Changing Linux distributions without confirming the proper functioning of default settings. 

Use Debian 11

**Comment by ViPeR5000** [comment]
> > * Changing Linux distributions without confirming the proper functioning of default settings.
> 
> Use Debian 11

Yes it works using Debian 11 sorry :) 

Thks for the fast replay

**Comment by oerix** [comment]
> > * Changing Linux distributions without confirming the proper functioning of default settings.
> 
> Use Debian 11

Will it ever be updated to support Debian 12 Bookworm, or is that not viable option? thanks
