### ISSUE TITLE
Alpine LXC SSH access

### ISSUE THREAD

**Issue by peracchi** [tteck/Proxmox#1654]
Is not working, maybe similar to #1254.

Take a look at https://github.com/tteck/Proxmox/discussions/1653

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

**Comment by tteck** [comment]
Did you try the solution found in #1254 ?

**Comment by tteck** [comment]
Added `alpine-install.sh` to resolve this issue. Create a new Alpine LXC.

**Comment by peracchi** [comment]
> Did you try the solution found in #1254 ?

Solution for #1254 do not apply because /etc/ssh/sshd_config do not even exists (openssh were not installed).
