### ISSUE TITLE
Nginx Proxy Manager installation

### ISSUE THREAD

**Issue by Sessix** [tteck/Proxmox#1655]
### A clear and concise description of the issue.

Error when running the Nginx script from Helper scripts.

[ERROR] in line 68: exit code 1: while executing command RELEASE=$(curl -s https://api.github.com/repos/NginxProxyManager/nginx-proxy-manager/releases/latest |
  grep "tag_name" |
  awk '{print substr($2, 3, length($2)-4) }')

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Scherm­afbeelding 2023-07-29 om 18 30 01](https://github.com/tteck/Proxmox/assets/130278923/1b714f7a-d1eb-48f0-864b-404dec22d1a4)

**Comment by tteck** [comment]
It seems that there are network issues, which may be related to DNS.

```
root@server:~# curl -s https://api.github.com/repos/NginxProxyManager/nginx-proxy-manager/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }'
2.10.3
```

**Comment by Sessix** [comment]
> 

{"message":"API rate limit exceeded for xxxxxxxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Any idea how to fix this?

**Comment by tteck** [comment]
Time...

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the person making requests.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-personal-accounts

As this issue is unrelated to the script, it is considered closed.
