### ISSUE TITLE
Error installing FileBrowser on Home Assistant Core LXC

### ISSUE THREAD

**Issue by Hoosier-IT** [tteck/Proxmox#1660]
### A clear and concise description of the issue.

When attempting to install FileBrowser  from an existing Home Assistant Core LXC install and error is received in console after executing the request 

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

                                                                                     
 - Installing FileBrowser...
[ERROR] in line 111: exit code 1: while executing command filebrowser config init -a '0.0.0.0' &> /dev/null

### Please provide detailed steps to reproduce the issue.

From proxmox 
Select the existing  Home Assistant Core LXC
Click Console
Paste bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homeassistant-core.sh)" press Enter
Select Yes to update question
Press Enter
Select Option 3 Install File Browser
Select Ok
![Capture](https://github.com/tteck/Proxmox/assets/8570961/86029de3-1a79-43a0-a1a8-9bf5171c7a25)

**Comment by tteck** [comment]
fixed

you may need to execute `rm -rf /usr/local/bin/filebrowser /root/filebrowser.db` and reboot before trying to install again
