### ISSUE TITLE
Kernel Clean Not Cleaning

### ISSUE THREAD

**Issue by oOStroudyOo** [tteck/Proxmox#1663]
### A clear and concise description of the issue.

The kernel cleaning script doesn't seem to be removing old kernels.
I've tried this multiple teams, rebooted node, tried uppercase and lower case Y

I guess there's not much to say, information is shown in the screenshot.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/111181956/b86d9d25-0620-4d4a-8087-800b8d799426)

### Please provide detailed steps to reproduce the issue.

Run the script: `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/kernel-clean.sh)"`

Press y to agree the risks

Press y to remove kernels

**Comment by tteck** [comment]
Working here...

```
    __ __                     __   ________               
   / //_/__  _________  ___  / /  / ____/ /__  ____ _____
  / ,< / _ \/ ___/ __ \/ _ \/ /  / /   / / _ \/ __ `/ __ \
 / /| /  __/ /  / / / /  __/ /  / /___/ /  __/ /_/ / / / /
/_/ |_\___/_/  /_/ /_/\___/_/   \____/_/\___/\__,_/_/ /_/

PVE Version: pve-manager/8.0.4/d258a813cfa6b390 (running kernel: 6.2.16-8-pve)

Current Kernel: 6.2.16-8-pve

'proxmox-kernel-6.2.16-6-pve' has been added to the remove Kernel list

 ✓ Kernel Search Completed

Would you like to remove the 1 selected Kernels listed above? [y/n]: y
 ✓ Successfully Removed Kernels
 ✓ Successfully Updated GRUB
 ✓ Done
root@server:~# 
```
🤷🏻‍♂️

**Comment by tteck** [comment]
Try executing the `apt autoremove` command

**Comment by oOStroudyOo** [comment]
They're cleared now.
My system must have been bugging.

Sorry for bothering you.
Have a great day.

**Comment by oOStroudyOo** [comment]
Resolved

**Comment by tteck** [comment]
Your current kernel was older than the ones you are trying to delete

**Comment by webmogul1** [comment]
I have just installed proxmox and kernel is 6.2.16-3-pve
Full upgrade is completed and not kernel is 6.2.16-6-pve

But when I run the script to clean old kernels, none is found. Shouldn't 6.12.16-3 be listed for removal?

![image](https://github.com/tteck/Proxmox/assets/5225701/cb76422e-75aa-4134-961f-23d7dd4d46bd)

**Comment by tteck** [comment]
What does the command `apt autoremove` show?

**Comment by webmogul1** [comment]
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by webmogul1** [comment]
another bit of info

![image](https://github.com/tteck/Proxmox/assets/5225701/2c540798-a584-4ccd-966f-3283226685d0)
