### ISSUE TITLE
Helper Script Menu

### ISSUE THREAD

**Issue by HTRamsey** [tteck/Proxmox#1673]
Would be cool to have a base menu script that allows you to choose between all the different scripts. Some useful features would be auto-updating list from repo, info on when a script was last run, etc. I'm imagining something similar to the [unifi easy update](https://community.ui.com/questions/UniFi-Installation-Scripts-or-UniFi-Easy-Update-Script-or-UniFi-Lets-Encrypt-or-UniFi-Easy-Encrypt-/ccbc7530-dd61-40a7-82ec-22b17f027776) script.
![Screenshot from 2023-08-08 15-47-50](https://github.com/tteck/Proxmox/assets/68555040/b2c98884-a52c-4b39-a347-64dcd5c5fd52)

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
