### ISSUE TITLE
NGINX proxy manager install script exits

### ISSUE THREAD

**Issue by elonden** [tteck/Proxmox#1675]
### A clear and concise description of the issue.

The installer does not complete and installation of the nginx proxy manager fails.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+ . /root/.bashrc
/root/.bashrc: line 6: PS1: unbound variable
+ exit

### Please provide detailed steps to reproduce the issue.

Excecute the installer script produces the same error every time

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one. 

https://github.com/tteck/Proxmox/issues/1574
