### ISSUE TITLE
zigbee2mqtt LXC wont start anymore.. very werid

### ISSUE THREAD

**Issue by koraysels** [tteck/Proxmox#1677]
### A clear and concise description of the issue.

connat run the zigbee 2 mqtt lxc container anymore

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```log
()
run_buffer: 322 Script exited with status 1
lxc_init: 844 Failed to run lxc.hook.pre-start for container "102"
__lxc_start: 2027 Failed to initialize container "102"
TASK ERROR: startup for container '102' failed
```

![Screenshot 2023-08-10 at 20 10 22](https://github.com/tteck/Proxmox/assets/2418853/adde92ca-0e5f-4b15-b57f-1b2f5f6e87aa)

### Please provide detailed steps to reproduce the issue.

it used to be working until a couple of weeks ago, I'm rebuilding my house so i did not notice right away.

**Comment by tteck** [comment]
Has the storage reached its capacity for the 102 LXC?

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by koraysels** [comment]
> Has the storage reached its capacity for the 102 LXC?

how do you check this ? this is what I see, 
![image](https://github.com/tteck/Proxmox/assets/2418853/88d4f5ff-8202-492e-901a-8553668728dc)


Sorry if this is not script related..  This i smy first time using LXC containers with proxmox

**Comment by koraysels** [comment]
no way! increasing size did work. WHat is taking up all that space though ?
