### ISSUE TITLE
Processor Microcode - some recent change broke script

### ISSUE THREAD

**Issue by peracchi** [tteck/Proxmox#1680]
### A clear and concise description of the issue.

Apparently a recent change on Proxmox VE Processor Microcode script broke it.

I just reinstalled Proxmox, updated it with Proxmox VE Post Install script and when tried to run Proxmox VE Processor Microcode script it appears to do nothing (see screenshots).

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![2023-08-11_221028](https://github.com/tteck/Proxmox/assets/1372058/e2b78e77-1fcd-4bb4-aab2-5b0cf9e7721b)

![2023-08-11_221029](https://github.com/tteck/Proxmox/assets/1372058/3cc4050b-284e-4f46-8cdc-db641d718abe)

**Comment by tteck** [comment]
No issue here

```
    ____                                               __  ____                                __
   / __ \_________  ________  ______________  _____   /  |/  (_)_____________  _________  ____/ /__
  / /_/ / ___/ __ \/ ___/ _ \/ ___/ ___/ __ \/ ___/  / /|_/ / / ___/ ___/ __ \/ ___/ __ \/ __  / _ \
 / ____/ /  / /_/ / /__/  __(__  |__  ) /_/ / /     / /  / / / /__/ /  / /_/ / /__/ /_/ / /_/ /  __/
/_/   /_/   \____/\___/\___/____/____/\____/_/     /_/  /_/_/\___/_/   \____/\___/\____/\__,_/\___/

 ✓ Current microcode updated early to revision 0xf4, date = 2023-02-23
Install the latest Processor Microcode (y/n)?
```
I made a change, please try again.

**Comment by peracchi** [comment]
Now it worked! Thanks!

![2023-08-11_222502](https://github.com/tteck/Proxmox/assets/1372058/ec081bf8-1982-4940-b043-7e6e8790ce4c)
