### ISSUE TITLE
Zigbee2mqtt problem at automatic startup

### ISSUE THREAD

**Issue by louanrobert** [tteck/Proxmox#1681]
### A clear and concise description of the issue.

Hello,

My problem comes from the automatic start-up with "rc-update".
Let me explain, when I start zigbee2mqtt with the "zigbee2mqtt" command, everything works fine and all my devices are visible. However, when the service starts automatically with "rc-update", I'm missing devices (only routers?) and the names I gave to those that are still there are missing.

Thanks in advance for your help

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Automatic :
![image](https://github.com/tteck/Proxmox/assets/33395798/8dfd0f4a-385d-40a3-8a26-d0c1eaf8a8e4)

Manual : 
![image](https://github.com/tteck/Proxmox/assets/33395798/3bdfbeae-d45b-4315-be49-65b3aa8d5337)

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

As this issue is unrelated to the script, it is considered closed.
