### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Sarnog** [tteck/Proxmox#1682]
### A clear and concise description of the issue.

When i copy and paste the bash script in the shell (PVE Shell, not a container or VM) it takes a while and then it returns to the state that i can typ something, without running the script.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Running proxmox 8 (latest)

**Comment by tteck** [comment]
It seems that you're facing a network problem, probably linked to DNS.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
