### ISSUE TITLE
Vaultwarden - can't reset admin Token

### ISSUE THREAD

**Issue by funky123** [tteck/Proxmox#1685]
### A clear and concise description of the issue.

I can't login with my documented admin_token, so i tryed to re-set it. via "bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/vaultwarden.sh)"" at container ssh

It seems like the token was set, but it dont works loging ito it.

i tryed to edit opt/vaultwarden/.env by hand, stopping an restarting vailtwarden.service but that changes anything.

How do i re-set the token?

I even tryed to set it "ABC" or something easy to avaiod typos .. nothing worked so far.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/12056510/4c7b2e65-9611-43a6-a896-b711a33f2a06)
![image](https://github.com/tteck/Proxmox/assets/12056510/43d74d52-7865-4f41-b83a-55b34103b146)
![image](https://github.com/tteck/Proxmox/assets/12056510/53da8df1-5aa8-44ea-b8b1-e792fd9d891b)

### Please provide detailed steps to reproduce the issue.

1. Try to access admin backend via correct url
2. use admin_token (you thing should work)
3. getting an error token would bewrong

**Comment by tteck** [comment]
The script runs without any problems from this end.  Changed the password without issues.

![Screenshot 2023-08-13 11 58 21 AM](https://github.com/tteck/Proxmox/assets/21342670/26de3e25-2d34-492e-80c5-77faece95d04)

Utilize the password you entered during the "Set the ADMIN_TOKEN" process.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by funky123** [comment]
@tteck okay, script may run without error but the effect - resetting admin token isn't as promised. since i cant edit the env file to solve the access issue, i am not quite sure if useing your scripts is the best idear. but i realy love them and honor your work! 

if you support other issues or not doesn't matter.

**Comment by tteck** [comment]
As I stated, in my case, resetting the admin token works as expected.

Is the value of `ADMIN_TOKEN=` changing when you use the script to reset the token?

**Comment by funky123** [comment]
Yes but i still can't login with that password

Before using script: 
```
ADMIN_TOKEN='$argon2i$v=19$m=65536,t=2,p=4$b1JaV0VhV0Q4SW1vdVFjUFZUWlB2NVJpUjlsNjRzQ3FrQWViRXNWd0pJOD0$q+lOHwezyBZrwQyFzZ9nAmNxuIJamKaTnPty3U>
ROCKET_ADDRESS=0.0.0.0
DATA_FOLDER=/opt/vaultwarden/data
DATABASE_MAX_CONNS=10
WEB_VAULT_FOLDER=/opt/vaultwarden/web-vault
WEB_VAULT_ENABLED=true
```
After using script:
```

ADMIN_TOKEN='$argon2i$v=19$m=65536,t=2,p=4$VjZYcVUwbDFNMHZEQis2ZHVEMk1lQi9hYmV6TmNsampGajZrbW5iTWFpQT0$Ve8BrzYiublbBzjWO9MqqI3wKVd14zdL2G2GEw>
...
```

**Comment by tteck** [comment]
And you're using the password you entered during the "Set the ADMIN_TOKEN" process?

**Comment by funky123** [comment]
> 

i found a file that conflicts

/opt/vaultwarden/data/config.json,

There is a admin Token that overwrides it ! (I migraded from a docker version)

so it is fixed now :)
