### ISSUE TITLE
can't update Photoprism

### ISSUE THREAD

**Issue by damda58** [tteck/Proxmox#1687]
### A clear and concise description of the issue.

Hi,
i have an error when i try to update my ct photoprism: 

[ERROR] in line 65: exit code 128: while executing command git clone https://github.com/photoprism/photoprism.git &> /dev/null

Can you help me ? 
Thks !

### Please provide detailed steps to reproduce the issue.

run "bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/photoprism.sh)"cd /opt/photoprism/"

actual version of photoprism ; Build [220704-5d7448d2]

**Comment by tteck** [comment]
What results do you observe when executing the command `git clone https://github.com/photoprism/photoprism.git` within the LXC console?

**Comment by damda58** [comment]
on /opt:

root@photoprism:/opt# git clone https://github.com/photoprism/photoprism.git 
fatal: destination path 'photoprism' already exists and is not an empty directory.
root@photoprism:/opt#
 

on another directory: 

root@photoprism:/opt/DC# git clone https://github.com/photoprism/photoprism.git 
Cloning into 'photoprism'...
remote: Enumerating objects: 86180, done.
remote: Counting objects: 100% (7110/7110), done.
remote: Compressing objects: 100% (548/548), done.
remote: Total 86180 (delta 6787), reused 6628 (delta 6561), pack-reused 79070
Receiving objects: 100% (86180/86180), 160.90 MiB | 10.26 MiB/s, done.
Resolving deltas: 100% (64986/64986), done.
root@photoprism:/opt/DC#

**Comment by tteck** [comment]
Run the script from the root directory

**Comment by tteck** [comment]
The script now ensures that it's in the root directory (`cd ~`) before continuing.

**Comment by damda58** [comment]
now i have this error :

⚠️  Ensure you set 2vCPU & 3072MiB RAM MIMIMUM!!! 

 ✓ Stopped PhotoPrism
 - Cloning PhotoPrism...
[ERROR] in line 66: exit code 128: while executing command git clone https://github.com/photoprism/photoprism.git &> /dev/null

**Comment by tteck** [comment]
Same error

**Comment by tteck** [comment]
Is there already a directory named `photoprism` in root? If so, remove it (`rm -rf photoprism`) and run the script

**Comment by damda58** [comment]
```
root@photoprism:~# ls -rtl
total 9
drwxr-xr-x  4 root root  4 May 31  2022 go
drwxr-xr-x 13 root root 38 Feb 22 22:20 photoprism
```

If i rename photoprism dir :
root@photoprism:~# mv photoprism/ photoprism_old
cloning is OK
building KO:
```
 ✓ Stopped PhotoPrism
 ✓ Cloned PhotoPrism
 - Building PhotoPrism...
[ERROR] in line 73: exit code 2: while executing command sudo ./scripts/build.sh prod /opt/photoprism/bin/photoprism &> /dev/null
```

**Comment by tteck** [comment]
Did you adhere to "⚠️ Ensure you set 2vCPU & 3072MiB RAM MIMIMUM!!!"? Your machine may require more resources for building.

**Comment by damda58** [comment]
yep 
![image](https://github.com/tteck/Proxmox/assets/6893451/9dbe6e62-0700-4b39-bcfd-547ce2cdc387)

**Comment by damda58** [comment]
sudo ./scripts/build.sh prod /opt/photoprism/bin/photoprism command  : 

```
root@photoprism:~/photoprism# sudo ./scripts/build.sh prod /opt/photoprism/bin/photoprism
Building PhotoPrism 230814-73fa7bbe8-Linux-AMD64 (prod)...
=> compiling "/opt/photoprism/bin/photoprism" with "go version go1.18.1 linux/amd64"
=> go build -ldflags -extldflags "-Wl,-rpath -Wl,$ORIGIN/../lib" -s -w -X main.version=230814-73fa7bbe8-Linux-AMD64 -o /opt/photoprism/bin/photoprism cmd/photoprism/photoprism.go
# github.com/photoprism/photoprism/internal/mutex
internal/mutex/atomic.go:9:22: undefined: atomic.Bool
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:125801:10: warning: function may return address of local variable [-Wreturn-local-addr]
125801 |   return pNew;
       |          ^~~~
sqlite3-binding.c:125761:10: note: declared here
125761 |   Select standin;
       |          ^~~~~~~
# github.com/photoprism/photoprism/internal/meta
internal/meta/json_exiftool.go:209:47: data.TakenAt.Sub(data.TakenAtLocal).Abs undefined (type time.Duration has no field or method Abs)
```

**Comment by tteck** [comment]
I recommend reviewing the [release notes](https://github.com/photoprism/photoprism/releases) to identify any updated dependency versions, like Go. It's advisable to perform this step for any application before upgrading to newer versions.

Or, backup, create a new Photoprism LXC and restore.

Edit: You are in the process of upgrading from a significantly outdated version (more than a year old).
