### ISSUE TITLE
Disable ipv6 not working with alpine LXC

### ISSUE THREAD

**Issue by chwoa** [tteck/Proxmox#1688]
### A clear and concise description of the issue.

Disabling ipv6 does not seem to work well with alpine 3.18 LXCs.
It correctly writes to /etc/sysctl.conf, but the init system does not seem to pick it up.
Running sysctl -p does make it take effect and it is a possible workaround.

### Please provide detailed steps to reproduce the issue.

- Create a LXC container and choose to disable ipv6
- ipv6 still shows in ip addr

_No response_

**Comment by tteck** [comment]
You are indeed correct. When adjustments are made to sysctl parameters by editing the configuration files within the `/etc/sysctl.conf` or `/etc/sysctl.d/` directory, it's necessary to apply those changes for them to become effective. The `sysctl -p` command is used to do just that. I'll update the `alpine-install.func` to call the `sysctl -p` command.

**Comment by chwoa** [comment]
Hey! That seems to work fine on the first boot, but it does not survive reboot...
In order to do so, I had to add the sysctl -p as a local service script:
```
cat "sysctl -p" > /etc/local.d/00_sysctl.start
chmod a+x /etc/local.d/00_sysctl.start
rc-update add local default
```

But to be honest I am not that sure if it is the best place to do so... It seems sysctl is not properly updated in LXCs as it is supposed to play with kernel parameters? Unless there is something off with my environment...

EDIT: It seems alpine does not update sysctl by default:
`rc-update add sysctl`
Sounds like a much better option :)

**Comment by tteck** [comment]
What about
```
echo "sysctl -w net.ipv4.ip_forward=1" > /etc/local.d/99_sysctl.start
chmod +x /etc/local.d/99_sysctl.start
rc-update add local default
```
Alpine is a strange creature to me.

**Comment by chwoa** [comment]
Oh! That sounds like it should work too, but it might be confusing to update it in a not standard place if anyone chooses to disable it in their containers.
In the meantime I did a pull request with the above, but please review carefully :)

**Comment by tteck** [comment]
The original code, which had `sysctl -p` already
```
  if [ "$DISABLEIPV6" == "yes" ]; then
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >>/etc/sysctl.conf
    $STD sysctl -p
  fi
```
Should persist across reboots.

**Comment by tteck** [comment]
```
  if [ "$DISABLEIPV6" == "yes" ]; then
    $STD sysctl -w net.ipv6.conf.all.disable_ipv6=1
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >>/etc/sysctl.conf
    $STD rc-update add sysctl default
  fi
```
This resolved the issue.
Thank you for your help!

**Comment by adra78** [comment]
Hi,
I'm having the same issue with release 3.18 running in proxmox.
Where did your put this ? 
```
  if [ "$DISABLEIPV6" == "yes" ]; then
    $STD sysctl -w net.ipv6.conf.all.disable_ipv6=1
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >>/etc/sysctl.conf
    $STD rc-update add sysctl default
  fi
```
Thanks for your help

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/ec08dae49cc0e675c0458937b1e414861bb2ac4a/misc/alpine-install.func#L24-L29
