### ISSUE TITLE
Hardware Transcoding does not work on Jellyfin LXC 

### ISSUE THREAD

**Issue by toczke** [tteck/Proxmox#1690]
### A clear and concise description of the issue.

I was unable to enable hardware transcoding on Vega 8 (Ryzen 2200G) using Jellyfin LXC on Proxmox 8 on HP G4 705 Mini. 

### Please provide detailed steps to reproduce the issue.

1. Deploy Jellyfin LXC with default options. 

Also I've found fix but don't know if it should apply to all Jellyfin LXC installations. Simple chmod 777 /dev/dri/* on LXC fixed issue.

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tjeerdhans** [comment]
` chmod 777 /dev/dri/*` is not preserved across reboots.

The jellyfin user needs to be in the sgx group, this fixed it for me:
```bash
usermod -a -G sgx jellyfin
```
