### ISSUE TITLE
is it possible to help with upgrades to debian bookworm

### ISSUE THREAD

**Issue by liv-in-sky** [tteck/Proxmox#1693]
### A clear and concise description of the issue.

tried to upgrade nginx-lxc but after upgrade nginx-lxc is broken

do you have any help descriptions ?

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/1498

**Comment by liv-in-sky** [comment]
thanx a lot - I wrote in the other thread because I have a problem
