### ISSUE TITLE
Heimdall Dashboard LXC only for English

### ISSUE THREAD

**Issue by Stoony1** [tteck/Proxmox#1695]
### A clear and concise description of the issue.

Heimdall Dashboard LXC only for English aviable language change not aviable. On the Original i can change it here in the LXC it is not work. Who is that problem?

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2023-08-15 212915](https://github.com/tteck/Proxmox/assets/28432944/6e0c7fcb-d8ba-4eb0-bf81-6d2549277266)

### Please provide detailed steps to reproduce the issue.

Install Heimdall Dashboard from here "https://tteck.github.io/Proxmox/" via LXC "Heimdall Dashboard LXC". Now try Change the language. Thats not work.

**Comment by tteck** [comment]
Apologies, I'm not aware of any specific actions to take in this situation. The files are there:
```
root@heimdalldashboard:/opt/Heimdall/resources/lang# ls
br  cs  da  de  el  en  es  fi  fr  hu  it  jp  ko  lmo  nl  no  pl  pt  ru  sl  sv  tr  uk  zh  zh_TW
```

**Comment by X-Anonymous-Y** [comment]
Heimdall needs [INTL PHP Extension](https://github.com/linuxserver/Heimdall/tree/v2.5.6#installing) maybe this is the problem

**Comment by Stoony1** [comment]
> Heimdall needs [INTL PHP Extension](https://github.com/linuxserver/Heimdall/tree/v2.5.6#installing) maybe this is the problem

The Dashboard is running an all is funktionally. The only Problem is that i cant chance the language. PhP 8.2 is running.

**Comment by Stoony1** [comment]
> /opt/Heimdall/resources/lang# ls

All files are aviable 
![Screenshot_1](https://github.com/tteck/Proxmox/assets/28432944/dfe067f4-8bcc-46ad-b3c6-b7ccd19095ad)

**Comment by tteck** [comment]
I plan to label the instructions as English-only and close this matter, given that I haven't discovered a solution. If I do come across a solution later on, I will reconsider the English-only restriction.

**Comment by tteck** [comment]
![Screenshot 2023-08-17 2 47 35 PM](https://github.com/tteck/Proxmox/assets/21342670/69559d5d-9d09-427f-b687-b7f5357472e7)

**Comment by SnakeEater96** [comment]
Die Parameter sollen bitte vor dem ersten Start von Heimdall in der .env bearbeitet werden da sonst Heimdall damit probleme hat im nachhinein per url aufgelöst zu werden (über Reverse Proxy)

      - DB_CONNECTION=mysql
      - DB_HOST=<IP ADDRESSE>
      - DB_PORT=<DB PORT>
      - DB_DATABASE=<DATABASE NAME>
      - DB_USERNAME=<DB USER>
      - DB_PASSWORD=<DB PASSWORT>

**Comment by xaimes** [comment]
The problem is in the addition of intl. You need to add php-intl to the installer and everything should work.

There is something like this in the Heimdall files:
```
        if (! class_exists('Locale')) {
            Log::info('PHP Extension Intl not found. Falling back to English language support only.');
            return json_encode(['en' => 'English']);
        }
```

A workaround for this problem is when selecting a language to examine the element and change the value en to e.g. pl in the select option and save.

![image](https://github.com/tteck/Proxmox/assets/36962784/70f2cf63-27f8-4127-a851-e2afbe9be999)

@tteck 
I think the only thing to do is to add here https://github.com/tteck/Proxmox/blob/6b31484fffc896e5eabec06119da11deb39d02fd/install/heimdalldashboard-install.sh
`$STD apt-get install -y php-intl`


Whereas I am not in a position to test it now.

**Comment by tteck** [comment]
It has been added.

**Comment by tteck** [comment]
![Screenshot 2023-12-11 6 19 34 AM](https://github.com/tteck/Proxmox/assets/21342670/e09248d1-d771-4e61-af8a-0321dc6b7b35)
