### ISSUE TITLE
Selecting advanced options on Rocky Linux builds a Debian LXC

### ISSUE THREAD

**Issue by LotusGuy** [tteck/Proxmox#1696]
### A clear and concise description of the issue.

Copy the build script for Rocky Linux.  Select Advanced option.
The options only give a choice of Debian or Ubuntu.

### Please provide detailed steps to reproduce the issue.

Select the Rocky Linux install.
Select Advanced options.

**Comment by tteck** [comment]
For Arch LXC, Devuan LXC, and Rocky Linux LXC, the `*-install.sh` scripts are absent, hence lacking "Advanced" settings. With the transition to reusable scripts, these will be eliminated. Default settings can be employed until they are removed.

**Comment by tteck** [comment]
Removed from "Operating System". No longer supported.

**Comment by LotusGuy** [comment]
Thank you for the update.  Will make my changes in Proxmox after building the default image.
