### ISSUE TITLE
qBittorrent LXC created in non-privileged mode

### ISSUE THREAD

**Issue by DmitryNefedov** [tteck/Proxmox#1697]
### A clear and concise description of the issue.

The main purpose of qBittorrent is to download files, some of which can be quite big (e.g. official Ubuntu images etc).

Using a non-privileged container does not allow binding mount points or mount NFS/SMB shares from another system.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`function default_settings() {
  CT_TYPE="1"`

### Please provide detailed steps to reproduce the issue.

1. Create a qBittorrent LXC using default settings. 
2. Try to bind mount points
3. Try to mount NFS/SMB share

**Comment by tteck** [comment]
Create the container privileged utilizing "Advanced" settings.

**Comment by tteck** [comment]
What is the issue with that?

**Comment by DmitryNefedov** [comment]
> Create the container privileged utilizing "Advanced" settings.

Why do some LXCs be privileged then? For E.g. Plex is created as privileged as a default

Sure, i can create it using Advanced settings or stop the container and change the conf file directly. 
However, it defeats the purpose of the default settings - the container is unusable when created with them.

**Comment by tteck** [comment]
Certain LXCs necessitate privileged access to operate, such as Zigbee2MQTT for the coordinator or Plex for hardware transcoding. Containers that can operate effectively without privileged access, like qBittorrent, will be assigned a default setting accordingly.

The responsibility doesn't lie with me for not exercising due diligence prior to running the script.

**Comment by DmitryNefedov** [comment]
I would argue that qBittorrent can not operate effectively without privileged access.
It is required to mount space to it. Yes, it installs successfully and doesnt through the error but it's unusable with default settings.
That's pretty much the same as not having it at all - it cannot be used.

Anyway, you've already closed the issue and failed to see my arguments. 
No point continuing the discussion.
P.S. Some of the scripts are pretty helpful, thank you.

**Comment by tteck** [comment]
It seems you're implying that privileged access is unattainable. However, had proper script vetting been performed, one would have recognized that the default settings were configured in unprivileged mode and could be changed to privileged access if necessary through Advanced settings, rookie mistake.

**Comment by Saik0Shinigami** [comment]
>I would argue that qBittorrent can not operate effectively without privileged access. It is required to mount space to it. 

No it's not? You can mount whatever you want from the proxmox host just fine without privileged mode.

Mount the share you want qbittorrent to talk to into proxmox, then share the mountpoint into the lxc. Perfectly workable and doesn't require privileged mode.

>Anyway, you've already closed the issue and failed to see my arguments.

You weren't making a valid argument. The application CAN and DOES function without privileged mode.

**Comment by DmitryNefedov** [comment]
I had an expectation that default settings are there for inexperienced users that allow them to create and use it straight away.
While you can mount to an unprivileged container, you also need to make sure the user/group is properly mapped with the Proxmox host. Otherwise, no downloads would be possible.
Moreover, NFS or SMB is not available for unprivileged one.

I've never mentioned that the application is not running or throwing errors.
This is not an issue for me personally I can use advanced or manually change the config. 
I've tried to improve the usability of the scripts for users who don't have enough knowledge.
You can call them rookie or noob but they will be using the default settings and hit the space limitation.

**Comment by tteck** [comment]
> I had an expectation that default settings are there for inexperienced users that allow them to create and use it straight away.

And it is, not everyone requires external storage; many individuals simply adjust the internal storage to match their requirements. Usually, more seasoned users are the ones who mount external drives or utilize NFS or SMB configurations.
