### ISSUE TITLE
Dashy failed install

### ISSUE THREAD

**Issue by Fearmonger** [tteck/Proxmox#1698]
Getting the following error attempting to install Dashy. I've attempted to install on 2 different machines and get the same error on both. I'm not exactly sure what additional info you would need but if you can let me know, I'll pull it together for you. Both servers are running 8.0.4.

found 0 vulnerabilities
+ n 16.20.1
  installing : node-v16.20.1
       mkdir : /usr/local/n/versions/node/16.20.1
       fetch : https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz
     copying : node/16.20.1
   installed : v16.20.1 (with npm 8.19.4)

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
If "node --version" shows the old version then start a new shell, or reset the location hash with:
hash -r  (for bash, zsh, ash, dash, and ksh)
rehash   (for csh and tcsh)
+ npm install -g pnpm
node:internal/modules/cjs/loader:1028
  const err = new Error(message);
              ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/nodejs/npm/lib/utils/unsupported.js
- /usr/share/nodejs/npm/lib/cli.js
- /usr/share/nodejs/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/usr/share/nodejs/npm/lib/utils/unsupported.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/npm/lib/utils/unsupported.js',
    '/usr/share/nodejs/npm/lib/cli.js',
    '/usr/share/nodejs/npm/bin/npm-cli.js'
  ]
}
++ error_handler 28 '$STD npm install -g pnpm'
++ local exit_code=1
++ local line_number=28
++ local 'command=$STD npm install -g pnpm'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m28\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD npm install -g pnpm\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m28\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD npm install -g pnpm\033[m'

[ERROR] in line 28: exit code 1: while executing command $STD npm install -g pnpm
++ [[ 28 -eq 24 ]]
+ exit

**Comment by tteck** [comment]
> - Changing Linux distributions without confirming the proper functioning of default settings. 

The script runs without any problems from this end using Debian. 

```
    ____             __         
   / __ \____ ______/ /_  __  __
  / / / / __  / ___/ __ \/ / / /
 / /_/ / /_/ (__  ) / / / /_/ / 
/_____/\__,_/____/_/ /_/\__, /  
                       /____/   
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: dashy
Using Disk Size: 6
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Dashy LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Installed Dashy
 ✓ Created Services
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Dashy should be reachable by going to the following URL.
         http://192.168.86.253:4000 
```
You're trying to use Ubuntu.
