### ISSUE TITLE
NocoDB LXC: Can't be reached after multiple installations

### ISSUE THREAD

**Issue by rolltidehero** [tteck/Proxmox#1699]
### A clear and concise description of the issue.

I have used your NocoDB LXC script 3 times now and each time it failed to load even though it stated that it completed successfully.

I tried 3 different ways:

1. Server A — LXC script with Default Settings
2. Server A —  LXC script with Custom Settings (More Disk, RAM, CPU, etc.)
3. Server B —  LXC script with Default Settings

This is the only script of your that hasn't worked.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/11590510/b15dd347-a376-43c4-8a8e-845a3d66c5c0)

### Please provide detailed steps to reproduce the issue.

_Run the command below in the Proxmox VE Shell._

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nocodb.sh)"`

**Comment by tteck** [comment]
fixed
