### ISSUE TITLE
PVE Post Install can't update on fresh install

### ISSUE THREAD

**Issue by zenodotus280** [tteck/Proxmox#1712]
### A clear and concise description of the issue.

Fresh install of Proxmox 8.0.2 on bare metal. When I run the script it fails at the update stage. When I run "apt update && apt upgrade" the upgrade fails because the enterprise repos are still active. When I select "no" to the install question it doesn't disable the Ceph repo and therefore causes the script to fail again. The only solution was to manually disable the Ceph repo then update and upgrade manually before running the script.

### Please provide detailed steps to reproduce the issue.

Install Proxmox.
Run the script.
Say yes or no to the Update prompt.
You will get kicked out to the shell within a few seconds once the update fails with no indication of what happened.

**Comment by tteck** [comment]
~Please post your APT Repositories. Proxmox may have changed the source locations.~

Disregard that, I've verified the repositories, and they are accurate.
https://pve.proxmox.com/wiki/Package_Repositories

**Comment by tteck** [comment]
> It is recommended to answer “yes” (y) to all options presented during the process.

If you had selected "yes" for "Enable 'ceph package repositories?" during setup, the ceph-quincy enterprise repository would have been disabled.

```
cat <<EOF >/etc/apt/sources.list.d/ceph.list
# deb http://download.proxmox.com/debian/ceph-quincy bookworm enterprise
deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
```
Perhaps a more detailed explanation is required.

**Comment by tteck** [comment]
The more detailed explanation is in **bold**

The 'Ceph Package Repositories' provides access to both the 'no-subscription'**(enabled)** and 'enterprise'**(disabled)** repositories. 
**Add** 'ceph package repositories?

**Comment by tteck** [comment]
This is now considered closed.

**Comment by zenodotus280** [comment]
Thanks for the quick response! I've been using these scripts for a couple years now.

> If you had selected "yes" for "Enable 'ceph package repositories?" during setup, the ceph-quincy enterprise repository would have been disabled.
> 
> ```
> cat <<EOF >/etc/apt/sources.list.d/ceph.list
> # deb http://download.proxmox.com/debian/ceph-quincy bookworm enterprise
> deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
> ```

Firstly, "Enable Ceph package respositories?" suggests that they are not enabled by default.

Secondly, If I have no intention of using Ceph why shouldn't the script disable _both_ of them? It is not intuitive that in order to disable the enterprise repo I must elect to *enable* it instead.

Lastly, I don't think that answering 'yes' to everything makes sense. The Testing Repo is probably not a common use case nor is using Ceph.

Thanks for your time!
