### ISSUE TITLE
Photoprism with MariaDB

### ISSUE THREAD

**Issue by besforttt** [tteck/Proxmox#1714]
### A clear and concise description of the issue.

Hey @tteck,

Thanks for all the scripts you are putting up and maintaining I've been using a lot of them!
Any chance you could add an option during the install process, or a different install script where photoprism uses mariadb server instead of sqlite3 ?
Or is there a simple way I can do that myself ?

Thanks in advance,

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
