### ISSUE TITLE
Photoprism script --upload-nsfw

### ISSUE THREAD

**Issue by bub4** [tteck/Proxmox#1717]
### A clear and concise description of the issue.

Hi tteck,

first of all thank you SO MUCH for the scripts. 
I once again hope, that you will get a millionaire on donations! 

Question:
The photoprism algorithm seems a bit weird.
It doesn't upload a picture of my (dressed) daughter jumping on a trampoline as it thinks it is offensive content. 
How and where can I adjust this option: PHOTOPRISM_UPLOAD_NSFW

I found this file in another ticket: '/var/lib/photoprism/.env'

I tried to nano this into the file:
PHOTOPRISM_UPLOAD_NSFW='yes'
but it seems not to work. 

Would be glad if you could help
Thanks a lot for your support and please apologize if this is a dump question!

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
