### ISSUE TITLE
Trying to Update SABnzbd

### ISSUE THREAD

**Issue by patchrick84** [tteck/Proxmox#1722]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the script from within the LXC, I get the following:

   _____ ___    ____              __        __
  / ___//   |  / __ )____  ____  / /_  ____/ /
  \__ \/ /| | / __  / __ \/_  / / __ \/ __  / 
 ___/ / ___ |/ /_/ / / / / / /_/ /_/ / /_/ /  
/____/_/  |_/_____/_/ /_/ /___/_.___/\__,_/   
                                              
Loading...
bash: line 27: variables: command not found
bash: line 28: color: command not found
bash: line 29: catch_errors: command not found
bash: line 69: start: command not found
bash: line 70: build_container: command not found
bash: line 71: description: command not found
bash: line 73: msg_ok: command not found
SABnzbd should be reachable by going to the following URL.
         http://:7777 

The LXC runs fine and the script works as expected from the host console.  This is the first time I've tried to run the update since creating the LXC, so I don't know if a recent change to Proxmox or otherwise broke it or if just never would have worked.  I'm running Proxmox 8.0.3 and the LXC is running Ubuntu 22.10, Kernel 6.2.16-4-pve.

And here's the verbose output:

```echo -e "Loading..."
Loading...
APP="SABnzbd"
var_disk="8"
var_cpu="2"
var_ram="2048"
var_os="debian"
var_version="12"
variables
bash: line 27: variables: command not found
color
bash: line 28: color: command not found
catch_errors
bash: line 29: catch_errors: command not found

function default_settings() {
  CT_TYPE="1"
  PW=""
  CT_ID=$NEXTID
  HN=$NSAPP
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET="dhcp"
  GATE=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="no"
  VERB="no"
  echo_default
}

function update_script() {
header_info
if [[ ! -d /opt/sabnzbd ]]; then msg_error "No ${APP} Installation Found!"; exit; fi
msg_info "Updating $APP"
systemctl stop sabnzbd.service
RELEASE=$(curl -s https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest | grep "tag_name" | awk '{print substr($2, 2, length($2)-3) }')
tar zxvf <(curl -fsSL https://github.com/sabnzbd/sabnzbd/releases/download/$RELEASE/SABnzbd-${RELEASE}-src.tar.gz) &>/dev/null
\cp -r SABnzbd-${RELEASE}/* /opt/sabnzbd &>/dev/null
rm -rf SABnzbd-${RELEASE}
cd /opt/sabnzbd
python3 -m pip install -r requirements.txt &>/dev/null
systemctl start sabnzbd.service
msg_ok "Updated $APP"
exit
}

start
bash: line 69: start: command not found
build_container
bash: line 70: build_container: command not found
description
bash: line 71: description: command not found

msg_ok "Completed Successfully!\n"
bash: line 73: msg_ok: command not found
echo -e "${APP} should be reachable by going to the following URL.
         ${BL}http://${IP}:7777${CL} \n"
SABnzbd should be reachable by going to the following URL.
         http://:7777```

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

Just running the script within the LXC shell produced the error.

**Comment by tteck** [comment]
Are you using SSH?

**Comment by patchrick84** [comment]
> Are you using SSH?

Nope.  This is in the Proxmox Web UI.

**Comment by tteck** [comment]
And executed  within the SABnzbd LXC console?

**Comment by patchrick84** [comment]
> And executed within the SABnzbd LXC console?

Yes.

![Screenshot 2023-08-23 at 5 37 58 PM](https://github.com/tteck/Proxmox/assets/56691001/0521202a-840b-4a88-866d-aa821a62866f)

**Comment by tteck** [comment]
The update script runs without any problems from this end. 

```
   _____ ___    ____              __        __
  / ___//   |  / __ )____  ____  / /_  ____/ /
  \__ \/ /| | / __  / __ \/_  / / __ \/ __  / 
 ___/ / ___ |/ /_/ / / / / / /_/ /_/ / /_/ /  
/____/_/  |_/_____/_/ /_/ /___/_.___/\__,_/   
                                              
 ✓ Updated SABnzbd
root@sabnzbd:~# 
```

**Comment by patchrick84** [comment]
Seems your script may have an incompatibility with an Ubuntu 22.10 LXC.  I created a new LXC with the default settings and the update script worked fine from within it.  So I guess I'll get to work on migrating over to a new LXC with Debian as the base.

I appreciate the work you put into these scripts, by the way.  It makes running a Proxmox environment a hell of a lot easier for an amateur like me.  So thanks for that.
