### ISSUE TITLE
Problem golang photoprism lxc

### ISSUE THREAD

**Issue by Surfer2010** [tteck/Proxmox#1723]
Hello, 

here the output off the installation process. Error at the end:

`    ____  __  ______  __________  ____  ____  _________ __  ___
   / __ \/ / / / __ \/_  __/ __ \/ __ \/ __ \/  _/ ___//  |/  /
  / /_/ / /_/ / / / / / / / / / / /_/ / /_/ // / \__ \/ /|_/ /
 / ____/ __  / /_/ / / / / /_/ / ____/ _, _// / ___/ / /  / /
/_/   /_/ /_/\____/ /_/  \____/_/   /_/ |_/___//____/_/  /_/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 0
Using Root Password: xxxxxxxxxxxx
Container ID: 141
Using Hostname: photoprism
Using Disk Size: 8
Allocated Cores: 4
Allocated RAM: 4096
Using Bridge: vmbr0
Using IP Address: 192.168.166.44/24
Using Gateway IP Address: 192.168.166.1
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: no
Creating a PhotoPrism LXC using the above advanced settings
 ✓ Using sixTB_isos for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 141 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.166.144
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.122.13
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 - Installing Golang...
[ERROR] in line 42: exit code 4: while executing command wget -q https://golang.org/dl/$RELEASE`

How can this be solved?
Hostsystem is a Terramaster NAS with proxmox installed and zfs filesystem.

Thanks a lot

**Comment by tteck** [comment]
What is the outcome of executing `wget -v https://golang.org/dl/go1.21.0.linux-amd64.tar.gz`?

**Comment by Surfer2010** [comment]
inside the lxc? or on the host?

**Comment by tteck** [comment]
LXC if you set a password, host if no password was set

**Comment by Surfer2010** [comment]
```
root@photoprism:~# wget -v https://golang.org/dl/go1.21.0.linux-amd64.tar.gz
--2023-08-23 23:45:00--  https://golang.org/dl/go1.21.0.linux-amd64.tar.gz
Resolving golang.org (golang.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'golang.org'
```

all the other scripts of you work on my system

**Comment by tteck** [comment]
It seems that you're facing a network problem, probably linked to DNS. Russia?

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
