### ISSUE TITLE
Alpine Error

### ISSUE THREAD

**Issue by iev4ry** [tteck/Proxmox#1727]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Unable to create vaultwarden LXC container. It worked fine yesterday, but today I'm receiving the error posted below. 

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"

Generates: 
```

WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)
ERROR: unable to select packages:
  bash (no such package):
    required by: world[bash]

[ERROR] in line 555: exit code 1: while executing command pct exec "$CTID" -- ash -c "apk add bash >/dev/null"
```

### Please provide detailed steps to reproduce the issue.

Run:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/vaultwarden.sh)"

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
 _    __            ____                          __         
| |  / /___ ___  __/ / /__      ______ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
 Alpine                                                 

Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: alpine-vaultwarden
Using Disk Size: 0.3
Allocated Cores: 1
Allocated RAM: 256
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Vaultwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Alpine-Vaultwarden
 ✓ Installed Web-Vault
 ✓ Started Alpine-Vaultwarden
 ✓ Customized Container
 ✓ Completed Successfully!

Alpine-Vaultwarden should be reachable by going to the following URL.
         http://192.168.86.253:8000 
```
It seems that you _may_ be facing a network problem. 
Or, follow this advice: `WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)`

**Comment by tteck** [comment]
BTW, you gave two different commands:
```
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"
```
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/vaultwarden.sh)"
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by iev4ry** [comment]
Thank you. It was a DNS issue.

**Comment by brianread108** [comment]
This fails for me also unless I choose "priviledged" in the advanced options.

**Comment by tteck** [comment]
What's the error message?

**Comment by brianread108** [comment]
As Above:
`WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)
ERROR: unable to select packages:
  bash (no such package):
    required by: world[bash]

[ERROR] in line 555: exit code 1: while executing command pct exec "$CTID" -- ash -c "apk add bash >/dev/null"
`

In my case it happened while installing the "empty" Alpine LXC from your script, rather than from the vaultwarden one.
