### ISSUE TITLE
qbittorrent config files

### ISSUE THREAD

**Issue by PozoSer** [tteck/Proxmox#1728]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

I've just installed qbittorrent using the script. Now I'd like to take a look at the config files. According to what I see online, config files should be in ~/.config/qBittorrent/, but there is no folder called qBittorrent on ./config. Where does the script places the config file?

Thanks

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

`/.config/qBittorrent/qBittorrent.conf`
