### ISSUE TITLE
Backup error for Docker LXC

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#1729]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

I'm trying to do a backup of my LXC and get the following error message :

`ERROR: Backup of VM 2000 failed - command 'rsync --stats -h -X -A --numeric-ids -aH --delete --no-whole-file --sparse --one-file-system --relative '--exclude=/tmp/?*' '--exclude=/var/tmp/?*' '--exclude=/var/run/?*.pid' /proc/1086712/root//./ /var/tmp/vzdumptmp1496453_2000' failed: exit code 23
`
I tried the following command :
`rsync --stats -h -X -A --numeric-ids -aH --delete --no-whole-file --sparse --one-file-system --relative --verbose '--exclude=/var/lib/php/sessions/' '--exclude=/tmp/?*' '--exclude=/var/tmp/?*' '--exclude=/var/run/?*.pid' /proc/1086712/root//./ /var/tmp/vzdumptmp1458788_2000`

but got the following response :

```
rsync: [generator] set_acl: sys_acl_set_file(var/log/journal, ACL_TYPE_ACCESS): Operation not supported (95)
rsync: [generator] set_acl: sys_acl_set_file(var/log/journal/92a1899cf71b421195d2bace02687f72, ACL_TYPE_ACCESS): Operation not supported (95)
rsync: [generator] set_acl: sys_acl_set_file(var/log/journal/92a1899cf71b421195d2bace02687f72/system.journal, ACL_TYPE_ACCESS): Operation not supported (95)
rsync: [generator] set_acl: sys_acl_set_file(var/log/journal/92a1899cf71b421195d2bace02687f72/system@0006037b01295803-44461770961afd06.journal~, ACL_TYPE_ACCESS): Operation not supported (95)
```
This might be out of the scope of your project but as you are in my eyes one of the top PVE specialist, you might know the answer quickly. 

Please note that when I shutdown the LXC, the snapshot is done without any problems. 

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Is the filesystem type ZHA?

**Comment by Jens-Wymeersch** [comment]
I'm not totally sure what you mean. Basically ZFS is used as my storage pool.

**Comment by tteck** [comment]
Haha, no worries! I'm currently assisting someone with their zigbee installation simultaneously.

**Comment by tteck** [comment]
Is the fuse-overlayfs storage driver being utilized in Docker?

**Comment by tteck** [comment]
You might find this helpful: https://forum.proxmox.com/threads/lxc-backup-faild-exit-code-23.79572/.

As this issue is unrelated to the script, it is considered closed.
