### ISSUE TITLE
Suggestion: Using Mosquitto Repository instead Debian Repository

### ISSUE THREAD

**Issue by skl283** [tteck/Proxmox#1735]
Hi @tteck,

thank you again for your great scripts! I have a suggestion of using Mosquitto in latest Version: in yor scripts you using the Debian Repo, but mosquitto delivers its own repository server - also for bookworm.

please look at https://mosquitto.org/blog/2013/01/mosquitto-debian-repository/ - also a bookworm repo file is availale.

br
sash

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
