### ISSUE TITLE
Plex memory leak, till stuck.

### ISSUE THREAD

**Issue by firestaerter3** [tteck/Proxmox#1737]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

All my Linux containers are working great, I truly appreciate all the effort going into this, thanks! However, except for Plex.. every few days, it hangs and I need to manually reboot the Linux container. The memory seems to be leaking slowly to the point where I limited my memory (4GB).

At the spikes of the screenshot I rebooted manually and than the memory is back to nearly zero.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="1044" alt="Screenshot 2023-08-27 at 20 26 00" src="https://github.com/tteck/Proxmox/assets/17737913/7ef03a07-4d34-4f63-a4ab-23d22d6191a8">

### Please provide detailed steps to reproduce the issue.

Installed Plex via the script.

**Comment by tteck** [comment]
It's unfortunate that you're dealing with a memory leak problem, but there's no connection to the script in this case. As a result, the matter is considered closed.

**Comment by tteck** [comment]
My primary focus revolves around the development of application LXCs, and I'm not specialized in providing support for operational issues that may arise with these applications.

**Comment by firestaerter3** [comment]
Ok, so it 100% cannot be caused by the script; I'll investigate further on Plex side. Thnx
