### ISSUE TITLE
Docker install script - Directories ?

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#1743]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

I love your script without any doubt ! Just a quick question, where are the docker, docker-compose and Portainer directories located ?

BR,
Jens

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

NA

### Please provide detailed steps to reproduce the issue.

NA

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
