### ISSUE TITLE
Mqtt LXC

### ISSUE THREAD

**Issue by cryd-s** [tteck/Proxmox#1747]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

See Screenshot ;(

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/47699362/40c89761-5c5c-415a-8d00-94f409e1166e)

![image](https://github.com/tteck/Proxmox/assets/47699362/0b39d25d-753d-4b68-a622-811e11b3e360)

### Please provide detailed steps to reproduce the issue.

Installed via the lxc script - advanced to set ip and container id - unpriviled container

**Comment by tteck** [comment]
Try `chmod 644 /etc/mosquitto/passwd`

**Comment by cryd-s** [comment]
perfect ! it works is it my fail or a fail in the script

**Comment by tteck** [comment]
It's not your fault, sometimes changes happen unexpectedly. It appears that something has been altered somewhere along the line. I'll work on getting the ~script~ instructions rectified.
