### ISSUE TITLE
can't create container with Advanced settings

### ISSUE THREAD

**Issue by Forsskieken** [tteck/Proxmox#175]
I'm trying the MotionEye v3 script with minor issue.

It generates an error if one doesn't enter the network IPv4/CIDR (192.168.1.155/24)
The gateway can be entered just like 192.168.1.1

pct create <vmid> <ostemplate> [OPTIONS]
[ERROR] 255@132 A problem occured while trying to create container.

**Comment by tteck** [comment]
I've never tried setting a VLAN with DHCP. Please try again to see if I fixed the issue

**Comment by tteck** [comment]
Oh, thanks for reporting the issue!
