### ISSUE TITLE
dashy does not show changes

### ISSUE THREAD

**Issue by seebaer1976** [tteck/Proxmox#1755]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

after installing the dashy containers and setup and creating the new sections, new items and then clicking 'save to disk'. only the dashboard of the first installation is loaded/displayed.

Even waiting 2 hours, then reloading the browser and deleting the browser cache only brings back the start screen of the initial installation.
a complete container reboot brings the same result.

but when you look at the conf.yml in /dashy/public, all my changes are there.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Try this:
After getting everything setup the way you want in interactive mode and saved to disk, go into update configuration and rebuild application.

**Comment by tteck** [comment]
Sounds like this https://github.com/tteck/Proxmox/pull/1670 isn't working?

**Comment by seebaer1976** [comment]
> Sounds like this #1670 isn't working?

yep, dashy auto rebuild doesn't seem to be working.

After running the command 'bash -c '$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/dashy.sh)' ' in the container console and the container itself restarted, my changes are displayed.

thank you for the quick help

**Comment by tteck** [comment]
I changed the documentation on the site.
revert https://github.com/tteck/Proxmox/pull/1670
