### ISSUE TITLE
NPM - unable to locate "app-images"

### ISSUE THREAD

**Issue by buczi11** [tteck/Proxmox#1757]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi, 
I'm not sure if this is a bug, as the script was successful, but maybe it will help to improve it.

All the best tteck!

*Subnet 10.10.30.0/24 set I have for DNS AdGuard "10.10.30.105"
First time I installed NPM and I got error "No internet connected".
Probably this is an error with me and the settings on the MT firewall

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![20230903356](https://github.com/tteck/Proxmox/assets/6137813/92363d6c-332b-4463-ac0c-0c84108a250e)

**Comment by tteck** [comment]
Thanks for the information, but it seems that the issue is with https://github.com/NginxProxyManager/nginx-proxy-manager and not with the script itself.
