### ISSUE TITLE
Error after running update wikijs, bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/wikijs.sh)"

### ISSUE THREAD

**Issue by NL-Tristan** [tteck/Proxmox#1760]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

If I want to update Wikijs from another directory, I get a error message.
I want to update Wikijs with the command in console:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/wikijs.sh)"

After this command, I get a error:

 ✓ Stopped Wikijs
 - Backing up Data...cp: target '/root/data-backup' is not a directory

[ERROR] in line 63: exit code 1: while executing command cp -R /opt/wikijs/{db.sqlite,config.yml,/data} ~/data-backup

I was in directory:  /root/utils 

There is a little bug in the script of https://github.com/tteck/Proxmox/raw/main/ct/wikijs.sh

msg_info "Backing up Data"
mkdir -p data-backup
cp -R /opt/wikijs/{db.sqlite,config.yml,/data} ~/data-backup
msg_ok "Backed up Data"

mkdir -p data-backup     
must be: 
mkdir -p ~/data-backup

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

At the console of wikijs server
$ cd /root/utils 
$  bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/wikijs.sh)"

Do you want to update wikijs?    Yes.

Then I get a Error:
- Backing up Data...cp: target '/root/data-backup' is not a directory

**Comment by tteck** [comment]
fixed
