### ISSUE TITLE
UniFi Network Application Error on Install

### ISSUE THREAD

**Issue by Mosher23** [tteck/Proxmox#1761]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

So I am running the script to install latest UniFi Network Application 7.5 

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

in all default mode
<img width="1181" alt="image" src="https://github.com/tteck/Proxmox/assets/8256425/560c2201-beaf-49c2-88a6-c7c7dc0210c3">
in verbose mode
<img width="1627" alt="Screenshot 2023-09-05 at 10 20 33" src="https://github.com/tteck/Proxmox/assets/8256425/51eab484-6883-4c4f-a6c0-372df343d346">

### Please provide detailed steps to reproduce the issue.

Just run the script and get the error

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
   __  __      _ _____ 
  / / / /__   (_) __(_)
 / / / / __ \/ / /_/ / 
/ /_/ / / / / / __/ /  
\____/_/ /_/_/_/ /_/   
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: password
Container ID: 112
Using Hostname: unifi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Unifi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed OpenJDK
 ✓ Installed MongoDB
 ✓ Installed UniFi Network Application
 ✓ Cleaned
 ✓ Completed Successfully!

Unifi should be reachable by going to the following URL.
         https://192.168.86.253:8443 
```

**Comment by tteck** [comment]
Perhaps the problem was related to the Unifi repository. I recommend giving it another try.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
