### ISSUE TITLE
install/docker-install.sh missing https port on 9443

### ISSUE THREAD

**Issue by newmy-de** [tteck/Proxmox#1763]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

due to https://docs.portainer.io/start/upgrade/docker:
_Starting from Portainer CE 2.9 and BE 2.10, HTTPS is enabled by default on port 9443. These instructions will configure Portainer to use 9443 for HTTPS and do not expose 9000 for HTTP. If you need to retain HTTP access, you can add:
-p 9000:9000
to your command._

The script only enables the non https port on 9000.

Please think about adding port 9443 additionally.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/42513464/1a340972-ca82-45bb-83da-262d16658509)

**Comment by tteck** [comment]
Following the LXC creation, users can customize ports as needed, similar to how it's done with any Docker container.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by bshor** [comment]
I agree it's very confusing as all the documentation refers to port 9443. I banged my head on the wall until I searched the issues here. I think the default should be to enable HTTPS on 9443.

Otherwise, thank you for creating such an easy one-stop shop installation!

**Comment by tteck** [comment]
Done

**Comment by chpego** [comment]
In the Alpine-Docker LXC, the portainer port is 9000
https://github.com/tteck/Proxmox/blob/d6abb580d2e0fde1d58abfdf16659b9f1d3621b5/install/alpine-docker-install.sh#L40-L42

**Comment by chpego** [comment]
https://github.com/tteck/Proxmox/commit/737240916ee8daab0e54ad2f45642ef3f89f46a7
