### ISSUE TITLE
Nextcloudpi Issue Error in line 23

### ISSUE THREAD

**Issue by stefan-ffr** [tteck/Proxmox#1769]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Get an error, when executing the script and it abort the installation.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

[ERROR] in line 23: exit code 1: while executing command $STD bash <(curl -fsSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh)
++ [[ 23 -eq 24 ]]
+ exit

### Please provide detailed steps to reproduce the issue.

Just run the script in verbose mode

**Comment by tteck** [comment]
> - Changing Linux distributions without confirming the proper functioning of default settings.
