### ISSUE TITLE
UpTimeKuma - Install fail

### ISSUE THREAD

**Issue by larod241** [tteck/Proxmox#177]
hello, 
Installation of uptime kuma fails.
I tried several times, and the error is the same.
Regards
![Capture d’écran 2022-04-19 à 21 25 57](https://user-images.githubusercontent.com/20423481/164080969-b3da43a5-3d0d-4123-85ce-71ea43586940.png)

**Comment by tteck** [comment]
Would you be so kind and try again?

**Comment by larod241** [comment]
It's gooooood now ! 
Thanks for the quick modif ! 
![Capture d’écran 2022-04-19 à 21 57 06](https://user-images.githubusercontent.com/20423481/164085535-76f2b485-4d6f-4b55-9714-5c4402d95349.png)

**Comment by tteck** [comment]
Thank you for reporting the issue!
