### ISSUE TITLE
default password on audiobookshelf

### ISSUE THREAD

**Issue by PozoSer** [tteck/Proxmox#1771]
Hi tteck, 

Huge thanks for your work. I have installed the audiobookshelf but I don't see user/pass on the script list as in other containers. I have also tried with the audiobook-documentation default (user:root, no pass) with no success. 

Thanks

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

The credentials are whatever you used at setup

![Screenshot 2023-09-08 5 24 48 AM](https://github.com/tteck/Proxmox/assets/21342670/8e9bad6e-6bff-46fc-9184-172837999c02)

**Comment by tteck** [comment]
If you are being prompted for LXC credentials and you didn't set them up during the creation through "Advanced" settings, it indicates that the installation wasn't completed successfully. Remain in the shell until you encounter the message " ✓ Completed Successfully!"
