### ISSUE TITLE
Homarr - ran update, now cannot load dashboard

### ISSUE THREAD

**Issue by memilanuk** [tteck/Proxmox#1774]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While using Homarr dashboard, I noted a blue dot on the menu stack (upper right corner).  Turned out to be Homarr alerting me that there was a new release.  Went to the main tteck Proxmox list, copied the script line to run inside the LXC to update it, and did so.  Script returned message saying everything was already up to date (I'm guessing the latest tteck lxc < latest homarr update?).  Went back to the dashboard, and reloaded the page.  Nothing.  No response using either the host name or ip address on the tailscale network, or on the LAN address (i.e. 192.168.1.107:3000).  Rebooted the LXC, still nothing.  Checked the network interfaces and both the lan and tailscale networks look to be up and functioning normally.

What options do I have to recover this LXC without losing all the icons I have setup?

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
What is the output of `systemctl status homarr`?

**Comment by memilanuk** [comment]
```
root@homarr:~# systemctl status homarr
x homarr.service - Homarr Service
     Loaded: loaded (/etc/systemd/system/homarr.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-09-08 17:35:12 PDT; 17min ago
   Duration: 724ms
    Process: 467 ExecStart=/usr/bin/yarn start (code=exited, status=127)
   Main PID: 467 (code=exited, status=127)
        CPU: 850ms

Sep 08 17:35:12 homarr systemd[1]: Starting homarr.service - Homarr Service...
Sep 08 17:35:12 homarr systemd[1]: Started homarr.service - Homarr Service.
Sep 08 17:35:12 homarr yarn[475]: command not found: next
Sep 08 17:35:12 homarr systemd[1]: homarr.service: Main process exited, code=exited, status>
Sep 08 17:35:12 homarr systemd[1]: homarr.service: Failed with result 'exit-code'.
lines 1-13/13 (END)
```

**Comment by tteck** [comment]
Sounds like it didn't finish updating?
Run the following commands, one at a time.
```
systemctl stop homarr
cd /opt/homarr
cp -R data data-backup
git stash
git pull
yarn install
yarn build
cp -R data-backup/* data
rm -rf data-backup
systemctl start homarr
```

**Comment by tteck** [comment]
If `Already up to date.` after `git pull` go directly to `systemctl start homarr`

```
root@homarr:~# systemctl stop homarr
root@homarr:~# cd /opt/homarr
root@homarr:/opt/homarr# git stash
Saved working directory and index state WIP on dev: 12230bd9 🌐 Merge pull request #1364 from ajnart/i10n_dev
root@homarr:/opt/homarr# git pull
Already up to date.
root@homarr:/opt/homarr# systemctl start homarr
root@homarr:/opt/homarr# 
```
It may take a minute for Homarr page to show

**Comment by memilanuk** [comment]
Well, that brought the dashboard back up... but blank.

**Comment by tteck** [comment]
Blank as in a fresh install?

**Comment by memilanuk** [comment]
Yup.  I didn't have that many apps set up yet, so not the end of the world <shrug>

**Comment by tteck** [comment]
There must be a `.json` file that needs to be backed up and restored. I'll see what I can find.

**Comment by tteck** [comment]
Fixed update, with backup and restore data directory. Updated my previous [update instructions](https://github.com/tteck/Proxmox/issues/1774#issuecomment-1712368575).

**Comment by tteck** [comment]
Sorry for any inconvenience.
