### ISSUE TITLE
Most recent update to add-tailscale script ignores switch

### ISSUE THREAD

**Issue by memilanuk** [tteck/Proxmox#1775]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Script to add tailscale to LXCs changed to add menu, but now ignores command-line switch that specifies which container to target.

The command provided on the web page (https://tteck.github.io/Proxmox/) provides an option at the end to specify a container to target.  But with the new menu system, the script appears to ignore the command line switch and the user has to scroll through the entire list even after specifying the container ID at the command line.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/add-tailscale-lxc.sh)" -s 106

**Comment by tteck** [comment]
The web page was updated when the [commit](https://github.com/tteck/Proxmox/commit/186230591ba9da31100ac986411c2ce4dc4299da) was pushed. I have moved away from command-line tags.
