### ISSUE TITLE
NPM fails DNS-01 challenge due to missing python package

### ISSUE THREAD

**Issue by t0rb3n** [tteck/Proxmox#1790]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Clean install of nginx proxy manager fails when trying to add a Lets Encrypt Certificate of a domain via Porkbun DNS challenge. 

The issue is resolved by installing issuing following command: 
`pip3 install certbot_dns_porkbun`

I am not sure if it's the best way to just install this package for everyone regarding security and 3rd party packages. 
Maybe an disclaimer when installing or somewhere would be sufficient. 
But that's up to you to decide.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Following error is shown: 

	Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-5" --agree-tos --email "xxxxxxx" --domains "xxxxxx" --authenticator dns-porkbun --dns-porkbun-credentials "/etc/letsencrypt/credentials/credentials-5"
	usage: 
	  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
	
	Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
	it will attempt to use a webserver both for obtaining and installing the
	certificate. 
	certbot: error: unrecognized arguments: --dns-porkbun-credentials /etc/letsencrypt/credentials/credentials-5

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`
    
    
Using `certbot plugins` we see there is no entry for porkbun: 
```
root@nginxproxymanager:/var/www/html# certbot plugins
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* dns-cloudflare
Description: Obtain certificates using a DNS TXT record (if you are using
Cloudflare for DNS).
Interfaces: Authenticator, Plugin
Entry point: dns-cloudflare =
certbot_dns_cloudflare._internal.dns_cloudflare:Authenticator

* standalone
Description: Spin up a temporary webserver
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
 

After installing using `pip3 install certbot_dns_porkbun`
```
root@nginxproxymanager:/var/www/html# certbot plugins
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* dns-cloudflare
Description: Obtain certificates using a DNS TXT record (if you are using
Cloudflare for DNS).
Interfaces: Authenticator, Plugin
Entry point: dns-cloudflare =
certbot_dns_cloudflare._internal.dns_cloudflare:Authenticator

* dns-porkbun
Description: Obtain certificates using a DNS TXT record for Porkbun domains
Interfaces: Authenticator, Plugin
Entry point: dns-porkbun = certbot_dns_porkbun.cert.client:Authenticator

* standalone
Description: Spin up a temporary webserver
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

### Please provide detailed steps to reproduce the issue.

1. Have a domain at porkbun
2. Go to SSL Certificates (/nginx/certificates)
3. Enter everything, toggle DNS challenge and select Porkbun.
4. Hit save and wait for it to fail

**Comment by tteck** [comment]
Fixed, thanks

**Comment by Stephan-4711** [comment]
It's the same problem with IONOS.
I manually installed:
pip3 install certbot_dns_ionos
then it's working. Maybe all DNS challenge provider are affected?

**Comment by tteck** [comment]
There are 100's of certbot dns packages. It's not unusual to have to install your preferred DNS providers package. 
https://pypi.org/search/?q=certbot-dns&o=

**Comment by Stephan-4711** [comment]
Ok, opnsense firewall and my proxmox host it self, had all dns challenge provider included and the error it self didn't point to a missing package.
