### ISSUE TITLE
Pi.Alert not updating

### ISSUE THREAD

**Issue by FredericMa** [tteck/Proxmox#1806]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing Pi.Alert I noticed it wasn't updating / scanning.
I read the installation instructions and noticed crontab being empty. Step 5.8 on this page: https://github.com/leiweibau/Pi.Alert/blob/main/docs/INSTALL.md

Executing this command 
`(crontab -l 2>/dev/null; cat /opt/pialert/install/pialert.cron) | crontab -` 
and changing the paths afterwards in the crontab config to use `/opt/pialert/` got things going.

I also did an installation using the default settings but it had the same result.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Fixed in the script

The provided solution is intended to address the issue and can be used by anyone looking to resolve a similar problem with their installation.
```
sed -i 's/~/\/opt/g' /opt/pialert/install/pialert.cron
(crontab -l 2>/dev/null; cat /opt/pialert/install/pialert.cron) | crontab -
```

**Comment by xekil** [comment]
Hello, same problem, good solution, thank you
