### ISSUE TITLE
Advanced option to select bridge other than default vmbr0

### ISSUE THREAD

**Issue by A-vesalius** [tteck/Proxmox#181]
Request to add an option to select a bridge other than vmbr0. Currently, the v3 install script fails for me on nodes without a vmbr0.

```
run_buffer: 321 Script exited with status 2
lxc_create_network_priv: 3413 No such device - Failed to create network device
lxc_spawn: 1843 Failed to create the network
__lxc_start: 2074 Failed to spawn container "101"

TASK ERROR: startup for container '101' failed```

**Comment by tteck** [comment]
which script would you want me to start with?

**Comment by A-vesalius** [comment]
I was attempting the docker LXC install, so there would be great. thanks for the quick response. I was just about to add a vmbr0 back to the node and then change it in the LXC network config to the correct bridge after the fact.

**Comment by tteck** [comment]
Try
```

```

**Comment by A-vesalius** [comment]
working perfectly. thanks for the unexpectedly fast turnaround.
