### ISSUE TITLE
Proxmox VE Helper Scripts with Man in the Middle HTTPS

### ISSUE THREAD

**Issue by peracchi** [tteck/Proxmox#1814]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Proxmox VE Helper Scripts works until some operation like `apk add` is used then it fails because needed certificates for MITM are not present.

For example, using Docker LXC with Alpine Linux:

- Shell on PVE
`root@pve:~# bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-docker.sh)"`

Here we can see the error caused by the lack of the MITM certificates:

```
    ____             __            
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 Alpine
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: r00t-PwD
Container ID: 100
Using Hostname: alpine-docker
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: no
Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 100 was successfully created.
 ✓ Started LXC Container
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)
486B009F977F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/community: Permission denied
ERROR: unable to select packages:
  bash (no such package):
    required by: world[bash]

[ERROR] in line 555: exit code 1: while executing command pct exec "$CTID" -- ash -c "apk add bash >/dev/null"

root@pve:~#

```

Then, to continue I do:

- Shell on Container at PVE
`alpine-docker:~# vi /etc/apk/repositories`
[ change ]
https://dl-cdn.alpinelinux.org/alpine/v3.18/main
https://dl-cdn.alpinelinux.org/alpine/v3.18/community
[ to ]
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
```
alpine-docker:~# apk --no-check-certificate add openssh
alpine-docker:~# rc-update add sshd
alpine-docker:~# sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
alpine-docker:~# service sshd start

```
- SSH/SCP
[ upload certificate-1.crt and certificate-2.crt ]
```
alpine-docker:~# apk --no-check-certificate add ca-certificates
alpine-docker:~# mv /root/certificate-1.crt /usr/local/share/ca-certificates/
alpine-docker:~# mv /root/certificate-2.crt /usr/local/share/ca-certificates/
alpine-docker:~# update-ca-certificates

```

From now on I can perform any operation involving HTTPS without errors but the script did not execute until the end.

Is there a way to pass the certificates to the script before execution or how to make the script continue executing to leave the container as intended?

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    ____             __            
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 Alpine
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: alpine-docker
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker
Would you like to add Portainer? <y/N> 
Would you like to add Docker Compose? <y/N> 
 ✓ Customized Container
 ✓ Completed Successfully!
```
> WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)

Can you open `https://dl-cdn.alpinelinux.org/alpine/v3.18/main` in your browser?

**Comment by tteck** [comment]
With password and Enable Root SSH Access

```
    ____             __            
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 Alpine
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: password
Container ID: 113
Using Hostname: alpine-docker
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: no
Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker
Would you like to add Portainer? <y/N> 
Would you like to add Docker Compose? <y/N> 
 ✓ Completed Successfully!
```
As this issue is unrelated to the script, it is considered closed.

**Comment by peracchi** [comment]
> The script runs without any problems from this end.

![it-runs-fine-on-my-browser](https://github.com/tteck/Proxmox/assets/1372058/9e14d81f-955e-4d3e-9eac-eb13377712d7)

I know that it runs, it's not a functional problem it's more a scope problem. Bigger scope.

Some networks use [HTTPS Inspection](https://sc1.checkpoint.com/documents/R81/WebAdminGuides/EN/CP_R81_NextGenSecurityGateway_Guide/Topics-FWG/HTTPS-Inspection.htm?TocPath=_____25) so any host on such network must have one or more "middleman certificates" installed before do HTTPS stuff.

![https+inspection+traffic+flow](https://github.com/tteck/Proxmox/assets/1372058/c32c2935-e9d8-40db-807a-08db813f73ab)

It would be nice if the scripts had the option of receiving one or more certificates to be imported into the container/vm before starting the part that needs to use HTTPS.

In the case of "Docker LXC with Alpine Linux" script it would be to copy certificate-1.crt and certificate-2.crt to container and right after start it do:
```
alpine-docker:~# apk --no-check-certificate add ca-certificates
alpine-docker:~# mv /root/certificate-1.crt /usr/local/share/ca-certificates/
alpine-docker:~# mv /root/certificate-2.crt /usr/local/share/ca-certificates/
alpine-docker:~# update-ca-certificates

```

If I can execute everything that comes after the "Started LXC Container" message, it also solves the problem. I manually do the part of inserting the necessary certificates and then let the script execute the missing part.

Anyway, thanks again for your scripts, they are brilliant.

"Live long and prosper" :vulcan_salute:

**Comment by tteck** [comment]
Oh, this was a feature request, since you answered "yes" to "Please verify that you have read and understood the guidelines." 
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

I went straight to the error message. I wouldn't think it would be a very widely used feature though.

**Comment by peracchi** [comment]
> Oh, this was a feature request, since you answered "yes" to "Please verify that you have read and understood the guidelines."

It's a mix between feature request and script error. After all, the script aborts and gives that error message.

Leaving the resource request aside, I suggest detecting HTTPS Inspection at the beginning of the script execution and gracefully terminating the script informing users that the scripts do not work in an environment with HTTPS Inspection.

**Comment by tteck** [comment]
In such an environment, can't you configure policies to allow certain URLs?

**Edit:** Is there a special `.crt` file that resides on the Proxmox host?

**Comment by peracchi** [comment]
> In such an environment, can't you configure policies to allow certain URLs?

Theoretically, yes.
But from a security point of view it's better to let everything go through HTTPS Inspection. Along with other measures, it is an attempt to mitigate the risks of viruses, malware and ransomware.
It is simpler and more logical to just include the internal certificates in the OSs.

> Is there a special .crt file that resides on the Proxmox host?

Yes, just after install Proxmox the two certificates are added to Proxmox host.

Every host, Windows, Linux or macOS has these certificates installed.

**Comment by tteck** [comment]
In order to perform HTTPS Inspection detection, certificates must either have a definable name or a definable path.

**Comment by peracchi** [comment]
> In order to perform HTTPS Inspection detection, certificates must either have a definable name or a definable path.

No, I think there is another way. Take a look.

I start creating an Alpine LXC.

`root@pve:~# bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/alpine.sh)"`

I only can create the container because Proxmox host already have the necessary self-signed certificates to work with HTTPS inspection on my network.

Container cannot be fully configured by the script because it does not have the self-signed certificates to work with HTTPS inspection on my network.

When container is ready, on container's console on PVE:

```
alpine-docker:~# sed -i 's/v3.18/edge/g' /etc/apk/repositories
alpine-docker:~# apk --no-check-certificate add ca-certificates curl openssh
alpine-docker:~# rc-update add sshd
alpine-docker:~# sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
alpine-docker:~# service sshd start

```

Script to check for HTTPS inspection. On container's console on PVE:

```
alpine-docker:~# cat << 'EOF' | tee /root/check-for-HTTPS-inspection.sh > /dev/null
#!/bin/ash

url="https://google.com"

echo
if curl -IsSf "$url" >/dev/null 2>&1; then
  echo "curl succedded to verify the legitimacy of the server at $url"
  echo "no HTTPS inspection is in use"
  echo " OR"
  echo "necessary self-signed certificate(s) were already imported"
  echo
else
  echo "curl failed to verify the legitimacy of the server at $url"
  echo "there is a self-signed certificate in returned certificate chain"
  echo "this usually occurs when HTTPS inspection is in use"
  echo "HTTPS inspection works by intercepting the HTTPS network traffic"
  echo "and performing a man-in-the-middle (MiTM) attack on the connection"
  echo
  exit 1
fi
EOF
alpine-docker:~# chmod +x /root/check-for-HTTPS-inspection.sh

```

At this point, on an environment with HTTPS inspection and without self-signed certificate(s) imported the script must fail. On container's console on PVE:

`alpine-docker:~# /root/check-for-HTTPS-inspection.sh`

Transfer the self-signed certificate(s) and import they. On container's console on PVE:

```
alpine-docker:~# mv /root/certificate-1.crt /usr/local/share/ca-certificates/
alpine-docker:~# mv /root/certificate-2.crt /usr/local/share/ca-certificates/
alpine-docker:~# update-ca-certificates

```

Now script must succeed. On container's console on PVE:

`alpine-docker:~# /root/check-for-HTTPS-inspection.sh`

Good link about HTTPS inspection: https://www.cloudflare.com/learning/security/what-is-https-inspection/

**Comment by tteck** [comment]
> I suggest detecting HTTPS Inspection at the beginning of the script execution

This I like

> When container is ready

That wasn't your suggestion; however, I won't be pursuing this feature.
