### ISSUE TITLE
NginX Proxy Manager CertBot Internal Error

### ISSUE THREAD

**Issue by nick-perry14** [tteck/Proxmox#1816]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to request an SSL acme cert, I get an internal error.  Upon checking the NPM logs, I get .  This is not an issue I've seen reported in the NPM discord, so I presume it has to do with the script installing a wacky version of certbot

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/6935777/e53e3858-207d-4c87-bfdb-aae1eebc0859)
![image](https://github.com/tteck/Proxmox/assets/6935777/73206044-ec94-4ccb-816d-3c72131abe12)

**Comment by tteck** [comment]
https://community.letsencrypt.org/t/no-module-named-acme-magic-typing/204030
As this issue is unrelated to the script, it is considered closed.
