### ISSUE TITLE
Magic Mirror Modules

### ISSUE THREAD

**Issue by markyskus** [tteck/Proxmox#1819]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Can't npm install moduls to the server, 

npm ERR! code 1
npm ERR! path /opt/magicmirror/modules/MMM-Screencast/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! Error: ENOSPC: no space left on device, write

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-09-21T16_24_48_650Z-debug-0.log

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> no space left on device

Increase storage

**Comment by markyskus** [comment]
aaah, thanks, i'm not az expert with linux, and i dont see that line :)

but now I have got a different message :\

up to date, audited 100 packages in 721ms

19 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (1 moderate, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.



google is not my friend now :\

**Comment by tteck** [comment]
`npm audit fix --force`

**Comment by markyskus** [comment]
thanks, not working, same error after force fix :(

**Comment by tteck** [comment]
> Run `npm audit` for details: This command will provide more detailed information about the vulnerabilities, including the affected dependencies and their versions. It will also suggest manual actions you can take to address the issues.

**Comment by markyskus** [comment]
npm audit only shows npm fix comand :) but nevermind, I will do something like magic mirror with home assistant :)
