### ISSUE TITLE
Whoogle https possible?

### ISSUE THREAD

**Issue by rafasanz** [tteck/Proxmox#1821]
Hi!

Installing whoogle lxc from script works fine.

I was configuring whoogle to access through proxy nginx. As i have anothers lxc working with https, i cant access to whoogle with https. As i know, nginx is well configured because others lxc are working fine.

I tried to edit `whoogle.service` to add `--https-only` but it is not working as i supposed to be. Always get 403 Forbidden

whoogle.service looks like that
![image](https://github.com/tteck/Proxmox/assets/102509029/a11a811d-2d9e-40a4-9b5c-04e13d58a8d8)

i tried to stop service, reload daemon and start again service, even reboot lxc, but still not working.

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
