### ISSUE TITLE
Proxmox VE LXC Updater - Selected lxc not working

### ISSUE THREAD

**Issue by NL-Tristan** [tteck/Proxmox#1824]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

On my proxmox server (8.0.4) I want to update my selected lxc's

The command I give in shell: 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/update-lxcs.sh)"

This Will Update Selected LXC Containers. Proceed? 
Yes

I select by examples 3 lxc's then Ok.

All my lxc's are going to update, not only my selected lxc's.

There are one more bug; when I cancel (where I can select lxc)  in update-lxcs.sh, it's not to quit, but all my lxc's are going to update.  You must press ctrl-c to quit. 

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

See "A clear and concise description of the issue."

**Comment by tteck** [comment]
I can see the confusion "This Will Update Selected LXC Containers. Proceed?"
https://github.com/tteck/Proxmox/blob/0692bad5c6c0b0adaa5b18dafa1c0b8d7dcaed0f/misc/update-lxcs.sh#L29 

when you make the selection, it is to exclude that selection from being updated
https://github.com/tteck/Proxmox/blob/0692bad5c6c0b0adaa5b18dafa1c0b8d7dcaed0f/misc/update-lxcs.sh#L37

read the whiptail messages carefully

**Comment by NL-Tristan** [comment]
I was indeed confused by the first message ""This Will Update Selected LXC Containers. Proceed?"
I did not saw "Select containers to skip from updates:". 
I was under the impression that the selection is updated and not skipped. I should have read better, sorry.

**Comment by NL-Tristan** [comment]
But cancelling is not good

**Comment by tteck** [comment]
You're right. I haven't found a solution to address that yet.
