### ISSUE TITLE
Proxmox VE LXC Updater - When pressing cancel, its updating

### ISSUE THREAD

**Issue by NL-Tristan** [tteck/Proxmox#1825]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

In proxmox shell I give a command to update lxc's

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/update-lxcs.sh)"`

When I want to cancel, it is not to going to quit, but it begin to  update all lxc's.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
I've been working on it, but I haven't managed to find a solution for it yet.

**Comment by NL-Tristan** [comment]
As a workaround you could replace "cancel" with press "ctrl-c" to exit. Until you have found a solution.

**Comment by tteck** [comment]
No matter what I try, the whiptail command is returning a code of 0, which indicates that it's not detecting the Cancel action as an error condition. In a typical whiptail dialog, the Cancel button should return a non-zero exit status.

**Comment by tteck** [comment]
fixed
