### ISSUE TITLE
Error while manually updating Adguard [ERROR] in line 57: exit code 3: while executing command wget -qL https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz

### ISSUE THREAD

**Issue by dudeoflife25** [tteck/Proxmox#1826]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Tried manually updating Adguard-Home today and received the following error [ERROR] in line 57: exit code 3: while executing command `wget -qL https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz`

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Open a console for the Adguard-Home LXC container and run the following command 
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/adguard.sh)"`

**Comment by tteck** [comment]
I just ran the command (`wget -qL https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz`) without issue.

**Comment by tteck** [comment]
```
    ___       __                           __
   /   | ____/ /___ ___  ______ __________/ /
  / /| |/ __  / __  / / / / __  / ___/ __  / 
 / ___ / /_/ / /_/ / /_/ / /_/ / /  / /_/ /  
/_/  |_\__,_/\__, /\__,_/\__,_/_/   \__,_/   
            /____/                           
 
 ✓ Stopped AdguardHome
 ✓ Updated AdguardHome
 ✓ Started AdguardHome
 ✓ Cleaned
 ✓ Updated Successfully
root@adguard:~# 
```

**Comment by dudeoflife25** [comment]
Sorry pasted the wrong command from my clipboard. It should have been bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/adguard.sh)"

**Comment by tteck** [comment]
Either way, they both were tested, and both worked.

**Comment by matroeh** [comment]
I had the same problem. 

In my case, it was because the LXC disc was too small (or too full) to unpack the update. After resizing the disk to 3 GB in Proxmox, the update went through.
