### ISSUE TITLE
Double NAT detected

### ISSUE THREAD

**Issue by jcreek** [tteck/Proxmox#1830]
I've run both the Plex and Wireguard scripts and neither is accessible from outside the network. Plex warns of a Double NAT but Proxmox is set up to bridge. Is there something I'm missing? There's only the one NAT on my network - the router, and every other machine I've run these services on has worked fine after port forwarding. I've troubleshooted and everything looks correct, so it can only be an issue with something to do with Proxmox and these LXCs

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 
As this issue is unrelated to the script, it is considered closed.
