### ISSUE TITLE
Cannot install Ubuntu LXC

### ISSUE THREAD

**Issue by NeoFax75** [tteck/Proxmox#1831]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the command it never builds the container.  I then copied the raw data from github and ran manually and get the below:

`   __  ____                __       
  / / / / /_  __  ______  / /___  __
 / / / / __ \/ / / / __ \/ __/ / / /
/ /_/ / /_/ / /_/ / / / / /_/ /_/ / 
\____/_.___/\__,_/_/ /_/\__/\__,_/  
 
Loading...
ubuntu.sh: line 27: variables: command not found
ubuntu.sh: line 28: color: command not found
ubuntu.sh: line 29: catch_errors: command not found
ubuntu.sh: line 63: start: command not found
ubuntu.sh: line 64: build_container: command not found
ubuntu.sh: line 65: description: command not found
ubuntu.sh: line 67: msg_ok: command not found`

### Which Linux distribution are you employing?

Ubuntu 23.04

### Please provide detailed steps to reproduce the issue.

First open the shell in your pve instance on proxmox and paste the following:

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/ubuntu.sh)"
`
Hit enter.  Nothing is done.  It just waits for a minute and then returns to the prompt.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
   __  ____                __       
  / / / / /_  __  ______  / /___  __
 / / / / __ \/ / / / __ \/ __/ / / /
/ /_/ / /_/ / /_/ / / / / /_/ /_/ / 
\____/_.___/\__,_/_/ /_/\__/\__,_/  
 
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 23.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: ubuntu
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Ubuntu LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```
It seems that you're facing a network problem, _probably_ linked to DNS. 
As this issue is unrelated to the script, it is considered closed.

**Comment by NeoFax75** [comment]
It was a DNS issue on my end as I moved the server from my house to a friends and forgot to setup the correct DNS.  BTW, how do I mark this as solved?
