### ISSUE TITLE
MQTT mosquitto service seems to start, but cannot be accessed via IP:1883

### ISSUE THREAD

**Issue by dbdmdbdmdbdm** [tteck/Proxmox#1832]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

MQTT seems to start but I cannot access it via its IP address. The page is unavailable. I have Home assistant running using your service on this proxmox instance and i am able to access that IP address, but 

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`root@mqtt:~# systemctl status mosquitto.service
* mosquitto.service - Mosquitto MQTT Broker
     Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-09-23 11:44:28 PDT; 3min 28s ago
       Docs: man:mosquitto.conf(5)
             man:mosquitto(8)
    Process: 147 ExecStartPre=/bin/mkdir -m 740 -p /var/log/mosquitto (code=exited, status=0/SUCC>
    Process: 152 ExecStartPre=/bin/chown mosquitto:mosquitto /var/log/mosquitto (code=exited, sta>
    Process: 158 ExecStartPre=/bin/mkdir -m 740 -p /run/mosquitto (code=exited, status=0/SUCCESS)
    Process: 160 ExecStartPre=/bin/chown mosquitto:mosquitto /run/mosquitto (code=exited, status=>
   Main PID: 163 (mosquitto)
      Tasks: 1 (limit: 18833)
     Memory: 1.9M
        CPU: 79ms
     CGroup: /system.slice/mosquitto.service
             `-163 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Sep 23 11:44:28 mqtt systemd[1]: Starting mosquitto.service - Mosquitto MQTT Broker...
Sep 23 11:44:28 mqtt mosquitto[163]: 1695494668: Loading config file /etc/mosquitto/conf.d/defaul>
Sep 23 11:44:28 mqtt systemd[1]: Started mosquitto.service - Mosquitto MQTT Broker.
lines 1-19/19 (END)`

### Please provide detailed steps to reproduce the issue.
I am getting the IP address for MQTT by using **lxc-info -n 101** in the proxmox shell
_No response_

**Comment by tteck** [comment]
Eclipse Mosquitto broker does NOT have a GUI.
If you're looking for a MQTT broker with such a feature, use EMQX.

As this issue is unrelated to the script, it is considered closed.

**Comment by dbdmdbdmdbdm** [comment]
@tteck ah i see, so if i go to IP:1883 I shouldnt be able to get anywhere? Was just looking to test before i start to cutover all my MQTT devices to Eclipse and HA

**Comment by tteck** [comment]
That's correct. port 1883 is the listening port
