### ISSUE TITLE
Issue Updating Nginx Proxy Manager

### ISSUE THREAD

**Issue by pennyblack** [tteck/Proxmox#1833]
Updating was working previously but now hitting the following whilst running an update from within the nginx proxy manager container

✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.10.4
 ✓ Setup Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 - Starting Services...
[ERROR] in line 168: exit code 1: while executing command systemctl enable -q --now openresty

**Comment by tteck** [comment]
I'm not using NPM, so I had to install a fresh LXC

```
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________ __  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                                      /____/                            /____/             
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: password
Container ID: 112
Using Hostname: nginxproxymanager
Using Disk Size: 4
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Nginx Proxy Manager LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python Dependencies
 ✓ Installed Openresty
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Downloaded Nginx Proxy Manager v2.10.4
 ✓ Set up Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Created Service
 ✓ Started Services
 ✓ Cleaned
 ✓ Completed Successfully!

Nginx Proxy Manager should be reachable by going to the following URL.
         http://192.168.86.253:81 
```
Then updating a fresh install
```
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________ __  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                                      /____/                            /____/             
 
 ✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.10.4
 ✓ Setup Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Started Services
 ✓ Cleaned
 ✓ Updated Successfully
root@nginxproxymanager:~# 
```

If I cannot reproduce the problem on my side, I cannot address an issue that appears to be functioning correctly here.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by louanrobert** [comment]
I'm having the same issue... Did you resolve it ?

**Comment by pennyblack** [comment]
Its fixed definitely not a script issue, its due to NPM not purging nginx
config files when SSL certificates are deleted from the NPM GUI.  Need to
manually clear the nginx server config files for non existing hosts /
certs. this should get the services started. Potentially a bug in NPM not
clearing down orphaned config files, I could repeat the issue by deleting a
certificate from GUI and issue would re occur.

**Comment by BlackrazorNZ** [comment]
Please forgive the bump, but: when you say to manually clear the nginx server config files for non-existing hosts, can you advise where specifically those config files are hosted and what they are called? my NPM install on ProxMox works fine, but whenever I run the 'upgrade' command, I loose all access to NPM, and have to end up restoring from backup. I've spent some time looking at /etc/nginx/nginx.conf in console, but I cannot find where specifically it references any old certs, and all my current proxy hosts are on a wildcard certificate (they used to be on individual ones).

My /data/nginx/proxy_host directory only has conf files for currently active proxy hosts, I have no redirect/streams/etc in place, and my /etc/letsencrypt/live only contains a single certificate directory (the wildcard) which all proxy host configs reference.

The only place I can find any references to multiple certificates etc is under the /etc/letsencrypt/csr and /etc/letsencrypt/keys directories, per below. 

![image](https://github.com/user-attachments/assets/21d61f2d-3cb3-464e-b385-db6736d8085f)


> Its fixed definitely not a script issue, its due to NPM not purging nginx config files when SSL certificates are deleted from the NPM GUI. Need to manually clear the nginx server config files for non existing hosts / certs. this should get the services started. Potentially a bug in NPM not clearing down orphaned config files, I could repeat the issue by deleting a certificate from GUI and issue would re occur.
