### ISSUE TITLE
HTTPS - All application get http acess, how add https ?

### ISSUE THREAD

**Issue by gamersalpha** [tteck/Proxmox#1835]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello, 

i used u installed guide, but i m not understand or read how to activate HTTPS on this application ?

for now evrythink is on http access, can u just give me a way to add https for applicaiton installed  

thanks

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
