### ISSUE TITLE
Homarr

### ISSUE THREAD

**Issue by Nazgile94** [tteck/Proxmox#1836]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Erro while install homarr

Default settings and manually / debian 11 / 12 

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`➤ YN0007: │ ssh2@npm:1.14.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/client@npm:5.2.0 [bdc39] must be built because it never has been before or the last one failed
➤ YN0007: │ homarr@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 47s 697ms
➤ YN0000: Done with warnings in 2m 53s
+ yarn build
❌ Invalid environment variables: { NEXTAUTH_URL: [ 'Required' ] }
- error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

> Build error occurred
Error: Invalid environment variables
    at /opt/homarr/node_modules/@t3-oss/env-nextjs/dist/index.js:1:792
    at T (/opt/homarr/node_modules/@t3-oss/env-nextjs/dist/index.js:1:1010)
    at P (/opt/homarr/node_modules/@t3-oss/env-nextjs/dist/index.js:1:1401)
    at Object.<anonymous> (/opt/homarr/src/env.js:7:13)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
++ error_handler 44 '$STD yarn build'
++ local exit_code=1
++ local line_number=44
++ local 'command=$STD yarn build'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m44\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn build\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m44\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn build\033[m'

[ERROR] in line 44: exit code 1: while executing command $STD yarn build
++ [[ 44 -eq 24 ]]
+ exit
root@proxmox:~# `

### Please provide detailed steps to reproduce the issue.

run script, hit enter with default settings :-)

**Comment by Nazgile94** [comment]
`➤ YN0000: ┌ Resolution step
➤ YN0002: │ @mantine/core@npm:6.0.19 [bdc39] doesn't provide @emotion/react (p74ffa), requested by @mantine/styles
➤ YN0002: │ @mantine/next@npm:6.0.19 [bdc39] doesn't provide @emotion/react (pd4fd4), requested by @mantine/styles
➤ YN0002: │ @mantine/next@npm:6.0.19 [bdc39] doesn't provide @emotion/react (p4c36a), requested by @mantine/ssr
➤ YN0002: │ @mantine/next@npm:6.0.19 [bdc39] doesn't provide @emotion/server (pf2ba8), requested by @mantine/ssr
➤ YN0002: │ @nivo/annotations@npm:0.83.0 [01db6] doesn't provide react-dom (ped1d0), requested by @react-spring/web
➤ YN0002: │ @nivo/axes@npm:0.83.0 [01db6] doesn't provide react-dom (pa02c0), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.0 [01db6] doesn't provide react-dom (p81da8), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.0 [5899b] doesn't provide react-dom (p2bc14), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.0 [bdc39] doesn't provide react-dom (p4f998), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.83.0 [f77dd] doesn't provide react-dom (pec8cc), requested by @react-spring/web
➤ YN0002: │ @nivo/line@npm:0.83.0 [bdc39] doesn't provide react-dom (p4f147), requested by @react-spring/web
➤ YN0002: │ @nivo/tooltip@npm:0.83.0 doesn't provide prop-types (pb9f7c), requested by @nivo/core
➤ YN0002: │ @nivo/tooltip@npm:0.83.0 doesn't provide react (p9afea), requested by @react-spring/web
➤ YN0002: │ @nivo/tooltip@npm:0.83.0 doesn't provide react (p1a443), requested by @nivo/core
➤ YN0002: │ @nivo/tooltip@npm:0.83.0 doesn't provide react-dom (p16cca), requested by @react-spring/web
➤ YN0002: │ @nivo/voronoi@npm:0.83.0 [01db6] doesn't provide prop-types (p6750d), requested by @nivo/core
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.7 doesn't provide @tiptap/pm (pc392d), requested by @tiptap/core
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.7 doesn't provide @tiptap/pm (p67156), requested by @tiptap/extension-code-block
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.7 doesn't provide @tiptap/pm (pf3e77), requested by @tiptap/extension-dropcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.7 doesn't provide @tiptap/pm (pbd40b), requested by @tiptap/extension-gapcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.7 doesn't provide @tiptap/pm (pb9f83), requested by @tiptap/extension-history
➤ YN0002: │ @tiptap/starter-kit@npm:2.1.7 doesn't provide @tiptap/pm (pdaaf6), requested by @tiptap/extension-horizontal-rule
➤ YN0002: │ browser-geo-tz@npm:0.0.4 doesn't provide typescript (p169a1), requested by tsify
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p15763), requested by @tiptap/extension-link
➤ YN0002: │ homarr@workspace:. doesn't provide @tiptap/core (p013d2), requested by @tiptap/react
➤ YN0060: │ homarr@workspace:. provides i18next (pd61c8) with version 22.5.1, which doesn't satisfy what next-i18next requests
➤ YN0002: │ homarr@workspace:. doesn't provide prop-types (pab8ab), requested by @nivo/core
➤ YN0060: │ homarr@workspace:. provides react-i18next (pfec32) with version 12.3.1, which doesn't satisfy what next-i18next requests
➤ YN0002: │ homarr@workspace:. doesn't provide react-native (p6fa00), requested by @react-native-async-storage/async-storage
➤ YN0002: │ homarr@workspace:. doesn't provide vite (pf9050), requested by @vitejs/plugin-react
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 469ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ ws@npm:7.5.9 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ xml-js@npm:1.6.11 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ xml2js@npm:0.5.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ xmlbuilder@npm:11.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ xss@npm:1.0.14 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A5.2.2#~builtin<compat/typescript>::version=5.2.2&hash=5da071: Cannot apply hunk #4
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.21.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.22.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zustand@npm:4.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 2m 4s
➤ YN0000: ┌ Link step
➤ YN0007: │ sharp@npm:0.32.5 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/engines@npm:5.3.1 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.32.1 must be built because it never has been before or the last one failed
➤ YN0007: │ cpu-features@npm:0.0.9 must be built because it never has been before or the last one failed
➤ YN0009: │ cpu-features@npm:0.0.9 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-1b7c371a/build.log)
➤ YN0007: │ prisma@npm:5.3.1 must be built because it never has been before or the last one failed
➤ YN0007: │ ssh2@npm:1.14.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/client@npm:5.2.0 [bdc39] must be built because it never has been before or the last one failed
➤ YN0007: │ homarr@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 47s 697ms
➤ YN0000: Done with warnings in 2m 53s
+ yarn build
❌ Invalid environment variables: { NEXTAUTH_URL: [ 'Required' ] }
- error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

> Build error occurred
Error: Invalid environment variables
    at /opt/homarr/node_modules/@t3-oss/env-nextjs/dist/index.js:1:792
    at T (/opt/homarr/node_modules/@t3-oss/env-nextjs/dist/index.js:1:1010)
    at P (/opt/homarr/node_modules/@t3-oss/env-nextjs/dist/index.js:1:1401)
    at Object.<anonymous> (/opt/homarr/src/env.js:7:13)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
++ error_handler 44 '$STD yarn build'
++ local exit_code=1
++ local line_number=44
++ local 'command=$STD yarn build'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m44\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn build\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m44\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn build\033[m'

[ERROR] in line 44: exit code 1: while executing command $STD yarn build
++ [[ 44 -eq 24 ]]
+ exit
root@proxmox:~# `

extended version

**Comment by tteck** [comment]
Homarr is currently undergoing extensive development, and we do not recommend installing it from source at this point. As a result, Homarr has been taken down from this site. We kindly suggest using the Docker installation method as an alternative.
