### ISSUE TITLE
can not create workable n8n container in proxmox 8.0.4

### ISSUE THREAD

**Issue by keekychen** [tteck/Proxmox#1837]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

my host environment is  Proxmox_VE_8.0.4.
I can created n8n LXC in Proxmox successfully via running this command `(bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/n8n.sh)")` in proxmox shell.  

however after n8n LXC been created, no service available when I access `http://{n8n_host_ip}:5678`, in n8n LXC's shell via `ss` port checking no 5678 is in listening 

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

I tried to recreate host many times with try to use different guest OS(Debian, Ubuntu...), same. 

then I try to run `(bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/n8n.sh)")`  in n8n LXC's shell (try to update n8n to see any luck), it shows

```
         ___        
        / _ \       
  _ __ | (_) |____  
 |  _ \ > _ <|  _ \ 
 | | | | (_) | | | |
 |_| |_|\___/|_| |_|
 
Loading...
bash: line 28: variables: command not found
bash: line 29: color: command not found
bash: line 30: catch_errors: command not found
bash: line 63: start: command not found
bash: line 64: build_container: command not found
bash: line 65: description: command not found
bash: line 67: msg_ok: command not found
n8n should be reachable by going to the following URL.
         http://:5678 

root@n8n:/tmp# 
```

then i manually installed `npm` in n8n LXC's shell via `apt install npm` because i found `npm` is requided in install script but not been installed.
and after that i try to run `(bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/n8n.sh)")` again, still same out out, 

then i run `npm install -g n8n` manually in n8n LXC, and looks it is allow me to install `n8n` but i do not know how to bring it up.

could you take a look and where is the problem i can not install n8n LXC automatically via script?

 

### Please provide detailed steps to reproduce the issue.

BTW, one problem i guess is my network need to have proxy access to internet therefore that install script may quit in silence when it can not install npm or n8n in LXC?

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
         ___        
        / _ \       
  _ __ | (_) |____  
 |  _ \ > _ <|  _ \ 
 | | | | (_) | | | |
 |_| |_|\___/|_| |_|
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 114
Using Hostname: n8n
Using Disk Size: 3
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a n8n LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 114 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed n8n
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

n8n should be reachable by going to the following URL.
         http://192.168.86.253:5678 
```
If I cannot reproduce the problem on my side, I cannot address an issue that appears to be functioning correctly here. 
As this issue is unrelated to the script, it is considered closed.
