### ISSUE TITLE
Monitor-all starts up too quickly when server rebooted

### ISSUE THREAD

**Issue by dmshimself** [tteck/Proxmox#1840]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I rebooted my proxmox 8 server recently to make use of an updated kernel, the system took ages to get back to a normal state.  I tracked it down to what looks like a clash between proxmox starting up VMs and LXCs and monitor-all doing the same thing.  There were many instances of stopping and starting LXCs in particular in the task history of proxmox.

It occurs to me that this might well happen if you have two services trying to start and check apps at the same time during reboot.  

At the moment I have disabled monitor-all and manually start it after the server reboots, but would it be possible to put some sort of dependency of monitor-all so it only starts to monitor once the regular proxmox startup processes have finished or perhaps have a configurable delay so it only begins work after (say) 10 mins?

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Have a bunch of LXCs set to auto start and leave monitor-all at default to monitor everything, then reboot the server and observe the behaviour.  Ideally the server should not be a top end spec, but more of an average home server

**Comment by tteck** [comment]
I hadn't considered that possibility. What are your thoughts on implementing a 5-minute delay before starting?

**Comment by tteck** [comment]
You can potentially address this issue by adding the following line `ExecStartPre=/usr/bin/sleep 300` above the line `ExecStart=/usr/local/bin/ping-instances.sh` in the `/etc/systemd/system/ping-instances.service` file.

This should introduce a 5-minute delay before executing the main command.

**Comment by dmshimself** [comment]
I should have thought of that!  Many thanks for the hint
