### ISSUE TITLE
[Feature Request] Add Authentik LXC

### ISSUE THREAD

**Issue by dreulavelle** [tteck/Proxmox#1841]
Would be pretty nice for an Authentik LXC. Think it would fit nicely in with the rest of the apps you've chosen.

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by dreulavelle** [comment]
Ahh my apologies! I'll add it over there. Thank you!
