### ISSUE TITLE
[plex]

### ISSUE THREAD

**Issue by geekscrapy** [tteck/Proxmox#1844]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Attempted to run the curreny version of the plex installer and got this error:

```
Loading...
ipcc_send_rec[1] failed: Unknown error -1
ipcc_send_rec[2] failed: Unknown error -1
ipcc_send_rec[3] failed: Unknown error -1
Unable to load access control list: Unknown error -1

[ERROR] in line 428: exit code 255: while executing command NEXTID=$(pvesh get /cluster/nextid)
```

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/11225502/4b5ffbec-7120-4701-ac64-c4e5453c59c7)

### Please provide detailed steps to reproduce the issue.

Just SSHd into PVE and attempted to run. I get a popup about "This will create a New Plex LXC. Proceed?", I click "Yes" and get the above error after a few seconds.

**Comment by geekscrapy** [comment]
Attempted to run `pvecm status` and got the same issue so I'm closing as it doesn't look to be a fault of the script

**Comment by tteck** [comment]
Did you receive this notice "It's suggested to use the Proxmox shell instead of SSH, since SSH can create issues while gathering variables. Would you like to proceed with using SSH?"

**Comment by geekscrapy** [comment]
I did, but only when I was running it from SSH. As soon as I saw that I tried to run it again from shell. Still failed. Think it might be an issue with the user privs

**Comment by tteck** [comment]
You are not using root?

**Comment by geekscrapy** [comment]
No, I create another user and assign it Administrative perms. I use the root account as a "breakglass" account and always create a new user to do stuff

**Comment by tteck** [comment]
I believe implementing a "root" check and exiting the script if not running as root is a good idea. This will prevent users from having to guess the source of any potential issues.

**Comment by geekscrapy** [comment]
Totally agree

**Comment by geekscrapy** [comment]
I see the root check is implemented for at least jellyfin. It doesn't allow me to run with `sudo bash ....` though

**Comment by tteck** [comment]
That is correct...
> Please run these scripts as root (not with sudo).
