### ISSUE TITLE
Z2M - cant bind USB device

### ISSUE THREAD

**Issue by dbdmdbdmdbdm** [tteck/Proxmox#1846]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am trying to bind a usb stick to Z2M. I am using the instructions here:
https://pve.proxmox.com/wiki/USB_Devices_in_Virtual_Machines

in the shell i am putting in:
qm set 105 -usb0 host=1cf1:0030
- where 105 is the container and 1cf1:0030 is the usb ID, using lsusb. I get the error: 
Configuration file 'nodes/pve/qemu-server/105.conf' does not exist

Also, the Home Assistant script gives me a "hardware" tab to map the USB device, whereas the Z2M script does not. That would be easier if its possible to somehow enable that gui option. 

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

As this issue is unrelated to the script, it is considered closed.
