### ISSUE TITLE
Home Assistant VM

### ISSUE THREAD

**Issue by markyskus** [tteck/Proxmox#1849]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

This is not really an issue, with 2023.10.0b0 user must change CPU type from default to host, otherwise HA doesn't appear again :)

maybe You could change it in the script :)

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
You're 4 hours late https://github.com/tteck/Proxmox/commit/24551de29206f1a1b71a1df413125126353d0757

**Comment by tteck** [comment]
This setting, among others, has been accessible for a while now when utilizing the "Advanced" settings.

Please take note that employing the "host" CPU type is incompatible with multi-node clustering that involves Live Migration.
