### ISSUE TITLE
Error in Umbrel LXC script (using default settings)

### ISSUE THREAD

**Issue by zephirus** [tteck/Proxmox#1862]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I get this error when executing the Umbrel LXC script with default settings:

- Installing Umbrel (Patience)...
[ERROR] in line 24: exit code 125: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Just used the following script in proxmox shell:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/umbrel.sh)"

**Comment by tteck** [comment]
> - When encountering the error message [ERROR] in line 24: exit code *: while executing command "$@" > /dev/null 2>&1, make sure to run the script in verbose mode to accurately determine the underlying issue.

**Comment by tteck** [comment]
http://umbrel.local

![Screenshot 2023-09-30 8 27 01 AM](https://github.com/tteck/Proxmox/assets/21342670/b141484e-c1d9-46a0-8cb2-86812399cdb6)

**Comment by zephirus** [comment]
Tried again and it's working.
