### ISSUE TITLE
No an issue just an improvement

### ISSUE THREAD

**Issue by scho0ck** [tteck/Proxmox#1867]
I've used many of your scripts out of simplicity however one thing that I did to improve the experience is to add an alias to each CT to update the app e.g. npm or vaultwarden this allows me to login and just run a memorable command to run the updater script.

Maybe you could add something like this to your install script?

For example for npm I have the following in my bashrc file.

`alias update_npm='bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"'`

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

https://github.com/tteck/Proxmox/discussions/1700#discussioncomment-6752297
