### ISSUE TITLE
Pi.Alert update with pialert.sh  script, get a error message

### ISSUE THREAD

**Issue by NL-Tristan** [tteck/Proxmox#1868]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I want to update Pi Alert with the pialert.sh script, I get a error message:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/pialert.sh)"

environment: line 56: update: command not found

[ERROR] in line 56: exit code 127: while executing command update

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

 root@pialert:~#  bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/pialert.sh)"

Support functions for PiAlert LXC.  Proceed?

Answer: yes

Result:

    ____  _   ___    __          __
   / __ \(_) /   |  / /__  _____/ /_
  / /_/ / / / /| | / / _ \/ ___/ __/
 / ____/ / / ___ |/ /  __/ /  / /_
/_/   /_(_)_/  |_/_/\___/_/   \__/

environment: line 56: update: command not found

[ERROR] in line 56: exit code 127: while executing command update

root@pialert:~#

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/1799#discussioncomment-7157050

**Comment by tteck** [comment]
https://github.com/leiweibau/Pi.Alert/issues/178

**Comment by tteck** [comment]
Until this issue is resolved at https://github.com/leiweibau/Pi.Alert you can utilize the following command to update.

```

```

**Comment by tteck** [comment]
Issue is resolved at https://github.com/leiweibau/Pi.Alert
