### ISSUE TITLE
Cannot install containers

### ISSUE THREAD

**Issue by koevoet1221** [tteck/Proxmox#187]
Hi, ive been trying to install a mqtt lxc but the script exits after installing dependencies or updating OS. I can’t access the console because it asks for a password, I used automatic login. When I did use a password I was able to access the console but no sudo or mosquitto was installed in the lxc. I’ve also tried the nodered script but it has the same issue. I didn’t try the non-advanced method because I need the VLAN.
Here are the settings I used:

Using Advanced Settings
Using CT Type Unprivileged
Using CT Password Automatic Login
Using CT ID 109
Using CT Name nodered
Using Disk Size 4GB
Using 40vCPU
Using 1024MiB RAM
Using Bridge vmbr1
Using Static IP Address dhcp
Using Gateway IP Address 192.168.20.1
Using VLAN Tag 20
Are these settings correct(y/n)? y
 ✓ Using local for Template Storage.
 ✓ Using Storage for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 109 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.20.9 
 ✓ Updated Container OS
root@pve:/

did i do anything wrong?
thanks in advance

**Comment by tteck** [comment]
Try not setting a Gateway IP Address unless you're using a Static IP. Just set VLAN Tag and see if that works

**Comment by tteck** [comment]
Using 40 CPU cores?

**Comment by koevoet1221** [comment]
The 40 cores are just for the install, I’ll set it to the default 1 after install. Or is the increased install speed insignificant?

**Comment by koevoet1221** [comment]
Same issue without a gateway set. Here are the settings I’ve used this time:
Using Advanced Settings
Using CT Type Unprivileged
Using CT Password Automatic Login
Using CT ID 109
Using CT Name mqtt
Using Disk Size 2GB
Using 40vCPU
Using 512MiB RAM
Using Bridge vmbr1
Using Static IP Address dhcp
Using Gateway IP Address NONE
Using VLAN Tag 20
Are these settings correct(y/n)? y
 ✓ Using local for Template Storage.
 ✓ Using Storage for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 109 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.20.10 
 ✓ Updated Container OS
 - Installing Dependencies...root@pve

**Comment by tteck** [comment]
I'm no network person, but...
It seems there's a network issue somehow. Looks like it's not reaching the internet. DNS?

**Comment by koevoet1221** [comment]
It says network connected tho. Ive tried without the vlan tag and it worked somehow. Ive got another machine running fine on the same vlan so it must be dns then. Ill try some stuff and let you know what works.
Thanks

**Comment by koevoet1221** [comment]
Okay turns out I’m an idiot. Its a firewall issue, fixed now. Thanks for your help

**Comment by tteck** [comment]
I added an Internet Connection Check to the scripts to help troubleshoot
