### ISSUE TITLE
Creating containers for MQTT, Zigbee2MQTT not working with Debian 12

### ISSUE THREAD

**Issue by amatiytsiv** [tteck/Proxmox#1888]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

while trying to create a container for MQTT or Zigbee2MQTT you end up with an error that points to build file:
[ERROR] in line 563: exit code 255: while executing command pct start "$CTID". MQTT is kind of working with debian 11(up and running in the system) . Wasnt able to test since wasn't able to install separate instance for zigbee2mqtt

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

execute any of the scripts below on the default setup:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/mqtt.sh)"
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/zigbee2mqtt.sh)"

**Comment by tteck** [comment]
No issues here. Are you using a VPS (Virtual Private Server) or a physical local machine?

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by amatiytsiv** [comment]
Private server

> No issues here. Are you using a VPS (Virtual Private Server) or a physical local machine?

**Comment by tteck** [comment]
Using these scripts with a VPS can lead to various issues related to variables, and I don't recommend doing so.

**Comment by amatiytsiv** [comment]
sh.. sorry was thinking about one thing - and wrote absolutely another. Im using physical machine intel based with quite ok hw for running proxmox. Cant understand what is goign wrong. but it absolutely not working with default settings for MQTT

**Comment by tteck** [comment]
Are you using the Proxmox shell or another terminal interface? What Proxmox version?

**Comment by amatiytsiv** [comment]
Proxmox shell, 8.0.4. after doing same thing the 21st time.... it actually installed mqtt  with the default setting - but now it thinks it has a password, root password i mean.

**Comment by tteck** [comment]
You need to remain in the shell for the entire process.

**Comment by amatiytsiv** [comment]
quite silly situation. exactly same steps give the different results - managed to install Debian 12 on both mosquitto and z2m.
have no clue how that happens, only idea is some kind of browser-wierd behaviour. Best alternative to use you may have to suggest ?
And by all means, without all those scripts i will end up - having HA OS installed with all addons installed in signle VM. Tremendous work!  Thanks!
