### ISSUE TITLE
Jellyfin RAM and CPU do not match LXC configuration when looking at summary in PROX pinned at defaults.

### ISSUE THREAD

**Issue by GG-GhostGaming** [tteck/Proxmox#1895]
### Please verify that you have read and understood the guidelines.

Yes
 @#
/
### A clear and concise description of the issue.

When I change the allocated amount of RAM/CPU that is dedicated to the jellyfin LXC, it does not change within jellyfin or any other applications run inside of the same LXC. They all are maxed out at two gigs and two CPU cores. No matter what I do, I cannot seem to get it to go any higher even though I'm running both jellyfin and qBitTorrent in the same LXC. It never goes above two gigs (1.67) of RAM and two CPU cores (18% utilization on the CPU). (I have eight cores dedicated to the LXC and 10 gigs of RAM.)

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Just putting this here because there's no other option to enter anywhere else but I'm not 100% sure on the version of about two that I'm using. It's either 22.04 or 20.04

### Please provide detailed steps to reproduce the issue.

After using the script successfully and gaining access to the web UI stop/shut down the jellyfin server, adjust CPU and RAM. Then check the summary on proxmox. If replicated properly you will notice it does not go above. 2. Gigs on RAM and has extremely low utilization on the CPU If you allocate 8 cores.

![Screenshot 2023-10-08 004315](https://github.com/tteck/Proxmox/assets/55955972/7967ee64-cf8d-4dfe-8e3c-5fd28aa49740)

**Comment by tteck** [comment]
Have you tried rebooting the LXC?
My primary focus revolves around the development of application LXCs, and I'm not specialized in providing support for operational issues that may arise with these applications.

**Comment by GG-GhostGaming** [comment]
I've rebooted the LXC multiple times, and still no change, I'm also slamming it with 1080p content and as many torrent downloads as I can test with and it is not going above defaults.

**Comment by tteck** [comment]
According to your pic, everything looks good, if that's the LXC in question.
You may find help by posting in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 
As this issue is unrelated to the script, it is considered closed.
