### ISSUE TITLE
[Feature Request ]Reboot info for update-lxc

### ISSUE THREAD

**Issue by MajorTomDE** [tteck/Proxmox#1897]
Hey,
it would be great if update-lxc shows an info when an reboot is required.
e.g. as an second option

1 = Classic Update
2 = Check Update Status > Show count of available updates, reboot required, disk status

Result should be a list for an complete overview

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
