### ISSUE TITLE
Unknown failure occured

### ISSUE THREAD

**Issue by ykii** [tteck/Proxmox#19]
Running Proxmox VE 7.1-10

Trying to install  mariadb lxc. Tried other scripts too, always ended this kind of error:

![image](https://user-images.githubusercontent.com/11420784/151579035-d6d25215-fc91-4ecd-a13b-870ac77850d9.png)

**Comment by tteck** [comment]
Can not replicate on my end.

![Screenshot 2022-01-28 11 06 26 AM](https://user-images.githubusercontent.com/21342670/151581215-4bf0fad9-eb50-42b3-98db-73f773b355f9.png)

**Comment by tteck** [comment]
try a `cd` first to get back to root. The n try running the script

**Comment by ykii** [comment]
Thanks for quick reply.

This is what I get when running pihole -script:

![image](https://user-images.githubusercontent.com/11420784/151583691-509f3245-26e3-48fc-a2d4-4ae6e7a2fd77.png)

Something wrong in this line maybe?:

![image](https://user-images.githubusercontent.com/11420784/151583838-bcdcb430-4705-438a-bb08-5faa7ec1fb1f.png)

**Comment by tteck** [comment]
No, it works on my end. I don't think it's a script issue

**Comment by tteck** [comment]
Try the pihole script again and see if it works now

**Comment by ykii** [comment]
Unfortunately same problem. Script dies in "Installing Prerequisites..."

It could be something apparmor related though.

**Comment by tteck** [comment]
Have you been messing with apparmor?

**Comment by ykii** [comment]
Nope, this is a fresh install. Only hass installed in VM via whiskerz007-script.

**Comment by tteck** [comment]
did you run the post install script from the repo?

**Comment by ykii** [comment]
yes I did, do you think it messed up?

**Comment by tteck** [comment]
no, did you update Proxmox?

**Comment by ykii** [comment]
Yes, updated and rebooted.

**Comment by tteck** [comment]
reboot Proxmox again and try running a script

**Comment by ykii** [comment]
Same errors.

Installing Prerequisites...
[ERROR:LXC] 100@35 Unknown failure occured.
[ERROR] 100@154 Unknown failure occured.
  Logical volume "vm-101-disk-0" successfully removed

I'll keep digging. If I figure it out, I'll post here.

**Comment by tteck** [comment]
yeah, something has happened
at this point beings that you don't have many VM/CT installed, I'd reinstall Proxmox

**Comment by tteck** [comment]
Not a script issue

**Comment by willsy555** [comment]
I get exactly the same issue Mariadb. Very strange!

**Comment by tteck** [comment]
@willsy555 try again

**Comment by willsy555** [comment]
Hello @tteck 

Tried again and it seems to work now... Got some error about indexes below, but seems to be up and running. Thank you very much! :-)

root@svr-gen-001:~# bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/mariadb_container.sh)"
This will create a New Mariadb LXC Container. Proceed(y/n)?y
[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 103.
Updating LXC template list...
Downloading LXC template...
Creating LXC container...
Starting LXC container...
Setting up container OS...
Updating container OS...
Installing Prerequisites...
Installing MariaDB...
W: Failed to fetch http://downloads.mariadb.com/Tools/debian/dists/bullseye/InRelease  Could not handshake: The TLS connection was non-properly terminated. [IP: 104.18.135.24 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Customizing container...
Cleanup...
[INFO] Successfully created a MariaDB LXC Container to 103 at IP Address 192.168.1.236
root@svr-gen-001:~#

**Comment by willsy555** [comment]
Because of my OCD... I deleted and tried again and now it works perfectly. Thank you @tteck 

bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/mariadb_container.sh)"
This will create a New Mariadb LXC Container. Proceed(y/n)?y
[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 103.
Updating LXC template list...
Downloading LXC template...
Creating LXC container...
Starting LXC container...
Setting up container OS...
Updating container OS...
Installing Prerequisites...
Installing MariaDB...
Customizing container...
Cleanup...
[INFO] Successfully created a MariaDB LXC Container to 103 at IP Address 192.168.1.184

**Comment by tteck** [comment]
Yeah, it looked like mariadb,com had a blip

**Comment by tteck** [comment]
Issue has been fixed

**Comment by pquodling** [comment]
I see similar - trying to do a node-red install. 


      _   _           _             _____          _ 
     | \ | |         | |           |  __ \        | |
     |  \| | ___   __| | ___ ______| |__) |___  __| |
     |     |/ _ \ / _  |/ _ \______|  _  // _ \/ _  |
     | |\  | (_) | (_| |  __/      | | \ \  __/ (_| |
     |_| \_|\___/ \__,_|\___|      |_|  \_\___|\__,_|
                                                 

 Using Privileged Install
[INFO] Using TBSSD for Template Storage.
[INFO] Using TBSSD for Container Storage.
 Updating LXC Template List... ✔ 
 Downloading LXC Template... ✔ 
 Creating LXC Container... ✔ 
[INFO] LXC Container 100 was successfully created.
 Starting LXC Container... ✔ 
 Setting up Container OS... ✔ 
 Network Connected: 2001:8003:7183:ea00:b8e0:5cff:fe9d:dbb0 fdc4:49a6:1a15:4c5c:b8e0:5cff:fe9d:dbb0  ✔ 
 Updating Container OS... ✔ 
 Installing Dependencies... [ERROR:LXC] 100@57 Unknown failure occured.
root@proximix:~# pwd
/root
root@proximix:~#

**Comment by tteck** [comment]
>[ERROR:LXC] 100@57 Unknown failure occured. 

fails at `apt-get install -y curl` suggests network issues

**Comment by popeter1** [comment]
im getting this issue too

    _   __          __        ____           __
   / | / /___  ____/ /__ v4  / __ \___  ____/ /
  /  |/ / __ \/ __  / _ \   / /_/ / _ \/ __  / 
 / /|  / /_/ / /_/ /  __/  / _, _/  __/ /_/ /  
/_/ |_/\____/\__,_/\___/  /_/ |_|\___/\__,_/   

Using Default Settings
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: Automatic Login
Using Container ID: 100
Using Hostname: node-red
Using Disk Size: 4GB
Allocated Cores 1
Allocated Ram 1024
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Using MAC Address: Default
Using VLAN Tag: Default
Creating a Node-Red LXC using the above default settings
 ✓ Using pve-shared for Template Storage.
 ✓ Using pve-shared for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 100 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.0.20.47 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Installing Node-Red...‼ ERROR 1@81 Unknown failure occurred.

**Comment by tteck** [comment]
@popeter1 fixed

**Comment by popeter1** [comment]
yea working now, thanks for that :)
