### ISSUE TITLE
Help: haos-vm.sh

### ISSUE THREAD

**Issue by eth030** [tteck/Proxmox#1907]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I reinstalled using https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh.
However, now the IP address of the VM is different. I changed the IP address in my router according to the new created MAC address. Despite rebooting the VM several times, it's not taking the IP address. I need help to change the VM IP address in Proxmox.

Old Home Assistant VM installed with helper script IP Address: x.x.x.133.
Deleted that VM.
Newly installed VM with helper script IP Address: x.x.x.80.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Change to IP Address: x.x.x.133 within Home Assistant.

> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by eth030** [comment]
thx i will try
