### ISSUE TITLE
PhotoPrism script doesn't appear to complete correctly

### ISSUE THREAD

**Issue by kezc7** [tteck/Proxmox#191]
When running the PhotoPrism script, it appears to terminate prematurely when running the TensorFlow section:

Using Disk Size 16GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address dhcp
Using Gateway IP Address NONE
Using VLAN Tag NONE
Are these settings correct(y/n)? y

 ✓ Using Storage for Template Storage.
 ✓ Using VMs2 for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 120 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.83 
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 - Installing Tensorflow...root@proxmox2:~#

**Comment by tteck** [comment]
The script tries to determin which Advanced Vector Extensions (AVX) your CPU has, then install the correct version of Tensorflow. If you'd run this `grep -o -m1 'avx[^ ]*' /proc/cpuinfo` ln the Proxmox Shell and share the output.

**Comment by tteck** [comment]
I just ran the script...

```
Using Default Settings
Using CT Type Unprivileged NO DEVICE PASSTHROUGH
Using CT Password Automatic Login
Using CT ID 111
Using CT Name photoprism
Using Disk Size 8GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.49 
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 ✓ Built PhotoPrism
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

PhotoPrism should be reachable by going to the following URL.
      http://192.168.86.49:2342 
```

**Comment by kezc7** [comment]
That will probably be the reason then :) I am running dual Xeon X5570 which do not support AVX. Is there any way around this?

**Comment by tteck** [comment]
What was the output of `grep -o -m1 'avx[^ ]*' /proc/cpuinfo`?

**Comment by tteck** [comment]
If the script doesn't detect AVX or AVX2 it should install the base CPU version.

**Comment by kezc7** [comment]
It was blank:
![pm](https://user-images.githubusercontent.com/23127971/165073475-1235e068-93d4-4dfa-ac02-fab305ad3337.png)

**Comment by tteck** [comment]
Try 
```

```
I set it to ONLY install the CPU version without checking... Hopefully this will get you past the AVX check

**Comment by kezc7** [comment]
It got further this time but failed when building photoprism:

Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address dhcp
Using Gateway IP Address NONE
Using VLAN Tag NONE
Are these settings correct(y/n)? y

 ✓ Using Storage for Template Storage.
 ✓ Using VMs2 for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 120 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.85 
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 - Building PhotoPrism...root@proxmox2:~#

**Comment by tteck** [comment]
There's no work around for that. Maybe throw more CPU cores and RAM at it.

**Comment by kezc7** [comment]
Upping it to 4 cores and 4gb of RAM worked. Thanks for all of your help :)

**Comment by heisenberg2980** [comment]
@kezc7 @tteck I am getting an "Unknown failure" error in the Installing Tensorflow step, but setting up 4 cores and 4Gb of RAM didn´t help, do you have any other idea?

![image](https://user-images.githubusercontent.com/58039006/166312063-19ceca91-e716-4425-ba6d-a37abdaef2bd.png)

**Comment by heisenberg2980** [comment]
> Try
> 
> ```
> 
> ```
> 
> I set it to ONLY install the CPU version without checking... Hopefully this will get you past the AVX check

@tteck what is the command to install the CPU version without checking?

**Comment by tteck** [comment]
Try
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/cpu/ct/photoprism-v3.sh)"
```

**Comment by tteck** [comment]
If that works for you, I'm gonna make it an option to check for Advanced Vector Extensions

**Comment by heisenberg2980** [comment]
It worked, it is now "Building PhotoPrism", thank you!!

EDIT: installation completed successfully
