### ISSUE TITLE
pimox-haos-vm: ERROR 25@311 Unknown failure occurred.

### ISSUE THREAD

**Issue by Yngve0** [tteck/Proxmox#1916]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I try to install pimox-haos-vm on  a Raspberry pi 4 8GB running pimox 7.2.7 running on.
The following error occour:
Creating a HAOS VM using the above default settings
 ✓ Using vmstore01 for Storage Location.
 ✓ Virtual Machine ID is 106.
 ✓ https://github.com/home-assistant/operating-system/releases/download/11.0/haos_generic-aarch64-11.0.qcow2.xz
 ✓ Downloaded haos_generic-aarch64-11.0.qcow2.xz
 ✓ Extracted Disk Image
 - Creating HAOS VM...‼ ERROR 25@311 Unknown failure occurred.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Linux version 6.1.21-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023

### Please provide detailed steps to reproduce the issue.

I used sudo bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/pimox-haos-vm.sh)" with standard settings

**Comment by tteck** [comment]
Check and see if you have a stray vm-106-disk-0 present. If so, remove it.

![Screenshot 2022-10-26 7 00 35 PM](https://github.com/tteck/Proxmox/assets/21342670/1943a828-0390-4804-bb56-c2b8035bc675)
(old pic)

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by Yngve0** [comment]
Thanks solved.
