### ISSUE TITLE
CasaOS update

### ISSUE THREAD

**Issue by BliXem1** [tteck/Proxmox#1918]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

4.4.3 is out, when will this be updated? When I'm executing "bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/casaos.sh)", and then update on LXC it stays on 4.4.2.

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
