### ISSUE TITLE
Docker LXC - 400 Parameter verification failed

### ISSUE THREAD

**Issue by mikebernat** [tteck/Proxmox#192]
### Discussed in https://github.com/tteck/Proxmox/discussions/190  deleted
<div type='discussions-op-text'>

<sup>Originally posted by **mikebernat** April 24, 2022</sup>
This is my first time trying to use these scripts. I ran the install command for Docker LXC so I could test out portainer and got the following error:

```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker-v3.sh)"


  _____             _
 |  __ \           | |
 | |  | | ___   ___| | _____ _ __
 | |v3| |/ _ \ / __| |/ / _ \  __|
 | |__| | (_) | (__|   <  __/ |
 |_____/ \___/ \___|_|\_\___|_|

Using Default Settings
Using CT Type Unprivileged NO DEVICE PASSTHROUGH
Using CT Password Automatic Login
Using CT ID 100
Using CT Name docker
Using Disk Size 4GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 - Downloading LXC Template...400 Parameter verification failed.
template: no such template
pveam download <storage> <template>
[ERROR] 255@120 A problem occured while downloading the LXC template.
```

Am I doing something wrong?</div>

**Comment by tteck** [comment]
Are you able to download a CT Template manually?

**Comment by tteck** [comment]
I'm guessing a new Proxmox install (CT ID 100). Have you ran the Proxmox VE 7 Post Install script?

**Comment by tteck** [comment]
???

**Comment by mikebernat** [comment]
Thank you for the feedback! 

I'm at work and unable to access proxmox. I'll try your suggestions this evening and report back.

**Comment by mikebernat** [comment]
Success! 

I ran the PVE 7 Post Install script. Then updated Proxmox via the proxmox GUI. Restarted. Then was able to install Docker w/ Portainer. 

Much thanks!
