### ISSUE TITLE
Alpine Nextcloud Hub Failing during creation

### ISSUE THREAD

**Issue by phellarv** [tteck/Proxmox#1927]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I try to create the Alpine Nextcloud Hub with default settings, it ends in an error message.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Alpine
Using Default Settings
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 106
Using Hostname: alpine-nextcloud
Using Disk Size: 2GB
Allocated Cores 2
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Alpine-Nextcloud LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using vmdata for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 106 was successfully created.
 ✓ Started LXC Container
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)
ERROR: unable to select packages:
  bash (no such package):
    required by: world[bash]

[ERROR] in line 567: exit code 1: while executing command pct exec "$CTID" -- ash -c "apk add bash >/dev/null"

### Please provide detailed steps to reproduce the issue.

Create the Alpine Nextcloud Hub with default settings.

**Comment by phellarv** [comment]
For the record - I have tried again later (about 10 hours later), and the same error occurs.

**Comment by tteck** [comment]
Cannot replicate the issue

```
    _   __          __       __                __   __  __      __
   / | / /__  _  __/ /______/ /___  __  ______/ /  / / / /_  __/ /_
  /  |/ / _ \| |/_/ __/ ___/ / __ \/ / / / __  /  / /_/ / / / / __ \
 / /|  /  __/>  </ /_/ /__/ / /_/ / /_/ / /_/ /  / __  / /_/ / /_/ /
/_/ |_/\___/_/|_|\__/\___/_/\____/\__,_/\__,_/  /_/ /_/\__,_/_.___/
Alpine
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: alpine-nextcloud
Using Disk Size: 2
Allocated Cores: 2
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Nextcloud LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed PHP/Redis
 ✓ Installed MySQL Database
 ✓ Installed Nextcloud
 ✓ Added Additional Nextcloud Packages
 ✓ Started Services
 ✓ Finished Nextcloud Setup-Wizard
 ✓ Customized Container
 ✓ Completed Successfully!

Alpine-Nextcloud should be reachable by going to the following URL.
         https://192.168.86.253 
```
When following https://dl-cdn.alpinelinux.org/alpine/v3.18/main do you receive 

![Screenshot 2023-10-15 7 33 57 AM](https://github.com/tteck/Proxmox/assets/21342670/fe29a79b-02df-40b6-bd6c-e0009d5ef9d5)

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
