### ISSUE TITLE
tteck-Nextcloud

### ISSUE THREAD

**Issue by speedAmaster** [tteck/Proxmox#1928]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I used the TurnKey Nextcloud helper script to setup my Nextcloud on my proxmox - long tiome ago......

Now it looks like, I am heavily outdated (Debian 10, PHP7.3.31, Nextcloud 23.0.12 (even it says "Deine Version ist aktuell)).

Is there any hint to updated from TurnKey? Any particular order (1st PHP from 7.3 to 7.4 to 8.x)? How do I perform that in TurnKey-Container on Proxmox?

### Which Linux distribution are you employing?

Debian 10   (TurnKey GNU/Linux 16.1 (Debian 10/Buster))

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
