### ISSUE TITLE
Unable to Start `nfs-server.service` and Mount NFS Shares on SABnzbd Server

### ISSUE THREAD

**Issue by isp** [tteck/Proxmox#1932]
### Please verify that you have read and understood the guidelines.

yes

### Description
Encountering an issue where the `nfs-server.service` fails to start on the SABnzbd server, causing an inability to mount NFS shares. Attempts to utilize NFS functionalities or manually start the NFS server have been unsuccessful. 

### Context
- **System:** SABnzbd server
- **OS:** Debian (version: bookworm/main)
- **Kernel:** 6.2.16-3-pve
- **Network Storage:** ZFS Pool
- Note: Another server (Jellyfin) is able to connect and read/write to the ZFS pool with no issues.

### Issue Symptoms 
1. **Failed to Start NFS Server:**
    ```
    A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.
    ```
   
   - System logs indicating that the `nfs-server.service` job fails due to a dependency.

2. **Unable to Load NFS Kernel Module:**
    ```
    modprobe: FATAL: Module nfs not found in directory /lib/modules/6.2.16-3-pve
    ```
   
   - The NFS kernel module cannot be found or loaded.

3. **Mounting Issues:**
    ```
    root@sabnzbd:/# mount -t nfs 192.168.12.36:/pool/data /mnt/pool_data
    mount.nfs: Operation not permitted
    ```
   
   - Cannot mount NFS shares, despite proper syntax and seemingly correct configuration.

### Troubleshooting Steps Taken
- **Rebooting SABnzbd:** The system was rebooted to attempt a resolution with no success.
- **Manually Starting NFS Services:** Trying to manually start `rpcbind` and `nfs-common` services, unsuccessful.
- **Modifying and Re-configuring:** Reconfiguration using `dpkg-reconfigure` was attempted, resulting in static units not starting.
- **Checking Status of `rpcbind` and `nfs-client.target`:** Both appear to be active and running.
- **Reinstalling NFS Components:** 
  - Installed `nfs-kernel-server`, but service failed to start, and some initializations were skipped.
  - `exportfs -ra` and checking `/etc/exports` were attempted without throwing specific errors.

### Questions
- What could be the problematic dependency preventing `nfs-server.service` from starting?
- Is there a known issue with NFS kernel modules not being available or compatible with certain kernel versions?

### Additional Information
Any insights or guidance would be greatly appreciated to troubleshoot and resolve this issue. If additional logs or system details are required, please let me know.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
The script doesn't install such a service.

```
root@sabnzbd:~# systemctl list-units --type=service
  UNIT                               LOAD   ACTIVE SUB     DESCRIPTION                                    
  console-getty.service              loaded active running Console Getty
  container-getty@1.service          loaded active running Container Getty on /dev/tty1
  container-getty@2.service          loaded active running Container Getty on /dev/tty2
  cron.service                       loaded active running Regular background program processing daemon
  dbus.service                       loaded active running D-Bus System Message Bus
  ifupdown-pre.service               loaded active exited  Helper to synchronize boot up for ifupdown
  ifupdown-wait-online.service       loaded active exited  Wait for network to be configured by ifupdown
  networking.service                 loaded active exited  Raise network interfaces
  nftables.service                   loaded active exited  nftables
  postfix.service                    loaded active exited  Postfix Mail Transport Agent
  postfix@-.service                  loaded active running Postfix Mail Transport Agent (instance -)
  sabnzbd.service                    loaded active running SABnzbd
  ssh.service                        loaded active running OpenBSD Secure Shell server
  systemd-firstboot.service          loaded active exited  First Boot Wizard
  systemd-journal-flush.service      loaded active exited  Flush Journal to Persistent Storage
  systemd-journald.service           loaded active running Journal Service
  systemd-logind.service             loaded active running User Login Management
  systemd-machine-id-commit.service  loaded active exited  Commit a transient machine-id on disk
  systemd-modules-load.service       loaded active exited  Load Kernel Modules
  systemd-network-generator.service  loaded active exited  Generate network units from Kernel command line
  systemd-networkd.service           loaded active running Network Configuration
  systemd-remount-fs.service         loaded active exited  Remount Root and Kernel File Systems
  systemd-sysctl.service             loaded active exited  Apply Kernel Variables
  systemd-sysusers.service           loaded active exited  Create System Users
  systemd-tmpfiles-setup-dev.service loaded active exited  Create Static Device Nodes in /dev
  systemd-tmpfiles-setup.service     loaded active exited  Create Volatile Files and Directories
  systemd-update-utmp.service        loaded active exited  Record System Boot/Shutdown in UTMP
  systemd-user-sessions.service      loaded active exited  Permit User Sessions

```

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

My primary focus revolves around the development of application LXCs, and I'm not specialized in providing support for operational issues that may arise with these applications. 

As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
Here's a consideration, when you created the LXC container, did you use the Privileged or Unprivileged mode? The default settings are Unprivileged, whereas Jellyfin is configured as Privileged.
