### ISSUE TITLE
Updater dont start stopped containers

### ISSUE THREAD

**Issue by MorphyDK** [tteck/Proxmox#1933]
Hi :)

https://raw.githubusercontent.com/tteck/Proxmox/main/misc/update-lxcs.sh

Have been using this great tool for ages - but somehow after Proxmox 8.0 I dont see that the script starts up the stopped containers ?

I have a VM installed - its currently shutdown . If I run the updater, I only see the VMs running and not the vms not running, I recall that the scripts automatically booted up the containers if I didnt want to skip anything?

Any chance to get the opportunity to update the stopped containers as well? :)

Thanks

**Comment by tteck** [comment]
Proxmox VE LXC Updater, It only updates containers (LXC), not virtual machines (VM).

**It shows 103 as stopped**
![Screenshot 2023-10-16 8 35 57 AM](https://github.com/tteck/Proxmox/assets/21342670/735d0b0f-89aa-45a8-a169-763ec54c43dc)

**When running the script, it starts 103**
![Screenshot 2023-10-16 8 36 28 AM](https://github.com/tteck/Proxmox/assets/21342670/59820056-42ef-4796-b246-49ed60620080)

**Updates and shuts down 103**
![Screenshot 2023-10-16 8 36 39 AM](https://github.com/tteck/Proxmox/assets/21342670/48769945-1d64-4597-95e2-0ab5bc44d379)

So, there's  no issues with the script.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
