### ISSUE TITLE
Passthrough QSV to homebridge lxc

### ISSUE THREAD

**Issue by joshuata** [tteck/Proxmox#1934]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

There is currently no option to create the homebridge container with the `/dev/dri` device passed through. This would normally not matter, however plugins such as Unifi Protect can use QSV in order to accelerate video transcoding for homekit video. Thus it would be useful to have a config option to create a privileged container with the video device passed through.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
