### ISSUE TITLE
Open Media Vault LXC Install Error

### ISSUE THREAD

**Issue by LostPoE** [tteck/Proxmox#1938]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When installing Open Media Vault > Advanced > Debian 12. I get the following error when installing.
 - Installing OpenMediaVault (Patience)...
[ERROR] in line 42: exit code 100: while executing command apt-get -y --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault &> /dev/null

Not sure what to do. Looks to work on Debian 11 defaults.

Thanks

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

na

### Please provide detailed steps to reproduce the issue.

When installing Open Media Vault > Advanced > Debian 12. I get the following error when installing.

**Comment by tteck** [comment]
> - Changing Linux distributions without confirming the proper functioning of default settings.

**Comment by tteck** [comment]
https://docs.openmediavault.org/en/stable/releases.html
