### ISSUE TITLE
Proxmox - reached heap limit Allocation failed

### ISSUE THREAD

**Issue by willart7401** [tteck/Proxmox#1939]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I launch the installation of Homepage I have an error

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/85478440/911ab396-7ad2-49dc-9beb-912f6953e990)
![image](https://github.com/tteck/Proxmox/assets/85478440/c1a956aa-7611-4af2-a203-934c1c3c52f5)

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homepage.sh)"

**Comment by tteck** [comment]
I cannot reproduce the problem on my side.
```
    __  __                                          
   / / / /___  ____ ___  ___  ____  ____ _____ ____ 
  / /_/ / __ \/ __ `__ \/ _ \/ __ \/ __ `/ __ `/ _ \
 / __  / /_/ / / / / / /  __/ /_/ / /_/ / /_/ /  __/
/_/ /_/\____/_/ /_/ /_/\___/ .___/\__,_/\__, /\___/ 
                          /_/          /____/       
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: homepage
Using Disk Size: 3
Allocated Cores: 2
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Homepage LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Homepage
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Homepage Setup should be reachable by going to the following URL.
         http://192.168.86.253:3000 
```
![Screenshot 2023-10-17 4 42 35 PM](https://github.com/tteck/Proxmox/assets/21342670/d655ca75-781a-4b25-988c-9bf5a5617da6)

"*FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory*," this can occur when you're running a Node.js application, and it tries to allocate more memory than is available. Try increasing RAM to 2048 . 🤞🏻

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
