### ISSUE TITLE
Uptime Kuma LXC Intall fails

### ISSUE THREAD

**Issue by Lasons** [tteck/Proxmox#194]
Hi tteck,
First of all, thanks a lot for these helper scripts!
I unfortunately run into an issue with Uptime Kuma LXC while installing both in auto or advanced mode:
![image](https://user-images.githubusercontent.com/69236145/165130945-6434721e-f02f-4824-ab7d-256d2cd6778c.png)
Tried different settings, but the outcome stays the same: Unknown failure. (similar to issue #177 )
Regards

**Comment by tteck** [comment]
What's the output of 
```
wget -q --tries=10 --timeout=5 --spider https://google.com
if [[ $? -eq 0 ]]; then
        echo -e "Internet Online"
else
        echo -e "Internet Offline"
fi
```
run in the Proxmox Shell

**Comment by Lasons** [comment]
Thank you for the fast reply!
Given command returns "Internet Offline"

**Comment by tteck** [comment]
Don't know why it would error there, you just ran the code starting at line 57
But... why no Internet?

**Comment by tteck** [comment]
I just ran the script...

```
Using Default Settings
Using CT Type Unprivileged NO DEVICE PASSTHROUGH
Using CT Password Automatic Login
Using CT ID 111
Using CT Name uptimekuma
Using Disk Size 4GB
Using 1vCPU
Using 512MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.50 
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Uptime Kuma
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Uptime Kuma should be reachable by going to the following URL.
         http://192.168.86.50:3001
```

**Comment by tteck** [comment]
New Error handling is catching "Internet Offline" as an error there instead of at "Updating Container OS"
either way it was going to error without Internet

**Comment by tteck** [comment]
It's probably (always) DNS 🤣

**Comment by Lasons** [comment]
That is interesting indeed. I thought maybe Pihole is interfering and blocking the request, but it is not the case

**Comment by tteck** [comment]
What do you get when you `ping google.com`?

**Comment by Lasons** [comment]
![image](https://user-images.githubusercontent.com/69236145/165141113-6ca727a4-c720-48e5-861c-f6b1b8484331.png)
all good, I guess

**Comment by tteck** [comment]
Now if you run https://github.com/tteck/Proxmox/issues/194#issuecomment-1108799963 again

**Comment by Lasons** [comment]
![image](https://user-images.githubusercontent.com/69236145/165141679-f7d94b09-f37f-445f-92b0-eaac42b1f377.png)

**Comment by tteck** [comment]
Try
```

```

**Comment by Lasons** [comment]
> Try
> 
> ```
> 
> ```

This worked!

**Comment by Lasons** [comment]
> What's the output of
> 
> ```
> wget -q --tries=10 --timeout=20 --spider http://google.com
> if [[ $? -eq 0 ]]; then
>         echo -e "Internet Online"
> else
>         echo -e "Internet Offline"
> fi
> ```
> 
> run in the Proxmox Shell

Also here if I set spider to use https instead of http, the request comes through and I get Internet Online

**Comment by Lasons** [comment]
![image](https://user-images.githubusercontent.com/69236145/165143198-f5437aff-85b3-4b8e-9f4a-b1ab43440d27.png)

**Comment by tteck** [comment]
Interesting, it should automatically switch http >> https

**Comment by tteck** [comment]
What happens if you just spider google.com?

**Comment by Lasons** [comment]
![image](https://user-images.githubusercontent.com/69236145/165144249-b711720d-675f-4789-b6af-4fb49c81eb5c.png)

**Comment by tteck** [comment]
I'll set spider to `https://google.com`

**Comment by Lasons** [comment]
Thank you for your time. Keep up the great work!
