### ISSUE TITLE
casaos

### ISSUE THREAD

**Issue by aroundmyroom** [tteck/Proxmox#1951]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

installing tteck script with casaos under debian or ubuntu lxc

/tmp/casaos-installer/tmp.cYY6JNb2EE /
[ INFO ] Downloading https://github.com/IceWhaleTech/CasaOS-Gateway/releases/download/v0.4.4-1/linux-amd64-casaos-gateway-v0.4.4-1.tar.gz...
[FAILED] Failed to download package
++ error_handler 35 '$STD bash <(curl -fsSL https://get.casaos.io)'
++ local exit_code=1
++ local line_number=35
++ local 'command=$STD bash <(curl -fsSL https://get.casaos.io)'

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

just started the lxc in proxmox 8 and tried verbose/advanced mode and without same issue

**Comment by tteck** [comment]
> - Changing Linux distributions without confirming the proper functioning of default settings. 

```
   ______                 ____  _____
  / ____/___ __________ _/ __ \/ ___/
 / /   / __ `/ ___/ __ `/ / / /\__ \ 
/ /___/ /_/ (__  ) /_/ / /_/ /___/ / 
\____/\__,_/____/\__,_/\____//____/  
                                     
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: casaos
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Fuse Overlayfs (ZFS): no
Enable Verbose Mode: no
Creating a CasaOS LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed CasaOS
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

CasaOS Setup should be reachable by going to the following URL.
         http://192.168.86.253  
```
