### ISSUE TITLE
nextcloud - is it possible to configure it?

### ISSUE THREAD

**Issue by homonto** [tteck/Proxmox#1952]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am not able to upload file bigger than 100MB or so (cannot check exactly but around 150MB I get error: connection closed)
I think it might be missing setting: 
`If you want to increase the maximum upload size, you will also have to modify your php-fpm configuration and increase the upload_max_filesize and post_max_size values. You will need to restart php-fpm and your HTTP server in order for these changes to be applied.`

but I am not sure where to add it - the only file where it should be is in /var/lib/docker/overlay2/..../ 
and it will disappear after restart
so I am wondering if this can be set on permanent basis or later changed
thx

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by homonto** [comment]
that is fine, thx, the issue is with macos client I believe as this upload works from www

**Comment by tteck** [comment]
If it is Alpine, look in `/etc/php82/php.ini`

**Comment by homonto** [comment]
Debian 12 and there is no such folder /etc/php82
but I am not sure where the problem is: I can upload from web even 200MB but client (MacOS) throws errors at around 100MB
