### ISSUE TITLE
Password with spaces crashes script

### ISSUE THREAD

**Issue by AbelLykens** [tteck/Proxmox#1956]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When using a password with spaces I get `A problem occured while trying to create container.: numeric argument required`.

### Which Linux distribution are you employing?

Debian 12

**Comment by AbelLykens** [comment]
I use `Proxmox/raw/main/ct/docker.sh`

**Comment by tteck** [comment]
Then, do not use a space in your password.

**Comment by AbelLykens** [comment]
Yeah that solves it. Problem is that it's not clear to a user that spaces in passwords are bad. Took a while to figure out it was the spaces causing my problem 😉

**Comment by Braekpo1nt** [comment]
I also was experiencing this issue, and it took me a while to find this resolved issue. I wonder if maybe the script could include a warning that you shouldn't put spaces in your password?
