### ISSUE TITLE
HAOS on debian

### ISSUE THREAD

**Issue by k3it** [tteck/Proxmox#1958]
Would it be hard to switch HAOS script to use a debian variant instead of Alpine?   the issue is that Alpine does not appear to have support from Nvidia for their compiled GPU drivers.  This makes it difficult to pass through nvidia hardware,. eg for use with the Frigate HA add on

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
