### ISSUE TITLE
HomeAssistant OS VM

### ISSUE THREAD

**Issue by guerocp** [tteck/Proxmox#196]
hi, Im trying to install this virtual machine without luck, this is what happens when I run the vm for the first time, hiting enter, any key or esc, nothing happens
![homeassistant os](https://user-images.githubusercontent.com/54694412/165225509-f827952a-1ccc-4b0a-9c2c-fba17838e962.png)

**Comment by sian-jing** [comment]
I also have the same problem...

**Comment by tteck** [comment]
Thanks for reporting this! Has been FIXED
It downloaded and installed the wrong image, remove and recreate VM
HA devs switched things up by adding another qcow2 file
