### ISSUE TITLE
OpenWRT - unable to assign LAN to second linux bridge.

### ISSUE THREAD

**Issue by mon5termatt** [tteck/Proxmox#1960]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Please reply if you need any more info. i know im not providing a TON of info.

Trying to assign WAN to vmbr0
Trying to assign LAN to vmbr2

Script errors out, see screenshot.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/43628254/e27b53a1-ded0-453d-88a7-3416d480a231)

### Please provide detailed steps to reproduce the issue.

Run openWRT script. 

Choose advanced settings and change the LAN bridge to any newly created linux bridge (vmbr2 in my case)

Use defaults for all other options. (I had VLAN changed to 1)

**Comment by mon5termatt** [comment]
Im not even sure if this is possible to do, but I'm trying to make this work like VYOS does. But with a VPN and Web UI

I use vyos to make a private network for sharing a single IP

**Comment by tteck** [comment]
I'm unable to determine if the issue is related to the script or if it's even possible given my lack of experience with it. Until it's determined to be a script issue, it will be moved to discussions.
