### ISSUE TITLE
Problem with omada script

### ISSUE THREAD

**Issue by riddertommie** [tteck/Proxmox#1963]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

getting error:

`[ERROR] in line 33: exit code 8: while executing command wget -qL http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb`

checking the url there is no ver. 2.19 anymore but new 2.20

`[libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb](http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb)`

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

executing bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/omada.sh)" in proxmox shell

**Comment by tteck** [comment]
fixed

**Comment by riddertommie** [comment]
Works! Thanks!
