### ISSUE TITLE
Alpine docker - missing autologin

### ISSUE THREAD

**Issue by Pandiora** [tteck/Proxmox#1975]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

For what it seems the autologin feature does not apply to alpine-docker. No matter if a password is set or not.

I miserably failed enabling the autologin feature on my own via [this guide](https://wiki.alpinelinux.org/wiki/TTY_Autologin#References) utilizing agetty.

Configuring agetty for autologin seems to conflict with getty - I'm getting errors stating "permission denied" which spam the console after reboot/login: `getty: tty1: TIOCSCTTY: Operation not permitted`

I have searched for more solutions which state I should edit the inittab, but my changes do get overwritten after reboot it seems.

A workaround could be to set the console mode to console via options.

My suggestion would be to add autologin to alpine-based lxc-containers too or provide a selection on container creation.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
For Alpine, you must type "root"

**Comment by Pandiora** [comment]
That does not seem correct, since other containers state the autologin was executed.

The alpine docker one needs [user and password](https://i.imgur.com/YTZx1pQ.png).

**Comment by tteck** [comment]
If you type "root" at login, it doesn't need a password (If no password is set).

**Comment by Pandiora** [comment]
Yes, but I would like to have the same experience for all containers. Otherwise I would not use the probably more performant alpine linux.

You are using agetty for [other containers](https://github.com/tteck/Proxmox/blob/1a985d64174322be5975e8cb543789d687485a3c/misc/install.func#L140). So I believe it should be the same experience for alpine linux too, I just can't figure out how to make it work without problems.

**Comment by tteck** [comment]
Alpine is different from Debian.

As this is more a feature request than an issue it is considered closed.
