### ISSUE TITLE
HomeAssisntant install on proxmox problem

### ISSUE THREAD

**Issue by eraser17** [tteck/Proxmox#1977]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have a problem with the installation of HA on Proxmox. could you advise me how to solve it. ,
Here is outpot from proxmox.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Using Default Settings
Using HAOS Version: 11.1
Using Virtual Machine ID: 100
Using Machine Type: i440fx
Using Disk Cache: Write Through
Using Hostname: haos11.1
Using CPU Model: Host
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using MAC Address: 02:54:E5:80:42:E9
Using VLAN: Default
Using Interface MTU Size: Default
Start VM when completed: yes
Creating a HAOS VM using the above default settings
 ✓ Using local-lvm for Storage Location.
 ✓ Virtual Machine ID is 100.
 ✓ https://github.com/home-assistant/operating-system/releases/download/11.1/haos_ova-11.1.qcow2.xz
 ✓ Downloaded haos_ova-11.1.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...
[ERROR] in line 426: exit code 5: while executing command pvesm alloc $STORAGE $VMID $DISK0 4M >&/dev/null

### Please provide detailed steps to reproduce the issue.

I used this script
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)"

**Comment by tteck** [comment]
You may have a stray `vm-100-disk-0`
Remove it and run the script again.

![image](https://github.com/tteck/Proxmox/assets/21342670/245b1d29-534e-45b2-8836-6723b39d1c5f)

**Comment by eraser17** [comment]
Great. It is work.

But i still dont connect to HA. HA dont show IP adress. :(

![ha](https://github.com/tteck/Proxmox/assets/24706023/a158305f-44f4-4c9c-abaf-685a484925e2)
![ha1](https://github.com/tteck/Proxmox/assets/24706023/b3e4bbe8-22c9-4c2f-b709-71575146673e)

**Comment by tteck** [comment]
It's using IPv6. You may have to disable IPv6 in your router.

**Comment by eraser17** [comment]
I dont use IPv6 . Only IPv4

**Comment by tteck** [comment]
The "IPs" in your picture is using an IPv6 address.

**Comment by eraser17** [comment]
You were right. In youter was turn on IPv6. I disabled and restart router but same problem.

**Comment by barrywoolgar** [comment]
~In your screenshot you also had an IPv4 address showing. Assuming this hasn't changed, does http://172.30.232.1:8123 work for you?~ (Sorry, misleading response)

**Comment by tteck** [comment]
> In your screenshot you also had an IPv4 address showing

That's the Docker network.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by troykelly** [comment]
@tteck Per https://github.com/tteck/Proxmox/issues/1989, I'm not sure how this is a duplicate?
Are you saying that I can not have a vm100 with any disks?
There are no stray/superflous disks for 108 which I am trying to create using your script.

How do I enable verbose mode as requested?

<img width="307" alt="Screenshot by Dropbox Capture" src="https://github.com/tteck/Proxmox/assets/4564803/f726d30b-9943-418e-9a4d-2ddee59ebee3">

**Comment by tteck** [comment]
```
bash -c "set -x; $(wget -qO- https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)"
```
