### ISSUE TITLE
alpine-nextcloud credentials not showing

### ISSUE THREAD

**Issue by josephwaligorski** [tteck/Proxmox#1979]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

when installing alpine-nextcloud on proxmox it does not show the username or password for the admin account. I turned on verbose logging and this is what was shown:
<img width="584" alt="image" src="https://github.com/tteck/Proxmox/assets/16547803/56706041-fd60-4820-b06e-d66a4ece2dca">

In the code I found this line:
<img width="669" alt="image" src="https://github.com/tteck/Proxmox/assets/16547803/ae1e4190-adbc-419d-b044-fc22d0bcd713">

With that information I figured out that the username should be ncadmin and the password should have the same structure. I removed the \e[32m from the beginning and \e[0m from the end of the password and it gave me the password. 

The goal is to provide the user with the username and password when installing this. These lines of code may need to be reviewed.

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

To reproduce this, just install the alpine-nextcloud on proxmox 8.0.4.

**Comment by tteck** [comment]
Follow the instructions.

![Screenshot 2023-10-29 11 51 33 AM](https://github.com/tteck/Proxmox/assets/21342670/c3bde87f-5e79-4f5c-afcf-7fec20131dbf)

**Comment by josephwaligorski** [comment]
I am not able to run that command because the LXC Console asks for the login. I followed the directions and could still could not get the credentials. I really appreciate all the work you put into this, and it has been a huge help for someone who is not fully versed on proxmox. 
<img width="671" alt="image" src="https://github.com/tteck/Proxmox/assets/16547803/7a14c8fe-e987-44f8-8f0a-92b44fff93a4">

**Comment by tteck** [comment]
type `root` for the login and press enter
then paste
```
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-nextcloud.sh)"
```
within the console and hit enter
follow the instructions

**Comment by josephwaligorski** [comment]
Thanks the root part was what I was missing.
