### ISSUE TITLE
esphome Request not successful (500) when attempting to create device

### ISSUE THREAD

**Issue by plantoschka** [tteck/Proxmox#1981]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I run esphome as lxc on Proxmox as provided by the script here. When I try to create a device by clicking on "New device" it asks me for a name and wifi credentials. After that I need to select a device type. I pick ESP32 and get the error "Request not successful (500)".

It does not matter what I pick here alway get the same error.

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="429" alt="Bildschirmfoto 2023-10-30 um 15 32 29" src="https://github.com/tteck/Proxmox/assets/2125129/6d63fc7f-9e16-4695-9f10-97598f505d40">

**Comment by tteck** [comment]
~> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.]~(https://github.com/tteck/Proxmox/discussions) 

~As this issue is unrelated to the script, it is considered closed.~

**Comment by plantoschka** [comment]
I could fix that by manually creating a config folder under /root

**Comment by tteck** [comment]
Explain

**Comment by tteck** [comment]
My installation has this folder

![Screenshot 2023-10-30 1 40 01 PM](https://github.com/tteck/Proxmox/assets/21342670/6fb8a2fa-4586-45f6-8c88-88f18fba70d5)

**Comment by plantoschka** [comment]
> Explain

Did a fresh install yesterday with your script by running
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/esphome.sh)"

Installed version was [2023.10.4].

The /config folder did not exist. I had to create it manually.

**Comment by tteck** [comment]
Testing now...

**Comment by tteck** [comment]
You are correct. I'll fix the script to create the directory.
