### ISSUE TITLE
Overseerr initial install exits with error

### ISSUE THREAD

**Issue by danofun** [tteck/Proxmox#1983]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Unable to install Overseerr

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

` ✓ Installed Node.js
+ msg_info 'Installing Yarn'
+ local 'msg=Installing Yarn'
+ echo -ne ' - \033[33mInstalling Yarn...'
 - Installing Yarn...+ npm install -g yarn

added 1 package in 836ms
npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.2.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.1
npm notice Run npm install -g npm@10.2.1 to update!
npm notice 
+ msg_ok 'Installed Yarn'
+ local 'msg=Installed Yarn'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mInstalled Yarn\033[m'
 ✓ Installed Yarn
+ msg_info 'Installing Overseerr (Patience)'
+ local 'msg=Installing Overseerr (Patience)'
+ echo -ne ' - \033[33mInstalling Overseerr (Patience)...'
 - Installing Overseerr (Patience)...+ git clone -q https://github.com/sct/overseerr.git /opt/overseerr
+ cd /opt/overseerr
+ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@npmcli/fs/-/fs-1.1.1.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/opt/overseerr/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
++ error_handler 43 '$STD yarn install'
++ local exit_code=1
++ local line_number=43
++ local 'command=$STD yarn install'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m43\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn install\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m43\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn install\033[m'

[ERROR] in line 43: exit code 1: while executing command $STD yarn install
++ [[ 43 -eq 24 ]]
+ exit`

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/overseerr.sh)"

**Comment by tteck** [comment]
The script runs without any problems from this end. 
The demanding build process may require additional system resources.

```
   ____
  / __ \_   _____  _____________  ___  __________
 / / / / | / / _ \/ ___/ ___/ _ \/ _ \/ ___/ ___/
/ /_/ /| |/ /  __/ /  (__  )  __/  __/ /  / /
\____/ |___/\___/_/  /____/\___/\___/_/  /_/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: overseerr
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Overseerr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Installed Overseerr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Overseerr should be reachable by going to the following URL.
         http://192.168.86.253:5055 
```

**Comment by danofun** [comment]
I attempted this may times before opening the issue. It now runs without throwing an error. Your magic extends beyond the code.. Cheers!
