### ISSUE TITLE
Unable to install HAOS on Proxmox 8

### ISSUE THREAD

**Issue by troykelly** [tteck/Proxmox#1989]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Unable to start verbose output as requested - I can't find any documentation on enabling verbose, and there's no mention of verbose mode in the code.

```
Using Advanced Settings
Using HAOS Version: 11.1
Virtual Machine ID: 108
Using Machine Type: q35
Using Disk Cache: Write Through
Using Hostname: example.com
Using CPU Model: Host
Allocated Cores: 6
Allocated RAM: 8192
Using Bridge: vmbr0
Using MAC Address: FF:AA:CC:EE:00:99
Using Vlan: 4
Using Interface MTU Size: Default
Start VM when completed: no
Creating a HAOS VM using the above advanced settings
 ✓ Using local-zfs for Storage Location.
 ✓ Virtual Machine ID is 108.
 ✓ https://github.com/home-assistant/operating-system/releases/download/11.1/haos_ova-11.1.qcow2.xz
 ✓ Downloaded haos_ova-11.1.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...
[ERROR] in line 426: exit code 4: while executing command pvesm alloc $STORAGE $VMID $DISK0 4M >&/dev/null
```

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Run script, answer prompts as above, see failure.

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one. 

https://github.com/tteck/Proxmox/issues/1977

**Comment by acebik** [comment]
I put data directly in the variables that fit my situation and ran it, and it worked.

example. pvesm alloc local-smb 101 vm-101-disk-0 4M 

So I downloaded it without running the script, modified all the variables to actual values, and ran it myself, 
and the installation was complete.

Well, there was a variable error in the next line as well, so I corrected the variables additionally 
whenever I got into trouble several times... This is how hard it is...

(You only need to change the variables in the row in question near the end of the script and the variables in the next two to three lines that are related to disk information.
Disk-related information varies from user to user, so you can modify it on your own...)


Download the script file
wget - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh
 
Give the script file permission to execute
chmod 777 ./haos-vm.sh 
 
Modify the variables in the script 
nano ./haos-vm.sh

You can run the script with .
bash -c "./haos-vm.sh"
