### ISSUE TITLE
Nginx Proxy Manager: Testing Server Reachability - "Communication with the API failed, is NPM running correctly?"

### ISSUE THREAD

**Issue by Chr1stian** [tteck/Proxmox#1991]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing the LXC with the script and trying to get started like I usually do with Nginx Proxy Manager, the testing for server reachability feature returns error message: 
"Communication with the API failed, is NPM running correctly?"

I have forwarded the ports get the "splash page" when I navigate to my external IP from a device outside my network.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="492" alt="Screenshot 2023-11-01 at 19 21 01" src="https://github.com/tteck/Proxmox/assets/5319700/8109e860-aa53-4e50-8de8-6c79cb9433b7">

### Please provide detailed steps to reproduce the issue.

1. Run script to install Nginx Proxy Manager LXC
2. Try to create Lets Encypt SSL Certificate
3. Receive error as shown in image

**Comment by tteck** [comment]
My primary focus revolves around the development of application LXCs, and I'm not specialized in providing support for operational issues that may arise with these applications.

**Comment by tteck** [comment]
Lets send this over to discussions...
