### ISSUE TITLE
Home assistant fails to update in Prodman HomeAssistant LXC

### ISSUE THREAD

**Issue by vahron** [tteck/Proxmox#1994]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to update HomeAssistant Proxmox LXC container by running this in **container** console

`> root@homeassistant:~# bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/podman-homeassistant.sh)"
`
Select "update home assistant", observe the following output
```shell
                     ____            __                                      
                    / __ \____  ____/ /___ ___  ____ _____                   
                   / /_/ / __ \/ __  / __  __ \/ __  / __ \                  
                  / ____/ /_/ / /_/ / / / / / / /_/ / / / /                  
    __  __       /_/    \____/\__,_/_/ /_/ /_/\__,_/_/ /_/__              __ 
   / / / /___  ____ ___  ___     /   |  __________(_)____/ /_____ _____  / /_
  / /_/ / __ \/ __  __ \/ _ \   / /| | / ___/ ___/ / ___/ __/ __  / __ \/ __/
 / __  / /_/ / / / / / /  __/  / ___ |(__  |__  ) (__  ) /_/ /_/ / / / / /_  
/_/ /_/\____/_/ /_/ /_/\___/  /_/  |_/____/____/_/____/\__/\__,_/_/ /_/\__/  
 
 ✓ Updated Successfully
 - Updating All Containers
...Trying to pull docker.io/docker.io/homeassistant/home-assistant:stable...
Error: initializing source docker://docker.io/homeassistant/home-assistant:stable: reading manifest stable in docker.io/docker.io/homeassistant/home-assistant: unauthorized

[ERROR] in line 77: exit code 125: while executing command podman pull "docker.io/${CONTAINER_IMAGE}"
``` 

Probably the error in repeating **docker.io** twice. Running the following succeeds.
```shell
root@homeassistant:~# podman pull docker.io/homeassistant/home-assistant:stable
Trying to pull docker.io/homeassistant/home-assistant:stable...
Getting image source signatures
Copying blob 79cd4486b380 skipped: already exists  
....
Copying blob 63fd14225570 skipped: already exists  
Copying config c8f5f65748 done  
Writing manifest to image destination
Storing signatures
c8f5f65748b5ca6e89f5faae4f28eb9eb14c7d644d4e0743500c54b35cca878d
```

And running this fails with the same update error
```shell
root@homeassistant:~# podman pull docker.io/docker.io/homeassistant/home-assistant:stable
Trying to pull docker.io/docker.io/homeassistant/home-assistant:stable...
Error: initializing source docker://docker.io/homeassistant/home-assistant:stable: reading manifest stable in docker.io/docker.io/homeassistant/home-assistant: unauthorized
```

### Which Linux distribution are you employing?

Default Settings

root@homeassistant:~# uname -r
6.2.16-3-pve

### Please provide detailed steps to reproduce the issue.

1. Install Podman Homeassistant LXC with priviledged mode, by running `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/podman-homeassistant.sh)"`

2. Switch to container console, try to update by running `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/podman-homeassistant.sh)"`

3. Observe update failed with error `Error: initializing source docker://docker.io/homeassistant/home-assistant:stable: reading manifest stable in docker.io/docker.io/homeassistant/home-assistant: unauthorized`

**Comment by tteck** [comment]
fixed

**Comment by vahron** [comment]
Thanks for swift update, appreciate it!
