### ISSUE TITLE
Updating plex with plexupdate error

### ISSUE THREAD

**Issue by gcraenen** [tteck/Proxmox#1995]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Scripts stops with error:

/var/lib/dpkg/info/plexmediaserver.postinst: line 527: gpg: command not found
PlexMediaServer install: WARNING: Unable to install Plex GPG signing key in /usr/share/keyrings/plexmediaserver.gpg
PlexMediaServer install: PlexMediaServer-1.32.8.7639-fb6452ebf - Installation successful.  Errors: 0, Warnings: 1
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...

[ERROR] in line 70: exit code 10: while executing command bash -c "$(wget -qO - https://raw.githubusercontent.com/mrworf/plexupdate/master/extras/installer.sh)"

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
This happened while trying to "Install plexupdate" with the update script?

**Comment by tteck** [comment]
If I cannot reproduce the problem on my side, I cannot address an issue that appears to be functioning correctly here.

**Comment by tteck** [comment]
I have no idea why you need `gpg`, but you can install it by executing this command: `apt-get install gnupg`

As this issue is unrelated to the script, it is considered closed.

**Comment by gcraenen** [comment]
Yes, it is a lxc container originally installed with this script and running. I wanted to update plex so I ran the bash command in the lxc container, choose plexupdate. After answering some question the script errored out with this error. So it is related to the script.

**Comment by gcraenen** [comment]
> This happened while trying to "Install plexupdate" with the update script?

Yes

**Comment by tteck** [comment]
The script runs without any problems from this end.

**Comment by gcraenen** [comment]
> I have no idea why you need `gpg`, but you can install it by executing this command: `apt-get install gnupg`
> 
> As this issue is unrelated to the script, it is considered closed.

Me neither. Is is something that the script starts.

**Comment by gcraenen** [comment]
> The script runs without any problems from this end.

Ok, no idea what could be the cause then. The plex container runs fine, updating it with the script just doesn't work here. Guess I have to update it manually or dump the container and use a docker.
