### ISSUE TITLE
Post-PVE-install add capability to remove ceph repository

### ISSUE THREAD

**Issue by ndoggac** [tteck/Proxmox#1997]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Post PVE8 installation.   I had elected yes on remove enterprise, yes on install no sub repo, yes to add disabled repo, no to install ceph, and yes to disable HA, and yes to update Proxmox.  The update failed.  In troubleshooting I realized the update didn't work because the ceph repository was still left enabled.  It needs to be disabled at least for this combination of choices.  I'm not sure if it should be left enabled based on other choice combinations.

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Install PVE8 
Run post-pve-install script
Elect yes on remove enterprise, yes on install no sub repo, yes to add disabled repo, no to install ceph, yes to disable HA, and yes to update Proxmox.
The apt update should fail.
Manually run apt update and it fails.
Edit /etc/apt/sources.list.d/ceph.list and comment the repo out
Manually run apt update again and it works.

**Comment by tteck** [comment]
Here is what the whiptail message states
>The 'Ceph Package Repositories' provides access to both the 'no-subscription'(enabled) and 'enterprise'(disabled) repositories.

If you'd answered "yes" as recommended, everything would have been fine. Maybe I need to reword "Add 'ceph package repositories?" to "Fix 'ceph package repositories?"

**Comment by tteck** [comment]
Changed the wording to "**Correct ceph package sources?**" This aligns better with the previous question, "**Correct Proxmox VE sources?**" that was asked earlier.

**Comment by ndoggac** [comment]
Thanks for lightning response!  And thanks for all your efforts!  I guess I misinterpreted, wasn't using ceph, so don't add them.  "Correct" seems more apt.
