### ISSUE TITLE
How i can add user and password for the dashboard?

### ISSUE THREAD

**Issue by oohiggsoo** [tteck/Proxmox#1998]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello, I'm trying to set a user + password for the dashboard, unfortunately it doesn't work with the command "esphome dashboard --username USER --password MYPASSWORD configuration".
Greetings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
