### ISSUE TITLE
name only in lowercase

### ISSUE THREAD

**Issue by pisabird** [tteck/Proxmox#1999]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

hello,
really a great thing! 
Unfortunately, the containers are created in lowercase. You ask for ID, for host, but not for the name? I used your ioBroker container script, and as you correctly write ioBroker in your installation process, I place a lot of value on the name of the container being ioBroker.

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
Using lowercase letters for hostnames is a recommended best practice, as it helps maintain consistency and minimizes the likelihood of confusion. The scripts in use adhere to this practice. It's also possible to change hostnames after creating an LXC container, but exercising caution is crucial to prevent any disruptions to your system's functionality.

**Comment by tteck** [comment]
Comments should be added to this issue, not creating a new one.
