### ISSUE TITLE
Privileged vs Unprivileged?

### ISSUE THREAD

**Issue by ma3d1um** [tteck/Proxmox#20]
Hi, thanks for your super useful Proxmox scripts. I used them to install Zigbee2MQTT and MQTT LXC's successfully.
But now I see that they are "Privileged", is there any special reason for that? Because I understand that they are considered [unsafe and therefore discouraged](https://linuxcontainers.org/lxc/security/). FYI: I'm happily running another Ubuntu LXC with a number of Docker containers, _unprivileged_

**Comment by tteck** [comment]
I understand your concerns, although I've never heard of any issues so far 🤞🏻 Some of the LXC's are required privileged for device passthrough and such. You can convert a privileged container into a unprivileged by making a backup of the LXC in local storage, remove the LXC, and then restore by running the following in the Proxmox shell. Of course you'll need to change the ID and backup name.
```yaml
pct restore 106 /var/lib/vz/dump/vzdump-lxc-106-2022_01_30-15_28_29.tar.zst -ignore-unpack-errors 1 -unprivileged --storage local-lvm
```
If you do decide to go unprivileged, I would be interested in hearing which worked and which didn't.

**Comment by tteck** [comment]
Every LXC in the dev branch is a unprivileged container for testing
Just replace `main` with `dev` in the script path

**Comment by ma3d1um** [comment]
Thanks for looking into this; I tried the pct restore as unprivileged but that one failed to start unfortunately, so I'm leaving this for now. I feel more comfortable with unprivileged containers, so I think I'm going to re-set them up manually in a few days.

**Comment by tteck** [comment]
Weird, I've never had the pct restore method not start 🤷🏻‍♂️

**Comment by tteck** [comment]
@ma3d1um NEW Unprivileged Install Scripts
