### ISSUE TITLE
photoprism installation missing "users" menu

### ISSUE THREAD

**Issue by shafai** [tteck/Proxmox#2005]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I don't know if it has anything with the script, but I used it to install photoprism. instsllation worked fine, but the settings menu only has "license", "upgrade" and "About". looking at the photoprism website, there must be a "users" menu there to add users.

I was wondering if anyone else has encountered the same issue.

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
Did you look at the top menu bar?

**Comment by tteck** [comment]
The script utilizes the official PhotoPrism binary. If you encounter any operational issues or have questions, it's advisable to address them on their [GitHub repository](https://github.com/photoprism/photoprism).
