### ISSUE TITLE
PhotoPrism Install Not Completing 

### ISSUE THREAD

**Issue by damienbowman** [tteck/Proxmox#201]
![Screen Shot 2022-04-27 at 17 16 20](https://user-images.githubusercontent.com/47603513/165634469-5632da68-f642-46d6-83e2-248c18530c66.png)

This same thing happens when I run most of the scripts on Proxmox, so i assume it isn't exclusive to PhotoPrism.

Thoughts?

**Comment by tteck** [comment]
It's failing at the Internet check. I removed it in PhotoPrism, try it now.

**Comment by tteck** [comment]
Improved Internet Check. All scripts should work for you.

**Comment by damienbowman** [comment]
![Screen Shot 2022-04-28 at 14 53 36](https://user-images.githubusercontent.com/47603513/165825743-18b53d91-4cee-407f-a73e-f8cf7e747974.png)

Looks the like sort of the same error. Is it possible it's a configuration issue somewhere on my side?

**Comment by tteck** [comment]
Try disabling IPv6

**Comment by damienbowman** [comment]
Exact same error. Disabled IPv6, and all filtering on my PfSense. Everything is just running straight to the internet. No special setup on proxmox -- i can dump diagnostic info (if you tell me where it is) if you think that would help? Again, every script has the same issue.

**Comment by tteck** [comment]
I'm thinking it's a network issue somehow, Firewall, DNS?
I am NOT a network guru, sorry.

**Comment by tteck** [comment]
What do you get when you `ping google.com` in the Proxmox Shell?

**Comment by tteck** [comment]
```
root@proxmox:~# ping google.com
PING google.com (172.217.2.46) 56(84) bytes of data.
64 bytes from atl14s78-in-f14.1e100.net (172.217.2.46): icmp_seq=1 ttl=113 time=35.1 ms
64 bytes from atl14s78-in-f14.1e100.net (172.217.2.46): icmp_seq=2 ttl=113 time=50.1 ms
64 bytes from atl14s78-in-f14.1e100.net (172.217.2.46): icmp_seq=3 ttl=113 time=39.1 ms
64 bytes from atl14s78-in-f14.1e100.net (172.217.2.46): icmp_seq=4 ttl=113 time=40.9 ms
64 bytes from atl14s78-in-f14.1e100.net (172.217.2.46): icmp_seq=5 ttl=113 time=36.4 ms
64 bytes from atl14s78-in-f14.1e100.net (172.217.2.46): icmp_seq=6 ttl=113 time=35.8 ms
^C
--- google.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5004ms
rtt min/avg/max/mdev = 35.128/39.581/50.112/5.112 ms
```

**Comment by damienbowman** [comment]
works

Linux pve 5.4.174-2-pve #1 SMP PVE 5.4.174-2 (Thu, 10 Mar 2022 15:58:44 +0100) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@pve:~# ping google.com
PING google.com (142.250.152.100) 56(84) bytes of data.
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=1 ttl=103 time=23.3 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=2 ttl=103 time=23.0 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=3 ttl=103 time=23.3 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=4 ttl=103 time=22.7 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=5 ttl=103 time=23.4 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=6 ttl=103 time=22.9 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=7 ttl=103 time=23.6 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=8 ttl=103 time=22.8 ms
64 bytes from ia-in-f100.1e100.net (142.250.152.100): icmp_seq=9 ttl=103 time=23.3 ms
^C
--- google.com ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 19ms
rtt min/avg/max/mdev = 22.703/23.128/23.581/0.302 ms
root@pve:~#

**Comment by tteck** [comment]
Yours
```
Linux pve 5.4.174-2-pve #1 SMP PVE 5.4.174-2 (Thu, 10 Mar 2022 15:58:44 +0100) x86_64
```
Mine
```
Linux proxmox 5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200) x86_64
```
What PVE version are you on? run `pveversion` in the Proxmox Shell
Have you ran the Proxmox VE 7 Post Install script?

**Comment by tteck** [comment]
Looks like you're on Proxmox VE 6.x
These scripts are designed for Proxmox VE 7.x

**Comment by damienbowman** [comment]
![Screen Shot 2022-04-28 at 19 48 39](https://user-images.githubusercontent.com/47603513/165865227-5fc5b798-7fd6-4665-8cdc-f444c19957a4.png)

I'm about ready to give up. I did get Proxmox updated, so thank you for that, but at a complete loss as to what else the issue could be. Still can ping from the shell.

**Comment by tteck** [comment]
Try this
```

```

**Comment by damienbowman** [comment]
Success!! Thanks so much for your help and patience. Can I ask what the issue was or what I can change so some of your other packages install?

**Comment by tteck** [comment]
All I did was remove the Internet check. I'm now thinking that I should remove it from all scripts. I have no idea why your setup is failing there.

**Comment by tteck** [comment]
Removed Internet Check from ALL scripts! Hopefully you'll have no more issues!

**Comment by pikiaboy** [comment]
Hey, apolgies for raising the dead thread. But I was wondering how come photoprism was removed from the scripts? Should we not use it anymore until its on the readme?

**Comment by tteck** [comment]
@pikiaboy it's broken https://github.com/tteck/Proxmox/issues/395

**Comment by tteck** [comment]
@pikiaboy fixed

**Comment by pikiaboy** [comment]
Thanks, you're the best!
