### ISSUE TITLE
Plex LXC can't be updated - repository no longer has release file

### ISSUE THREAD

**Issue by Ancalgon** [tteck/Proxmox#2011]
### Discussed in https://github.com/tteck/Proxmox/discussions/1913

<div type='discussions-op-text'>

<sup>Originally posted by **Ancalgon** October 13, 2023</sup>
Hy guys, 

I need a hand. I have a problem with all my Ubuntu LXC installed via script, PLEX in the first place. The 22.10 verion of ubuntu is not available anymore so I can't update  my Plex setup. I have tried to upgrade repositorys and force an upgrade but every time Plex not working anymore. I'm lucky that Proxmox has a backup system.

Do you have any suggestion?
```
apt update
Hit:1 https://downloads.plex.tv/repo/deb public InRelease
Ign:2 http://archive.ubuntu.com/ubuntu kinetic InRelease
Ign:3 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease
Ign:4 http://archive.ubuntu.com/ubuntu kinetic-security InRelease
Err:5 http://archive.ubuntu.com/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.36 80]
Err:6 http://archive.ubuntu.com/ubuntu kinetic-updates Release
  404  Not Found [IP: 185.125.190.36 80]
Err:7 http://archive.ubuntu.com/ubuntu kinetic-security Release
  404  Not Found [IP: 185.125.190.36 80]
Reading package lists... Done
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-updates Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-security Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Usign the Plex script inside the container:
`[ERROR] in line 63: exit code 100: while executing command apt-get update &> /dev/null`
</div>

**Comment by X-Anonymous-Y** [comment]
I think the reason is:

Version.          | Code name    | Docs.                | Release.                 | End of Life
Ubuntu 22.10 | Kinetic Kudu | Release Notes | October 20, 2022 | July 20, 2023

Maybe Backup your files and create a New LXC Container with the New Ubuntu Version / LTS Version :)

**Comment by Ancalgon** [comment]
Isn't impossible of course, but I would prefer to continue to use the script in future. And I can't if I'm build my own lxc

**Comment by X-Anonymous-Y** [comment]
Just test the Upgrade command in Terminal:

sudo do-release-upgrade -c
