### ISSUE TITLE
Issues with deploying Alpine Nextcloud Script

### ISSUE THREAD

**Issue by bradleyshelley-cloud** [tteck/Proxmox#2015]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

failure while deploying.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

+ apk add nextcloud-mysql mariadb mariadb-client
ERROR: unable to select packages:
  so:libicui18n.so.73 (no such package):
    required by: php82-intl-8.2.12-r0[so:libicui18n.so.73]
  so:libicuio.so.73 (no such package):
    required by: php82-intl-8.2.12-r0[so:libicuio.so.73]
  so:libicuuc.so.73 (no such package):
    required by: php82-intl-8.2.12-r0[so:libicuuc.so.73]
++ error_handler 50 '$STD apk add nextcloud-mysql mariadb mariadb-client'
++ local exit_code=6
++ local line_number=50
++ local 'command=$STD apk add nextcloud-mysql mariadb mariadb-client'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m50\033[m: exit code \033[01;31m6\033[m: while executing command \033[33m$STD apk add nextcloud-mysql mariadb mariadb-client\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m50\033[m: exit code \033[01;31m6\033[m: while executing command \033[33m$STD apk add nextcloud-mysql mariadb mariadb-client\033[m\n'

[ERROR] in line 50: exit code 6: while executing command $STD apk add nextcloud-mysql mariadb mariadb-client

+ exit

### Please provide detailed steps to reproduce the issue.

failure during script run.

**Comment by tteck** [comment]
fixed
