### ISSUE TITLE
Linkwarden script execution issue - database string is invalid.

### ISSUE THREAD

**Issue by Zovix** [tteck/Proxmox#2017]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Database connection error during execution of script.

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

Done in 113.78s.
+ yarn prisma migrate deploy
yarn run v1.22.19
$ /opt/linkwarden/node_modules/.bin/prisma migrate deploy
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database

Error: P1013: The provided database string is invalid. invalid port number in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
++ error_handler 84 '$STD yarn prisma migrate deploy'
++ local exit_code=1
++ local line_number=84
++ local 'command=$STD yarn prisma migrate deploy'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m84\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn prisma migrate deploy\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m84\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn prisma migrate deploy\033[m'

[ERROR] in line 84: exit code 1: while executing command $STD yarn prisma migrate deploy
++ [[ 84 -eq 24 ]]
+ exit

### Please provide detailed steps to reproduce the issue.

Execute script.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    __    _       __                           __
   / /   (_)___  / /___      ______ __________/ /__  ____
  / /   / / __ \/ //_/ | /| / / __ `/ ___/ __  / _ \/ __ \
 / /___/ / / / / ,<  | |/ |/ / /_/ / /  / /_/ /  __/ / / /
/_____/_/_/ /_/_/|_| |__/|__/\__,_/_/   \__,_/\___/_/ /_/

Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: linkwarden
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Linkwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Cloned Linkwarden Repository
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> 
 ✓ Installed Linkwarden
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Linkwarden should be reachable by going to the following URL.
         http://192.168.86.253:3000 
```

**Comment by tteck** [comment]
Standard PostgreSQL port
https://github.com/tteck/Proxmox/blob/95e26b68427592dbf25e8f187a0ebe7ab22cce51/install/linkwarden-install.sh#L81

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
