### ISSUE TITLE
Linkwarden - Unable to install

### ISSUE THREAD

**Issue by joanfercal** [tteck/Proxmox#2021]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

I get the message "[ERROR] in line 73: exit code 1: while executing command $STD yarn"
Tested with 2 different servers, PVE 7 and PVE 8
Same result.
Using Ubuntu 22.04

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

+ msg_info 'Installing Linkwarden (Patience)'
+ local 'msg=Installing Linkwarden (Patience)'
+ echo -ne ' - \033[33mInstalling Linkwarden (Patience)...'
 - Installing Linkwarden (Patience)...+ yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[12/12] ⡀ @prisma/client
[-/12] ⡀ waiting...
[10/12] ⡀ sharp
[-/12] ⡀ waiting...
error /opt/linkwarden/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /opt/linkwarden/node_modules/sharp
Output:
sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-linux-x64.t

++ error_handler 73 '$STD yarn'
++ local exit_code=1
++ local line_number=73
++ local 'command=$STD yarn'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m73\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m73\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn\033[m'

[ERROR] in line 73: exit code 1: while executing command $STD yarn
++ [[ 73 -eq 24 ]]
+ exit

### Please provide detailed steps to reproduce the issue.

Run: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/linkwarden.sh)"

**Comment by tteck** [comment]
Just tested again and the script runs without any problems from this end. 

```
    __    _       __                           __
   / /   (_)___  / /___      ______ __________/ /__  ____
  / /   / / __ \/ //_/ | /| / / __ `/ ___/ __  / _ \/ __ \
 / /___/ / / / / ,<  | |/ |/ / /_/ / /  / /_/ /  __/ / / /
/_____/_/_/ /_/_/|_| |__/|__/\__,_/_/   \__,_/\___/_/ /_/

Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: linkwarden
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Linkwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Cloned Linkwarden Repository
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> 
 ✓ Installed Linkwarden
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Linkwarden should be reachable by going to the following URL.
         http://192.168.86.253:3000 
```
As this issue is unrelated to the script, it is considered closed.
