### ISSUE TITLE
Error when running script in proxmox

### ISSUE THREAD

**Issue by pootsounds** [tteck/Proxmox#2022]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

bash: -c: line 58: unexpected EOF while looking for matching `''

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Not enough information.

**Comment by pootsounds** [comment]
referring to this line in the script
RELEASE=$(curl -s https://api.github.com/repos/Kareadita/Kavita/releases/latest | grep "tag_name" | awk '{print substr($2, 2, l>

assuming the bash error is coming from the (') in the (awk '{print) section toward the end

    __ __            _ __       
   / //_/___ __   __(_) /_____ _
  / ,< / __ `/ | / / / __/ __ `/
 / /| / /_/ /| |/ / / /_/ /_/ / 
/_/ |_\__,_/ |___/_/\__/\__,_/  
                                
Loading...
bash: -c: line 58: unexpected EOF while looking for matching `''
root@ProxMox:~#

**Comment by tteck** [comment]
fixed
be sure to clear browser cache
