### ISSUE TITLE
Homarr Update LXC

### ISSUE THREAD

**Issue by xekil** [tteck/Proxmox#2025]
Good morning,

Homarr has just been updated and there is a new mount point to make in the LXC container so that it can continue to work correctly. https://github.com/ajnart/homarr/releases

How do I apply this update correctly so that the mount point is created?

If I apply this command I don't think the mount point will be created
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homarr.sh)"

I also just saw that it has disappeared from the site as well https://tteck.github.io/

THANKS

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

Homarr is currently undergoing extensive development, and we do not recommend installing it from source at this point. As a result, Homarr has been taken down from this site. We kindly suggest using the Docker installation method as an alternative.

**Comment by xekil** [comment]
ok thanks

**Comment by tteck** [comment]
Homarr is back!

**Comment by xekil** [comment]
great, thank you, the update will automatically create the necessary assembly links for the new version?

**Comment by xekil** [comment]
great, thanks, I tried to create a new container with the default settings and I get the error below:

```
[ERROR] in line 42: exit code 1: while executing command sed -i 's/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'"$(openssl rand -base64 32)"'"/' /opt/homarr/.env
root@pve:~# 
```
