### ISSUE TITLE
Minor textual issue by "Proxmox VE Backup Server Post Install"

### ISSUE THREAD

**Issue by GrumpyMeow** [tteck/Proxmox#2026]
I'm not here to complain.. Just here to help making your scripts even more perfect.

This is the current text which i think is not correct:
`Run the command below in the Proxmox VE Shell. ⚠️ Proxmox VE Backup Server ONLY`

I have PBS running on my PVE host, given the instruction so i thought i would be able to run the command in the Proxmox VE Shell. But this gives the following error:
`🛑  PVE Detected, Wrong Script!`
I expected this error already, but the instruction is somewhat unclear.

I think the text should've said:
`Run the command below in the Proxmox Backup Server. ⚠️ Proxmox Backup Server ONLY`

The Proxmox product names are:
* Proxmox VE
* Proxmox Backup Server

**Comment by tteck** [comment]
Thanks
