### ISSUE TITLE
script backup and restore hass probelms - LXC version

### ISSUE THREAD

**Issue by sarunyu** [tteck/Proxmox#203]
volume path is change to  /var/lib/docker/volumes/hass_config/_data

`
    {
        "CreatedAt": "2022-04-29T17:52:14Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/hass_config/_data",
        "Name": "hass_config",
        "Options": {},
        "Scope": "local"
    }
]`

**Comment by tteck** [comment]
I'm not following
Better explanation of issue

**Comment by tteck** [comment]
⚙️ **Path to HA /config**
```yaml
/var/lib/docker/volumes/hass_config/_data
 ```
This has always been the path
