### ISSUE TITLE
Turnkey fileserver creation

### ISSUE THREAD

**Issue by sascha-hemi** [tteck/Proxmox#2030]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When i create a new Turnkey fileserver LXC i became this error: 1@212 Unknown failure occured
and the lxc pops up and instantly goes away

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

run this: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/turnkey/turnkey.sh)" and select fileserver.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
 ______              __ __           __   _  _______
/_  __/_ _________  / //_/__ __ __  / /  | |/_/ ___/
 / / / // / __/ _ \/ ,< / -_) // / / /___>  </ /__
/_/  \_,_/_/ /_//_/_/|_|\__/\_, / /____/_/|_|\___/
                           /___/

[INFO] LXC container '112' was successfully created, and its IP address is 192.168.86.12.

[INFO] Proceed to the LXC console to complete the setup.

[INFO] login: root
[INFO] password: t9/f7ikRyFw=

```

```
root@server:~# cat turnkey-fileserver.creds
TurnKey fileserver password: t9/f7ikRyFw=
```

**Comment by tteck** [comment]
Looks like it's failing while attempting to retrieve the IP address. Are you using SSH? 
https://github.com/tteck/Proxmox/blob/026ad7bbec68d9f3f253ea1b100461a5182b3cb6/turnkey/turnkey.sh#L212

**Comment by tteck** [comment]
You can download the script and remove lines 206 thru 226 and execute the script locally to bypass the "get IP function".

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/1742
