### ISSUE TITLE
Error when updating Vaultwarden to version V1.30.0 using the script within the LXC

### ISSUE THREAD

**Issue by bobvmierlo** [tteck/Proxmox#2031]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the script within the container and choosing to update VaultWarden (so nog the Web-Vault) I get the error below after about 10 minutes:
[ERROR] in line 82: exit code 101: while executing command cargo build --features "sqlite,mysql,postgresql" --release &> /dev/null

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
Try allocating more resources to the container.

**Comment by bobvmierlo** [comment]
Disksize was the issue, thanks for the tip.
