### ISSUE TITLE
Jellyfin does not seem to have networking mounting 

### ISSUE THREAD

**Issue by MasterCATZ** [tteck/Proxmox#2035]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am just wondering how others are mounting their network drives with Jellyfin using bookworm 

mine seems to be missing the mount.<type>  files in the sbin folder?
are we meant to be installing these packages ourselves? 

just about to retry with the Ubuntu version 

tried nfs and cifs 

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

~~~
bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
       dmesg(1) may have more information after failed mount system call.
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
~~~

### Please provide detailed steps to reproduce the issue.

Fresh install trying to get network mapping working

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
