### ISSUE TITLE
Nginx Proxy manager - default.json

### ISSUE THREAD

**Issue by danmed** [tteck/Proxmox#204]
Hi,

I'm looking at switching from a docker container to your LXC for NPM but i use an external MariaDB database.

I've found the default.json where i set the connection string but it's in a folder with the NPM version number : 

/nginx-proxy-manager-2.9.18/backend/config/default.json

I am concerned that when i upgrade the lxc using your update script, any changes i make to this file will be lost.. 

Am i right to be concerned or does this file get moved to the new version too?

Edit : OK, now i'm looking at that file, it's already set to mysql.. which says to me it's not being used as i see no MySQL or MariaDB processes running in the LXC.... so.. i guess my question is.. how do i point this LXC to an external MariaDB server?

**Comment by tteck** [comment]
This installation is using sqlite3 _only_, contained in the LXC (`/data/database.sqlite`) so that the app and all data can be backed up and restored together.
