### ISSUE TITLE
Homarr LXC not installing

### ISSUE THREAD

**Issue by xekil** [tteck/Proxmox#2045]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Good morning,

Homarr LXC does not install, there is an error message.

THANKS

```
[ERROR] in line 42: exit code 1: while executing command sed -i 's/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'"$(openssl rand -base64 32)"'"/' /opt/homarr/.env
root@pve:~# 
```

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

   __  __
   / / / /___  ____ ___  ____ ___________
  / /_/ / __ \/ __ `__ \/ __ `/ ___/ ___/
 / __  / /_/ / / / / / / /_/ / /  / /
/_/ /_/\____/_/ /_/ /_/\__,_/_/  /_/

Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 109
Using Hostname: homarr
Using Disk Size: 4GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Homarr LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 109 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.70 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 - Installing Homarr (Patience)...sed: -e expression #1, char 84: unknown option to `s'

[ERROR] in line 42: exit code 1: while executing command sed -i 's/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'"$(openssl rand -base64 32)"'"/' /opt/homarr/.env
root@pve:~# 

### Please provide detailed steps to reproduce the issue.

Creation of a new LXC container with default parameters.
OS: Proxmox 8.0.4

**Comment by tteck** [comment]
That is a valid `sed` command. Delete browser cache and try again.
https://github.com/tteck/Proxmox/discussions/2039#discussioncomment-7546371

**Comment by xekil** [comment]
Thanks, that was good :)

**Comment by xekil** [comment]
Thanks, that was good :)

**Comment by dragonfire1119** [comment]
@tteck This is caused by the output of `openssl rand -base64 32`, which can include the `/` character. Since `/` is being used as the delimiter in your sed command, any `/` in the replacement string can break the command.

I would propose changing it to:

```
sed -i 's|NEXTAUTH_SECRET="[^"]*"|NEXTAUTH_SECRET="'"$(openssl rand -base64 32)"'"|' /opt/homarr/.env
```

It uses `|` instead of `/` as the delimiter for the sed substitution command.

**Comment by tteck** [comment]
@dragonfire1119 You are correct, thanks for catching this. Changes will be made.
