### ISSUE TITLE
Add Storage to OMV LXC

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#2046]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I ran the OMV script. Now need to find a way to add storage. When I add it as a mountpoint, OMV doesn't recognize it. Can you please advice ?

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by Jens-Wymeersch** [comment]
@tteck I looked on the discussion section (with open topic) but no solution

**Comment by tteck** [comment]
Have you looked through this discussion https://github.com/tteck/Proxmox/discussions/1075 ?

**Comment by Jens-Wymeersch** [comment]
@tteck I'm getting the following error when I try to setup the LXC in advanced setup.
`[ERROR] in line 42: exit code 100: while executing command apt-get -y --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault &> /dev/null`

**Comment by tteck** [comment]
Linux distribution?

**Comment by Jens-Wymeersch** [comment]
Please note that I choose Debian 12 - once I moved to Debian 11 - it worked - maybe this should be mentioned somewhere more clearly.

**Comment by tteck** [comment]
![Screenshot 2023-11-13 6 48 40 AM](https://github.com/tteck/Proxmox/assets/21342670/50aac6b6-f636-4f0d-912b-2c3637902e87)

**Comment by Jens-Wymeersch** [comment]
thanks mate - always amazing how you make your scripts
