### ISSUE TITLE
Installing Homarr resulting with an error

### ISSUE THREAD

**Issue by megusd** [tteck/Proxmox#2050]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

An error past installation of Node.js/Yarn

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`added 1 package in 4s
+ msg_ok 'Installed Node.js/Yarn'
+ local 'msg=Installed Node.js/Yarn'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mInstalled Node.js/Yarn\033[m'
 ✓ Installed Node.js/Yarn
+ msg_info 'Installing Homarr (Patience)'
+ local 'msg=Installing Homarr (Patience)'
+ echo -ne ' - \033[33mInstalling Homarr (Patience)...'
 - Installing Homarr (Patience)...+ git clone -q https://github.com/ajnart/homarr.git /opt/homarr
+ cd /opt/homarr
+ cp -p /opt/homarr/.env.example /opt/homarr/.env
++ openssl rand -base64 32
+ sed -i 's/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="XSH/OL1bnljWXyVe4O9CnA7hIILjdjfabyz37KeTOyI="/' /opt/homarr/.env
sed: -e expression #1, char 48: unknown option to `s'
++ error_handler 42 'sed -i '\''s/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'\''"$(openssl rand -base64 32)"'\''"/'\'' /opt/homarr/.env'
++ local exit_code=1
++ local line_number=42
++ local 'command=sed -i '\''s/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'\''"$(openssl rand -base64 32)"'\''"/'\'' /opt/homarr/.env'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m42\033[m: exit code \033[01;31m1\033[m: while executing command \033[33msed -i '\''s/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'\''"$(openssl rand -base64 32)"'\''"/'\'' /opt/homarr/.env\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m42\033[m: exit code \033[01;31m1\033[m: while executing command \033[33msed -i '\''s/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'\''"$(openssl rand -base64 32)"'\''"/'\'' /opt/homarr/.env\033[m'

[ERROR] in line 42: exit code 1: while executing command sed -i 's/NEXTAUTH_SECRET="[^"]*"/NEXTAUTH_SECRET="'"$(openssl rand -base64 32)"'"/' /opt/homarr/.env
++ [[ 42 -eq 24 ]]
+ exit
root@pve:~# `

### Please provide detailed steps to reproduce the issue.

Running the script :
'
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homarr.sh)"
'

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one. 

https://github.com/tteck/Proxmox/issues/2045
