### ISSUE TITLE
Error while update Alpine-Vaultwarden, or Set the Admin Token, run the command below in the LXC Console.

### ISSUE THREAD

**Issue by mariomsamy** [tteck/Proxmox#2052]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

when i use the command give me this error 
![Screenshot at Nov 14 07-40-46](https://github.com/tteck/Proxmox/assets/16023864/ff18c57e-1824-4d5d-9921-e0b90ee908f1)

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 _    __            ____                          __         
| |  / /___ ___  __/ / /__      ______ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
 Alpine                                                 

Loading...
environment: line 56: apk: command not found

[ERROR] in line 56: exit code 127: while executing command apk add -q newt

**Comment by X-Anonymous-Y** [comment]
Run 

> ### Please verify that you have read and understood the guidelines.
> yes
> 
> ### A clear and concise description of the issue.
> when i use the command give me this error ![Screenshot at Nov 14 07-40-46](https://user-images.githubusercontent.com/16023864/282674821-ff18c57e-1824-4d5d-9921-e0b90ee908f1.png)
> 
> ### Which Linux distribution are you employing?
> Debian 12
> 
> ### If relevant, including screenshots or a code block can be helpful in clarifying the issue.
> | | / /___ ___ **/ / /** ______ ________**/ /** ____ | | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __ / _ / __ | |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / / / /_/ / **/ / / / |**_/__,_/__,_/_/__/ |**/|**/__,_/_/ __,_/___/_/ /_/ Alpine
> 
> Loading... environment: line 56: apk: command not found
> 
> [ERROR] in line 56: exit code 127: while executing command apk add -q newt
> 
> ### Please provide detailed steps to reproduce the issue.
> _No response_

Run this for Debian: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/vaultwarden.sh)"

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
