### ISSUE TITLE
tasmoadmin

### ISSUE THREAD

**Issue by tigertim08** [tteck/Proxmox#2053]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hallo Zusammen, 

ich habe Tasmoadmin über das Skript erstellt, erhalte aber leider keinen Zugriff auf die Oberfläche. Über meine Netzwerkverwaltung sehe ich, dass die ip Vergabe funktioniert hat und auch Datenpakete hin und her geschickt werden. Ein ping vom Rechner an den LXC funktioniert auch. 

Hat jemand eine Idee wo mein Fehler liegt 

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![2023-11-14_12-15-50](https://github.com/tteck/Proxmox/assets/24661102/915864d6-1160-4d88-a610-692e7d5258b9)

IP Settings:
`2: eth0@if41: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 62:42:b0:f2:22:88 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.50.117/24 brd 10.0.50.255 scope global dynamic eth0
       valid_lft 79622sec preferred_lft 79622sec
    inet6 fd17:a797:4e5c:413b:6042:b0ff:fef2:2288/64 scope global dynamic mngtmpaddr 
       valid_lft 1632sec preferred_lft 1632sec
    inet6 fe80::6042:b0ff:fef2:2288/64 scope link 
       valid_lft forever preferred_lft forever`

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
  ______                           ___       __          _ 
 /_  __/___ __________ ___  ____  /   | ____/ /___ ___  (_)___
  / / / __ `/ ___/ __ `__ \/ __ \/ /| |/ __  / __ `__ \/ / __ \
 / / / /_/ (__  ) / / / / / /_/ / ___ / /_/ / / / / / / / / / /
/_/  \__,_/____/_/ /_/ /_/\____/_/  |_\__,_/_/ /_/ /_/_/_/ /_/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: tasmoadmin
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a TasmoAdmin LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed TasmoAdmin
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

TasmoAdmin should be reachable by going to the following URL.
         http://192.168.86.253:9999 
```
![Screenshot 2023-11-14 6 25 58 AM](https://github.com/tteck/Proxmox/assets/21342670/85a8fa55-08e7-4924-a896-f08b949965b0)

**Comment by tteck** [comment]
BTW, English only.
