### ISSUE TITLE
Homarr - Unable to write

### ISSUE THREAD

**Issue by brusarp** [tteck/Proxmox#2054]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Just fresh install of Homarr script.
After the installation (all seems fine) the Homarr homepage says that "is unable to write to the database".

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/14950532/148cd4ce-c479-49f3-a7e6-38ecf2795ad4)

### Please provide detailed steps to reproduce the issue.

Just install Homarr with LXC Script

**Comment by tteck** [comment]
finally fixed

**Comment by brusarp** [comment]
> finally fixed

Yes! Thank you for your prompt availability and resolution of the issue! 👍🏻👍🏻👍🏻

**Comment by biz5000** [comment]
i am having the same issue.  how did you resove this problem?

**Comment by tteck** [comment]
No issues here.

```
    __  __
   / / / /___  ____ ___  ____ ___________
  / /_/ / __ \/ __ `__ \/ __ `/ ___/ ___/
 / __  / /_/ / / / / / / /_/ / /  / /
/_/ /_/\____/_/ /_/ /_/\__,_/_/  /_/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: homarr
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Homarr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Installed Homarr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Homarr should be reachable by going to the following URL.
         http://192.168.86.250:3000 
```
![Screenshot 2024-07-17 8 48 18 PM](https://github.com/user-attachments/assets/02ce4828-e580-48a4-b212-24966357a298)

![Screenshot 2024-07-17 8 49 30 PM](https://github.com/user-attachments/assets/6021c324-0ec4-400c-825c-c95b9ff0e59b)
