### ISSUE TITLE
Turnkey LCX - nextcloud script doesn't work

### ISSUE THREAD

**Issue by kornelremete** [tteck/Proxmox#2055]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

If I try to install then the following message appears:
[ERROR] 1@179 Unable to find a template when searching for 'debian-11-turnkey-nextcloud'.

It is because the template file is for the debian 12.

### Which Linux distribution are you employing?

Debian 12

**Comment by raffaelevall** [comment]
> ### Verifica di aver letto e compreso le linee guida.
> SÌ
> 
> ### Una descrizione chiara e concisa del problema.
> Se provo a installare, viene visualizzato il seguente messaggio: [ERRORE] 1@179 Impossibile trovare un modello durante la ricerca di "debian-11-turnkey-nextcloud".
> 
> È perché il file modello è per Debian 12.
> 
> ### Quale distribuzione Linux stai utilizzando?
> Debian12
> 
> ### Se pertinente, includere screenshot o un blocco di codice può essere utile per chiarire il problema.
> _Nessuna risposta_
> 
> ### Fornisci i passaggi dettagliati per riprodurre il problema.
> _Nessuna risposta_

same issue with proxmox 8.0.4

**Comment by tteck** [comment]
fixed

**Comment by tteck** [comment]
Note: You can always utilize the All Templates script for a full list of what's available.
