### ISSUE TITLE
Homarr update fail

### ISSUE THREAD

**Issue by brusarp** [tteck/Proxmox#2056]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The update script exit with:

[ERROR] in line 60: exit code 128: while executing command git stash &> /dev/null

Upgrading from 0.14 to 0.14.1

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/14950532/b62acaf0-c10d-4566-b5db-6f30d43d0c09)

**Comment by tteck** [comment]
After using a new installation method, there is currently no established or available update path.
Update now states such.

**Comment by brusarp** [comment]
So, just to understand, now that there is one new release (0.14.1) what we have to do? Just "wait" it and retry?

**Comment by tteck** [comment]
That's what I'm trying to figure out.

**Comment by brusarp** [comment]
Oh, good... sorry 👍 take it easy 😉

**Comment by tteck** [comment]
Ready for an attempt to upgrade?

**Comment by brusarp** [comment]
Stand-by
![Screenshot_20231114_233435_Chrome.jpg](https://github.com/tteck/Proxmox/assets/14950532/784a4b43-feb8-4173-90be-55308a91c36b)

**Comment by brusarp** [comment]
![Screenshot_20231114_234041_Chrome.jpg](https://github.com/tteck/Proxmox/assets/14950532/5eb8f2e7-7426-49e9-be22-b15255982918)

Good job, as always 💪🏻👍🏻
(approx 5min of "patience" with an i5)

**Comment by brusarp** [comment]
Hi @tteck, I'm writing here because I think the latest problem today is linked to the latest changes made... This morning I updated an already customized installation (0.14.0) and I practically lost the dashboard I had created... it's possible there was a wrong wipe?

**Comment by tteck** [comment]
The update is backing up the data and database folders, building the new release version, and restoring the backed up folders. I'll look again to see if I made an error.

**Comment by tteck** [comment]
fixed

**Comment by brusarp** [comment]
> fixed

I'll try next update... thanks for your work 👍🏻
