### ISSUE TITLE
ESPHome UI not accessible unless LXC created with autologon

### ISSUE THREAD

**Issue by BigFam194** [tteck/Proxmox#2062]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the script bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/esphome.sh)" and adding a root password, I can't access the ESPHome UI after the instal completes. If I run the same script and select no password the resulting system is fine and I can access the ESPHome UI. I've confirmed it both in Default and Advanced mode on several different Proxmox hosts 8.0.4 with kernel Linux 6.2.16-19-pve. The error message in browser is ERR_CONNECTION_REFUSED

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. Run scriptbash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/esphome.sh)"
2. Select Advanced, step through all default values except provide a root password and enable root access
3. After the install finishes, go to the URL provided in the script output
4. The error message is ERR_CONNECTION_REFUSED

**Comment by tteck** [comment]
Strange, but fixed.

**Comment by BigFam194** [comment]
Wow, that was super fast. Thanks a lot for all your work and contributions!

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: tteckster ***@***.***>
Skickat: Friday, November 17, 2023 1:39:58 AM
Till: tteck/Proxmox ***@***.***>
Kopia: BigFam ***@***.***>; Author ***@***.***>
Ämne: Re: [tteck/Proxmox] ESPHome UI not accessible unless LXC created with autologon (Issue #2062)


Strange, but fixed.
