### ISSUE TITLE
No network!

### ISSUE THREAD

**Issue by Hackatoan** [tteck/Proxmox#2064]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Getting No Network! on all the scripts. Some still work some don't. 
The ones that worked were nginx, wireguard, and debian. 
the ones that are failing are nextcloud, plex, and vaultwarden. 
in the image i used advanced as a test but normally i use default and got same results. 
network settings are basically unchanged in proxmox. 

*i am new so i assume i could be missing something obvious. 
also what network settings is the script referring to. Proxmox? 
my network is just a standard spectrum internet and router. 

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/62629253/563b8c71-e619-4d59-b39b-541ecaa036ca)

### Please provide detailed steps to reproduce the issue.

Use nextcloud, plex, or debian install script with default settings.

**Comment by tteck** [comment]
Sounds like an IPv6 issue. Can you turn off IPv6 in your router to test?

The script looks to make sure it has an IP address.
https://github.com/tteck/Proxmox/blob/f2aed7d532d04fa29edf16c32c9329bc4398e3d5/misc/install.func#L74C1-L85C5

Are you out of assignable (DHCP) IPs?

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
