### ISSUE TITLE
Navidrome download link fail 404

### ISSUE THREAD

**Issue by b3ni** [tteck/Proxmox#2065]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Fail script install navidrome.

https://github.com/tteck/Proxmox/blob/main/ct/navidrome.sh

Downalod link fail:

```
[ERROR] in line 30: exit code 8: while executing command $STD wget https://github.com/navidrome/navidrome/releases/download/v${RELEASE}/navidrome_${RELEASE}_Linux_x86_64.tar.gz -O Navidrome.tar.gz
```

Latest release is 0.50.0

I think the link correct is:

https://github.com/navidrome/navidrome/releases/download/v0.50.0/navidrome_0.50.0_linux_amd64.tar.gz

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/navidrome.sh)"

debian 12

**Comment by tteck** [comment]
fixed
