### ISSUE TITLE
Trying to run https://github.com/tteck/Proxmox/raw/main/vm/haos-vm-v5.sh

### ISSUE THREAD

**Issue by ahadata** [tteck/Proxmox#2067]
Hi

Trying to run your excellent script for HA OS install on proxmox
github.com/tteck/Proxmox/raw/main/vm/haos-vm-v5.sh
But parts seem to be missing in git

Best regards
Anders

**Comment by X-Anonymous-Y** [comment]
> Hi
> 
> Trying to run your excellent script for HA OS install on proxmox github.com/tteck/Proxmox/raw/main/vm/haos-vm-v5.sh But parts seem to be missing in git
> 
> Best regards Anders

Try this link: [https://raw.githubusercontent.com/tteck/Proxmox/main/vm/haos-vm.sh](https://raw.githubusercontent.com/tteck/Proxmox/main/vm/haos-vm.sh)

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
