### ISSUE TITLE
 Nginx Proxy Manager LXC script missing certbot-dns-desec

### ISSUE THREAD

**Issue by nexusband** [tteck/Proxmox#2069]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When using the script, certbot for lets encrypt is installed. however, it is installed not with all addons, so using a dns-challange for desec.io is impossible and will result in certbot not recognizing the command.

![grafik](https://github.com/tteck/Proxmox/assets/109827980/bff3892b-9c74-4378-bb2e-8686e583db59)

Manually installing the plugin with `pip3 install certbot-dns-desec` solves the issue

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`certbot: error: unrecognized arguments: --dns-desec-credentials /etc/letsencrypt/credentials/credentials-6`

**Comment by tteck** [comment]
As there are 100's of cert-bots, you are required to install the bot of your choosing. This is not a script issue.

**Comment by nexusband** [comment]
> _As there are 100's of cert-bots, you are required to install the bot of your choosing_. This is not a script issue.

Could you please add exactly that to the script description? Thanks!
