### ISSUE TITLE
nextcloudpi install script failure

### ISSUE THREAD

**Issue by AkiVonAkira** [tteck/Proxmox#2073]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

cannot install nextcloudpi 
I ran `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nextcloudpi.sh)"` in advanced mode for more storage and different password/ct id

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

hastebin of the console output in verbose mode;
https://hastebin.skyra.pw/neporifomu.prolog

**Comment by tteck** [comment]
> - Changing Linux distributions without confirming the proper functioning of default settings.
