### ISSUE TITLE
CPU Scaling govenor only offers perfomance Mode after last Proxmox update

### ISSUE THREAD

**Issue by Stephan-4711** [tteck/Proxmox#2084]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The CPU Scaling governor only shows performance since last proxmox update

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Update to latest promox non commercial updates
run CPU Scaling governor script

**Comment by tteck** [comment]
The script only shows what scaling governors are available.
```
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
```
On my system
```
root@server:~# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
performance powersave
root@server:~# 
```
![Screenshot 2023-11-21 9 06 38 AM](https://github.com/tteck/Proxmox/assets/21342670/88966954-5a84-4173-9b29-99e8feecebf9)

**Comment by Stephan-4711** [comment]
Sorry, okay.
Then something else is wrong.
My Server now used 3 times the power then before the last update.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
