### ISSUE TITLE
Dashy upgrade failed

### ISSUE THREAD

**Issue by zelig2** [tteck/Proxmox#209]
I ran the upgrade script in the Dashy console:
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/dashy-update.sh)"`
Then I got this output:
```
  _____            _           
 |  __ \          | |          
 | |  | | __ _ ___| |__  _   _ 
 | |  | |/ _  / __|  _ \| | | |
 | |__| | (_| \__ \ | | | |_| |
 |_____/ \__,_|___/_| |_|\__, |
          UPDATE          __/ |
                         |___/ 

 Stopping Dashy... ✔ 
 Backup conf.yml... ✔ 
 Updating Dashy... ✔ 
 Restoring conf.yml... cp: cannot stat 'conf.yml': No such file or directory
root@dashy:/dashy# 
```

I think as part of the upgrade process the script should start with `cd ~` as the script appears to want to be run from the home directory. After I changed to the home directory and reran the upgrade script it worked well.

**Comment by tteck** [comment]
Good catch! Thanks
