### ISSUE TITLE
Is there an easy way to edit the container config before the first container start?

### ISSUE THREAD

**Issue by ChrisLuck** [tteck/Proxmox#2091]
Thanks for your amazing work @tteck !
I only recently learned about your project here and I am already a big fan.

I am trying create a setup where multiple containers are sharing data via bindmounts as explained in "Method 2" on this page:
https://www.itsembedded.com/sysadmin/proxmox_bind_unprivileged_lxc/

To do so, the uid and gid mapping has to be added to the container's config file.
The tricky part is, that this has to be done before the container is started for the first time otherwise the new mapping will screw up the ownership of already created files.

Is there an easy way to edit the container config before the first container start?

Can the scripts somehow be "localized" so that I can clone, edit and execute them locally? (that would have to replace all github curls with relative paths)

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by ChrisLuck** [comment]
Thanks! I did not know about the discussion section.
The guidelines do not contain this particular guideline ;)

**Comment by tteck** [comment]
![Screenshot 2023-11-22 4 50 40 PM](https://github.com/tteck/Proxmox/assets/21342670/3fedeca3-facc-493f-b861-fa974ca06355)

**Comment by ChrisLuck** [comment]
Ohh sorry, got it. I took the wrong turn. I did not have an "issue pertaining specifically to the script", so I never ended up on this page but here instead:

![Screenshot at 23-13-47](https://github.com/tteck/Proxmox/assets/7473058/5c7aa343-5c92-40c4-99a1-6f43a8931c99)

Sorry for wasting your time with this.

**Comment by tteck** [comment]
Fixed
![Screenshot 2023-11-22 5 39 36 PM](https://github.com/tteck/Proxmox/assets/21342670/57da2063-0b22-4fdd-8358-8597fe6a8fce)
