### ISSUE TITLE
Grocy LXC install

### ISSUE THREAD

**Issue by TomJC70** [tteck/Proxmox#2098]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Proxmox 7.2-11
Installing Grocy I get an error and the installer exits (see below). The LXC is created , but http(s)://ip is not loading (also not after restarting the lxc).
Given the Debian 12 warning, I'm installing using Ubuntu 22.04.

Copypaste lines 23 to 71 in the LXC console and running those works and after that http://ip/ shows the grocy login and it seems to work.

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
[ERROR] in line 27: exit code 100: while executing command $STD apt-get update
++ [[ 27 -eq 24 ]]
+ exit
```

### Please provide detailed steps to reproduce the issue.

Run the installer script in advanced mode

**Comment by tteck** [comment]
My first suggestion would be to upgrade to Proxmox 8.1, or at least update 7.2 to the latest version. 
Whenever the default distribution is Debian 12, I'd suggest utilizing Debian 11 instead of Ubuntu. 

I have no idea why it would fail at `apt-get update` 

The script runs without any problems from this end. 
As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
```
   ____ __________  _______  __
  / __  / ___/ __ \/ ___/ / / /
 / /_/ / /  / /_/ / /__/ /_/ / 
 \__, /_/   \____/\___/\__, /  
/____/                /____/   
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: grocy
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a grocy LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed PHP 8.1
 ✓ Installed grocy
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

grocy should be reachable by going to the following URL.
         http://192.168.86.253 
```

**Comment by TomJC70** [comment]
Thank you for the response. I don't know enough about linux environments to determine where a cause of an issue lies, so I figured better post it as an issue. Apologies for doing so incorrectly.
