### ISSUE TITLE
Nginx Proxy Manager

### ISSUE THREAD

**Issue by jonnycyborg** [tteck/Proxmox#21]
Hoping you can help me track down why it might be throwing an error installing dependencies on line 37 of npm_setup.sh:

```
root@pve:~#bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/npm_container.sh)"
This will create a New Nginx Proxy Manager LXC Container. Proceed(y/n)?y
[INFO] Using 'local-lvm' for storage location.
[INFO] LXC ID is 101.
✔  Updating LXC Template List... 
✔  Downloading LXC Template... 
✔  Creating LXC... 
✔  Starting LXC... 
✔  Setting up Container OS... 
✔  Updating Container OS... 
✔  Installing Dependencies... 
[ERROR:LXC] 100@37 Unknown failure occured.
[ERROR] 100@156 Unknown failure occured.
  Logical volume "vm-101-disk-0" successfully removed
 ```

Want to thank you for all your hard work on these awesome tools!

**Comment by tteck** [comment]
I don't understand why a few has had this issue (not just npm), I can never replicate it here. I even added an extra `apt-get update` right before installing any dependencies. Again, I just tested the Nginx Proxy Manager LXC Container script, no issues here. Install went as expected  🤷🏻‍♂️

**Comment by jonnycyborg** [comment]
Hmm yeah new proxmox install, was starting to go down your list. So far only did the Post Install, Dark theme, and Home Assistant Container LXC before this one. Also just tried Debian which worked fine too. Nothing special or custom about the setup drive/network wise and the main node shows no updates. I guess I'll have to step through it and see why apt-get is failing.

**Comment by tteck** [comment]
If you would, try the Nginx Proxy Manager LXC Container script again.

**Comment by jonnycyborg** [comment]
Same thing, and tried a reboot as well no luck.
Including what's above the command in the console screenshot just in case those version numbers help
![image](https://user-images.githubusercontent.com/17607132/151995910-e9e04fbd-6cf8-4bfc-b990-46166ac64fb3.png)

**Comment by jonnycyborg** [comment]
Following your commits, doesn't make any sense why it would fail on 37 again right?

**Comment by tteck** [comment]
Strange thing is, I changed the NPM script to match the HA script, removed the tag `--no-install-recommends` and added the normal `-qqy` tag, again runs fine here.

**Comment by jonnycyborg** [comment]
Not sure if this is the actual issue but I made some progress.
I started cutting up the install script to the bare minimum, and running commands and everything was fine.

**Comment by jonnycyborg** [comment]
It's possible the sleeps had some other effect that wasn't inherently obvious, but that seemed like a plausible cause IMO.
You certainly will have better incite than I will!

**Comment by tteck** [comment]
Glad you got it installed! Your previous attempts failed after the OS update, so I'd assume your network was active since it's a hefty download. 
I would also expect no network while starting the LXC, but be connected before updating the OS or the fail should have happened there 🤷🏻‍♂️ 
Maybe a simple `sleep 3` somewhere could help settle things on slower/complex networks?

**Comment by jonnycyborg** [comment]
Yeah I would think the `apt update` and `apt-get upgrade` would cause it to fail in the same way with no connection, right?

Just to be sure I tried the original script and it failed in the same way.
I think you'd hate the sleep solution just as much as I would 🙄

**Comment by tteck** [comment]
Just to see, I added a `sleep 3` on line 37 where it was failing. Mind testing it?

**Comment by jonnycyborg** [comment]
Hmm no dice, do we go more drastic with a 5 or 10 haha?
![image](https://user-images.githubusercontent.com/17607132/152072491-6f4e9584-78a3-470c-9128-03870925c775.png)

**Comment by tteck** [comment]
Would ya try again?

**Comment by jonnycyborg** [comment]
Nope still no go
![image](https://user-images.githubusercontent.com/17607132/152073356-daf80675-29ce-4eed-bb68-5fb9dac57dae.png)

**Comment by tteck** [comment]
I added your snippet to the code, last time I ask

**Comment by jonnycyborg** [comment]
Worked fine, what I did notice is the `Updating Container OS...` step took significantly longer that time, so it must be passing over it without a connection?

![image](https://user-images.githubusercontent.com/17607132/152074127-d91dc5e2-06aa-46cf-8b49-b6bda4e43724.png)

No worries! I'm happy to keep debugging, glad it's reproducible for my setup.

**Comment by tteck** [comment]
If you insist 😄 If this works, I may add it to all the scripts!?

**Comment by jonnycyborg** [comment]
Looks much better haha, would we need some sort of timeout or max retry count?
Feel free to remove the parentheses or tidy up as needed.
![image](https://user-images.githubusercontent.com/17607132/152075880-0ec05c86-016c-43bf-a19e-a1aa2cdbea5f.png)

**Comment by tteck** [comment]
I'll mess around with it before using it on all scripts. Thanks for your help!

**Comment by tteck** [comment]
I think I have the code finished. Take a look and see if you see anything outta place

```yaml
RETRY_NUM=5
RETRY_EVERY=3
NUM=$RETRY_NUM
while [ "$(hostname -I)" = "" ]; do
  1>&2 echo -e "${CROSS} \e[1;31m No network: \e[0m $(date)"
  sleep $RETRY_EVERY
  ((NUM--))
  if [ $NUM -eq 0 ]
  then
    1>&2 echo command No network after $RETRY_NUM tries
    exit 1
  fi
done
  echo -e "${CHECKMARK} \e[1;92m Network connected: \e[0m $(hostname -I)"
```

**Comment by jonnycyborg** [comment]
Looks okay to me! Hopefully that solves the issue for others as well. I noticed the other closed thread when you first mentioned others having a similar issue

**Comment by tteck** [comment]
🤞🏻 Hopefully this will solve those as well. It's difficult to solve an issue if I can't replicate it.

Again, thanks for your help! If you want, this can just be closed.

**Comment by jonnycyborg** [comment]
No problem, thanks again for all your hard work on these scripts. It's seriously a game changer!
