### ISSUE TITLE
Home Assistant LXC fail to pull image

### ISSUE THREAD

**Issue by Hanselljlh** [tteck/Proxmox#210]
I have tried both the LXC versions and both fail to load the Home Assistant Image after making the LXC and containers.

**Comment by tteck** [comment]
I just ran the script with no issues.

```
  _                                        _     _              _   
 | |   v3                                 (_)   | |            | |  
 | |__   ___  _ __ ___   ___  __ _ ___ ___ _ ___| |_ __ _ _ __ | |_ 
 |  _ \ / _ \|  _   _ \ / _ \/ _  / __/ __| / __| __/ _  |  _ \| __|
 | | | | (_) | | | | | |  __/ (_| \__ \__ \ \__ \ || (_| | | | | |_ 
 |_| |_|\___/|_| |_| |_|\___|\__,_|___/___/_|___/\__\__,_|_| |_|\__|

Using Default Settings
Using CT Type Unprivileged NO DEVICE PASSTHROUGH
Using CT Password Automatic Login
Using CT ID 111
Using CT Name homeassistant
Using Disk Size 16GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.32 
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed pip3
 ✓ Installed Docker v20.10.14
 ✓ Pulled Portainer 2.11.1 Image
 ✓ Installed Portainer 2.11.1
 ✓ Pulled Home Assistant 2022.4.7 Image
 ✓ Installed Home Assistant 2022.4.7
 ✓ Created Update Menu Script
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Home Assistant should be reachable by going to the following URL.
         http://192.168.86.32:8123
Portainer should be reachable by going to the following URL.
         http://192.168.86.32:9000
```

**Comment by tteck** [comment]
I'm guessing that you're not staying in the shell until you see
```
 ✓ Completed Successfully!
```

**Comment by Hanselljlh** [comment]
No I stay in the shell. Even tried from putty but both come back with failed unknown error.

**Comment by tteck** [comment]
Where? at what line?

**Comment by Hanselljlh** [comment]
Pulling Home Assistant 2022.4.7 Image

**Comment by tteck** [comment]
so it pulls Portainer Image?

**Comment by Hanselljlh** [comment]
Yes

**Comment by tteck** [comment]
`docker pull portainer/portainer-ce:latest`
`docker pull homeassistant/home-assistant:stable`

If it pulled one, it should the other. 
I can't replicate your issue on my end.
Nothing that I can do, sorry.

**Comment by Hanselljlh** [comment]
Where is it pulling the image from? I looked through the scripts but couldn't figure it out. I was going to see if I can  access it. I feel like it is more a DNS or something router related.

**Comment by tteck** [comment]
Both pulling from `https://hub.docker.com/`

**Comment by Hanselljlh** [comment]
Thank you for the info. I know it isn't a script issue at all now nor is it your problem to deal with me... But... I have played around and I think it is a docker issue. It fails to pull the image so I loaded the docker script and tried pulling HA myself and still have problems. I even spun up my first HA backup and it won't load either. Both freash docker install and my original script backup both sit at "waiting for HA CLI" then eventually scroll something I don't remeber for like 50 lines then ends with something about not reaching the docker demon then asks if it is even running. When I systemctl status docker it show active.

Either way if you can maybe point me in a direction gratefully appreciated. If not I fully understand and honestly wouldn't blame you. But at least if this issue pops up anywhere else we know it isn't a one off anymore.

**Comment by tteck** [comment]
It would be my guess that you're experiencing DNS issues
