### ISSUE TITLE
qbittorent locales issues

### ISSUE THREAD

**Issue by Patatra** [tteck/Proxmox#2106]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Using the script to install qbittorrent doesn't set the default locale to whatever.UTF-8, so when downloading a torrent whith accents (é à ç è ô, etc) those characters are replaced by a dot. It confuse the *arr software who can't find the correct filename (they are looking for "je suis une légende.mkv" but can only found "je suis une l.gende.mkv" and don't catch it).

I solved this issue just by setting the locales to fr_FR.UTF-8 but i guess it could work with en_EN.UTF-8.

Maybe setting the locales could be done within post-install?

### Which Linux distribution are you employing?

Ubuntu 23.04

### Please provide detailed steps to reproduce the issue.

Try to download whatever torrent you want with an accent in the name

**Comment by tteck** [comment]
Did you SSH into Proxmox and then create the LXC?

**Comment by Patatra** [comment]
I've used the shell from Proxmox webUI
(edit issue : i'm using ubuntu 23.04, not debian 12)

**Comment by tteck** [comment]
> - Switching Linux distributions without verifying that the default distribution is working correctly.

**Comment by Patatra** [comment]
Just tried with default distribution and the issue is still here.

<img width="787" alt="Capture d’écran 2023-11-26 à 15 14 12" src="https://github.com/tteck/Proxmox/assets/2571948/b8cda0d8-a5ba-4a14-a53f-9a336eefaff1">

The file name should be "Thérèse..."

After setting locales to C.UTF-8 : 

<img width="1193" alt="Capture d’écran 2023-11-26 à 15 17 45" src="https://github.com/tteck/Proxmox/assets/2571948/d630ed6a-253b-4067-9582-6cf6a180b70d">

**Comment by tteck** [comment]
The `install.func` script is using the variable `$LANG` from Proxmox.

https://github.com/tteck/Proxmox/blob/cb09bdf7b86645fe4378a1c95747b63dcba3d18d/misc/install.func#L70-L73

What is the output from `echo "$LANG"` when run in the Proxmox shell?

You can also run `dpkg-reconfigure tzdata` in the LXC console to correct `tzdata`

**Comment by Patatra** [comment]
<img width="782" alt="Capture d’écran 2023-11-26 à 15 30 51" src="https://github.com/tteck/Proxmox/assets/2571948/fe1f6ea3-5d7d-4066-9082-cf49f8ada614">

For the tzdata, i don't understand, it seems good to me (I'm in France, sorry I may missing a point here)
