### ISSUE TITLE
haos-vm.sh failing on line 426 (pvesm alloc)

### ISSUE THREAD

**Issue by eveiscoull** [tteck/Proxmox#2107]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

For some reason it doesn't give me an option to run verbose but when running the haos-vm.sh script, it fails on line 426 (see code below)

This happens while going through advanced mode and default. Any ideas on how to fix this?

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
    __  __                        ___              _      __              __     ____  _____
   / / / /___  ____ ___  ___     /   |  __________(_)____/ /_____ _____  / /_   / __ \/ ___/
  / /_/ / __ \/ __ `__ \/ _ \   / /| | / ___/ ___/ / ___/ __/ __ `/ __ \/ __/  / / / /\__ \
 / __  / /_/ / / / / / /  __/  / ___ |(__  |__  ) (__  ) /_/ /_/ / / / / /_   / /_/ /___/ /
/_/ /_/\____/_/ /_/ /_/\___/  /_/  |_/____/____/_/____/\__/\__,_/_/ /_/\__/   \____//____/

Using Default Settings
Using HAOS Version: 11.1
Using Virtual Machine ID: 102
Using Machine Type: i440fx
Using Disk Cache: Write Through
Using Hostname: haos11.1
Using CPU Model: Host
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using MAC Address: 02:AC:09:09:70:43
Using VLAN: Default
Using Interface MTU Size: Default
Start VM when completed: yes
Creating a HAOS VM using the above default settings
 ✓ Using local-zfs for Storage Location.
 ✓ Virtual Machine ID is 102.
 ✓ https://github.com/home-assistant/operating-system/releases/download/11.1/haos_ova-11.1.qcow2.xz
 ✓ Downloaded haos_ova-11.1.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...
[ERROR] in line 426: exit code 1: while executing command pvesm alloc $STORAGE $VMID $DISK0 4M >&/dev/null
```

### Please provide detailed steps to reproduce the issue.

1. Run `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)"`
2. Try Default or Advanced Mode
3. See error once it gets to `Creating HAOS VM...`

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/1628

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
