### ISSUE TITLE
Motioneye store on SMB

### ISSUE THREAD

**Issue by rikki78** [tteck/Proxmox#211]
Could you change the motioneye config so storing on a SMB server is possible? 
When changing the `smb_shares` to `true` in `motioneye.conf,` the program will not start.

**Comment by tteck** [comment]
Privileged or Unprivileged container?

**Comment by rikki78** [comment]
according to the [documentation ](https://github.com/motioneye-project/motioneye/wiki/Configuration-File#smb_shares)I think it should be a Privileged

**Comment by tteck** [comment]
How did you create the LXC, Privileged or Unprivileged?

**Comment by rikki78** [comment]
Initially I used the default settings (so Unprivileged) but just now I tried privileged and still it won't start

**Comment by rikki78** [comment]
I found what was needed. cifs-utils had to be installed additionally.
Thanks for your quick help!

**Comment by tteck** [comment]
![Screenshot 2022-05-03 6 35 36 AM](https://user-images.githubusercontent.com/21342670/166439512-4bce9372-16d3-4298-835a-83de0a3b5df1.png)

**Comment by rikki78** [comment]
Where can this be found?

**Comment by tteck** [comment]
![Screenshot 2022-05-03 6 54 21 AM](https://user-images.githubusercontent.com/21342670/166441480-ccbd3971-f6dd-4fd6-894e-b9295ece8f41.png)

**Comment by rikki78** [comment]
Just for your information, I've tried this again with the SMB/CIFS checkbox checked but I still had to install cifs-utils manually. Maybe I missed something again?

**Comment by tteck** [comment]
Maybe I should make it a dependency if created as privileged.

**Comment by nortuzar** [comment]
> Could you change the motioneye config so storing on a SMB server is possible? When changing the `smb_shares` to `true` in `motioneye.conf,` the program will not start.

Having exactly the same problem with a privilege LXC. I enable smb/cifs feature. The problem is when turning enable the setting on motioneye.conf

cifs-utils is installed. Do I need to install samba or something?
