### ISSUE TITLE
PBS UI not loading after update script

### ISSUE THREAD

**Issue by SamKr** [tteck/Proxmox#2111]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I've ionstalled Proxmox Backup 3.0-1, and afterwards was able to login to the web interface. I then ran `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pbs-install.sh)"`, answering yes to all options.

After reboot, the web interface stopped working giving a connection refused error. I was able to login to the terminal. 

Any idea what could go wrong, can it be because of version 3? If you need logs, please tell me which/where to find them.

Thanks in advance.

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

- Install PBS using the provided .iso
- Run script through Shell
- Let the script reboot the environment

**Comment by tteck** [comment]
Nothing in the script to cause this. Maybe the IP changed after the reboot. 🤷🏻‍♂️

**Comment by tteck** [comment]
I've never used PBS, does it use `https://` like Proxmox?

**Comment by SamKr** [comment]
Hm ok. IP stayed the same (web interface url gets printed in terminal after reboot, and confirmed manually). 

> does it use https:// like Proxmox?

Yep, on `https://ipaddress:8007`.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
