### ISSUE TITLE
MissingDependency Error after Update from Paperless 1.17.4 to 2.0.0 via Script

### ISSUE THREAD

**Issue by epcos71** [tteck/Proxmox#2117]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I did an update from Paperless 1.17.4 to 2.0.0 via the Helper script. When I a do an upload of a document I now geht the error "MissingDependencyError: gs"
In the past updates via script went really good, but now not. 

### Which Linux distribution are you employing?

Ubuntu 23.04

**Comment by tteck** [comment]
> - Switching Linux distributions without verifying that the default distribution is working correctly. 

The script was created to support the default Linux distribution. As Ubuntu 23.04 is not the default distribution, no actions will be taken.

**Comment by t0rb3n** [comment]
@tteck This error appears with debian 11 too.
https://github.com/paperless-ngx/paperless-ngx/issues/4696
The issue appears to be an outdated version of ghostscript. Debian 11 has up to 9.53.3 in their repos, 12 currently 10.0.0 which would satisfy ghostscript.

Is there any easy way to upgrade a LXC container to Debian 12? To answer myself, yes of course there is (https://github.com/tteck/Proxmox/discussions/1498)

After upgrading to Debian 12 Paperless Webserver wouldn't start due some module missing error with gunicorn. Running the update/install script again seemed to have worked. Processing new files works again.

**Comment by tteck** [comment]
Debian 12 has been the default distribution since Jun 29, 2023

**Comment by t0rb3n** [comment]
> Debian 12 has been the default distribution since Jun 29, 2023

I for instance have my LXC running longer than that 😄
