### ISSUE TITLE
Passing "yes" flag to LXC Container Update/Install script

### ISSUE THREAD

**Issue by tweibler** [tteck/Proxmox#2119]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am running the LXC install/update script via Ansible against the LXCs that I have deployed (ie. Jellyfin). This is being run on the LXC itself, and not on the Proxmox host.

Is there a way to pass a "yes" to the script (  bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jellyfin.sh)"
) like this:

> anyway to skip the first prompt for the update-lxcs script? maybe a "-f" or "-y". This would be useful in scheduling automatic updates
> 
> nevermind, using the YES command works:
> yes | bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/update-lxcs.sh)"

> From https://github.com/tteck/Proxmox/issues/914#issuecomment-1567984485

I am trying to run a similar process such as this:

> yes | bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jellyfin.sh)"

But it does not work, since I am not sure if the build script is able to accept a "yes" like the update-lxcs.sh script does.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
