### ISSUE TITLE
Photoprism - Error Building Photoprism

### ISSUE THREAD

**Issue by Normanras** [tteck/Proxmox#212]
I used this script a few months ago in an LXC and it worked without issue. I'm now trying to set up a different one and it failed on me multiple times, using default and custom settings. I see you just updated the photoprism install script 10 minutes ago, so perhaps you already know about the issue. Here is the error:

```
Are these settings correct(y/n)? y

 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 105 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.169 
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 - Building PhotoPrism...‼ ERROR 2@116 Unknown failure occured.
```

Line 116 of the script is the creation of the systemd service, so perhaps that is where it is failing?

Let me know if you already caught this bug and I can close this. Thanks for making these scripts!

**Comment by tteck** [comment]
Try it now and let me know

**Comment by Normanras** [comment]
It worked! Thanks.
