### ISSUE TITLE
Advanced install suggestions

### ISSUE THREAD

**Issue by michaelr0** [tteck/Proxmox#2124]
Hi There,

This is more of a feature request than anything else, I think that it would be handy for the installer script to provide suggestions where possible for what the default normally is, When you pick advanced.

Once such example is that it already suggests the OS to use (for support), but it would also be handy for it to suggest the container type (`Privileged` vs `Unprivileged`)

Thanks

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
![Screenshot 2023-11-29 8 08 50 PM](https://github.com/tteck/Proxmox/assets/21342670/d5ce3104-5e13-43a5-ac84-d001dfc26894)
> Blank issues will be closed immediately.

**Comment by michaelr0** [comment]
Oh yes, sorry about that
