### ISSUE TITLE
Paperless update 2.0 fails

### ISSUE THREAD

**Issue by poltrian** [tteck/Proxmox#2128]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

thanks for the amazing scripts!

Have a problem to update Paperless 2.0
` ✓ Stopped Paperless-ngx
 - Updating to v2.0.0...
[ERROR] in line 86: exit code 1: while executing command pip install -r requirements.txt &> /dev/null`

How can i fix it?

### Which Linux distribution are you employing?

Ubuntu 22.04

### Please provide detailed steps to reproduce the issue.

Run the script in LXC and update Paperless

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one. 

https://github.com/tteck/Proxmox/issues/2117

> - If the default Linux distribution is not adhered to, script support will be discontinued.
