### ISSUE TITLE
Zwave-js-ui name changed

### ISSUE THREAD

**Issue by webmogul1** [tteck/Proxmox#2129]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Looks like .zip contents changed name

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/5225701/999b9d65-e952-4697-839b-aa34d8a19d63)

**Comment by webmogul1** [comment]
you might want to take a look at that: https://github.com/zwave-js/zwave-js-ui/issues/3458

**Comment by tteck** [comment]
fixed

**Comment by tteck** [comment]
They changed the name back in 9.5.1

**Comment by webmogul1** [comment]
@tteck  Thanks!
