### ISSUE TITLE
Gitea Script - or via Turnkey ??

### ISSUE THREAD

**Issue by ngblume** [tteck/Proxmox#2131]
> Sorry for not fully complying to the rules.. no proper excuse on my side...
> My bad..
> Will try the Turnkey Appliance script, thanks !

Hej hej,

I'm relatively new to Proxmox and used your scripts heavily so far..
I plan on using Gitea at home and was wondering, if there is a plan to provide a script for Gitea as well?
I saw that it seems doable via TurnKey LXC, but maybe I don't understand the concept, but it seems that this would be a LXC container ("TurnKey LXC Appliances"), which than in itself kind of creates a container (not sure of LXC ??) for Gitea..
Maybe I am mistaken..

Thanks!

Cheers
Niels Göran

**Comment by tteck** [comment]
> Blank issues will be closed immediately.


![Screenshot 2023-11-29 8 08 50 PM](https://github.com/tteck/Proxmox/assets/21342670/b338ed89-4865-4a5f-94ed-610f28f6e476)

Yes, TurnKey **LXC** Appliances script creates a Linux container (LXC).
