### ISSUE TITLE
‼ ERROR 255@106 A problem occured while downloading the LXC template.

### ISSUE THREAD

**Issue by Wolffoxfangs** [tteck/Proxmox#214]
hey there! sorry for making an issue post, i tried a few different helper scripts and it seems like the plex one was the only one to complete properly, whenever i attempt to run any other helper script that creates LXC containers i get the following error

✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 - Downloading LXC Template...400 Parameter verification failed.
template: no such template
pveam download <storage> <template>
‼ ERROR 255@106 A problem occured while downloading the LXC template.

ive attempted both the default and advanced configurations. im sure its something simple im missing,  thank you so much what you do and for your time!

**Comment by tteck** [comment]
Run 
```
pveam download local debian-11-standard_11.3-1_amd64.tar.zst
```
in the Proxmox shell and share the results

**Comment by Wolffoxfangs** [comment]
when running that i get the following 

`root@Rhay:~# pveam download local debian-11-standard_11.3-1_amd64.tar.zst
400 Parameter verification failed.
template: no such template
pveam download <storage> <template>
root@Rhay:~# `

**Comment by tteck** [comment]
I'm no network guy, but it sounds like DNS issues 

Here's the output when I run `pveam download local debian-11-standard_11.3-1_amd64.tar.zst`
```
root@proxmox:~# pveam download local debian-11-standard_11.3-1_amd64.tar.zst
downloading http://download.proxmox.com/images/system/debian-11-standard_11.3-1_amd64.tar.zst to /var/lib/vz/template/cache/debian-11-standard_11.3-1_amd64.tar.zst
--2022-05-04 19:07:04--  http://download.proxmox.com/images/system/debian-11-standard_11.3-1_amd64.tar.zst
Resolving download.proxmox.com (download.proxmox.com)... 144.217.225.162, 2607:5300:203:7dc2::162
Connecting to download.proxmox.com (download.proxmox.com)|144.217.225.162|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 123216040 (118M) [application/octet-stream]
Saving to: '/var/lib/vz/template/cache/debian-11-standard_11.3-1_amd64.tar.zst.tmp.256718'
     0K ........ ........ ........ ........ 27% 9.41M 9s
 32768K ........ ........ ........ ........ 54% 9.97M 6s
 65536K ........ ........ ........ ........ 81% 10.1M 2s
 98304K ........ ........ .....            100% 9.97M=12s
2022-05-04 19:07:16 (9.83 MB/s) - '/var/lib/vz/template/cache/debian-11-standard_11.3-1_amd64.tar.zst.tmp.256718' saved [123216040/123216040]
calculating checksum...OK, checksum verified
download of 'http://download.proxmox.com/images/system/debian-11-standard_11.3-1_amd64.tar.zst' to '/var/lib/vz/template/cache/debian-11-standard_11.3-1_amd64.tar.zst' finished
root@proxmox:~#
```

**Comment by Wolffoxfangs** [comment]
thank you! ill poke around and see where i messed up! haha
