### ISSUE TITLE
maybe an idea to improve post-pve-install.sh robustness

### ISSUE THREAD

**Issue by github-tomster** [tteck/Proxmox#2141]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

hello world

the script can call:
```
apt-get update &>/dev/null
apt-get -y dist-upgrade &>/dev/null
```
this means no apt-related messages that require an user-interaction are displayed to the screen.
in case there are messages - for example grub related ones - the procedure waits forever  ⏳ 

is it by design or can this script only run on fresh installs?

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
