### ISSUE TITLE
Create install script with openmptcprouter

### ISSUE THREAD

**Issue by onlineapps-cloud** [tteck/Proxmox#2143]
hi, first i want to say thanks for your work, very useful scripts to deploy useful tools.
It's possible to create VM with this system like Openwrt? https://www.openmptcprouter.com
On download page at the end, persist different x86-64 (64-bits) OS types, thanks, best whishes.

**Comment by tteck** [comment]
![Screenshot 2023-11-29 8 08 50 PM](https://github.com/tteck/Proxmox/assets/21342670/75b4ce4c-4e34-4eed-965e-0d062034516e)
