### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by IIPoliII** [tteck/Proxmox#215]
Will Ubuntu 22.04 come to LXC for Proxmox, it would be awesome!

**Comment by tteck** [comment]
Run the Ubuntu LXC script, use advanced settings to define the version 18.04, 20.04, 21.10 or 22.04.

**Comment by tteck** [comment]
I just set 22.04 as default

**Comment by IIPoliII** [comment]
Thanks a lot that was fast!
