### ISSUE TITLE
In lxc kavita update script; cp: cannot overwrite directory '/opt/Kavita/Kavita' with non-directory

### ISSUE THREAD

**Issue by NL-Tristan** [tteck/Proxmox#2152]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

In lxc of kavita I want to update with the following command:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/kavita.sh)"

After confirm to proceed, I get a error:

    __ __            _ __       
   / //_/___ __   __(_) /_____ _
  / ,< / __ `/ | / / / __/ __ `/
 / /| / /_/ /| |/ / / /_/ /_/ / 
/_/ |_\__,_/ |___/_/\__/\__,_/  
                                
 - Updating Kavita LXC...cp: cannot overwrite directory '/opt/Kavita/Kavita' with non-directory

[ERROR] in line 61: exit code 1: while executing command cp -r Kavita/* /opt/Kavita

root@kavita:~# 

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

In lxc of kavita I want to update with the following command:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/kavita.sh)"

After confirm to proceed, I get the error

**Comment by tteck** [comment]
The error message indicates that you're trying to copy the contents of the "Kavita" directory into the "/opt/Kavita" directory, but there is a subdirectory named "Kavita" inside the destination directory.

I don't know why you have the path `/opt/Kavita/Kavita`.

**Comment by tteck** [comment]
Creating a new Kavita LXC and updating has no issues
```
    __ __            _ __       
   / //_/___ __   __(_) /_____ _
  / ,< / __ `/ | / / / __/ __ `/
 / /| / /_/ /| |/ / / /_/ /_/ / 
/_/ |_\__,_/ |___/_/\__/\__,_/  
                                
 ✓ Updated Kavita LXC
root@kavita:~# 
```

**Comment by tteck** [comment]
Is there anything in `/opt/Kavita/Kavita`? If not, just remove that subdirectory.

**Comment by NL-Tristan** [comment]
There was  /opt/Kavita/Kavita present on my server, I did not create this folder with contents. After deleting this folder the update script is working now. Thank you.
