### ISSUE TITLE
After Kavita update script in LXC, Kavita is not reachable by webbrowser. 

### ISSUE THREAD

**Issue by NL-Tristan** [tteck/Proxmox#2156]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I start the update script in kavita lxc with the following command:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/kavita.sh)"

After pressing on "Proceed" Kavita is updating and don't give a error.

Kavita is not reachable by a webbrowser;  http://<ip van kavita server>:5000

I saw in journalctl -xe , the following messages:
 
**The error number returned by this process is ERRNO.
Dec 05 00:11:54 kavita systemd[686]: kavita.service: Failed at step EXEC spawning /opt/Kavita/Kavita: Permission denied
-- Subject: Process /opt/Kavita/Kavita could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support**  

In console I give the following command:
**chmod +x  /opt/Kavita/Kavita**

Then:
**systemctl start kavita**   (now kavita is reachable with a webbrowser.

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

See "A clear and concise description of the issue"

**Comment by tteck** [comment]
I'm guessing this is for reference. You could also have combined your 3 issues into 1 to make them easier for someone to find.

As this issue is unrelated to the script, it is considered closed.
