### ISSUE TITLE
Wireguard - Update breaks connectivity

### ISSUE THREAD

**Issue by almostserious** [tteck/Proxmox#216]
When I install Wireguard (PIVPN) via the script, and add a client the connection works fine.
If there is an update, or if i reinstall pivpn (update it) something breaks and im unable to even connect to the host anymore.

Haven't been able to find out the reason yet.

**Comment by tteck** [comment]
Hopefully someone will chime in here and offer help. I don't use or know much about Wireguard.
Maybe `/etc/pivpn/wireguard/setupVars.conf` is getting overwritten?

**Comment by almostserious** [comment]
I just tried playing around with it again to find a clear way to reproduce it. I am unable to reproduce it again. Updating or reinstalling pivpn keeps connectivity going. So Im closing this again. Sorry.
