### ISSUE TITLE
Podman instalation - Error installing HACS

### ISSUE THREAD

**Issue by xppx99** [tteck/Proxmox#2161]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Brand new "Podman Home Assistant Container LXC" installation with success. 

Trying to install HACS, by running the command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/podman-homeassistant.sh)"` inside the container, returns the following error: 
`[ERROR] in line 92: exit code 1: while executing command bash <(curl -fsSL https://get.hacs.xyz) &> /dev/null`

The installation of FileBrowser by same method worked fine. 

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. Fresh "Podman Home Assistant Container LXC" installation
2. Running the command bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/podman-homeassistant.sh)"
3. Selection Install HACS
4. Returns error mentioned.

**Comment by tteck** [comment]
ERROR: HACS will currently not work on 2023.12 versions of Home Assistant, latest known working version is 2023.11.3

**Comment by tteck** [comment]
https://github.com/hacs/integration/issues/3384#issuecomment-1843752886

**Comment by tteck** [comment]
To clean up lingering files.
```
rm /var/lib/containers/storage/volumes/hass_config/_data/custom_components/hacs.zi*
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by xppx99** [comment]
Thanks! 

PS: You are very quick, thank you for your work.
