### ISSUE TITLE
ERRO[0000] [graphdriver] prior storage driver overlay failed: 'overlay' is not supported over zfs, a mount_program is required

### ISSUE THREAD

**Issue by DieterTHeck** [tteck/Proxmox#2167]
Tail of error message for "Podman Home Assistant Container LXC"...
>> Not mentioned on WebSite, that ZFS based is not working?

 ✓ Installed Podman
+ msg_info 'Pulling Home Assistant Image'
+ local 'msg=Pulling Home Assistant Image'
+ echo -ne ' - \033[33mPulling Home Assistant Image...'
 - Pulling Home Assistant Image...+ podman pull docker.io/homeassistant/home-assistant:stable
ERRO[0000] [graphdriver] prior storage driver overlay failed: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver 
Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
++ error_handler 28 '$STD podman pull docker.io/homeassistant/home-assistant:stable'
++ local exit_code=125
++ local line_number=28
++ local 'command=$STD podman pull docker.io/homeassistant/home-assistant:stable'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m28\033[m: exit code \033[01;31m125\033[m: while executing command \033[33m$STD podman pull docker.io/homeassistant/home-assistant:stable\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m28\033[m: exit code \033[01;31m125\033[m: while executing command \033[33m$STD podman pull docker.io/homeassistant/home-assistant:stable\033[m'

[ERROR] in line 28: exit code 125: while executing command $STD podman pull docker.io/homeassistant/home-assistant:stable

**Comment by tteck** [comment]
> Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver

Yes, I'm aware of this issue with ZFS. https://github.com/containers/podman/issues/20324
Regrettably, the problem doesn't stem from the script; rather, it is a Podman issue.

**Comment by DieterTHeck** [comment]
Moved on to Docker Script. Testing now.
I guess you can close this for now. Maybe add a comment *Not working on ZFS* to webpage?

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
