### ISSUE TITLE
DNS challenge missing on certbot for "--dns-infomaniak-credentials"

### ISSUE THREAD

**Issue by pandamasta** [tteck/Proxmox#2169]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

 I consume infomaniak dns challanger plugin but it crash as certbot doesn't have the plugin dns-infomaniak-credentials

```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-3" --agree-tos --email "xxx" --domains "xxxxx" --authenticator dns-infomaniak --dns-infomaniak-credentials "/etc/letsencrypt/credentials/credentials-3"
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-infomaniak-credentials /etc/letsencrypt/credentials/credentials-3

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

I don't know if it's related to your build, I have also open a case at nginx reverse proxy project
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2709

Thanks :)

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Use arg certbot --dns-infomaniak-credentials

**Comment by pandamasta** [comment]
Fixed by installing

pip install certbot-dns-infomaniak

**Comment by tteck** [comment]
🚨 Since there are hundreds of Certbot instances, it's necessary to install the specific Certbot of your preference.

It's in the instructions
