### ISSUE TITLE
Error message when updating Emby

### ISSUE THREAD

**Issue by kayanhr-ahadidi** [tteck/Proxmox#2172]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I **_update_** Emby, I receive an error message:

### Which Linux distribution are you employing?

Ubuntu 20.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

``` bash
[ERROR] in line 62: exit code 1: while executing command dpkg -i emby-server-deb_${LATEST}_amd64.deb &> /dev/null
```

### Please provide detailed steps to reproduce the issue.

Per the instruction of installing the CT on Proxmox, I paste the script below inside the shell of my Emby CT:
``` bash
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/emby.sh)"
```

Btw, I tried to add `-vvv` and `--verbose` at the end of the command but it didn't enable the verbose flag, is this because it's updating and not installing? If such a flag exists, please let me know so I can give a more complete description of the problem.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    ______          __         
   / ____/___ ___  / /_  __  __
  / __/ / __  __ \/ __ \/ / / /
 / /___/ / / / / / /_/ / /_/ / 
/_____/_/ /_/ /_/_.___/\__, /  
                      /____/   
 ✓ Stopped Emby
 ✓ Updated Emby
 ✓ Started Emby
 ✓ Updated Successfully
root@emby:~# 
```
You can use the `set -x` option for verbose
```
bash -c " set -x; $(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/emby.sh)"
```

**Comment by tteck** [comment]
Looks like `curl -sL https://api.github.com/repos/MediaBrowser/Emby.Releases/releases/latest | grep '"tag_name":' | cut -d'"' -f4` is not reachable.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
