### ISSUE TITLE
Homarr installation fails

### ISSUE THREAD

**Issue by OberfragGER** [tteck/Proxmox#2177]
I tried a lot of things, bt Homarr installations failed with Debian12.

`yarn run v1.22.21
$ NEXTAUTH_SECRET=WILL_BE_OVERWRITTEN next build
- info Loaded env from /opt/homarr/.env
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

- info Linting and checking validity of types ...- error ESLint: ESLint configuration in package.json is invalid:       - Unexpected top-level property "ignoreDuringBuilds". 
- info Linting and checking validity of types .Failed to compile.

./src/components/Manage/User/Invite/create-invite.modal.tsx:41:8
Type error: Property 'placeholder' is missing in type '{ value: any; onChange: any; checked?: any; error?: any; onFocus?: any; onBlur?: any; popoverProps: { withinPortal: true; }; minDate: Date; maxDate: Date; withAsterisk: true; valueFormat: string; label: DefaultTFuncReturn; variant: "filled"; }' but required in type 'Pick<DateTimePickerProps, "error" | "name" | "date" | "description" | "left" | "right" | "value" | "defaultValue" | "key" | "firstDayOfWeek" | "id" | "children" | ... 383 more ... | "submitButtonProps">'.

  39 |       <Text>{t('modals.create.description')}</Text>
  40 | 
> 41 |       <DateTimePicker
     |        ^
  42 |         popoverProps={{ withinPortal: true }}
  43 |         minDate={minDate}
  44 |         maxDate={maxDate}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
++ error_handler 47 '$STD yarn build'
++ local exit_code=1
++ local line_number=47
++ local 'command=$STD yarn build'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m47\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn build\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m47\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD yarn build\033[m'

[ERROR] in line 47: exit code 1: while executing command $STD yarn build
++ [[ 47 -eq 24 ]]
+ exit`

**Comment by OberfragGER** [comment]
looks linke the same problem
https://github.com/tteck/Proxmox/issues/1774

**Comment by OberfragGER** [comment]
Without verbose it looks like this:

`Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 114
Using Hostname: homarr
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Homarr LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 114 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1xxxxxxxxxxxxxxxxxxxxxxxxxxxx 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 - Installing Homarr (Patience)...
[ERROR] in line 24: exit code 1: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

root@proxmox:~# `

**Comment by tteck** [comment]
Removed from website. Use Docker.

**Comment by tteck** [comment]
```
yarn build
yarn run v1.22.21
$ NEXTAUTH_SECRET=WILL_BE_OVERWRITTEN next build
- info Loaded env from /opt/homarr/.env
- info Linting and checking validity of types ..- error ESLint: ESLint configuration in package.json is invalid:        - Unexpected top-level property "ignoreDuringBuilds". 
- info Linting and checking validity of types .Failed to compile.

./src/components/Manage/User/Invite/create-invite.modal.tsx:41:8
Type error: Property 'placeholder' is missing in type '{ value: any; onChange: any; checked?: any; error?: any; onFocus?: any; onBlur?: any; popoverProps: { withinPortal: true; }; minDate: Date; maxDate: Date; withAsterisk: true; valueFormat: string; label: DefaultTFuncReturn; variant: "filled"; }' but required in type 'Pick<DateTimePickerProps, "error" | "name" | "date" | "description" | "left" | "right" | "value" | "defaultValue" | "key" | "firstDayOfWeek" | "id" | "children" | ... 383 more ... | "submitButtonProps">'.

  39 |       <Text>{t('modals.create.description')}</Text>
  40 | 
> 41 |       <DateTimePicker
     |        ^
  42 |         popoverProps={{ withinPortal: true }}
  43 |         minDate={minDate}
  44 |         maxDate={maxDate}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
