### ISSUE TITLE
Run script non-interactive

### ISSUE THREAD

**Issue by romanpeters** [tteck/Proxmox#2179]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I'm trying to run the PVE post install script from an Ansible playbook.
Is there a way to make it run without needing user-input using the default values?

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
