### ISSUE TITLE
How to change Bootdisk size for Home Assistant OS VM?

### ISSUE THREAD

**Issue by jonalbr** [tteck/Proxmox#218]
Hi @tteck,
I like your script for Home Assistant OS VM. However, I'd like to change the size of the (virtual) hard disk to 16Gb instead of 32 Gb. I tried to fork your script and changed row 328 to `  -scsi0 ${DISK1_REF},size=16G >/dev/null`. However, after using the changed script, still a 32Gb drive was created. Do you know what my mistake here is?
 
I used the following command: `bash -c "$(wget -qLO - https://raw.githubusercontent.com/jonas240/Proxmox/main/vm/haos-vm-v3.sh)"`

Thank you for your help!
Jonas

**Comment by tteck** [comment]
We used to be able to do that, but the Home Assistant Image now sets that to 32gb, no way around it.That's the reason no option for disk size is available in the script.

**Comment by jonalbr** [comment]
Oh ok; This might be the reason why this method: https://github.com/whiskerz007/proxmox_hassos_install didn't work for me as it created a 6 Gb drive. Thanks for your quick reply!

**Comment by tteck** [comment]
That script now downloads the wrong image (haos_generic-aarch64-8.0.rc4.vmdk).
