### ISSUE TITLE
[NgnixProxyManager] Getting a certbot error, certbot reinstall needed

### ISSUE THREAD

**Issue by tompointexe** [tteck/Proxmox#2182]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing a NgnixProxyManager, you can get the error "The 'certbot_dns_cloudflare._internal.dns_cloudflare' plugin errored while loading: No module named 'acme.magic_typing'." when requesting a certificate in the NPM logs
To fix, you have to remove everything with "pip3 uninstall certbot certbot-nginx acme" and reinstall certbot using pip "pip install certbot"

This might not be a script issue, but as certbot is installed by the script, i figured ou it might

This post helped me fix the error https://community.letsencrypt.org/t/no-module-named-acme-magic-typing/204030

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
The 'certbot_dns_cloudflare._internal.dns_cloudflare' plugin errored while loading: No module named 'acme.magic_typing'.
```

### Please provide detailed steps to reproduce the issue.

Do a clean install of NPM using the script
try requesting a certificate from NPM
the error should be in ``systemctl status npm``

Thanks a lot for looking into that

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one. 

Please read the instructions on the website!

🚨 Since there are hundreds of Certbot instances, it's necessary to install the specific Certbot of your preference.

**Comment by tteck** [comment]
If you are working with Python 3, it is recommended to use pip3 to ensure that you are installing packages for the correct Python version. Using pip for Python 3 might result in installing packages for Python 2, which is not ideal, especially considering that Python 2 is no longer supported.

**Comment by m1ckyb** [comment]
The issue here is the version of certbot-dns-cloudflare (which is installed by the script) is a really old version

Needs to be updated run `pip3 install certbot-dns-cloudflare -U`

**Comment by spidey-169** [comment]
> The issue here is the version of certbot-dns-cloudflare (which is installed by the script) is a really old version
> 
> Needs to be updated run `pip3 install certbot-dns-cloudflare -U`

This fixed the issue for me too. Thanks

**Comment by BarronK47** [comment]
> The issue here is the version of certbot-dns-cloudflare (which is installed by the script) is a really old version
> 
> Needs to be updated run `pip3 install certbot-dns-cloudflare -U`

Running this command didn't work at first.  Restarting the LXC afterward got it all working.
