### ISSUE TITLE
motionEye not working correct, when you change the motioneye.conf to something with /mnt/

### ISSUE THREAD

**Issue by OberfragGER** [tteck/Proxmox#2185]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I installed motionEye ether the script and also manually. It worked so far, but you couldnt mount and other device. When you set in the /etc/motioneye/motioneye.conf something with /mnt/ the server will not start. Even when you dont activate smb. Also when you set the folder in the media-section of that file to /mnt/...
So i found today the official installation instructions from the dev-tree. Its working fine now.

I installed motioneye with this instructions. https://github.com/motioneye-project/motioneye/tree/dev#installation

Also there is a new motion version 4.6. Its working flawless.

But anyway, thanks for everything. I just found the bug.

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Installed via your script or installed manually like your script

When you set in the /etc/motioneye/motioneye.conf something with /mnt/ the server will not start. Even when you dont activate smb. Also when you set the folder in the media-section of that file to /mnt/...

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
