### ISSUE TITLE
Monitor All high periodic CPU level

### ISSUE THREAD

**Issue by jsapede** [tteck/Proxmox#2186]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

after launching monitor all script got high cpu peaks every 5 minutes (~35-40% cpu load Vs 10% usually)
cease with script uninstalled

### Which Linux distribution are you employing?

proxmox 7.4

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/66303110/aad4f60d-5245-4b4a-9e8a-d3f623597978)

### Please provide detailed steps to reproduce the issue.

install monitor all script

**Comment by tteck** [comment]
Every 5 minutes is when it checks each instance to see if it's running. Depending on your machine's specs, this _could_ be normal.

As this issue is unrelated to the script, it is considered closed.
