### ISSUE TITLE
Update Omanda 

### ISSUE THREAD

**Issue by pedrware** [tteck/Proxmox#219]
Hello. Can you update Omanda to the latest version Please.
I think it's 5.3.1

**Comment by tteck** [comment]
It's still showing 5.1.7 as latest at https://www.tp-link.com/us/support/download/omada-software-controller/

**Comment by pedrware** [comment]
I just installed it asked to install: omada_v5.3.1_linux_x64

**Comment by tteck** [comment]
When the official mentioned site above posts a link, I'll update the script

**Comment by pedrware** [comment]
Thanks

**Comment by elRadix** [comment]
here is the latest version

https://community.tp-link.com/en/business/forum/topic/548752

**Comment by tteck** [comment]
Thanks, Updated
