### ISSUE TITLE
after install homebridge ct update is not possible

### ISSUE THREAD

**Issue by platini76** [tteck/Proxmox#2201]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

when I try to make update this is the result

root@homebridge:~# update
-bash: update: command not found

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
The `update` command was introduced Oct 5 2023, If your LXC was created before that date, use the full update command
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homebridge.sh)"
```
Besides, Homebridge updates via `apt`

**Comment by platini76** [comment]
launched command:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homebridge.sh)"


system say:
 ✓ Updated Successfully

but... when I launch..

root@homebridge:~# update
-bash: update: command not found
root@homebridge:~#

**Comment by platini76** [comment]
how can I set the script to get the command update without a total reinstallation?

**Comment by tteck** [comment]
Execute the command below in the Homebridge LXC console.
```
echo "bash -c \"\$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homebridge.sh)\"" >/usr/bin/update
chmod +x /usr/bin/update
```

**Comment by platini76** [comment]
it goes ok but when I try to give command update:

- Updating Homebridge LXC...
[ERROR] in line 58: exit code 100: while executing command apt-get install -y homebridge &> /dev/null

root@homebridge:~#

**Comment by tteck** [comment]
Does `apt-get update && apt-get upgrade` work?

**Comment by platini76** [comment]
there was a postfix concinfigure.. thanks very mych for your help.
can you please make a script also for install and update spoolman?
