### ISSUE TITLE
Not able to creat the CT - debian version issuse

### ISSUE THREAD

**Issue by infostand9** [tteck/Proxmox#2202]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

all the scripts( i tried 5)  ended with this message " - Creating LXC Container...unable to create CT 116 - unsupported debian version '12.2'
bash: line 163: exit: A problem occured while trying to create container.: numeric argument required"
i am running proxmox 7.3.3

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Untitled](https://github.com/tteck/Proxmox/assets/154042077/2d1bab6d-d7da-460c-89ce-8bf3b021de1a)

**Comment by tteck** [comment]
Either upgrade to Proxmox 8 or use Advanced settings and use Debian 11. There was a warning that you ignored, 
> Proxmox VE 7 Detected You are currently using Proxmox VE 7, refrain from creating Debian 12 LXCs

BTW, 7.3.3  is not the latest 7 series version (7.4-16)
