### ISSUE TITLE
Homepage LXC uses old git repo "which is significantly behind the current one"

### ISSUE THREAD

**Issue by tonizombie** [tteck/Proxmox#2203]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The current script uses https://github.com/benphelps/homepage.git to build the program instead of the new and up to date https://github.com/gethomepage/homepage.git

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

https://github.com/gethomepage/homepage/discussions/2138

As side note since it builds from source the version is shown as "dev" with the date the lxc was created/updated so current version is hard to tell.

**Comment by tteck** [comment]
Fixed https://github.com/tteck/Proxmox/commit/144c067c6f3e4298b73c017103912563c0c08f3c
