### ISSUE TITLE
SABnzbd LXC - 

### ISSUE THREAD

**Issue by Vetsus** [tteck/Proxmox#2204]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

[ERROR] in line 24: exit code 1: while executing command $STD dpkg -i unrar*.deb
++ [[ 24 -eq 24 ]]
++ echo -e 'The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.\n'
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![SABnzbd LXC - Error](https://github.com/tteck/Proxmox/assets/25618238/0ceb618a-8540-4326-8d2d-08680e962c24)

### Please provide detailed steps to reproduce the issue.

i just ran the code as usual per usage of other LXC containers, but ran advanced setting to set a static ip address for the container.... nothing else was updated other than setting a static ip with my current gateway ip.  i did try the Ubuntu 23.04 linux distro as well with the same error result.... for the most part i'm just running these for all the 'arr' apps as well as qbittorrent and everything else worked fine.. just wanted to setup the usenet service as this keeps failing.  the lxc is created but the interface will not load.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
   _____ ___    ____              __        __
  / ___//   |  / __ )____  ____  / /_  ____/ /
  \__ \/ /| | / __  / __ \/_  / / __ \/ __  / 
 ___/ / ___ |/ /_/ / / / / / /_/ /_/ / /_/ /  
/____/_/  |_/_____/_/ /_/ /___/_.___/\__,_/   
                                              
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 100
Using Hostname: sabnzbd
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.5/24
Using Gateway IP Address: 192.168.86.1
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a SABnzbd LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 100 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.5 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Updated Python3
 ✓ Installed SABnzbd
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

SABnzbd should be reachable by going to the following URL.
         http://192.168.86.5:7777 
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by Vetsus** [comment]
you'd be correct i suppose.  i tried more times with multiple options.. same results... however i finally got it to run once i chose the 'local' drive for installation rather than my ZFS drive.... not sure why that happened, has plenty of space and all the others are installed there but regardless... it's in now.  thanks for the scripts btw!

**Comment by pythongod** [comment]
cat <<EOF >/etc/apt/sources.list.d/non-free.list
deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
EOF

This is also done on the ubuntu install and did cause the script to exit
