### ISSUE TITLE
Unmanic fixes for Intel HW encoding/decoding

### ISSUE THREAD

**Issue by timdonovanuk** [tteck/Proxmox#2209]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Chances are if you're using Unmanic and you're using Intel (nucs), you'll want to take advantage of HW encoding/decoding. Your Plex script already takes this into account and sorts dev/dri/renderD128 access.

I have found for Unmanic to work properly to encode files to h265 you need to:

Add the following to the lxc conf:

```
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
```

This is enough for Plex to do hardware encoding, but for some reason whatever ffmpeg parameters that Unmanic uses, this isn't enough. You also need to...

- add the non-free sources to debian repos, e.g. change /etc/apt/sources/list to:
![image](https://github.com/tteck/Proxmox/assets/8156439/dbe3ba36-7c13-4756-a35e-ab3a76904b26)

- Install the intel drivers: `apt install intel-media-va-driver-non-free`

- Otherwise you get a bunch of weird ffmpeg errors (e.g. [hevc_qsv @ 0x55759e86ccc0] Low power mode is unsupported) and end up going down a very deep google rabbit hole.

Hope this helps someone. 

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
You could utilize 
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/hw-acceleration.sh)"
```
If you need non-free
```
wget -q https://ftp.debian.org/debian/pool/non-free/i/intel-media-driver-non-free/intel-media-va-driver-non-free_23.4.2+ds1-1_amd64.deb
dpkg -i intel-media-va-driver-non-free_23.4.2+ds1-1_amd64.deb
```

**Comment by timdonovanuk** [comment]
It's not a suggestions, questions or feature/script requests - HW encoding doesn't work and the render is missing in the lxc config ;)

Cool, thanks for these. I don't see hw acceleration in the list on the homepage, but possibly overlooking it. Doesn't appear searching "acceleration" either though.

**Comment by tteck** [comment]
There are many "hidden" scripts not on the website, but discussed in the Discussions section.
Usually in "misc"

**Comment by tteck** [comment]
Also, I'd consider adding  HW encoding to Unmanic a feature request. 🤷🏻‍♂️

**Comment by timdonovanuk** [comment]
My apologies then. The Plex script comes with everything needed to support HW encoding, so it follows that an app specifically for encoding would also include this. Hence me feeling it's not really a feature request. I even provided a fix.

Your suggestion to manually install the drivers does not work:

```
root@lxc-unmanic2:/transcode# dpkg -i intel-media-va-driver-non-free_23.4.2+ds1-1_amd64.deb
Selecting previously unselected package intel-media-va-driver-non-free:amd64.
dpkg: regarding intel-media-va-driver-non-free_23.4.2+ds1-1_amd64.deb containing intel-media-va-driver-non-free:amd64:
 intel-media-va-driver-non-free conflicts with intel-media-va-driver
  intel-media-va-driver:amd64 (version 23.1.1+dfsg1-1) is present and installed.

dpkg: error processing archive intel-media-va-driver-non-free_23.4.2+ds1-1_amd64.deb (--install):
 conflicting packages - not installing intel-media-va-driver-non-free:amd64
Errors were encountered while processing:
 intel-media-va-driver-non-free_23.4.2+ds1-1_amd64.deb
```

My fix/suggestion to change /etc/apt/sources/list is probably preferable to keep them up to date via apt, rather than manually installing, no?

Thank you for the hidden script - it does not seem to allow updating unprivileged containers. The default in the unmanic script is unprivileged.  

Running it for a privileged container worked, but then it seems to have broken hw encoding on my other (unprivileged) containers. It's like the script stole device access away from other containers. 

`No device available for decoder: device type qsv needed for codec hevc_qsv.`

**Comment by tteck** [comment]
Repository 'Debian bookworm' changed its 'non-free component' value from `non-free` to `non-free non-free-firmware`

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/c2a3eb52caa871f3cc0a66c2a7f3065474bb3e69
