### ISSUE TITLE
Latest Photoprism script fails building PhotoPrism "ERROR 2@126?"

### ISSUE THREAD

**Issue by 2600box** [tteck/Proxmox#221]
The latest script fails. I tried twice with the same result. What does ERROR 2@126 mean?

```
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.0.0.95
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 - Building PhotoPrism...‼ ERROR 2@126 Unknown failure occured.
```

Previous versions of the script installed without error.

**Comment by tteck** [comment]
Typically, errors while building is CPU/RAM related. Throw more cores and ram at it. I use 4 cores while building.

**Comment by 2600box** [comment]
Until now I have only used 4cores and 4096MB ram and privileged container which has worked for the previous versions of the script I tested these past few days. 

With this current version I have now tested the defaults (2cores and 2048MB ram) and 6cores with 8192MB ram. Privileged and Unprivileged. Same result. 

I have about 10GB of ram free according to proxmox. and I have a 6core cpu... (Intel® Core™ i5-8400 Processor)

So I don't think that is it...

**Comment by tteck** [comment]
Just ran the script...
```
  _____  _           _        _____      _               
 |  __ \| |         | |      |  __ \    (_)              
 | |__) | |__   ___ | |_ ___ | |__) | __ _ ___ _ __ ___  
 |  ___/|  _ \ / _ \| __/ _ \|  ___/  __| / __|  _   _ \ 
 | |    | | | | (_) | || (_) | |   | |  | \__ \ | | | | |
 |_| v3 |_| |_|\___/ \__\___/|_|   |_|  |_|___/_| |_| |_|

Using Advanced Settings
Using CT Type Unprivileged
Using CT Password Automatic Login
Using CT ID 111
Using CT Name photoprism
Using Disk Size 8GB
Using 4vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address dhcp
Using Gateway IP Address NONE
Using VLAN Tag NONE
Are these settings correct(y/n)? y
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.69 
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 ✓ Built PhotoPrism
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

PhotoPrism should be reachable by going to the following URL.
      http://192.168.86.69:2342 
```
I did make a change to limit Node's memory usage to 2048

**Comment by 2600box** [comment]
I tried your same settings and it failed. 

Are you running intel?

I am using ZFS for boot and storage array - but it worked fine for previous versions of the script...


Is there no way to log the output from the build script?

```

  _____  _           _        _____      _
 |  __ \| |         | |      |  __ \    (_)
 | |__) | |__   ___ | |_ ___ | |__) | __ _ ___ _ __ ___
 |  ___/|  _ \ / _ \| __/ _ \|  ___/  __| / __|  _   _ \
 | |    | | | | (_) | || (_) | |   | |  | \__ \ | | | | |
 |_| v3 |_| |_|\___/ \__\___/|_|   |_|  |_|___/_| |_| |_|

Using Advanced Settings
Using CT Type Unprivileged
Using CT Password Automatic Login
Using CT ID 120
Using CT Name photoprism
Using Disk Size 8GB
Using 4vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address dhcp
Using Gateway IP Address NONE
Using VLAN Tag NONE
Are these settings correct(y/n)? y
 ✓ Using local for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 120 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.0.0.102
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 - Building PhotoPrism...‼ ERROR 2@126 Unknown failure occured.
```

**Comment by 2600box** [comment]
To be clear, I am running this command on my proxmox terminal: 

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/photoprism-v3.sh)" `

**Comment by aurelpec** [comment]
I had the same problem on I5-8500t

It was caused by : AVX variables containing multiple lines
```
root@photoprism:~# grep -o -m1 'avx[^ ]*' /proc/cpuinfo
avx
avx2
```

So tensorflow was not installed, and photoprism build failed.

**Comment by tteck** [comment]
Should I just set it to use the CPU only Tensorflow?

**Comment by tteck** [comment]
@2600box Try
```
now in main
```
I put in an option "Check For Advanced Vector Extensions?"
If you answer y it will use the output from `grep -o -m1 'avx[^ ]*' /proc/cpuinfo`
If you answer n it will use CPU version of tensorflow (which is what i reverted to here https://github.com/tteck/Proxmox/commit/34ea1a170c21a9c7021c534cece04e89c9bf0b77)

**Comment by 2600box** [comment]
> Should I just set it to use the CPU only Tensorflow?

Worth a try - to eliminate the variables. Though I do intend to use GPU tensor flow.

I have only intel igpu in proxmox system.

I use a privileged lxc container for plex and the igpu provides accelerated transcoding.

**Comment by 2600box** [comment]
Running `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/avx/ct/photoprism-v3.sh)"` I was not prompted for "Check For Advanced Vector Extensions?"

If I run the check manually in the container this is the result:
```
root@photoprism:~# grep -o -m1 'avx[^ ]*' /proc/cpuinfo
avx
avx2
```

**Comment by tteck** [comment]
Then answer n

**Comment by tteck** [comment]
```
  _____  _           _        _____      _               
 |  __ \| |         | |      |  __ \    (_)              
 | |__) | |__   ___ | |_ ___ | |__) | __ _ ___ _ __ ___  
 |  ___/|  _ \ / _ \| __/ _ \|  ___/  __| / __|  _   _ \ 
 | |    | | | | (_) | || (_) | |   | |  | \__ \ | | | | |
 |_| v3 |_| |_|\___/ \__\___/|_|   |_|  |_|___/_| |_| |_|

Using Advanced Settings
Using CT Type Unprivileged
Using CT Password Automatic Login
Using CT ID 111
Using CT Name photoprism
Using Disk Size 8GB
Using 4vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address dhcp
Using Gateway IP Address NONE
Using VLAN Tag NONE
Are these settings correct(y/n)? y
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.32 
 ✓ Internet Online
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
Check For Advanced Vector Extensions? y
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 - Building PhotoPrism...
 ```

**Comment by 2600box** [comment]
Ok, I ran it again and the prompt came up. Selecting `n` worked and it finished. Thanks!

Is it not possible to have GPU support?

**Comment by tteck** [comment]
gotta figure out the how to deal with the double line answer from `grep -o -m1 'avx[^ ]*' /proc/cpuinfo`

**Comment by 2600box** [comment]
> gotta figure out the how to deal with the double line answer from `grep -o -m1 'avx[^ ]*' /proc/cpuinfo`

Cool. Thanks for working on this, I think it is really worthwhile.

Going back to the original issue of Exiftool/Json not working, it seems it is not resolved after all...

See my further comment on the closed issue here: https://github.com/tteck/Proxmox/issues/217#issuecomment-1120233649_

**Comment by tteck** [comment]
More changes made

**Comment by aurelpec** [comment]
I created pull request https://github.com/tteck/Proxmox/pull/226 to check avx capabilities automatically and swith to cpu if not found.

**Comment by tteck** [comment]
Which did it find for your I5-8500t, AVX or AVX2?

**Comment by aurelpec** [comment]
avx2

**Comment by tteck** [comment]
single line?

**Comment by aurelpec** [comment]
No double lines. But the first if match, so it installed tensorflow with avx2 support.
