### ISSUE TITLE
New Service wanted

### ISSUE THREAD

**Issue by Skyscraper76** [tteck/Proxmox#2212]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After pve 8x use gotify for notifications, I think it make sense to have a ready to use lxc with gotify server.
https://gotify.net/docs/install
Can you create this for us?

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
