### ISSUE TITLE
AdGuard won't update

### ISSUE THREAD

**Issue by quantummobile** [tteck/Proxmox#2213]
Hello,

I get this error while running update in CLI in AdGuard LCX:

[ERROR] in line 57: exit code 3: while executing command wget -qL https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz

**Comment by OddSquirrel** [comment]
Hi @quantummobile! Did you try updating from within AdGuard Home? That's what usually works for me.

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to the script. For other inquires please share them in the Discussions section. **_Blank issues will be closed immediately._**
