### ISSUE TITLE
Alpine (docker): No bash -> how to update LXC using script?

### ISSUE THREAD

**Issue by HerzogVonWiesel** [tteck/Proxmox#2215]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running
`bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-docker.sh)"`
inside of the LXC console, I get the error that bash is not installed. How would I go about using the script to update the image? On top of that, it seems docker isn't actually installed, since I can't run `docker compose up -d` in the lxc, since docker doesn't seem to be installed.

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Run
`bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-docker.sh)"`
in the pve console, then the same command in the newly created LXC. Try to run `docker compose up -d` in the console as well

**Comment by tteck** [comment]
Sounds like the script didn't finish successfully. It is crucial not to exit the Proxmox shell while running scripts. Leaving the shell during script execution will result in the script being interrupted. 

The script insatlls `bash`
https://github.com/tteck/Proxmox/blob/ab36af75af826ad7862d147578bc056997b2cd09/misc/build.func#L544

The script gives the option to install Docker Compose.
https://github.com/tteck/Proxmox/blob/ab36af75af826ad7862d147578bc056997b2cd09/install/alpine-docker-install.sh#L51

As these issues are unrelated to the script, it is considered closed.

**Comment by HerzogVonWiesel** [comment]
> Sounds like the script didn't finish successfully. It is crucial not to exit the Proxmox shell while running scripts. Leaving the shell during script execution will result in the script being interrupted.
> 
> The script insatlls `bash`
> 
> https://github.com/tteck/Proxmox/blob/ab36af75af826ad7862d147578bc056997b2cd09/misc/build.func#L544
> 
> The script gives the option to install Docker Compose.
> 
> https://github.com/tteck/Proxmox/blob/ab36af75af826ad7862d147578bc056997b2cd09/install/alpine-docker-install.sh#L51
> 
> As these issues are unrelated to the script, it is considered closed.

Though you linked the alpine-docker-install.sh, which is different from the one listed here https://tteck.github.io/Proxmox/, which is the alpine-docker.sh right? Should we use that one instead?

Oh nevermind, I see that it somehow references that script, where does that happen though just out of interest as it works now? Thank you so much for your work and help!

**Comment by tteck** [comment]
Use the command listed on the website.  You may find that reading ["Exploring the Scripts and Steps Involved in an Application LXC Installation"](https://github.com/tteck/Proxmox/blob/main/CODE-AUDIT.md) will help in understanding how the process works.
