### ISSUE TITLE
Building Frontend Failed

### ISSUE THREAD

**Issue by aMugabi** [tteck/Proxmox#2217]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The script runs but failed on Building the front end

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 103
Using Hostname: nginxproxymanager
Using Disk Size: 4GB
Allocated Cores 1
Allocated Ram 1024
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Nginx Proxy Manager LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 103 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.10.8.203 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python Dependencies
 ✓ Installed Openresty
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Downloaded Nginx Proxy Manager v2.10.4
 ✓ Set up Enviroment
 - Building Frontend...
[ERROR] in line 24: exit code 128: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

### Please provide detailed steps to reproduce the issue.

I followed the script from here: https://tteck.github.io/Proxmox/

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"

**Comment by tteck** [comment]
> - When encountering the error message [ERROR] in line 24: exit code *: while executing command "$@" > /dev/null 2>&1, make sure to run the script in verbose mode to accurately determine the underlying issue. 

Try allocating more resources (2vCPU & 2048 RAM) by utilizing the Advanced settings.

**Comment by ekorn** [comment]
Changing the Settings worked for me but it took me a while to find this closed Ticket.
