### ISSUE TITLE
OpenMediaVault LXC - continual Crash

### ISSUE THREAD

**Issue by bearhntr** [tteck/Proxmox#2218]
I stood up a 2nd PVE box on my old Optiplex 7010 with Core i7-3770 CPU (I used to use this as my Domain Controller running 2016).  With the help of TTeck's other scripts and some research I stood up another PVE server and have the DC over there with Server 2019.  

This 7010 box has a 5.25" bay with 6 x 2.5" HDDs that I was using as NAS-like storage on the DC.  I would like to utilize this box with PVE as a NAS (and maybe a couple other VMs as it only has 16GB RAM). 

The TTECK script ran without any hitches (I used the advanced option and chose all defaults except the VMID - I wanted to set this myself) and it started just fine.  I was able to get to the OMV Dashboard, and these questions arose:

1)  Is the QEMU Guest Agent on here?  How can it be installed as this is a container and I do not see it here...nor can I Edit these settings:

![image](https://github.com/tteck/Proxmox/assets/100164602/ba71f45a-bc7f-4c0f-af76-f97393daaaa1)

2)  The Time on OMV is wrong, and I have my pfSense set to handle NTP requests - it is working everywhere (either by name or or IP).  I try and set this in OVM and it will not accept when I hit APPLY.  I get the Green Box at the bottom when I enter it - but APPLY gives a big red box error:

![image](https://github.com/tteck/Proxmox/assets/100164602/0f26fc57-c5de-4465-a907-3773dacb27f6)

3)  If I do nothing in OMV for about 15-20 mins (it must be crashing in the background some place) as I go to refresh the web page and it is gone - with the following error at the top.  If I open PVE GUI - the Container is not running:

![image](https://github.com/tteck/Proxmox/assets/100164602/75b07653-ed77-49b3-8c26-6b0c271cd51f)

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to the script. For other inquires please share them in the Discussions section. **_Blank issues will be closed immediately._**

> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
QEMU Guest Agent is for virtual machines, not Linux containers
