### ISSUE TITLE
Nextcloud LXC

### ISSUE THREAD

**Issue by ThetomekK** [tteck/Proxmox#2219]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

nginx service does not start

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mAdded Additional Nextcloud Packages\033[m'
 ✓ Added Additional Nextcloud Packages
+ msg_info 'Starting Services'
+ local 'msg=Starting Services'
+ echo -ne ' - \033[33mStarting Services...'
 - Starting Services...+ rc-service redis start
 * Caching service dependencies ...                                                              [ ok ]
 * /run/redis: creating directory
 * /run/redis: correcting owner
 * Starting Redis server ...                                                                     [ ok ]
+ rc-update add redis default
 * service redis added to runlevel default
+ rc-service php-fpm82 start
 * Checking /etc/php82/php-fpm.conf ...
 * /run/php-fpm82: creating directory
 * Starting PHP FastCGI Process Manager ...                                                      [ ok ]
+ chown -R nextcloud:www-data /var/log/nextcloud/
+ rc-service php-fpm82 restart
 * Stopping PHP FastCGI Process Manager ...                                                      [ ok ]
 * Checking /etc/php82/php-fpm.conf ...
 * Starting PHP FastCGI Process Manager ...                                                      [ ok ]
+ rc-service nginx start
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: configuration file /etc/nginx/nginx.conf test failed
 * ERROR: nginx failed to start
++ error_handler 167 '$STD rc-service nginx start'
++ local exit_code=1
++ local line_number=167
++ local 'command=$STD rc-service nginx start'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m167\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD rc-service nginx start\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m167\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD rc-service nginx start\033[m\n'

[ERROR] in line 167: exit code 1: while executing command $STD rc-service nginx start`

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-nextcloud.sh)"
with 2048 RAM , rest default

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    _   __          __  ________                ______  _ 
   / | / /__  _  __/ /_/ ____/ /___  __  ______/ / __ \(_)
  /  |/ / _ \| |/_/ __/ /   / / __ \/ / / / __  / /_/ / / 
 / /|  /  __/>  </ /_/ /___/ / /_/ / /_/ / /_/ / ____/ /  
/_/ |_/\___/_/|_|\__/\____/_/\____/\__,_/\__,_/_/   /_/   
                                                          
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 101
Using Hostname: nextcloudpi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a NextCloudPi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 101 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed NextCloudPi
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

NextCloudPi Setup should be reachable by going to the following URL.
         https://192.168.86.253/ 
```

**Comment by tteck** [comment]
Oh, I see now that it was Alpine, checking...

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    _   __          __       __                __   __  __      __
   / | / /__  _  __/ /______/ /___  __  ______/ /  / / / /_  __/ /_
  /  |/ / _ \| |/_/ __/ ___/ / __ \/ / / / __  /  / /_/ / / / / __ \
 / /|  /  __/>  </ /_/ /__/ / /_/ / /_/ / /_/ /  / __  / /_/ / /_/ /
/_/ |_/\___/_/|_|\__/\___/_/\____/\__,_/\__,_/  /_/ /_/\__,_/_.___/
Alpine
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 101
Using Hostname: alpine-nextcloud
Using Disk Size: 2
Allocated Cores: 2
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Nextcloud LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 101 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed PHP/Redis
 ✓ Installed MySQL Database
 ✓ Installed Nextcloud
 ✓ Added Additional Nextcloud Packages
 ✓ Started Services
 ✓ Finished Nextcloud Setup-Wizard
 ✓ Customized Container
 ✓ Completed Successfully!

Alpine-Nextcloud should be reachable by going to the following URL.
         https://192.168.86.253 
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
