### ISSUE TITLE
NocoDB upgrade via "npm run upgrade"?

### ISSUE THREAD

**Issue by 2600box** [tteck/Proxmox#222]
The script installs `84.18` which is a long way behind the latest `90.11`

I ran `npm run upgrade` from `/opt/nocodb` and rebooted the container.

It now reports `90.11`

My question: Is this method of upgrading acceptable? I noticed on https://tteck.github.io/Proxmox/ under NocoDB that you have: 

"⚙️ To Update

Working on"

**Comment by tteck** [comment]
Yes, that is the same as running `npm uninstall --save nocodb && npm install --save nocodb` 
I'll add it to the NocoDB page
