### ISSUE TITLE
Missing permission in Tailscale install

### ISSUE THREAD

**Issue by cwecki** [tteck/Proxmox#2225]
I have executed the helper script for the installation of tailscale in an existing LCX container on a fresh Proxmox system. The execution took place via the shell of the node and was confirmed with the green confirmation message.

I restarted the container and could not start tailscale using "tailscale up".
Also, the TUN device did not exist.

The correct authorizations for the TUN device on the node are missing, as described in https://pve.proxmox.com/wiki/OpenVPN_in_LXC
A 
`chown 100000:100000 /dev/net/tun`
on the node provided a remedy.

Before:
`crw-rw-rw- 1 root root 10, 200 Dec 21 23:16 /dev/net/tun`

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
  ______      _ __                __        
 /_  __/___ _(_) /_____________ _/ /__
  / / / __ `/ / / ___/ ___/ __ `/ / _ \
 / / / /_/ / / (__  ) /__/ /_/ / /  __/
/_/  \__,_/_/_/____/\___/\__,_/_/\___/

This will add Tailscale to an existing LXC Container ONLY. Proceed(y/n)?y
Installing Tailscale...
Installed Tailscale
 ✔ Completed Successfully!
 Reboot 102 LXC to apply the changes, then run tailscale up in the LXC console
```

```
root@debian-12:~# tailscale up

To authenticate, visit:

        https://login.tailscale.com/a/c2c87662b51f
```
![Screenshot 2023-12-22 7 08 47 AM](https://github.com/tteck/Proxmox/assets/21342670/88299fc3-d9b7-48b1-8470-68a97dd16fe1)


![Screenshot 2023-12-22 7 09 32 AM](https://github.com/tteck/Proxmox/assets/21342670/e4a386dc-25ca-4b8f-bd73-e75780b358f7)

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
