### ISSUE TITLE
Why doesn't the LXC cron updater also create a snapshot before?

### ISSUE THREAD

**Issue by thibaultmol** [tteck/Proxmox#2226]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I noticed the Update LXC's cron script doesn't take a snapshot before each update. While an update usually should go fine, maybe it's a good idea to give the user the option if they want to have a snapshot for every update?

(btw: `If the default Linux distribution is not adhered to, script support will be discontinued.` it's not actually clearly stated (in my opinion) in the documentation what the default linux distro for an LXC container should be. I went with Debian but I can't actually see it in any of the help documentation what you recommend)*
* I only see the list of the linux distributions in this issue creation wizard now, but I assume there's another list in the docu's but it's not clear where.

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
What's not clear about this?


![Screenshot 2023-12-22 6 57 50 AM](https://github.com/tteck/Proxmox/assets/21342670/af714051-9211-40b7-9688-4cb8468c6053)

Default settings use the preferred Linux distribution.

**Comment by thibaultmol** [comment]
Ah sorry, didn't know it showed a visual warning during the setup wizard, hadn't used any of the lxc scripts **yet**.

Made a discussion post about it: https://github.com/tteck/Proxmox/discussions/2228
