### ISSUE TITLE
Tailscale installation on LXC Container

### ISSUE THREAD

**Issue by Basti-Fantasti** [tteck/Proxmox#2230]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the tailscale installation script on the Proxmox host, the configuration adjustments to the node.conf file are not done correct, when there are snapshots of the container.

The changes are only attached at the end of the file, which does not work.

![grafik](https://github.com/tteck/Proxmox/assets/1663072/d8e55d13-b019-456e-8ae8-68282d467ac8)

the changes have to be made on top of configuration file.
I made the changes manually, as shown below, then then tailscale worked!

![grafik](https://github.com/tteck/Proxmox/assets/1663072/cf0069e7-1102-4845-a060-1c713ce845f0)

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

- Make an LXC container (Ubuntu / Debian)
- make a snapshot
- run the tailscale script
- see the problem in node.conf file

**Comment by tteck** [comment]
I don't fully understand what you're talking about, if you take a snapshot before installing Tailscale, of course the snapshot will not contain the new LXC (not node)`.conf`  or the Tailscale installation.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by Basti-Fantasti** [comment]
Sorry but the issue is related to the script. 
The script simply inserts the lines at the end of the conf file which does not work.
See your script starting row 54. 

```bash
CTID_CONFIG_PATH=/etc/pve/lxc/${CTID}.conf
cat <<EOF >>$CTID_CONFIG_PATH
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
EOF
```

This just does not work when snapshots are taken from the container at any time before.

Unfortunately, you have already closed the issue without understanding the problem right and without asking further.
So I will continue to manually adjust the configuration files after running the script to make it work if needed.

If someone else is running in the same problem he/she can find the solution here in my first post.
If you decide to fix the bug feel free to contact me, I'm happy to help.

**Comment by tteck** [comment]
What do you mean by  "_when snapshots are taken from the container at any time before_"?

**Comment by tteck** [comment]
There is NO bug to fix. https://github.com/tteck/Proxmox/issues/2225#issuecomment-1867624942

**Comment by tteck** [comment]
> The script simply inserts the lines at the end of the conf file which does not work.

It's designed to do so, and yes it does work.

**Comment by tteck** [comment]
Even your pictures show the same thing 🤷🏻‍♂️ I sense there might be some confusion about the concept of snapshots.

**Comment by tteck** [comment]
> if you take a snapshot before installing Tailscale, of course the snapshot will not contain the new LXC (not node).conf or the Tailscale installation.

Take a snapshot after installing Tailscale, the `.conf` will have everything.

**Comment by Basti-Fantasti** [comment]
1 Setup a new container
2 Take a snapshot
3 run the script

The script will attach the lines in the end of the file which is in the backup section ( please check my first screenshot, it's in the vzdump section not in the main/active part of the configuration

As long as it's a new container which has no snapshots in its history everything works as expected

**Comment by tteck** [comment]
I think that you're still confused 

> 1 Setup a new container
2 Take a snapshot
3 run the script

The script will **not** write the new `.conf` to the already made snapshot.

**Comment by tteck** [comment]
1 Setup a new container
2 Take a snapshot >> This **will not** have Tailscale
3 run the script
4 Take a snapshot >> This **will** have Tailscale

So, if you rollback to **2**, it will equal a fresh container ( before the Tailscale installation)
If you rollback to **4**, it will contain Tailscale

**Comment by Basti-Fantasti** [comment]
1 Setup new container
2 take snapshot of empty container (conf file below, snapshot name **dummy**)

![grafik](https://github.com/tteck/Proxmox/assets/1663072/53420171-3d98-4fd6-bd89-4da072791647)

here's the conf file 

![grafik](https://github.com/tteck/Proxmox/assets/1663072/bd7f9635-b96f-4a7e-81c2-7f3e45575614)

3 run the script

configuration is automatically adjusted

![grafik](https://github.com/tteck/Proxmox/assets/1663072/d57f74cc-2353-4608-b786-bdb2b9fb9e22)

4 reboot the container as suggested

![grafik](https://github.com/tteck/Proxmox/assets/1663072/a6b03e63-015c-4b55-98b2-73457fb5aa4e)


5 login in lxc container and try `tailscale up`

![grafik](https://github.com/tteck/Proxmox/assets/1663072/96e9a50d-51ff-497e-a636-900372fbaa23)

**--> not working**

6 manually adjust conf file as shown below and reboot the container

![grafik](https://github.com/tteck/Proxmox/assets/1663072/1d7282a7-4828-4f33-bb2a-1f63c01dffbc)

7 after logging in again `tailscale up` works

![grafik](https://github.com/tteck/Proxmox/assets/1663072/3279ea61-4630-49bd-a03f-fc4b55b7e82a)


Hopefully you can reproduce these steps with the instruction and screenshots above

I do not jump forth and back in the snapshots. The problem is the pure existence of snapshots in the conf file.
The working set for the configuration is always the top most configuration. Below that are all the snapshots. 
So IMHO the scripts modification have to be before the first subsection / snapshot section in the conf file not automatically appended at the end

**Comment by tteck** [comment]
I see now, why would it add the new lines to the [fresh] snapshot instead of the [tailscale] snapshot?


```
root@pve:~# cat /etc/pve/lxc/100.conf
arch: amd64
cores: 1
features: nesting=1
hostname: testing
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:B8:7A:11,ip=192.168.86.253/24,type=veth
ostype: debian
parent: tailscale
rootfs: local-lvm:vm-100-disk-0,size=2G
swap: 512
unprivileged: 1

[fresh]
arch: amd64
cores: 1
features: nesting=1
hostname: testing
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:B8:7A:11,ip=192.168.86.253/24,type=veth
ostype: debian
rootfs: local-lvm:vm-100-disk-0,size=2G
snaptime: 1703272733
swap: 512
unprivileged: 1
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file

[tailscale]
arch: amd64
cores: 1
features: nesting=1
hostname: testing
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:B8:7A:11,ip=192.168.86.253/24,type=veth
ostype: debian
parent: fresh
rootfs: local-lvm:vm-100-disk-0,size=2G
snaptime: 1703332070
swap: 512
unprivileged: 1
```

**Comment by tteck** [comment]
It even adds the new lines to [fresh] instead of adding the lines to the top most configuration. This seems to be a Proxmox bug.

```
root@pve:~# cat /etc/pve/lxc/101.conf
arch: amd64
cores: 1
hostname: testing-priv
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:68:D3:E4,ip=192.168.86.253/24,type=veth
ostype: debian
parent: fresh
rootfs: local-lvm:vm-101-disk-0,size=2G
swap: 512

[fresh]
arch: amd64
cores: 1
hostname: testing-priv
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:68:D3:E4,ip=192.168.86.253/24,type=veth
ostype: debian
rootfs: local-lvm:vm-101-disk-0,size=2G
snaptime: 1703329744
swap: 512
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
```

**Comment by Basti-Fantasti** [comment]
yes this could be. IMO It's not so good, how proxmox handles the snapshots. It would be good if there was a `[named section]` for the active working set as well as for the backups. In that way it would be easy to add the configuration to the correct section. in the config file . Proxmox always dumps the snapshots to the end at the config file.

**Comment by tteck** [comment]
This is definitely a Proxmox bug. I added HW acceleration and made a snaphot, it added the lines to [tailscale]. 

```
root@pve:~# cat /etc/pve/lxc/101.conf
arch: amd64
cores: 1
hostname: testing-priv
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:68:D3:E4,ip=192.168.86.253/24,type=veth
ostype: debian
parent: hw-accel
rootfs: local-lvm:vm-101-disk-0,size=2G
swap: 512

[fresh]
arch: amd64
cores: 1
hostname: testing-priv
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:68:D3:E4,ip=192.168.86.253/24,type=veth
ostype: debian
rootfs: local-lvm:vm-101-disk-0,size=2G
snaptime: 1703329744
swap: 512
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file

[hw-accel]
arch: amd64
cores: 1
hostname: testing-priv
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:68:D3:E4,ip=192.168.86.253/24,type=veth
ostype: debian
parent: tailscale
rootfs: local-lvm:vm-101-disk-0,size=2G
snaptime: 1703335444
swap: 512

[tailscale]
arch: amd64
cores: 1
hostname: testing-priv
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.86.1,hwaddr=BC:24:11:68:D3:E4,ip=192.168.86.253/24,type=veth
ostype: debian
parent: fresh
rootfs: local-lvm:vm-101-disk-0,size=2G
snaptime: 1703335086
swap: 512
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
```
