### ISSUE TITLE
haos-vm.sh error due to iscsi

### ISSUE THREAD

**Issue by ChrisonSimtian** [tteck/Proxmox#2233]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

hey,
When running the haos-vm script the storage table keeps crashing. I ran your other scripts and they worked fine (although complaining about failing to login to my iscsi storage).

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
Creating a HAOS VM using the above default settings

msg_info "Validating Storage"
 - Validating Storage...while read -r line; do
  TAG=$(echo $line | awk '{print $1}')
  TYPE=$(echo $line | awk '{printf "%-10s", $2}')
  FREE=$(echo $line | numfmt --field 4-6 --from-unit=K --to=iec --format %.2f | awk '{printf( "%9sB", $6)}')
  ITEM="  Type: $TYPE Free: $FREE "
  OFFSET=2
  if [[ $((${#ITEM} + $OFFSET)) -gt ${MSG_MAX_LENGTH:-} ]]; then
    MSG_MAX_LENGTH=$((${#ITEM} + $OFFSET))
  fi
  STORAGE_MENU+=("$TAG" "$ITEM" "OFF")
done < <(pvesm status -content images | awk 'NR>1')
iscsiadm: default: 1 session requested, but 1 already present.
iscsiadm: Could not login to [iface: default, target: iqn.2000-01.com.synology:NAS.Target-1.5f3e40521c1, portal: fe80::211:32ff:fed4:6701,3260].
iscsiadm: initiator reported error (15 - session exists)
iscsiadm: Could not login to [iface: default, target: iqn.2000-01.com.synology:NAS.Target-1.5f3e40521c1, portal: 192.168.10.2,3260].
iscsiadm: initiator reported error (19 - encountered non-retryable iSCSI login failure)
iscsiadm: Could not login to [iface: default, target: iqn.2000-01.com.synology:NAS.Target-1.5f3e40521c1, portal: fe80::211:32ff:fed4:6702,3260].
iscsiadm: initiator reported error (15 - session exists)
iscsiadm: Could not log into all portals
command '/usr/bin/iscsiadm --mode node --targetname iqn.2000-01.com.synology:NAS.Target-1.5f3e40521c1 --login' failed: exit code 15
numfmt: invalid number: ‘[iface:’
error_handler $LINENO "$BASH_COMMAND"

[ERROR] in line 363: exit code 2: while executing command FREE=$(echo $line | numfmt --field 4-6 --from-unit=K --to=iec --format %.2f | awk '{printf( "%9sB", $6)}')
```

### Please provide detailed steps to reproduce the issue.

Run script with default settings

**Comment by ChrisonSimtian** [comment]
As expected, disabling said iscsi storage "fixes" the issue and in my case is a valid workaround.
Anyway would be nice to see this fixed, as the other scripts dont seem to have an issue with that storage :-)

**Comment by tteck** [comment]
I'm unsure how to resolve an iSCSI-based storage login error.

**Comment by ChrisonSimtian** [comment]
> I'm unsure how to resolve an iSCSI-based storage login error.

hey, I dont think you need to fix the login error. When I ran your other scripts the error popped up but the storage table worked fine. But with the haos one it crashes ... so whatever the difference is I think the way you handle the storage selection in your other scripts seems to be more robust than in this one :-)

**Comment by tteck** [comment]
The VM is actually importing a `.qcow2` image, totally different from creating an LXC.

**Comment by tteck** [comment]
I strive to develop scripts that are compatible with a wide range of storage pools. However, it appears that not all storage pools are accessible. 
Since this issue is associated with storage preferences beyond the scope of the script, it is considered closed.
