### ISSUE TITLE
Alpine Vaultwarden LXC does not update.

### ISSUE THREAD

**Issue by mguedes71** [tteck/Proxmox#2236]
### Discussed in https://github.com/tteck/Proxmox/discussions/2235

<div type='discussions-op-text'>

<sup>Originally posted by **mguedes71** December 23, 2023</sup>
Alpine Vaultwarden LXC does not update. Despite having an indication that it has updates (Web and Server), it does not update when I use the script indicated for this purpose (bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ ct/alpine-vaultwarden.sh)"). Any help?

![image](https://github.com/tteck/Proxmox/assets/34092794/939f2bb9-0d1d-4bea-bd25-bc7b1b791e5a)
</div>

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to the script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**
