### ISSUE TITLE
Removing subscription nag doesn't work on fresh install?

### ISSUE THREAD

**Issue by thibaultmol** [tteck/Proxmox#2237]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

i'm on a fresh proxmox 8.1.3 install and it seems like the subscription nag notification  part of the script doesn't actually work because I still get the popup. (I'm already paying for an official support license my production machine).
I have ran the script multiple times and rebooted multiple times between each attempt. but still get it

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
At the login screen, do a CTRL+R

![Screenshot 2023-12-23 7 56 48 AM](https://github.com/tteck/Proxmox/assets/21342670/cd86b368-3d08-4b21-aecb-fc608c28c206)

**Comment by thibaultmol** [comment]
didn't think that would be a cache issue. Regular refresh wasn't enough so deleted the site data and then refreshed the page, that worked. thx!

**Comment by rharmonson** [comment]
I got bit by the cache as well. This issue was very helpful. Thank you, both.
