### ISSUE TITLE
Sonarr error while executing command

### ISSUE THREAD

**Issue by ahmadarifabdulkadir** [tteck/Proxmox#2238]
Hi,

I am trying to install Sonarr but it gives me error as follow:

[ERROR] in line 29: exit code 100: while executing command DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" install -qqy sonarr &> /dev/null

This happens for both v3 and v4 install.

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to the script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

**Comment by tteck** [comment]
There seems to be issues with Sonarr download repositories. Hopefully they'll get it resolved soon.
