### ISSUE TITLE
Installation failure with - Home Assistant Container LXC  AND Podman Home Assistant Container LXC

### ISSUE THREAD

**Issue by FordMustang0288** [tteck/Proxmox#224]
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homeassistant-v3.sh)"
  _                                        _     _              _   
 | |   v3                                 (_)   | |            | |  
 | |__   ___  _ __ ___   ___  __ _ ___ ___ _ ___| |_ __ _ _ __ | |_ 
 |  _ \ / _ \|  _   _ \ / _ \/ _  / __/ __| / __| __/ _  |  _ \| __|
 | | | | (_) | | | | | |  __/ (_| \__ \__ \ \__ \ || (_| | | | | |_ 
 |_| |_|\___/|_| |_| |_|\___|\__,_|___/___/_|___/\__\__,_|_| |_|\__|

‼ ERROR 1@65 Unknown failure occured.
‼ ERROR 1@65 Unknown failure occured.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/podman-homeassistant-v3.sh)"

  _____          _                                                  
 |  __ \        | |                                                 
 | |__) |__   __| |_ __ ___   __ _ _ __                             
 |  ___/ _ \ / _  |  _   _ \ / _  |  _ \                            
 | |  | (_) | (_| | | | | | | (_| | | | |                           
 |_|   \___/ \__,_|_| |_| |_|\__,_|_| |_|  _     _              _   
 | |       v3                             (_)   | |            | |  
 | |__   ___  _ __ ___   ___  __ _ ___ ___ _ ___| |_ __ _ _ __ | |_ 
 |  _ \ / _ \|  _   _ \ / _ \/ _  / __/ __| / __| __/ _  |  _ \| __|
 | | | | (_) | | | | | |  __/ (_| \__ \__ \ \__ \ || (_| | | | | |_ 
 |_| |_|\___/|_| |_| |_|\___|\__,_|___/___/_|___/\__\__,_|_| |_|\__|
                                                                                                                        

‼ ERROR 1@72 Unknown failure occured.
‼ ERROR 1@72 Unknown failure occured.

**Comment by tteck** [comment]
What Proxmox Version are you on?

**Comment by tteck** [comment]
These scripts are intended for PVE 7

**Comment by FordMustang0288** [comment]
I just came to say that I realized the error messages were likely pointing to line numbers. Line 65 gave me the insight that I needed 7+ and I am working on updating now.

Thanks for the quick reply and sorry for the confusion. Although, an actual error message would be useful for others if that is  reasonable to do.

**Comment by tteck** [comment]
There's a message to be shown, but my error handling is catching it super fast.

**Comment by FordMustang0288** [comment]
Alright that makes sense. I just went back to see the echo myself. Just for your information, I was on 6.2-4. Thanks again, now hopefully everything else goes smoothly!

**Comment by tteck** [comment]
I just tested again...
```
  _                                        _     _              _   
 | |   v3                                 (_)   | |            | |  
 | |__   ___  _ __ ___   ___  __ _ ___ ___ _ ___| |_ __ _ _ __ | |_ 
 |  _ \ / _ \|  _   _ \ / _ \/ _  / __/ __| / __| __/ _  |  _ \| __|
 | | | | (_) | | | | | |  __/ (_| \__ \__ \ \__ \ || (_| | | | | |_ 
 |_| |_|\___/|_| |_| |_|\___|\__,_|___/___/_|___/\__\__,_|_| |_|\__|

This script requires Proxmox Virtual Environment 7.0 or greater
Exiting...
root@proxmox:~# 
```
but I'm changing parameters so it fails, not actually <7
