### ISSUE TITLE
Possible to add new Proxmox 8.x QEMU CPU Types?

### ISSUE THREAD

**Issue by juronja** [tteck/Proxmox#2240]
With version 8 Proxmox added new default CPU types. I suggest an addition in the setup wizard for:

x86-64-v2
x86-64-v2-AES
x86-64-v3
x86-64-v4

Detailed info here: https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings
Paragraph "QEMU CPU Types"

much obliged

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to the script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.** 

> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
I see no need for the change.
In short:
If live migration is not a concern, or if your cluster consists of nodes with identical CPUs and microcode versions, it is advisable to set the CPU type to '**host**.' In theory, this configuration will provide maximum performance for your guests.

For scenarios involving live migration between different CPUs, it is recommended to use the default '**kvm64**,' which is compatible with essentially all x86_64 host CPUs.

**Comment by juronja** [comment]
Sorry for posting at the wrong place. It's a nice to have feature.

I make use of the live migrations when I do hardware maintenance.
I would rather make use of the new CPU types in the future, it eventually seems more future-proof, so an option for at least the new default CPU type would be a bonus. I can use kvm64 or change post-install. 

thank you again for the awesome scripts!
