### ISSUE TITLE
unable to Update Runtipi

### ISSUE THREAD

**Issue by Trustwbc** [tteck/Proxmox#2241]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi
i installed RUNTIPI, Version 2.2.1 via ScriptHelper.
When i type "update" in runtipi Console, Message is:
"✗ There is currently no update path available."

In the runtipi Dashboard / Settings there is an:
A new version (v2.3.1) of Tipi is available
How to update
From the root folder of your Tipi install

sudo ./runtipi-cli update v2.3.1

when i type this Command in my runtipi console Message is:
sudo: ./runtipi-cli: command not found

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

type "update" in console
type "sudo ./runtipi-cli update v2.3.1"
look at runtipi dashboard

**Comment by tteck** [comment]
If it doesn't specify on the website, it means that the update process is performed within the application itself or no update path has been resolved.

**Comment by tteck** [comment]
```
cd /opt/runtipi
./runtipi-cli update latest
```

**Comment by tteck** [comment]
Now, the `update` command is working.

**Comment by JigSawFr** [comment]
@tteck nice to see that you added RunTipi to your repo, using your Docker LXC ATM to run it!
Don't hesitate to ping us if you need help,
I will add a page about your script, this will definitively help our users!
Thanks for all of your work, and have a wonderful day,
