### ISSUE TITLE
nginx proxy manager - root password not working

### ISSUE THREAD

**Issue by learningdotnet17** [tteck/Proxmox#2246]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Created a new LXC with the script today. Proxmox 7, so I used Debian 11. I gave the root password using a password manager. The same password is not working for root login. NPM comes up fine on port 81 (after a reboot) and I can login as admin. But I cannot login to the LXC as root and I don't want to continue using it in case I have issues later. Any thoughts on what might be going wrong here?

Side note - Install using Ubuntu 23.04 fails and the verbose messages are indicating something about installing python packages for Debian. That is why I switched to using Debian. There is a closed issue here that says Ubuntu is not supported but I don't see any other mention that Ubuntu is not supported

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
> Any thoughts on what might be going wrong here?

The password entered during creation is different from the one you are trying to use. That's the only reason I can think of.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by learningdotnet17** [comment]
I appreciate you taking the time to reply and I understand that from your POV it seems the most likely cause is user error. But I have used other scripts with the same process and this process has always worked so far.

Unfortunately I have spent too much time on this and I don't have time experiment again. So I am going to just let it go. Thanks again!

**Comment by tteck** [comment]
The application scripts use the same set of reusable scripts: `build.func`, `create_lxc.sh`, and `install.func`, if one works, they all _should_ work.

**Comment by learningdotnet17** [comment]
That makes sense. Thanks again
