### ISSUE TITLE
Update OS of homeassistant VM installation

### ISSUE THREAD

**Issue by T1mey** [tteck/Proxmox#2247]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

How do I update the underlying OS of an HA VM installation on proxmox?
If I enter the console only th HA cli opens and it seems that SSH is not enabled. 

### Which Linux distribution are you employing?

Ubuntu 23.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

no

### Please provide detailed steps to reproduce the issue.

How do I update the underlying OS of an HA VM installation on proxmox?
If I enter the console only th HA cli opens and it seems that SSH is not enabled.

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

You don't.
