### ISSUE TITLE
Zigbee2MQTT fails to start -alpine LXC

### ISSUE THREAD

**Issue by KimCarlsen** [tteck/Proxmox#2252]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi. 
Followed the guide on setting up Z2M on Proxmox using Alpine LXC (priviliged)
But i fails to start when rebooting the container.
I can then sign in and start it manually.

Its already set to autostart
z2m:~# rc-update add zigbee2mqtt default
 * rc-update: zigbee2mqtt already installed in runlevel `default'; skipping

How can i troubleshoot?  Note. I'm totally new to LXC and Alpine.
So is there an issue with the scripts? Thanks for great scripts BTW.

thanks
Kim

### Which Linux distribution are you employing?

Default Settings

**Comment by mues-lee** [comment]
with `rc-status` you can see the current status of the service, if it indicates a crash for zigbee2MQTT after the restart, you can take a look at the sys messages to find the cause--> `tail /var/log/messages`
