### ISSUE TITLE
Using a password which starts with -- (double dash) in advanced mode, causes script to fail

### ISSUE THREAD

**Issue by locorotondo-gitter** [tteck/Proxmox#2261]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Whenever I use "advanced" mode to run any of the install scripts and use a password which starts with -- (double dash), the script will fail. Cause seems to be that the "--" seems to be interpreted as an argument on the command line. (error message states 'unknown  option: XXXX', where XXXX is the password without the leading double dash.  Passwords without the -- at the start work fine. See below for the error message; I used --TestPassword as the password.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

+ echo -ne ' - \033[33mCreating LXC Container...'
 - Creating LXC Container...+ pct create 700 backup:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst -features nesting=1 -hostname prometheus -tags proxmox-helper-scripts -net0 name=eth0,bridge=vmbr0,ip=dhcp,tag=30 -onboot 1 -cores 1 -memory 2048 -unprivileged 0 -password --TestPassword -rootfs local-lvm:4
Unknown option: testpassword
400 unable to parse option
pct create <vmid> <ostemplate> [OPTIONS]
+ exit 'A problem occured while trying to create container.'
bash: line 163: exit: A problem occured while trying to create container.: numeric argument required
+ exit

### Please provide detailed steps to reproduce the issue.

1: Run script in advanced mode
2: make selections
3: for password give any password which starts with -- (double dash)
4: continue script
5: script seems to run, but crashes due to --whateverpassword is interpreted as an option.

**Comment by locorotondo-gitter** [comment]
I realized it helps if you see a bit more of the error message, which includes the full command line before the error. If you need me to test some things for you, please ask. See below:

+ TEMPLATE=debian-12-standard_12.2-1_amd64.tar.zst
+ pveam list backup
+ grep -q debian-12-standard_12.2-1_amd64.tar.zst
+ DEFAULT_PCT_OPTIONS=(-arch $(dpkg --print-architecture))
++ dpkg --print-architecture
+ PCT_OPTIONS=(${PCT_OPTIONS[@]:-${DEFAULT_PCT_OPTIONS[@]}})
+ [[  -features nesting=1 -hostname prometheus -tags proxmox-helper-scripts -net0 name=eth0,bridge=vmbr0,ip=dhcp,tag=30 -onboot 1 -cores 1 -memory 2048 -unprivileged 0 -password --TestPassword  =~  -rootfs  ]]
+ PCT_OPTIONS+=(-rootfs $CONTAINER_STORAGE:${PCT_DISK_SIZE:-8})
+ msg_info 'Creating LXC Container'
+ local 'msg=Creating LXC Container'
+ echo -ne ' - \033[33mCreating LXC Container...'
 - Creating LXC Container...+ pct create 700 backup:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst -features nesting=1 -hostname prometheus -tags proxmox-helper-scripts -net0 name=eth0,bridge=vmbr0,ip=dhcp,tag=30 -onboot 1 -cores 1 -memory 2048 -unprivileged 0 -password --TestPassword -rootfs local-lvm:4
Unknown option: testpassword
400 unable to parse option
pct create <vmid> <ostemplate> [OPTIONS]
+ exit 'A problem occured while trying to create container.'
bash: line 163: exit: A problem occured while trying to create container.: numeric argument required
+ exit

**Comment by tteck** [comment]
Avoid Starting or Ending with a Hyphen: Some systems may have issues with hostnames that start or end with a hyphen.

[The original specification of hostnames required that labels start with an alpha character, and not end with a hyphen.](https://en.wikipedia.org/wiki/Hostname)

In short:
Proper hostnames cannot start/end with a hyphen.

**Comment by locorotondo-gitter** [comment]
The hostname is not the problem; the password (for root login) is. 
If the password starts with a (double) hyphen, the script fails. From the text I gave: "-password --TestPassword " leads to error "Unknown option: testpassword". 
In short; if one wanted to use a password (for root login) that starts with a double hyphen, the script fails as the option "-password --WHATEVERPASSWORD" is interpreted as "option -password"  (with an empty password) AND "option whateverpassword", which of course is a non-existent option. I will see if over the weekend I can come up with a fix that captures passwords in such a manner that they are never interpreted as an option on the command line.

**Comment by tteck** [comment]
Sorry, I don't know why I was thinking hostname.
When creating a LXC the options use hyphens to separate one another:
https://github.com/tteck/Proxmox/blob/a9b44432c4ff5810582de9bc11c03e7c8e346d83/misc/build.func#L492-L503
`$PW` is populated from
https://github.com/tteck/Proxmox/blob/a9b44432c4ff5810582de9bc11c03e7c8e346d83/misc/build.func#L208
So, using a hyphen at the beginning of your password (`-password`) ends up being `-password -password` which equals 2 invalid options.

**Comment by tteck** [comment]
Dang, my reading skills are lacking lately, you mentioned exactly what I tried to explain. 🤦

Edit: I've got to stop glazing over comments and actually read them.

**Comment by locorotondo-gitter** [comment]
That's always a good idea :-), but I guess you have to wade through tons of comments which don't make sense, so no harm done. Happy 2024 by the way. 

Is there an easy fix around this, such like enclosing the password given between special characters? Or maybe have a check on the input field which rejects passwords starting with a "-"? (if first character = '-', give warning and try again, or something like that)
