### ISSUE TITLE
Cannot run PVE Post Install script on a Mac-mini server.  No error message given.

### ISSUE THREAD

**Issue by Buckeyes1995** [tteck/Proxmox#2263]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am trying to run the post install script on my Mac-Mini Proxmox Server. I have several LXCs running without issue.  When I attempt to run the PVE Install Script, I select 'Yes' to every option except 'Disable high availability' as I run a three node cluster.  The script starts with the 'Updating Proxmox VE (Patience)...' print out and then just drops out to the shell. No error message is given.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/35143900/43aa97db-9e21-4fb0-b6c4-d32e01f64965)

### Please provide detailed steps to reproduce the issue.

1.  Open ProxMox Console.
2. Paste the following into shell: _**bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"**_

**Comment by tteck** [comment]
That section is just a
```
    msg_info "Updating Proxmox VE (Patience)"
    apt-get update &>/dev/null
    apt-get -y dist-upgrade &>/dev/null
    msg_ok "Updated Proxmox VE"
```
so, there shouldn't be any reason that I can think of for it to end (unless there's DNS issues).

```
    ____ _    ________   ____             __     ____           __        ____
   / __ \ |  / / ____/  / __ \____  _____/ /_   /  _/___  _____/ /_____ _/ / /
  / /_/ / | / / __/    / /_/ / __ \/ ___/ __/   / // __ \/ ___/ __/ __ `/ / /
 / ____/| |/ / /___   / ____/ /_/ (__  ) /_   _/ // / / (__  ) /_/ /_/ / / /
/_/     |___/_____/  /_/    \____/____/\__/  /___/_/ /_/____/\__/\__,_/_/_/

 ✓ Corrected Proxmox VE Sources
 ✓ Disabled 'pve-enterprise' repository
 ✓ Enabled 'pve-no-subscription' repository
 ✓ Enabled 'ceph package repositories'
 ✓ Added 'pvetest' repository
 ✗ Selected no to Enabling high availability
 ✓ Updated Proxmox VE
 ✗ Selected no to Rebooting Proxmox VE (Reboot recommended)
 ✓ Completed Post Install Routines
root@pve:~# 
```

**Comment by tteck** [comment]
Could it be that you're facing a network problem? _Probably_ linked to DNS.

**Comment by Buckeyes1995** [comment]
> Could it be that you're facing a network problem? _Probably_ linked to DNS.

I don't believe so.  I can do apt-get update/upgrade fine, get to all traffic on my LXCs, etc.    If I manually run 'apt-get -y dist-upgrade' I do get a message that says : "E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem."

**Comment by tteck** [comment]
The command (`dpkg --configure -a`) will attempt to configure any packages that were not configured during an interrupted installation or update.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by Buckeyes1995** [comment]
> The command (`dpkg --configure -a`) will attempt to configure any packages that were not configured during an interrupted installation or update.

Thanks, that cleaned it up and allowed the script to complete.
