### ISSUE TITLE
influxdb

### ISSUE THREAD

**Issue by titof2375** [tteck/Proxmox#227]
![erreur](https://user-images.githubusercontent.com/31250165/167307450-cdf5faab-f38a-43e2-a7e4-fc003d5cfb2f.PNG)

**Comment by tteck** [comment]
what did you type in as size?

**Comment by titof2375** [comment]
I'm not tall

**Comment by tteck** [comment]
wtf?

**Comment by titof2375** [comment]
![erreur_LI](https://user-images.githubusercontent.com/31250165/167307845-6eadfb76-17e4-4744-aba3-cfd6fc20c5af.jpg)
