### ISSUE TITLE
Paperless LXC update from bullseye -> bookworm not working.

### ISSUE THREAD

**Issue by Nick4-1** [tteck/Proxmox#2278]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Was running Paperless on Proxmox 7.x (latest), upgraded to 8.x, changed the repository from bullseye to bookworm in the LXC and now can't access the webUI anymore

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> **Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section.** Blank issues will be closed immediately.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/1498

**Comment by Nick4-1** [comment]
Hi, thank you for your quick response!
I did a search in the issues, but for paperless bullseye bookworm.

Started over with backup from LXC and your solution in the link but still the same.

**Comment by tteck** [comment]
Did you reboot the LXC?

**Comment by Nick4-1** [comment]
Yes.
Could it have something to do with the version of paperless I was running (1.17.4)?
Apart from that, the container was up-to-date on bullseye.

**Comment by tteck** [comment]
🤷🏻‍♂️  There's nothing wrong with leaving it running on Debian 11

**Comment by Nick4-1** [comment]
I guess not.
I just thought that upgrading would just work, and got curious why it didn't.
As a test I also tried a fresh install which worked right away.
Is this a common problem, do you have an idea what the reason might be?
