### ISSUE TITLE
Gotify new script

### ISSUE THREAD

**Issue by oliv99** [tteck/Proxmox#2280]
https://gotify.net/

Bonjour,

Gotify is an open-source self-hosted notification server that allows you to send and receive push notifications to various devices and applications. It provides a simple API and web interface, making it easy to integrate with different platforms and service

**As Proxmox 8 has implemented Gotify notification, it would be nice to have this has an LXC server**

Thanks for all your great work !

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to the script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.** 

> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/3cfb46c580c315d45b6feeede7ccb1457953fefa
