### ISSUE TITLE
Zigbee2MQTT now needs NPM if updated in LXC

### ISSUE THREAD

**Issue by Calimerorulez** [tteck/Proxmox#2281]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi,

First of all, happy New Year.
I just tried to update in my Zigbee2MQTT LXC to 1.35.0, but the script fails because `npm` isn't installed. Following the guide in the script for handling of the data and the backup directory, manually installing `npm`, and then running the update script again, fixed it.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
node 18.x stopped utilizing npm by default

I'll add
```
if [[ "$(node -v | cut -d 'v' -f 2)" == "18."* ]]; then
  if ! command -v npm >/dev/null 2>&1; then
    echo "Installing NPM..."
    apt-get install -y npm >/dev/null 2>&1
    echo "Installed NPM..."
  fi
fi
```
to the update script. It checks if the installed version of Node.js is 18.x and, if so, ensures that npm is also installed.
