### ISSUE TITLE
ioBroker installation fails

### ISSUE THREAD

**Issue by derlbear** [tteck/Proxmox#2282]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

` - Installing ioBroker (Patience)...
[ERROR] in line 24: exit code 1: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

root@proxmox:~# `

That's it. I receive the error on two different proxmox systems. To be fair: the manual iobroker installation also fails because nodejs can't be installed (on the created LXC).

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Use this command in the Proxmox VE Shell:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/iobroker.sh)"

Use default settings.

**Comment by tteck** [comment]
Since node 18.x has stopped utilizing npm by default, it has broken their script.
Fixed by installing node.js v20.x

**Comment by derlbear** [comment]
That was quick! Awesome, thanks!
