### ISSUE TITLE
Node-Red LXC

### ISSUE THREAD

**Issue by Hoosier-IT** [tteck/Proxmox#2283]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

 Running LXC update, bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/node-red.sh)"
   _   __          __        ____           __
   / | / /___  ____/ /__     / __ \___  ____/ /
  /  |/ / __ \/ __  / _ \   / /_/ / _ \/ __  / 
 / /|  / /_/ / /_/ /  __/  / _, _/  __/ /_/ /  
/_/ |_/\____/\__,_/\___/  /_/ |_|\___/\__,_/   
 
 ✓ Stopped Node-Red
 - Updating Node-Red...
[ERROR] in line 66: exit code 127: while executing command npm install -g --unsafe-perm node-red &> /dev/null

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
ESPHome? Did you mean Node-Red?

**Comment by Hoosier-IT** [comment]
> ESPHome? Did you mean Node-Red?

Corrected title, yes, Node-Red.

**Comment by tteck** [comment]
fixed
