### ISSUE TITLE
Node-RED Themes

### ISSUE THREAD

**Issue by bonanitech** [tteck/Proxmox#2287]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Node-RED LXC script installs deprecated NPM packages for Node-RED themes. Those themes are now maintained in a new package with many new theme options.

https://github.com/node-red-contrib-themes/theme-collection

https://www.npmjs.com/package/@node-red-contrib-themes/theme-collection

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Thank you for bringing this to my attention.
