### ISSUE TITLE
Adguard

### ISSUE THREAD

**Issue by rodgers86** [tteck/Proxmox#2293]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After pasting

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/adguard.sh)"
`

into the Proxmox shell, 

I get a short delay and then it just goes to root@proxmox1:~#

No VM is created and no option to set up comes up, as they do for the other things I installed today (HA, MQTT and z2m) I have got all these working. 

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
It seems that you're facing a network problem, _probably_ linked to DNS. 
The script runs without any problems from this end.

**Comment by rodgers86** [comment]
Many thanks!! Pointed me in the correct direction. No idea how that setting changed! But its fixed now
