### ISSUE TITLE
ps uses unrecognized -p option in Alpine Docker script

### ISSUE THREAD

**Issue by deviantintegral** [tteck/Proxmox#2301]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

It looks like the setup script is assuming procutils is installed, as busybox doesn't support the `-p` option.

What's odd is the setup script was working fine a week ago, and I don't see any obvious changes in the repo that would cause this.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
    ____             __
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /
/_____/\____/\___/_/|_|\___/_/
 Alpine

Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 106
Using Hostname: airthings-mqtt-ha-docker
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using vmdata for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 106 was successfully created.
 ✓ Started LXC Container
 - Setting up Container OS  /ps: unrecognized option: p
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
	-T			Show threads
```

### Please provide detailed steps to reproduce the issue.

`bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-docker.sh)"`

**Comment by deviantintegral** [comment]
Here's the relevant snippet from verbose mode:

```
+ cat
+ msg_ok 'Set up Container OS'
+ '[' -n 453 ']'
+ ps -p 453
ps: unrecognized option: p
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
	-T			Show threads
+ printf '\e[?25h'
+ local 'msg=Set up Container OS'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mSet up Container OS\033[m'
 ✓ Set up Container OS
++ tail -n1
++ cut -d/ -f1
++ awk '{print $2}'
++ grep 'inet '
++ ip addr show
+ msg_ok 'Network Connected: \033[36m192.168.20.167\033[m'
+ '[' -n 453 ']'
+ ps -p 453
ps: unrecognized option: p
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
	-T			Show threads
+ printf '\e[?25h'
```

**Comment by deviantintegral** [comment]
I tried bisecting, but I still see this going back as far as 5e4f0d683ac73a4cbe9fac81b65cdc01634edf80. I wonder if the upstream template changed? I see `alpine-3.18-default_20230607_amd64.tar.xz` has a date of `2023-12-25 13:39:03` which is after I last remember this working.

**Comment by tteck** [comment]
fixed https://github.com/tteck/Proxmox/commit/e27191e60787b238ec0ce5cd88eddc5ea1a91263

**Comment by deviantintegral** [comment]
Thank you! Confirmed fixed.

A quick aside; I realized my bisecting wasn't working because the scripts themselves look to hardcode curling from `main` even in a local checkout. I didn't find any local development docs. Can we link to them in the README? Or if they don't exist, I'd be happy to write them up and test them if you can provide a rough outline of your dev / test process.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/main/CODE-AUDIT.md
