### ISSUE TITLE
Tdarr

### ISSUE THREAD

**Issue by nlmz90** [tteck/Proxmox#2305]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

 - Updating Tdarr LXC  \
[ERROR] in line 57: exit code 0: while executing command apt-get update &> /dev/null

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 - Updating Tdarr LXC   + SPINNER_PID=2109
+ apt-get update
+ spinner
+ printf '\e[?25l'
+ spinner='/-\|/-\|'
+ spin_i=0
+ true
+ printf '\b%s' /
/+ sleep 0.1
+ true
+ printf '\b%s' -
-+ sleep 0.1
+ true
+ printf '\b%s' '\'
\+ sleep 0.1
+ true
+ printf '\b%s' '|'
|+ sleep 0.1
+ true
+ printf '\b%s' /
/+ sleep 0.1
+ true
+ printf '\b%s' -
-+ sleep 0.1
+ true
+ printf '\b%s' '\'
\+ sleep 0.1
+ true
+ printf '\b%s' '|'
|+ sleep 0.1
+ true
+ printf '\b%s' /
/+ sleep 0.1
+ true
+ printf '\b%s' -
-+ sleep 0.1
+ true
+ printf '\b%s' '\'
\+ sleep 0.1
+ true
+ printf '\b%s' '|'
|+ sleep 0.1
+ true
+ printf '\b%s' /
/+ sleep 0.1
+ true
+ printf '\b%s' -
-+ sleep 0.1
+ true
+ printf '\b%s' '\'
\+ sleep 0.1
++ error_handler 57 'apt-get update &> /dev/null'
++ '[' -n 2109 ']'
++ ps -p 2109
++ kill 2109
++ printf '\e[?25h'
++ local exit_code=0
++ local line_number=57
++ local 'command=apt-get update &> /dev/null'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m57\033[m: exit code \033[01;31m0\033[m: while executing command \033[33mapt-get update &> /dev/null\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m57\033[m: exit code \033[01;31m0\033[m: while executing command \033[33mapt-get update &> /dev/null\033[m\n'

[ERROR] in line 57: exit code 0: while executing command apt-get update &> /dev/null

### Please provide detailed steps to reproduce the issue.

When updating the Tdarr LXC with either the original bash code or update command this error shows up. 
When attempting to make a new LXC with the bash command it stalls on Installing Tdarr

**Comment by tteck** [comment]
Try `apt update && apt upgrade` in the console, postfix fix may be holding it up. 🤷🏻‍♂️ 
 
It's a standard snippet
```
function update_script() {
header_info
if [[ ! -d /opt/tdarr ]]; then msg_error "No ${APP} Installation Found!"; exit; fi
msg_info "Updating $APP LXC"
apt-get update &>/dev/null
apt-get -y upgrade &>/dev/null
msg_ok "Updated $APP LXC"
exit
}
```

**Comment by nlmz90** [comment]
Thank you, it didn't update though running the script to make a new LXC worked.
