### ISSUE TITLE
Unable to update Zwavejs2MQTT

### ISSUE THREAD

**Issue by gforschi** [tteck/Proxmox#231]
Hi, I'm not able to update my Zwavejs2MQTT LXC using your script.
It seems to get stuck on Updating Zwavejs2MQTT...

**Comment by tteck** [comment]
is `zwavejs2mqtt-v6.9.1.zip` in directory `/opt/zwavejs2mqtt`? https://github.com/tteck/Proxmox/discussions/220
I can't replicate the issue.

**Comment by gforschi** [comment]
Yes I can find the .zip in the /opt/zwavejs2mqtt
I tried running the script line by line and it seems to hang on the unzip command

**Comment by FredericMa** [comment]
I had the same issue this week but thought I messed something up myself. It was hanging at the unzip because the folder to extract to already existed. So it was asking for confirmation on what to do (overwrite,...) Deleting the existing folder and reruning the script solved it for me.

**Comment by tteck** [comment]
Try running the update script again, I changed it to `unzip -o`

**Comment by gforschi** [comment]
Perfect! That solved it
Thanks!

**Comment by tteck** [comment]
Thanks @FredericMa
