### ISSUE TITLE
Stirling-PDF Exits Silently

### ISSUE THREAD

**Issue by shiftybitshiftr** [tteck/Proxmox#2313]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When executing `stirling-pdf.sh` in the ProxMox VE Shell with the provided bash snippet, the script exits silently.

My ProxMox kernel version is Linux 5.15.85-1-pve #1 SMP PVE 5.15.85-1 (2023-02-01T00:00Z) and PVE manager is pve-manager/7.3-6/723bb6ec.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/13820335/441afb1d-3ebb-4d39-a7fc-c4c965b2a203)

### Please provide detailed steps to reproduce the issue.

- Open ProxMox VE Shell
- Paste in `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/stirling-pdf.sh)"`
- Hit Enter

**Comment by tteck** [comment]
It seems that you're facing a network problem, _probably_ linked to DNS.

**Comment by shiftybitshiftr** [comment]
Good call. I had tested with another script a bit later (`paperless-ngx.sh`) and got the UI, so I assumed it was specific to this script. On checking my traffic logs, my line was completely saturated when I tried `stirling-pdf.sh` - trying again now it works fine. Woops.

Thanks for making these (and for your patience)!
