### ISSUE TITLE
Please add par2cmdline-turbo to sabnzbd Script

### ISSUE THREAD

**Issue by bjoerrrrn** [tteck/Proxmox#2315]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Heya, i have no time for a PR right now, but i would like to see that par2cmdline-turbo gets added to the sabnzbd container. I will add my installation steps in the clarifying block. Thanks!

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
cd ~
wget https://github.com/animetosho/par2cmdline-turbo/releases/download/v1.1.1/par2cmdline-turbo-v1.1.1-linux-amd64.xz
xz -dv par2cmdline-turbo-v1.1.1-linux-amd64.xz
chmod +x par2cmdline-turbo-v1.1.1-linux-amd64
mv /usr/bin/par2 /usr/bin/par2.old
mv par2cmdline-turbo-v1.1.1-linux-amd64 /usr/bin/par2
```

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by PropaneMilo** [comment]
For future googlers:
Discussion [https://github.com/tteck/Proxmox/discussions/2316](https://github.com/tteck/Proxmox/discussions/2316): _Please add par2cmdline-turbo to sabnzbd Script #2316_
