### ISSUE TITLE
USB pass throught to Home assistant OS 

### ISSUE THREAD

**Issue by Haasie** [tteck/Proxmox#232]
Hello tteck,

Thank you for your work making proxmox easier for people like me.
there is one thing that i can not figure out. how do i pass through a P1 (DSMR) reader USB to Home Assistant OS? it keeps seeing it like an event instead of and device. 
Can you give me any guidance?

**Comment by tteck** [comment]
Sorry, that's a question for the Home Assistant forum/discord as I don't know what a "P1 (DSMR) reader" is.
