### ISSUE TITLE
error when running haos script - line 414 wget -q --show=progress $URL

### ISSUE THREAD

**Issue by Taubin** [tteck/Proxmox#2320]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I an attempting to run the home assistant os script at https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh

I am following the instructions at https://www.derekseaman.com/2023/10/home-assistant-proxmox-ve-8-0-quick-start-guide-2.html which work well until after performing the advanced section. It downloads the hoas_ova_11.4.qcow2.xz file, then it gives the following error: 

`[ERROR] in line 414: exit code 0: while executing command wget -q --show-progress $URL`
 It then boots me back to the prompt. 

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2024-01-11 164712](https://github.com/tteck/Proxmox/assets/8891792/c7e520f2-73eb-4fbf-9a55-75ec14d7eb3e)

### Please provide detailed steps to reproduce the issue.

Open shell within proxmox, paste `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)"`

**Comment by Taubin** [comment]
Never mind, seems to have been a github issue. It is working now. Sorry about that.

**Comment by alcaan16** [comment]
I'm in the same situation. someone help me?
