### ISSUE TITLE
AgentDVR crashes

### ISSUE THREAD

**Issue by ipod86** [tteck/Proxmox#2322]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

AgentDVR crashes as soon as you use a function that uses the graphics card.  After I installed sudo apt install libva-drm2, things work.

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Use Timelaps

**Comment by tteck** [comment]
Thanks for reporting.
