### ISSUE TITLE
Sonar Script Update failure : /dev/fd/63: line 69: SPINNER_PID: unbound variable

### ISSUE THREAD

**Issue by digitydogs** [tteck/Proxmox#2324]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When attempting to run the script in the lxc to update sonar the following error is given : 

   _____
  / ___/____  ____  ____  __________
  \__ \/ __ \/ __ \/ __ `/ ___/ ___/
 ___/ / /_/ / / / / /_/ / /  / /
/____/\____/_/ /_/\__,_/_/  /_/

/dev/fd/63: line 69: SPINNER_PID: unbound variable

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Could this be the issue?

## 2024-01-03

### Changed

- **Sonarr LXC**
  - Breaking Change
  - Complete recode
  - https://github.com/tteck/Proxmox/discussions/1738#discussioncomment-8005107

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
   _____
  / ___/____  ____  ____  __________
  \__ \/ __ \/ __ \/ __ `/ ___/ ___/
 ___/ / /_/ / / / / /_/ / /  / /
/____/\____/_/ /_/\__,_/_/  /_/

 ✓ Updated Sonarr v4
root@sonarr:~# 
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
