### ISSUE TITLE
Username & password for vm-ubuntu 

### ISSUE THREAD

**Issue by ussdeveloper** [tteck/Proxmox#2325]
Hi, maybe it's stupid questrion but I did run script for install vm-ubuntu but I cannot login what is the username and password ?

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.** 

https://github.com/tteck/Proxmox/discussions/2072
