### ISSUE TITLE
AgentDVR update error

### ISSUE THREAD

**Issue by ipod86** [tteck/Proxmox#2326]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I just wanted to update AgentDVR because (even though my installation is very recent) my version is quite old. To do this I entered "update" in the shell. Unfortunately the update doesn't work.

`
   /   | ____ ____  ____  / /_/ __ \ |  / / __ \
  / /| |/ __ `/ _ \/ __ \/ __/ / / / | / / /_/ /
 / ___ / /_/ /  __/ / / / /_/ /_/ /| |/ / _, _/
/_/  |_\__, /\___/_/ /_/\__/_____/ |___/_/ |_|
      /____/
/dev/fd/63: line 69: SPINNER_PID: unbound variable
root@agentdvr:~#
`
p.s.:

The normal update of AGentDVR does not work in CT. According to the instructions you have to stop the service with sudo systemctl stop AgentDVR.service. However, he says that the service is not running.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Nowhere does it give update instructions.

![Screenshot 2024-01-12 4 34 41 AM](https://github.com/tteck/Proxmox/assets/21342670/6fdc6efb-54e3-4b9e-ae4e-827abb9eac84)

https://github.com/tteck/Proxmox/blob/478b4e1c32ca1f9942d0f4bfd53523af6702c41c/ct/agentdvr.sh#L53-L58

As for the "unbound variable" error, I'll fix that.

**Comment by tteck** [comment]
What version is your AgentDVR?

**Comment by ipod86** [comment]
5.1.0.0
