### ISSUE TITLE
Stirling-PDF App Version

### ISSUE THREAD

**Issue by Deekerman** [tteck/Proxmox#2327]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing Stirling-PDF i looked in the settings and it says "App Version: 0.0.0" and that there is an update available. So I went into the lxc and typed update, got the confirmation it is now on the latest (at this time its v0.19.1) but in the app itself it says the same thing. 

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/33733383/4610e090-1278-409b-86e3-5ce4b9e53ac1)

### Please provide detailed steps to reproduce the issue.

For me it was just install Stirling-PDF

**Comment by tteck** [comment]
> Generate a report on an **issue pertaining specifically to a script**. For other inquires please share them in the Discussions section. Blank issues will be closed immediately.

https://github.com/tteck/Proxmox/discussions/1887#discussioncomment-8046777
