### ISSUE TITLE
Homepage LXC Issue - Unbound Variable

### ISSUE THREAD

**Issue by MikeTheScriptKid** [tteck/Proxmox#2328]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I'm trying to install the Homepage LXC in Proxmox. In the terminal I enter the command: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homepage.sh)"

It comes up and says it will install Homepage LXC - I select Yes.
Use default settings: Yes

But then I get this error:
Creating a Homepage LXC using the above default settings
/dev/fd/63: line 514: APT_CACHER: unbound variable

Does anyone know how to fix this?

### Which Linux distribution are you employing?

Default Settings

**Comment by dserranoc** [comment]
Same for me with umbrel script. It seems like tteck is changing something and has not finished yet.

**Comment by tteck** [comment]
Guys, please check if the issue has been resolved (may have to clear browser cache).

**Comment by greirson** [comment]
@tteck Just tested with PiAlert, getting this error.

```
Creating a PiAlert LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.22.9 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 192.30.255.112
 - Updating Container OS   /dev/stdin: line 134: CACHER: unbound variable
```

**Comment by dserranoc** [comment]
> Guys, please check if the issue has been resolved (may have to clear browser cache).

Still nothing, but now the error appears in "Updating Container OS" step.

**Comment by MikeTheScriptKid** [comment]
> Guys, please check if the issue has been resolved (may have to clear browser cache).

It goes on to install but now theres another error:

Updating Container OS   /dev/stdin: line 134: CACHER: unbound variable

**Comment by BRShadow19** [comment]
> It goes on to install but now theres another error:
> 
> Updating Container OS /dev/stdin: line 134: CACHER: unbound variable

I'm getting this same error with the Transmission script, and this is with the new change that was pushed about 15 minutes ago

**Comment by tteck** [comment]
All issues should be resolved.
