### ISSUE TITLE
LXC Update script failing on non debian or /bin/bash containers 

### ISSUE THREAD

**Issue by jershbytes** [tteck/Proxmox#233]
lxc-attach: 100: attach.c: lxc_attach_run_command: 1839 No such file or directory - Failed to exec "bash"

I tried to use the LXC update script on my install last couple days and return the same error. This seems to fail on the ngnix proxy manager container which uses alpine most likely will fail on my non debians one as well which im not concerned about wonder if their is a way to exclude the ones that fail out besides turning them off during each update.

**Comment by tteck** [comment]
The update script ONLY works with the install Nginx Proxy Manager LXC script from this repo

**Comment by tteck** [comment]
Sorry, I read it wrong, yeah, only Debian/Ubuntu LXC's
