### ISSUE TITLE
Debian Vaultwarden - Unable to Update

### ISSUE THREAD

**Issue by themanbornwithin** [tteck/Proxmox#2330]
Using the script I am unable to update Vaultwarden server. It will sit for roughly 15 minutes before exiting without any error. I cannot access my vault afterwards. I get 90+% CPU utilization for around 5ish minutes, then it drops to 25% until it exits.

I have assigned 4 CPUs. 4GB mem, and 20GB (5GB used) of HD space. Tried installing all OS updates without any changes.

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**
