### ISSUE TITLE
Unable to update Debian Vaultwarden

### ISSUE THREAD

**Issue by themanbornwithin** [tteck/Proxmox#2331]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Using the script I am unable to update Vaultwarden server (currently at v1.30.0-03c6ed2e). It will sit for roughly 15 minutes before exiting without any error. I cannot access my vault afterwards. I get 90+% CPU utilization for around 5ish minutes, then it drops to 25% until it exits.

I have assigned 4 CPUs. 4GB mem, and 20GB (5GB used) of HD space. Tried installing all OS updates without any changes.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Try allotting 6GB of RAM for the build process.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
 _    __            ____ _       __               __         
| |  / /___ ___  __/ / /| |     / /___ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
                                                             

 ⚠️  Ensure you set 4vCPU & 4096MiB RAM minimum!!! 

 ✓ Stopped Vaultwarden
 ✓ Updated VaultWarden
 ✓ Cleaned
 ✓ Started Vaultwarden
 ✓ 1.30.1 Update Successful

 ⚠️  Ensure you set resources back to normal settings 

root@vaultwarden:~# 
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
