### ISSUE TITLE
Home Assistant OS VM unbound variable

### ISSUE THREAD

**Issue by brettinternet** [tteck/Proxmox#2338]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the HAOS VM setup script:

```sh
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)"
```

I then see this error after the initial prompt:

```
environment: line 100: SPINNER_PID: unbound variable
```

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

To work around this I simply ran the script with the variable defined:

```
SPINNER_PID="" bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)"
```

**Comment by tteck** [comment]
Did you execute via SSH or the Proxmox shell?

**Comment by brettinternet** [comment]
I attempted both
