### ISSUE TITLE
mqtt fails to start - chown issue ?

### ISSUE THREAD

**Issue by magiva** [tteck/Proxmox#2339]
I followed this guide
https://smarthomescene.com/guides/how-to-separate-zigbee2mqtt-from-home-assistant-in-proxmox/

which executes and installs mqtt to proxmox - successfully 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/mqtt.sh)"

i then set the password as guided
sudo mosquitto_passwd -c /etc/mosquitto/passwd <user>

and ensure i have the default config

upon restarting with sudo systemctl restart mosquitto
im informed that the service has issues
![image](https://github.com/tteck/Proxmox/assets/7522405/6ba90ae8-a003-4977-b16a-50bce35872e1)

looking in the log i have this repeating
1705225164: mosquitto version 2.0.18 starting
1705225164: Config loaded from /etc/mosquitto/mosquitto.conf.
1705225164: Error: Unable to open pwfile "/etc/mosquitto/passwd".
1705225164: Error opening password file "/etc/mosquitto/passwd".

i saw that in a non-proxmox thread that maybe the chown is using the wrong user but i dont know where i would change that
the ct auto logs in with root.

**Comment by magiva** [comment]
i got it running with
sudo chmod 777 /etc/mosquitto/passwd
but this is not ideal i dont think

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.** 

If you had look at the instructions here, you would have noticed they left out `chown mosquitto:mosquitto /etc/mosquitto/passwd`
