### ISSUE TITLE
Website: Open Links in New Window/Tab

### ISSUE THREAD

**Issue by GTez** [tteck/Proxmox#2342]
Firstly, I want to say a big thanks for your awesome scripts. They're wicked!

When I'm [browsing them,](https://tteck.github.io/Proxmox/) most have a link to the app's webpage (example below) to learn more. Sometime I'll click on them and forget to open the link in a new page, then forgot to come back to the original page.  Would it be possible to open those links in a new page via a `target="_blank"` attribute in the `<a>`?

![image](https://github.com/tteck/Proxmox/assets/872203/ace54154-ee4a-4963-8895-46afa0581574)

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

**Comment by tteck** [comment]
Your request has been completed.

Old code
`[Uptime Kuma](https://github.com/louislam/uptime-kuma#uptime-kuma)`

New code
`<a href="https://github.com/louislam/uptime-kuma#uptime-kuma" target="_blank" rel="noopener noreferrer">Uptime Kuma</a>`
