### ISSUE TITLE
Docker LXC - 400 Parameter verification failed

### ISSUE THREAD

**Issue by edilhouse** [tteck/Proxmox#2344]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While installing a container (I tried Docker and Influxdb LXC) I get this error.
I already ran the Proxmox VE Post Install, but nothing changed

Proxmox 7.0-11

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Creating a Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 - Downloading LXC Template  /400 Parameter verification failed.
template: no such template
pveam download <storage> <template>
bash: line 168: exit: A problem occured while downloading the LXC template.: numeric argument required

### Please provide detailed steps to reproduce the issue.

run lxc scripts for docker

**Comment by tteck** [comment]
Why are you using such an old Proxmox version?
If you had successfully executed the  Proxmox VE Post Install script, you _should_ be on version 7.4.17 

The script runs without any problems from this end. 

```
    ____             __            
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: docker
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker v24.0.7
Would you like to add Portainer? <y/N> 
Would you like to add the Portainer Agent? <y/N> 
Would you like to add Docker Compose? <y/N> 
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```
It seems that you're facing a network problem, _probably_ linked to DNS.

**Comment by edilhouse** [comment]
Thanks @tteck 

Since it's a remote machine not directly accessible by me, I was worried to have issues upgrading from 7.0.x to 7.4.x

I have ran the post install scripts, without updating, since I read same issue here solved running post install script.

After your answer, I have done the updates, crossing my fingers, and everything went fine.

Also the Docker script runned well, so thanks

I will close the issue

**Comment by tteck** [comment]
Why not update to version 8 now?
https://www.derekseaman.com/2023/06/how-to-proxmox-7-4-to-8-0-upgrade.html
