### ISSUE TITLE
✗ No Sonarr Installation Found!

### ISSUE THREAD

**Issue by n0bbi** [tteck/Proxmox#2347]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I try to run the update for Sonarr and I get the error message, "No Sonarr Installation Found!". The last update worked without any problems. 

### Which Linux distribution are you employing?

Ubuntu 23.04

**Comment by tteck** [comment]
## 2024-01-03

### Changed

- **Sonarr LXC**
  - Breaking Change
  - Complete recode
  - https://github.com/tteck/Proxmox/discussions/1738#discussioncomment-8005107

**Comment by n0bbi** [comment]
Sorry, I should have found this :(
