### ISSUE TITLE
Problem installing OPENWRT VM scrip 

### ISSUE THREAD

**Issue by Wellynounet** [tteck/Proxmox#2350]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

![image](https://github.com/tteck/Proxmox/assets/88185485/47898f12-c8af-491b-9802-10dd7222ba6e)
Hello, I just made a small homelab with proxmox I discover this universe but I encounter a small problem with the script for openwrt at the end I have an error 

https://i.imgur.com/2KEngpU.png

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

https://i.imgur.com/2KEngpU.png

### Please provide detailed steps to reproduce the issue.

go in proxmox  shell  copy/paste 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/openwrt.sh)" 
enter clik enter for everything and waiiiiiiiit 
and  the error  happen

**Comment by Wellynounet** [comment]
https://mega.nz/file/t6ljAQrR#lIBP0GvJNZBMR_3m_UPRq-c4yj-Coj0IF010qZLUPOY

here the videos

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
   ____                 _       __     __
  / __ \____  ___  ____| |     / /____/ /_
 / / / / __ \/ _ \/ __ \ | /| / / ___/ __/
/ /_/ / /_/ /  __/ / / / |/ |/ / /  / /_
\____/ .___/\___/_/ /_/|__/|__/_/   \__/
    /_/ W I R E L E S S   F R E E D O M

Using Advanced Settings
Virtual Machine ID: 112
Using Hostname: openwrt
Allocated Cores: 1
Allocated RAM: 256
Using WAN Bridge: vmbr0
Using LAN Bridge: vmbr0
Using LAN IP ADDRESS: 192.168.1.1
Using LAN NETMASK: 255.255.255.0
Using WAN MAC Address: 02:99:69:B1:9D:49
Using LAN MAC Address: 02:D7:A9:51:83:06
Using WAN Vlan: Default
Using LAN Vlan: 999
Using Interface MTU Size: Default
Start VM when completed: no
Creating a OpenWrt VM using the above advanced settings
 ✓ Using local-lvm for Storage Location.
 ✓ Virtual Machine ID is 112.
 ✓ https://downloads.openwrt.org/releases/23.05.2/targets/x86/64/openwrt-23.05.2-x86-64-generic-ext4-combined.img.gz
 ✓ Downloaded openwrt-23.05.2-x86-64-generic-ext4-combined.img.gz
 ✓ Extracted & Resized OpenWrt Disk Image openwrt-23.05.2-x86-64-generic-ext4-combined.img
 ✓ Created OpenWrt VM (openwrt)
 ✓ Network interfaces are being configured as OpenWrt initiates.
Sending line: 
Sending line: uci delete network.@device[0]
Sending line: uci set network.wan=interface
Sending line: uci set network.wan.device=eth1
Sending line: uci set network.wan.proto=dhcp
Sending line: uci delete network.lan
Sending line: uci set network.lan=interface
Sending line: uci set network.lan.device=eth0
Sending line: uci set network.lan.proto=static
Sending line: uci set network.lan.ipaddr=192.168.1.1
Sending line: uci set network.lan.netmask=255.255.255.0
Sending line: uci set firewall.@zone[1].input='ACCEPT'
Sending line: uci set firewall.@zone[1].forward='ACCEPT'
Sending line: uci commit
Sending line: halt
 ✓ Network interfaces have been successfully configured.
 ✓ Bridge interfaces have been successfully added.
 ✓ Completed Successfully!
```

**Comment by tteck** [comment]
If I cannot reproduce the problem on my side, I cannot address an issue that appears to be functioning correctly here. 
As this issue is unrelated to the script, it is considered closed.
