### ISSUE TITLE
Zigbee2MQTT PVE Installer Script - Fails on Edge Install

### ISSUE THREAD

**Issue by ElksInNC** [tteck/Proxmox#2353]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Using Zigbee2MQTT LXC (not Alpine) install the script errors out right after answering Y to the EDGE install question.

I repeated install exactly the same way (after deleting CT) and got the same error at this point each time.

Successfully installs if answer N to Edge/dev branch question.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

` ✓ Installed Node.js
 - Setting up Zigbee2MQTT Repository  /Cloning into '/opt/zigbee2mqtt'...
/remote: Enumerating objects: 141, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 141 (delta 7), reused 55 (delta 0), pack-reused 0
Receiving objects: 100% (141/141), 519.89 KiB | 4.41 MiB/s, done.
Resolving deltas: 100% (7/7), done.
 ✓ Set up Zigbee2MQTT Repository
Switch to Edge/dev branch? (y/N) y
 - Installing Zigbee2MQTT  /error: pathspec 'dev' did not match any file(s) known to git

[ERROR] in line 53: exit code 0: while executing command $STD git checkout dev`

### Please provide detailed steps to reproduce the issue.

![Screenshot 2024-01-16 at 16 52 03](https://github.com/tteck/Proxmox/assets/77821967/9772070e-992a-4f94-a6b7-32807f570da5)
![Screenshot 2024-01-16 at 16 56 36](https://github.com/tteck/Proxmox/assets/77821967/719445c3-0166-4037-a03c-401437c2f39a)

PVE Version / Setup
![Screenshot 2024-01-16 at 16 42 13](https://github.com/tteck/Proxmox/assets/77821967/80a9d020-2b51-466e-a227-c38878959744)

**Comment by tteck** [comment]
This is the result of using shallow clone https://github.com/tteck/Proxmox/commit/8b340be22dbb66e1aecc593e454e079c52b728a2 Let me see what I can do...

**Comment by tteck** [comment]
Should be fixed now. Would you please test?

**Comment by tteck** [comment]
Fixed

**Comment by ElksInNC** [comment]
Confirmed - works correctly now. Thanks!
![image](https://github.com/tteck/Proxmox/assets/77821967/98b5676b-37dd-47f0-ae62-d90310e90a3f)
