### ISSUE TITLE
NPM upgrade to 2.11.0 fails

### ISSUE THREAD

**Issue by jl-678** [tteck/Proxmox#2362]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am running NPM based on your script with 2.10.4 and everything works great. I just got an alert that 2.11.0 was released and went through your standard upgrade process. Unfortunately, it fails and NPM stops working. A rollback fixed it.

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Here is the output from the script:

 ✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.11.0
 ✓ Setup Enviroment
 - Building Frontend  \
[ERROR] in line 139: exit code 0: while executing command yarn install --network-timeout=30000 &> /dev/null

### Please provide detailed steps to reproduce the issue.

Try to upgrade from 2.10.4...

**Comment by klaasnicolaas** [comment]
![image](https://github.com/tteck/Proxmox/assets/20448157/f9f3815e-0e16-436c-a970-107cff68d563)

This may have to do with an outdated version of node that is still in use 🤔

**Comment by klaasnicolaas** [comment]
I just removed the `&>/dev/null` to see what actually happens and at first it seems to break down with an interactive selection menu that you wouldn't normally get.

![image](https://github.com/tteck/Proxmox/assets/20448157/372e7ab5-5c5a-4414-a5ca-b3b275ffeccd)

**Comment by tteck** [comment]
Why not just run the script in verbose mode?

**Comment by klaasnicolaas** [comment]
Because I don't see that documented anywhere 😅 Choose version `10.5.2` and your NPM will be up and running again in no time. What I just find strange is that if your update fails, sass-loader is changed to `"^12.11.0"` (inside package.json), a version that does not exist.

**Comment by tteck** [comment]
verbose mode is in Advanced settings

**Comment by tteck** [comment]
> Choose version 10.5.2 and your NPM will be up and running again in no time. 

The GUI will not load

**Comment by klaasnicolaas** [comment]
> verbose mode is in Advanced settings

Is this also possible with existing LXC containers? Because I debugged in my existing container.

> The GUI will not load

Do you have any errors? Because for me it works again without any problems.
