### ISSUE TITLE
Bad Gateway after NPM upgrade from 2.10.4 to 2.11.0

### ISSUE THREAD

**Issue by roswitina** [tteck/Proxmox#2365]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have updated my version of NPM 2.10.4 to version NPM 2.11.0 using the script provided. Everything went through without errors.
When I tried to log in, I got the following error message: Bad Gateway

I am back to NPM 2.10.4 for the time being.

<img width="574" alt="Screenshot 2024-01-19 153036" src="https://github.com/tteck/Proxmox/assets/2253471/1fa82f9d-89f4-45c6-9bc3-8731514132d9">

Which log files can I supply?

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Starting the script

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"

and wait until it has run through without errors.

**Comment by tteck** [comment]
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one. 

I currently don't use NPM, so when I create a new LXC, it's already up to date. However, the update process doesn't result in a "Bad Gateway" situation for me. If you had raised this issue in https://github.com/tteck/Proxmox/issues/2362, perhaps others would have shared their experiences with updating.

**Comment by tteck** [comment]
Have you rebooted the LXC after the update?

**Comment by roswitina** [comment]
The container itself was updated before the script was executed. The script was then executed. There was no error message. The container was then restarted.

Nevertheless, I could not log in. The Bad Gateway error message remained.

**Comment by roswitina** [comment]
Installing version 2.11.0 also works for me without any problems.

I'll stick with version 2.10.4 for the time being, thank you.

**Comment by roswitina** [comment]
from NPM Github Page --> Bad Gateway
 
[Upgrading from 2.10.4 to 2.11.0 causes 502 for API endpoints #3473 ](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3473)

**Comment by roswitina** [comment]
Everything works perfectly with version 2.11.1.
