### ISSUE TITLE
Proxmox VE Monitor-All starts messes up with boot order options

### ISSUE THREAD

**Issue by sammy708** [tteck/Proxmox#2369]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Good morning, just noticed after a PVE reboot, that the monitor-all service starts a not running VM right at the beginning, although according to boot order option one may want postpone the start of a VM for some time. E.g. boot homeassistant some minutes after startup of Maria DB.
Any idea how to configure a initial waiting time, until the monitor-all service starts monitoring the VMs/Containers?
Thanks and take care! Sam

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

Reboot PVE and observe var/log/ping-instances.log for VMs getting started although according to boot delay they shouldn’t yet.

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

Moving to Discussions.
