### ISSUE TITLE
Problem with haos script - Error with line 415

### ISSUE THREAD

**Issue by Paulingo93** [tteck/Proxmox#2372]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello, I tried installing haos with your script, got error with both default and advanced settings, error code is this:

![Snimka zaslona 2024-01-20 182449](https://github.com/tteck/Proxmox/assets/153704878/b5cf049c-eaf6-42d8-8c4f-1009f6da3302)

Any ideas?

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
It seems that you're facing a network problem, _probably_ linked to DNS.

**Comment by Paulingo93** [comment]
yea, my dns was 127.0.0.1

sorry to bother you, works fine now! thank you for that awesome script.
