### ISSUE TITLE
Error is script Wireguard

### ISSUE THREAD

**Issue by Plaatjesdraaier** [tteck/Proxmox#2377]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When istalling the Wireguard script a error mesaage accurs :
[ERROR] in line 40: exit code 0: while executing command $STD bash <(curl -fsSL https://install.pivpn.io) --unattended options.conf

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![error](https://github.com/tteck/Proxmox/assets/25374760/79153b3f-143c-4681-919f-8efcfc5aabb9)

### Please provide detailed steps to reproduce the issue.

Just copied the code in the shell of proxmox. (i'm a noob)

**Comment by tteck** [comment]
> - If the default Linux distribution is not adhered to, script support will be discontinued. 

```
 _       ___           ______                     __
| |     / (_)_______  / ____/_  ______ __________/ /
| | /| / / / ___/ _ \/ / __/ / / / __ `/ ___/ __  / 
| |/ |/ / / /  /  __/ /_/ / /_/ / /_/ / /  / /_/ /  
|__/|__/_/_/   \___/\____/\__,_/\__,_/_/   \__,_/   
                                                    
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: wireguard
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Wireguard LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed WireGuard
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by Plaatjesdraaier** [comment]
![error1](https://github.com/tteck/Proxmox/assets/25374760/8586b6b2-6879-46b6-bc07-759e20c753ff)

**Comment by Plaatjesdraaier** [comment]
Ok, wil use Debian 11, Thank you !

**Comment by tteck** [comment]
Use Debian 11

**Comment by tteck** [comment]
![Screenshot 2024-01-21 8 19 21 AM](https://github.com/tteck/Proxmox/assets/21342670/b7e1cfc8-b8be-4285-8fd5-ae238dadefd3)
