### ISSUE TITLE
Agentdvr service bstall

### ISSUE THREAD

**Issue by Seqway** [tteck/Proxmox#2379]
Hello,
I installed via the helper script the agentdvr software. Works fine BUT the service is installed as agentdvr.service (small letters). This is not in line with the official docu which expects AgentDVR.service
Especially important for updates ! Its case sensitive.
Please check

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**
