### ISSUE TITLE
Change Omanda Ubuntu 18.04 to a more recent OS Version

### ISSUE THREAD

**Issue by skl283** [tteck/Proxmox#238]
Hey,

at first - @tteck you're doing a great job! 

Is it possible to update the omanda Script to a more recent OS Version? The Omanda Controller since Version 5.1.x works with Ubuntu 16.04/18.04/20.04, Debian 8/9/10

Or ist it possible to choose between 18.04/20.04 or even Debian?

br
sk

**Comment by tteck** [comment]
Why is a newer OS version needed?

**Comment by skl283** [comment]
It is not "needed" - but if i create a new lxc i'd like to have the most recent OS.

Since omada v5 the most used Docker Container from mbentley also uses 20.04. https://github.com/mbentley/docker-omada-controller

**Comment by tteck** [comment]
good enough... changed to 20.04

**Comment by tteck** [comment]
Wonder if it'd work with 22.04?

**Comment by skl283** [comment]
I Don‘t know / haven't tried it yet.
Officially it's only working with the above mentioned OS, 22.04 or Debian 11 is officially not supported :-(

**Comment by skl283** [comment]
Tested, Omada works with the new 20.04. Script.
