### ISSUE TITLE
Yunohost - /etc/resolv.conf overwritten by PVE

### ISSUE THREAD

**Issue by battosai30** [tteck/Proxmox#2380]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi,

I used Yonhost install script with success (thanks for that !)
But at some point I was not anymore able to access anything (502 errors mainly). Digging a little, Yunohost tools show a warning about /etc/resolv.conf which are not what it is supposed to be : 

![image](https://github.com/tteck/Proxmox/assets/5184702/d588e6a8-18cf-4d75-9668-5e57c72bb321)

It's in french sorry but it says that resolv.conf should be a symbolic link (I suppose Yunohost use it to mange routes in system). And when I look at it, PVE overwrite it, which is the normal behaviour in PVE (and because I restarted the CT). For now I did not succesfully restored all functionnalities but I think the issue needs to be corrected :) 

Apparently it's pretty simple to manage : 

`touch /etc/.pve-ignore.hosts
`
https://pve.proxmox.com/wiki/Linux_Container#_guest_operating_system_configuration

I did not create a pull request as I don't know how you want to "globally" manage that as it may be required by other solutions.

Regards

### Which Linux distribution are you employing?

Debian 11

**Comment by battosai30** [comment]
Ok so I think I succesfully restored all functions : 

`touch /etc/.pve-ignore.resolv.conf `=> better :) but I don't know if /etc/hosts is concerned too

And if you meet this issue, I solved it with this complete script : 

```
rm /etc/resolv.conf
touch /etc/.pve-ignore.resolv.conf 
ln -s /etc/resolvconf/run/resolv.conf /etc/resolv.conf
yunohost tools regen-conf dnsmasq
```

**Comment by tteck** [comment]
So, you're suggesting that the script should include the command `touch /etc/.pve-ignore.resolv.conf` since no modifications have been made by PVE yet (new installation).

**Comment by battosai30** [comment]
Exactly : the problem occurs when you restart the CT and PVE overwrites /etc/resolv.conf. So as long as you don't restart the CT it works, but if you do, nothing works anymore ... To prevent it you can "just" block PVE resolv.conf update
