### ISSUE TITLE
Linkwarden error on install

### ISSUE THREAD

**Issue by miguelns21** [tteck/Proxmox#2383]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Would you like to add Adminer? <y/N> 
 - Installing Linkwarden (Patience)  |
[ERROR] in line 23: exit code 0: while executing command "$@" > /dev/null 2>&1

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Captura de pantalla 2024-01-24 103958](https://github.com/tteck/Proxmox/assets/45329734/e108e84c-bd30-48d4-8d9f-63d9914406cc)

### Please provide detailed steps to reproduce the issue.

Install with:
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/linkwarden.sh)"

```

**Comment by tteck** [comment]
> - When encountering the error message [ERROR] in line 23: exit code *: while executing command "$@" > /dev/null 2>&1, make sure to run the script in verbose mode to accurately determine the underlying issue.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    __    _       __                           __
   / /   (_)___  / /___      ______ __________/ /__  ____
  / /   / / __ \/ //_/ | /| / / __ `/ ___/ __  / _ \/ __ \
 / /___/ / / / / ,<  | |/ |/ / /_/ / /  / /_/ /  __/ / / /
/_____/_/_/ /_/_/|_| |__/|__/\__,_/_/   \__,_/\___/_/ /_/

Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: linkwarden
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Linkwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Cloned Linkwarden Repository
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> 
 ✓ Installed Linkwarden
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Linkwarden should be reachable by going to the following URL.
         http://192.168.86.253:3000 
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by mikoz93** [comment]
Experiencing the same issue. It seems that Debian is not quite supported by the underlying dependencies, so it might be worth removing that option from the setup 👍

**Comment by tteck** [comment]
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by mikoz93** [comment]
> it might be worth removing that option from the setup 👍
