### ISSUE TITLE
Runtipi, Permission Denied

### ISSUE THREAD

**Issue by xekil** [tteck/Proxmox#2384]
Hello @Tteck,

Thanks for the runtipi script, however there is a problem installing it with the default settings.

Indeed, it is impossible to modify the default parameters of runtipi in the graphical interface, the following error appears:

`EACCES: permission denied, open '/runtipi/state/settings.json'`

The command chmod 777 /opt/runtipi/state/settings.json resolves the entitlement issue, but I'm not sure it's the right security solution.

An idea ? In the meantime, I will try installing the script in advanced mode to test.

THANKS.

### Please provide detailed steps to reproduce the issue.

Default install

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/runtipi.sh)"

**Comment by xekil** [comment]
same error with advanced installation

![image](https://github.com/tteck/Proxmox/assets/69087258/380e8eb9-3950-4b3f-9d88-c77b2f087ed6)

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    ____              __  _       _
   / __ \__  ______  / /_(_)___  (_)
  / /_/ / / / / __ \/ __/ / __ \/ /
 / _, _/ /_/ / / / / /_/ / /_/ / /
/_/ |_|\__,_/_/ /_/\__/_/ .___/_/
                       /_/
Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 112
Using Hostname: runtipi
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Runtipi LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.82 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Runtipi
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Runtipi should be reachable by going to the following URL.
         http://192.168.86.82  
```

**Comment by xekil** [comment]
yes yes it runs correctly, but after creating a username and password to access the graphical interface, it is not possible to modify the parameters without doing a chmod.

**Comment by tteck** [comment]
Strange, the script is using their installation method.
I would recommend `chmod 660 /opt/runtipi/state/settings.json`

**Comment by xekil** [comment]
same error with `chmod 660 /opt/runtipi/state/settings.json`

**Comment by tteck** [comment]
Looks like `chmod 666 /opt/runtipi/state/settings.json` is as safe as you can go and it still works. I'm going to look into the issue.

**Comment by xekil** [comment]
ok thank you

**Comment by xekil** [comment]
ok thank you, the command `chmod 666 /opt/runtipi/state/settings.json` works

**Comment by tteck** [comment]
The file untouched is `-rw-r--r-- 1 root root 2 Jan 25 05:43 /opt/runtipi/state/settings.json` which is 644

**Comment by xekil** [comment]
I tested `chmod 644 /opt/runtipi/state/settings.json` and it doesn't work
