### ISSUE TITLE
HA Container LXC Issue // pulling HA 2022.5.5 image ERROR 1@107

### ISSUE THREAD

**Issue by Mrdindon** [tteck/Proxmox#239]
I dont really understand where the issue comes from. Network / connectivity seams to be ok since it was able to pull docker and portainer but pulling HA failed. I tried multiple times. Any idea ?

Using Default Settings
Using CT Type Unprivileged NO DEVICE PASSTHROUGH
Using CT Password Automatic Login
Using CT ID 101
Using CT Name homeassistant
Using Disk Size 16GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using R1_1.6TB_SSD_EVO860 for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 101 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.32.50.183
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed pip3
 ✓ Installed Docker v20.10.16
 ✓ Pulled Portainer 2.13.1 Image
 ✓ Installed Portainer 2.13.1
 - Pulling Home Assistant 2022.5.5 Image...‼ ERROR 1@107 Unknown failure occured.

**Comment by Mrdindon** [comment]
when I try to install the docker manually in the ct, the process seems to hang there:
I have good networking...

docker pull homeassistant/home-assistant:stable
stable: Pulling from homeassistant/home-assistant
97518928ae5f: Pull complete 
28691efa37aa: Pull complete 
b70459a95560: Pull complete 
1759b9456f7c: Pull complete 
a6e0d7988b58: Pull complete 
ea08c5549069: Pull complete 
c58551c724c5: Pull complete 
01cb44b5b7e0: Pull complete 
34f12bd05fad: Download complete 
2c730e3aa4f2: Download complete 
a8d8fd784aab: Download complete 
e5bae439cc57: Download complete 
ba0572c64b26: Download complete 
ccebe946445e: Download complete 
8af7bd1cff26: Download complete 
e12c973863dc: Download complete 
a3c4899d076a: Download complete 
9f5717132794: Download complete 
a2019baebeca: Download complete 
953099e1aa5d: Download complete 
779cb0fbc770: Download complete 
11e8c3d3d51b: Download complete 
2c1e9c1114cf: Download complete 
8955662f689f: Pull complete 
8c5f997998df: Pull complete 
65da689cb069: Pull complete 
fd2deec51de1: Extracting  1.227kB/1.227kB
b4037be4d3f3: Download complete

**Comment by Mrdindon** [comment]
Pulling HA fills up the disk when using default disk size 16gb !
![image](https://user-images.githubusercontent.com/5002201/169646746-0ba88290-b8bb-43d2-8745-d9d0bcac52d4.png)

Installation complete if I double the disk size to 32gb.
the setup takes around 20gb to install:
![image](https://user-images.githubusercontent.com/5002201/169646867-f0c3e169-844e-4463-8bd8-efe403f7554c.png)

**Comment by tteck** [comment]
```
  _                                        _     _              _   
 | |   v3                                 (_)   | |            | |  
 | |__   ___  _ __ ___   ___  __ _ ___ ___ _ ___| |_ __ _ _ __ | |_ 
 |  _ \ / _ \|  _   _ \ / _ \/ _  / __/ __| / __| __/ _  |  _ \| __|
 | | | | (_) | | | | | |  __/ (_| \__ \__ \ \__ \ || (_| | | | | |_ 
 |_| |_|\___/|_| |_| |_|\___|\__,_|___/___/_|___/\__\__,_|_| |_|\__|

Using Default Settings
Using CT Type Unprivileged NO DEVICE PASSTHROUGH
Using CT Password Automatic Login
Using CT ID 112
Using CT Name homeassistant
Using Disk Size 16GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.64 
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed pip3
 ✓ Installed Docker v20.10.16
 ✓ Pulled Portainer 2.13.1 Image
 ✓ Installed Portainer 2.13.1
 ✓ Pulled Home Assistant 2022.5.5 Image
 ✓ Installed Home Assistant 2022.5.5
 ✓ Created Update Menu Script
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Home Assistant should be reachable by going to the following URL.
         http://192.168.86.64:8123
Portainer should be reachable by going to the following URL.
         http://192.168.86.64:9000
```
![Screenshot 2022-05-21 7 51 49 AM](https://user-images.githubusercontent.com/21342670/169650415-73f9dfad-776b-483c-9729-70d7ab9fa5ce.png)
As you can see, that isn't the results I'm getting with a fresh install using ext4 filesystem.

**Comment by Mrdindon** [comment]
That is really strange... what explain that ?
I can see the docker pull taking a lot of time and filling the disk...
The only difference with you (is it a difference) is that the lxc is stored on a zfs datastore but that should make any difference right ?

**Comment by tteck** [comment]
Never used ZFS as I prefer EXT4 for my small homelab. 
I try to follow the KISS principle. 😉
