### ISSUE TITLE
changedetection.io install script missing playwright pip 

### ISSUE THREAD

**Issue by dgtlmoon** [tteck/Proxmox#2391]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Greetings from changedetection.io!

I'm referring to this issue https://github.com/dgtlmoon/changedetection.io/issues/2132

basically the user ran some install script, but that script is missing the `pip3 install playwright` part

https://github.com/tteck/Proxmox/blob/main/ct/changedetection.sh

However it is present here

https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh

I have to admit that I know little about proxmox, but this seems to be an inconsistancy.

### Which Linux distribution are you employing?

Ubuntu 23.04

### Please provide detailed steps to reproduce the issue.

Note: I cannot confirm if this the _RIGHT_ way to install it, the other script https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh has it correct, I do not know why this user chose this "`.../ct/changedetection.sh`" script over the other one.

```
execute 'bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/changedetection.sh)"' on the changedetection LXC
rebooting the LXC
triggering a recheck of a playwright request
```

Another thing is that the application should be run with the env var `PLAYWRIGHT_DRIVER_URL=ws://localhost:3000/?stealth=1&--disable-web-security=true` so that it knows where to connect/find playwright, can this also be added to https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh ?

**Comment by dgtlmoon** [comment]
note note: `playwright` does not install/work on ARM v6/v7  and musl/alpine

https://github.com/dgtlmoon/changedetection.io/blob/d31a45d49a3d50aff4c103aee47f75c598ca3ad4/Dockerfile#L26

**Comment by tteck** [comment]
Greetings back from [Helper-Scripts](https://helper-scripts.com)! 


<h2><div align="center">Exploring the Steps Involved in an Change Detection LXC Installation</div></h2>

1) [changedetection.sh](https://github.com/tteck/Proxmox/blob/main/ct/changedetection.sh): This script collects system parameters. (Also holds the function to update the application.)
2) [build.func](https://github.com/tteck/Proxmox/blob/main/misc/build.func): Adds user settings and integrates collected information.
3) [create_lxc.sh](https://github.com/tteck/Proxmox/blob/main/ct/create_lxc.sh): Constructs the LXC container.
4) [changedetection-install.sh](https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh): Executes functions from [install.func](https://github.com/tteck/Proxmox/blob/main/misc/install.func), and installs the application.
5) [changedetection.sh](https://github.com/tteck/Proxmox/blob/main/ct/changedetection.sh) (again): To display the completion message.

The installation process uses reusable scripts: [build.func](https://github.com/tteck/Proxmox/blob/main/misc/build.func), [create_lxc.sh](https://github.com/tteck/Proxmox/blob/main/ct/create_lxc.sh), and [install.func](https://github.com/tteck/Proxmox/blob/main/misc/install.func), which are not specific to any particular application.

To gain a better understanding, focus on reviewing [changedetection-install.sh](https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh). This script contains the commands and configurations for installing and configuring Change Detection within the LXC container.

If you spot anything that is not correct, please don't hesitate to bring it to my attention.

**Comment by dgtlmoon** [comment]
@tteck thank you but that doesnt help :-)

**Comment by dgtlmoon** [comment]
@tteck the problem is that https://github.com/tteck/Proxmox/blob/main/ct/changedetection.sh is totally inconsistent with https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh

its not really something for our team to fix, i dont know why https://github.com/tteck/Proxmox/blob/main/ct/changedetection.sh is missing the playwright steps, this script shouldnt exist if there's a better recommended way (https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh) am I right?

**Comment by tteck** [comment]
The `changedetection.sh` and `changedetection-install.sh` scripts have totally different purposes as outlined in my previous post. Only the `changedetection-install.sh` is responsible for the actual Change Detection installation.

**Comment by tteck** [comment]
It takes **all 5 scripts** to create a Change Detection LXC.

**Comment by dgtlmoon** [comment]
@tteck ah my apologies, so you have some UI/usability/lack-of-clarity/bad-documentation issue if people are downloading and executing a script that is only used to _"This script collects system parameters. (Also holds the function to update the application.)",_ I believe the user should not be running that script directly, no?

**Comment by tteck** [comment]
> Another thing is that the application should be run with the env var PLAYWRIGHT_DRIVER_URL=ws://localhost:3000/?stealth=1&--disable-web-security=true so that it knows where to connect/find playwright, can this also be added

It's already incorporated 
https://github.com/tteck/Proxmox/blob/702dbc7bbaded6d4a00e60dea5ecbad33f61a05c/install/changedetection-install.sh#L125

**Comment by dgtlmoon** [comment]
As I wrote in my first post

> Note: I cannot confirm if this the RIGHT way to install it, the other script https://github.com/tteck/Proxmox/blob/main/install/changedetection-install.sh has it correct, I do not know why **this user chose** this ".../ct/changedetection.sh" script over the other one.

**Comment by tteck** [comment]
> I believe the user should not be running that script directly, no?

`changedetection.sh` is the correct script to execute to start the creation process.

**Comment by dgtlmoon** [comment]
> > I believe the user should not be running that script directly, no?
> 
> `changedetection.sh` is the correct script to execute to start the creation process.

So why is this line not being run?

https://github.com/tteck/Proxmox/blob/702dbc7bbaded6d4a00e60dea5ecbad33f61a05c/install/changedetection-install.sh#L74

**Comment by dgtlmoon** [comment]
ahhhh i think I know, `playwright` is never upgraded!! it should have been upgraded

https://github.com/tteck/Proxmox/blob/702dbc7bbaded6d4a00e60dea5ecbad33f61a05c/ct/changedetection.sh#L59

in older versions of playwright, it had the wrong API, and we changed it

**Comment by tteck** [comment]
So, the update also needs to update playwright `pip3 install playwright --upgrade`, correct?

**Comment by dgtlmoon** [comment]
https://github.com/dgtlmoon/changedetection.io/commit/d8ee5472f18c930b4e504fd4c0a9bca3caba9f1e#diff-1a79d924d1840c485238e66772391268a89c95b781d69091384cf1ea1ac146c9L155

yes that is correct

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/1597f560c7138397235dac6ca5dc54d19d96444d

**Comment by dgtlmoon** [comment]
@tteck thank you so much, so the person who reported the issue first needs to update proxmox, then update changedetection.io right?

**Comment by tteck** [comment]
When he updates via the script, everything _should_ work as intended. Thanks for your help on this!!

**Comment by dgtlmoon** [comment]
@tteck thanks to you :) have a coffee on us today :)

**Comment by navels** [comment]
Thank you both for sorting this out!
