### ISSUE TITLE
Creating TurnKey LXC not working

### ISSUE THREAD

**Issue by lpispek** [tteck/Proxmox#2397]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Running this from the console of Proxmox.
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/turnkey/turnkey.sh)"

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/64278282/e44e6500-3bea-4474-8324-5ac77669a8a4)

### Please provide detailed steps to reproduce the issue.

Just running the code from website: 

![image](https://github.com/tteck/Proxmox/assets/64278282/745a2ca0-6e1d-4421-aebb-3e9a46b70ea4)

**Comment by tteck** [comment]
No issue here:
```
 ______              __ __           __   _  _______
/_  __/_ _________  / //_/__ __ __  / /  | |/_/ ___/
 / / / // / __/ _ \/ ,< / -_) // / / /___>  </ /__
/_/  \_,_/_/ /_//_/_/|_|\__/\_, / /____/_/|_|\___/
                           /___/
[INFO] Using 'local' for template storage.
[INFO] Using 'local-lvm' for container storage.
Updating LXC template list...
Creating LXC container...
Starting LXC Container...
```
```
 ______              __ __           __   _  _______
/_  __/_ _________  / //_/__ __ __  / /  | |/_/ ___/
 / / / // / __/ _ \/ ,< / -_) // / / /___>  </ /__
/_/  \_,_/_/ /_//_/_/|_|\__/\_, / /____/_/|_|\___/
                           /___/

[INFO] LXC container '111' was successfully created, and its IP address is 192.168.86.106.

[INFO] Proceed to the LXC console to complete the setup.

[INFO] login: root
[INFO] password: s1vkkbOfXAI=
```
My _guess_ is that something is wrong with your storage.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by lpispek** [comment]
Hi, sorry but all other scripts are working with any selected storage, but this one is not.

![image](https://github.com/tteck/Proxmox/assets/64278282/a52fa3ad-c58e-474a-a7cc-cd0bc83fde15)

Ok, the script only works if it uses default storage (**local** and **local-lvm**) any different storage is not working.
