### ISSUE TITLE
login credetials an database pw for paperles-ngx

### ISSUE THREAD

**Issue by FraatTailscale** [tteck/Proxmox#2398]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

the paperlses script seem to be runnig fine, but the login credentials and database pw will not be displayed this is the output:

Creating a Paperless-ngx LXC using the above advanced settings
 ✓ Using StarGateBackup for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 305 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.xx.xx.xx
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Python3
 ✓ Installed Dependencies
 ✓ Installed OCR Dependencies
 ✓ Installed JBIG2
 ✓ Installed Paperless-ngx
 ✓ Installed Natural Language Toolkit
 ✓ Set up PostgreSQL database
Would you like to add Adminer? <y/N> y
 ✓ Installed Adminer
 ✓ Set up admin Paperless-ngx User & Password
 ✓ Created Services
 ✓ Cleaned
 ✓ Completed Successfully!

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Creating a Paperless-ngx LXC using the above advanced settings
 ✓ Using StarGateBackup for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 305 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Python3
 ✓ Installed Dependencies
 ✓ Installed OCR Dependencies
 ✓ Installed JBIG2
 ✓ Installed Paperless-ngx
 ✓ Installed Natural Language Toolkit
 ✓ Set up PostgreSQL database
Would you like to add Adminer? <y/N> y
 ✓ Installed Adminer
 ✓ Set up admin Paperless-ngx User & Password
 ✓ Created Services
 ✓ Cleaned
 ✓ Completed Successfully!

**Comment by tteck** [comment]
Read the instructions!

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
