### ISSUE TITLE
- Installing Golang  - [ERROR] in line 27

### ISSUE THREAD

**Issue by Kolyhan-Mihail** [tteck/Proxmox#2401]
- Installing Golang  -
[ERROR] in line 27: exit code 0: while executing command wget -q https://golang.org/dl/$RELEASE

**Comment by Kolyhan-Mihail** [comment]
When executing the script   "sftpgo.sh"

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**
