### ISSUE TITLE
vs code server can't

### ISSUE THREAD

**Issue by basalisco** [tteck/Proxmox#2407]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

script don't install vs code server
![image](https://github.com/tteck/Proxmox/assets/16223678/bb8e8e9e-3b62-444d-8559-0cc4a289cff4)

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
![Screenshot 2024-01-30 1 12 39 PM](https://github.com/tteck/Proxmox/assets/21342670/96f4727a-e2cf-490b-815c-df3bc292b997)
As this issue is unrelated to the script, it is considered closed.

**Comment by basalisco** [comment]
Forgive me, I missed it. thank's for your job

**Comment by zeushomeserver** [comment]
I am getting thge same error. Where can I find this LXC console @basalisco ?
