### ISSUE TITLE
Pi.Alert Error - FileNotFoundError: [Errno 2] No such file or directory: 'avahi-resolve'

### ISSUE THREAD

**Issue by sebastienhouzet** [tteck/Proxmox#2415]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installation with Verbose mode to analyse with i have error "[ERROR] in line 23: exit code *: while executing command "$@" > /dev/null 2>&1"

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Processing scan results...
\    Processing ignore list...
        Ignore list is empty
    Devices Detected.......: 45
        arp-scan Method....: 43
        Pi-hole Method.....: +0
        Fritzbox Method....: +0
        Mikrotik Method....: +0
        UniFi Method.......: +0
        New Devices........: 44

    Devices in this scan...: 1
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
|    Updating Devices Info...
        Trying to resolve devices without name...Traceback (most recent call last):
  File "/opt/pialert/back/pialert.py", line 2860, in <module>
    sys.exit(main())       
  File "/opt/pialert/back/pialert.py", line 90, in main
    res = scan_network()
  File "/opt/pialert/back/pialert.py", line 523, in scan_network
    update_devices_names()
  File "/opt/pialert/back/pialert.py", line 1315, in update_devices_names
    newName = resolve_device_name (device['dev_MAC'], device['dev_LastIP'])
  File "/opt/pialert/back/pialert.py", line 1403, in resolve_device_name
    newName = resolve_device_name_avahi(pIP)
  File "/opt/pialert/back/pialert.py", line 1357, in resolve_device_name_avahi
    newName = subprocess.run(avahi_args, capture_output=True, text=True, timeout=5)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'avahi-resolve'

[ERROR] in line 90: exit code 0: while executing command $STD python3 /opt/pialert/back/pialert.py 1
root@nuc:~# 

### Please provide detailed steps to reproduce the issue.

Copy paste script install.
Use Advance Mode to activate Verbose mode.

**Comment by tteck** [comment]
If you're using Debian 12, why does it show "`python3.9`"? 
Debian 12 utilizes `python3.11`

**Comment by tteck** [comment]
@leiweibau Looks like changes were made https://github.com/leiweibau/Pi.Alert/pull/248/commits/0b9993e0c37c3c67851d65abae2abd01fa041604 that broke the install

**Comment by leiweibau** [comment]
I didn't realize that you had to add the dependencies separately from my installation script or update script. I will pass on a note to you in the future. Sorry

**Comment by sebastienhouzet** [comment]
@leiweibau @tteck i need to make action or i need to wait a new version publish ?

**Comment by tteck** [comment]
The script has been fixed, create a new LXC.
