### ISSUE TITLE
Configure photoprism paths

### ISSUE THREAD

**Issue by rikki78** [tteck/Proxmox#242]
Is it possible to configure the paths where the photos are stored and imported? I prefer to use a NFS share mapped to a mount point, but I can't find out how to have photoprism pointing at the mount point.
Thanks

**Comment by tteck** [comment]
```
nano /var/lib/photoprism/.env
```

**Comment by rikki78** [comment]
How can I monitor the logs from such a container, similar to `docker logs`?

**Comment by divemasterjm** [comment]
> ```
> nano /var/lib/photoprism/.env
> ```

i've change .env restart service but nothing changes, is very important to modify this file cause we need to have photlibrary on nas due the amount of space needed
can you please tell me how to proceed?

**Comment by Dreanaught** [comment]
As of today the command in the lxc console is:
nano /opt/photoprism/config/.env

**Comment by tteck** [comment]
Correct
https://github.com/tteck/Proxmox/blob/6037d381ef3f061357b6d689f5fa89df26310c59/install/photoprism-install.sh#L43
