### ISSUE TITLE
Error updating Alpine containers using update-lxcs.sh

### ISSUE THREAD

**Issue by dannybouwers** [tteck/Proxmox#2420]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When using the update-lxc script, I get an error on all Alpine containers. Ubuntu containers do update as expected.

The cause and a solution appears to be reported here https://forum.proxmox.com/threads/strange-error-when-updating-alpine-packages-via-pct-command.140517/

I can confirm updating using the command ```lxc-attach -n 100 -- ash -c "apk update && apk upgrade"``` does work and manually calling ```pct exec 100 -- ash -c 'apk update && apk upgrade'``` gives the same error.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

The output is:
```  __  __          __      __          __   _  ________
  / / / /___  ____/ /___ _/ /____     / /  | |/ / ____/
 / / / / __ \/ __  / __ `/ __/ _ \   / /   |   / /
/ /_/ / /_/ / /_/ / /_/ / /_/  __/  / /___/   / /___
\____/ .___/\__,_/\__,_/\__/\___/  /_____/_/|_\____/
    /_/

[Info] Updating 100 : xxx - [No disk info for alpine]

fetch https://dl-4.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
WARNING: updating https://dl-4.alpinelinux.org/alpine/latest-stable/main: Permission denied
fetch https://dl-4.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(/usr/lib/ssl/certs)
086BC36C7F7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
WARNING: updating https://dl-4.alpinelinux.org/alpine/latest-stable/community: Permission denied
v3.19.1-29-g9631b024a8f [https://dl-4.alpinelinux.org/alpine/latest-stable/main]
v3.19.1-32-g82251c2e6da [https://dl-4.alpinelinux.org/alpine/latest-stable/community]
0 unavailable, 2 stale; 22988 distinct packages available
```

### Please provide detailed steps to reproduce the issue.

I run the script using the provided command via an SSH shell ```bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/update-lxcs.sh)"```.

Promox: Virtual Environment 8.1.4 (unlicensed)
User: root.
Client OS: MacOS 14.2.1 
Terminal: MacOD default (Version 2.14 (452))

**Comment by tteck** [comment]
What is the output of `cat /etc/apk/repositories`?

**Comment by tteck** [comment]
Alpine LXCs update as expected using the Proxmox VE LXC Updater script on this end.

**Comment by dannybouwers** [comment]
> What is the output of `cat /etc/apk/repositories`?

```
root@pve:~# lxc-attach -n 112 -- ash -c "cat /etc/apk/repositories"
https://dl-4.alpinelinux.org/alpine/latest-stable/main
https://dl-4.alpinelinux.org/alpine/latest-stable/community
```

**Comment by tteck** [comment]
Where did you get those repositories?
```
alpine-docker:~# cat /etc/apk/repositories
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
```

**Comment by tteck** [comment]
Change your repositories to the ones I showed above, then execute the Proxmox VE LXC Updater script.

**Comment by dannybouwers** [comment]
Changing the repositories to yours fixed the problem.

```
lxc-attach -n 100 -- ash -c "sed -i 's/https/http/g' /etc/apk/repositories"
lxc-attach -n 100 -- ash -c "sed -i 's/dl-4/dl-cdn/g' /etc/apk/repositories"
```

**Comment by dannybouwers** [comment]
I don't know how the repositories got as they were. I haven't set them consciously...

**Comment by tteck** [comment]
Something changed them 🤷🏻‍♂️ 
https://github.com/tteck/Proxmox/blob/f4b7aa6e4d5b8f0770536b503259cc1d5d645229/misc/build.func#L576-L579

**Comment by dannybouwers** [comment]
Problem solved, but still strange the functionality of the update script is dependent on the used repositories. Especially since the containers do update using other methods...

**Comment by dannybouwers** [comment]
> Something changed them 🤷🏻‍♂️
> 
> https://github.com/tteck/Proxmox/blob/f4b7aa6e4d5b8f0770536b503259cc1d5d645229/misc/build.func#L576-L579

I didn't create the containers using one of your scripts. Manually created then using one of my own templates... Think it's time for an update 😉
