### ISSUE TITLE
dockge-install.sh immich 

### ISSUE THREAD

**Issue by Buksa** [tteck/Proxmox#2423]
https://github.com/tteck/Proxmox/blob/f4b7aa6e4d5b8f0770536b503259cc1d5d645229/install/dockge-install.sh#L56
looks like has wrong link they made changes in [v1.94.0](https://github.com/immich-app/immich/releases/tag/v1.94.0)
https://github.com/immich-app/immich/releases/download/v1.94.1/hwaccel.ml.yml

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**
