### ISSUE TITLE
hyperion wont start after installation with script

### ISSUE THREAD

**Issue by Blackspell01** [tteck/Proxmox#2430]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I just ran the script and chose the default installation. 
For some reason I can't access the web server through port 8090.
hyperion doesn't seem to be running

Im sorry if I have overseen something important

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="1500" alt="Bildschirmfoto 2024-02-04 um 23 33 59" src="https://github.com/tteck/Proxmox/assets/65290701/b413dd9f-6cbc-43d3-8257-323039ed4a68">
<img width="1495" alt="Bildschirmfoto 2024-02-04 um 23 35 43" src="https://github.com/tteck/Proxmox/assets/65290701/bfc4032b-007d-4ad3-af9b-893b141af412">

**Comment by tteck** [comment]
Fixed
