### ISSUE TITLE
Latest Nginx Proxy Manager broken

### ISSUE THREAD

**Issue by jngutierrez** [tteck/Proxmox#2431]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The latest Nginx Proxy Manager version has a lot of bugs. Please update script to latest NPM stable version - v2.10.4

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

Install NPM using Helper Script. Add a proxy Host and finally add a custom location, which breaks the config file and proxy host becomes offline

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
> - If the default Linux distribution is not adhered to, script support will be discontinued.
