### ISSUE TITLE
Wrong defaults for vaultwarden-v3.sh ?

### ISSUE THREAD

**Issue by schiz0phr3ne** [tteck/Proxmox#244]
Hi @tteck,

Is it normal that [vaultwarden-v3.sh](https://github.com/tteck/Proxmox/blob/95096cc89c2dffb4461f3a85a40ecbf5dd5ac963/ct/vaultwarden-v3.sh) have other default settings that written on our website ?

**vaultwarden-v3.sh** :
```
[...]
echo -e "${DGN}Using Disk Size ${BGN}8${CL}${DGN}GB${CL}"
DISK_SIZE="8"
echo -e "${DGN}Using ${BGN}4${CL}${DGN}vCPU${CL}"
CORE_COUNT="4"
echo -e "${DGN}Using ${BGN}4096${CL}${DGN}MiB RAM${CL}"
RAM_SIZE="4096"
[...]
```

**Website** :
```
[...]
⚡ Normal Settings: 512Mib RAM - 8GB Storage - 1vCPU ⚡
[...]
```

I actually have a VM for Vaultwarden (Debian 11, docker (vaultwarden, portainer, watchtower) which runs great with 1vCPU and 1Gib RAM, so maybe there is an error in script rather than website.

I created PR #243.

**Comment by tteck** [comment]
As stated right above normal settings "It builds from source, which takes time and resources. After the installation, resources can be set to Normal Settings."

**Comment by schiz0phr3ne** [comment]
Oh... I'm feeling silly.
Sorry for this :(
