### ISSUE TITLE
Issue while upgrading Nginx Proxy Manager

### ISSUE THREAD

**Issue by mateuszmalek** [tteck/Proxmox#2441]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I've tried to update the Debian 12 LXC on my Proxmox using `update` alias as well as running `bash & wget` combination command and was unable to update NPM. The installation was unusable (services were not starting up) and I've needed to perform a restore from backup.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/13499892/5e9af490-9d49-49f9-a60d-89ae8d03bf80)

### Please provide detailed steps to reproduce the issue.

1. Open Nginx Proxy Manager LXC console inside Proxmox
2. Run `update` or `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"`
3. Select "Yes" to confirm update
4. The error occurs.

**Comment by tteck** [comment]
fixed

**Comment by mateuszmalek** [comment]
Confirmed, thank you!
