### ISSUE TITLE
Update Adguard LXC container

### ISSUE THREAD

**Issue by svanimpelen** [tteck/Proxmox#2456]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I tried updating the Adguard Home LXC using the instruction, by running the command update within the console of the container. 
However I get an error message:

 ✓ Stopped AdguardHome
 - Updating AdguardHome  /
[ERROR] in line 65: exit code 0: while executing command tar -xvf AdGuardHome_linux_amd64.tar.gz &> /dev/null

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

https://tteck.github.io/Proxmox/
search for Adguard.

### Please provide detailed steps to reproduce the issue.

Type command 'update' within the console of the container.

**Comment by tteck** [comment]
The only time you should manually update Adguard Home is when you're instructed to in the GUI. Anyway, I just tested the manual update:
```
    ___       __                           __
   /   | ____/ /___ ___  ______ __________/ /
  / /| |/ __  / __  / / / / __  / ___/ __  / 
 / ___ / /_/ / /_/ / /_/ / /_/ / /  / /_/ /  
/_/  |_\__,_/\__, /\__,_/\__,_/_/   \__,_/   
            /____/                           
 
 ✓ Stopped AdguardHome
 ✓ Updated AdguardHome
 ✓ Started AdguardHome
 ✓ Cleaned
 ✓ Updated Successfully
root@adguard:~# 
```
The script runs without any problems from this end.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by svanimpelen** [comment]
The issue was that the bootdisk was too small. Increasing it to 3G solved the issue. Now need to figure out why its increasing.
