### ISSUE TITLE
Update of Vaultwarden

### ISSUE THREAD

**Issue by ordo01** [tteck/Proxmox#2459]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I tried to use the script `bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"` to update my vaultwarden instance which I created earlier using the same script.
Even though I can see an update function in the script, I did not get presented with the option to update my existing instance.
Is there anything I am missing for updating vaultwarden using the script?

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

I used [](bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)") in the proxmox console.

**Comment by tteck** [comment]
The update function is there
https://github.com/tteck/Proxmox/blob/c0856c0d0c5ca18aecfab7a4788501ee03e4d53e/ct/alpine-vaultwarden.sh#L56-L76
Albeit it's just an `apk update && apk upgrade` because alpine-vaultwarden updates via the **A**lpine **P**ackage **K**eeper

**Comment by ordo01** [comment]
I do see that the update function is in the script. My point is, that running the script I do not get an option presented to update but only to install a new container.

**Comment by tteck** [comment]
Apparently, you have not read the instructions.

![Screenshot 2024-02-09 8 43 35 AM](https://github.com/tteck/Proxmox/assets/21342670/9846e412-1a90-484f-8027-952fe50cb67a)

**Comment by tteck** [comment]
> Which Linux distribution are you employing?
Debian 12

Details matter

As this issue is unrelated to the script, it is considered closed.

**Comment by ordo01** [comment]
Thanks a lot for your prompt response. I did overlook the last line to run it in the container.
