### ISSUE TITLE
Adguard Home upgrade failed due to lack of disk space

### ISSUE THREAD

**Issue by petervk** [tteck/Proxmox#2462]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I tried to update my adguard lxc and it failed because I didn't have enough disk space. I had to manually restart the service, increase the size of the boot disk, and then the "update" command wouldn't work (it failed silently) until I re-downloaded the script again.

Can you put in a check in the script to validate there is sufficient disk space before attempting to upgrade? Maybe also have the script offer to resize the boot disk for you if that is possible?

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Let your adguard home LXC basically run out of space
Try to upgrade adguard using the "update" command
It will fail at some point and you will be left with no DNS until you manually restart the adguard home service using systemctl.

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by petervk** [comment]
Isn't this a bug with the script? It didn't warn me that I needed more space to do this and it failed in a way that could be hard to troubleshoot. I was able to get my system working again but I feel this isn't merely a feature request.

**Comment by tteck** [comment]
A bug? **NO**. I think that it's your responsibility to be aware of your storage requirements. Besides, if you utilize the Proxmox VE LXC Updater script, it shows disk information.

**Comment by tteck** [comment]
fixed
