### ISSUE TITLE
[n8n] installation script fails during `npm install --global n8n`

### ISSUE THREAD

**Issue by idbartosz** [tteck/Proxmox#2465]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installation script ` bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/n8n.sh)"` fails during `npm install --global n8n` step, and in consequence a non functional container is created.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Zrzut ekranu 2024-02-10 170142](https://github.com/tteck/Proxmox/assets/21260478/c80ab320-fafa-4e4c-ba20-368382367ec0)

### Please provide detailed steps to reproduce the issue.

Steps to reproduce:
1. Create a fresh installation of n8n with use of ` bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/n8n.sh)"`
2. Wait till the end of  `npm install --global n8n`
3. Installation script fails, and a non fumctional container is created

**Comment by JamesSimpson** [comment]
I was just about to post the exact same thing.
