### ISSUE TITLE
Feature Request - ActivePieces

### ISSUE THREAD

**Issue by JamesSimpson** [tteck/Proxmox#2467]
Hey Guys,

Saw the n8n container, and works great - what about getting ActivePeices ported into a single install too? Much like n8n, but feel that this one is a little bit better in some instances. 

https://github.com/activepieces/activepieces

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
