### ISSUE TITLE
Idea. Make script that increase swap

### ISSUE THREAD

**Issue by Serhioromano** [tteck/Proxmox#2476]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Default swap size in only 8Gb and it is full very fast. I increased it to 32Gb but that was an adventure. I immediately remembered you. that would be nice to have a script to increase a size of swap.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

https://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by Serhioromano** [comment]
You have no place for feature requests.
