### ISSUE TITLE
post-pve-install script doesn't run

### ISSUE THREAD

**Issue by dreed47** [tteck/Proxmox#2480]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I new/clean install of proxmox 8.1.4.  When I try to run the post-pve-install script it does nothing, just returns to the prompt.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
It seems that you're facing a network problem, _probably_ linked to DNS.

**Comment by dreed47** [comment]
yep, you're correct, a DNS issue.  Thanks

**Comment by michelececcacci** [comment]
In my case i fixed it by running `apt install whiptail`

**Comment by eblucas** [comment]
I'm having the same problem, how did you know it was DNS issue and how to fix? Thank you
