### ISSUE TITLE
unable SSH as root with Ubuntu 22.04 cloud VM with SSH script run

### ISSUE THREAD

**Issue by shreddeddonut** [tteck/Proxmox#2483]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Existing 22.04 cloud VM working fine, created a new VM using the Ubuntu 22.04 VM script and configured correctly as per the guide. Ran the 'Get SSH Going' script and rebooted - getting 'permission denied (public key)' when attempting to SSH from a new client. Cleared keys, tried fresh PC that has never SSH'd before with no success. 

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
Did you try this solution https://github.com/tteck/Proxmox/discussions/2072#discussioncomment-8269708

**Comment by shreddeddonut** [comment]
Hey, I did try this late last night which did not correct itself unfortunately. After spending time on it this morning, I have renamed the `60-cloudimg-settings.conf` to `60-cloudimg-settings.conf.bak`. Following a reboot I was able to successfully SSH to the VM as root user. 

Thanks for your quick response.
