### ISSUE TITLE
Ceph version overwritten in PVE 8.1 (quincy vs reef)

### ISSUE THREAD

**Issue by mcgarrah** [tteck/Proxmox#2484]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Ceph version is over written with hardwired "quincy" at lines: 
https://github.com/tteck/Proxmox/blob/main/misc/post-pve-install.sh#L109-L110

With PVE 8.1 we have the option to install "reef" which then has to be manually changed back.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

My apt sources for Ceph were overwritten with quincy vs reef by the "Proxmox VE Post Install" script. I had to manually correct it after the execution.

```
# cat /etc/apt/sources.list.d/ceph.list 
deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
```

### Please provide detailed steps to reproduce the issue.

Running the "Proxmox VE Post Install"
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"
```

Overwrites the Ceph Reef with Quincy in the apt ceph.list file. The lines of code are found at https://github.com/tteck/Proxmox/blob/main/misc/post-pve-install.sh#L109-L110.

I'm trying to think thru how to fix the script so it can detect if the entry already has "quincy" or "reef" or a future codename for the Ceph install and change just the enterprise to no-subscription.

**Comment by tteck** [comment]
What if I add both Quincy and Reef, both initially disabled, so that the user can choose which one they prefer to enable?

**Comment by tteck** [comment]
![Screenshot 2024-02-13 5 38 02 AM](https://github.com/tteck/Proxmox/assets/21342670/c18635b0-125e-419e-b8de-94df9e716052)
