### ISSUE TITLE
zigbee2mqtt lxc - read only file system for configuration yaml

### ISSUE THREAD

**Issue by MIsegrim** [tteck/Proxmox#2485]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

hello,
im trying to use zigbee2mqtt as lxc using the script for the debian install, so far so good. editing the configuration.yaml fails due permission error. any suggestions or ideas?

![Screenshot 2024-02-13 133552](https://github.com/tteck/Proxmox/assets/77529418/b676c167-7756-4c8d-a1f0-f59e2d2c5cd8)

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
Try this command `chmod u+rw /opt/zigbee2mqtt/data/configuration.yaml`

> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by tteck** [comment]
BTW, I just tested a fresh Debian 11 Zigbee2MQTT install, I don't have any permission issues.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
