### ISSUE TITLE
Scrypted with debian/tensorflow-lite

### ISSUE THREAD

**Issue by mnestor** [tteck/Proxmox#2488]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Debian doesn't like to have python 3.9 installed which is required for tensorflow-lite plugin in scrypted. 

Perhaps a warning should be shown on creation that if you plan to use tensorflow-lite for a coral or something you should not pick debian to install with? Unless you want to have a very bad time. 

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
👍🏻 Sounds like the tensorflow-lite plugin needs updated.

**Comment by mnestor** [comment]
I figured it might be a smidge easier to convince you to add a note vs adding my upvote into the ocean of users trying to get Google to update it.

**Comment by koush** [comment]
Tensorflow lite plugin can't be updated to support newer pythons because the hard dependency is in Google's libraries.
