### ISSUE TITLE
paperless-ngx not importing documents

### ISSUE THREAD

**Issue by joaofgf** [tteck/Proxmox#2491]
### Discussed in https://github.com/tteck/Proxmox/discussions/2490

<div type='discussions-op-text'>

<sup>Originally posted by **joaofgf** February 14, 2024</sup>
After updating or installing the current available version, the paperless-ngx app does not import documents and returns the error: `MissingDependencyError: gs`</div>

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

**Comment by joaofgf** [comment]
ill just install the docker version.
