### ISSUE TITLE
Overseerr script - yarn - ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by wetfox** [tteck/Proxmox#2492]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Thank you so much for all of your scripts. I'm a bit of my depth here but learning a lot.
I have a problem with using the automated script for overseerr, ESOCKETTIMEDOUT when in the process of installing yarn.

I have found some threads on the net suggestion increasing the timeout buffer but I have no idea where to add that. First time using Proxmox /Linux
https://stackoverflow.com/questions/55845756/esockettimedout-error-while-yarn-install-command

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

✔ Installed Yarn
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying... info There appears to be trouble with your network connection. Retrying.. info There appears to be trouble with your network connection. Retrying... info There appears to be trouble with your network connection. Retrying... info There appears to be trouble with your network connection. Retrying. info There appears to be trouble with your network connection. Retrying. info There appears to be trouble with your network connection. Retrying.. info There appears to be trouble with your network connection. Retrying...
error Error: https://registry.yarnpkg.com/date-fns/-/date-fns-2.29.3.tgz: ESOCKETTIMEDOUT at
ClientRequest.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:141501:19)
at Object.onceWrapper (node: events:632:28)
at ClientRequest.emit (node:events:518:28)
at TLSSocket.emitRequestTimeout (node:_http_client:840:9)
at Object.onceWrapper (node:events:632:28)
at TLSSocket.emit (node: events: 530:35)
at Socket._onTimeout (node:net:589:8)
at listOnTimeout (node: internal/timers: 573:17)
at process.processTimers (node: internal/timers: 514:7)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ERROR] in line 43: exit code 0: while executing command $STD yarn install

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/overseerr.sh)"

**Comment by wetfox** [comment]
![Screenshot_8](https://github.com/tteck/Proxmox/assets/45440363/64fbefdb-a7e3-4f64-b9c4-01e81fc7ce61)

**Comment by tteck** [comment]
The script runs without any problems from this end.

```
   ____
  / __ \_   _____  _____________  ___  __________
 / / / / | / / _ \/ ___/ ___/ _ \/ _ \/ ___/ ___/
/ /_/ /| |/ /  __/ /  (__  )  __/  __/ /  / /
\____/ |___/\___/_/  /____/\___/\___/_/  /_/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: overseerr
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Overseerr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Installed Overseerr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Overseerr should be reachable by going to the following URL.
         http://192.168.86.250:5055 
```
The error states "There appears to be trouble with your network connection."

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
