### ISSUE TITLE
Problem with updating plex from command update

### ISSUE THREAD

**Issue by platini76** [tteck/Proxmox#2493]
[ERROR] in line 72: exit code 0: while executing command bash -c "$(wget -qO - https://raw.githubusercontent.com/mrworf/plexupdate/master/extras/installer.sh)"

this is the error... can you please help me?

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**
