### ISSUE TITLE
After Update: "Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.23"

### ISSUE THREAD

**Issue by seneca13** [tteck/Proxmox#2496]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

grocy LXC" 4.0.x ( Installed by Proxmox Helper Scripts)

did an update with the  Proxmox Helper Scripts
it ran throgh with no Problems, quite quick

But when trying to reach the web frontend of grocy it says:
**Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.23**

Tried to install a new LXC, to make sure it's a update only problem:
New LXC works just fine. 

Could You please change the script for the update?
How can I restore the backup, made automatically during the update?

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![grocy-update](https://github.com/tteck/Proxmox/assets/111911896/c8370a80-463f-4e5b-b503-dfd51ffb5e7e)

### Please provide detailed steps to reproduce the issue.

perform an Update of grocy LXC (4.0.x)

**Comment by seneca13** [comment]
I read the closed issue:
**#2463  Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.27** 
https://github.com/tteck/Proxmox/issues/2463

The Script works just fine, when installing a **new** grocy lxc

But as I wrote in the opening thread: 
There still is a problem when doing an update of an version lower 4.1

**Comment by tteck** [comment]
Fixed. It will now update PHP to version 8.3

**Comment by seneca13** [comment]
Big Thnx!

It works, partially
(in the first attempt it couldn't install PHP 8.3, because the packages were outdated, needed to do "apt-get update" first and start the script again)

Now PHP is VersionPHP 8.3.2-1
But still grocy is not reachable:
"Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.23"

**Comment by seneca13** [comment]
NOPE!

now:
PHP 8.2.15 (cli) (built: Jan 20 2024 14:14:18) (NTS)

but still (after 2 reboots):
Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.27

**Comment by mikemathewson** [comment]
The issue is that Apache is not updated to use the new PHP version. The following fixed it for me:

```
sudo apt install libapache2-mod-php8.3
sudo a2dismod php8.1
sudo a2enmod php8.3
sudo systemctl restart apache2
```
