### ISSUE TITLE
Can't install openvault-media LXC

### ISSUE THREAD

**Issue by kirush0280** [tteck/Proxmox#2499]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Cant install LXC with openmedia-vault

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 ✓ Installed Dependencies
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org bookworm-security InRelease                                             
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease                                            
Get:4 https://packages.openmediavault.org/public shaitan InRelease [12.8 kB]       
Get:5 https://packages.openmediavault.org/public shaitan/main amd64 Packages [13.6 kB]
Fetched 26.4 kB in 1s (31.5 kB/s)  
Reading package lists... Done
|
[ERROR] in line 42: exit code 0: while executing command apt-get -y --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault &> /dev/null

root@nas:~# apt-get -y --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package openmediavault-keyring
E: Unable to locate package openmediavault

**Comment by ghost** [comment]
https://github.com/tteck/Proxmox/issues/1823#issuecomment-1732198389

**Comment by tteck** [comment]
> - If the default Linux distribution is not adhered to, script support will be discontinued.
