### ISSUE TITLE
Login Details

### ISSUE THREAD

**Issue by B08Z** [tteck/Proxmox#25]
First off, thanks very mcuh for these scripts. 
I had set every thing up in docker on VMs but knew that there must be a better way. 

I have set up HA and MQTT no issues 
However zigbee2mqtt is asking for a username and password.
I have tried the default Debian and it does not seem to work.

**Comment by tteck** [comment]
If it's asking for a username and password, the script never finished. Remove the LXC, and re-run the script.

**Comment by B08Z** [comment]
Done....thank you very much for the quick response!

IAW
