### ISSUE TITLE
Paperless-NGX LXC

### ISSUE THREAD

**Issue by coolduke666** [tteck/Proxmox#2500]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Error on PDF import "MissingDependencyError: gs"

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

after updating to the latest version - PDF import drops the following error "MissingDependencyError: gs"

**Comment by tteck** [comment]
Which Linux distribution are you employing?

**Comment by coolduke666** [comment]
debian 11... I already found out, that I have to upgrade to debian 12 in order got the newer ghostscript version.

Nonetheless it would be nice, if your update-script will update the OS as well.

Otherwise great work - love your scripts!

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/1498

**Comment by coolduke666** [comment]
FYI...
- update to debian 12 worked like a charm
- but paperless-ngx didn't start
- after reappliying your update script everythings works fine (and all data are still available)
