### ISSUE TITLE
unable to locate packages while installing linkwarden via script 

### ISSUE THREAD

**Issue by protonaut** [tteck/Proxmox#2502]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The problem remains with and without adding Adminer during the installation of the script.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libjpeg-turbo8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

Package xfonts-cyrillic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-unifont' has no installation candidate
E: Package 'xfonts-cyrillic' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libx264-155
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
E: Package 'libjpeg-turbo8' has no installation candidate
E: Unable to locate package libvpx6
E: Unable to locate package libwebp6
Failed to install browser dependencies
Error: Installation process exited with code: 100
\
[ERROR] in line 74: exit code 0: while executing command $STD npx playwright install-deps

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/linkwarden.sh)"

**Comment by tteck** [comment]
> - If the default Linux distribution is not adhered to, script support will be discontinued.

```
    __    _       __                           __
   / /   (_)___  / /___      ______ __________/ /__  ____
  / /   / / __ \/ //_/ | /| / / __ `/ ___/ __  / _ \/ __ \
 / /___/ / / / / ,<  | |/ |/ / /_/ / /  / /_/ /  __/ / / /
/_____/_/_/ /_/_/|_| |__/|__/\__,_/_/   \__,_/\___/_/ /_/

Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: linkwarden
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Linkwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Cloned Linkwarden Repository
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> 
 ✓ Installed Linkwarden
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Linkwarden should be reachable by going to the following URL.
         http://192.168.86.250:3000 
```

**Comment by protonaut** [comment]
Thanks for the response. I just tipped the "Enter" some times and ended with debian 11 which is not supported anymore. Switched to ubuntu 22.04 and it works like a charm.
