### ISSUE TITLE
still: After Update:  "Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.23"

### ISSUE THREAD

**Issue by seneca13** [tteck/Proxmox#2504]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Problem ist still not solved completly:

https://github.com/tteck/Proxmox/issues/2496
> Fixed. It will now update PHP to version 8.3

PHP 8.3.2-1 is running, indeed,
but still grocy is not:
When trying to open the grocy frontend there is still the same message:
"Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.27"
(although PHP 8.3.2-1 is running)

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

perform an Update of grocy LXC (4.0.x)
(Restarts don't change a thing)

**Comment by tteck** [comment]
What is the output when executing `php -v` ?

**Comment by seneca13** [comment]
![grocy-update](https://github.com/tteck/Proxmox/assets/111911896/7090743e-0626-4256-bc2c-89efed89ee1d)

**Comment by seneca13** [comment]
![grocy-php](https://github.com/tteck/Proxmox/assets/111911896/7eacc28e-fb74-45ac-9302-15c36bd592d0)

**Comment by tteck** [comment]
Have you tried rebooting the container?

**Comment by seneca13** [comment]
Yes, multiple times!
No change...

**Comment by tteck** [comment]
Try this:

```
apt-get update
apt-get install -y php8.2
apt-get install -y libapache2-mod-php8.2
apt-get install -y php8.2-sqlite3
apt-get install -y php8.2-gd
apt-get install -y php8.2-intl
apt-get install -y php8.2-mbstring
update-alternatives --set php /usr/bin/php8.2
```

**Comment by tteck** [comment]
Well?

**Comment by seneca13** [comment]
NOPE!

now:
PHP 8.2.15 (cli) (built: Jan 20 2024 14:14:18) (NTS)

but still (after 2 reboots):
Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.27

**Comment by tteck** [comment]
I have no idea then, the script is doing what it's designed to do. 
I would suggest creating a new grocy LXC.

**Comment by seneca13** [comment]
Is there a way to roll back to the previous version?
This way I could at least see my datas again.

**Comment by tteck** [comment]
restore a backup

**Comment by seneca13** [comment]
How do I restore a backup?

**Comment by tteck** [comment]
My primary focus revolves around the development of application LXCs, and I'm not specialized in providing support for operational issues that may arise with these applications.

Looks like you need to do some Googling for "Proxmox how to's"

As I believe this issue is unrelated to the script, it is considered closed.

**Comment by DirkTas67** [comment]
Had this problem too, I just reinstalled Grocy, probably not the best solution but it works again.

**Comment by mikemathewson** [comment]
The issue is that Apache is not updated to use the new PHP version. The following fixed it for me:

```
sudo apt install libapache2-mod-php8.3
sudo a2dismod php8.1
sudo a2enmod php8.3
sudo systemctl restart apache2
```
