### ISSUE TITLE
update script for changedetection not work

### ISSUE THREAD

**Issue by githubaobab** [tteck/Proxmox#2507]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi,
The lastest version when i use the script upgrade [ bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/changedetection.sh)" ] in the lxc container = 0.45.9
The lastest version from github = 0.45.14
https://github.com/dgtlmoon/changedetection.io/releases
How can i upgrade the app ?
thx

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

pip3 install changedetection.io --upgrade

Requirement already satisfied: changedetection.io in /usr/local/lib/python3.9/dist-packages (0.45.9)
Collecting changedetection.io
Using cached changedetection.io-0.45.9-py3-none-any.whl (682 kB)
Using cached changedetection.io-0.45.8.1-py3-none-any.whl (682 kB)
Requirement already satisfied: flask-compress in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.13)
Requirement already satisfied: brotli~=1.0 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.0.9)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (3.1.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (2022.7.1)
Requirement already satisfied: jinja2-time in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (0.2.0)
Requirement already satisfied: jsonpath-ng~=1.5.3 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.5.3)
Requirement already satisfied: urllib3>1.26 in /usr/lib/python3/dist-packages (from changedetection.io) (1.26.5)
Requirement already satisfied: paho-mqtt in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.6.1)
Requirement already satisfied: validators~=0.21 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (0.22.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (4.9.2)
Requirement already satisfied: flask-restful in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (0.3.9)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (2.28.2)
Requirement already satisfied: jinja2~=3.1 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (3.1.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (4.11.2)
Requirement already satisfied: apprise~=1.6.0 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.6.0)
Requirement already satisfied: feedgen~=0.9 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (0.9.0)
Requirement already satisfied: timeago~=1.0 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.0.16)
Requirement already satisfied: dnspython~=2.4 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (2.4.2)
Requirement already satisfied: pytest-flask~=1.2 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.2.0)
Requirement already satisfied: jsonschema==4.17.3 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (4.17.3)
Requirement already satisfied: chardet>2.3.0 in /usr/lib/python3/dist-packages (from changedetection.io) (4.0.0)
Requirement already satisfied: flask-login>=0.6.3 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (0.6.3)
Requirement already satisfied: flask~=2.3 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (2.3.3)
Requirement already satisfied: wtforms~=3.0 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (3.0.1)
Requirement already satisfied: jq~=1.3 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.4.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (9.4.0)
Requirement already satisfied: flask-wtf~=1.2 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.2.1)
Requirement already satisfied: flask-expects-json~=1.7 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (1.7.0)
Requirement already satisfied: eventlet>=0.33.3 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (0.33.3)
Requirement already satisfied: elementpath in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (4.1.5)
Requirement already satisfied: werkzeug~=3.0 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (3.0.1)
Requirement already satisfied: selenium~=4.14.0 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (4.14.0)
Requirement already satisfied: pytest~=7.2 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (7.2.2)
Requirement already satisfied: cryptography~=3.4 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (3.4.8)
Requirement already satisfied: inscriptis~=2.2 in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (2.3.2)
Requirement already satisfied: flask-paginate in /usr/local/lib/python3.9/dist-packages (from changedetection.io) (2022.1.8)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema==4.17.3->changedetection.io) (0.19.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema==4.17.3->changedetection.io) (22.2.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.9/dist-packages (from apprise~=1.6.0->changedetection.io) (1.3.1)
Requirement already satisfied: click>=5.0 in /usr/local/lib/python3.9/dist-packages (from apprise~=1.6.0->changedetection.io) (8.1.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from apprise~=1.6.0->changedetection.io) (2023.7.22)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.9/dist-packages (from apprise~=1.6.0->changedetection.io) (6.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.9/dist-packages (from apprise~=1.6.0->changedetection.io) (3.4.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/dist-packages (from cryptography~=3.4->changedetection.io) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.12->cryptography~=3.4->changedetection.io) (2.21)
Requirement already satisfied: greenlet>=0.3 in /usr/local/lib/python3.9/dist-packages (from eventlet>=0.33.3->changedetection.io) (2.0.2)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from eventlet>=0.33.3->changedetection.io) (1.16.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from feedgen~=0.9->changedetection.io) (2.8.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in /usr/local/lib/python3.9/dist-packages (from flask~=2.3->changedetection.io) (6.0.0)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.9/dist-packages (from flask~=2.3->changedetection.io) (2.1.2)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.9/dist-packages (from flask~=2.3->changedetection.io) (1.7.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=3.6.0->flask~=2.3->changedetection.io) (3.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2~=3.1->changedetection.io) (2.1.2)
Requirement already satisfied: ply in /usr/local/lib/python3.9/dist-packages (from jsonpath-ng~=1.5.3->changedetection.io) (3.11)
Requirement already satisfied: decorator in /usr/local/lib/python3.9/dist-packages (from jsonpath-ng~=1.5.3->changedetection.io) (5.1.1)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.9/dist-packages (from pytest~=7.2->changedetection.io) (2.0.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.9/dist-packages (from pytest~=7.2->changedetection.io) (1.1.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.9/dist-packages (from pytest~=7.2->changedetection.io) (1.0.0)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from pytest~=7.2->changedetection.io) (2.0.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from pytest~=7.2->changedetection.io) (23.0)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.9/dist-packages (from selenium~=4.14.0->changedetection.io) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.9/dist-packages (from selenium~=4.14.0->changedetection.io) (0.9.2)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.9/dist-packages (from trio~=0.17->selenium~=4.14.0->changedetection.io) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in /usr/local/lib/python3.9/dist-packages (from trio~=0.17->selenium~=4.14.0->changedetection.io) (1.10)
Requirement already satisfied: outcome in /usr/local/lib/python3.9/dist-packages (from trio~=0.17->selenium~=4.14.0->changedetection.io) (1.2.0)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from trio~=0.17->selenium~=4.14.0->changedetection.io) (2.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.9/dist-packages (from trio~=0.17->selenium~=4.14.0->changedetection.io) (1.3.0)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.9/dist-packages (from trio-websocket~=0.9->selenium~=4.14.0->changedetection.io) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.9/dist-packages (from urllib3>1.26->changedetection.io) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.9/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium~=4.14.0->changedetection.io) (0.14.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4->changedetection.io) (2.3.2.post1)
Requirement already satisfied: aniso8601>=0.82 in /usr/local/lib/python3.9/dist-packages (from flask-restful->changedetection.io) (9.0.1)
Requirement already satisfied: arrow in /usr/local/lib/python3.9/dist-packages (from jinja2-time->changedetection.io) (1.2.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.9/dist-packages (from openpyxl->changedetection.io) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->changedetection.io) (3.0.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from requests-oauthlib->apprise~=1.6.0->changedetection.io) (3.2.2)

**Comment by tteck** [comment]
https://pypi.org/project/changedetection.io/
> Requires: Python >= 3.10

also
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by githubaobab** [comment]
> https://pypi.org/project/changedetection.io/
> 
> > Requires: Python >= 3.10
> 
> also
> 
> > * If the default Linux distribution is not adhered to, script support will be discontinued.

maybe update script to Debian Bookworm 12 ?

**Comment by MrEddX** [comment]
Just migrate your Changedetection instance, to a new up to date container. For example:
* Create new Changedetection container, based on **Debian 12** using: `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/changedetection.sh)"` in the **Proxmox VE Shell**;
* Replace the `/opt/changedetection` folder with the one from your existing (old) installation;
* Test it.
