### ISSUE TITLE
USB Passthrough Problem in Debian LXC

### ISSUE THREAD

**Issue by Ryeera** [tteck/Proxmox#2510]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I deployed a Debian 12 LXC using your script and installed it as a privileged container as to set up USB passthrough. The USB-Device in question (a UPS) also appears when running `lsusb`, but when I run `nut-scanner`, it gives me this error:

`Failed to open device bus '005', skipping: No such device (it may have been disconnected)`

Does your script do anything to my Proxmox-Host itself? Because when I create a new Debian-Container without your script, it still shows all the USB-devices when running `lsusb`. How do I undo this change?

Cheers! Your scripts already saved me a great deal of time!

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> Does your script do anything to my Proxmox-Host itself?

no

> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

My primary focus revolves around the development of application LXCs, and I'm not specialized in providing support for operational issues that may arise with these applications.

I consider this issue unrelated to the script, so it is now closed.
