### ISSUE TITLE
How to install Python 3.12.2 for Home Assistant 2024.4 in Debian LXC?

### ISSUE THREAD

**Issue by fruchttiger87** [tteck/Proxmox#2519]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After updating Home Assistant Core LXC via the script inside the container I get the following warning (see below) which means: the support for Python 3.11.2 will be removed with the update 2024.4 of Home Assistant
I tried to update to python 3.12 without success.
I know this is not an issue with the script but I don't know where to post the question instead. 
When I used the script with Docker instead, python would be upgraded automatically by upgrading the container. How will it be with the LXC? Will it be updated automatically as well by the script in the future or is is necessary to install Python 3.12 manually because it will not be available in Debian 12 repositories.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/63422494/19bf33fe-6131-4426-bcae-4a83830f1686)

### Please provide detailed steps to reproduce the issue.

After updating to version 2024.2.1

**Comment by tteck** [comment]
You gotta start reading. https://github.com/tteck/Proxmox/discussions/2458

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
