### ISSUE TITLE
[install/paperless-ngx-install.sh] inappropriate postgres charset

### ISSUE THREAD

**Issue by alxvlkr** [tteck/Proxmox#2525]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

django-allauth has issues with SQL_ASCII database encoding, when using utf8 charset there are no problems.
See https://github.com/paperless-ngx/paperless-ngx/issues/5837 for further explaination.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Out of curiosity, did you create the LXC via SSH?

**Comment by alxvlkr** [comment]
It was a few months ago... I used the serial console of the host when deploying (webgui). The error appeared later, while I was trying to set up a custom idp, which is a new feature of paperless.
