### ISSUE TITLE
Transmission LXC Proxmox script

### ISSUE THREAD

**Issue by rukakolink** [tteck/Proxmox#2526]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

hi how can access the files downloaded on Transmission LXC ?
is possible to map a network share and change the downloads location to it?
thanks in advance

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
