### ISSUE TITLE
The VSCode script does not run

### ISSUE THREAD

**Issue by kewgenia** [tteck/Proxmox#2529]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the VSCode installation script in the proxmox console: Can't Install on Proxmox

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Read the instructions.

**Comment by kewgenia** [comment]
______          __        _____                          
  / ____/___  ____/ /__     / ___/___  ______   _____  _____
 / /   / __ \/ __  / _ \    \__ \/ _ \/ ___/ | / / _ \/ ___/
/ /___/ /_/ / /_/ /  __/   ___/ /  __/ /   | |/ /  __/ /    
\____/\____/\__,_/\___/   /____/\___/_/    |___/\___/_/     
 
⚠️  Can't Install on Proxmox

**Comment by kewgenia** [comment]
Other scripts are working

**Comment by tteck** [comment]
> To Install VS Code Server, ⚠️ run the command below in the **LXC console**.

Again, read the instructions.

**Comment by tteck** [comment]
This is because you're trying to execute a script on the Proxmox host that is not allowed.

**Comment by kewgenia** [comment]
The obvious is on the surface. Thanks
