### ISSUE TITLE
Error 25@323 Creating VM 

### ISSUE THREAD

**Issue by elax46** [tteck/Proxmox#253]
![Immagine 2022-06-02 110328](https://user-images.githubusercontent.com/55278049/171597488-3ec7982f-cf94-43ec-9d6b-adfee4254a3d.png)

**Comment by tteck** [comment]
Ok, need a little more info. Tell me about your Promox setup.

**Comment by elax46** [comment]
> Ok, need a little more info. Tell me about your Promox setup.

What information do you need?

**Comment by tteck** [comment]
Is it Pimox? What type of storage are you using?

**Comment by elax46** [comment]
> Is it Pimox? What type of storage are you using?

Yes of course proxmox version 7.2.4 internal storage (ssd 250gb)

**Comment by tteck** [comment]
ext4 | ZFS | BTRFS ?

**Comment by tteck** [comment]
This script will not work with Pimox.

**Comment by elax46** [comment]
> This script will not work with Pimox.

I do not use Pimox but proxmox on my server not on a raspberry

**Comment by tteck** [comment]
What type of file system? Because you're using local for storage.

**Comment by elax46** [comment]
> What type of file system? Because you're using local for storage.

I can also use an external NFS space or create a specific one

**Comment by tteck** [comment]
Do you know what type of file system you're using? ext4 | ZFS | BTRFS ?

**Comment by tteck** [comment]
Try creating a new VM using default settings

**Comment by tteck** [comment]
Until I know what type of file system you're using, I can't provide further assistance.

**Comment by tteck** [comment]
Same issue https://github.com/tteck/Proxmox/issues/248#issue-1251752722

**Comment by tteck** [comment]
This may help you out: https://github.com/tteck/Proxmox/issues/257#issuecomment-1145788515
