### ISSUE TITLE
Stuck on Creating HAOS VM

### ISSUE THREAD

**Issue by userspaced** [tteck/Proxmox#2530]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am trying to use the HAOS VM script and everything seems to go fine until I get to "Creating HAOS VM". It seems stuck on that step. I have let it go for 20 minutes and still it hasn't finished. I can't tell if it's still doing anything or not.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
What storage are you trying to use?

**Comment by userspaced** [comment]
Do you mean the storage location? It's basically an LVM on an SSD. I have created several LXC containers on it already without issue.

Here's the output from the script. Is there a log file somewhere that has more details? I didn't see a verbose option on this one.

```Using Advanced Settings
Using HAOS Version: 11.5
Virtual Machine ID: 103
Using Machine Type: i440fx
Using Disk Cache: Write Through
Using Hostname: haos11.5
Using CPU Model: Host
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using MAC Address: 02:A3:04:63:F7:4D
Using Vlan: Default
Using Interface MTU Size: Default
Start VM when completed: no
Creating a HAOS VM using the above advanced settings
 ✓ Using Data1 for Storage Location.
 ✓ Virtual Machine ID is 103.
 ✓ https://github.com/home-assistant/operating-system/releases/download/11.5/haos_ova-11.5.qcow2.xz
 ✓ Downloaded haos_ova-11.5.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM  ◓^C^C```

**Comment by tteck** [comment]
As a test, try a different storage. Maybe local-lvm

**Comment by userspaced** [comment]
Interesting. It worked fine and quickly there. I wonder what the issue could be on the other SSD? Perhaps I can move it now?

**Comment by tteck** [comment]
Why use LVM instead of LVM-Thin if you're using it for Disk image and container?

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by userspaced** [comment]
> Why use LVM instead of LVM-Thin if you're using it for Disk image and container?

I'm still learning about Proxmox, so chalk that up to just not understanding the benefits of going with the LVM-Thin.
