### ISSUE TITLE
heimdall script error

### ISSUE THREAD

**Issue by frezeen** [tteck/Proxmox#2534]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

bash: line 104: start: command not found
/dev/fd/63: line 30: SPINNER_PID: unbound variable

script dont start

### Which Linux distribution are you employing?

Debian 12

**Comment by cbc-projects** [comment]
I am getting the same (related) error with the Nginx Proxy Manager script:

`bash: line 184: start: command not found
/dev/fd/63: line 30: SPINNER_PID: unbound variable`

**Comment by tteck** [comment]
retry now

**Comment by cbc-projects** [comment]
Working for me! Thanks @tteck!
