### ISSUE TITLE
Error when installing Nginx Proxy Manager

### ISSUE THREAD

**Issue by jamiepentland** [tteck/Proxmox#2535]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I run the install script for Nginx Proxy Manager, I get the following error:

```
bash: line 184: start: command not found
/dev/fd/63: line 30: SPINNER_PID: unbound variable
```

Note that I don't get any prompts for advanced install settings, etc. It doesn't get that far. Grateful for any troubleshooting steps!

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

In Proxmox shell, execute: 
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"
`

**Comment by greirson** [comment]
Im receiving this with dockge as well. 

```sh
    ____             __
   / __ \____  _____/ /______ ____
  / / / / __ \/ ___/ //_/ __ `/ _ \
 / /_/ / /_/ / /__/ ,< / /_/ /  __/
/_____/\____/\___/_/|_|\__, /\___/
                      /____/
Loading...
bash: line 66: start: command not found
/dev/fd/63: line 30: SPINNER_PID: unbound variable
```

**Comment by cbc-projects** [comment]
It looks like tteck was actively working on the build.func dependency - I just tried Nginx Proxy Manager again and it's working now.

**Comment by jamiepentland** [comment]
Unfortunately still not working from my side, but tomorrow is another day :-)

**Comment by cbc-projects** [comment]
lol I just tried installing Docker and it didn't work, same error. So I'm guessing tteck's actively working on it and to try again when the work is done.

**Comment by tteck** [comment]
Everything should be good now. If not, clear cache.
