### ISSUE TITLE
Problem updating LXC

### ISSUE THREAD

**Issue by tigercraft4** [tteck/Proxmox#2539]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I execute the script Update LXC
and this errors are reported
![image](https://github.com/tteck/Proxmox/assets/50810385/e041d669-22bb-49e6-8721-f35fc4eb7fb0)

### Which Linux distribution are you employing?

Default Settings

### Please provide detailed steps to reproduce the issue.

i tried with the lxc shutdown or turned on and no sucess

**Comment by tteck** [comment]
Something strange on your end.

![Screenshot 2024-02-22 9 01 35 AM](https://github.com/tteck/Proxmox/assets/21342670/c86ace61-eadc-444d-83ff-8c283940a4df)

**Comment by tigercraft4** [comment]
Solved, I have a "C" caracter in .conf file
