### ISSUE TITLE
Stirling PDF - "disabled" OCR function

### ISSUE THREAD

**Issue by DeepCoreSystem** [tteck/Proxmox#2540]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

A fresh installation of Stirling PDF with the scripts yields a disabled OCR function in Stirling PDF. 
The displayed page in Stirling PDF suggest to refer to its documentation.

The problem arises from the fact that Debian installs the `tessdata` in the "wrong" directory. See discussion #2538

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
   _____ __  _      ___                 ____  ____  ______
  / ___// /_(_)____/ (_)___  ____ _    / __ \/ __ \/ ____/
  \__ \/ __/ / ___/ / / __ \/ __ `/___/ /_/ / / / / /_
 ___/ / /_/ / /  / / / / / / /_/ /___/ ____/ /_/ / __/
/____/\__/_/_/  /_/_/_/ /_/\__, /   /_/   /_____/_/
                          /____/
Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 116
Using Hostname: stirling-pdf
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Stirling-PDF LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-vm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 116 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.13.4.216 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed LibreOffice Components
 ✓ Installed Python Dependencies
 ✓ Installed Azul Zulu
 ✓ Installed JBIG2
 ✓ Installed Language Packs
 ✓ Installed Stirling-PDF v0.21.0
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Stirling-PDF should be reachable by going to the following URL.
         http://10.13.4.216:8080  
```

![grafik](https://github.com/tteck/Proxmox/assets/3703938/9aebc2b5-89f5-4cc8-b585-3bb0cae595e3)

### Please provide detailed steps to reproduce the issue.

- Install a new Stirling PDF LXC container with the default settings with the script
- Try to do an OCR on any PDF
- Take note of the displayed information
- Perform the following steps as root in the corresponding LXC container to resolve the issue:

```
mkdir -p /usr/share/tessdata
cp -r /usr/share/tesseract-ocr/5/tessdata/* /usr/share/tessdata
```

**Comment by tteck** [comment]
What about just creating a symlink?
```
ln -s /usr/share/tesseract-ocr/5/tessdata/ /usr/share/tessdata
```

**Comment by DeepCoreSystem** [comment]
Yes, it would work ... I couldn't remember how to set a symlink and needed the OCR asap

Could you add the step with the symlink in your script?

**Comment by tteck** [comment]
If I can remember which direction it goes...

**Comment by tteck** [comment]
fixed
