### ISSUE TITLE
Update of Unifi

### ISSUE THREAD

**Issue by Stephan-4711** [tteck/Proxmox#2542]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I don't get the newest Unifi Manager update when I execute the Update script.
What do I need to do to get the newest release.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Show the output of `cat /etc/apt/sources.list.d/100-ubnt-unifi.list`

**Comment by tteck** [comment]
The latest [version](https://www.ui.com/download/releases/network-server) from their website is 8.0.28

The version the script installs is:
```
root@unifi:~# dpkg -l | grep unifi
ii  unifi                            8.0.28-24416-1                 all          Ubiquiti UniFi server
```
Seems to be an issue on your end.

**Comment by Stephan-4711** [comment]
I got an email that there is a new stable release https://[community.ui.com/releases/UniFi-Network-Application-8-1-107/c2cb7b81-07b9-43e7-a0ec-f728ab76e8a2?notification=d5c8f495-d2d1-4d92-b58d-c698c03aa5d8](https://community.ui.com/releases/UniFi-Network-Application-8-1-107/c2cb7b81-07b9-43e7-a0ec-f728ab76e8a2?notification=d5c8f495-d2d1-4d92-b58d-c698c03aa5d8)

**Comment by tteck** [comment]
That's early access, not stable, only stable releases are in their repository.

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
