### ISSUE TITLE
vaultvarden debian

### ISSUE THREAD

**Issue by frezeen** [tteck/Proxmox#2546]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

first try with default setting and waltwarden.bin compiling stopped with out of memory error on proxmox syslog, try with custom settings , 8gb ram lxc, and creation si ended without error.
i think, but i cant confirm this, 4gb ram is low for to complete lxc creation.

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
