### ISSUE TITLE
Mariadb LXC issue with Adminer

### ISSUE THREAD

**Issue by koftikes** [tteck/Proxmox#2565]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After install bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/mariadb.sh)"
with default setting and make mysql_secure_installation.
Can not enter to IP/adminer/, got error  "Server sent charset (0) unknown to the client. Please, report to the developers"

If try use other client, from Developer IDE for example, all work fine.

Looks like issue with adminer not with DB container.  Please assist if it possible.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
Did you create a database?

**Comment by tteck** [comment]
Just went through the complete installation with no issues.

As this issue is unrelated to the script, it is considered closed.

**Comment by koftikes** [comment]
> Did you create a database?

Yes. I do all by the the script...

> Just went through the complete installation with no issues.
> 
> As this issue is unrelated to the script, it is considered closed.

your script installs a package that obviously does not work correctly with the database.
So I have strong doubts that this has nothing to do with the script...

Did you check connect to DB through adminer?

**Comment by koftikes** [comment]
https://github.com/tteck/Proxmox/blob/b88dc1338313d9eca530adf82a8546b3af192850/install/mariadb-install.sh#L30

The is the place what "unrelated to the script"

**Comment by tteck** [comment]
My apologies, after actually trying to login, I too get the error with MariaDB. Adminer with PostgreSQL still works as intended.
I guess I have no choice but to remove Adminer from the MariaDB script. 🤷🏻‍♂️

**Comment by torifat** [comment]
Anyone facing this problem, can comment out the line `character-set-collations = utf8mb4=uca1400_ai_ci` in `/etc/mysql/mariadb.conf.d/50-server.cnf`.

https://github.com/php/php-src/issues/13452
