### ISSUE TITLE
Cannot update ESPHome container

### ISSUE THREAD

**Issue by vdiogo** [tteck/Proxmox#2566]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to update ESPHome LXC (I am on 2023.12.9) using the provided script
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/esphome.sh)"

I get the following error message:
[ERROR] in line 66: exit code 0: while executing command pip3 install -U esphome &> /dev/null

PS: I was unable to load ESPHome at first, so rebooted the container and now can open it

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

[ERROR] in line 66: exit code 0: while executing command pip3 install -U esphome &> /dev/null

### Please provide detailed steps to reproduce the issue.

1. Select ESPHome container
2. Open console
3. Run script bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/esphome.sh)"
4. Press Enter

**Comment by tteck** [comment]
No issue here
```
    ___________ ____  __  __                   
   / ____/ ___// __ \/ / / /___  ____ ___  ___ 
  / __/  \__ \/ /_/ / /_/ / __ \/ __ `__ \/ _ \
 / /___ ___/ / ____/ __  / /_/ / / / / / /  __/
/_____//____/_/   /_/ /_/\____/_/ /_/ /_/\___/ 
                                               
 ✓ Stopped ESPHome
 ✓ Updated ESPHome
 ✓ Started ESPHome
 ✓ Updated Successfully
root@esphome:~# 
```

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.

**Comment by vdiogo** [comment]
as a note, I used the same script to install it so probably there was some issue on the installation. Can't comment if it's a script related or not.

I ended up creating a new container and will monitor for the future if some issue with updating it
