### ISSUE TITLE
Website correction

### ISSUE THREAD

**Issue by oOStroudyOo** [tteck/Proxmox#2567]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

The description for Mafl on your website shows "To update Homarr.."

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/111181956/c075b873-874b-4b2f-b796-a1e3d68dbe86)

**Comment by tteck** [comment]
Fixed, thanks
