### ISSUE TITLE
Creating HAOS VM...‼ ERROR 255@323 Unknown failure occured.

### ISSUE THREAD

**Issue by DanielV88** [tteck/Proxmox#257]
Hi ttech,

I'm using your script to deploy HA to my proxmox, but I'm getting a "ERROR 255@323 Unknown failure occured" when creating the VM.
Is there anything I am doing wrong? I'm using al default settings.

 ✓ Extracted Disk Image
 - Creating HAOS VM...volume 'Synology-NFS:100/vm-100-disk-1.qcow2' does not exist
‼ ERROR 255@325 Unknown failure occured.

I'm using NFS Storage from my Synology to deploy the VM on to.

**Comment by DanielV88** [comment]
When creating the VM on the local storage the script works.
I've now deployed to local and then moved the storage to the NFS storage.

**Comment by tteck** [comment]
@DanielV88 would you be so kind and try to create a new HAOS VM using Synology-NFS for Storage Location?
