### ISSUE TITLE
deCONZ LXC Failing on "Installing deConz" - [ERROR] in line 29: exit code 0: while executing command wget -qL http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb 

### ISSUE THREAD

**Issue by bkarakashev** [tteck/Proxmox#2578]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

No matter the installation option I select (Default, Advanced, Privileged, Non-privileged, Verbose, etc.) it never installs without errors. 
I try using all the options for the OS, but they all fail the same way.
I try running it in the console I try ssh and execute the script this way, but nothing works.
I always get the same error.

 - Installing deConz  \
`[ERROR] in line 29: exit code 0: while executing command wget -qL http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb `

Please let me know if you need any more information.

Thanks

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="1452" alt="Screenshot 2024-02-28 at 10 02 25 pm" src="https://github.com/tteck/Proxmox/assets/6206509/77360220-cd46-405d-9d60-655eefa0bf39">

### Please provide detailed steps to reproduce the issue.

The steps I took are just running the provided script for deCONZ LXC
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/deconz.sh)"`

**Comment by tteck** [comment]
fixed
