### ISSUE TITLE
Install scripts not detecting storage

### ISSUE THREAD

**Issue by munkk01** [tteck/Proxmox#2579]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I moved from an old proxmox host to a new one with all new hardware and drives. 

Instead of using backups on this host, I wanted a completely fresh instance. I am attempting to install nginxproxymanager via the install script.

I have created a zfs pool aptly named `lxc-storage` and can use it for storage by creating an lxc normally from a template. However, when running the install script.. My only options for lxc storage are `local` and my nas that is connected via smb. 

`lxc-storage` is a ZFS pool with `Disk Image, Container` selected.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/152475628/7eb4bf88-baae-4535-9a0b-6e8b556a0a9f)
`ZFS pool mentioned above`

![image](https://github.com/tteck/Proxmox/assets/152475628/126b44df-897a-4358-959a-0e0a28314fad)
`lxc-storage available when manually creating lxc using a template`

- Command used to install nginxproxymanager:
```sh
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"
```
- Used default settings

 -> Result for storage
 
![image](https://github.com/tteck/Proxmox/assets/152475628/21adc88b-e84c-46b8-9905-b9e434a5d185)

I also noticed that it isn't picking up my `local-zfs` either?

I'm really not sure if I messed up something or what but I didn't encounter this on my old proxmox host.

### Please provide detailed steps to reproduce the issue.

1. Create ZFS pool with storage for containers
2. Run install script
3. Check storage options

**Comment by tteck** [comment]
Your picture shows "Which storage pool you would like to use for the container **template**" not "Which storage pool you would like to use for the container"

**Comment by munkk01** [comment]
> Your picture shows "Which storage pool you would like to use for the container **template**" not "Which storage pool you would like to use for the container"

Oh lord. I need to take a long break from this headache. Closing this due to my sleep deprivation from the struggles of putting this thing in the rack and rails.
