### ISSUE TITLE
Tandoor helper-script does not actually match the documented Default Settings of 2vCPU and 2GB RAM

### ISSUE THREAD

**Issue by supermarkert** [tteck/Proxmox#2590]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Tandoor helper-scripts website says that default setting is 2vCPU and 2GB RAM, however in the script itself the actual default is (4) CPUs and 4096 MB (both of which seems excessive).

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/15205204/7eb59d79-1ac8-4b5d-aa85-0a88bd784a82)
![image](https://github.com/tteck/Proxmox/assets/15205204/8c01fff6-7695-4f17-8a24-9b423a0962fb)

### Please provide detailed steps to reproduce the issue.

Attempt to install the Tandoor Recipes script with the default values...

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/89d9b9ca9f0b749243b51b0be3e9bc96f7ce7007/ct/tandoor.sh#L83-L86
