### ISSUE TITLE
tailscale script doesn't install tailscale on yunohost LXC

### ISSUE THREAD

**Issue by protonaut** [tteck/Proxmox#2591]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I discovered, that the tailscale-Script is not installing tailsacle in some Containers.

For example: To install tailscale on yunohost failes without an error massage. But also the expected logs for succesfully creating tailscale don't appear (see the screenshot)

![Bildschirmfoto vom 2024-03-01 20-46-24](https://github.com/tteck/Proxmox/assets/75339252/49d9a177-81ff-4ff4-9acc-85b53518e260)

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Bildschirmfoto vom 2024-03-01 20-46-24](https://github.com/tteck/Proxmox/assets/75339252/8aaef5f6-4916-4d53-b7a2-26384a0ba5cd)

**Comment by tteck** [comment]
OK, noted.
