### ISSUE TITLE
Error in Wiki.js LXC

### ISSUE THREAD

**Issue by ipod86** [tteck/Proxmox#2595]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have an error on the first page of Wiki.js LXC setup.  As soon as I press "install" the following error occurs.

`insert into `authentication` (`autoEnrollGroups`, `config`, `displayName`, `domainWhitelist`, `isEnabled`, `key`, `order`, `selfRegistration`, `strategyKey`) values ('{"v":[]}', '{}', 'Local', '{"v":[]}', true, 'local', 0, false, 'local') - SQLITE_CONSTRAINT: UNIQUE constraint failed: authentication.key`

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot_20240302_172506_Chrome](https://github.com/tteck/Proxmox/assets/66136363/a5d90b07-c294-48d0-92f5-41cfb118f5a3)

**Comment by tteck** [comment]
Set "SITE URL" to http://IP:3000

```
 _       ___ __   _     _     
| |     / (_) /__(_)   (_)____
| | /| / / / //_/ /   / / ___/
| |/ |/ / / ,< / /   / (__  ) 
|__/|__/_/_/|_/_(_)_/ /____/  
                 /___/      
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: wikijs
Using Disk Size: 3
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Wikijs LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Wiki.js
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Wikijs should be reachable by going to the following URL.
         http://192.168.86.250:3000 
```

![Screenshot 2024-03-02 12 35 22 PM](https://github.com/tteck/Proxmox/assets/21342670/173e4ee5-7c1a-482c-9632-0a1aa1e29579)

**Comment by ipod86** [comment]
Still the same
![Screenshot_20240302_184912_Chrome](https://github.com/tteck/Proxmox/assets/66136363/1f910a3a-93e2-4fc4-abb7-6d3275a40bdb)

**Comment by tteck** [comment]
🤷🏻‍♂️  Working here.

If I'm unable to replicate the problem on my end, I won't be able to resolve an issue that seems to be working fine from my perspective.

**Comment by ipod86** [comment]
OK, thanks for your help.
