### ISSUE TITLE
pialert cannot execute speedtest without www-data sudoers access

### ISSUE THREAD

**Issue by mterry63** [tteck/Proxmox#2597]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installed pialert as an LXC in Proxmox with this script. Install worked, but speedtest functions do not.

The php script speedtest_ookla.php runs the speedtest executable using sudo. This generates an error message in the apache error log:

sudo: a password is required
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

Added a file www-data to /etc/sudoers.d/ with the following contents:
www-data ALL=NOPASSWD: /opt/pialert/back/speedtest/speedtest

Speedtest then was able to execute. No more errors in log.

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

None.

### Please provide detailed steps to reproduce the issue.

Open the Tools tab of the pialert Internet record and click the button labeled "Start Speedtest (Ookla)"

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
