### ISSUE TITLE
Integrate jDownloader 2 LXC in helper scripts

### ISSUE THREAD

**Issue by rcasula** [tteck/Proxmox#2602]
Hello,

would be nice if you can implement a jDownloader 2 LXC script. 

An example could be found here https://github.com/StevenSeifried/proxmox-scripts and https://github.com/StevenSeifried/proxmox-scripts/issues/12#issuecomment-1356144716.

Let me know if I can help anyhow, maybe I can open a PR myself.

BTW, thanks for your collection of scripts, those are so helpful!

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**
