### ISSUE TITLE
Prometheus update

### ISSUE THREAD

**Issue by danny1605** [tteck/Proxmox#2607]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

It is not possible to update Prometheus using the command listed below

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2024-03-06 084745](https://github.com/tteck/Proxmox/assets/59099140/d181ad44-bb53-48d5-9768-d839a3bd4d21)
![Screenshot 2024-03-06 084714](https://github.com/tteck/Proxmox/assets/59099140/07542106-fc86-421d-a0e2-e3b501fb4532)

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/prometheus.sh)"

✓ Updated Successfully

**Comment by danny1605** [comment]
![Screenshot 2024-03-06 113750](https://github.com/tteck/Proxmox/assets/59099140/26466eaf-99f1-411c-9a5f-fead8a427e86)


@tteck Wouldn't an update of Prometheus be possible? If not, how can I update it manually?

**Comment by sahara101** [comment]
I would also like to update prometheus
