### ISSUE TITLE
MQTT LXC installation failed

### ISSUE THREAD

**Issue by LocoR9** [tteck/Proxmox#2617]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

installation failed

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

` ✓ Installed Dependencies
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease                                                  
Hit:3 http://security.debian.org bookworm-security InRelease                                                   
Get:4 https://repo.mosquitto.org/debian bookworm InRelease [18.7 kB]      
Err:4 https://repo.mosquitto.org/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 779B22DFB3E717B7
Reading package lists... Done
|W: GPG error: https://repo.mosquitto.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 779B22DFB3E717B7
E: The repository 'https://repo.mosquitto.org/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

[ERROR] in line 27: exit code 0: while executing command $STD apt-get update`

**Comment by th33xil3** [comment]
With debian 11 it will work.

**Comment by tteck** [comment]
According to https://repo.mosquitto.org/debian/README.md:

# The Eclipse Mosquitto debian repository

Use this if you want to install the most recent version of Mosquitto on your
Debian system.

Supported architectures are amd64, i386, and armhf (for Raspberry Pi OS).

## Setup

The Debian repo key is mosquitto-repo.gpg.key, to add it to your keyring, do the following as root:

```
wget -qO- http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key | sudo tee /etc/apt/trusted.gpg.d/mosquitto-repo.asc
```


To add the repo to your sources.list:

```
wget -O /etc/apt/sources.list.d/mosquitto-bookworm.list http://repo.mosquitto.org/debian/mosquitto-bookworm.list
```

Or:

```
wget -O /etc/apt/sources.list.d/mosquitto-bullseye.list http://repo.mosquitto.org/debian/mosquitto-bullseye.list
```

Then do:

```
apt-get update && apt-get install mosquitto
```

The available packages are:

* libmosquitto-dev
* libmosquitto1
* libmosquitto1-dbgsym
* libmosquittopp-dev
* libmosquittopp1
* libmosquittopp1-dbgsym
* mosquitto
* mosquitto-clients
* mosquitto-clients-dbgsym
* mosquitto-dbgsym
* mosquitto-dev


## Old archives

The `buster`, `stretch` and `jessie` archives remain available, but are no longer updated with new versions.

```
wget -O /etc/apt/sources.list.d/mosquitto-stretch.list http://repo.mosquitto.org/debian/mosquitto-buster.list
wget -O /etc/apt/sources.list.d/mosquitto-stretch.list http://repo.mosquitto.org/debian/mosquitto-stretch.list
wget -O /etc/apt/sources.list.d/mosquitto-jessie.list http://repo.mosquitto.org/debian/mosquitto-jessie.list
```
This is what the script is using. I can modify the script to satisfy the requirements, but I'm sure I'll need to change it back later. I also noticed recent (3/8/2024) changes to the [repo](https://repo.mosquitto.org/debian/) that is _probably_ the cause.

**Comment by tteck** [comment]
~Well, seems error detection didn't like that.~
Add `gpg`

**Comment by tteck** [comment]
```
    __  ___           ____        _ ____________    
   /  |/  /___  _____/ __ \__  __(_)_  __/_  __/___ 
  / /|_/ / __ \/ ___/ / / / / / / / / /   / / / __ \
 / /  / / /_/ (__  ) /_/ / /_/ / / / /   / / / /_/ /
/_/  /_/\____/____/\___\_\__,_/_/ /_/   /_/  \____/ 
                                                    
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: mqtt
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a MQTT LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Mosquitto MQTT Broker
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by nfribeiro** [comment]
Mine failed in two different machines on debian 12. 
Also on debian 11.
✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Installing Mosquitto MQTT Broker  |
[ERROR] in line 23: exit code 0: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

Something not right

**Comment by tteck** [comment]
keys changed, updated

**Comment by nfribeiro** [comment]
> keys changed, updated

Now is Ok. Thanks!
