### ISSUE TITLE
Latest version of changedetection.io requires libjpeg-dev

### ISSUE THREAD

**Issue by navels** [tteck/Proxmox#2619]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Trying to update to

https://github.com/dgtlmoon/changedetection.io/releases/tag/0.45.15

and getting this error:

>       The headers or library files could not be found for jpeg, a required dependency when compiling Pillow from source.

### Which Linux distribution are you employing?

Debian 12

**Comment by navels** [comment]
Meanwhile there is more going on apparently:
```
Mar 08 10:32:38 cd changedetection.io[103095]:     return func(*args, **kwargs)
Mar 08 10:32:38 cd changedetection.io[103095]:            ^^^^^^^^^^^^^^^^^^^^^
Mar 08 10:32:38 cd changedetection.io[103095]:   File "/usr/local/lib/python3.11/dist-packages/changedetectionio/flask_app.py", line 409, in index
Mar 08 10:32:38 cd changedetection.io[103095]:     from changedetectionio import forms
Mar 08 10:32:38 cd changedetection.io[103095]:   File "/usr/local/lib/python3.11/dist-packages/changedetectionio/forms.py", line 28, in <module>
Mar 08 10:32:38 cd changedetection.io[103095]:     from changedetectionio.blueprint.browser_steps.browser_steps import browser_step_ui_config
Mar 08 10:32:38 cd changedetection.io[103095]:   File "/usr/local/lib/python3.11/dist-packages/changedetectionio/blueprint/browser_steps/browser_steps.py", line 9, >
Mar 08 10:32:38 cd changedetection.io[103095]:     from changedetectionio.content_fetchers.base import manage_user_agent
Mar 08 10:32:38 cd changedetection.io[103095]: ModuleNotFoundError: No module named 'changedetectionio.content_fetchers'
Mar 08 10:32:38 cd changedetection.io[103095]: 67.160.99.155,192.168.4.4 - - [08/Mar/2024 10:32:38] "GET / HTTP/1.1" 500 464 0.002573
```

**Comment by navels** [comment]
I've alerted the owner: https://github.com/dgtlmoon/changedetection.io/discussions/2238

**Comment by dgtlmoon** [comment]
@navels should be good to go https://github.com/dgtlmoon/changedetection.io/actions/runs/8208472374/job/22452013413 `0.45.16`

**Comment by navels** [comment]
Confirmed fixed, although just for clarity: that is after I manually installed libjpeg-dev.

**Comment by tteck** [comment]
Nice!
https://chromewebstore.google.com/detail/changedetectionio-website/kefcfmgmlhmankjmnbijimhofdjekbop?hl=en-GB&authuser=0

**Comment by dgtlmoon** [comment]
@tteck new minor update to that extension awaiting approval from google, then we start adding some serious features 8) if you have any suggestions..

**Comment by dgtlmoon** [comment]
@navels libjpeg-dev ? yeah something upstream changed.. i dont know how to solve that as a requirements.txt type deal

**Comment by navels** [comment]
> @navels libjpeg-dev ? yeah something upstream changed.. i dont know how to solve that as a requirements.txt type deal

no need, tteck added it to the install script, same dependency as in your Dockerfile.
