### ISSUE TITLE
Tandoor -> Consider removing header from tandoor.conf

### ISSUE THREAD

**Issue by jproz** [tteck/Proxmox#2621]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While the standard Tandoor LXC build works, it breaks if you are using a double proxy.
Specifically, with the custom nginx build starting at line 112, @tteck has included
`proxy_set_header X-Forwarded-Proto $scheme;`
The problem here is that if, as in my case, you front the whole lxc install with NPM for SSL management, that line will overwrite the https scheme header with http scheme header .. causing breakage.
Once commented out, the whole thing works - both direct access as normal to the LXC as well as NPM SSL -> NGINX -> Tandoor.

Also note ... in the standard docker install, the only header used is `proxy_set_header Host $http_host;` so the additional header above isn't really needed by default.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

starting at 112 in the install script 
```cat << 'EOF' >/etc/nginx/conf.d/tandoor.conf
server {
    listen 8002;
    #access_log /var/log/nginx/access.log;
    #error_log /var/log/nginx/error.log;

    # serve media files
    location /static/ {
        alias /opt/tandoor/staticfiles/;
    }

    location /media/ {
        alias /opt/tandoor/mediafiles/;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://unix:/opt/tandoor/tandoor.sock;
        proxy_set_header X-Forwarded-Proto $scheme; ### REMOVE THIS LINE
    }
}
EOF
```
### Please provide detailed steps to reproduce the issue.

just put NPM in front of the LXC for SSL RP offload. The won't be able to pull up resources even though it "loads" - no recipes, shopping etc.

**Comment by tteck** [comment]
Removed
