### ISSUE TITLE
Jellyfin fails to install with default settings missing package

### ISSUE THREAD

**Issue by ggee** [tteck/Proxmox#2624]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Choosing the default install options for Jellyfin fail during install to find package.

### Which Linux distribution are you employing?

Default Settings

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Get:4 https://repo.jellyfin.org/ubuntu jammy InRelease [6,639 B]
Get:5 https://tor1.mirror.jellyfin.org/files/ubuntu jammy/main amd64 Packages [851 B]
Fetched 7,490 B in 1s (11.1 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
|Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
/ jellyfin : Depends: jellyfin-ffmpeg5 (>= 5.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

[ERROR] in line 53: exit code 0: while executing command $STD apt-get install -y jellyfin

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jellyfin.sh)"

**Comment by ggee** [comment]
Using Default Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04

**Comment by tteck** [comment]
The script uses the Jellyfin metapackage, which will automatically fetch the various sub-packages.

Seems that the Jellyfin Ubuntu repo is borked, while the Jellyfin Debian repo functions as it should.

If you decide to install Jellyfin utilizing Debian 12, you will need to manually execute the following command in the Jellyfin LXC console to properly correct groups
```
sed -i -e 's/^sgx:x:104:$/render:x:104:root,jellyfin/' -e 's/^render:x:106:root,jellyfin$/sgx:x:106:/' /etc/group
```

For now, there's nothing that I can do but wait on Jellyfin/Ubuntu to fix their issue.

**Comment by ggee** [comment]
Thanks.  I'll try that out.  BTW, can the Ubuntu 23 be replaced with 24?  I tried 23 and got error during apt update.

```
Hit:1 http://archive.ubuntu.com/ubuntu lunar InRelease
Hit:2 http://archive.ubuntu.com/ubuntu lunar-updates InRelease            
Hit:3 http://archive.ubuntu.com/ubuntu lunar-security InRelease           
Ign:4 https://repo.jellyfin.org/ubuntu lunar InRelease
Err:5 https://repo.jellyfin.org/ubuntu lunar Release
  404  Not Found [IP: 68.183.204.194 443]
Reading package lists... Done
E: The repository 'https://repo.jellyfin.org/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

[ERROR] in line 52: exit code 0: while executing command $STD apt-get update
```

**Comment by tteck** [comment]
There is no v24 https://www.releases.ubuntu.com/

**Comment by tteck** [comment]
I replaced 23.04 Lunar with 23.10 Mantic

**Comment by tteck** [comment]
They have corrected their issues.

```
       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
 
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 0
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: jellyfin
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Jellyfin LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Hardware Acceleration
 ✓ Installed Jellyfin
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Jellyfin should be reachable by going to the following URL.
             http://192.168.86.250:8096
```
