### ISSUE TITLE
NextCloud Alpine doesn't update to the latest version.

### ISSUE THREAD

**Issue by eakteam** [tteck/Proxmox#2625]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

So tried to install the LXC Alpine for NextCloud and everything seems to works OK.
After finished I was able to access it and the version installed is: **27.1.7**

After that run the install script on the CTX shell to try to update and it shows that the latest version is v28.0.3. 
Selected that option to update and after the script finished the job NextCloud is still on the older version....

Is this expected behaviour or a bug which doesn't let it to be updated on the latest version?

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
The script utilizes the Alpine Package keeper, it shows that the available version is 27.1.7
https://pkgs.alpinelinux.org/packages?name=nextcloud&branch=v3.19&repo=&arch=x86_64&maintainer=

You'll have to wait until the version is in the repository.
