### ISSUE TITLE
Requires Proxmox Virtual Environment Version 8.1.1 or later.

### ISSUE THREAD

**Issue by soakes** [tteck/Proxmox#2626]
Hi,

I noticed that you pushed this change (https://github.com/tteck/Proxmox/commit/78bc2006bc1519a3aef51f2d51daaf0606fc5922) earlier today.  

Today I have just installed a new proxmox host and found that your script now refuses to install. 

Most people are finding that the latest installer of `Proxmox 8.1` does not work on all systems (mostly gen 13+) and the only work around currently is to make it boot using the `proxmox-ve_8.0-2.iso` installer.  After installed, you then patch the system after to 8.1 (latest).

I have taken a look at your changes and I personally disagree with limiting the script to `> 8.1.1` as many people will still be forced to use a slightly earlier version until Promox developers fix the boot issue.  After taking a look at your changes, there is nothing in your changes which would not work with 8.0.2, so IMHO, this should be adjusted so that your requiring `>8.0.2` and not `>8.1.1`

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

**Comment by tteck** [comment]
I don't think that reverting https://github.com/tteck/Proxmox/commit/78bc2006bc1519a3aef51f2d51daaf0606fc5922 will solve your concerns. Have you read https://github.com/tteck/Proxmox/discussions/2433?

**Comment by soakes** [comment]
> I don't think that reverting [78bc200](https://github.com/tteck/Proxmox/commit/78bc2006bc1519a3aef51f2d51daaf0606fc5922) will solve your concerns. Have you read #2433?

I must admit, I didnt notice this post, thanks for linking.

However, I wasn't asking to revert it, I was just suggesting that you could easily adjust it to be 8.x or higher, which would still do what you want.

Anyways, for anyone who needs a work around before running the script, you can do the following which will update your base 8.0.x install to latest which will then allow for script to work.

p.s you don't have to remove all files in `/etc/apt/sources.list.d` but as the script just comments them, they are pritty pointless to keep anyways.  Just my two cents.

```
rm -vf /etc/apt/sources.list.d/*
cat << 'EOF' > /etc/apt/sources.list.d/pve-install-repo.list
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
EOF

apt-get update
apt-get dist-upgrade -y
sync; reboot
```
After systems rebooted:
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"
```
