### ISSUE TITLE
Homeassistant installer on Proxmox VM does not work

### ISSUE THREAD

**Issue by kilasat** [tteck/Proxmox#2627]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I got this error trying to install HA on a Proxom Version 8.1.4. but the script says it need 8.1.1 or later

bash: line 22: pvesh: command not found
environment: line 118: pveversion: command not found
 ✗ This version of Proxmox Virtual Environment is not supported
Requires PVE7 Version 7.4-13 or later, or PVE8 Version 8.1.1 or later.

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
Are you executing the script in the Proxmox shell? I'm afraid I need a little more information.

**Comment by tteck** [comment]
As this issue is user error and clearly unrelated to the script, it is considered closed.

**Comment by kilasat** [comment]
> Are you executing the script in the Proxmox shell? I'm afraid I need a little more information.

Got it. This was my mistake.
