### ISSUE TITLE
Tandoor Deployment On Ubuntu 22.04 Fails On apt-get install -y postgresql-16

### ISSUE THREAD

**Issue by IamTHEvilONE** [tteck/Proxmox#2629]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Was trying to get Tandoor installed on Ubuntu 22.04 (preferred OS for me)
- All default settings other than
- Ubuntu 22.04

Postgres Fails install due to unmet dependencies.  Debian 12 works without issue on same settings.

Verbose mode output of the failure attached.

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
\ postgresql-16 : Depends: postgresql-client-16 but it is not going to be installed
                 Depends: libicu72 (>= 72.1~rc-1~) but it is not installable
                 Depends: libllvm16 but it is not installable
                 Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-3build1 is to be installed
                 Recommends: sysstat but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
|
[ERROR] in line 81: exit code 0: while executing command $STD apt-get install -y postgresql-16```

### Please provide detailed steps to reproduce the issue.

- Run bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/tandoor.sh)"
- Advanced
- Choose 22.04
- Only change verbose mode to see formal error state

**Comment by tteck** [comment]
> - If the default Linux distribution is not adhered to, script support will be discontinued.

Bookworm sources 🤷🏻‍♂️ 
https://github.com/tteck/Proxmox/blob/b12a98e5a3e647217bb481342041ae9ea6958eb1/install/tandoor-install.sh#L79
