### ISSUE TITLE
Ubuntu 22.04 vm -- error

### ISSUE THREAD

**Issue by mupsje** [tteck/Proxmox#2637]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

error in line 376: exit code 3: while executing command wget -q --show-progress $URL

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/46684538/4069f99c-1f9c-4603-81fc-77c3dec2e03e)

### Please provide detailed steps to reproduce the issue.

***

**Comment by tteck** [comment]
The script runs without any problems from this end.

```
   __  ____                __           ___  ___    ____  __ __     _    ____  ___
  / / / / /_  __  ______  / /___  __   |__ \|__ \  / __ \/ // /    | |  / /  |/  /
 / / / / __ \/ / / / __ \/ __/ / / /   __/ /__/ / / / / / // /_    | | / / /|_/ /
/ /_/ / /_/ / /_/ / / / / /_/ /_/ /   / __// __/_/ /_/ /__  __/    | |/ / /  / /
\____/_.___/\__,_/_/ /_/\__/\__,_/   /____/____(_)____/  /_/       |___/_/  /_/

Using Advanced Settings
Virtual Machine ID: 110
Using Machine Type: i440fx
Using Disk Cache: None
Using Hostname: ubuntu
Using CPU Model: KVM64
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using MAC Address: 02:72:B7:C4:51:EE
Using Vlan: Default
Using Interface MTU Size: Default
Start VM when completed: no
Creating an Ubuntu 22.04 VM using the above advanced settings
 ✓ Using thin-pool for Storage Location.
 ✓ Virtual Machine ID is 110.
 ✓ https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
 ✓ Downloaded jammy-server-cloudimg-amd64.img
 ✓ Created a Ubuntu 22.04 VM (ubuntu)
 ✓ Completed Successfully!

Setup Cloud-Init before starting 

More info at https://github.com/tteck/Proxmox/discussions/2072 
```
As this issue is unrelated to the script, it is considered closed.

**Comment by manuelkue** [comment]
@mupsje have you checked if you had assigned enough disk space to the VM? Does your host have enough space left? Is your internet connection stable and connected via LAN?

**Comment by mupsje** [comment]
My fault indeed! 
Sorry for this.
