### ISSUE TITLE
Script don't start ?

### ISSUE THREAD

**Issue by gamersalpha** [tteck/Proxmox#2639]
Hello there i just install the 8.1.4 but when  i lunch the script nothing happens ?

![image](https://github.com/tteck/Proxmox/assets/32466950/345be72c-35e2-4b6b-ba05-961a00235c9e)

![image](https://github.com/tteck/Proxmox/assets/32466950/7ed634c3-4ae0-430e-9304-584b8a9a9875)

do u knowh why all script don't start ?

Thanks

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

**Comment by tteck** [comment]
It seems that you're facing a network problem, _probably_ linked to DNS.
