### ISSUE TITLE
Internet check fails

### ISSUE THREAD

**Issue by zelig2** [tteck/Proxmox#264]
Just installed the Whoogle container (thanks for setting that one up for us). During the install I got this error:
```
bash: connect: Connection timed out
bash: line 57: /dev/tcp/8.8.8.8/53: Connection timed out
 ✗ Internet Offline
```
Since I run AdGuard I block access to 8.8.8.8 from my internal networks. Maybe if `8.8.8.8` fails you could check for `google.com` to test for an internet connection.

**Comment by tteck** [comment]
Does it error (stop) the script?

**Comment by zelig2** [comment]
No, it completes as expected since it can resolve the domain names needed to update the container. Just wanted you to be aware.

**Comment by tteck** [comment]
Good, thanks for the heads up. I'm betting that most don't block access to 8.8.8.8 😉

**Comment by mschabhuettl** [comment]
@tteck i do block all DNS Providers, as well as all Ports and use my own. I also ran into this issue when I was installing PostgreSQL i think.

**Comment by tteck** [comment]
It's just a check to make one aware, that's all.
