### ISSUE TITLE
Proxmox VE 7.4 to 8.0 Upgrade

### ISSUE THREAD

**Issue by Phil1988** [tteck/Proxmox#2642]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hey, 
I just wanted to upgrade from Proxmox 7.4-17 to 8.x and followed your guide here:
https://www.derekseaman.com/2023/06/how-to-proxmox-7-4-to-8-0-upgrade.html

unforunately your script seems to need the v 8.x already, as this:
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"`
gives me that
![image](https://github.com/tteck/Proxmox/assets/6054234/16beecf1-b282-4507-8b60-138dd04bf42b)

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
The instructions state:
> 3. Verify you are running at least Proxmox VE 7.4-13. If you aren’t this current, see the next step for updating. If up to date, skip to step 9.

Your version is 7.4-17

BTW, that's not my guide.
