### ISSUE TITLE
WireGuard LXC

### ISSUE THREAD

**Issue by eakteam** [tteck/Proxmox#2645]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Install failed on Ubuntu 22.04 and Debian 12.

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
~Need more information.~

> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by tteck** [comment]
![Screenshot 2024-03-12 11 07 59 AM](https://github.com/tteck/Proxmox/assets/21342670/a74437b6-5db4-4723-a215-4083d0dc3ce9)
