### ISSUE TITLE
HomeAssistant Core LXC not installing

### ISSUE THREAD

**Issue by herecomethebugs** [tteck/Proxmox#2650]
### Discussed in https://github.com/tteck/Proxmox/discussions/2649

<div type='discussions-op-text'>

<sup>Originally posted by **herecomethebugs** March 12, 2024</sup>
I think there might be something wrong with the HomeAssistant Core LXC script and I'm not quite sure how to proceed/if there is anything I can do to fix it.

I've tried using it multiple times but it bombs out with the following error:

[ERROR] in line 45: exit code 0: while executing command RELEASE=$(curl -s https://www.python.org/downloads/ | grep -oP 'Download Python \K\d+\.\d+\.\d+' | head -1)</div>

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

**Comment by tteck** [comment]
fixed https://github.com/tteck/Proxmox/commit/16070912baccad3e32114bcaff1a0fc34df2b9e5
