### ISSUE TITLE
dashy update problem

### ISSUE THREAD

**Issue by seebaer1976** [tteck/Proxmox#2661]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have this update command 

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/dashy.sh)"

in Dashy's console and get this message.

   ____             __         
   / __ \____ ______/ /_  __  __
  / / / / __  / ___/ __ \/ / / /
 / /_/ / /_/ (__  ) / / / /_/ / 
/_____/\__,_/____/_/ /_/\__, /  
                       /____/   
 ✗ No Dashy Installation Found!
root@dashy:/#

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/2614

**Comment by seebaer1976** [comment]
Does this mean that I have to do a new installation, because dashy was moved to /opt/dashy?
