### ISSUE TITLE
dashy

### ISSUE THREAD

**Issue by seebaer1976** [tteck/Proxmox#2665]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I just created a new dashy container with
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/dashy.sh)"
because dashy was moved to /opt/dashy

dashy 2.1.1 will be installed. running!

then tried the update with
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/dashy.sh)"
and now it comes
 ✗ There is currently no update path available.

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
> - Prior to submitting, **kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved.** If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2614#issuecomment-1982036903
https://github.com/tteck/Proxmox/discussions/2631
