### ISSUE TITLE
VS Code Server: can't install on proxmox

### ISSUE THREAD

**Issue by lowrisk75** [tteck/Proxmox#2667]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

When using VS Code Server script which is : `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/code-server.sh)"
`
Proxmox return "can't install on Proxmox"

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2024-03-16 at 19 04 20](https://github.com/tteck/Proxmox/assets/37781161/43cad441-cf9d-428f-ac5c-d62c2b467dcb)

### Please provide detailed steps to reproduce the issue.

open Shell in proxmox 
type `lsb_release -a
`

**Comment by tteck** [comment]
![Screenshot 2024-03-16 6 12 59 PM](https://github.com/tteck/Proxmox/assets/21342670/3130e591-31a5-49f8-9521-d8bb6be4cebd)

**Comment by lowrisk75** [comment]
> ![Screenshot 2024-03-16 6 12 59 PM](https://private-user-images.githubusercontent.com/21342670/313433473-3130e591-31a5-49f8-9521-d8bb6be4cebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MTE5MjMsIm5iZiI6MTcxMDcxMTYyMywicGF0aCI6Ii8yMTM0MjY3MC8zMTM0MzM0NzMtMzEzMGU1OTEtMzFhNS00OWY4LTk1MjEtZDhiYjZiZTRjZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDIxNDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOWQ2ZDU5YTA3Yzc0MWNkNDRkNDIyNmNjNGYwYjMzOTc0MWJmZjQzYmM3ZmRiMDYwOTYxYTNkM2I0YmQ0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4P3_COU3dZJzKAglfB-lslvyqwhNtNjZOjjSg59gjqQ)

sorry, I should have read properly, I do have more issue though,
runing from a LXC, I first had 


`This will Install Code Server on VSCodeStudio. Proceed(y/n)?y
 ✓ Installed Dependencies
bash: line 77: curl: command not found
‼ ERROR 1@77 Unknown failure occured.
‼ ERROR 1@77 Unknown failure occured.
root@VSCodeStudio:~# `

I installed GUID which fixed that and then

`This will Install Code Server on VSCodeStudio. Proceed(y/n)?y
 ✓ Installed Dependencies
 - Installing Code-Server v4.22.1...‼ ERROR 127@81 Unknown failure occured.
root@VSCodeStudio:~# 
`
anyway probably something I misread again, I'll lock at it better tomorrow.
