### ISSUE TITLE
Ubuntu VM hard to resize

### ISSUE THREAD

**Issue by levid0s** [tteck/Proxmox#2669]
The Ubuntu VM gets created with a very small disk, and it's only possible to resize it offline using a Live CD.

I wonder if it could have a better partitioning design.

**Comment by tteck** [comment]
> Generate a report on an issue pertaining specifically to a script. For other inquires please share them in the Discussions section. **Blank issues will be closed immediately.**

**Comment by tteck** [comment]
Follow the instructions posted here https://github.com/tteck/Proxmox/discussions/2072
