### ISSUE TITLE
Linkwarden install failed

### ISSUE THREAD

**Issue by Mio3000** [tteck/Proxmox#2673]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

the Linkwarden script failed after step "Installed Adminer?

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

here is the error log:
` ✓ Installed Adminer
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @atlaskit/tree@8.8.7" has incorrect peer dependency "react@^16.8.0".
warning "@atlaskit/tree > react-beautiful-dnd-next@11.0.5" has incorrect peer dependency "react@^16.8.5".
[4/4] Building fresh packages...
Done in 147.31s.
|BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Hit:1 http://security.debian.org bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease                   
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease           
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease           
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libjpeg-turbo8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

Package xfonts-cyrillic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-unifont' has no installation candidate
E: Package 'xfonts-cyrillic' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libx264-155
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
E: Package 'libjpeg-turbo8' has no installation candidate
E: Unable to locate package libvpx6
E: Unable to locate package libwebp6
Failed to install browser dependencies
Error: Installation process exited with code: 100
/
[ERROR] in line 74: exit code 0: while executing command $STD npx playwright install-deps
root@proxmox:~#`

### Please provide detailed steps to reproduce the issue.

start the installation using script

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by rgb2017** [comment]
Hi ttech, 

I'm having the same issue using default installation settings with Ubuntu 22.04 as specified. 

![image](https://github.com/tteck/Proxmox/assets/31419732/9006f679-6638-45c4-be82-41f3851f1bca)

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    __    _       __                           __
   / /   (_)___  / /___      ______ __________/ /__  ____
  / /   / / __ \/ //_/ | /| / / __ `/ ___/ __  / _ \/ __ \
 / /___/ / / / / ,<  | |/ |/ / /_/ / /  / /_/ /  __/ / / /
/_____/_/_/ /_/_/|_| |__/|__/\__,_/_/   \__,_/\___/_/ /_/

Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: linkwarden
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Linkwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Cloned Linkwarden Repository
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> 
 ✓ Installed Linkwarden
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Linkwarden should be reachable by going to the following URL.
         http://192.168.86.250:3000 
```
Try giving it more resources (4vCPUs and 4MiB RAM)

**Comment by rgb2017** [comment]
Still the same error with increased resources. I used advanced install and set the CPU to 4 and Memory to 4096.  Have tried several times with different variations (with/without adminer for example).

**Comment by rgb2017** [comment]
Figured it out. After some debug, turns out the failed download is due to a network restriction on that source. Thank you for your assistance and advice. I'm not familiar with the components in use here so assumed a write error would be a script issue, but it was really a connectivity issue with the download location.
