### ISSUE TITLE
Umbrel 1.0+ is not supported

### ISSUE THREAD

**Issue by tnware** [tteck/Proxmox#2684]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Umbrel installation fails as the package's install script has been temporarily deprecated.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
                ,;###GGGGGGGGGGl#Sp
             ,##GGGlW""^'  '`""%GGGG#S,
           ,#GGG"                  "lGG#o
          #GGl^                      '$GG#
        ,#GGb       umbrelOS 1.0       \GGG,
        lGG"                            "GGG
       #GGGlGGGl##p,,p##lGGl##p,,p###ll##GGGG
      !GGGlW"""*GGGGGGG#""""WlGGGGG#W""*WGGGGS
       ""          "^          '"          ""

------------------------------------------------------
|                                                    |
|  umbrelOS 1.0 is currently only compatible with    |
|  Umbrel Home, Raspberry Pi 4 and Raspberry Pi 5.   |
|  Support for more devices is coming in April 2024. |
|                                                    |
------------------------------------------------------
```

### Please provide detailed steps to reproduce the issue.

install umbrel, verbose mode will render the relevant error message, or simply reference the install script from https://umbrel.sh/

**Comment by tteck** [comment]
Will be removed from the website, thanks for the heads up.

**Comment by tnware** [comment]
> Will be removed from the website, thanks for the heads up.

hopefully only until April 🙂

**Comment by tteck** [comment]
Done.
https://github.com/tteck/Proxmox/actions/runs/8382208422

**Comment by DaTwo** [comment]
Install script is here... 

curl -L https://umbrel.sh | bash

**Comment by tteck** [comment]
Doesn't work. Feel free to try it:
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/umbrel.sh)"
```
