### ISSUE TITLE
Tandoor - import function broken - fix below

### ISSUE THREAD

**Issue by jproz** [tteck/Proxmox#2685]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

UseCase:
I want to build a new LXC from scratch but export existing recipes from old into new.

Problem:
Currently - import function in LXC doesn't work.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Current NGINX config is missing a line that devs have in their docker and manual builds.
Add to ngnix config (e.g. line 117 in the script)
`client_max_body_size 128M;`

### Please provide detailed steps to reproduce the issue.

attempt to export recipes and then reimport them. it will error out.
add line above - and viola - it works.

**Comment by tteck** [comment]
Thanks!
