### ISSUE TITLE
Sterling PDF OCR does not work

### ISSUE THREAD

**Issue by bshor** [tteck/Proxmox#2686]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I installed the Sterling-PDF LXC container. It runs very well. However, when I try to click on "OCR", it only suggests a link to "ocrmypdf". When I try to see if ocrmypdf is installed, it certainly is installed by default. But I don't see any interface to it. So I'm at a loss as to what to try next.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/468070/4cb03edc-e2a3-43d0-886a-ef1b13be7683)

### Please provide detailed steps to reproduce the issue.

Open the Sterling-PDF server web app, then click on "OCR".

**Comment by tnware** [comment]
happened to just try this and it works out of the box with Stirling-PDF, is there any more info you can provide about your environment? is it possible that the language packs are not installed? 


 `apt-get install -y 'tesseract-ocr-*'`


![image](https://github.com/tteck/Proxmox/assets/537897/ea375bf5-85de-40ac-9628-0ded3eba7d71)

![image](https://github.com/tteck/Proxmox/assets/537897/650044ff-a921-4340-90ff-e55c633b6487)

![image](https://github.com/tteck/Proxmox/assets/537897/809aa230-cb5c-4ca8-a056-6c2738e0ec9e)

![image](https://github.com/tteck/Proxmox/assets/537897/2d28cd78-5b66-4a8e-a781-04fd78616154)

**Comment by tteck** [comment]
@tnware thank you for the help, I really appreciate it!!

@bshor seems that it's not a script Issue.?

https://github.com/tteck/Proxmox/blob/c5ddb590d771ba3f31335d4723cd5c26994823cf/install/stirling-pdf-install.sh#L70-L72

**Comment by tteck** [comment]
Per @tnware, 
This issue is unrelated to the script, it is considered closed.

Again, thank you @tnware!

**Comment by bshor** [comment]
@tnware @tteck Thank you for your help. tesseract-ocr-* is installed by TTeck's script. But I'm not seeing the OCR interface!

![image](https://github.com/tteck/Proxmox/assets/468070/2c224bf0-486a-4ec4-8831-ca4f2659a8aa)

So I'm not sure why I don't see what @tnware sees.

**Comment by DeepCoreSystem** [comment]
see here: [Tesseract OCR packages not in expected directory](https://github.com/tteck/Proxmox/issues/2540)

**Comment by DeepCoreSystem** [comment]
@bshor The output of `apt install tesseract-ocr-eng` only confirms that the language package is installed in the directory `/usr/share/tesseract-ocr/5/tessdata`
But Stirling PDF needs the language packs to be in directory `/usr/share/tessdata`

What do you have in that directory?
![image](https://github.com/tteck/Proxmox/assets/3703938/aa5bcda0-8665-46b5-931f-e433395b2d75)


If effectively the language packs are **not** in `/usr/share/tessdata`, you can either copy them over,
```
sudo mkdir -p /usr/share/tessdata
sudo cp -r /usr/share/tesseract-ocr/5/tessdata/* /usr/share/tessdata
```
 or put a symlink  `ln -s /usr/share/tesseract-ocr/5/tessdata/ /usr/share/tessdata`

And reboot the container!

**Comment by bshor** [comment]
Once I copied the files it worked!

@tteck Perhaps you can include this in the next version of this script. It works perfectly otherwise -- thank you so much for creating this!

**Comment by tteck** [comment]
The symbolic link is already in the script.
https://github.com/tteck/Proxmox/blob/9f32d30f6be6c71de1265cce9fec7ddc2ce0352e/install/stirling-pdf-install.sh#L86

**Comment by bshor** [comment]
Hmm. Don't think it works then. I tried the symbolic link myself and it didn't work till I copied the files over.

**Comment by tteck** [comment]
Just created a Stirling-PDF LXC to test, it appears to be working correctly here 🤷🏻‍♂️
