### ISSUE TITLE
Problem with tandoor

### ISSUE THREAD

**Issue by mrcsdl** [tteck/Proxmox#2689]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hey first of all nice project.

when running the tandoor script its crashing for me over and over again:

Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
- postgresql-16 : Depends: postgresql-client-16 but it is not going to be installed
                 Depends: libicu72 (>= 72.1~rc-1~) but it is not installable
                 Depends: libllvm16 but it is not installable
                 Depends: libzstd1 (>= 1.5.2) but 1.4.8+dfsg-3build1 is to be installed
                 Recommends: sysstat but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

[ERROR] in line 81: exit code 0: while executing command $STD apt-get install -y postgresql-16

its also with default settings

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
