### ISSUE TITLE
Phoscon App not finding conbee II

### ISSUE THREAD

**Issue by jddayley** [tteck/Proxmox#269]
The phoscon app is not able to detect the conbee II.   I can see it on the proxmox host when I run lsusb.   I also see it in the lxc container when I run ls -l /dev/serial/by-id/  
/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2495756-if00 -> ../../ttyACM0

I also tried to upgrade the firmware.

root@deconz:/usr/share/deCONZ/firmware# GCFFlasher_internal -d /dev/ttyACM0 -f deCONZ_ConBeeII_0x26720700.bin.GCF -x 3
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
11:16:09:329 using firmware file: deCONZ_ConBeeII_0x26720700.bin.GCF 
11:16:09:388 ls dev: /dev/ttyACM0 (0x0000/0x0000) sn: 
11:16:09:388 ls dev: /dev/ttyS0 (0x0000/0x0000) sn: 
11:16:09:388 ls dev: /dev/ttyS1 (0x0000/0x0000) sn: 
11:16:09:388 device /dev/ttyACM0 not found
root@deconz:/usr/share/deCONZ/firmware#

**Comment by tteck** [comment]
Is the LXC Privileged?

**Comment by tteck** [comment]
> I also see it in the lxc container when I run ls -l /dev/serial/by-id/
> /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2495756-if00 -> ../../ttyACM0

I'd say yes... lol

**Comment by tteck** [comment]
Beings that I don't own a Conbee II stick, hopefully someone with experience will chime in and help

**Comment by jddayley** [comment]
Is there a command that I could run to determine that information?  Otherwise, I'm going to reinstall the script

**Comment by tteck** [comment]
Look under the LXC's options tab

![Screenshot 2022-06-07 7 34 37 AM](https://user-images.githubusercontent.com/21342670/172370059-54085235-f950-4f67-b552-e399b151371c.png)

**Comment by jddayley** [comment]
<img width="391" alt="Screen Shot 2022-06-07 at 7 38 13 AM" src="https://user-images.githubusercontent.com/29357870/172370553-0f0e3533-132e-4f62-9a16-e415dfec75e9.png">

**Comment by schiz0phr3ne** [comment]
Did you tried to update your Conbee II with her ID (`/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2495756-if00`) ?

In Zigbee2MQTT, we can use ID or logical name.

**Comment by nicedevil007** [comment]
Can you post your entire LXC config file here?
To get the conbee up and running wasn't an easy task inside a LXC but I got it working on a friends environment where I still have access to :)

Maybe I can help out.
