### ISSUE TITLE
Dashy Update / Version

### ISSUE THREAD

**Issue by Nexow91** [tteck/Proxmox#2693]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello, 

following problem when I install Dashy LXC the latest version is not installed this would be 2.1.2 moment is installed. 2.1.1. the problem is that this version has some bugs with the authentication so that user input or changes are difficult to update. LXC has been successfully installed on Debian 12 Bookworm. Even a subsequent command "update" in the LXC container did not result in another update. 

Would it be possible to add a version selector or at least be able to switch to the latest version? 

Unfortunately, I do not know how the LXC was installed or which steps are necessary to update to version 2.1.2 or to downgrade. 

Apart from that, I love the TTECK scripts and they have already made my life a lot easier. 

Best regards

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2024-03-24 112902](https://github.com/tteck/Proxmox/assets/73191540/5a772d48-2103-4274-b6ae-6b460a95184e)

### Please provide detailed steps to reproduce the issue.

Install Dashy LXC, check version, check bug report on Dashy Github.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues?q=is%3Aissue+is%3Aclosed+dashy
