### ISSUE TITLE
Monitor-All restarts excluded VM

### ISSUE THREAD

**Issue by Teberon** [tteck/Proxmox#2695]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Within /usr/local/bin/ping-instances.sh I have added 100 after the required line and then reloaded and started the service
```# To specify which CT/VM should be excluded, add the CT/VM ID at the end of the line where ExecStart=/usr/local/bin/ping-instances.sh is specified.
# For example: ExecStart=/usr/local/bin/ping-instances.sh 100 102
# Virtual machines without the QEMU guest agent installed must be excluded.

ExecStart=/usr/local/bin/ping-instances.sh 100```

but it still restarted the VM 100.

Please disregard Linux distro as it is the script for Proxmox itself,

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```root@pve01:~# nano /etc/systemd/system/ping-instances.service
root@pve01:~# systemctl daemon-reload
root@pve01:~# systemctl start ping-instances
root@pve01:~# cat /var/log/ping-instances.log
No QEMU guest agent configured
Sun Mar 24 06:42:42 PM CET 2024: VM 100 is not responding, restarting...
VM 9000 is not running
Skipping 9000 because it is set not to boot
Sun Mar 24 06:43:11 PM CET 2024: Pausing for 5 minutes...```

### Please provide detailed steps to reproduce the issue.

1. Install Monitor-All
2. edit /usr/local/bin/ping-instances.sh
3. add VM id behind 'ExecStart=/usr/local/bin/ping-instances.sh'
4. systemctl daemon-reload
5. systemctl start ping-instances
6. Observe VM being restarted

**Comment by tteck** [comment]
did you `systemctl stop ping-instances` before editing?

**Comment by tteck** [comment]
![Screenshot 2024-03-24 2 06 39 PM](https://github.com/tteck/Proxmox/assets/21342670/774c302b-cca4-4772-8568-f1717ddde7be)

**Comment by Teberon** [comment]
I have not read that part ... closings issue

**Comment by fuelflo** [comment]
This explananation is missing on the new website, unless i just didn't find it. Would be nice to re-add it again.

> ![Screenshot 2024-03-24 2 06 39 PM](https://private-user-images.githubusercontent.com/21342670/316330464-774c302b-cca4-4772-8568-f1717ddde7be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDQ4OTEsIm5iZiI6MTcxNjY0NDU5MSwicGF0aCI6Ii8yMTM0MjY3MC8zMTYzMzA0NjQtNzc0YzMwMmItY2NhNC00NzcyLTg1NjgtZjE3MTdkZGRlN2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzNDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MDYxOWMyYjgxYWEyZTlkNjUxMDhlYmNiMTFjMDVlMWM4ZWZiNzAwMTY4MmNhY2JkZGYyZDZkNDEwNGQzM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nu_smf4AsEMYjJtPmCKn2zUSW__thmxCtCxEiMupIj4)

**Comment by tteck** [comment]
Added as "Post Install" button
