### ISSUE TITLE
vs-code-server ERROR 127@81

### ISSUE THREAD

**Issue by martinjgrunwald** [tteck/Proxmox#2698]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I created a fresh Debian 12 LXC and tried to run the script for installing vs-code-server. This is the output of the script:
```
✓ Installed Dependencies
 - Installing Code-Server v4.22.1...‼ ERROR 127@81 Unknown failure occured.
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Create LXC container
Install curl
Run `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/code-server.sh)"`
ERROR 127@81 occurs

**Comment by tteck** [comment]
🔁 I cannot reproduce the problem on my side, I cannot address an issue that appears to be functioning correctly here.

```
    ____       __    _           
   / __ \___  / /_  (_)___ _____ 
  / / / / _ \/ __ \/ / __ `/ __ \
 / /_/ /  __/ /_/ / / /_/ / / / /
/_____/\___/_.___/_/\__,_/_/ /_/ 
                                 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: debian
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Debian LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```
```
   ______          __        _____                          
  / ____/___  ____/ /__     / ___/___  ______   _____  _____
 / /   / __ \/ __  / _ \    \__ \/ _ \/ ___/ | / / _ \/ ___/
/ /___/ /_/ / /_/ /  __/   ___/ /  __/ /   | |/ /  __/ /    
\____/\____/\__,_/\___/   /____/\___/_/    |___/\___/_/     
 
This will Install Code Server on debian. Proceed(y/n)?y
 ✓ Installed Dependencies
 ✓ Installed Code-Server v4.22.1 on debian
Code Server should be reachable by going to the following URL.
         http://192.168.86.250:8680 
```

**Comment by tteck** [comment]
Did you create the Debian 12 LXC using the script in this repo?

Line 81:

https://github.com/tteck/Proxmox/blob/e1e0b4af9ee5c58b69c4362f697aaedf7299f4ed/misc/code-server.sh#L81

**Comment by martinjgrunwald** [comment]
No, I manually created the LXC. Which script should I use to create it?

**Comment by tteck** [comment]
Just install `sudo`, execute `apt install -y sudo` in the LXC console.

**Comment by tteck** [comment]
You'll need `curl` also, execute `apt install -y curl`

**Comment by martinjgrunwald** [comment]
Previously curl was missing but I got this warning:
```
bash: line 77: curl: command not found
‼ ERROR 1@77 Unknown failure occured.
‼ ERROR 1@77 Unknown failure occured.
```
This helped me track down the issue. Maybe you could implement a similar warning for when sudo is missing? Now, with curl and sudo installed the installation worked fine.

**Comment by tteck** [comment]
The Debian LXC script has those dependencies installed.
https://github.com/tteck/Proxmox/blob/e1e0b4af9ee5c58b69c4362f697aaedf7299f4ed/install/debian-install.sh#L16-L20
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/debian.sh)"
```

**Comment by martinjgrunwald** [comment]
Alright, that should suffice then 😄
