### ISSUE TITLE
How do I add a ssh-key after creating the lxc-container?

### ISSUE THREAD

**Issue by tristan-k** [tteck/Proxmox#27]
After creating the lxc container how do I add a ssh id_rsa.pub to the container for passwordless access?

**Comment by tteck** [comment]
https://www.pragmaticlinux.com/2021/05/configure-ssh-for-login-without-a-password/

**Comment by tristan-k** [comment]
How can I copy the ssh pubkey if there is no root password?

**Comment by tteck** [comment]
Webmin System Administration is a useful tool for LXC's

**Comment by tristan-k** [comment]
> Webmin System Administration is a useful tool for LXC's

Seriously? Seems like overkill. Why not add a prompt for a ssh-key in the install script or ask for root password?
