### ISSUE TITLE
Cannot run Frigate & script not available in the catalog for fresh install

### ISSUE THREAD

**Issue by vdiogo** [tteck/Proxmox#2709]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I ran the Frigate installation script 2 months back from here: https://tteck.github.io/Proxmox/

As the Coral USB was not available, and I started reading loads of issues caused by lack of performance without the USB stick, I ordered it and it arrived today (had to be manufactured, shipped, ...).

As I was picking up from where I left the LXC, I cannot get my head around how to run it (the IP is defined as static, but there is no IP defined in the container settings), so I thought on re-starting the process from scratch.

Now I cannot find the installation script anymore on https://tteck.github.io/Proxmox/ however, I do see a file [here](https://github.com/tteck/Proxmox/blob/main/misc/frigate-support.sh) (which I don't know if applicable, a leftover from the previous script, ...).

Anyway, any guidance would be helpful so I can start the "Frigate" process properly.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
