### ISSUE TITLE
Heimdal Updater broken

### ISSUE THREAD

**Issue by Deekerman** [tteck/Proxmox#271]
Running the Heimdal updater will only bring you to Version 2.4.11 and the current release is 7.7

There is some major fixes in the current one which unbreak the program (500 error)

**Comment by tteck** [comment]
Current is showing as 2.4.12
https://github.com/linuxserver/Heimdall/releases

**Comment by Deekerman** [comment]
its more than possible that I dont know what im talking about 

but i had seen this:
https://github.com/heimdal/heimdal/releases/tag/heimdal-7.7.0

**Comment by Deekerman** [comment]
WOW. so....yeah. i see the problem. Im dumb af.

Sorry to have wasted your time.
