### ISSUE TITLE
Issue running install scripts

### ISSUE THREAD

**Issue by EvanDevvv** [tteck/Proxmox#2713]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running any install scripts, it shows a blank line for a few seconds and then does nothing.

This is a fresh installation of Proxmox. It worked fine on my other installations.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot_1](https://github.com/tteck/Proxmox/assets/123332223/4559aef6-effb-4400-84d3-172aba957214)

### Please provide detailed steps to reproduce the issue.

First paste a install script into the pve terminal, and wait a few seconds.

**Comment by tteck** [comment]
🌐 It seems that you're facing a network problem, _probably_ linked to DNS.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/2699
