### ISSUE TITLE
Dashy update - cant find installation

### ISSUE THREAD

**Issue by francismiles1** [tteck/Proxmox#2726]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I tried to update Dashy today. Running your script in the LXC always resolves to:
✗ No Dashy Installation Found!

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

in the lxc container console, I pasted 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/dashy.sh)"

Click through "update functions for Dashy LXC"

Results in ✗ No Dashy Installation Found!

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

https://github.com/tteck/Proxmox/issues?q=dashy

🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.
