### ISSUE TITLE
Nginx Proxy Manager not updating (fix)

### ISSUE THREAD

**Issue by AlexTryHarder** [tteck/Proxmox#2733]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

[ERROR] in line 142: exit code 0: while executing command pnpm run build &> /dev/null

To fix run in shell: export NODE_OPTIONS=--openssl-legacy-provider

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Thanks
