### ISSUE TITLE
Appdaemon removed from Home Assistant Core LXC?

### ISSUE THREAD

**Issue by SergioRius** [tteck/Proxmox#2735]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Today I've gone through the procedure for upgrading HA to 2024.4 and leave behind the python 3.11 and then realized that AppDaemon installation implemented in [this PR](https://github.com/tteck/Proxmox/pull/1167) has been removed.

Perhaps is there's another way of installing it now, or installed by default with another service name?

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
Yes, it has been removed. It now requires a manual install.
