### ISSUE TITLE
PVE 8.1.10, Plex LXC errors out on "A problem occured while trying to create container.: numeric argument required"

### ISSUE THREAD

**Issue by vitteloil** [tteck/Proxmox#2736]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

I'm trying out the Plex LXC script on an upgraded PVE (8.1.10) and I'm hit with an `A problem occured while trying to create container.: numeric argument required` error. I tried many combinations of 'Advanved' settings selections, without luck. Verbose mode doesn't seem to be more verbose too, unless I missunderstood what it is.

Thanks !

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/370841/d62a9040-52f0-4247-bad1-7a8c8dd8667a)

### Please provide detailed steps to reproduce the issue.

- PVE 8.1.10
- Open a shell through the UI 
- Run `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/plex.sh)"`
- Press Enter, Enter, Enter, etc.. to validate all defaults

Result : Plex LXC : A problem occured while trying to create container.: numeric argument required

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    ____  __             __  ___         ___          _____                          
   / __ \/ /__  _  __   /  |/  /__  ____/ (_)___ _   / ___/___  ______   _____  _____
  / /_/ / / _ \| |/_/  / /|_/ / _ \/ __  / / __ `/   \__ \/ _ \/ ___/ | / / _ \/ ___/
 / ____/ /  __/>  <   / /  / /  __/ /_/ / / /_/ /   ___/ /  __/ /   | |/ /  __/ /    
/_/   /_/\___/_/|_|  /_/  /_/\___/\__,_/_/\__,_/   /____/\___/_/    |___/\___/_/     
                                                                                      
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: plex
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Plex LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Plex Media Server Repository
 ✓ Installed Plex Media Server
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Plex should be reachable by going to the following URL.
             http://192.168.86.250:32400/web
```

**Comment by vitteloil** [comment]
I'll try to debug this by retrieving the .func files, etc.. locally and run it

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
