### ISSUE TITLE
Mongod fails to start in Unifi LXE

### ISSUE THREAD

**Issue by andrzejpolis** [tteck/Proxmox#2738]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installation Unifi server doesn't start due to 
```
[2024-04-05 22:10:40,809] <mongo-db> INFO  mongo  - Database process stopped, code=132
[2024-04-05 22:10:43,810] <mongod-tail> WARN  mongo  - Mongo log not found during startup
[2024-04-05 22:10:43,821] <mongo-db> WARN  mongo  - Stop listening to Mongo logs after process has exited
```
It seems mongod process doesn't start because of issues described e.g. [here](https://stackoverflow.com/questions/68937131/illegal-instruction-core-dumped-mongodb-ubuntu-20-04-lts)
When calling mongod from shell I get the same error:
```
root@unifi:~# mongod
Illegal instruction
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by andrzejpolis** [comment]
Seems like it is a recent update that changed mongod from 4.x to 7.x. Most likely based on recent 8.1 Unifi Controller support for Mongo 7.

**Comment by tteck** [comment]
The script installs version 7 of MongoDB
https://github.com/tteck/Proxmox/blob/fe0b379ed1526adccfb5c0f7488eba1a05fce866/install/unifi-install.sh#L32

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
   __  __      _ _____ 
  / / / /__   (_) __(_)
 / / / / __ \/ / /_/ / 
/ /_/ / / / / / __/ /  
\____/_/ /_/_/_/ /_/   
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: unifi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Unifi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Eclipse Temurin JRE
 ✓ Installed MongoDB
 ✓ Installed UniFi Network Server
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Unifi should be reachable by going to the following URL.
         https://192.168.86.250:8443 
```

![Screenshot 2024-04-05 5 14 37 PM](https://github.com/tteck/Proxmox/assets/21342670/6fd4f441-50d6-4d86-8544-63d7414c1794)

**Comment by andrzejpolis** [comment]
As this seems to be CPU related I'm installing it on Intel N5095 based host. This CPU lacks AVX instructions set required for MongoDB 7.x.
If MongoDB 4.x has a better compatibility wouldn't be a better choice to stick to the older version? Or at least provide an option?

**Comment by tteck** [comment]
MongoDB 4.4 has reached its [End of Life](https://www.mongodb.com/legal/support-policy/lifecycles), meaning no more security updates.

The N5095 does support AVX according to the [spec sheet](https://www.intel.com/content/www/us/en/products/sku/212322/intel-celeron-processor-n5095-4m-cache-up-to-2-90-ghz/specifications.html) (Instruction Set Extensions)

![Screenshot 2024-04-05 5 39 03 PM](https://github.com/tteck/Proxmox/assets/21342670/8ebc6f62-7189-4532-90ca-c60cdc49cf45)

**Comment by tteck** [comment]
What is the output from the command `grep -o -m1 'avx[^ ]*' /proc/cpuinfo`?

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by andrzejpolis** [comment]
> What is the output from the command `grep -o -m1 'avx[^ ]*' /proc/cpuinfo`?

Output from the command is obviously empty. 

I don't expect to rollback to MongoDB 4.x as I understand 7.x is a better choice for people having newer CPUs. 
My suggestion would be to create a configuration option or separate scripts to satisfy both groups. Would that be possible?

**Comment by indistinctTalk** [comment]
I started looking into this but seems Mongo 4.4 is not being built for bookworm. To get around this situation I created a docker LXC and then used [linuxserver.io](https://docs.linuxserver.io/images/docker-unifi-network-application).

**Comment by PilaScat** [comment]
Is possibile to run MongoDB 5 without AVX, with a proper flag
It's possibile to add this to the script for who doesn't have the requirement? As I see a lot of people...
Or even a version without mongo, so that you can install your preferred version

**Comment by tteck** [comment]
https://stackoverflow.com/questions/68937131/illegal-instruction-core-dumped-mongodb-ubuntu-20-04-lts
