### ISSUE TITLE
Setting up CrowdSec Repository...‼ ERROR 127@65 Unknown failure occured

### ISSUE THREAD

**Issue by talltechy** [tteck/Proxmox#274]
proxmox 7.2
no issues running any of your other install scripts

when attempting to run the crowdsec installer it returns the following error:

"Setting up CrowdSec Repository...‼ ERROR 127@65 Unknown failure occured."

**Comment by tteck** [comment]
make sure `curl` is installed, `apt install curl` or, for a newly created LXC needs a reboot before adding CrowdSec. 🤷🏻‍♂️

**Comment by talltechy** [comment]
curl is already installed on the host

`~# apt install curl  
Reading package lists... Done  
Building dependency tree... Done  
Reading state information... Done  
curl is already the newest version (7.74.0-1.3+deb11u1).  
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by talltechy** [comment]
ah.. ignore... this doesn't auto-build the container like the other scripts it seems, so i need to pre-build the container.

my bad!
