### ISSUE TITLE
Scripts exit with error about not using Bash shell, even though script is ran using `bash -c`

### ISSUE THREAD

**Issue by lightmaster** [tteck/Proxmox#2740]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Running the command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/debian.sh)"` pulls up the initial prompt asking you to click yes to proceed, but then throws this error:

```
✗ Your default shell is currently not set to Bash. To use these scripts, please switch to the Bash shell.
```

Considering that the command copy/pasted from your site is ran using `bash -c`, it's has to be running in a bash shell. Even if I manually change to bash shell using `bash`, then run the command, it still won't let it get past the initial yes/no prompt

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. Set default shell to zsh
2. run script that with `bash -c` in it.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/2536

**Comment by lightmaster** [comment]
What about adding a check for a default shell that's not bash and then adding a prompt about if you aren't using bash as your *default* shell, then support will not be given? Then you can also have a check to make sure that it's at least ran with `bash -c` and exit if it's not. This gives a decent compromise, ensuring that for people that want to risk it and use another default shell, then they are at least warned (same as selecting a different LXC OS).

**Comment by tteck** [comment]
You can either employ the workaround or revert to the Bash shell, these will remain the only options available to utilize the scripts.
