### ISSUE TITLE
NginxProxyManager not installing npm user, getting error in logs

### ISSUE THREAD

**Issue by DrEVILish** [tteck/Proxmox#2745]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Running a standard instance of NginxProxyManager, I have performed 'update' before posting, still getting the following error message.

Apr 06 14:25:04 nginxproxymanager node[148]: [4/6/2024] [2:25:04 PM] [Setup    ] <E2><80><BA> <E2><9A><A0>  CommandError: error: /etc/logrotate.d/nginx-proxy-manager:2 unknown user 'npm'
Apr 06 14:25:04 nginxproxymanager node[148]: error: found error in /data/logs/*_access.log /data/logs/*/access.log , skipping
Apr 06 14:25:04 nginxproxymanager node[148]: error: /etc/logrotate.d/nginx-proxy-manager:16 unknown user 'npm'
Apr 06 14:25:04 nginxproxymanager node[148]: error: found error in /data/logs/*_error.log /data/logs/*/error.log , skipping
Apr 06 14:25:04 nginxproxymanager node[148]:     at /app/lib/utils.js:16:13
Apr 06 14:25:04 nginxproxymanager node[148]:     at ChildProcess.exithandler (node:child_process:410:5)
Apr 06 14:25:04 nginxproxymanager node[148]:     at ChildProcess.emit (node:events:513:28)
Apr 06 14:25:04 nginxproxymanager node[148]:     at maybeClose (node:internal/child_process:1100:16)
Apr 06 14:25:04 nginxproxymanager node[148]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________ __  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                                      /____/                            /____/             
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: nginxproxymanager
Using Disk Size: 4
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Nginx Proxy Manager LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python Dependencies
 ✓ Installed Openresty
 ✓ Installed Node.js
 ✓ Installed pnpm
Would you like to install an older version (v2.10.4)? <y/N> 
 ✓ Downloaded Nginx Proxy Manager v2.11.1
 ✓ Set up Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Created Service
 ✓ Customized Container
 ✓ Started Services
 ✓ Cleaned
 ✓ Completed Successfully!

Nginx Proxy Manager should be reachable by going to the following URL.
         http://192.168.86.250:81
```
![Screenshot 2024-04-06 9 42 19 AM](https://github.com/tteck/Proxmox/assets/21342670/0ce2298a-1a2f-4457-9a7b-e32d0f52cbb3)

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by githubsean** [comment]
I found the same issue. To expand on what is said above (as opposed to opening another issue - happy to do so if you want).

Inside the container, if I run `systemctl status`, I see that the system id degraded.
Just running `systemctl` shows me that the logrotate.service unit has failed.
I then ran `journalctl -u logrotate.service` to get the details of why it might have failed. You may have to have the npm container up and running for a little bit in order that you get at least one call to the service. It is on a timer that runs once a day (`systemctl cat logrotate.timer`)

```
May 26 00:00:21 npmlocal systemd[1]: Starting Rotate log files...
May 26 00:00:21 npmlocal logrotate[553]: error: nginx-proxy-manager:2 unknown user 'npm'
May 26 00:00:21 npmlocal logrotate[553]: error: found error in /data/logs/*_access.log /data/logs/*/access.log , skipping
May 26 00:00:21 npmlocal logrotate[553]: error: nginx-proxy-manager:16 unknown user 'npm'
May 26 00:00:21 npmlocal logrotate[553]: error: found error in /data/logs/*_error.log /data/logs/*/error.log , skipping
May 26 00:00:21 npmlocal logrotate[553]: error: found error in file nginx-proxy-manager, skipping
May 26 00:00:21 npmlocal systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
May 26 00:00:21 npmlocal systemd[1]: logrotate.service: Failed with result 'exit-code'.
May 26 00:00:21 npmlocal systemd[1]: Failed to start Rotate log files.

```

Looking in /etc/logrotate.d/nginx-proxy-manager, there is a line there that says `su npm npm` which seems to be indicating that the logrotate config expects that the npm service will run as the npm user.

```
root@npmlocal:/etc/logrotate.d# cat nginx-proxy-manager
/data/logs/*_access.log /data/logs/*/access.log {
    su npm npm
    create 0644
    weekly
    rotate 4
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
    /bin/kill -USR1 `cat /run/nginx.pid 2>/dev/null` 2>/dev/null || true
    endscript
}

/data/logs/*_error.log /data/logs/*/error.log {
    su npm npm
    create 0644
    weekly
    rotate 10
    missingok
    notifempty
    compress
    sharedscripts
    postrotate
    /bin/kill -USR1 `cat /run/nginx.pid 2>/dev/null` 2>/dev/null || true
    endscript

```

I guess there may be two solutions. One would be to setup the npm user within the container - but that may also mean changing other things around how npm is installed. Alternatively, maybe the `su npm npm` lines can just be removed from the nginx-proxy-manager logrotate config. For what it's worth, I did the 2nd option and commented out the lines and everything seemed to work.

**Comment by jvonhoff** [comment]
Same here... I think I crawled deep enough to see the logrotate config getting copied from the docker install of NPM, where I'm assuming the npm user is used to rotate the logs.

I also commented out the `su npm npm` lines in the above file `/etc/logrotate.d/nginx-proxy-manager` and all seems to be working.  Matrix is a chatty service, and it creates 1GB log files pretty quickly.

**Comment by volteret4** [comment]
Sorry for resurrecting this, but I cant find the solution to this, I tried comenting both lines with `su npm npm`  whitout success. Sorry for asking here, I know its not the best way but I dont find this error on any other site. 

Thanks in advance for your comprehension.

EDIT: I forgot to mention that I cant use the script to update the LXC Container either:
`[ERROR] in line 136: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null`
