### ISSUE TITLE
Unable to install nginx proxy manager with ubuntu 23

### ISSUE THREAD

**Issue by emanuellopes** [tteck/Proxmox#2750]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Install Nginx Proxy manager and select the Ubuntu 23.
The installation will take some time but will crash after setting .nvm in bash file

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 23.10

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Advanced settings

- container type: unprivileged
- root password: empty
- container id: 104
- hostname: nginxproxymanager
- disk size: 4GB
- CPU cores: 1
- RAM: 1024
- bridge: vmbr1
- IP Address: 192.168.100.104/24
- gateway: 192.168.100.1
- APT cacher: default
- disable ipv6: yes
- MTU: empty
- DNS: empty
- DNS IP: empty
- MAC: empty
- VLAN: 100

<img width="782" alt="Screenshot 2024-04-06 at 14 19 30" src="https://github.com/tteck/Proxmox/assets/6977270/623a1a99-0e76-459b-9932-8aede72aae71">

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
