### ISSUE TITLE
Pi hole SSH Login

### ISSUE THREAD

**Issue by stanus74** [tteck/Proxmox#2754]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

what is the login data for SSH

The login data for the web interface does not work

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
