### ISSUE TITLE
Paperless ngx install | command not found

### ISSUE THREAD

**Issue by narucx** [tteck/Proxmox#2756]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I run the command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"` like it says on your site, but I get multiple "command not found" like you can see in the screenshot

The LXC was freshly created with Ubunntu 23.10 template
Only thing I did before running the command was updating the lxc

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 23.10

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/75908696/a76fc2c7-bbf7-431f-8a1b-130a5624d1ba)

**Comment by tteck** [comment]
![Screenshot 2024-04-08 5 33 28 AM](https://github.com/tteck/Proxmox/assets/21342670/53d2ec6d-7a6f-4df6-a320-82c4c4162eca)
