### ISSUE TITLE
Cant install Home Assistant VM Script on Promox

### ISSUE THREAD

**Issue by eav86** [tteck/Proxmox#2757]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

i tried to reinstall the HA via the VM Script you created. I already had in installed once but had to delete the VM because of issues.
If i tried to install it now with "bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)" "

Well nothing happens is just comes up with the empty command line again without executing the script it seems.
So i wanted to know if its possible the issue is that i have to clean something from the Old Install ? The VM is completly deleted

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
🌐 It seems that you're facing a network problem, _probably_ linked to DNS.

**Comment by eav86** [comment]
tried using "ping github.com" works fine. i even accidently used "ping bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm.sh)" " and it completly showed me the content of the script.

Any idea how to fix it ?

**Comment by eav86** [comment]
ok. got if fixed. by uploading the script to my own page... no idea where the issue was with github and my DNS. Thank you a lot ffor the quick support
