### ISSUE TITLE
pvesm: command not found / STORAGE_MENU: unbound variable

### ISSUE THREAD

**Issue by rdtm443** [tteck/Proxmox#276]
Hello

First of all, many thanks for offering this super interesting project - highly appreciated !

Unfortunately I am getting some weird error messages during installation of HAOS on Proxmox 7:

pvesm: command not found
STORAGE_MENU: unbound variable

[image](https://user-images.githubusercontent.com/25002690/172893870-2a1bc7aa-7188-478f-b6cd-8995010be469.png)

Latest updates installed.

Any idea? 

Many thanks !

**Comment by tteck** [comment]
Run `pvesm status -content images | awk 'NR>1'` in the Proxmox shell and share the results

**Comment by rdtm443** [comment]
> Run `pvesm status -content images | awk 'NR>1'` in the Proxmox shell and share the results

Ran in the proxmox shell (via web gui) i get this output: 
local-lvm     lvmthin     active       354791424               0       354791424    0.00%

When i run it via ssh (putty), i get 'pvesm: command not found'. 

Thanks a lot !

**Comment by tteck** [comment]
I also noticed in the image that no VM ID was assigned

**Comment by rdtm443** [comment]
> I also noticed in the image that no VM ID was assigned

Same result if I enter a VM ID manually... basically pvesm not found (via ssh).

**Comment by tteck** [comment]
only use the Proxmox shell

**Comment by rdtm443** [comment]
> only use the Proxmox shell

Gosh, I suspected so... The guide on community.home-assistant.io is wrong then, as it explicitly states to use putty. 

Thank you so much for your quick help, VM up and running now :)

**Comment by tteck** [comment]
I'd suggest to `kanga_who` to remove the reference for a putty install. If SSH is needed, the user can add it after the Home Assistant OS VM creation.
I've never had the need to SSH into my Proxmox server
