### ISSUE TITLE
ISSU when updating the LXCs

### ISSUE THREAD

**Issue by quorle** [tteck/Proxmox#2768]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

No matter which LXC I want to update, the same error always appears (see screenshot). This applies to Heimdall, Vaultwarden, etc...

The command I use:
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/heimdalldashboard.sh)"`

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Unbenannt](https://github.com/tteck/Proxmox/assets/38273154/2db09463-3b88-496d-b726-2f161bc57019)

**Comment by tteck** [comment]
What `user`?

**Comment by quorle** [comment]
user = root

I installed all LXC via your scripts. Without having created another user afterwards.

**Comment by tteck** [comment]
It's an issue on your end. Are you using SSH?

**Comment by quorle** [comment]
Oh, OK. 

Unfortunately I didn't get any help in the discussion. I use the Proxmox console

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
What version of Debian are you using?

**Comment by quorle** [comment]
Debian 11

**Comment by tteck** [comment]
That seems to be the issue, https://github.com/tteck/Proxmox/discussions/2772
