### ISSUE TITLE
File Browser | Error | line 68 command not found

### ISSUE THREAD

**Issue by David-Moreira** [tteck/Proxmox#2775]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Created a new LCX with debian 12.
Ran Filebrowser script & got the following error:
![image](https://github.com/tteck/Proxmox/assets/22283161/ae05470a-d0fc-4e84-bd3e-f2166332069d)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by David-Moreira** [comment]
I guess I was missing curl. Feel free to evaluate and close.

**Comment by tteck** [comment]
It appears that FileBrowser was added to an LXC instance not initialized by the scripts in this repository, as `curl` is included with each LXC script provided here.

**Comment by tteck** [comment]
Easily solved. https://github.com/tteck/Proxmox/commit/4fecdcaa6a438bf024701a0f1773e31104922475

**Comment by David-Moreira** [comment]
> Easily solved. [4fecdca](https://github.com/tteck/Proxmox/commit/4fecdcaa6a438bf024701a0f1773e31104922475)

Thanks. Cheers.
