### ISSUE TITLE
Install script fails for ActualBudget

### ISSUE THREAD

**Issue by pusta** [tteck/Proxmox#2778]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the ActualBudget LXC install script on the Proxmox host console. it fails out at this part:

npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.2
npm notice Run npm install -g npm@10.5.2 to update!
npm notice 
 ✓ Installed Node.js
 - Installing Actual Budget   Cloning into '/opt/actualbudget'...
-remote: Enumerating objects: 1617, done.
remote: Counting objects: 100% (848/848), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 1617 (delta 641), reused 654 (delta 568), pack-reused 769
Receiving objects: 100% (1617/1617), 3.54 MiB | 17.79 MiB/s, done.
Resolving deltas: 100% (896/896), done.
|➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable

➤ YN0000: · Yarn 4.0.1
➤ YN0000: ┌ Resolution step
➤➤ YN0000: └ Completed in 0s 312ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ actual-sync@workspace:. doesn't provide @babel/core (pd13b1), requested by @babel/preset-typescript.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: ⠧ ===============================================================================--
/
[ERROR] in line 39: exit code 0: while executing command $STD yarn install

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.2
npm notice Run npm install -g npm@10.5.2 to update!
npm notice 
 ✓ Installed Node.js
 - Installing Actual Budget   Cloning into '/opt/actualbudget'...
-remote: Enumerating objects: 1617, done.
remote: Counting objects: 100% (848/848), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 1617 (delta 641), reused 654 (delta 568), pack-reused 769
Receiving objects: 100% (1617/1617), 3.54 MiB | 17.79 MiB/s, done.
Resolving deltas: 100% (896/896), done.
|➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable

➤ YN0000: · Yarn 4.0.1
➤ YN0000: ┌ Resolution step
➤➤ YN0000: └ Completed in 0s 312ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ actual-sync@workspace:. doesn't provide @babel/core (pd13b1), requested by @babel/preset-typescript.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: ⠧ ===============================================================================--
/
[ERROR] in line 39: exit code 0: while executing command $STD yarn install

### Please provide detailed steps to reproduce the issue.

Run the ActualBudget script

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/2751

**Comment by tteck** [comment]
🔁 If I cannot reproduce the problem on my side, I cannot address an issue that appears to be functioning correctly here.

```
    ___        __              __   ____            __           __
   /   | _____/ /___  ______ _/ /  / __ )__  ______/ /___ ____  / /_
  / /| |/ ___/ __/ / / / __ `/ /  / __  / / / / __  / __ `/ _ \/ __/
 / ___ / /__/ /_/ /_/ / /_/ / /  / /_/ / /_/ / /_/ / /_/ /  __/ /_
/_/  |_\___/\__/\__,_/\__,_/_/  /_____/\__,_/\__,_/\__, /\___/\__/
                                                  /____/
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: 04/11/2024
Container ID: 110
Using Hostname: actualbudget
Using Disk Size: 4
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Actual Budget LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Actual Budget
 ✓ Created Service
 ✓ Cleaned
 ✓ Completed Successfully!

Actual Budget should be reachable by going to the following URL.
         http://192.168.86.250:5006 
```
Try giving it another vCPU to help during the build process.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/9c19734b5b3e0910bc2fa3dc60867251003b58bd
