### ISSUE TITLE
Vaultwarden Admin Page

### ISSUE THREAD

**Issue by millie75** [tteck/Proxmox#278]
How can I add the Admin token for Vault warden - when going to https://vault.domain.com/admin I get the below

The admin panel is disabled, please configure the 'ADMIN_TOKEN' variable to enable it

Many thanks

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/250

**Comment by millie75** [comment]
Thanks

**Comment by tteck** [comment]
https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
Line 234
