### ISSUE TITLE
LXC is not supported by OpenMediaVault

### ISSUE THREAD

**Issue by MDBInd** [tteck/Proxmox#2780]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

OpenMediaVault does not currently usable in an LXC.
Might I suggest that the script gets refactored to install as a VM which is fully supported.

From the official website:
openmediavault does not support the installation in LXC or any other container based solution.
https://docs.openmediavault.org/en/stable/installation/index.html

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2024-04-12 at 08-44-16 pcc-omv lan - openmediavault Workbench](https://github.com/tteck/Proxmox/assets/86257053/f4c8d09b-c60e-4c25-8095-fca8cda6769e)

### Please provide detailed steps to reproduce the issue.

Install LXC using default settings.
Try and add a Filesystem mount (in my case using ZFS at mp0)
The Filesystem select is blank and cannot be filled in.

I tried using the openmediavault-sharerootfs plugin but get the error: WARNING: No root filesystem has been found.

I tried adding a Disk and Shared Folder but nothing works as the LXC is not supported by OMV.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
