### ISSUE TITLE
Dashy Update Broken maybe?

### ISSUE THREAD

**Issue by jershbytes** [tteck/Proxmox#279]
Dashy is showing a new update and like last time I just ran the script to update. It has no issue backing up the config file or stooping dahsy but when it hits the update portion it just kills the script and drops down to terminal. 

```
Stopping Dashy... ✔[m 
 Backup conf.yml... ✔[m 
 Updating Dashy... root@dashy:~#
 ```
 This is what it looks like while running the script. 
 
 I've even tried to copy and paste the script in the container itself and it just fails as well.

**Comment by tteck** [comment]
Can't replicate on my end
```
  _____            _           
 |  __ \          | |          
 | |  | | __ _ ___| |__  _   _ 
 | |  | |/ _  / __|  _ \| | | |
 | |__| | (_| \__ \ | | | |_| |
 |_____/ \__,_|___/_| |_|\__, |
          UPDATE          __/ |
                         |___/ 

 Stopping Dashy... ✔ 
 Backup conf.yml... ✔ 
 Updating Dashy... ✔ 
 Restoring conf.yml... ✔ 
 Cleaning... ✔ 
 Starting Dashy... ✔ 
 Finished 

root@dashy:~# 
```

**Comment by jershbytes** [comment]
This is odd I've made no changes to the container what so ever and this is somehow failing no matter how I run it. Thanks for trying on your end. Sorry for opening this up thought maybe was something was failing over all

**Comment by tteck** [comment]
I'll take a look at the script to see if I can find a reason

**Comment by tteck** [comment]
If you would try
```

```
and let me know the results

**Comment by carlreid** [comment]
I just ran the update then found this issue (with slight panic), however my update went smoothly - so unfortunately (or fortunately?) can't help debug anything here.

Cheers for the great work @tteck 👍

**Comment by jershbytes** [comment]
So I've tried that and got the same error. I even reinstalled yarn and also tried to run the commands by themself to try and update them. I think at this point it's more or less my container failing to build it out god know why. But at this point ill just grab my config and re do dashy. Thanks for help.
