### ISSUE TITLE
error in update script for nginx 

### ISSUE THREAD

**Issue by sammy708** [tteck/Proxmox#2811]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

When executing `bash -c "$(wget -qLO - `https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"` in LXC Console I get the following error:
` - Installing pnpm  /
[ERROR] in line 65: exit code 0: while executing command npm install -g pnpm@8.15 &> /dev/null`

my installed version of nginx is v2.10.4 

Any hints? Thank you!

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

see description

### Please provide detailed steps to reproduce the issue.

execute update script in LXC Console

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2706
