### ISSUE TITLE
Uptime Kuma needs more RAM when update

### ISSUE THREAD

**Issue by schiz0phr3ne** [tteck/Proxmox#282]
Hi @tteck,

I saw today that Uptime Kuma need more RAM when update : at 512 MiB, update crashes quickly after beginning of `npm ci` (I tried several times, to confirm).

```shell
  _    _       _   _                  _  __                     
 | |  | |     | | (_)                | |/ /                     
 | |  | |_v3_ | |_ _ _ __ ___   ___  | ' /_   _ _ __ ___   __ _ 
 | |  | |  _ \| __| |  _   _ \ / _ \ |  <| | | |  _   _ \ / _  |
 | |__| | |_) | |_| | | | | | |  __/ | . \ |_| | | | | | | (_| |
  \____/| .__/ \__|_|_| |_| |_|\___| |_|\_\__,_|_| |_| |_|\__,_|
        | |                                                     
        |_|  UPDATE                                                   

 ✓ Stopped Uptime Kuma
 ✓ Pulled Uptime Kuma
 - Updating Uptime Kuma (Patience)...
Debian GNU/Linux 11 uptimekuma tty1

uptimekuma login:
```

At 1 GiB, no problem : RAM consumption is maximum ~60-62 %, but update can finish.

Something else : any possibility to restrict updates to `latest` tagged releases ? Actually, update can be a `beta` release, as you can see below.

![image](https://user-images.githubusercontent.com/22858496/173665054-fe4724a2-3258-4c9b-a9e0-3f8b2610e751.png)

**Comment by schiz0phr3ne** [comment]
For release which are choosen when updating, maybe ask user at the beginning of the script.
I'm not a `git` expert, and I failed to use `latest` tagged release (1.16.1 at time).

`latest` release :
![image](https://user-images.githubusercontent.com/22858496/173665831-70e519a7-0871-4acc-9391-27e7bbced2ef.png)

Latest release :
![image](https://user-images.githubusercontent.com/22858496/173665954-3a614179-e1ac-4d93-8082-ebc2c64e38ca.png)

**Comment by tteck** [comment]
Thank you for bringing this to my attention.

I set the default ram to 1024 MiB 

If you'd test
```

```
It should only update to latest release, never pre-release.

**Comment by schiz0phr3ne** [comment]
As I am already on `1.16.1`, I can't do a real full update process.
But on test LXC, with your script as local script and removed `?>/dev/null`, it seems to be good (no update on pre-release, and `npm` _warnings_ that nothing is updated).

What about install script ?
I saw `git clone`, so it should clone pre-release ?

Thanks for your reactivity and your work !

**Comment by tteck** [comment]
The install script will create latest **release**
