### ISSUE TITLE
Update script of pihole broken

### ISSUE THREAD

**Issue by CrazyWolf13** [tteck/Proxmox#2831]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Pihole is not updating and bringing up that error below, and I guess instantly exits.

Edit: 
Tried to run the update script with verbose, but there is no advanced section to enable it.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

      ____  ____   __  ______  __    ______
   / __ \/  _/  / / / / __ \/ /   / ____/
  / /_/ // /___/ /_/ / / / / /   / __/   
 / ____// /___/ __  / /_/ / /___/ /___   
/_/   /___/  /_/ /_/\____/_____/_____/   
 
   Updating Pihole   environment: line 60: pihole: command not found
 /
[ERROR] in line 60: exit code 0: while executing command pihole -up

 ✓ Updated Pihole
root@pihole:~# 

### Please provide detailed steps to reproduce the issue.

Install pihole via lxc script and then run update command to update the lxc

**Comment by tteck** [comment]
Did you run the script in the LXC console?

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    ____  ____   __  ______  __    ______
   / __ \/  _/  / / / / __ \/ /   / ____/
  / /_/ // /___/ /_/ / / / / /   / __/   
 / ____// /___/ __  / /_/ / /___/ /___   
/_/   /___/  /_/ /_/\____/_____/_____/   
 
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 8.2.18
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
 -  [i] Pi-hole Core:   up to date
 /  [i] Web Interface:  up to date
 -  [i] FTL:            up to date

  [✓] Everything is up to date!
 ✓ Updated Pihole
```

**Comment by CrazyWolf13** [comment]
> Did you run the script in the LXC console?

Yes

**Comment by tteck** [comment]
Was Pi-hole created utilizing the script from this repo?

**Comment by CrazyWolf13** [comment]
> Was Pi-hole created utilizing the script from this repo?

definitely yes

**Comment by CrazyWolf13** [comment]
funny thing is the pihole command does not work by default, I have to use sudo pihole, only then it's recognized as correct command, however I did not do any changes to that LXC, install like 2 weeks ago.

**Comment by tteck** [comment]
So, you created, and are using a different user?

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by CrazyWolf13** [comment]
> So, you created, and are using a different user?

What?
No I'm not using a different user

**Comment by tteck** [comment]
User `root` doesn't need to use `sudo`

**Comment by CrazyWolf13** [comment]
> User `root` doesn't need to use `sudo`

well yeah that really was what I was asking myself as well, as far as I remember this is a problem since I installed it, but it never bugged me as with sudo it worked.

**Comment by CrazyWolf13** [comment]
> User `root` doesn't need to use `sudo`
@tteck 
Well try it out, I just spun up a fresh new lxc and it has exactly the same behaviour.


Install it via script, 
pct ent er {id}
pihole -> command not found
sudo pihole -> pihole help page

**Comment by tteck** [comment]
Use the LXC console, not the Proxmox shell

**Comment by CrazyWolf13** [comment]
Oh you are referring to that LXC console, got, Apologies.

Consider resolved, thanks.
