### ISSUE TITLE
DNS Caching not in settings of uptime kuma lxc

### ISSUE THREAD

**Issue by CrazyWolf13** [tteck/Proxmox#2832]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Uptime-Kuma needs nscd to have dns-cache, which is currently not installed / not configured correctly.

Look here for reference: https://github.com/louislam/uptime-kuma/issues/4699

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
As far as I know, that option is Docker only 🤷🏻‍♂️ 

you can install `nscd`, but I never got Uptime Kuma to show that option.

**Comment by tteck** [comment]
```
apt install nscd
systemctl enable --now nscd
```
```
nano /etc/nscd.conf
```

**Comment by tteck** [comment]
🧐 As this issue is more a feature to the script, it is considered closed.
