### ISSUE TITLE
OpenMediaVault LXC installation problem

### ISSUE THREAD

**Issue by akirax2304** [tteck/Proxmox#2838]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

during installation of OpenMediaVault there is an error:
`\ Installing OpenMediaVault (Patience) [ERROR] in line 42: exit code 0: while executing command apt-get -y --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault &> /dev/null`

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`\ Installing OpenMediaVault (Patience) [ERROR] in line 42: exit code 0: while executing command apt-get -y --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault &> /dev/null`

### Please provide detailed steps to reproduce the issue.

Trying to install.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
