### ISSUE TITLE
Docker LXC: Root Password needs escaping

### ISSUE THREAD

**Issue by neitsab** [tteck/Proxmox#2843]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi,

Trying to use a Root Password containing the space character breaks the (Docker LXC) script with the error described below. Other special characters such as quote or exclamation mark are fine. Default settings are of course also fine since they use autologin.

In the process of reporting this bug, I also discovered that using `Test` as the first word in the passphrase results in a different error, also described below.

All in all it looks like the Root Password input needs to be properly escaped/quoted.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Error when using space in combination with qote and exclamation mark:

![space-plus-quote-excl](https://github.com/tteck/Proxmox/assets/2963014/8fe5e461-7a43-4b72-b617-c11c0b59c0b4)

```
/dev/fd/63: line 234: [: too many arguments
Using Root Password: Test ' me!
...
400 too many arguments
pct create <vmid> <ostemplate> [OPTIONS]
bash: line 182: exit: A problem occured while trying to create container.: numeric argument required
```

Error when using a single space character:

![single-space](https://github.com/tteck/Proxmox/assets/2963014/5a02a8c5-2b19-4469-8453-411eb13d5f24)

```
dev/fd/63: line 234: [: Test: binary operator expected
Using Root Password: Test passphrase
...
-400 too many argumentsr   
pct create <vmid> <ostemplate> [OPTIONS]
bash: line 182: exit: A problem occured while trying to create container.: numeric argument required
```

### Please provide detailed steps to reproduce the issue.

* paste command `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker.sh)"` in Proxmox node console
* select Advanced settings
* choose Debian 12, Unprivileged
* at `PASSWORD (leave blank for automatic login)` `Set Root Password (needed for root ssh access)` stage, input either `my spaced passphrase` or `Test Passphrase`
* the script fails with one of the aforementioned errors

**Comment by tteck** [comment]
How's this an issue? Don't use spaces.

**Comment by neitsab** [comment]
Why not? Passwords should be able to contain any kind of characters, and a robust script should not trip on the simplest case. If that is your policy though, it would be worth making it explicit (e.g. displaying on screen "Don't use spaces" or documenting it somewhere™).

**Comment by neitsab** [comment]
And as the `Test` password case shows (which is a common password for quick-and-dirty... tests), the input really ought to be escaped.

**Comment by tteck** [comment]
Fixed

**Comment by W00glin** [comment]
I wanted to chime in for anyone who also might have been experiencing this issue, I was using spaces in my DNS list entries. Saw this issue, re-ran the script without spaces in my DNS entries and it ran without issue.
