### ISSUE TITLE
Root password cannot be blank anymore

### ISSUE THREAD

**Issue by pgodzwa** [tteck/Proxmox#2845]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

During configuration, on the "Set root password" stage you can't use blank password anymore. It was working fine just yesterday, I suppose it might have broke after this change: https://github.com/tteck/Proxmox/issues/2843

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
fixed https://github.com/tteck/Proxmox/commit/c073351b4c9bd91c1fbb7f7172c3b9a79d47de61

**Comment by tteck** [comment]
Clear browser cache
