### ISSUE TITLE
Cloudflared LXC not working

### ISSUE THREAD

**Issue by guilherme-santos** [tteck/Proxmox#2849]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The installation of  Cloudflared LXC does not succeed.

When running the script with verbose mode I get the following:

```sh
 ✓ Installed Dependencies
Hit:1 http://archive.ubuntu.com/ubuntu mantic InRelease
Ign:2 https://pkg.cloudflare.com/cloudflared mantic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu mantic-updates InRelease
Err:4 https://pkg.cloudflare.com/cloudflared mantic Release
  404  Not Found [IP: 104.18.1.118 443]
Hit:5 http://archive.ubuntu.com/ubuntu mantic-security InRelease
Reading package lists... Done
E: The repository 'https://pkg.cloudflare.com/cloudflared mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

[ERROR] in line 27: exit code 0: while executing command $STD apt-get update
```

When checking the installation process on Cloudflare page, I have something like so:

```sh
curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
sudo dpkg -i cloudflared.deb && 
sudo cloudflared service install
```

So I believe that the script is outdated.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 23.10

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by guilherme-santos** [comment]
🤔
