### ISSUE TITLE
Whoogle search throws error

### ISSUE THREAD

**Issue by ghost** [tteck/Proxmox#287]
Here is the terminal print/output after searching for anything:
```
root@whoogle:~# /usr/bin/python3 /usr/local/bin/whoogle-search --host 0.0.0.0
ERROR:app:Exception on /search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/app/routes.py", line 79, in decorated
    _ = pickle.load(session_file)
MemoryError
```

And here is the browser error message after each search:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Thanks, and really appreciate all the work you do.

**Comment by 2600box** [comment]
I get something similar about half thé time, but seems random. Could not pin down reproducibility

**Comment by tteck** [comment]
Looks to be the same as https://github.com/tteck/Proxmox/issues/272
I've not encountered this, yet
Try setting the host IP in `/etc/systemd/system/whoogle.service` to the LXC IP

**Comment by ghost** [comment]
Setting it to the LXC IP results in the same error.

**Comment by tteck** [comment]
Did you reboot the LXC after the change?

**Comment by ghost** [comment]
Yes, I changed the service file, and rebooted.

**Comment by nicedevil007** [comment]
same here

**Comment by tteck** [comment]
Try changing resources to 1024MiB RAM - 2vCPU and see if you still get an error

**Comment by nicedevil007** [comment]
> Try changing resources to 1024MiB RAM - 2vCPU and see if you still get an error

error appears again after 5th search or so

![image](https://user-images.githubusercontent.com/17103076/174448181-c4308bf2-f099-4193-ada0-5e8cce6c93f8.png)

![image](https://user-images.githubusercontent.com/17103076/174448186-c72ff2a4-324f-4d6e-95ca-5bad8c444796.png)

**Comment by tteck** [comment]
So, it's not a script issue
https://github.com/benbusby/whoogle-search/issues/777

**Comment by tteck** [comment]
Before I close this (all that I can fix is script issues) try
```
pip install -i https://test.pypi.org/simple/ whoogle-search
```

**Comment by nicedevil007** [comment]
> Before I close this (all that I can fix is script issues) try
> 
> ```
> pip install -i https://test.pypi.org/simple/ whoogle-search
> ```

Already installed it :) Will report back if I get any more errors

**Comment by ghost** [comment]
I ran the command to no avail. Same result.

**Comment by ghost** [comment]
Wasn't able to update to dev earlier, now did, and seems to work. Will close for now - thanks for the assistance!
