### ISSUE TITLE
Glances installer not checking for successful completion, fails on hosts with managed python

### ISSUE THREAD

**Issue by htmlspinnr** [tteck/Proxmox#2870]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When executing the glances installer, no exit status is polled for the nested installer script. This leads to a false positive on installation which allows for systemd service creation for a missing service. Because line 68 of the installation wrapper pipes output to `/dev/null`, the user is unaware of the failure. 

The instlallation fails on systems running Python 3.11.x if apt package `libpython3.11-stdlib` is present (usually is as it's part of the python-3.11 metapackage) as it owns the file `/usr/lib/python3.11/EXTERNALLY-MANAGED` which, in turn, causes pip to refuse global installation without risky `--break-system-packages` flag. While not a problem caused by this script, the error is being redirected to `/dev/null`. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Proxmox VE 8.2.2

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Resultant output:
```
   ________
  / ____/ /___ _____  ________  _____
 / / __/ / __ `/ __ \/ ___/ _ \/ ___/
/ /_/ / / /_/ / / / / /__/  __(__  )
\____/_/\__,_/_/ /_/\___/\___/____/

This will Install Glances on proxmox. Proceed(y/n)?y
 ✓ Installed Glances on proxmox
Glances should be reachable by going to the following URL.
         http://192.168.1.xxx:61208 
```

Under the covers, line 68 is calling:
`bash -c "$(wget -qLO - https://raw.githubusercontent.com/nicolargo/glancesautoinstall/master/install.sh)" &>/dev/null`

If that script is executed w/o redirecting to `/dev/null`, the following output would be seen:
```
root@spinnrprox:~# bash ./install.sh 
Detected system: Debian
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (23.0.1+dfsg-1).
python3-docker is already the newest version (5.0.3-1).
gcc is already the newest version (4:12.2.0-3).
lm-sensors is already the newest version (1:3.6.0-7.1).
wireless-tools is already the newest version (30~pre9-14).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Install dependencies
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

### Please provide detailed steps to reproduce the issue.

1. Execute script
2. Expect accessible glances instance at http://_url_:61208
3. Run `pgrep glances` and observe that glances is not running
4. Note that `/usr/local/bin/glances` is missing
5. Observe looping service start failure by systemd in journal.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/2858#discussioncomment-9237108
