### ISSUE TITLE
How to uninstall Glances securely?

### ISSUE THREAD

**Issue by woody4165** [tteck/Proxmox#2873]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing Glances with the script, how is it possible to uninstall it securely, without compromising the Proxmox environment?

The next two questions regarding settings utilized and Linux distribution are set just because they are mandatory

Thanks

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by ryanjohnsontv** [comment]
These scripts don't install anything on the Proxmox host, so all that's needed is to shut down the Glances container the script made and remove it.

**Comment by woody4165** [comment]
@ryanjohnsontv are you sure?
It does not create any LXC nor VM.

**Comment by ryanjohnsontv** [comment]
That was my mistake entirely, I assumed Glances was a container! The Glances script calls this script for installing: https://raw.githubusercontent.com/nicolargo/glancesautoinstall/master/install.sh
That installs: `apt-get install -y python3-pip python3-docker gcc lm-sensors wireless-tools`
And once python is installed it uses pip to install: `pip install setuptools glances[action,batinfo,browser,cpuinfo,docker,export,folders,gpu,graph,ip,raid,snmp,web,wifi]`

So you'd need to disable the glances service `systemctl stop glances`, `systemctl disable glances`, and `rm /etc/systemd/system/glances.service`, uninstall the python packages, and then remove the packages installed via apt.

**Comment by tteck** [comment]
Rerun the script and select uninstall.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/869a95d22137bfc491d958263d602b1f283f477b
