### ISSUE TITLE
heimdall update error

### ISSUE THREAD

**Issue by roschi02** [tteck/Proxmox#2874]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The update script for Heimdall fails

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`[ERROR] in line 77: exit code 0: while executing command apt-get install -y composer &> /dev/null`

### Please provide detailed steps to reproduce the issue.

Just run the update
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/heimdall-dashboard.sh)"

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/2772
