### ISSUE TITLE
OpenMediaValut

### ISSUE THREAD

**Issue by kry008** [tteck/Proxmox#2875]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 0
Using Root Password: MyPassword1234.
Container ID: 100
Using Hostname: omv
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a OMV LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 100 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 190.0.0.184 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 / Installing OpenMediaVault (Patience)   
`[ERROR] in line 42: exit code 0: while executing command apt-get -y --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends --option DPkg::Options::="--force-confdef" --option DPkg::Options::="--force-confold" install openmediavault-keyring openmediavault &> /dev/null`
root@pve:~# 

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

On autoinstall it works

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/omv.sh)"

Using this script, only change is to disc size from default 4 to 8GB

Script create CT, but nothing is installed on it

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by tteck** [comment]
![Screenshot 2024-04-29 6 58 37 AM](https://github.com/tteck/Proxmox/assets/21342670/e7bc3716-eae8-4d1c-8c05-137dc1b2f87f)
