### ISSUE TITLE
Umbrel

### ISSUE THREAD

**Issue by easaw** [tteck/Proxmox#2880]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Umbrel v1.0+ is available but they haven't made it compatible for a VM.

It's kind of a 'fresh' install.

Instructions from Umbrel: https://community.umbrel.com/t/how-to-update-from-umbrelos-0-5-to-umbrelos-1-1-on-linux-devices/16704

Please could you create an updated template, or one that chooses from v0.5 or v1.1?

Thank you :)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

https://github.com/tteck/Proxmox/discussions/2879
