### ISSUE TITLE
Vaultwarden LXC - Alpine (Update)

### ISSUE THREAD

**Issue by AlexTryHarder** [tteck/Proxmox#2881]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Update script run inside of LXC container,
seems to do only 

apk update && upgrade
exit

obviously Vault warden not being updated.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by tteck** [comment]
As for all Alpine application scripts in this repository, an `apk update && apk upgrade` is all that is required to update.

Vaultwarden
https://pkgs.alpinelinux.org/packages?name=vaultwarden&branch=v3.19&repo=&arch=x86_64&maintainer=

Vaultwarden-web-vault
https://pkgs.alpinelinux.org/packages?name=vaultwarden-web-vault&branch=v3.19&repo=&arch=x86_64&maintainer=

I'd suggest contacting the package maintainer to check the status of future updates.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
