### ISSUE TITLE
Network routing

### ISSUE THREAD

**Issue by blade10101** [tteck/Proxmox#2882]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Adding network routing for proxmox would help alot. My default allports are filtered and not accessible from outside the lan.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Install proxmox and a lxc container

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
