### ISSUE TITLE
Wireguard : Debian 12 fails to install

### ISSUE THREAD

**Issue by David-Moreira** [tteck/Proxmox#2885]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Wireguard debian 12 fails to install

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/22283161/8ecd394c-2b8b-42de-aa7f-136862f1c505)

::: User root does not exist, creating...
useradd: user 'root' already exists
::: User created without a password, please do sudo passwd root to create one
 -:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
 done! Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn ... [/]  
::: WireGuard will be installed
::: Installing WireGuard from Debian package...
:::    Checking for wireguard-tools... not installed!
:::    Checking for qrencode... not installed!
:::    Checking for linux-headers-amd64... not installed!
:::    Checking for wireguard-dkms... not installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package wireguard-dkms is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wireguard-dkms' has no installation candidate
:::    Failed to install wireguard-tools!
:::    Failed to install qrencode!
:::    Failed to install linux-headers-amd64!
:::    Failed to install wireguard-dkms!
[2024-04-30T20:47:44+0100]:

[ERROR] in line 40: exit code 0: while executing command $STD bash <(curl -fsSL https://install.pivpn.io) --unattended options.conf

### Please provide detailed steps to reproduce the issue.

![image](https://github.com/tteck/Proxmox/assets/22283161/ddb8d207-04e4-4862-ae07-7f1a65c5f462)

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

![Screenshot 2024-04-30 3 53 00 PM](https://github.com/tteck/Proxmox/assets/21342670/15171e3d-6ad5-4f3a-bfa2-2d2740118bcf)

**Comment by David-Moreira** [comment]
You're absolutely right! Sorry!
