### ISSUE TITLE
Unable to use script to install Home Assistant VM (Fresh Proxmox Install)

### ISSUE THREAD

**Issue by sbcrumb** [tteck/Proxmox#289]
When running

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm-v3.sh)"

`I get the below error
Start VM when completed yes
 ✓ Using Data for Storage Location.
 ✓ Container ID is 101.
 ✓ Found URL for Home Assistant 8.1 Disk Image
 ✓ https://github.com/home-assistant/operating-system/releases/download/8.1/haos_ova-8.1.qcow2.xz
 ✓ Downloaded 8.1.qcow2 Disk Image
 ✓ Extracted Disk Image
 - Creating HAOS VM...volume 'Data:101/vm-101-disk-1.qcow2' does not exist
‼ ERROR 255@325 Unknown failure occured.`

**Comment by tteck** [comment]
Storage location. https://github.com/tteck/Proxmox/issues/257

**Comment by sbcrumb** [comment]
This local storage.

**Comment by tteck** [comment]
run `pvesm status -content images | awk 'NR>1'` in the Proxmox shell and share the results

**Comment by sbcrumb** [comment]
Data          dir     active       229640080         1710776       216191420    0.74%
local         dir     active        53881816         4969428        46572136    9.22%

**Comment by tteck** [comment]
Are you using BTRFS?

**Comment by sbcrumb** [comment]
Extra nothing fancy. It won't install on either of the drives

**Comment by tteck** [comment]
You stated "_Fresh Proxmox Install_" what file system did you select during the Proxmox install?

**Comment by sbcrumb** [comment]
default ext4

**Comment by tteck** [comment]
what happened to local-lvm?

**Comment by sbcrumb** [comment]
I merged it with local for one drive with that space, do you think that is the issue? it is fresh so I can redo it.

**Comment by tteck** [comment]
Yes! never merge!

**Comment by sbcrumb** [comment]
Ok let me reload

**Comment by sbcrumb** [comment]
Same problem.

 ✓ Using Data for Storage Location.
 ✓ Container ID is 100.
 ✓ Found URL for Home Assistant 8.2 Disk Image
 ✓ https://github.com/home-assistant/operating-system/releases/download/8.2/haos_ova-8.2.qcow2.xz
 ✓ Downloaded 8.2.qcow2 Disk Image
 ✓ Extracted Disk Image
 - Creating HAOS VM...volume 'Data:100/vm-100-disk-1.qcow2' does not exist
‼ ERROR 255@325 Unknown failure occured.
root@pve:~# 

root@pve:~# pvesm status -content images | awk 'NR>1'
Data              dir     active       229640080              56       217902140    0.00%
local             dir     active        15117272         2749896        11577668   18.19%
local-lvm     lvmthin     active        28966912               0        28966912    0.00%

**Comment by tteck** [comment]
use local-lvm (lvmthin), Data is directory

**Comment by sbcrumb** [comment]
Can I not use a dir? I mean that is where I want it.
and I don't know if I have enough space I only have 26gb on that dir.

**Comment by tteck** [comment]
Can you manually create a VM using that dir?

**Comment by sbcrumb** [comment]
I sure can. Even used your script to do the zigbee2mqtt container on that.

**Comment by tteck** [comment]
I said VM, not CT

**Comment by sbcrumb** [comment]
But they asnwer is yes I created a VM as well. I did a CT as a test so yes they both work.

**Comment by tteck** [comment]
Then I'd suggest you create a HAOS VM manually

**Comment by sbcrumb** [comment]
I am going to try another SSD drive just to make sure it is not hardware as well. Since it is thin I was able to get it to create on the local-lvm, and I guess I can move it to the other drive.

**Comment by tteck** [comment]
glad you got it going 👍🏻

**Comment by dbroome1978** [comment]
> Are you using BTRFS?

Is there a trick if we are? I am using BTRFS and getting the same error.  I have no local-lvm, just local

**Comment by tteck** [comment]
BTRFS isn't compatible with the Home Assistant OS VM script

:stop_sign: BTRFS integration is currently a technology preview in Proxmox VE.
https://pve.proxmox.com/wiki/BTRFS

I’d suggest using ext4

**Comment by dbroome1978** [comment]
Fair enough. Thank you

**Comment by tteck** [comment]
@dbroome1978  would you be so kind and try to create a new HAOS VM with BTRFS?

**Comment by dbroome1978** [comment]
It didn't work.  Is there a debug option?


```
Using Version 8.2
Using VM ID 108
Using VM Name haos8.2
Using 2vCPU
Using 4096MiB
Using Bridge vmbr0
Using MAC Address 00:60:2F:57:01:75
Using VLAN Tag NONE
Start VM when completed yes
Are these settings correct(y/n)? y
 ✓ Using mystorage for Storage Location.
 ✓ Container ID is 108.
 ✓ Found URL for Home Assistant 8.2 Disk Image
 ✓ https://github.com/home-assistant/operating-system/releases/download/8.2/haos_ova-8.2.qcow2.xz
 ✓ Downloaded 8.2.qcow2 Disk Image
 ✓ Extracted Disk Image
 - Creating HAOS VM...‼ ERROR 25@324 Unknown failure occured.
```

**Comment by tteck** [comment]
run `pvesm status -content images | awk 'NR>1'` in the Proxmox shell and share the results
I'd really like to figure this BTRFS issue out

**Comment by dbroome1978** [comment]
Here is the output
```
root@dellr710:~# pvesm status -content images | awk 'NR>1'
local             dir     active      5859997252       184875720      5674013752    3.15%
mystorage       btrfs     active     30273961984     20658956820      7117375996   68.24%
```

**Comment by tteck** [comment]
I'm treating `btrfs` as a `dir` for storage type like Proxmox suggests 🤷🏻‍♂️ 
```
case $STORAGE_TYPE in
  btrfs|nfs|dir)
        DISK_EXT=".qcow2"
        DISK_REF="$VMID/"
        DIR_IMPORT="-format qcow2"
esac
```
I'll keep trying! Thank you for the help.

**Comment by dbroome1978** [comment]
Ok- based on what you just wrote, I tried it again, but this time choosing "local" as my target storage device.  Installing it there works.  (My local is also a btrfs drive but listed as dir as storage type).
Not where I want it, but a great start since - from there - I can back it up and move it to my larger pool.

**Comment by tteck** [comment]
@dbroome1978 would you test this to make sure it's working with `btrfs` storage
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos_vm.sh)"
```
I had to setup a Proxmox `btrfs` test machine and it's finally working for me.
Just wanted your input before going public! lol

**Comment by dbroome1978** [comment]
That got it working
