### ISSUE TITLE
Jellyfin bashline error

### ISSUE THREAD

**Issue by dualizeo** [tteck/Proxmox#2890]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

using advance mode for setting it up I got this error:

bash: line 182: exit: A problem occured while trying to create container.: numeric argument required
 -ot@pve1:~# 

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
![Screenshot 2024-05-01 11 02 24 AM](https://github.com/tteck/Proxmox/assets/21342670/45d84ee3-6527-4f0d-b9e9-bb8e241a7236)

Show your Advanced settings.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by dualizeo** [comment]
yeah my bad looking at it closely 😂 it appears to say "  VM already exist with that number 😅 OOps
