### ISSUE TITLE
NextCloudPi has switched to bookworm

### ISSUE THREAD

**Issue by namomitk** [tteck/Proxmox#2893]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installed with supported Debian 11:

NextcloudPi has switched to bookworm in master https://github.com/nextcloud/nextcloudpi/blob/master/etc/ncp.cfg

This causes the install to fail for distro not supported.

------------------------------------
Unrelated but relevant information:

Tried Advanced Settings with Debian 12 selected but that also seems to fail due to issues unrelated to the script perse. Something is breaking DNS resolution. This appears to be the nextcloudpi install.sh recent commits:

https://github.com/nextcloud/nextcloudpi/blame/474c0007a1f80416eab5c9239476f9e9a95bab6e/install.sh#L68

```
if [[ -d "/run/systemd/system" ]] && is_lxc
then
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y systemd-resolved
  systemctl enable systemd-resolved
fi
```

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
    _   __          __  ________                ______  _ 
   / | / /__  _  __/ /_/ ____/ /___  __  ______/ / __ \(_)
  /  |/ / _ \| |/_/ __/ /   / / __ \/ / / / __  / /_/ / / 
 / /|  /  __/>  </ /_/ /___/ / /_/ / /_/ / /_/ / ____/ /  
/_/ |_/\___/_/|_|\__/\____/_/\____/\__,_/\__,_/_/   /_/   
                                                          
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 711
Using Hostname: nextcloudpi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr1
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: 70
Enable Root SSH Access: no
Enable Verbose Mode: yes
Creating a NextCloudPi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using pvestorage1 for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 711 was successfully created.
 ✓ Started LXC Container
net.ipv6.conf.all.disable_ipv6 = 1
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.70.101 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.4

Installing NextCloudPi...
 -ERROR: distro not supported:
Debian GNU/Linux 11 \n \l
```

```
    _   __          __  ________                ______  _ 
   / | / /__  _  __/ /_/ ____/ /___  __  ______/ / __ \(_)
  /  |/ / _ \| |/_/ __/ /   / / __ \/ / / / __  / /_/ / / 
 / /|  /  __/>  </ /_/ /___/ / /_/ / /_/ / /_/ / ____/ /  
/_/ |_/\___/_/|_|\__/\____/_/\____/\__,_/\__,_/_/   /_/   
                                                          
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 711
Using Hostname: nextcloudpi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr1
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: 70
Enable Root SSH Access: no
Enable Verbose Mode: yes
Creating a NextCloudPi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using pvestorage1 for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 711 was successfully created.
 ✓ Started LXC Container
net.ipv6.conf.all.disable_ipv6 = 1
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.70.102 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.3


  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lbzip2/lbzip2_2.5-2.3_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

[ERROR] in line 23: exit code 0: while executing command $STD bash <(curl -fsSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh)
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.
```

**Comment by tteck** [comment]
Can you file an issue over there? I'll switch the script to use Debian 12.

**Comment by namomitk** [comment]
Will do.  Looks like after you added lbzip2 to deps it wants to do these after systemd-resolve gets loaded in and breaks DNS:

```
The following additional packages will be installed:
  fuse libarchive13 libavahi-client3 libavahi-common-data libavahi-common3 libfuse2 libldb2 libsmbclient libtalloc2 libtdb1 libtevent0 libwbclient0
  samba-common samba-libs
Suggested packages:
  lrzip cifs-utils heimdal-clients
Recommended packages:
  samba-common-bin
 -The following NEW packages will be installed:
  exfat-fuse exfatprogs fuse libarchive13 libavahi-client3 libavahi-common-data libavahi-common3 libfuse2 libldb2 libsmbclient libtalloc2 libtdb1
  libtevent0 libwbclient0 samba-common samba-libs smbclient
```

More complete:
```
The following NEW packages will be installed:
  systemd-resolved
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 305 kB of archives.
After this operation, 827 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 systemd-resolved amd64 252.22-1~deb12u1 [305 kB]
Fetched 305 kB in 0s (5,355 kB/s)    
 \Selecting previously unselected package systemd-resolved.
(Reading database ... 24094 files and directories currently installed.)
Preparing to unpack .../systemd-resolved_252.22-1~deb12u1_amd64.deb ...
Unpacking systemd-resolved (252.22-1~deb12u1) ...
 |Setting up systemd-resolved (252.22-1~deb12u1) ...
Converting /etc/resolv.conf to a symlink to /run/systemd/resolve/stub-resolv.conf...
Creating group 'systemd-resolve' with GID 996.
Creating user 'systemd-resolve' (systemd Resolver) with UID 996 and GID 996.
 /Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /lib/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-resolved.service → /lib/systemd/system/systemd-resolved.service.
 \Processing triggers for dbus (1.14.10-1~deb12u1) ...
Processing triggers for man-db (2.11.2-2) ...
 |Installing nc-nextcloud
Ign:1 https://packages.sury.org/php bookworm InRelease
Ign:2 http://deb.debian.org/debian bookworm InRelease
Ign:3 http://security.debian.org bookworm-security InRelease
Ign:4 http://deb.debian.org/debian bookworm-updates InRelease
Ign:1 https://packages.sury.org/php bookworm InRelease
Ign:2 http://deb.debian.org/debian bookworm InRelease                
Ign:3 http://security.debian.org bookworm-security InRelease         
Ign:4 http://deb.debian.org/debian bookworm-updates InRelease
Ign:2 http://deb.debian.org/debian bookworm InRelease
Ign:1 https://packages.sury.org/php bookworm InRelease
Ign:3 http://security.debian.org bookworm-security InRelease
Ign:4 http://deb.debian.org/debian bookworm-updates InRelease
Err:2 http://deb.debian.org/debian bookworm InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://security.debian.org bookworm-security InRelease            
  Temporary failure resolving 'security.debian.org'
Err:1 https://packages.sury.org/php bookworm InRelease                  
  Temporary failure resolving 'packages.sury.org'
Err:4 http://deb.debian.org/debian bookworm-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done    
W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/dists/bookworm-security/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch https://packages.sury.org/php/dists/bookworm/InRelease  Temporary failure resolving 'packages.sury.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lbzip2 is already the newest version (2.5-2.3).
iputils-ping is already the newest version (3:20221126-1).
jq is already the newest version (1.6-2.1).
wget is already the newest version (1.21.3-1+b2).
 |0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  fuse libarchive13 libavahi-client3 libavahi-common-data libavahi-common3 libfuse2 libldb2 libsmbclient libtalloc2 libtdb1 libtevent0 libwbclient0
  samba-common samba-libs
Suggested packages:
  lrzip cifs-utils heimdal-clients
Recommended packages:
  samba-common-bin
 -The following NEW packages will be installed:
  exfat-fuse exfatprogs fuse libarchive13 libavahi-client3 libavahi-common-data libavahi-common3 libfuse2 libldb2 libsmbclient libtalloc2 libtdb1
  libtevent0 libwbclient0 samba-common samba-libs smbclient
```

**Comment by tteck** [comment]
Yep, when they added
```
if [[ -d "/run/systemd/system" ]] && is_lxc
then
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y systemd-resolved
  systemctl enable systemd-resolved
fi
```
it breaks DNS like you said.

**Comment by tteck** [comment]
I also put in a PR to fix their `README.md` section on "Run in Proxmox" https://github.com/nextcloud/nextcloudpi/pull/1908/files

**Comment by theCalcaholic** [comment]
Hi, I'm the NCP maintainer. ~I tried building without systemd-resolved and it broke the networking during build~ so I added this section. But I'll check if there's another way around this. If not, I'll try to differentiate between the official LXC-image and custom installations.

**EDIT:** DNS resolution didn't break during build, but when upgrading a bullseye based container to bookworm.

**Comment by tteck** [comment]
> EDIT: DNS resolution didn't break during build, 

So,
```
if [[ -d "/run/systemd/system" ]] && is_lxc
then
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y systemd-resolved
  systemctl enable systemd-resolved
fi
```
can be removed?

**Comment by theCalcaholic** [comment]
> > EDIT: DNS resolution didn't break during build,
> 
> So,
> 
> ```
> if [[ -d "/run/systemd/system" ]] && is_lxc
> then
>   DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y systemd-resolved
>   systemctl enable systemd-resolved
> fi
> ```
> 
> can be removed?

Unfortunately no, not that easy - with the provided LXC images, I try to have instances that are as reproducible as possible. If I would remove systemd-resolved only for the build but not for the upgrade from older versions I would have to support diverging architectures which I would like to avoid.

**Comment by tteck** [comment]
After reading https://github.com/nextcloud/nextcloudpi/issues/1907#issuecomment-2089466852 which closed the issue with no resolution for _their_ "Curl install scripts" I've decided to remove NextCloudPi from the website.

**Comment by namomitk** [comment]
Fair enough. There is always the Alpine image. Thanks for working on this with me.

**Comment by tteck** [comment]
Yeah, I hate to remove it but I'm not going to download and install a template that I have no way to vet.

**Comment by theCalcaholic** [comment]
> After reading https://github.com/nextcloud/nextcloudpi/issues/1907#issuecomment-2089466852 which closed the issue with no resolution for their "Curl install scripts" I've decided to remove NextCloudPi from the website.

Okay, I do understand your reasoning in that you cannot guarantee that the official Nextcloud image does not contain any malicious intents, but I would like to invite you to reconsider your stance, because I really don't see how this changes if you offer a wrapper around the install script.

1) I didn't intend to propose to discontinue your installer. What I was going to discuss, was a fix to your script, as systemd-resolved works perfectly fine with Proxmox (in fact that's the case for my own, personal NCP instance - I daily drive NCP via Proxmox/LXC myself). Systemd-resolved has a mode of operation where it uses an externally managed resolv.conf file - which it should usually do automatically (and did so for the CT template, as well as the upgrade from bullseye), however, it didn't seem to work with your installer. I assume that there would be a very simple fix to that.

2) I'm not sure what extra "vetting" the installer provides over the official LXC image. Every user of NextcloudPi needs to have trust in the good-will of the project maintainer, i.e. me. NextcloudPi is basically "managed selfhosting" - I write update automation routines that would allow me to execute arbitrary code on users' instances and therefore there's now way for this to work without this trust. So even if you provide a wrapper around the installation script (that in turn is probably not checked by you regularly), you couldn't guarantee the integrity, security or benevolent nature of the upstream project (and the same probably applies to all the other installation scripts).
NCP Images are build and tested in publicly viewable pipelines and pushed to GH releases with checksums (that can be compared to the pipeline) to validate. These automated pipelines ensure a certain level of functionality and integrity which is a guarantee that you lack when using the installer directly (network issues happen all the time and break things during installation).

I'm very open to any points I missed or misunderstood here and hope to here more about your reasoning.


**EDIT:** on a personal note: For the last two weeks, I have invested every minute of free time (and a significant amount of time that I should have been working for my day job and need to catch up on) on the latest NCP release. The maintenance overhead for these kinds of updates is enormous and hardly sustainable, which is why my main focus for the project is currently cutting maintenance overhead. And that means first and foremost: More testing, more automatization and more standardization (because, as you know, there's no automation without standardization). That's why I don't want to afford diverging architectures like having some LXC instances use resolvconf and some use systemd-resolved unless there's really no feasible way around that. It's also the reason why I dropped support for the NCP docker containers and migrated the Raspberry Pi images to Armbian. Yesterday I finished the release after working all night and did just not have the energy to give all the details above on this issue before getting some sleep. Cheers, and keep up your good work.

**Comment by namomitk** [comment]
I had some success with pausing the installer and changing DNS so that it could resolve. I still had to fix it after the fact. I was also able to make this work by installing all the packages requested as deps. Piping a script to bash is what it is; especially from the master branch of another project. 

Great work to both of you; these are both excellent projects and I'm sorry to see them diverge. Not sure how many cycles I have available but I'm willing to work on some commits if this is something everyone wants to hang on to.

**Comment by tteck** [comment]
I modified the script. @namomitk would you test the script?

**Comment by tteck** [comment]
```
    _   __          __  ________                ______  _ 
   / | / /__  _  __/ /_/ ____/ /___  __  ______/ / __ \(_)
  /  |/ / _ \| |/_/ __/ /   / / __ \/ / / / __  / /_/ / / 
 / /|  /  __/>  </ /_/ /___/ / /_/ / /_/ / /_/ / ____/ /  
/_/ |_/\___/_/|_|\__/\____/_/\____/\__,_/\__,_/_/   /_/   
                                                          
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: nextcloudpi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a NextCloudPi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed NextCloudPi
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

NextCloudPi Setup should be reachable by going to the following URL.
         https://192.168.86.250/ 
```
![Screenshot 2024-05-02 1 02 43 PM](https://github.com/tteck/Proxmox/assets/21342670/5870f8fd-c034-45b4-8604-6fae1670cce0)

**Comment by tteck** [comment]
Added back to the website.

**Comment by namomitk** [comment]
Can confirm it works for me as well.

**Comment by theCalcaholic** [comment]
Great work! Out of curiosity: How did you fix it?

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/c8205964310dbf72a08b1e182a28fd65a3f7c034
