### ISSUE TITLE
Failure to install JellyFin as lxc

### ISSUE THREAD

**Issue by jakartadot** [tteck/Proxmox#2894]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

when running this

  bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jellyfin.sh)"
  
  I get this
 

[ERROR] in line 616: exit code 0: while executing command pct start "$CTID"

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

''''       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
 
Using Default Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 109
Using Hostname: jellyfin
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Jellyfin LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 109 was successfully created.
 /Device /dev/dri/renderD128 does not exist

[ERROR] in line 616: exit code 0: while executing command pct start "$CTID"''''

### Please provide detailed steps to reproduce the issue.

In Proxmox shell, run bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jellyfin.sh)".

this will begin the install steps for jellyfin but it will fail with this error.

[ERROR] in line 616: exit code 0: while executing command pct start "$CTID"

**Comment by tteck** [comment]
Will you try Advanced settings and select privileged, as a test.

**Comment by jakartadot** [comment]
That worked! Thanks for being so responsive!

**Comment by tteck** [comment]
Thanks, a fix is coming, soon.
