### ISSUE TITLE
Heimdall update error

### ISSUE THREAD

**Issue by lyricnz** [tteck/Proxmox#2896]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Opened the console in proxmox, ran
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/heimdall-dashboard.sh)"`
And got error
`[ERROR] in line 78: exit code 0: while executing command COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload &> /dev/null`

Container was originally installed using tteck scripts. No hackery as far as I remember.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
            _               _       _ _      ___          _     _                         _ 
  /\  /\___(_)_ __ ___   __| | __ _| | |    /   \__ _ ___| |__ | |__   ___   __ _ _ __ __| |
 / /_/ / _ \ | '_ ` _ \ / _` |/ _` | | |   / /\ / _` / __| '_ \| '_ \ / _ \ / _` | '__/ _` |
/ __  /  __/ | | | | | | (_| | (_| | | |  / /_// (_| \__ \ | | | |_) | (_) | (_| | | | (_| |
\/ /_/ \___|_|_| |_| |_|\__,_|\__,_|_|_| /___,' \__,_|___/_| |_|_.__/ \___/ \__,_|_|  \__,_|
                                                                                            
cat: /opt/Heimdall-Dashboard_version.txt: No such file or directory
 ✓ Stopped Heimdall-Dashboard
 ✓ Backed up Data
 | Updating Heimdall Dashboard to v2.6.1   
[ERROR] in line 78: exit code 0: while executing command COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload &> /dev/null

root@heimdalldashboard:~# ```

### Please provide detailed steps to reproduce the issue.

Running script with bash-x ended with

```
++ error_handler 78 'COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload &> /dev/null'
++ '[' -n 35618 ']'
++ ps -p 35618
+ true
+ printf '\r \e[36m%s\e[0m' -
 -+ sleep 0.1
++ kill 35618
++ printf '\e[?25h'
++ local exit_code=0
++ local line_number=78
++ local 'command=COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload &> /dev/null'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m78\033[m: exit code \033[01;31m0\033[m: while executing command \033[33mCOMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload &> /dev/null\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m78\033[m: exit code \033[01;31m0\033[m: while executing command \033[33mCOMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload &> /dev/null\033[m\n'

[ERROR] in line 78: exit code 0: while executing command COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload &> /dev/null
```

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2874

**Comment by lyricnz** [comment]
What do you mean "If the default Linux distribution is not adhered to, script support will be discontinued."?

I never touched anything - this container is 100% tteck script driven.

It looks like YOU have changed the base image, and broke the upgrade for anyone who installed on your old version?

**Comment by tteck** [comment]
You didn't follow the link. https://github.com/tteck/Proxmox/discussions/2772

**Comment by lyricnz** [comment]
OK, I updated to deb12 manually following your steps. Same result.

The failing command emitted lots of PHP/composer class problems ending thusly:

```
root@heimdalldashboard:/opt/Heimdall# COMPOSER_ALLOW_SUPERUSER=1 composer dump-autoload | tail -20
...
Warning: Ambiguous class resolution, "Carbon\Doctrine\CarbonTypeConverter" was found in both "/opt/Heimdall/vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/CarbonTypeConverter.php" and "/opt/Heimdall/vendor/nesbot/carbon/src/Carbon/Doctrine/CarbonTypeConverter.php", the first will be used.
Class Monolog\Handler\ElasticsearchHandler located in ./vendor/monolog/monolog/src/Monolog/Handler/ElasticSearchHandler.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

  Class "DOMDocument" not found

  at vendor/nunomaduro/termwind/src/HtmlRenderer.php:32
     28▕      * Parses the given html.
     29▕      */
     30▕     public function parse(string $html): Components\Element
     31▕     {
  ➜  32▕         $dom = new DOMDocument();
     33▕ 
     34▕         if (strip_tags($html) === $html) {
     35▕             return Termwind::span($html);
     36▕         }

      +25 vendor frames 
  26  app/Providers/AppServiceProvider.php:148
      Illuminate\Support\Facades\Facade::__callStatic()

  27  app/Providers/AppServiceProvider.php:31
      App\Providers\AppServiceProvider::setupDatabase()
root@heimdalldashboard:/opt/Heimdall# 
```

**Comment by lyricnz** [comment]
PS: fixed it by doing a brand new install, then copying the files the script backed up into the new system. Also had to copy custom icons from /opt/Heimdall/storage/app/public/icons.
