### ISSUE TITLE
NginxProxyManager update script fails with ERROR in lin 65

### ISSUE THREAD

**Issue by marc-gist** [tteck/Proxmox#2898]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

[ERROR] in line 65: exit code 0: while executing command npm install -g pnpm@8.15 &> /dev/null

after running
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"`

on an existing system.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

n/a

### Please provide detailed steps to reproduce the issue.

run the script on a existing LXC NginxProdyManager, select yes to update, produces error.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2706#issuecomment-2041056086

**Comment by marc-gist** [comment]
> 🛑 Failure to comply with the following guideline.
> 
> > * Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.
> 
> [#2706 (comment)](https://github.com/tteck/Proxmox/issues/2706#issuecomment-2041056086)

sorry, thought I did. clearly not well enough.
Shouldn't your script handle this gracefully?

**Comment by marc-gist** [comment]
That fix didn't work :( @tteck
