### ISSUE TITLE
FlowiseAI LXC - Error installation with script

### ISSUE THREAD

**Issue by gamersalpha** [tteck/Proxmox#2906]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When i start the script : 

![image](https://github.com/tteck/Proxmox/assets/32466950/fc31cbfb-6e56-41c0-b694-5282b1e96abc)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - When encountering the error message [ERROR] in line 23: exit code *: while executing command "$@" > /dev/null 2>&1, make sure to run the script in verbose mode to accurately determine the underlying issue.

**Comment by urukalo** [comment]
I bumped into the same error:

> Using Default Settings
> Using Distribution: debian
> Using debian Version: 12
> Using Container Type: 1
> Using Root Password: Automatic Login
> Using Container ID: 101
> Using Hostname: flowiseai
> Using Disk Size: 10GB
> Allocated Cores 4
> Allocated Ram 4096
> Using Bridge: vmbr0
> Using Static IP Address: dhcp
> Using Gateway IP Address: Default
> Using Apt-Cacher IP Address: Default
> Disable IPv6: No
> Using Interface MTU Size: Default
> Using DNS Search Domain: Host
> Using DNS Server Address: Host
> Using MAC Address: Default
> Using VLAN Tag: Default
> Enable Root SSH Access: No
> Enable Verbose Mode: No
> Creating a FlowiseAI LXC using the above default settings
>  ✓ Using local for Template Storage.
>  ✓ Using local-lvm for Container Storage.
>  ✓ Updated LXC Template List
>  ✓ LXC Container 101 was successfully created.
>  ✓ Started LXC Container
>  ✓ Set up Container OS
>  ✓ Network Connected: 192.168.79.136 
>  ✓ IPv4 Internet Connected
>  ✗ IPv6 Internet Not Connected
>  ✓ DNS Resolved github.com to 140.82.121.4
>  ✓ Updated Container OS
>  ✓ Installed Dependencies
>  ✓ Installed Node.js
>  - Installing FlowiseAI (Patience)   
>  
> [ERROR] in line 23: exit code 0: while executing command "$@" > /dev/null 2>&1
> The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    ________              _           ___    ____
   / ____/ /___ _      __(_)_______  /   |  /  _/
  / /_  / / __ \ | /| / / / ___/ _ \/ /| |  / /
 / __/ / / /_/ / |/ |/ / (__  )  __/ ___ |_/ /
/_/   /_/\____/|__/|__/_/____/\___/_/  |_/___/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: flowiseai
Using Disk Size: 10
Allocated Cores: 4
Allocated RAM: 4096
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a FlowiseAI LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Node.js
 ✓ Installed FlowiseAI
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Set Container to Normal Resources
 ✓ Completed Successfully!

FlowiseAI should be reachable by going to the following URL.
         http://192.168.86.250:3000 
```
🛑 Failure to comply with the following guideline.
> - When encountering the error message [ERROR] in line 23: exit code *: while executing command "$@" > /dev/null 2>&1, make sure to run the script in verbose mode to accurately determine the underlying issue.

**Comment by urukalo** [comment]
I see that You used advanced settings, not default one
I tried the same and it worked, here is my choice:

> Using Advanced Settings
> Using Distribution: debian
> Using debian Version: 12
> Using Container Type: 1
> Using Root Password: miki97912
> Container ID: 101
> Using Hostname: flowiseai
> Using Disk Size: 10
> Allocated Cores: 4
> Allocated RAM: 4096
> Using Bridge: vmbr0
> Using IP Address: dhcp
> Using Gateway IP Address: Default
> Using APT-Cacher IP Address: Default
> Disable IPv6: yes
> Using Interface MTU Size: Default
> Using DNS Search Domain: Host
> Using DNS Server IP Address: Host
> Using Vlan: Default
> Enable Root SSH Access: yes
> Enable Verbose Mode: yes
> Creating a FlowiseAI LXC using the above advanced settings

I hope that this will help someone who lands on this issue 😄
