### ISSUE TITLE
Transmission LXC, permission denied

### ISSUE THREAD

**Issue by TomasDJo** [tteck/Proxmox#2911]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Tried installing Transmission through tteck proxmox script using default settings. Afterwards, I configured lxc.idmap identical to my other (working) LXCs. 

I get "Permission denied" when trying to download anything and storing the result on the disk Media1. It manages to download somewhere between 1-10 MB before presenting the error.

I have also seen comments on other pages such as reddit, where people informs they went ahead with using something else than tteck transmission due to not being able to gain access to a mountpoint. Not sure if the issue is related to the script or transmission. 

I changed to using deluge and it seems to work fine, so just letting you know about the bug.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/62136003/50f55f2d-1017-4186-8ac7-3b723657220b)

Configuration
```
arch: amd64
cores: 2
features: keyctl=1,nesting=1
hostname: transmission
memory: 2048
mp0: /mnt/pve/Media1,mp=/Media1
net0: name=eth0,bridge=vmbr0,gw=192.168.10.1,hwaddr=BC:24:11:7C:A7:F7,ip=192.168.10.224/24,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-105-disk-0,size=8G
swap: 512
tags: proxmox-helper-scripts
unprivileged: 1
lxc.idmap: u 0 100000 1000
lxc.idmap: g 0 100000 1000
lxc.idmap: u 1000 1000 1
lxc.idmap: g 1000 1000 1
lxc.idmap: u 1001 101000 64535
lxc.idmap: g 1001 101000 64535
```

### Please provide detailed steps to reproduce the issue.

Install transmission using tteck helper script, default settings. 
Add lxc.idmap to /etc/pve/lxc/#LXC_ID#.conf for gaining access to a mountpoint. 
Add a torrent and it fails after downloading a few MB.

**Comment by tteck** [comment]
👨🏻‍🦱 My focus is on developing application LXC scripts, and maintaining said scripts. I do not specialize in, nor do I have the time to provide support for operational issues. If you still insist your issue is directly related to the script, plead your case (within 1 hr ⌛), otherwise, I consider this closed.

Why not set mount points and devices in an unprivileged container via the GUI?

 
![image](https://github.com/tteck/Proxmox/assets/21342670/4876f7ad-2173-47b0-b52b-7aa7d988591a)
