### ISSUE TITLE
Docker line 26 error on install

### ISSUE THREAD

**Issue by Peffy95** [tteck/Proxmox#2912]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Pretty new here.
Trying to install docker using 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker.sh)"

I keep getting an error "[ERROR] in line 26: exit code 0: while executing command DOCKER LATEST VERSION=$(get latest release "moby/moby")"

I even get this error using default settings.

Any idea?

Thanks! 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="1152" alt="Untitled" src="https://github.com/tteck/Proxmox/assets/152871425/aad84e8f-de0d-4897-a334-a9f9c54d56ba">

**Comment by tteck** [comment]
It appears that the variable `get_latest_release()` is not working for you. Copy the snippet below and paste within the Proxmox shell and share the output.

```
get_latest_release() {
  curl -sL https://api.github.com/repos/$1/releases/latest | grep '"tag_name":' | cut -d'"' -f4
}
DOCKER_LATEST_VERSION=$(get_latest_release "moby/moby")
echo "Installing Docker $DOCKER_LATEST_VERSION"
```

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by Peffy95** [comment]
<img width="586" alt="image" src="https://github.com/tteck/Proxmox/assets/152871425/de04ed2b-20f7-40ef-a3d5-ef46264d915e">

**Comment by BunnySilly** [comment]
This was caused for me by having to many requests to the GitHub API and being temporarily blocked.

if going to [https://api.github.com/repos/$1/releases/latest](https://api.github.com/repos/$1/releases/latest) in a web browser gives you a too many API requests message, just wait until they unblock you or change your IP with a VPN or something.
