### ISSUE TITLE
pimox-haos-vm  line 264: STORAGE_MENU: unbound variable

### ISSUE THREAD

**Issue by Yngve0** [tteck/Proxmox#2914]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am trying to install pimox-haos-vm on a Raspberry pi 5 with Bookworm and proxmox 8.1.7
The script gives following error:

Creating a HAOS VM using the above advanced settings

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

ipcc_send_rec[1] failed: Unknown error -1
ipcc_send_rec[2] failed: Unknown error -1
ipcc_send_rec[3] failed: Unknown error -1
Unable to load access control list: Unknown error -1
‼ ERROR 255@263 Unknown failure occurred.
bash: line 264: STORAGE_MENU: unbound variable

### Please provide detailed steps to reproduce the issue.

Running bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/pimox-haos-vm.sh)"
from CLI on the Raspberry

**Comment by tteck** [comment]
~~Are you using PiMox?~~ I see that you are.
Executing within the Proxmox shell, not SSH?

**Comment by tteck** [comment]
> advanced settings

But you listed 
> What settings are you currently utilizing?
Default Settings

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by Yngve0** [comment]
>>Executing within the Proxmox shell, not SSH?
Seems like this was the issue, first attempt was SSH. From Proxmox shell it seems fine
