### ISSUE TITLE
Octoprint script, how to passthru usb port?

### ISSUE THREAD

**Issue by woody4165** [tteck/Proxmox#2918]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing the Octoprint via script, a usb port has to be passed to the container.
In the Container Resources I've added a Device Passthru with /dev/serial/by-id/usb-....... but still no serial port found in octoprint after a restart

Any info on how to do it?

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
