### ISSUE TITLE
Wireguard.sh --> Update WGDashboard

### ISSUE THREAD

**Issue by roswitina** [tteck/Proxmox#2919]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When executing the script to update the WGDashboard, I get an error. Could it be that lines 73 and 74 are mixed up in the script?
<img width="410" alt="wgupdate" src="https://github.com/tteck/Proxmox/assets/2253471/eccd1005-1d86-4659-920d-a222dce82d27">

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Looks like an issue created https://github.com/tteck/Proxmox/commit/1672c7fc0eb6e61a51f6a93c21fedb962efafcec by @hoggatt
