### ISSUE TITLE
Wireguard; install advanced with debian 12; Failure

### ISSUE THREAD

**Issue by roswitina** [tteck/Proxmox#2926]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

**Advanced Options:**

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: test1234
Container ID: 154
Using Hostname: wireguard
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: yes

**Output from bash**
...
Setting up iptables-persistent (1.0.20) ...
 \Setting up git (1:2.39.2-1.1) ...
Processing triggers for man-db (2.11.2-2) ...
 |Processing triggers for libc-bin (2.36-9+deb12u7) ...
 \:::    Package git successfully installed!
:::    Package dnsutils successfully installed!
:::    Package grepcidr successfully installed!
:::    Package net-tools successfully installed!
:::    Package bsdmainutils successfully installed!
:::    Package iptables-persistent successfully installed!
::: PiVPN Automated Installer
::: This installer will transform your Debian host into an OpenVPN or WireGuard server!
::: Initiating network interface
 |::: IPv6 test connections to google.com have failed. Disabling IPv6 support. (The curl test failed with code: 7)
::: Enable forced IPv6 route with no IPv6 uplink on server.
::: Using interface: eth0 for IPv4
::: Since we think you are not using Raspberry Pi OS, we will not configure a static IP for you.
::: User root does not exist, creating...
useradd: user 'root' already exists
::: User created without a password, please do sudo passwd root to create one
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... not found!
 done! Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn ... [/]  
::: WireGuard will be installed
::: Installing WireGuard from Debian package...
:::    Checking for wireguard-tools... not installed!
:::    Checking for qrencode... not installed!
:::    Checking for linux-headers-amd64... not installed!
:::    Checking for wireguard-dkms... not installed!
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package wireguard-dkms is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wireguard-dkms' has no installation candidate
:::    Failed to install wireguard-tools!
:::    Failed to install qrencode!
:::    Failed to install linux-headers-amd64!
:::    Failed to install wireguard-dkms!
[2024-05-07T12:40:11+0200]:

[ERROR] in line 40: exit code 0: while executing command $STD bash <(curl -fsSL https://install.pivpn.io) --unattended options.conf

_**The installation with the "default" settings (Debian 11) works...**_

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
