### ISSUE TITLE
updating Debian and Ubuntu-based LXCs via cron job will produce some warnings

### ISSUE THREAD

**Issue by alberanid** [tteck/Proxmox#2931]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

By default, the `apt` command will print a warning to stderr when called as a script: **WARNING: apt does not have a stable CLI interface. Use with caution in scripts.**

These warnings will end in the cron log and possibly in emails.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### Please provide detailed steps to reproduce the issue.

It's possible to reproduce the script from the command line running:

```
misc/update-lxcs-cron.sh > /dev/null
```

On the output, you will see lines like **WARNING: apt does not have a stable CLI interface. Use with caution in scripts.**

**Comment by tteck** [comment]
Yes,`apt` will give warnings, but `apt-get` is suitable for scripting and automation tasks. `apt-get` should not throw any warnings.
