### ISSUE TITLE
Paperless-NGX Cannot find creds

### ISSUE THREAD

**Issue by madcar86** [tteck/Proxmox#2934]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After reading the issue log regarding updating Paperless, I reinstalled the LXC as directed. However when I run update or the script, I get the following error.
[ERROR] in line 99: exit code 0: while executing command cat paperless.creds

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

'''[ERROR] in line 99: exit code 0: while executing command cat paperless.creds'''

### Please provide detailed steps to reproduce the issue.

Run "update" or script in Paperless LXC

**Comment by tteck** [comment]
No issue here

```
    ____                        __                                     
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/                                         /____/        
 

Paperless-ngx Database User: paperless
Paperless-ngx Database Password: xbE5qUgD9qLQg
Paperless-ngx Database Name: paperlessdb

Paperless-ngx WebUI User: admin
Paperless-ngx WebUI Password: xbE5qUgD9qLQg

root@paperless-ngx:~# 
```
❗ It is crucial not to exit the Proxmox shell while running scripts. Leaving the shell during script execution will result in the script being interrupted.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by stan23** [comment]
@madcar86 
I had the same error message and figured out that the file `paperless.cred` is placed in `/root` because I ran the script as root for installation.
But I ran the script as a normal user later and then of course the file could not be found.

Maybe you can find the file in `/root` as well?
