### ISSUE TITLE
Paperless-ngx update to v2.8.2 fails

### ISSUE THREAD

**Issue by fbloemhof** [tteck/Proxmox#2937]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Tried running update from the shell and also run the script from Git, both result in 

```
[ERROR] in line 83: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null
``` 

Rebooted the LXC but had no effect. 

Also noticed this message:

````
cat: /opt/Paperless-ngx_version.txt: No such file or directory
````

Not sure if this is related.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2925
