### ISSUE TITLE
error when using the script to update paperless-ngx

### ISSUE THREAD

**Issue by andreklug** [tteck/Proxmox#2938]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Paperless-ngx was installed some time ago and was always updated using the scipt from within the container
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"
While I try updating from 2.7.2 to 2.8.2 using the same way, I receive the error essage below and get back to the CLI.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="790" alt="grafik" src="https://github.com/tteck/Proxmox/assets/13343357/21bbf98f-12e6-4741-a67e-841fcce954f9">

bash: -c: line 69: syntax error in conditional expression

### Please provide detailed steps to reproduce the issue.

use the script to update paperless-ngx

**Comment by lenne0815** [comment]
Same here

**Comment by tteck** [comment]
Fast enough? 😉

**Comment by andreklug** [comment]
impressive :) works!
Sir, would you please take a seat in the lounge of heroes.

**Comment by tteck** [comment]
Your next error https://github.com/tteck/Proxmox/issues/2925
