### ISSUE TITLE
Update Zoraxy 3.02 to 3.03 - There is currently no update path available.

### ISSUE THREAD

**Issue by cvroque** [tteck/Proxmox#2939]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I installed the zoraxy LXC using the script, but the updates aren't recognized:

![image](https://github.com/tteck/Proxmox/assets/65680394/f6d0f5d6-84fe-4277-9081-9565a44f5d2d)

The installed version is 3.02 and the latest version is 3.03.

Creating a new LXC seems to install the latest version correctly, so it was quite easy to run the script again and import the settings, but I decided to open an issue anyway. 

If I'm barking at the wrong tree please let me know, thanks in advance.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
That means that an update script has not been created.

🧐 As this issue is unrelated to the script, it is considered closed.
