### ISSUE TITLE
Encoding on paperless-ngx can cause issues

### ISSUE THREAD

**Issue by JesperDramsch** [tteck/Proxmox#2949]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

My paperless-ngx install did not want to ingest documents anymore.

The issue was opened with something similar here: https://github.com/paperless-ngx/paperless-ngx/issues/6651 with this error:

``` 
01-ticket-400.png: The following error occurred while storing document 01-ticket-400.png after parsing: conversion between UTF8 and SQL_ASCII is not supported
LINE 1: ...46', 46, '2024-01-17 01-ticket-400', NULL, 0, '', '{"notes":...
                                                             ^
```

on any file I ingested. I was able to resolve this by re-encoding the database with the recipe described on that issue.

I feel that it may be worth it to force the `utf-8` encoding of the postgres database in the helper script to reduce these kinds of issues in the future.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2925#issuecomment-2098914527

**Comment by JesperDramsch** [comment]
Sorry
