### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by milandzuris** [tteck/Proxmox#2955]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi do you help me with this problem?, thanks

1
![image](https://github.com/tteck/Proxmox/assets/42905545/1ea0eee1-be99-43e7-9d3e-c1d6d9631846)

2
![image](https://github.com/tteck/Proxmox/assets/42905545/9cd26cea-acfe-4a34-98c4-7c1c4efca547)

3
![image](https://github.com/tteck/Proxmox/assets/42905545/8a6f945d-471a-40e5-9497-2693989ed362)

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
   __  __      _ _____ 
  / / / /__   (_) __(_)
 / / / / __ \/ / /_/ / 
/ /_/ / / / / / __/ /  
\____/_/ /_/_/_/ /_/   
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: unifi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Unifi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Eclipse Temurin JRE
 ✓ Installed MongoDB
 ✓ Installed UniFi Network Server
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Unifi should be reachable by going to the following URL.
         https://192.168.86.250:8443 
```

**Comment by milandzuris** [comment]
> 🏁 The script runs without any problems from this end.
> 
> ```
>    __  __      _ _____ 
>   / / / /__   (_) __(_)
>  / / / / __ \/ / /_/ / 
> / /_/ / / / / / __/ /  
> \____/_/ /_/_/_/ /_/   
>  
> Using Advanced Settings
> Using Distribution: debian
> Using debian Version: 12
> Using Container Type: 1
> Using Root Password: Automatic Login
> Container ID: 112
> Using Hostname: unifi
> Using Disk Size: 8
> Allocated Cores: 2
> Allocated RAM: 2048
> Using Bridge: vmbr0
> Using IP Address: dhcp
> Using Gateway IP Address: Default
> Using APT-Cacher IP Address: Default
> Disable IPv6: yes
> Using Interface MTU Size: Default
> Using DNS Search Domain: Host
> Using DNS Server IP Address: Host
> Using MAC Address: AE:1A:60:07:B7:59
> Using Vlan: Default
> Enable Root SSH Access: no
> Enable Verbose Mode: no
> Creating a Unifi LXC using the above advanced settings
>  ✓ Using local for Template Storage.
>  ✓ Using thin-pool for Container Storage.
>  ✓ Updated LXC Template List
>  ✓ LXC Container 112 was successfully created.
>  ✓ Started LXC Container
>  ✓ Set up Container OS
>  ✓ Network Connected: 192.168.86.250 
>  ✓ IPv4 Internet Connected
>  ✗ IPv6 Internet Not Connected
>  ✓ DNS Resolved github.com to 140.82.114.4
>  ✓ Updated Container OS
>  ✓ Installed Dependencies
>  ✓ Installed Eclipse Temurin JRE
>  ✓ Installed MongoDB
>  ✓ Installed UniFi Network Server
>  ✓ Customized Container
>  ✓ Cleaned
>  ✓ Completed Successfully!
> 
> Unifi should be reachable by going to the following URL.
>          https://192.168.86.250:8443 
> ```

Ok how to fix this problem?

**Comment by tteck** [comment]
What Proxmox version are you using? Show the output of `pveversion`

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by milandzuris** [comment]
> What Proxmox version are you using? Show the output of `pveversion`

8.2.2

**Comment by tteck** [comment]
Show the output of `pveversion`

**Comment by milandzuris** [comment]
> pveversion

![image](https://github.com/tteck/Proxmox/assets/42905545/1d83879a-0f12-4c79-b33d-a4c31876941c)

**Comment by tteck** [comment]
Does Default settings work?

**Comment by milandzuris** [comment]
> Does Default settings work?

default work

**Comment by tteck** [comment]
That suggests that your settings are incorrect when utilizing Advanced

**Comment by milandzuris** [comment]
> That suggests that your settings are incorrect when utilizing Advanced

i only set password and change hhd to 4gb
