### ISSUE TITLE
YunoHost is only available for the version 11 (Bullseye) of Debian

### ISSUE THREAD

**Issue by kotovasia5120** [tteck/Proxmox#2957]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

```
 ✓ Installed Dependencies
 /[FAIL] YunoHost is only available for the version 11 (Bullseye) of Debian, you are using '12.5'.
[INFO] Installation logs are available in /var/log/yunohost-installation_20240511_160517.log

[ERROR] in line 29: exit code 0: while executing command $STD bash <(curl -fsSL https://install.yunohost.org) -a
root@proxmox:~# 
```
Is it possible to add a check for supported versions?

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

![Screenshot 2024-05-11 9 13 40 AM](https://github.com/tteck/Proxmox/assets/21342670/cf97f57b-08f0-4356-83c2-27626231446a)
