### ISSUE TITLE
Whoogle LXC 500 server error

### ISSUE THREAD

**Issue by spants** [tteck/Proxmox#296]
Not sure whether it is the script of the Whoogle code itself, but it seems to work for a couple of queries and then gives a 500 Server Error response. 
Not sure how to get logs for this.....

(Thanks for all your work on these helpers - they are fantastic!)

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/287

**Comment by spants** [comment]
thanks -= just found that - will check
