### ISSUE TITLE
Omada script entry is showing the TP-Link URL instead of the command to execute in the PVE shell

### ISSUE THREAD

**Issue by djismgaming** [tteck/Proxmox#2961]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Omada LXC script is showing the URL `https://www.tp-link.com/us/support/download/omada-software-controller/` instead of the script download/execution command:

```bash
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/omada.sh)"
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Go to the URL `https://helper-scripts.com/scripts` and search for "omada". The section "How to install" and see the URL there instead of the execution command.

**Comment by tteck** [comment]
fixed
