### ISSUE TITLE
Script Nginx Proxy Manager error generate  Let’s Encrypt Namecheap

### ISSUE THREAD

**Issue by vsc55** [tteck/Proxmox#2962]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to create a wildcard certificate in Let's Encrypt in the Namecheap provider, the following error is generated.

```CommandError: usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-namecheap-credentials /etc/letsencrypt/credentials/credentials-48

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

I was able to solve it by installing the certbot plugin manually:
```
pip install certbot-dns-namecheap
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🚨 Since there are hundreds of Certbot instances, it's necessary to install the specific Certbot of your preference.

**Comment by vsc55** [comment]
Wouldn't it be nice to add a note in the installation procedure documentation?
