### ISSUE TITLE
Frigate LXC-update fails

### ISSUE THREAD

**Issue by raeserfisk** [tteck/Proxmox#2963]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

When trying to call an update by issuing "update" from within container the script starts properly but then exits saying "There is currently no update path available".

This could be as intended saying there is no update available at the moment. I would suggest a rewrite to remove potential misunderstanding.

PS.
I don't know if this is related to "Helper-scripts.com" not cover NVR-section (including Frigate) yet(?).

Cheers,
Kalle

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

Install with default settings and then call update in container shell.

**Comment by tteck** [comment]
"There is currently no update path available" means that there is no way to update the software, period. 

Fixed the site. Thanks

**Comment by raeserfisk** [comment]
Thank you kindly for quick and thorough answer :)
