### ISSUE TITLE
unifi - fails without AVX

### ISSUE THREAD

**Issue by atcapollo** [tteck/Proxmox#2965]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

This doesn't work if the proxmox CPU doesn't support AVX.

Mongodb fails.... can you add either  a notice or a check to preempt someone getting stuck with this?

I am using a Dell Wyse 5070 which seems not to be compatible

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Journalctl returns:
```
-- Boot 87328089ce8f4f9dbe474650c99560ab --
May 11 22:04:43 zebulon-prx-unifi systemd[1]: Starting unifi.service - unifi...
May 11 22:04:44 zebulon-prx-unifi unifi[236]: init complete...
May 11 22:04:44 zebulon-prx-unifi unifi-network-service-helper[236]: <13>May 11 22:04:44 unifi: init complete...

```

Systemctl returns:
```
systemctl status unifi
* unifi.service - unifi
     Loaded: loaded (/lib/systemd/system/unifi.service; enabled; preset: enabled)
     Active: activating (start) since Sat 2024-05-11 22:04:43 BST; 7min ago
    Process: 197 ExecStartPre=/usr/sbin/unifi-network-service-helper init (code=exited, status=0/SUCCESS)
    Process: 237 ExecStartPre=/usr/sbin/unifi-network-service-helper init-uos (code=exited, status=0/SUCCESS)
   Main PID: 241 (java)
      Tasks: 171 (limit: 9230)
     Memory: 587.2M
        CPU: 34.420s
     CGroup: /system.slice/unifi.service
             `-241 /usr/bin/java -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Dapple.awt.UIElement=true -Dunifi.core.enabled=false -Dunifi.mongodb.service.e>

May 11 22:04:43 zebulon-prx-unifi systemd[1]: Starting unifi.service - unifi...
May 11 22:04:44 zebulon-prx-unifi unifi[236]: init complete...
May 11 22:04:44 zebulon-prx-unifi unifi-network-service-helper[236]: <13>May 11 22:04:44 unifi: init complete...

```

/var/log/unifi/server.log
```
[2024-05-11 22:12:54,840] <mongod-tail> WARN  mongo  - Mongo log not found during startup
[2024-05-11 22:12:54,860] <mongo-db> WARN  mongo  - Stop listening to Mongo logs after process has exited
[2024-05-11 22:12:54,861] <mongo-db> INFO  mongo  - Database process stopped, code=132
```

### Please provide detailed steps to reproduce the issue.

start container

__go to web interface

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/2738

**Comment by tteck** [comment]
Added a notice to the website.

![Screenshot 2024-05-11 6 37 56 PM](https://github.com/tteck/Proxmox/assets/21342670/77680837-0b45-4af2-a312-35f45b820ac6)

https://www.mongodb.com/legal/support-policy/lifecycles

🧐 As this issue is unrelated to the script, it is considered closed.
