### ISSUE TITLE
Update Paperless 2.7.2 to 2.8.3 failes

### ISSUE THREAD

**Issue by Stephan-4711** [tteck/Proxmox#2974]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While updating paperpless I get an error. How to enable  verbose mode while update? I tried many diffrent switches and used google. But it didn't work

cat: /opt/Paperless-ngx_version.txt: Datei oder Verzeichnis nicht gefunden (file or folder not found)
 ✓ Stopped all Paperless-ngx Services
 - Updating to v2.8.3   
[ERROR] in line 83: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2925
