### ISSUE TITLE
Paperless Update Issue

### ISSUE THREAD

**Issue by themanbornwithin** [tteck/Proxmox#2976]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the update command, it fails with "[ERROR] in line 83: exit code 0: while executing command /usr/bin/python3 manage.py migrate &> /dev/null"

Running the command manually results in the following two errors:
psycopg2.errors.FeatureNotSupported: conversion between UTF8 and SQL_ASCII is not supported
django.db.utils.NotSupportedError: conversion between UTF8 and SQL_ASCII is not supported

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

**HOW I FIXED IT**

I had found instructions online to backup the db, remove it and import it as UTF8. This worked, but then I got permission issues, I managed to work through those as well. When I wiped everything and started fresh to ensure that I had my instructions down correctly to post on issue 2925, I mistyped a command. What I ended up finding is that in the script, it runs the following:

```
cd /opt/paperless/src
/usr/bin/python3 manage.py migrate &>/dev/null
```

If I change it to
```
#cd /opt/paperless/src
/usr/bin/python3 /opt/paperless/src/manage.py migrate &>/dev/null
```
the entire script runs correctly, and Paperless is updated to the latest version. I have no idea why it works this way.

**Comment by themanbornwithin** [comment]
Sorry, I should have specified that I originally running 2.7.3

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/2925
