### ISSUE TITLE
Nginx Proxy Manager error: 400 Parameter verification failed. hostname: invalid format - value does not look like a valid DNS name

### ISSUE THREAD

**Issue by GnussonNet** [tteck/Proxmox#298]
<img width="653" alt="Screenshot 2022-06-22 at 18 14 33" src="https://user-images.githubusercontent.com/40320838/175082605-7fbb504a-7ae2-4d4e-9b16-13459e1bba11.png">

**Comment by tteck** [comment]
exceed hostname length limit

**Comment by GnussonNet** [comment]
Tried debugging and found out that the CT Name (nginx proxy manager's hostname) can't includes "_" (underscores)

**Comment by tteck** [comment]
yep, I see them now  😉
