### ISSUE TITLE
'mysql' is depricated and should be exchanged by '/usr/bin/mariadb'

### ISSUE THREAD

**Issue by Wolk9** [tteck/Proxmox#2993]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

in your post-instralation manual you mention 'mysql' as command but 'mysql' is depricated and should be exchanged by '/usr/bin/mariadb'

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

``

### Please provide detailed steps to reproduce the issue.

Following the post install steps

**Comment by tteck** [comment]
Thanks, fixed.
