### ISSUE TITLE
Can't create LXCs

### ISSUE THREAD

**Issue by shaddowlink** [tteck/Proxmox#2994]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am not able to create or better run LXCs with the script, on my fresh Proxmox installation. I am stuck at the same part, with default settings, at this error:  

```
[...]
Creating a Pihole LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 103 was successfully created.
 |safe_mount: 1425 Operation not permitted - Failed to mount "proc" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs/proc"
lxc_mount_auto_mounts: 614 Operation not permitted - Failed to mount "proc" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs/proc" with flags 14
lxc_setup: 3906 Failed to setup first automatic mounts
do_start: 1273 Failed to setup container "103"
sync_wait: 34 An error occurred in another process (expected sequence number 3)
__lxc_start: 2114 Failed to spawn container "103"
startup for container '103' failed

[ERROR] in line 618: exit code 0: while executing command pct start "$CTID"
```

Using `proxmox-ve: 8.2.0 (running kernel: 6.8.4-3-pve)`
lxcfs is runngin
Creating VMs worked and they run. Manual and with script
Tried several ones (Pi-hole, plex,...) always stuck

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

install proxmox, try to run LXC script

**Comment by tteck** [comment]
Are you using user `root` and utilizing the Proxmox shell?

**Comment by tteck** [comment]
It seems like there's an issue with mounting the "proc" filesystem inside a container, likely due to a permission problem. 

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by shaddowlink** [comment]
> Are you using user `root` and utilizing the Proxmox shell?

yes, using the shell of the webui with root
