### ISSUE TITLE
Receiving error 143 when creating a Proxmox Nginx Proxy Manager LXC Container

### ISSUE THREAD

**Issue by circa1741** [tteck/Proxmox#3]
I am trying to create a Proxmox Nginx Proxy Manager LXC Container. However, I am receiving the error message:

**[error] 143 NULL: _storage_type=$(pvesm status -storage $_storage 2>/dev/null | awk 'NR>1 {print $2}')**

The full output is:

root@pvehost:~#  curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s

[warn] Container will be created using the following settings.
[warn] 
[warn] ctid:     104
[warn] hostname: nginx-proxy-manager
[warn] cores:    1
[warn] memory:   512
[warn] swap:     0
[warn] disksize: 2G
[warn] bridge:   vmbr0
[warn] storage:  local-lvm
[warn] templates:  local
[warn] 
[warn] If you want to abort, hit ctrl+c within 10 seconds...

[info] Updating LXC template list...
[info] Downloading LXC template...
**[error] 143 NULL: _storage_type=$(pvesm status -storage $_storage 2>/dev/null | awk 'NR>1 {print $2}')**

Any feedback is appreciated. Thanks.

**Comment by tteck** [comment]
Do you have local-lvm?

**Comment by circa1741** [comment]
Sorry, I do not.
Do you have a version of your Wireguard Helper that is for storage type = local?

**Comment by tteck** [comment]
What storage type are you using?
I don't have Wireguard listed in the helpers.

**Comment by circa1741** [comment]
I am sorry I am mixing things up. (Reminder to myself): This is regarding Nginx Proxy Manager and not Wireguard.
Anyway, my storage type is local only. I do not have local-lvm nor local-zfs.
I am wondering if you have a version of your Nginx Proxy Manager Helper that is for storage type = local?

**Comment by tteck** [comment]
Try `curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s -- --storage local`

**Comment by circa1741** [comment]
The installation completed and I can navigate to the login page. Thank you very much.
