### ISSUE TITLE
"Latest Kernel:" Wrong on Proxmox Kernel Clean script

### ISSUE THREAD

**Issue by jbabio** [tteck/Proxmox#301]
I've ran the Proxmox Kernel Clean script and got this output:

************************
_PVE Version: pve-manager/7.2-5/12f1e639 (running kernel: 5.15.35-2-pve)

**Latest Kernel: pve-kernel-5.4.174-2-pve**
'pve-kernel-5.4.174-2-pve' has been added to the remove Kernel list
'pve-kernel-5.13.19-6-pve' has been added to the remove Kernel list
'pve-kernel-5.15.30-2-pve' has been added to the remove Kernel list
'pve-kernel-5.15.35-1-pve' has been added to the remove Kernel list

 ✓ Kernel Search Completed_
************************

It states that the "Latest kernel:" is "pve-kernel-5.4.174-2-pve" which is, in fact, the "Oldest kernel".

Maybe I'm mistaken, and this has other meaning.

Regards, and thank you for your work.

**Comment by tteck** [comment]
I think `pve-kernel-5.4.174-2-pve` is the latest Proxmox 6.4 kernel.

The script runs `uname -r` to find the current kernel, and uses that info in
```
function kernel_info() {
    latest_kernel=$(dpkg --list| grep 'kernel-.*-pve' | awk '{print $2}' | tac | head -n 1)
    echo -e "PVE Version: $pve\n"
    if [[ "$current_kernel" == *"pve"* ]]; then
      if [[ "$latest_kernel" != *"$current_kernel"* ]]; then
        echo -e "Latest Kernel: $latest_kernel\n"
      fi
    else
        echo -e "\nERROR: No PVE Kernel Found\n"
        exit 1
    fi
```
Anyway, it looks like the script did it's job and corrected whatever was going on with that "old" PVE 6 kernel

**Comment by jbabio** [comment]
Yes, the script worked and deleted all the old kernels, including the PVE 6 one, without issues,
