### ISSUE TITLE
confusion ct type OMV LXC

### ISSUE THREAD

**Issue by gilbrotheraway** [tteck/Proxmox#3010]
the omv script has unprivileged ct as it's default but afaik there's no way to run nfs/smb shares that way, what i'm missing?

also how are people attaching disks to the LXC??
### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
