### ISSUE TITLE
Hyperhdr script

### ISSUE THREAD

**Issue by thepuncake** [tteck/Proxmox#3014]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

First let me say hello. I've installed many of your scripts on proxmox and it has streamlined things greatly so thanks for that. I have a little bit of an issue with hyperhdr. After upgrading to version 20 from a recent beta my config is nowhere to be found. I tried asking in the hyperhdr GitHub but haven't gotten anywhere sadly. I noticed by the way that you provide an update command for Hyperion lxc btw but not a hyperhdr and I imagine there's a reason for that. Do you have any clues as to what happened to my config? This is what I used to update in the lxc shell: `sudo apt update && sudo apt install hyperhdr -y`. Thanks in advance. I'm on the latest version of proxmox.
- Theo 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Install version 20 beta 1 hyperhdr with the script and try to update in the lxc console with: `sudo apt update && sudo apt install hyperhdr -y`

**Comment by tteck** [comment]
All that you should have done is `apt update && apt upgrade` that would have picked up any new versions in their repository. When you executed `apt install hyperhdr -y` you got a fresh install.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by thepuncake** [comment]
Oh no, thanks for your reply regardless. Maybe include the update command in the script page so people avoid making the same mistake.

**Comment by thepuncake** [comment]
Btw would be great if you could chime in here and clarify some things if you have the time: 

https://github.com/awawa-dev/HyperHDR/discussions/813#discussioncomment-9489512

I seem to be getting conflicting info 😂

**Comment by tteck** [comment]
Ok, I just created a HyperHDR LXC. He is correct in that the database should persist during updates and installs. You can find the database here `cd /.hyperhdr/db/`. Now why you lost yours, 🤷🏻‍♂️ .

**Comment by thepuncake** [comment]
There is only one file in that directory and it's the newly generated one. Any vague idea on what could have gone wrong?
