### ISSUE TITLE
Installing when using APT Cacher NG always fails

### ISSUE THREAD

**Issue by chrismanivong** [tteck/Proxmox#3016]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When using prior installed APT-Cacher-NG to execute any script, and using the advanced installation options, adding here the IP of the APT-Cacher-NG, the installation of another script will fail on Debian 12 installations.

When installing with these scripts, it will fetch the installation packages from the internet and everything works.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

From the logs:

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/perl/libperl5.36_5.36.0-7%2bdeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/perl/perl_5.36.0-7%2bdeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/perl/perl-base_5.36.0-7%2bdeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/perl/perl-modules-5.36_5.36.0-7%2bdeb12u1_all.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/tar/tar_1.34%2bdfsg-1.2%2bdeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/libnss-systemd_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/systemd-timesyncd_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/libpam-systemd_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/systemd_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/libsystemd-shared_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/systemd-sysv_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cryptsetup/libcryptsetup12_2.6.1-4%7edeb12u2_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/libsystemd0_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/postfix/postfix_3.7.10-0%2bdeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gnutls28/libgnutls30_3.7.9-2%2bdeb12u2_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/udev_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/libudev1_252.22-1%7edeb12u1_amd64.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/u/usrmerge/usrmerge_37%7edeb12u1_all.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/tzdata/tzdata_2024a-0%2bdeb12u1_all.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Failed to fetch http://deb.debian.org/debian/pool/main/d/distro-info-data/distro-info-data_0.58%2bdeb12u1_all.deb  503  Connection reset by peer [IP: 172.22.40.2 3142]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

[ERROR] in line 167: exit code 0: while executing command $STD apt-get -o Dpkg::Options::="--force-confold" -y dist-upgrade

172.22.40.2 is my APT-Cacher-NG install I did from this repository.

### Please provide detailed steps to reproduce the issue.

First install from https://helper-scripts.com/scripts?id=Apt-Cacher-NG
Than install any other script from helper-scripts.com with the selection of Debian Bookworm 12.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    ____       __    _           
   / __ \___  / /_  (_)___  ____ 
  / / / / _ \/ __ \/ / __ `/ __ \
 / /_/ /  __/ /_/ / / /_/ / / / /
/_____/\___/_.___/_/\__,_/_/ /_/ 
                                 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: debian
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: 192.168.86.109
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Debian LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by tteck** [comment]
```
    ____           ___     
   / __ \___  ____/ (_)____
  / /_/ / _ \/ __  / / ___/
 / _, _/  __/ /_/ / (__  ) 
/_/ |_|\___/\__,_/_/____/  

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: redis
Using Disk Size: 4
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: 192.168.86.109
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Redis LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Redis
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

🧐 As this issue is unrelated to the script, it is considered closed.
