### ISSUE TITLE
Feature: Update Command

### ISSUE THREAD

**Issue by milandzuris** [tteck/Proxmox#3017]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi there is chance add to webpage command for update individual (lxc vm), idk how to update Z2M NR and other, but pihole have command pihole -up.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

Type the command `update` in the LXC console
