### ISSUE TITLE
Home Assistant Core wrong OS requirements

### ISSUE THREAD

**Issue by Epic-F** [tteck/Proxmox#3025]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to install (advanced) Home Assistant Core using the script (see link below) it says it requires Ubuntu 24.04, however, it generates the following error: 
_```
unable to create CT 205 - unsupported Ubuntu version '24.04'
bash: line 182: exit: A problem occured while trying to create container.: numeric argument required
```_

https://helper-scripts.com/scripts?id=Home+Assistant+Core

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

unable to create CT 205 - unsupported Ubuntu version '24.04'
bash: line 182: exit: A problem occured while trying to create container.: numeric argument required

### Please provide detailed steps to reproduce the issue.

_No response_

**Comment by tteck** [comment]
![Screenshot 2024-05-20 3 37 38 PM](https://github.com/tteck/Proxmox/assets/21342670/be7be65d-68b7-4b91-8f52-24c46807a2bf)

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
