### ISSUE TITLE
NGINX does not log into access.log

### ISSUE THREAD

**Issue by DST73** [tteck/Proxmox#3033]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have noticed that NGINX logs into error.log but does not log into access.log

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![grafik](https://github.com/tteck/Proxmox/assets/122279682/46735579-1bdc-4eaa-95de-db3ad87b8f16)

### Please provide detailed steps to reproduce the issue.

Have installed NGINX using the script

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by DST73** [comment]
Why is this issue closed ?
