### ISSUE TITLE
Docker-Alpine LXC script errors out due to problems with Alpine repository

### ISSUE THREAD

**Issue by trenchcoatjedi** [tteck/Proxmox#3035]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The script for the Docker on Alpine LXC currently errors out due to problems with the Alpine repository

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Proxmox console output, errors bolded

Using Default Settings
Using Container Type: 1
Using Root Password: *secret*
Container ID: 101
Using Hostname: alpine-docker
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: yes
Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 101 was successfully created.
 ✓ Started LXC Container
 * service sysctl added to runlevel default
 ✓ Set up Container OS
 ✓ Network Connected: *IP ADDRESS*
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 - Updating Container OS...fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
v3.20.0_rc2-113-g1402388a3a7 [http://dl-cdn.alpinelinux.org/alpine/latest-stable/main]
v3.20.0_rc2-111-g2fb6423efca [http://dl-cdn.alpinelinux.org/alpine/latest-stable/community]
OK: 24173 distinct packages available
Upgrading critical system libraries and apk-tools:
(1/1) Upgrading apk-tools (2.14.0-r5 -> 2.14.4-r0)
**ERROR: apk-tools-2.14.4-r0: BAD signature**
Continuing the upgrade transaction with new apk-tools:
(1/25) Upgrading alpine-baselayout-data (3.4.3-r2 -> 3.6.5-r0)
(2/25) Upgrading musl (1.2.4_git20230717-r4 -> 1.2.5-r0)
(3/25) Upgrading busybox (1.36.1-r15 -> 1.36.1-r28)
Executing busybox-1.36.1-r28.post-upgrade
(4/25) Upgrading busybox-binsh (1.36.1-r15 -> 1.36.1-r28)
(5/25) Upgrading alpine-baselayout (3.4.3-r2 -> 3.6.5-r0)
Executing alpine-baselayout-3.6.5-r0.pre-upgrade
Executing alpine-baselayout-3.6.5-r0.post-upgrade
(6/25) Upgrading ifupdown-ng (0.12.1-r4 -> 0.12.1-r5)
(7/25) Upgrading libcap2 (2.69-r1 -> 2.70-r0)
(8/25) Upgrading openrc (0.52.1-r2 -> 0.54-r1)
Executing openrc-0.54-r1.post-upgrade
(9/25) Upgrading mdev-conf (4.6-r0 -> 4.7-r0)
(10/25) Upgrading busybox-mdev-openrc (1.36.1-r15 -> 1.36.1-r28)
(11/25) Upgrading alpine-conf (3.17.2-r0 -> 3.18.0-r0)
(12/25) Upgrading alpine-release (3.19.1-r0 -> 3.20.0-r0)
(13/25) Upgrading ca-certificates-bundle (20230506-r0 -> 20240226-r0)
**ERROR: ca-certificates-bundle-20240226-r0: BAD signature**
(14/25) Upgrading libcrypto3 (3.1.4-r5 -> 3.3.0-r2)
(15/25) Upgrading libssl3 (3.1.4-r5 -> 3.3.0-r2)
(16/25) Upgrading ssl_client (1.36.1-r15 -> 1.36.1-r28)
(17/25) Upgrading zlib (1.3.1-r0 -> 1.3.1-r1)
(18/25) Upgrading apk-tools (2.14.0-r5 -> 2.14.4-r0)
**ERROR: apk-tools-2.14.4-r0: BAD signature**
(19/25) Upgrading busybox-openrc (1.36.1-r15 -> 1.36.1-r28)
(20/25) Upgrading busybox-suid (1.36.1-r15 -> 1.36.1-r28)
(21/25) Purging libc-utils (0.7.2-r5)
(22/25) Upgrading musl-utils (1.2.4_git20230717-r4 -> 1.2.5-r0)
(23/25) Upgrading alpine-base (3.19.1-r0 -> 3.20.0-r0)
(24/25) Upgrading doas (6.8.2-r6 -> 6.8.2-r7)
Executing doas-6.8.2-r7.post-upgrade
(25/25) Upgrading libacl (2.3.1-r4 -> 2.3.2-r0)
Executing busybox-1.36.1-r28.trigger
2 errors; 12 MiB in 33 packages

**[ERROR] in line 100: exit code 2: while executing command $STD apk upgrade**

### Please provide detailed steps to reproduce the issue.

Run the script as is.

**Comment by tteck** [comment]
Yeah, looks like the issue is with the Alpine repository, nothing that I can do for that.

**Comment by trenchcoatjedi** [comment]
The script hits the repository for Alpine 3.20.0_rc2 but the container runs Alpine 3.19

Is there a way to force it to use the repository for version 3.19?

**Comment by tteck** [comment]
It's currently set to latest-stable
https://github.com/tteck/Proxmox/blob/73291211a885df94a8419d3fa38ecbff05f9ab3c/misc/build.func#L622-L625

https://github.com/tteck/Proxmox/commit/d468fc6c1f0bb379f824b193113e872db72401d2 working now

```
    ____             __            
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 Alpine
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: alpine-docker
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker
Would you like to add Portainer? <y/N> 
Would you like to add the Portainer Agent? <y/N> 
Would you like to add Docker Compose? <y/N> 
 ✓ Customized Container
 ✓ Completed Successfully!
```
