### ISSUE TITLE
Prowlarr update says "There is currently no update path available." despite /opt containing the app

### ISSUE THREAD

**Issue by jarjarfinks** [tteck/Proxmox#3037]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I ran the Prowlarr script from within my Prowlarr LXC and it complained about "There is currently no update path available." I did a directory listing for `/opt` and it's definitely there. Not sure what's wrong

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
The message "There is currently no update path available." means exactly that, the script has no update method available.

**Comment by jarjarfinks** [comment]
Prowlarr WebUI states there is an update but the built in update mechanism isn't working.

**Comment by tteck** [comment]
There has not been an update script created.
