### ISSUE TITLE
Update emby

### ISSUE THREAD

**Issue by cob94440** [tteck/Proxmox#3047]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Emby says a new version is available
when i launch :
curl -sL https://api.github.com/repos/MediaBrowser/Emby.Releases/releases/latest | grep '"tag_name":' | cut -d'"' -f4

i see a new version but how to update

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by therumbler** [comment]
to update, connect to the LCX (ssh, or via Proxmox UI console) and run the command `update`

**Comment by cob94440** [comment]
thanks it works
