### ISSUE TITLE
Photoprism installing script is failing

### ISSUE THREAD

**Issue by LionSander** [tteck/Proxmox#3048]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Encountering an Error message during installation. The service cannot start. 

installing libvips42 fixed the service. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
photoprism.service - PhotoPrism service
     Loaded: loaded (/etc/systemd/system/photoprism.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-05-23 22:32:31 CEST; 50s ago
    Process: 11133 ExecStart=/opt/photoprism/bin/photoprism up -d (code=exited, status=127)
        CPU: 999us

May 23 22:32:31 photoprism systemd[1]: Starting photoprism.service - PhotoPrism service...
May 23 22:32:31 photoprism photoprism[11133]: /opt/photoprism/bin/photoprism: error while loading shared libraries: libvips.so.42: cannot open shared object file: No such file or directory
May 23 22:32:31 photoprism systemd[1]: photoprism.service: Control process exited, code=exited, status=127/n/a
May 23 22:32:31 photoprism systemd[1]: photoprism.service: Failed with result 'exit-code'.
May 23 22:32:31 photoprism systemd[1]: Failed to start photoprism.service - PhotoPrism service.
```

**Comment by LionSander** [comment]
If you [build from source](https://docs.photoprism.app/getting-started/faq/#building-from-source) or use one of our [binary installation packages](https://dl.photoprism.app/pkg/linux/README.html), the system on which you build and/or run PhotoPrism must have libvips >= 8.10 installed.  <-- From https://github.com/photoprism/photoprism/releases

**Comment by dbzoo** [comment]
I created [PR#3049](https://github.com/tteck/Proxmox/pull/3049) for this issue.

**Comment by LionSander** [comment]
@dbzoo Thanks :)
