### ISSUE TITLE
Nextcloud alpine creds not shown

### ISSUE THREAD

**Issue by DmitryNefedov** [tteck/Proxmox#3055]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While installing alpine-nextcloud after the installation no credentials are shown.

Accessing the container shell and running `cat nextcloud.creds` reveals the credentials.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/7058068/3efaa624-49b0-431c-914e-e0a8df1849e4)

### Please provide detailed steps to reproduce the issue.

1. access proxmox shell
2. run bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-nextcloud.sh)"
3. choose advanced settings 
4. wait for installation to complete
5. no credentials are shown

**Comment by tteck** [comment]
Execute `bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-nextcloud.sh)"` in the LXC console. Need to add those instructions to the new site.
