### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by ashoktvm** [tteck/Proxmox#3058]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I need the root password of jellyfin LXC, since I need to update the server

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
❗ It is crucial not to exit the Proxmox shell while running scripts. Leaving the shell during script execution will result in the script being interrupted.

**Comment by ashoktvm** [comment]
> ❗ It is crucial not to exit the Proxmox shell while running scripts. Leaving the shell during script execution will result in the script being interrupted.

U got me wrong. The LXC has been installed perfectly.  Only issue is it asks for login when accessing console

**Comment by tteck** [comment]
If you used "Default Settings" it uses autologin, unless the script didn't finish.
