### ISSUE TITLE
Sabnzbd script fails with an error

### ISSUE THREAD

**Issue by johnsturgeon** [tteck/Proxmox#3064]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I get an error when trying to install the sabnzbd script.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
Err:2 http://deb.debian.org/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

[ERROR] in line 25: exit code 0: while executing command $STD apt-get update
```

### Please provide detailed steps to reproduce the issue.

* wget
* advanced

Here are the settings I changed
* ubuntu
* 22.04
* static IP

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by johnsturgeon** [comment]
Gotcha, thx.  Sorry for the issue
