### ISSUE TITLE
Nextcloud-alpine

### ISSUE THREAD

**Issue by CrazyWolf13** [tteck/Proxmox#3068]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After trying to access my nextcloud instance today I get greeted wth the following message:
![image](https://github.com/tteck/Proxmox/assets/96661824/53a9bced-7c43-459f-89b7-544b784d2b9a)
I could fix this by running
`apk add nextcloud-files_reminders`
after that I get greeted with a update note:
![image](https://github.com/tteck/Proxmox/assets/96661824/7da485b1-ae53-4e78-b7d3-7143c1da129a)

After trying to click update, I get the following error:
![image](https://github.com/tteck/Proxmox/assets/96661824/375bfa6f-7526-4b32-a9ef-62296cd08791)

Also the script update function seems to be broken atm:
![image](https://github.com/tteck/Proxmox/assets/96661824/13132fd6-c341-44e1-b2ee-e8302055e8eb)

This seems to be an upstream alpine problem tough:
https://gitlab.alpinelinux.org/alpine/aports/-/issues/16147

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Alpine

### Please provide detailed steps to reproduce the issue.

create a alpine nextcloud lxc
get greeted with that note.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    _   __          __       __                __   __  __      __
   / | / /__  _  __/ /______/ /___  __  ______/ /  / / / /_  __/ /_
  /  |/ / _ \| |/_/ __/ ___/ / __ \/ / / / __  /  / /_/ / / / / __ \
 / /|  /  __/>  </ /_/ /__/ / /_/ / /_/ / /_/ /  / __  / /_/ / /_/ /
/_/ |_/\___/_/|_|\__/\___/_/\____/\__,_/\__,_/  /_/ /_/\__,_/_.___/
Alpine
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: alpine-nextcloud
Using Disk Size: 2
Allocated Cores: 2
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Nextcloud LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed PHP/Redis
 ✓ Installed MySQL Database
 ✓ Installed Nextcloud
 ✓ Added Additional Nextcloud Packages
 ✓ Started Services
 ✓ Finished Nextcloud Setup-Wizard
 ✓ Customized Container
 ✓ Completed Successfully!

Alpine-Nextcloud should be reachable by going to the following URL.
         https://192.168.86.250 
```
![Screenshot 2024-05-26 7 17 11 AM](https://github.com/tteck/Proxmox/assets/21342670/20f77cf8-8d95-4e0f-bfb6-ef4c88978942)

![Screenshot 2024-05-26 7 17 28 AM](https://github.com/tteck/Proxmox/assets/21342670/3dc572ce-9e75-4c56-8aca-8047c35c1810)

![Screenshot 2024-05-26 7 17 50 AM](https://github.com/tteck/Proxmox/assets/21342670/e47aafc8-0ad3-4042-9f1e-0c673e8c3622)

![Screenshot 2024-05-26 7 18 42 AM](https://github.com/tteck/Proxmox/assets/21342670/4b7b1dce-ce65-411e-9440-9ebf257c3b0a)

![Screenshot 2024-05-26 7 19 51 AM](https://github.com/tteck/Proxmox/assets/21342670/16daf8c9-e7ff-4ee1-ac88-49307a2185c5)

```
    _   __          __       __                __   __  __      __
   / | / /__  _  __/ /______/ /___  __  ______/ /  / / / /_  __/ /_
  /  |/ / _ \| |/_/ __/ ___/ / __ \/ / / / __  /  / /_/ / / / / __ \
 / /|  /  __/>  </ /_/ /__/ / /_/ / /_/ / /_/ /  / __  / /_/ / /_/ /
/_/ |_/\___/_/|_|\__/\___/_/\____/\__,_/\__,_/  /_/ /_/\__,_/_.___/
Alpine
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
v3.19.1-577-gb3ea1811daf [http://dl-cdn.alpinelinux.org/alpine/v3.19/main]
v3.19.1-575-gd679707d49e [http://dl-cdn.alpinelinux.org/alpine/v3.19/community]
OK: 23030 distinct packages available
OK: 1008 MiB in 251 packages
Nextcloud is already latest version
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Check indices of the oc_jobs table.
Check indices of the oc_direct_edit table.
Check indices of the oc_preferences table.
Check indices of the oc_mounts table.
Check indices of the oc_systemtag_object_mapping table.
Done.
alpine-nextcloud:~# 
```
I have no issues here. Check your repositories `cat /etc/apk/repositories` I know that for some reason the `latest-stable` branch was going to release candidates. I made a change here https://github.com/tteck/Proxmox/commit/d468fc6c1f0bb379f824b193113e872db72401d2. Try the below

``` 
#http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
#http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
http://dl-cdn.alpinelinux.org/alpine/v3.19/main
http://dl-cdn.alpinelinux.org/alpine/v3.19/community
```

**Comment by CrazyWolf13** [comment]
Thanks, the fix provided with the v3.19 repo worked, so I guess there is an upstream problem.

However there still seems to be an issue with the script, mine is unable to update:

```
    _   __          __       __                __   __  __      __
   / | / /__  _  __/ /______/ /___  __  ______/ /  / / / /_  __/ /_
  /  |/ / _ \| |/_/ __/ ___/ / __ \/ / / / __  /  / /_/ / / / / __ \
 / /|  /  __/>  </ /_/ /__/ / /_/ / /_/ / /_/ /  / __  / /_/ / /_/ /
/_/ |_/\___/_/|_|\__/\___/_/\____/\__,_/\__,_/  /_/ /_/\__,_/_.___/
Alpine
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
v3.19.1-577-gb3ea1811daf [http://dl-cdn.alpinelinux.org/alpine/v3.19/main]
v3.19.1-575-gd679707d49e [http://dl-cdn.alpinelinux.org/alpine/v3.19/community]
OK: 23231 distinct packages available
OK: 981 MiB in 244 packages
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
Maintenance mode is kept active
Resetting log level

[ERROR] in line 85: exit code 0: while executing command su nextcloud -s /bin/sh -c 'php82 /usr/share/webapps/nextcloud/occ upgrade'

alpine-nextcloud:~# ^C
```

I'm also unable to opt-out of that update, It somewhat forced me into that, as described above.

I can see yours is also still on v27.x and not v29.x

**Comment by tteck** [comment]
There are no issues with the script as I have shown. The script is using the Alpine Package Keeper (apk) for the installation. The version is currently 27.1.9 for Alpine 3.19 https://pkgs.alpinelinux.org/packages?name=nextcloud&branch=v3.19&repo=&arch=x86_64&maintainer=

**Comment by tteck** [comment]
![Screenshot 2024-05-26 7 52 00 AM](https://github.com/tteck/Proxmox/assets/21342670/5ff8a96a-9c98-41e7-a3cd-45df8ee2f656)

**Comment by tteck** [comment]
A fresh install from this repository, _should_ not create any issues.

**Comment by CrazyWolf13** [comment]
Thanks for clarification, could it be that nextcloud themself are trying tog et more users to update to their AI stuff?

Because to be honest, I've not touched nor changed a single thing, and the above screenshot appeared, as if auto-updates would be on.

**Comment by tteck** [comment]
I think that the issue started when their `latest-stable` branch introduced the Alpine v20-rc. You now have mixed packages, which doesn't work well. https://pkgs.alpinelinux.org/packages?name=nextcloud&branch=v3.20&repo=&arch=x86_64&maintainer=

**Comment by CrazyWolf13** [comment]
> I think that the issue started when their `latest-stable` branch introduced the Alpine v20-rc. You now have mixed packages, which doesn't work well. https://pkgs.alpinelinux.org/packages?name=nextcloud&branch=v3.20&repo=&arch=x86_64&maintainer=

Oh Yeah that seems to make a lot of sense.

Would you think editing the script to use latest (v3.20) repo and then reinstalling would solve the conflicts?

**Comment by tteck** [comment]
There is no Alpine v3.20 template.

**Comment by CrazyWolf13** [comment]
Oh I see, guess then we'd have to wait for that.

Thanks for the quick feedback and for maintainig those scripts.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by CrazyWolf13** [comment]
According to this upstream repos should be fixed!
```
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
```
https://gitlab.alpinelinux.org/alpine/aports/-/issues/16147#note_408035

**Comment by sic699** [comment]
> According to this upstream repos should be fixed!
> 
> ```
> http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
> http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
> ```
> 
> https://gitlab.alpinelinux.org/alpine/aports/-/issues/16147#note_408035

I updated the repositories manually to the latest, I ran then ran an apk update and apk upgrade followed by using the tteck script command in alpine which led me to the same error as you. This was to upgrade to nextcloud 29.0

Now when I try to log onto my cloudserver via the website I am stuck with the  nextcloud maintenance window.

**Comment by CrazyWolf13** [comment]
Hmm strange,  closing the maintenance mode is possible, but you probably just bricked your installation aswell!!

@tteck Possibly you can pin something, so this issue does not appear for any other users?

As much as I love the helper scrips, neither the alpine version nor nextcloudpi is what I want, so I'll switch to a manual installation with debian.

(If wished by tteck I can create a PR afterwards.)

**Comment by sic699** [comment]
if i try to upgrade it via the web interface I get 

Possible CSRF attack. Connection will be closed.

Detailed logs

**Comment by sic699** [comment]
well luckily I have a backup of my configs however I just have 1 security warning after reinstalling nextcloud-alpine 

The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the [security tips ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-security).

if someone can point in the right direction on how to fix that warning it would be greatly appreciated I am running nginx-proxymanager btw with my nextcloud setup.

**Comment by sic699** [comment]
im backup up and running after resintalling alpine-nextcloud no issues, I have not bothered to upgrade to 29.0 ill leave it as it is i just spent 3 hours fixing the new install up.

**Comment by CrazyWolf13** [comment]
@sic699 HSTS can be enabled on your reverse proxy or directly in the nextcloud apache server.
 https://help.nextcloud.com/t/help-me-to-enable-hsts-http-strict-transport-security-on-my-nc22-instance-please/121552/8

**Comment by sic699** [comment]
@CrazyWolf13 Ty everything is up and running luckily I had backups of my config.php and my previous data folders/files from my previous nextcloud install.

**Comment by flyguy729** [comment]
Hello @sic699 . Found a solution to your problem. The reason it cannot upgrade is because your config.php file is still on version 27.x.x.x. You need to nano to /etc/nextcloud/config.php and edit it to the version on Alpine : https://pkgs.alpinelinux.org/packages?name=nextcloud&branch=v3.20&repo=&arch=&maintainer= 
which is currently at 29.0.0-r0. 

Once you change that, you can update it. Took me a while to figure this out but found the solution here. https://github.com/nextcloud/docker/issues/1652

I also had the files_reminders error and your post help me fixed that so i thought of giving back (:
