### ISSUE TITLE
Frigate install

### ISSUE THREAD

**Issue by ArMaTeC** [tteck/Proxmox#3071]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to install frigate i get the error listed below

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Package libtbb2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtbbmalloc2

 |E: Package 'libtbb2' has no installation candidate
E: Unable to locate package libdc1394-22-dev

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
