### ISSUE TITLE
Installation error PhotoPrism

### ISSUE THREAD

**Issue by jabijker** [tteck/Proxmox#3085]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Error during installation of the Application.

 / Installing PhotoPrism (Patience)   
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

[ERROR] in line 37: exit code 0: while executing command tar -xz -C /opt/photoprism --strip-components=1

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/119865733/aaa66586-3bac-4bb9-9ff3-9854a7670bc4)

### Please provide detailed steps to reproduce the issue.

- bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/photoprism.sh)"
- use default settings

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    ____  __  ______  __________  ____  ____  _________ __  ___
   / __ \/ / / / __ \/_  __/ __ \/ __ \/ __ \/  _/ ___//  |/  /
  / /_/ / /_/ / / / / / / / / / / /_/ / /_/ // / \__ \/ /|_/ / 
 / ____/ __  / /_/ / / / / /_/ / ____/ _, _// / ___/ / /  / /  
/_/   /_/ /_/\____/ /_/  \____/_/   /_/ |_/___//____/_/  /_/   

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: photoprism
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a PhotoPrism LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed PhotoPrism
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

PhotoPrism should be reachable by going to the following URL.
         http://192.168.86.250:2342 
```
I suspect your issue is downloading https://dl.photoprism.app/pkg/linux/amd64.tar.gz

**Comment by jabijker** [comment]
Strange issue, when i run the command "wget -q -cO - https://dl.photoprism.app/pkg/linux/amd64.tar.gz | tar -xz -C /opt/photoprism --strip-components=1" everything downloads and unpacks its just fine :-(

root@pve:/# wget -q -cO - https://dl.photoprism.app/pkg/linux/amd64.tar.gz | tar -xz -C /opt/photoprism --strip-components=1
root@pve:/# ls -l /opt/photoprism/
total 18
drwxr-xr-x 9 1000 1000 10 May 28 08:32 assets
drwxr-xr-x 2 1000 1000  3 May 28 08:32 bin
drwxr-xr-x 2 1000 1000  6 May 28 08:31 lib
root@pve:/# 

I will dig into it later on this week.
