### ISSUE TITLE
LXC IPv6 DHCP causing startup delay

### ISSUE THREAD

**Issue by manjaroblack** [tteck/Proxmox#3102]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The LXC container scripts, by default, configures IPv6 using DHCP. If DHCP is not configured for IPv6, this causes about a 5 minute delay before the container is fully loaded. I suggest either changing the default to Static - None, or SLAAC (preferred).

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

easiest fix:
build.func, line 149
```  echo -e "${DGN}Disable IPv6: ${BGN}No${CL}"```
change to
```  echo -e "${DGN}Disable IPv6: ${BGN}Yes${CL}"```

**Comment by tteck** [comment]
IPv6 is disabled on my router. The scripts do not exhibit any delays, nor have I received any reports of such issues. It sounds like there might be a problem with your DHCP server.

**Comment by tteck** [comment]
Have you tried Advanced settings and select Yes to Disable IPv6?

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
