### ISSUE TITLE
Passwords Should be Masked

### ISSUE THREAD

**Issue by timothystewart6** [tteck/Proxmox#3103]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi and thanks for this repo! 

This is more of a suggestion but I feel like the passwords should always be masked when printing them to the screen.

e.g.

- https://github.com/tteck/Proxmox/blob/37f42468ba295b42f4cd636fb31d8eacbd2703ab/misc/build.func#L139
- https://github.com/tteck/Proxmox/blob/37f42468ba295b42f4cd636fb31d8eacbd2703ab/turnkey/turnkey.sh#L240

There are likely other places too.  I am not sure if this was a decision based on feedback from the community, a support issue, or just because that's how the code was written but I feel like this should be the default for all printed passwords on the screen.

Thank you!

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### Please provide detailed steps to reproduce the issue.

Create any LXC and choose a root password.

**Comment by timothystewart6** [comment]
Also, I am happy to open a PR but you might have a more elegant way of doing this other than hard coding `***********` 😅

Could even be a question (mask password? YES/NO), hopefully default is YES.

**Comment by tteck** [comment]
The reason passwords are not masked (that's an easy whiptail change) is because it's also displayed to the user during creation. I've even entered a password correctly (I thought) to be shown I misspelled it during creation. Without this extra check, the container would be useless without proper credentials. Besides, who else is going to view the password?

As for the `turnkey.sh`
https://github.com/tteck/Proxmox/blob/37f42468ba295b42f4cd636fb31d8eacbd2703ab/turnkey/turnkey.sh#L240
This is only displayed once upon completion for convenience (line 240 could be removed) , but can be retrieved from the `*creds` file the script creates in the Proxmox root directory.

**Comment by tteck** [comment]
`--inputbox` can be changed to `--passwordbox` so the password is masked during entering but the password will still be shown on the creation page for that extra check.
https://github.com/tteck/Proxmox/blob/37f42468ba295b42f4cd636fb31d8eacbd2703ab/misc/build.func#L235

**Comment by timothystewart6** [comment]
> Besides, who else is going to view the password?

I don't think it's a matter of who else (although this happened to me in my YouTube video) I think it's just good security hygiene never to display the password unmasked.  If you're worried about the user mistyping the password, you could prompt for verification (enter twice)

**Comment by Mellowlynx** [comment]
Because it's a random-generated password and only used for setup while the scrips runs, I think this is fine.
Also, making it `--passwordbox` would indeed mean you need to confirm it by entering it twice.

Showing it once upon completion, for convenience, is in my eyes, it's better than having users reusing their unsafe/easy passwords and never updating them.

Hard-coding API keys or passwords that do not change, is another story. 😄

But maybe that can be a setting that is set using an env.conf file?
- mask password Yes/No
- generate pass
- min pass length
etc.

**Comment by tteck** [comment]
Hey, thanks for the video! Just realized who this was. 😄 
I understand, and typically enforce this. But in this case, it's usually just the user and not thousands looking over their shoulder. 👀 

This could be used to prompt for verification

```
while true; do
  if PW1=$(whiptail --backtitle "Proxmox VE Helper Scripts" --passwordbox "\nSet Root Password (needed for root ssh access)" 9 58 --title "PASSWORD (leave blank for automatic login)" 3>&1 1>&2 2>&3); then
    if [[ ! -z "$PW1" ]]; then
      if [[ "$PW1" == *" "* ]]; then
        whiptail --msgbox "Password cannot contain spaces. Please try again." 8 58
      elif [ ${#PW1} -lt 5 ]; then
        whiptail --msgbox "Password must be at least 5 characters long. Please try again." 8 58
      else
        if PW2=$(whiptail --backtitle "Proxmox VE Helper Scripts" --passwordbox "\nVerify Root Password" 9 58 --title "PASSWORD VERIFICATION" 3>&1 1>&2 2>&3); then
          if [[ "$PW1" == "$PW2" ]]; then
            PW="-password $PW1"
            echo -e "${DGN}Using Root Password: ${BGN}$PW1${CL}"
            break
          else
            whiptail --msgbox "Passwords do not match. Please try again." 8 58
          fi
        else
          exit-script
        fi
      fi
    else
      PW1="Automatic Login"
      PW=""
      #echo -e "${DGN}Using Root Password: ${BGN}$PW1${CL}"
      break
    fi
  else
    exit-script
  fi
done
```
Then remove the password from being shown during creation. Let me think about this.

**Comment by timothystewart6** [comment]
Ok, I guess we will disagree to disagree 😅. This is honestly the first time I have encountered a system that printed out the password unmasked and I have built and used a lot of systems 😅. Printing out the user typed root password just feels wrong but it seems like I am in the minority here on this repo.  Feel free to close this if that's your intention, but anyone viewing that screen at the time now has your password.  Could be Zoom, could be Teams/Slack/Discord, YouTube, or could be someone in the same room.

**Comment by timothystewart6** [comment]
> Hey, thanks for the video! Just realized who this was. 😄 I understand, and typically enforce this. But in this case, it's usually just the user and not thousands looking over their shoulder. 👀
> 
> This could be used to prompt for verification
> 
> ```
> while true; do
>   if PW1=$(whiptail --backtitle "Proxmox VE Helper Scripts" --passwordbox "\nSet Root Password (needed for root ssh access)" 9 58 --title "PASSWORD (leave blank for automatic login)" 3>&1 1>&2 2>&3); then
>     if [[ ! -z "$PW1" ]]; then
>       if [[ "$PW1" == *" "* ]]; then
>         whiptail --msgbox "Password cannot contain spaces. Please try again." 8 58
>       elif [ ${#PW1} -lt 5 ]; then
>         whiptail --msgbox "Password must be at least 5 characters long. Please try again." 8 58
>       else
>         if PW2=$(whiptail --backtitle "Proxmox VE Helper Scripts" --passwordbox "\nVerify Root Password" 9 58 --title "PASSWORD VERIFICATION" 3>&1 1>&2 2>&3); then
>           if [[ "$PW1" == "$PW2" ]]; then
>             PW="-password $PW1"
>             echo -e "${DGN}Using Root Password: ${BGN}$PW1${CL}"
>             break
>           else
>             whiptail --msgbox "Passwords do not match. Please try again." 8 58
>           fi
>         else
>           exit-script
>         fi
>       fi
>     else
>       PW1="Automatic Login"
>       PW=""
>       #echo -e "${DGN}Using Root Password: ${BGN}$PW1${CL}"
>       break
>     fi
>   else
>     exit-script
>   fi
> done
> ```
> 
> Then remove the password from being shown during creation. Let me think about this.

All good!  No worries.  I didn't see this comment before my last.  This is only my opinion and it's your scripts so feel free to close if that's not what you want 😄

**Comment by tteck** [comment]
See if the change meets your approval.

**Comment by timothystewart6** [comment]
This is great!  Wow, that you very much!
