### ISSUE TITLE
influxdb - user creation fails

### ISSUE THREAD

**Issue by umrath** [tteck/Proxmox#3107]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When installing influxdb v2, with or without Telegraf, the user creation fails and subsequentially, a login is not possible.
The ui reports "Could not set up admin user".

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1. run the script on Proxmox 8.2, choose v2
2. run the onboarding after finishing the script
3. enter username, password, etc. in the respective fields
4. observe the error

**Comment by tteck** [comment]
No error here

![Screenshot 2024-06-01 7 29 32 AM](https://github.com/tteck/Proxmox/assets/21342670/ca47065a-9f87-4eed-8cf7-c7ecdceee5e9)

**Comment by umrath** [comment]
Hmm, any idea  what I could be doing wrong?

**Comment by tteck** [comment]
Not filling out all fields 🤷🏻‍♂️ 

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by umrath** [comment]
Well, I cannot even hit the button when not all fields are filled, it's pretty safe to say that this is not the issue.
