### ISSUE TITLE
ActualBudget installation

### ISSUE THREAD

**Issue by pfml** [tteck/Proxmox#3108]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Trying to install ActualBudget using the script. Got a series of error message

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

'''
    ___        __              __   ____            __           __
   /   | _____/ /___  ______ _/ /  / __ )__  ______/ /___ ____  / /_
  / /| |/ ___/ __/ / / / __ `/ /  / __  / / / / __  / __ `/ _ \/ __/
 / ___ / /__/ /_/ /_/ / /_/ / /  / /_/ / /_/ / /_/ / /_/ /  __/ /_
/_/  |_\___/\__/\__,_/\__,_/_/  /_____/\__,_/\__,_/\__, /\___/\__/
                                                  /____/
Loading...
bash: line 27: variables: command not found
bash: line 28: color: command not found
bash: line 29: catch_errors: command not found
bash: line 68: start: command not found
bash: line 69: build_container: command not found
bash: line 70: description: command not found
bash: line 71: msg_info: command not found
400 not enough arguments
pct set <vmid> [OPTIONS]
400 not enough arguments
pct set <vmid> [OPTIONS]
bash: line 74: msg_ok: command not found
bash: line 75: msg_ok: command not found
Actual Budget should be reachable by going to the following URL.
         http://:5006 
'''

### Please provide detailed steps to reproduce the issue.

copy/paste `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/actualbudget.sh)"`  in the console

**Comment by tteck** [comment]
How to install
To create a new Proxmox VE Actual Budget LXC, run the command below in the **Proxmox VE Shell.**

**Comment by pfml** [comment]
Sorry, I've made an error stating it was runned in the console. I actually runned it in the proxmox ve shell. Made another attempt, same result.

Trying to better undestand this issue, use `bash -v -c "$(wget...` and obtain a perfectly working lxc container of ActualBudget.

Many thanks for the script and the support
