### ISSUE TITLE
Qbittorrent LXC

### ISSUE THREAD

**Issue by kiwinh0** [tteck/Proxmox#3117]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

qbittorrent LXC does not update beyond version 4.5.2 which is very outdated and 4.6.5 is currently available. 
It is available in the Debian 12 repositories but the script does not update

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

run 'update' - not qbittorrent update

**Comment by tteck** [comment]
```
root@server:~# apt search qbittorrent-nox
Sorting... Done
Full Text Search... Done
qbittorrent-nox/stable 4.5.2-3+deb12u1 amd64
  bittorrent client based on libtorrent-rasterbar (without X support)
```

```
root@server:~# apt-cache policy qbittorrent-nox
qbittorrent-nox:
  Installed: (none)
  Candidate: 4.5.2-3+deb12u1
  Version table:
     4.5.2-3+deb12u1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
```

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
