### ISSUE TITLE
Pi.Alert update script get an error message Line 86

### ISSUE THREAD

**Issue by Nilan464** [tteck/Proxmox#3119]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I use this command to update Pi.Alert in Proxmox 8.1.4 :
bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh)"

I get this error message :
environment: line 86: /root/pialert/back/pialert-cli: No such file or directory

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

############################################################################
# You are planning to update Pi.Alert. Please make sure that no scan takes #
# place during the update to avoid possible database errors afterwards!!!  #
#                                                                          #
# This can be done by pausing the Arp scan via the settings page. However, #
# scans that are already running will not be terminated. For more          #
# information, check the Help/FAQ section in Pi.Alert                      #
############################################################################

Press enter to continue 

############################################################
 Pi.Alert Update
############################################################
Mon Jun  3 11:30:50 CEST 2024
Logfile: pialert_update_2024-06-03_11-30.log

- Checking Python...
Python 3 is installed on your system
mac-vendor-lookup is already installed
fritzconnection is already installed
routeros_api is already installed
pyunifi is already installed
- Stopping Pi.Alert...
environment: line 86: /root/pialert/back/pialert-cli: No such file or directory
root@pialert:~#

**Comment by tteck** [comment]
You executed the wrong command.

Execute `update` in the LXC console. or 
```
bash -c "$(wget -qLO - https://github.com/leiweibau/Pi.Alert/raw/main/install/pialert_update.sh)" -s --lxc
```
