### ISSUE TITLE
Jellyfin Media Server Fails To Install

### ISSUE THREAD

**Issue by PIRANY1** [tteck/Proxmox#3129]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When i install Jellyfin the Script returns the Error:
 ✓ Set Up Hardware Acceleration
 -curl: (28) Failed to connect to repo.jellyfin.org port 443 after 136054 ms: Connection timed out
gpg: no valid OpenPGP data found.

[ERROR] in line 41: exit code 0: while executing command gpg --dearmor --yes --output /etc/apt/keyrings/jellyfin.gpg

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 ✓ Set Up Hardware Acceleration
 -curl: (28) Failed to connect to repo.jellyfin.org port 443 after 136054 ms: Connection timed out
gpg: no valid OpenPGP data found.

[ERROR] in line 41: exit code 0: while executing command gpg --dearmor --yes --output /etc/apt/keyrings/jellyfin.gpg

### Please provide detailed steps to reproduce the issue.

Just start the install

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
 
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: jellyfin
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Jellyfin LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Hardware Acceleration
 ✓ Installed Jellyfin
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Jellyfin should be reachable by going to the following URL.
             http://192.168.86.250:8096
```

**Comment by PIRANY1** [comment]
Okay thank you for your fast response

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
