### ISSUE TITLE
Flaresolverr script [ERROR] in line 11

### ISSUE THREAD

**Issue by clartek** [tteck/Proxmox#3132]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Trying to run the new Flaresolverr script, getting the below error after CT is created. Only using advanced settings for verbose mode, default settings result in the same error.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 122
Using Hostname: flaresolverr
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Enable Firewall: 1
Using Vlan: Default
Enable Root SSH Access: no
Add common sudo user with SSH access: no
Enable Shared Mount: no
Configure Postfix Satellite: no
Nvidia GPU Passthrough: no
Enable Verbose Mode: yes
Creating a FlareSolverr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs02 for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 122 was successfully created.
 ✓ Started LXC Container
Customizing LXC creation
 | Setting up Container   
[ERROR] in line 11: exit code 0: while executing command pct exec $CTID -- /bin/bash -c "apt install -qqy curl &>/dev/null"

/dev/fd/63: line 76: pop_var_context: head of shell_variables not a function context
```

### Please provide detailed steps to reproduce the issue.

Run the script on the host

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/flaresolverr.sh)"

**Comment by tteck** [comment]
Fixed https://github.com/tteck/Proxmox/commit/d2805145050d28f9f182eac14eda3dd490a644b5

**Comment by clartek** [comment]
Thanks, working great now.
