### ISSUE TITLE
jackett updater doesn't update jackett

### ISSUE THREAD

**Issue by navels** [tteck/Proxmox#3135]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

jackett update script does this:
```
apt-get update &>/dev/null
apt-get -y upgrade &>/dev/null
```
where instead it needs to do something like (adapted from the install steps):
```
RELEASE=$(wget -q https://github.com/Jackett/Jackett/releases/latest -O - | grep "title>Release" | cut -d " " -f 4)
wget -q https://github.com/Jackett/Jackett/releases/download/$RELEASE/Jackett.Binaries.LinuxAMDx64.tar.gz
systemctl stop jackett
rm -rf /opt/Jackett
tar -xzf Jackett.Binaries.LinuxAMDx64.tar.gz -C /opt
rm -rf Jackett.Binaries.LinuxAMDx64.tar.gz
systemctl start jackett
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Where does it mention "To update Jackett"?

![Screenshot 2024-06-05 5 01 25 AM](https://github.com/tteck/Proxmox/assets/21342670/04207c0b-1128-4b28-9d14-0bf755ac9a3a)

We accept pull requests.

🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by navels** [comment]
I guess that's on me for assuming that `update` and "Updating Jackett LXC" don't update the app and that's by design . . . next time I'll check the docs ¯\\\_(ツ)_/¯
