### ISSUE TITLE
hompage script does not delete old update files

### ISSUE THREAD

**Issue by pafade89** [tteck/Proxmox#3138]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The homepage script does not delete the old downloaded update files for your "update command"

![image](https://github.com/tteck/Proxmox/assets/113902279/fac02240-f133-41af-a516-948d85dbb926)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by pafade89** [comment]
Another thing I noticed is that the used storage of the LXC has become very large. What could be the cause of this?

![image](https://github.com/tteck/Proxmox/assets/113902279/f62bd8d6-8a1e-454a-b3fd-58764d1edab0)

**Comment by tteck** [comment]
Remove all of those `.tar.gz` files

**Comment by pafade89** [comment]
I've already done that, but it remains nearly as large after deleting. The directory /opt/homepage is only 693 MB. So where does the rest come from?

![image](https://github.com/tteck/Proxmox/assets/113902279/e957cf21-f123-4027-a25a-94d5de569d39)

I will set up the LXC again with default settings and see how much storage it uses then.

**Comment by pafade89** [comment]
Default size after installation looks better:

![image](https://github.com/tteck/Proxmox/assets/113902279/70f9c61f-707a-449c-8004-b7cb183e058d)

Do you have any ideas what could be causing it to gradually increase in size?

**Comment by tteck** [comment]
🤷🏻‍♂️  If the drive is SSD, have you tried [fstrim](https://helper-scripts.com/scripts?id=Proxmox+VE+LXC+Filesystem+Trim) on that LXC

**Comment by pafade89** [comment]
Before trim:

![image](https://github.com/tteck/Proxmox/assets/113902279/4bed2c1d-0803-4625-9ed6-d6da76849f0d)


After trim:

![image](https://github.com/tteck/Proxmox/assets/113902279/41544dc1-6928-47b3-b542-1e3986ec37f0)
