### ISSUE TITLE
Scripts page is empty

### ISSUE THREAD

**Issue by kinhsman** [tteck/Proxmox#3139]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When accessing https://helper-scripts.com/scripts page, I'm presented with an empty page and cannot search for anything as there is no search box
![image](https://github.com/tteck/Proxmox/assets/145226962/89d4f871-d67d-48bd-8208-4bf2e9e4531c)
****

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
![Screenshot 2024-06-05 3 54 08 PM](https://github.com/tteck/Proxmox/assets/21342670/0112a445-5dcd-467e-9f35-321e4296949f)

Seems the server hosting the back-end is having issues.

**Comment by tteck** [comment]
Switched to a self-hosted server.
