### ISSUE TITLE
Proxmox VE LXC Cleaner clean everything in stead of only selected

### ISSUE THREAD

**Issue by ferreto1978** [tteck/Proxmox#3161]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Proxmox VE LXC Cleaner clean everything in stead of only selected.
It did list all the LXC containers correctly, but when I only selected one of the containers to clean, it went through all of them.
All containers still work (as far as I could validate), so no severe issues here.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by Mellowlynx** [comment]
The instructions state to select the LXC that should **not** be cleaned.
![afbeelding](https://github.com/tteck/Proxmox/assets/2348339/cee9ea67-671d-45f7-84ba-c3db17a62a7b)

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
