### ISSUE TITLE
Failure installing PI-Hole

### ISSUE THREAD

**Issue by jflorido94** [tteck/Proxmox#3172]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have 2 fails when I run the script. 

1º DNS lookup Failure
2º [ERROR] in line 17: exit code 0: while executing command $STD apt-get install -y curl

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/tteck/Proxmox/assets/58602366/5273b009-26da-4782-a2e7-44859516cf7a)

Its the fails that I get

### Please provide detailed steps to reproduce the issue.

![image](https://github.com/tteck/Proxmox/assets/58602366/72cea284-ed84-47f9-99f7-e3cac45e0699)

I used this configuration in a hp mini prodesk 400 g4 with 16Gb RAM

**Comment by tteck** [comment]
🌐 It seems that you're facing a network problem, _probably_ linked to DNS.

🧐 As this issue is unrelated to the script, it is considered closed.
