### ISSUE TITLE
Homer - update script wipes all yaml files except `config.yml`

### ISSUE THREAD

**Issue by liveware-problems** [tteck/Proxmox#3175]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

When running the update script on a Homer LXC install, only the `config.yml` and /tools folder are backed up and restored.
With Homer, you can create additional pages as further .yml files, detailed in the Homer file `additional-page.yml.dist`.
However these additional yaml files will be deleted when the update script runs.
The update should script should therefore backup and restore *any* yaml file in the /assets directory.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Before screenshot - showing #devices ref in config.yml and devices.yml file in explorer sidebar:
![image](https://github.com/tteck/Proxmox/assets/32192569/daeb8033-b7c6-4ed6-b3b6-b090cbf2136f)

Post update - devices.yml has been deleted by update script:
![image](https://github.com/tteck/Proxmox/assets/32192569/52f2f1de-1ab8-4109-bec3-eb39d6f66622)

### Please provide detailed steps to reproduce the issue.

Add additional page.yml file
Update LXC using script
Additional page,yml file will be deleted

**Comment by tteck** [comment]
It now backs up the `assets` directory

**Comment by liveware-problems** [comment]
Many thanks for the super-swift bugfix @tteck - verified as working fine on my LXC!
