### ISSUE TITLE
Don't install develop branch for Jellyseerr as default

### ISSUE THREAD

**Issue by pafade89** [tteck/Proxmox#3190]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Is it possible to add a selection option to the Jellyseerr script to choose which branch to install? Currently, it always installs the develop branch, but it might make more sense to default to the stable one.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by pafade89** [comment]
Sry i will create a discussion.
