### ISSUE TITLE
PVE Post Install script causes proxmox to no longer boot with zfs pools

### ISSUE THREAD

**Issue by Adam-Gibbs** [tteck/Proxmox#3192]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After running the `post-pve-install.sh` script o a brand new install of proxmox 8.1, if there is a zfs pool attached, it will cause proxmox to no longer boot successfully. It will just hang indefinitely with the message shown below. If you run the script and attach a zpool after it is fine. Is there any way to revert the changes to fix this and make it bootable again, also any idea on why this would be?

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

On boot the only text on screen is:
```
Booting `Proxmox VE GNU/Linux'

Loading Linux 6.8.4-3-pve ...
Loading initial ramdisk ...
_
```

### Please provide detailed steps to reproduce the issue.

Install proxmox 8.1 using ISO, follow all default options etx4 on single disk. Then import a zfs pool and then run `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-pve-install.sh)"` accept all options, reboot, and should see top msg. Then re-install using exactly the same default, just run the post-install script without importing the zpool, allow reboot, import the same pool and it will function just fine after a reboot.

**Comment by tteck** [comment]
I don't think it's the script's fault. You installed an old version (8.1), and the script updated it to the latest version (8.2.2), which includes a new kernel, etc. I'm not sure what you mean by "importing" a zpool, but the script functions as expected.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by Adam-Gibbs** [comment]
Sorry I got my versions mixed up, it would have been 8.2, I just downloaded the ISO from the site to test this today.
By importing I just meant using `zpool import <poolName>` I was testing using an existing pool.
It could well be just updating that broke it. I had a machine running happily on 6.8 kernel prior to the script and after, it only runs on 6.5. I'll try the same test just running updates instead of the script to see if that's the issue.

**Comment by Adam-Gibbs** [comment]
I tested the following steps:

1. Fresh proxmox install on system, using the 8.2 iso
2.  `zpool import mypool`
3.  commented out the enterprise repo in `/etc/apt/sources.list.d/pve-enterprise.list` and `/etc/apt/sources.list.d/ceph.list`
4. `apt update`
5. `apt -y dist-upgrade`
6. rebooted the system

It worked fine after that. Does the script update something that I am missing, or is there another odd interaction that breaks things?

**Comment by tteck** [comment]
The source is viewable at https://github.com/tteck/Proxmox/blob/main/misc/post-pve-install.sh
Nothing extra going on.
