### ISSUE TITLE
UniFi Network Server LXC scripts end with mongodb-server-7.0.gpg error

### ISSUE THREAD

**Issue by evertmulder1982** [tteck/Proxmox#3194]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the UniFi Network Server LXC script it exits after a while with the following error, ran the script multiple times on two different Proxmox hosts. Both hosts support AVX.

I haven't run into this problem with other machines I have deployed the last couple of days.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
✓ Installed Eclipse Temurin JRE
 -gpg: no valid OpenPGP data found.

[ERROR] in line 32: exit code 0: while executing command gpg --dearmor > /usr/share/keyrings/mongodb-server-7.0.gpg
```

### Please provide detailed steps to reproduce the issue.

Run the install script: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/unifi.sh)"

Both advanced mode and default have the same result. When running in verbose no extra information is given except information above,

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
   __  __      _ _____ 
  / / / /__   (_) __(_)
 / / / / __ \/ / /_/ / 
/ /_/ / / / / / __/ /  
\____/_/ /_/_/_/ /_/   
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: unifi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Unifi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Eclipse Temurin JRE
 ✓ Installed MongoDB
 ✓ Installed UniFi Network Server
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Unifi should be reachable by going to the following URL.
         https://192.168.86.250:8443 
```

**Comment by evertmulder1982** [comment]
I am sorry to say the fault was at my side, adguard blocked traffic to the the PGP keys for MongoDB. I will make a call at the adlist provider.
