### ISSUE TITLE
Vaultwarden STORAGE_MENU: unbound variable

### ISSUE THREAD

**Issue by jaydhary14** [tteck/Proxmox#32]
root@promox:~# bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/vault_container.sh)"
This will create a New Vaultwarden LXC Container. Proceed(y/n)?y
bash: line 91: STORAGE_MENU: unbound variable
root@promox:~#

**Comment by tteck** [comment]
Problem? or no?

**Comment by jaydhary14** [comment]
fixed it :) have to  enable container in Pool View > Datacenter > Storage menu.

Just a suggestion add that as a note in your instructions.
