### ISSUE TITLE
Sonarr LXC script not listing all available disks

### ISSUE THREAD

**Issue by 3th3r** [tteck/Proxmox#3206]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Sonarr LXC script, do not list all availlable disk. 
It seems it will only list the first two disks. The interface is also a litlle buggy, 
The disk page will also not filter disks content, and will list disk without Container options. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot_1](https://github.com/tteck/Proxmox/assets/9539206/56b3c0c9-2124-40ca-8973-1cb0193bf4b3)
![Screenshot_2](https://github.com/tteck/Proxmox/assets/9539206/9969d5c1-6527-4777-9d77-f5428efc53fc)

### Please provide detailed steps to reproduce the issue.

Hard to explain on how to reproduce. 

On my setup, 
Create more than 3 disk, including a CIFS share (https://www.thushanfernando.com/notes/proxmox-cifs-setup/) used for mounting in LXCs. 
Start the sonarr script (bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/sonarr.sh)")
Chose default
You will get to the disks page.

**Comment by tteck** [comment]
It will list every storage location that is assigned "Container" in the Datacenter that has a valid target path.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by 3th3r** [comment]
I can create manually an LXC on the disk not listed, so it isn't that. 
This is related to a script, so why rushing to close these issues ?

**Comment by tteck** [comment]
On my system, any storage with the content defined as "Container" is showing.

![Screenshot 2024-06-18 3 22 22 AM](https://github.com/tteck/Proxmox/assets/21342670/40dc87b6-6ee4-4c76-be5b-c95a471de651)

**Comment by tteck** [comment]
In your picture, it says Container template.

**Comment by 3th3r** [comment]
What do you mean "In your picture, it says Container template."
The install script only list two disks, my main CIFS share and local, but not the two disks with 'container' enable.  (not my secondary CIFS share, NVME Drive or local-lvm)

It was working fine, before I've added manually a CIFS share. 

What does the install script is listing, what "content" it is looking for ? Content=Container ?
If not, there is a problem with Proxmox, because I can create an LXC, on my disks with their content set to 'Container'.

**Comment by tteck** [comment]
> The install script only list two disks

Yes, for any storage with the content defined as "**Container Template**".

> What does the install script is listing, what "content" it is looking for ? Content=Container ?

First it only asks IF you have more than one storage location for Container template and Container defined in the Datacenter. 🤦‍♂️

**Comment by 3th3r** [comment]
Ok, my bad, I thought that disk should be set to 'Container' no 'Container Template'.

I will try this fix later. 

Is this specified in the documentation ?
