### ISSUE TITLE
Can't Install Plex - ERROR] in line 40

### ISSUE THREAD

**Issue by geoffrays** [tteck/Proxmox#3207]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

While installing plex I get an error.

While activating verbose mode, I guess it comes from the plex repo not added to proxmox. 

I added it, but got the same issue.

I'm stuck now. Your help is really appreciated.

Thanks

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
Processing triggers for man-db (2.10.2-1) ...
 ✓ Set Up Hardware Acceleration
 ✓ Set Up Plex Media Server Repository
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Get:4 https://downloads.plex.tv/repo/deb public InRelease [6,685 B]
Get:5 https://downloads.plex.tv/repo/deb public/main amd64 Packages [428 B]
Fetched 7,113 B in 0s (21.4 kB/s) 
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 -The following NEW packages will be installed:
  plexmediaserver
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 82.0 MB of archives.
After this operation, 214 MB of additional disk space will be used.
Err:1 https://downloads.plex.tv/repo/deb public/main amd64 plexmediaserver amd64 1.40.2.8395-c67dce28e
  404  Not Found [IP: 104.18.1.127 443]
E: Failed to fetch https://downloads.plex.tv/repo/deb/pool/plexmediaserver_1.40.2.8395-c67dce28e_amd64.deb  404  Not Found [IP: 104.18.1.127 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

[ERROR] in line 40: exit code 0: while executing command $STD apt-get -o Dpkg::Options::="--force-confold" install -y plexmediaserver

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```    ____  __             __  ___         ___          _____                          
   / __ \/ /__  _  __   /  |/  /__  ____/ (_)___ _   / ___/___  ______   _____  _____
  / /_/ / / _ \| |/_/  / /|_/ / _ \/ __  / / __ `/   \__ \/ _ \/ ___/ | / / _ \/ ___/
 / ____/ /  __/>  <   / /  / /  __/ /_/ / / /_/ /   ___/ /  __/ /   | |/ /  __/ /    
/_/   /_/\___/_/|_|  /_/  /_/\___/\__,_/_/\__,_/   /____/\___/_/    |___/\___/_/     
                                                                                      
Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 113
Using Hostname: plex
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Plex LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Hardware Acceleration
 ✓ Set Up Plex Media Server Repository
 ✓ Installed Plex Media Server
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Plex should be reachable by going to the following URL.
             http://192.168.86.250:32400/web
```

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by geoffrays** [comment]
Thanks for your help. 

Works as a charm while installing manually, doesn't work with the script.
