### ISSUE TITLE
Can't install Linkwarden

### ISSUE THREAD

**Issue by Krik658** [tteck/Proxmox#3209]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Linkwarden won't complete installation.

- [fail] Advanced Settings with Debian 12 won't install. (see log below)
- [fail] Advanced Settings with Ubuntu 24.04 won't install (different error).  
- [pass] Default Settings (Ubuntu 22.04.) will install without errors.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: ********
Container ID: 247
Using Hostname: linkwarden
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 10.0.0.247/8
Using Gateway IP Address: 10.0.0.254
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: <removed>
Using DNS Server IP Address: 10.0.0.252
Using MAC Address: BC:24:11:A0:C0:F7
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: yes
Creating a Linkwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 247 was successfully created.
 ✓ Started LXC Container
net.ipv6.conf.all.disable_ipv6 = 1
 ✓ Set up Container OS
 ✓ Network Connected: 10.0.0.247 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.121.4
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]

(whole lot of apt messages - cropped)

added 1 package in 2s
 ✓ Installed Node.js/Yarn
 /Cloning into '/opt/linkwarden'...
 -remote: Enumerating objects: 12780, done.
remote: Counting objects: 100% (2337/2337), done.
remote: Compressing objects: 100% (834/834), done.
remote: Total 12780 (delta 1446), reused 2192 (delta 1387), pack-reused 10443
Receiving objects: 100% (12780/12780), 28.29 MiB | 11.13 MiB/s, done.
Resolving deltas: 100% (7914/7914), done.
 ✓ Cloned Linkwarden Repository
 /CREATE ROLE PostgreSQL DB   
 -CREATE DATABASE
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> n
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @atlaskit/tree@8.8.7" has incorrect peer dependency "react@^16.8.0".
warning "@atlaskit/tree > react-beautiful-dnd-next@11.0.5" has incorrect peer dependency "react@^16.8.5".
[4/4] Building fresh packages...
Done in 163.94s.
 -BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org bookworm-security InRelease             
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease            
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease            
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libjpeg-turbo8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

Package xfonts-cyrillic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-unifont' has no installation candidate
E: Package 'xfonts-cyrillic' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libx264-155
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
E: Package 'libjpeg-turbo8' has no installation candidate
E: Unable to locate package libvpx6
E: Unable to locate package libwebp6
Failed to install browser dependencies
Error: Installation process exited with code: 100

[ERROR] in line 76: exit code 0: while executing command $STD npx playwright install-dep

### Please provide detailed steps to reproduce the issue.

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/linkwarden.sh)"`

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
