### ISSUE TITLE
Unifi installation script not finishing

### ISSUE THREAD

**Issue by Zetto12** [tteck/Proxmox#3218]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I tried to install the Unifi Network server using the installation script.

The script seems to hang when installing the actual application. The machine I'm trying to install it on has an N5105 process which does not have AVX support as far as I'm aware. Could that be the reason.

Also if I select the default installation and want to log in to the container afterwards I've been asked for a user and password, which is not specified on the website.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

I'm on Proxmox 8.2.2, machine has an N5105 processor. After copying the script into the shell and executing I select Default installation. Installation starts but when it reaches the actual Unifi application it does not progress any further. I can't access the webUi under port 8443 and if I try to access the shell of the lxc container I've been asked for a 'Unifi Login'.

**Comment by tteck** [comment]
Yes, AVX is required.

![Screenshot 2024-06-16 5 08 31 PM](https://github.com/tteck/Proxmox/assets/21342670/a55b1051-c23b-4579-97bc-adb7475c60ca)

https://github.com/tteck/Proxmox/issues/2738

🧐 As this issue is unrelated to the script, it is considered closed.
