### ISSUE TITLE
Nginx Proxy Manager fails install

### ISSUE THREAD

**Issue by jarjarfinks** [tteck/Proxmox#3226]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I get the following error when I run the Nginx Proxy Manager script to create a new LXC
`✓ Installed Openresty
 |=> Downloading nvm from git to '/root/.nvm'
 |Cloning into '/root/.nvm'...
 -remote: Enumerating objects: 369, done.
remote: Counting objects: 100% (369/369), done.
remote: Compressing objects: 100% (315/315), done.
remote: Total 369 (delta 43), reused 173 (delta 27), pack-reused 0
Receiving objects: 100% (369/369), 368.09 KiB | 1.62 MiB/s, done.
Resolving deltas: 100% (43/43), done.
 -* (HEAD detached at FETCH_HEAD)
  master
=> Compressing and cleaning up git repository

=> Appending nvm source string to /root/.bashrc
=> Appending bash_completion source string to /root/.bashrc
 \=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
/root/.bashrc: line 6: PS1: unbound variable`

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### Please provide detailed steps to reproduce the issue.

Ubuntu 22.04
Disable IPv6
Enable Root console

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by bilogic** [comment]
Hmm, I'm facing the same. If it can only work with debian, why not remove the ubuntu question then?
