### ISSUE TITLE
Jellyseer script not working

### ISSUE THREAD

**Issue by josejrr1989** [tteck/Proxmox#3254]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Script is un-able to finish install do in ability to install yarn. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 ✓ Installed Yarn
yarn install v1.22.22
info No lockfile found.
$ npx only-allow pnpm
npm error Override without name: sqlite3/node-gyp

npm error A complete log of this run can be found in: /root/.npm/_logs/2024-06-23T23_52_12_687Z-debug-0.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 /
[ERROR] in line 43: exit code 0: while executing command $STD yarn install

### Please provide detailed steps to reproduce the issue.

copy bash script (bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/jellyseerr.sh)") 
paste script into proxmox shell
select advance options, keep all default options except verbose option, set it to yes
wait until error shows

**Comment by tteck** [comment]
Fixed

```
       __     ____
      / /__  / / /_  __________  ___  __________
 __  / / _ \/ / / / / / ___/ _ \/ _ \/ ___/ ___/
/ /_/ /  __/ / / /_/ (__  )  __/  __/ /  / /
\____/\___/_/_/\__, /____/\___/\___/_/  /_/
              /____/
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: jellyseerr
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Jellyseerr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed pnpm
 ✓ Installed Jellyseerr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Set Container to Normal Resources
 ✓ Completed Successfully!

Jellyseerr should be reachable by going to the following URL.
         http://192.168.86.250:5055 
```

**Comment by Deekerman** [comment]
@tteck While it does go through everything correctly. The server does not seem to be running. I just finished reinstalling it due to my previous install not working anymore and it is not actually active. I get "This site can't be reached"
