### ISSUE TITLE
5@324 Unknown failure occured

### ISSUE THREAD

**Issue by mflage** [tteck/Proxmox#326]
Attempting to create a new VM with H-A using the provided script (```bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm-v3.sh)"```), but getting:

```
        _    _          ____   _____
       | |  | |   /\   / __ \ / ____|
       | |__| |  /  \ | |  | | (___
       |  __  | / /\ \| |  | |\___ \
       | |  | |/ ____ \ |__| |____) |
       |_|  |_/_/ v3 \_\____/|_____/

Using Default Settings
Using Version 8.3
Using VM ID 105
Using VM Name haos8.3
Using 2vCPU
Using 4096MiB RAM
Using Bridge vmbr0
Using MAC Address 00:60:2F:1F:43:61
Using VLAN Tag NONE
Start VM when completed yes
 ✓ Using local-lvm for Storage Location.
 ✓ Virtual Machine ID is 105.
 ✓ https://github.com/home-assistant/operating-system/releases/download/8.3/haos_ova-8.3.qcow2.xz
 ✓ Downloaded haos_ova-8.3.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...‼ ERROR 5@324 Unknown failure occured.
 ```

```pvesm status -content images | awk 'NR>1'``` returns:

```
local-lvm     lvmthin     active      1311555584       196339870      1115215713   14.97%
```

**Comment by tteck** [comment]
new Proxmox install?

**Comment by mflage** [comment]
> new Proxmox install?

200+ days, so no.

**Comment by tteck** [comment]
Everything looks ok with storage. Have you ever ran the Proxmox VE 7 Post Install script? If not, I'd suggest run it then try running the Home Assistant OS VM install script again.

**Comment by mflage** [comment]
I have ran the script. Do I need to reboot afterwards?

**Comment by tteck** [comment]
You don't have to, but I would, because it probably installed a new kernel

**Comment by tteck** [comment]
Care to share your findings?

**Comment by mflage** [comment]
> Care to share your findings?

Have to schedule a bit of downtime for the VMs running on the host first. I'll let you know once I have tried.

**Comment by ajayrgb** [comment]
> I have ran the script. Do I need to reboot afterwards?

Did you type "y" for the prompts in the post install script?  I found that simply pressing enter on a <Y/n> prompt actually selects No.

#334

**Comment by tteck** [comment]
@ajayrgb unless you type `y`, `Y`, `yes` or`Yes` the answer should be always be `no` by default

**Comment by ajayrgb** [comment]
> @ajayrgb unless you type `y`, `Y`, `yes` or`Yes` the answer should be always be `no` by default

That sounds reasonable, but then I would suggest you change the prompt from "<Y/n>" to "<y/N>" to better indicate the default value.

**Comment by mflage** [comment]
> > I have ran the script. Do I need to reboot afterwards?
> 
> Did you type "y" for the prompts in the post install script? I found that simply pressing enter on a <Y/n> prompt actually selects No.
> 
> #334

I reran the script now and made sure I typed 'yes'|'y' to every question. Still no dice. Still working to schedule that reboot of the host.

**Comment by tteck** [comment]
go ahead and try the HAOS VM install script

edit: "Still no dice" must mean that you did try?

**Comment by bgulla** [comment]
I am having this error as well on haOS-8.3. After editing the 'latest' HAos version to 8.2 and installed, it is working appropriately. There must be a bug in the 8.3 OVA build that is causing it not to start. @mflage

**Comment by tteck** [comment]
I try to keep this script behind 1 version (8.2) for this purpose 
```yaml
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos_vm.sh)"
```

**Comment by tteck** [comment]
> There must be a bug in the 8.3 OVA build that is causing it not to start. 

@bgulla I agree. in 8.3 the "Preparing Home Assistant" screen doesn't show. It does in 8.2

**Comment by tteck** [comment]
@mflage any update before closing?

**Comment by tteck** [comment]
???

**Comment by mflage** [comment]
> @mflage any update before closing?

After reboot:

```
Using Default Settings
Using Version 8.2
Using VM ID 105
Using VM Name haos8.2
Using 2vCPU
Using 4096MiB RAM
Using Bridge vmbr0
Using MAC Address 00:60:2F:19:F9:27
Using VLAN Tag NONE
Start VM when completed yes
 ✓ Using local-lvm for Storage Location.
 ✓ Virtual Machine ID is 105.
 ✓ https://github.com/home-assistant/operating-system/releases/download/8.2/haos_ova-8.2.qcow2.xz
 ✓ Downloaded haos_ova-8.2.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...‼ ERROR 5@333 Unknown failure occured.
```

So it changed from the unknown error 5@324 to 5@333 .... :)

**Comment by tteck** [comment]
IMHO, it looks like you have something strange going on with your storage.

Line 333 `pvesm alloc $STORAGE $VMID $DISK0 4M`
pvesm is Proxmox VE Storage Manager

Line 334 `qm importdisk $VMID ${FILE%.*} $STORAGE ${DISK_IMPORT:-}`
qm is Qemu/KVM Virtual Machine Manager

You may have to go with the manual install method.

**Comment by mflage** [comment]
What do you mean? I have? How can you tell from that output?

**Comment by tteck** [comment]
Right now (‼ ERROR 5@333) the Proxmox VE Storage Manager can't allocate the disk image.

**Comment by mflage** [comment]
> Right now (bangbang ERROR 5@333) the Proxmox VE Storage Manager can't allocate the disk image.

But I haven't done anything out of the ordinary. I would really like to "sanitize" my Proxmox setup, what can I do to confirm this?

**Comment by tteck** [comment]
If it were me, I'd backup all of my CT/VM's to a external USB drive and reinstall PVE 7.2 then restore.
I've had to do this several times because I goofed something up.

If everything is running ok, and you just want to add HAOS, try installing it [manually](https://blog.habitats.tech/howto-install-home-assistant-ha-os-in-proxmox-ve-pve-71)

**Comment by tteck** [comment]
If you need to add a USB drive, here's a [guide](https://nubcakes.net/index.php/2019/03/05/how-to-add-storage-to-proxmox/)
