### ISSUE TITLE
OpenWrt VM script can't select storage pool

### ISSUE THREAD

**Issue by yawaworhtt** [tteck/Proxmox#3262]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

On the Storage pool selection page, I am unable to select local or local-lvm, I am just brought back to the same page when entered. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![Screenshot 2024-06-25 at 20-08-48 a - Proxmox Virtual Environment](https://github.com/tteck/Proxmox/assets/171207550/0c05baf5-6d5f-4221-9e5d-373bce997756)

**Comment by tteck** [comment]
Use spacebar

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
