### ISSUE TITLE
Frigate LXC dependency update (bookworm)

### ISSUE THREAD

**Issue by stinobook** [tteck/Proxmox#3264]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

install fails line 17. dependency not found.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

line 17:
    Replace libtbb2 with libtbbmalloc2
    Replace libdc1394-22-dev with libdc1394-dev

should fix it i think :)

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by stinobook** [comment]
Hello,

AFAIK it is a default linux distro ? its just proxmox 8.2.4. Still new to proxmox so i might have selected the wrong thing in the issue.

![image](https://github.com/tteck/Proxmox/assets/51697064/83a06e28-9e42-4bc4-8882-7ba09279d1dd)

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/4a135f4ecd48e12babe00de177d236d3d2fb88ee/ct/frigate.sh#L22-L27

**Comment by stinobook** [comment]
Oops! sorry :) still learning proxmox. loving all your scripts btw!
Just ran default settings and it worked ! 
i just thought it had to be debian 12 due to:
![image](https://github.com/tteck/Proxmox/assets/51697064/44719327-ba14-4365-90e4-6e9d44646ac5)
