### ISSUE TITLE
PIHOLE LXC not installing via script

### ISSUE THREAD

**Issue by killahkazx** [tteck/Proxmox#3271]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When using the pihole LXC install script the install is failing. The container is created but the install of the pihole application into the created container is not completed.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 |Selecting previously unselected package dnsutils.
(Reading database ... 20448 files and directories currently installed.)
Preparing to unpack .../dnsutils_1%3a9.18.24-1_all.deb ...
Unpacking dnsutils (1:9.18.24-1) ...
 /Setting up dnsutils (1:9.18.24-1) ...
 -----------------------------------------------------------------------
 /  [✗] Retrieval of supported OS list failed. dig failed with return code 9. 
      Unable to determine if the detected OS (Debian 12) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/

[ERROR] in line 42: exit code 0: while executing command $STD bash <(curl -fsSL https://install.pi-hole.net) --unattended |Selecting previously unselected package dnsutils.
(Reading database ... 20448 files and directories currently installed.)
Preparing to unpack .../dnsutils_1%3a9.18.24-1_all.deb ...
Unpacking dnsutils (1:9.18.24-1) ...
 /Setting up dnsutils (1:9.18.24-1) ...
 -----------------------------------------------------------------------
 /  [✗] Retrieval of supported OS list failed. dig failed with return code 9. 
      Unable to determine if the detected OS (Debian 12) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/

[ERROR] in line 42: exit code 0: while executing command $STD bash <(curl -fsSL https://install.pi-hole.net) --unattended

**Comment by MickLesk** [comment]
I cannot reproduce the fault. Do you have any firewall or something ? 
Debian 12 is fully supported, and has been for a very long time.

Can you set verbose-mode to yes? 

<img width="441" alt="image" src="https://github.com/tteck/Proxmox/assets/47820557/6dc04fbf-e37e-4e57-a82d-3adac5821374">

**Comment by tteck** [comment]
What version of Proxmox are you using?

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by killahkazx** [comment]
8.2.4 just installed prod mox, no firewall installed verbose result is what I posted.

Sent from my mobile, please excuse my brevity and any grammatical errors.

On Jun 27, 2024, at 7:02 AM, tteckster ***@***.***> wrote:

﻿

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by ArnaudFeld** [comment]
Hi,

When using the Script I get following Error when using default settings:
```
Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 103
Using Hostname: pihole
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Pihole LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 103 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.10.10.162 fd00:dead:beef:666:be24:11ff:fe98:5e6d 2003:cf:f0e:f100:be24:11ff:fe98:5e6d 
 ✓ IPv4 Internet Connected
 ✓ IPv6 Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 \ Installing Pi-hole   
[ERROR] in line 23: exit code 0: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.`
```
and when using Advanced Settings:
```
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 0
Using Root Password: ********
Container ID: 105
Using Hostname: pihole
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: yes
Creating a Pihole LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 105 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.10.10.164 fd00:dead:beef:666:be24:11ff:fee3:36e 2003:cf:f0e:f100:be24:11ff:fee3:36e 
 ✓ IPv4 Internet Connected
 ✓ IPv6 Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 .....
 [i] SELinux not detected
  [✓] Update local cache of available packages

  [✗] Checking apt-get for upgraded packages
      Kernel update detected. If the install fails, please reboot and try again
  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [i] Checking for dnsutils (will be installed)
  [i] Waiting for package manager to finish (up to 30 seconds)
  [i] Processing apt-get install(s) for: dnsutils, please wait...
----------------------------------------------------------------------
 /Selecting previously unselected package dnsutils.
(Reading database ... 20447 files and directories currently installed.)
Preparing to unpack .../dnsutils_1%3a9.18.28-1~deb12u2_all.deb ...
Unpacking dnsutils (1:9.18.28-1~deb12u2) ...
Setting up dnsutils (1:9.18.28-1~deb12u2) ...
 \----------------------------------------------------------------------
  [✗] Retrieval of supported OS list failed. dig failed with return code 9. 
      Unable to determine if the detected OS (Debian 12) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues

      https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash

           If you are seeing this message after having run pihole -up:
             sudo PIHOLE_SKIP_OS_CHECK=true pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/


[ERROR] in line 42: exit code 0: while executing command $STD bash <(curl -fsSL https://install.pi-hole.net) --unattended`
```

Any Hints what Wrong?

Proxmox 8.2.7 is up2date

thanks a lot

**Comment by tteck** [comment]
I have no idea what your issue is, it states internet connectivity issues. Maybe try without IPv6 active.

I have no issues (IPv6 disabled in router):

```
    ____  ____   __  ______  __    ______
   / __ \/  _/  / / / / __ \/ /   / ____/
  / /_/ // /___/ /_/ / / / / /   / __/   
 / ____// /___/ __  / /_/ / /___/ /___   
/_/   /___/  /_/ /_/\____/_____/_____/   
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: pihole
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Pihole LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Pi-hole
Would you like to add Unbound? <y/N> y
 ✓ Installed Unbound
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Pihole should be reachable by going to the following URL.
         http://192.168.86.250/admin 
```
Are you using SSH?

**Comment by ArnaudFeld** [comment]
Same Problem with IPv6 disabled.

Installation is starting via Shell over the Web-UI from Proxmox. Or what you mean with SSH?

**Comment by tteck** [comment]
IPv6 is disabled in your router? I have no idea then. It definitely is something on your end. 🤷🏻‍♂️

**Comment by ArnaudFeld** [comment]
no IPv6 is enabled in my Router. In Advanced Settings from your script I said IPv6 => no....

When deploying my self a Container the installation is working... that is what I not understand

**Comment by tteck** [comment]
It's creating the container just fine
```
Using Default Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 103
Using Hostname: pihole
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Pihole LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 103 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.10.10.162 fd00:dead:beef:666:be24:11ff:fe98:5e6d 2003:cf:f0e:f100:be24:11ff:fe98:5e6d 
 ✓ IPv4 Internet Connected
 ✓ IPv6 Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
```

 it's not installing Pi-hole in that container without issues for some reason. I'm _guessing_ because of IPv6 enabled in your router.
```
 \ Installing Pi-hole   
[ERROR] in line 23: exit code 0: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.
```

**Comment by ArnaudFeld** [comment]
But Then is the Question why the Installation works when i Setup the CT manually and also the Installation of PiHole?

If IPv6 is the reason it should Not work on any Way i do the Installation, but that is Not the case

**Comment by tteck** [comment]
Good question, I have no idea. 🤷🏻‍♂️

**Comment by ArnaudFeld** [comment]
For others:

If you have restricted your router so that no device, except your Pi-hole (in my case, my old Pi-hole), can resolve DNS on its own, the installation will fail.

Disable the restriction, complete the installation, and then re-enable it. Also, don’t forget to set your new Pi-hole as the only DNS server in your network (if that’s what you want).

So it is not IPv6 ;)
