### ISSUE TITLE
Traefik script installs latest RC instead of latest stable

### ISSUE THREAD

**Issue by Sarke** [tteck/Proxmox#3294]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Did the Traefik LXC install, but it installed v3.1.0-rc2 instead of the latest stable (v3.0.3).  I don't think this is desirable for most people.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/traefik.sh)"
```

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by Sarke** [comment]
With all due respect, @tteck, this is a bug as it causes unexpected behaviour.  For example, if you were to run this install in the last 2 days, depending on the precise time it was run, it would have installed one of the following:

v3.1.0-rc3 (latest RC)
v3.0.4 (latest stable)
v2.11.6 (latest v2 branch)

If you still think that is intended behaviour, I'll submit a feature request, but to me this is a bug.

**Comment by tteck** [comment]
You are correct. They're not utilizing proper tags. e.g. pre-release, release or latest. I'm guessing I will have to hard-code the version.

**Comment by tteck** [comment]
Hard-coded version https://github.com/tteck/Proxmox/commit/65968509182c9f25c7445eaeed3f9ca22f441b8d

**Comment by abediali** [comment]
Since version 3.10 is out, running the update command doesn't do anything with the hardcoded value.
