### ISSUE TITLE
Debian VM script gives errors

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#3295]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi @tteck I love your scripts but had to revert to standard Debian install due to the fact that i got persistent package dpkg errors. Can you please have a look ?

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
I need more information. "A clear and concise description of the issue."

**Comment by tteck** [comment]
After Debian 12 VM creation, are you following https://github.com/tteck/Proxmox/discussions/1988?
