### ISSUE TITLE
Nextcloud update stuck on 27.1.x

### ISSUE THREAD

**Issue by ordo01** [tteck/Proxmox#3298]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have an issue with the update of Nextcloud. Running the script I do see the option to update to the latest version 29.0.3

                               ┌──────────────────────┤ SUPPORT ├───────────────────────┐
                               │ Spacebar = Select                                      │
                               │                                                        │
                               │  (*) 1  Update Nextcloud to v29.0.3                    │
                               │  ( ) 2  Nextcloud Login Credentials                    │
                               │  ( ) 3  Renew Self-signed Certificate                  │
                               │                                                        │
                               │                                                        │
                               │             <Ok>                 <Exit-Script>         │
                               │                                                        │
                               └────────────────────────────────────────────────────────┘

Once selected the update script shows updating from 27.1.10 to 27.1.11. But not updating to the next major release.
Please see the logs.
    _   __          __       __                __   __  __      __
   / | / /__  _  __/ /______/ /___  __  ______/ /  / / / /_  __/ /_
  /  |/ / _ \| |/_/ __/ ___/ / __ \/ / / / __  /  / /_/ / / / / __ \
 / /|  /  __/>  </ /_/ /__/ / /_/ / /_/ / /_/ /  / __  / /_/ / /_/ /
/_/ |_/\___/_/|_|\__/\___/_/\____/\__,_/\__,_/  /_/ /_/\__,_/_.___/
Alpine
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
v3.19.2-25-g7baf9e90ed4 [http://dl-cdn.alpinelinux.org/alpine/v3.19/main]
v3.19.2-26-g84c795618cb [http://dl-cdn.alpinelinux.org/alpine/v3.19/community]
OK: 23066 distinct packages available
(1/36) Upgrading libcrypto3 (3.1.5-r0 -> 3.1.6-r0)
(2/36) Upgrading libssl3 (3.1.5-r0 -> 3.1.6-r0)
(3/36) Upgrading nextcloud (27.1.10-r0 -> 27.1.11-r0)
Executing nextcloud-27.1.11-r0.pre-upgrade
Executing nextcloud-27.1.11-r0.post-upgrade
  * Run "occ upgrade" to finish upgrading your NextCloud instance!
(4/36) Upgrading nextcloud-activity (27.1.10-r0 -> 27.1.11-r0)
(5/36) Upgrading nextcloud-admin_audit (27.1.10-r0 -> 27.1.11-r0)
(6/36) Upgrading nextcloud-comments (27.1.10-r0 -> 27.1.11-r0)
(7/36) Upgrading nextcloud-dashboard (27.1.10-r0 -> 27.1.11-r0)
(8/36) Upgrading nextcloud-circles (27.1.10-r0 -> 27.1.11-r0)
(9/36) Upgrading nextcloud-files_pdfviewer (27.1.10-r0 -> 27.1.11-r0)
(10/36) Upgrading nextcloud-files_rightclick (27.1.10-r0 -> 27.1.11-r0)
(11/36) Upgrading nextcloud-logreader (27.1.10-r0 -> 27.1.11-r0)
(12/36) Upgrading nextcloud-password_policy (27.1.10-r0 -> 27.1.11-r0)
(13/36) Upgrading nextcloud-photos (27.1.10-r0 -> 27.1.11-r0)
(14/36) Upgrading nextcloud-privacy (27.1.10-r0 -> 27.1.11-r0)
(15/36) Upgrading nextcloud-recommendations (27.1.10-r0 -> 27.1.11-r0)
(16/36) Upgrading nextcloud-files_sharing (27.1.10-r0 -> 27.1.11-r0)
(17/36) Upgrading nextcloud-serverinfo (27.1.10-r0 -> 27.1.11-r0)
(18/36) Upgrading nextcloud-survey_client (27.1.10-r0 -> 27.1.11-r0)
(19/36) Upgrading nextcloud-text (27.1.10-r0 -> 27.1.11-r0)
(20/36) Upgrading nextcloud-default-apps (27.1.10-r0 -> 27.1.11-r0)
(21/36) Upgrading nextcloud-doc (27.1.10-r0 -> 27.1.11-r0)
(22/36) Upgrading nextcloud-encryption (27.1.10-r0 -> 27.1.11-r0)
(23/36) Upgrading nextcloud-federation (27.1.10-r0 -> 27.1.11-r0)
(24/36) Upgrading nextcloud-files_external (27.1.10-r0 -> 27.1.11-r0)
(25/36) Upgrading nextcloud-files_trashbin (27.1.10-r0 -> 27.1.11-r0)
(26/36) Upgrading nextcloud-files_versions (27.1.10-r0 -> 27.1.11-r0)
(27/36) Upgrading nextcloud-initscript (27.1.10-r0 -> 27.1.11-r0)
(28/36) Upgrading nextcloud-mysql (27.1.10-r0 -> 27.1.11-r0)
(29/36) Upgrading nextcloud-notifications (27.1.10-r0 -> 27.1.11-r0)
(30/36) Upgrading nextcloud-sharebymail (27.1.10-r0 -> 27.1.11-r0)
(31/36) Upgrading nextcloud-support (27.1.10-r0 -> 27.1.11-r0)
(32/36) Upgrading nextcloud-suspicious_login (27.1.10-r0 -> 27.1.11-r0)
(33/36) Upgrading nextcloud-systemtags (27.1.10-r0 -> 27.1.11-r0)
(34/36) Upgrading nextcloud-user_status (27.1.10-r0 -> 27.1.11-r0)
(35/36) Upgrading nextcloud-weather_status (27.1.10-r0 -> 27.1.11-r0)
(36/36) Upgrading openssl (3.1.5-r0 -> 3.1.6-r0)
Executing busybox-1.36.1-r19.trigger
Executing ca-certificates-20240226-r0.trigger
OK: 1008 MiB in 251 packages

Running the script a second time, I get the message "Nextcloud is already latest version".
How can I perform the update

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### Please provide detailed steps to reproduce the issue.

Run the update script 
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-nextcloud.sh)"

**Comment by tteck** [comment]
You are obliged to adhere to updates provided by the package maintainer.
[Alpine 3.19](https://pkgs.alpinelinux.org/packages?name=nextcloud&branch=v3.19&repo=&arch=x86_64&maintainer=)
[Alpine 3.20](https://pkgs.alpinelinux.org/packages?name=nextcloud&branch=v3.20&repo=&arch=x86_64&maintainer=)

I will remove the update option.
