### ISSUE TITLE
paperless-ngx update error

### ISSUE THREAD

**Issue by andreklug** [tteck/Proxmox#3308]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the script to update to 2.10.2, the update fails with the following error message:

```
    ____                        __                                     
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/                                         /____/        
 
 ✓ Stopped all Paperless-ngx Services
 \ Updating to v2.10.2   
[ERROR] in line 81: exit code 0: while executing command pip install -r requirements.txt &> /dev/null
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
If you have updated to Debian 12.6, execute `rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED` in the LXC console.

**Comment by andreklug** [comment]
That solved the issue, thank you very much!

**Comment by timdonovanuk** [comment]
This command did not solve the issue for me. 

```
root@lxc-paperlessngx:~# cat /proc/version
Linux version 6.5.13-1-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-1 (2024-02-05T13:50Z)
```

Solved it by randomly running random commands from random issues.

```
#cd /opt/paperless/src
/usr/bin/python3 /opt/paperless/src/manage.py migrate &>/dev/null
```

https://github.com/tteck/Proxmox/issues/2976

Edit: oh I lie, it broke my paperless ng instance. It loads but throws a bunch of errors. But it's _not_ a script issue.
