### ISSUE TITLE
Whoogle LXC install fails

### ISSUE THREAD

**Issue by Sailing74** [tteck/Proxmox#331]
Trying to install the Whoogle LXC container with IP settings

`Using Bridge vmbr0
Using Static IP Address 192.168.1.201
Using Gateway IP Address 192.168.1.1
Using VLAN Tag NONE`

fails with

` - Creating LXC Container...400 Parameter verification failed.
net0: invalid format - format error
net0.ip: invalid format - value does not look like a valid ipv4 network configuration`

**Comment by tteck** [comment]
You must "Enter a Static IPv4 CIDR Address"
example: `192.168.1.201/24`
