### ISSUE TITLE
Updating NGINX proxy manager from 2.10.2 to 2.10.3

### ISSUE THREAD

**Issue by oswaldo-be** [tteck/Proxmox#3311]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.11.3
 | Setting up Enviroment   
[ERROR] in line 136: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

none

### Please provide detailed steps to reproduce the issue.

execute update in Terminal

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/3300#discussioncomment-9923938

**Comment by tteck** [comment]
It's not a bad idea to execute `rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED` in all LXC consoles.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by oswaldo-be** [comment]
Great, thank you very much. 
It worked.
