### ISSUE TITLE
Frigate install Error

### ISSUE THREAD

**Issue by greirson** [tteck/Proxmox#3315]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Receiving error on installing Frigate LXC

```
Unpacking python3-pycoral (2.0.0) ...
Setting up libwebpdemux2:amd64 (0.6.1-2.1+deb11u2) ...
Setting up libedgetpu1-max:amd64 (16.0) ...
Setting up libimagequant0:amd64 (2.12.2-1.1) ...
Setting up python3-numpy (1:1.19.5-1) ...
Setting up python3-tflite-runtime (2.5.0.post1) ...
Setting up python3-pil:amd64 (8.1.2+dfsg-0.3+deb11u2) ...
Setting up python3-pycoral (2.0.0) ...
Processing triggers for libc-bin (2.31-13+deb11u10) ...
+ [[ amd64 == \a\m\d\6\4 ]]
+ mkdir -p /usr/lib/btbn-ffmpeg
+ wget -qO btbn-ffmpeg.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-07-31-12-37/ffmpeg-n5.1-2-g915ef932a3-linux64-gpl-5.1.tar.xz

[ERROR] in line 63: exit code 0: while executing command $STD /opt/frigate/docker/main/install_deps.sh
```

Running on a fresh install with a i7-13620H

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

Run script, default settings

**Comment by tteck** [comment]
That's a Frigate issue in their `install_deps.sh`. The FFmpeg link was updated today (https://github.com/BtbN/FFmpeg-Builds/releases/) and apparently `wget -qO btbn-ffmpeg.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-07-31-12-37/ffmpeg-n5.1-2-g915ef932a3-linux64-gpl-5.1.tar.xz` was dropped 
```
root@frigate:~# wget https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-07-31-12-37/ffmpeg-n5.1-2-g915ef932a3-
linux64-gpl-5.1.tar.xz
--2024-07-01 18:34:52--  https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-07-31-12-37/ffmpeg-n5.1-2-g915ef932a3-linux64-gpl-5.1.tar.xz
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-07-01 18:34:52 ERROR 404: Not Found.
```

**Comment by greirson** [comment]
[It looks like they're working on updating the FFmpeg source](https://github.com/blakeblackshear/frigate/commit/ef7846bb41d500ff79c0a97c40636672ea7ab048)
