### ISSUE TITLE
Having issue when installing Friagte

### ISSUE THREAD

**Issue by mastan30** [tteck/Proxmox#3317]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Seeing the below error when trying to install Friagte LXC

Setting up nethogs (0.8.5-2+b1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+deb11u10) ...
+ update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
update-alternatives: using /usr/bin/python3.9 to provide /usr/bin/python3 (python3) in auto mode
+ mkdir -p -m 600 /root/.gnupg
+ curl -fsSLo - https://packages.cloud.google.com/apt/doc/apt-key.gpg
+ gpg --dearmor -o /etc/apt/trusted.gpg.d/google-cloud-packages-archive-keyring.gpg
+ tee /etc/apt/sources.list.d/coral-edgetpu.list
+ echo 'deb https://packages.cloud.google.com/apt coral-edgetpu-stable main'
deb https://packages.cloud.google.com/apt coral-edgetpu-stable main
+ debconf-set-selections
+ echo 'libedgetpu1-max libedgetpu/accepted-eula select true'
+ grep -q Debian /etc/issue
+ sed -i '-es/ main/ main contrib non-free/g' /etc/apt/sources.list
+ apt-get -qq update
+ apt-get -qq install --no-install-recommends --no-install-suggests -y libedgetpu1-max python3-tflite-runtime python3-pycoral
Preconfiguring packages ...
Selecting previously unselected package libedgetpu1-max:amd64.
(Reading database ... 49999 files and directories currently installed.)
Preparing to unpack .../0-libedgetpu1-max_16.0_amd64.deb ...
Unpacking libedgetpu1-max:amd64 (16.0) ...
Selecting previously unselected package libimagequant0:amd64.
Preparing to unpack .../1-libimagequant0_2.12.2-1.1_amd64.deb ...
Unpacking libimagequant0:amd64 (2.12.2-1.1) ...
Selecting previously unselected package libwebpdemux2:amd64.
Preparing to unpack .../2-libwebpdemux2_0.6.1-2.1+deb11u2_amd64.deb ...
Unpacking libwebpdemux2:amd64 (0.6.1-2.1+deb11u2) ...
Selecting previously unselected package python3-numpy.
Preparing to unpack .../3-python3-numpy_1%3a1.19.5-1_amd64.deb ...
Unpacking python3-numpy (1:1.19.5-1) ...
Selecting previously unselected package python3-pil:amd64.
Preparing to unpack .../4-python3-pil_8.1.2+dfsg-0.3+deb11u2_amd64.deb ...
Unpacking python3-pil:amd64 (8.1.2+dfsg-0.3+deb11u2) ...
Selecting previously unselected package python3-tflite-runtime.
Preparing to unpack .../5-python3-tflite-runtime_2.5.0.post1_amd64.deb ...
Unpacking python3-tflite-runtime (2.5.0.post1) ...
Selecting previously unselected package python3-pycoral.
Preparing to unpack .../6-python3-pycoral_2.0.0_amd64.deb ...
Unpacking python3-pycoral (2.0.0) ...
Setting up libwebpdemux2:amd64 (0.6.1-2.1+deb11u2) ...
Setting up libedgetpu1-max:amd64 (16.0) ...
Setting up libimagequant0:amd64 (2.12.2-1.1) ...
Setting up python3-numpy (1:1.19.5-1) ...
Setting up python3-tflite-runtime (2.5.0.post1) ...
Setting up python3-pil:amd64 (8.1.2+dfsg-0.3+deb11u2) ...
Setting up python3-pycoral (2.0.0) ...
Processing triggers for libc-bin (2.31-13+deb11u10) ...
+ [[ amd64 == \a\m\d\6\4 ]]
+ mkdir -p /usr/lib/btbn-ffmpeg
+ wget -qO btbn-ffmpeg.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-07-31-12-37/ffmpeg-n5.1-2-g915ef932a3-linux64-gpl-5.1.tar.xz

[ERROR] in line 63: exit code 0: while executing command $STD /opt/frigate/docker/main/install_deps.sh

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Setting up nethogs (0.8.5-2+b1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+deb11u10) ...
+ update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
update-alternatives: using /usr/bin/python3.9 to provide /usr/bin/python3 (python3) in auto mode
+ mkdir -p -m 600 /root/.gnupg
+ curl -fsSLo - https://packages.cloud.google.com/apt/doc/apt-key.gpg
+ gpg --dearmor -o /etc/apt/trusted.gpg.d/google-cloud-packages-archive-keyring.gpg
+ tee /etc/apt/sources.list.d/coral-edgetpu.list
+ echo 'deb https://packages.cloud.google.com/apt coral-edgetpu-stable main'
deb https://packages.cloud.google.com/apt coral-edgetpu-stable main
+ debconf-set-selections
+ echo 'libedgetpu1-max libedgetpu/accepted-eula select true'
+ grep -q Debian /etc/issue
+ sed -i '-es/ main/ main contrib non-free/g' /etc/apt/sources.list
+ apt-get -qq update
+ apt-get -qq install --no-install-recommends --no-install-suggests -y libedgetpu1-max python3-tflite-runtime python3-pycoral
Preconfiguring packages ...
Selecting previously unselected package libedgetpu1-max:amd64.
(Reading database ... 49999 files and directories currently installed.)
Preparing to unpack .../0-libedgetpu1-max_16.0_amd64.deb ...
Unpacking libedgetpu1-max:amd64 (16.0) ...
Selecting previously unselected package libimagequant0:amd64.
Preparing to unpack .../1-libimagequant0_2.12.2-1.1_amd64.deb ...
Unpacking libimagequant0:amd64 (2.12.2-1.1) ...
Selecting previously unselected package libwebpdemux2:amd64.
Preparing to unpack .../2-libwebpdemux2_0.6.1-2.1+deb11u2_amd64.deb ...
Unpacking libwebpdemux2:amd64 (0.6.1-2.1+deb11u2) ...
Selecting previously unselected package python3-numpy.
Preparing to unpack .../3-python3-numpy_1%3a1.19.5-1_amd64.deb ...
Unpacking python3-numpy (1:1.19.5-1) ...
Selecting previously unselected package python3-pil:amd64.
Preparing to unpack .../4-python3-pil_8.1.2+dfsg-0.3+deb11u2_amd64.deb ...
Unpacking python3-pil:amd64 (8.1.2+dfsg-0.3+deb11u2) ...
Selecting previously unselected package python3-tflite-runtime.
Preparing to unpack .../5-python3-tflite-runtime_2.5.0.post1_amd64.deb ...
Unpacking python3-tflite-runtime (2.5.0.post1) ...
Selecting previously unselected package python3-pycoral.
Preparing to unpack .../6-python3-pycoral_2.0.0_amd64.deb ...
Unpacking python3-pycoral (2.0.0) ...
Setting up libwebpdemux2:amd64 (0.6.1-2.1+deb11u2) ...
Setting up libedgetpu1-max:amd64 (16.0) ...
Setting up libimagequant0:amd64 (2.12.2-1.1) ...
Setting up python3-numpy (1:1.19.5-1) ...
Setting up python3-tflite-runtime (2.5.0.post1) ...
Setting up python3-pil:amd64 (8.1.2+dfsg-0.3+deb11u2) ...
Setting up python3-pycoral (2.0.0) ...
Processing triggers for libc-bin (2.31-13+deb11u10) ...
+ [[ amd64 == \a\m\d\6\4 ]]
+ mkdir -p /usr/lib/btbn-ffmpeg
+ wget -qO btbn-ffmpeg.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-07-31-12-37/ffmpeg-n5.1-2-g915ef932a3-linux64-gpl-5.1.tar.xz

[ERROR] in line 63: exit code 0: while executing command $STD /opt/frigate/docker/main/install_deps.sh

### Please provide detailed steps to reproduce the issue.

Use the script for frigate lxc and it's failing with a message to set verbose, did the verbose setting and found the above error.

**Comment by mastan30** [comment]
Duplicate issue

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/eab4160c33137b8e999dea7df0821f9e0988a48c
