### ISSUE TITLE
PiHole Installation Issue

### ISSUE THREAD

**Issue by millie75** [tteck/Proxmox#332]
Hi

I'm getting the below when trying to install Pi-Hole.
I'm using the advanced setup to install and choosing an IP for static in the form of 192.168.1.13/24 and get the error message while it is install the pi-hole part. I have tried 3 times with a different static IP but have the same result each time

  [i] Installer exited at static IP message.
‼ ERROR 1@68 Unknown failure occured.

**Comment by tteck** [comment]
Did you "Enter a Gateway IP (mandatory if static IP is used)"?
example: `192.168.1.1`

**Comment by millie75** [comment]
Yes add the gateway, and also tried on another proxmox and get the same issue

**Comment by tteck** [comment]
Let me check here

**Comment by tteck** [comment]
I'm getting the error as you. 
The issue seems to be with their script `https://install.pi-hole.net` 
I'm looking into it

**Comment by millie75** [comment]
Cheers

**Comment by tteck** [comment]
I just got a `✓ Completed Successfully!` by not using auto login (set a password) and setting a static IP
beings we are now Debian 11.4, that may have changed something?
Try what I did to see if it works for you.
meanwhile, I'm still investigating the issue.

**Comment by millie75** [comment]
I gave that a try, set a password and the IP address 192.168.1.13/24 with the appropriate gateway, but have the same error message

**Comment by tteck** [comment]
Issues have been resolved.
Thank you for bringing this issue to my attention.

**Comment by cdladeroute** [comment]
This is still happening to me today. sigh
