### ISSUE TITLE
jellyfin script doesn't work

### ISSUE THREAD

**Issue by caiot5** [tteck/Proxmox#3340]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I don't know much but the script did not work for me.
The errors were:

root@pxx02-sbr-sjp-brz:~/Proxmox/install# ./jellyfin-install.sh 
./jellyfin-install.sh: line 9: color: command not found
./jellyfin-install.sh: line 10: verb_ip6: command not found
./jellyfin-install.sh: line 11: catch_errors: command not found
./jellyfin-install.sh: line 12: setting_up_container: command not found
./jellyfin-install.sh: line 13: network_check: command not found
./jellyfin-install.sh: line 14: update_os: command not found
./jellyfin-install.sh: line 16: msg_info: command not found
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.74.0-1.3+deb11u12).
curl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 134 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
sudo is already the newest version (1.9.5p2-3+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 134 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnupg is already the newest version (2.2.27-2+deb11u2).
0 upgraded, 0 newly installed, 0 to remove and 134 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mc is already the newest version (3:4.8.26-1.1).
0 upgraded, 0 newly installed, 0 to remove and 134 not upgraded.
./jellyfin-install.sh: line 21: msg_ok: command not found
./jellyfin-install.sh: line 23: msg_info: command not found
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
intel-opencl-icd is already the newest version (20.44.18297-1).
intel-gpu-tools is already the newest version (1.25-2.1).
va-driver-all is already the newest version (2.10.0-1).
vainfo is already the newest version (2.10.0+ds1-1).
ocl-icd-libopencl1 is already the newest version (2.2.14-2).
0 upgraded, 0 newly installed, 0 to remove and 134 not upgraded.
./jellyfin-install.sh: line 32: msg_ok: command not found
./jellyfin-install.sh: line 34: msg_info: command not found
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://alcateia.ufscar.br/debian bullseye InRelease                                                       
Hit:3 http://alcateia.ufscar.br/debian bullseye-updates InRelease                                               
Ign:4 https://repo.jellyfin.org bullseye InRelease                                                              
Hit:5 http://download.proxmox.com/debian/pve bullseye InRelease
Err:6 https://repo.jellyfin.org bullseye Release     
  404  Not found [IP: 68.183.204.194 443]
Reading package lists... Done                       
E: The repository 'https://repo.jellyfin.org bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package jellyfin
./jellyfin-install.sh: line 59: msg_ok: command not found
./jellyfin-install.sh: line 61: motd_ssh: command not found
./jellyfin-install.sh: line 62: customize: command not found
./jellyfin-install.sh: line 64: msg_info: command not found
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 134 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
./jellyfin-install.sh: line 67: msg_ok: command not found

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

- Clone the repository
- Run the jellyfin-install.sh

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
