### ISSUE TITLE
Stirling wrong python version

### ISSUE THREAD

**Issue by Lyngtoft** [tteck/Proxmox#3351]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The function of converting a Word file .docx doesn't work. - many other features work fine though, so far only seen problems with .docx files.

> Internal Server Error:java.io.IOException: Command process failed with exit code 1. Error message: unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice ERROR: No module named 'base' unoconv: Cannot find a suitable office installation on your system. ERROR: Please locate your office installation and send your feedback to: http://github.com/dagwieers/unoconv/issues

As far as i can see the documentation states that Python 3.8 should be used, but i believe 3.11 is installed.
https://stirlingtools.com/docs/Getting%20started/Installation/Local/Unix%20Installation/

I tried running the steps for the unoconv since that is the one from the error, but that didn't help.
pip3 install uno opencv-python-headless unoconv pngquant WeasyPrint --break-system-packages

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Run default install
Try to convert a .docx file to PDF

**Comment by tteck** [comment]
I don't _think_ the Python version is the issue.

Still open issues https://github.com/Stirling-Tools/Stirling-PDF/issues/1403 and https://github.com/unoconv/unoconv/issues/615

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by Lyngtoft** [comment]
Thank you for looking into it. It does however look like it really should be 3.8 and not the 3.11 that is default. I see an older post about it as well.
https://github.com/Stirling-Tools/Stirling-PDF/issues/575
(Unfortunately the fix there for Ubuntu doesn't seem to translate directly to the debian version)

But no problem, I will give it a go with a manual install to verify if I can get it up and running.
