### ISSUE TITLE
Frigate

### ISSUE THREAD

**Issue by Ceel84** [tteck/Proxmox#3355]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have a problem with the installation:

`Package libtbb2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtbbmalloc2

E: Package 'libtbb2' has no installation candidate
E: Unable to locate package libdc1394-22-dev

[ERROR] in line 17: exit code 0: while executing command $STD apt-get install -y {curl,sudo,mc,git,gpg,automake,build-essential,xz-utils,libtool,ccache,pkg-config,libgtk-3-dev,libavcodec-dev,libavformat-dev,libswscale-dev,libv4l-dev,libxvidcore-dev,libx264-dev,libjpeg-dev,libpng-dev,libtiff-dev,gfortran,openexr,libatlas-base-dev,libssl-dev,libtbb2,libtbb-dev,libdc1394-22-dev,libopenexr-dev,libgstreamer-plugins-base1.0-dev,libgstreamer1.0-dev,gcc,gfortran,libopenblas-dev,liblapack-dev,libusb-1.0-0-dev,jq}`

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Get:1 http://security.debian.org bookworm-security InRelease [48.0 kB]
Get:2 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:4 http://security.debian.org bookworm-security/main amd64 Packages [168 kB]
Get:5 http://security.debian.org bookworm-security/main Translation-en [101 kB]
Get:6 http://security.debian.org bookworm-security/contrib amd64 Packages [644 B]
Get:7 http://security.debian.org bookworm-security/contrib Translation-en [372 B]
Get:8 http://deb.debian.org/debian bookworm/main amd64 Packages [8,788 kB]
Get:9 http://deb.debian.org/debian bookworm-updates/main amd64 Packages.diff/Index [10.6 kB]
Get:10 http://deb.debian.org/debian bookworm-updates/contrib amd64 Packages.diff/Index [1,591 B]
Get:11 http://deb.debian.org/debian bookworm-updates/main amd64 Packages T-2024-04-23-2036.10-F-2023-11-06-2008.27.pdiff [8,935 B]
Get:11 http://deb.debian.org/debian bookworm-updates/main amd64 Packages T-2024-04-23-2036.10-F-2023-11-06-2008.27.pdiff [8,935 B]
Get:12 http://deb.debian.org/debian bookworm-updates/contrib amd64 Packages T-2024-02-16-2007.16-F-2024-02-16-2007.16.pdiff [682 B]
Get:12 http://deb.debian.org/debian bookworm-updates/contrib amd64 Packages T-2024-02-16-2007.16-F-2024-02-16-2007.16.pdiff [682 B]
Get:13 http://deb.debian.org/debian bookworm/main Translation-en [6,109 kB]
Get:14 http://deb.debian.org/debian bookworm/contrib amd64 Packages [54.1 kB]
Get:15 http://deb.debian.org/debian bookworm/contrib Translation-en [48.8 kB]
Get:16 http://deb.debian.org/debian bookworm-updates/main Translation-en [16.0 kB]
Get:17 http://deb.debian.org/debian bookworm-updates/contrib Translation-en [408 B]
Fetched 15.6 MB in 2s (9,140 kB/s)                                 
Reading package lists... Done
 \N: Repository 'http://deb.debian.org/debian bookworm InRelease' changed its 'Version' value from '12.2' to '12.6'
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
 -The following packages will be upgraded:
  base-files bash bind9-dnsutils bind9-host bind9-libs bsdextrautils bsdutils distro-info-data fdisk krb5-locales less libblkid1 libc-bin libc-l10n libc6 libcryptsetup12 libcurl3-gnutls libfdisk1 libgnutls30 libgssapi-krb5-2
  libk5crypto3 libkrb5-3 libkrb5support0 libmount1 libnghttp2-14 libnss-systemd libpam-systemd libperl5.36 libpython3.11-minimal libpython3.11-stdlib libseccomp2 libsmartcols1 libssl3 libsystemd-shared libsystemd0 libudev1
  libuuid1 libuv1 locales mount nano openssh-client openssh-server openssh-sftp-server openssl perl perl-base perl-modules-5.36 postfix python3-idna python3.11 python3.11-minimal ssh systemd systemd-sysv systemd-timesyncd tar
  tzdata udev usrmerge util-linux util-linux-extra
 \62 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 47.0 MB of archives.
After this operation, 462 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 base-files amd64 12.4+deb12u6 [70.8 kB]
Get:2 http://security.debian.org bookworm-security/main amd64 libgssapi-krb5-2 amd64 1.20.1-2+deb12u2 [135 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 bash amd64 5.2.15-2+b7 [1,490 kB]
Get:4 http://security.debian.org bookworm-security/main amd64 libkrb5-3 amd64 1.20.1-2+deb12u2 [332 kB]
Get:5 http://security.debian.org bookworm-security/main amd64 libkrb5support0 amd64 1.20.1-2+deb12u2 [32.6 kB]
Get:6 http://security.debian.org bookworm-security/main amd64 libk5crypto3 amd64 1.20.1-2+deb12u2 [78.7 kB]
Get:7 http://security.debian.org bookworm-security/main amd64 openssh-sftp-server amd64 1:9.2p1-2+deb12u3 [65.8 kB]
Get:8 http://security.debian.org bookworm-security/main amd64 openssh-server amd64 1:9.2p1-2+deb12u3 [456 kB]
Get:9 http://security.debian.org bookworm-security/main amd64 openssh-client amd64 1:9.2p1-2+deb12u3 [991 kB]
Get:10 http://security.debian.org bookworm-security/main amd64 krb5-locales all 1.20.1-2+deb12u2 [62.8 kB]
Get:11 http://security.debian.org bookworm-security/main amd64 ssh all 1:9.2p1-2+deb12u3 [174 kB]
Get:12 http://deb.debian.org/debian bookworm/main amd64 bsdutils amd64 1:2.38.1-5+deb12u1 [94.3 kB]
Get:13 http://deb.debian.org/debian bookworm/main amd64 libperl5.36 amd64 5.36.0-7+deb12u1 [4,218 kB]
Get:14 http://deb.debian.org/debian bookworm/main amd64 perl amd64 5.36.0-7+deb12u1 [239 kB]
Get:15 http://deb.debian.org/debian bookworm/main amd64 perl-base amd64 5.36.0-7+deb12u1 [1,608 kB]
Get:16 http://deb.debian.org/debian bookworm/main amd64 perl-modules-5.36 all 5.36.0-7+deb12u1 [2,815 kB]
Get:17 http://deb.debian.org/debian bookworm/main amd64 libc6 amd64 2.36-9+deb12u7 [2,758 kB]
Get:18 http://deb.debian.org/debian bookworm/main amd64 tar amd64 1.34+dfsg-1.2+deb12u1 [836 kB]
Get:19 http://deb.debian.org/debian bookworm/main amd64 libsmartcols1 amd64 2.38.1-5+deb12u1 [107 kB]
Get:20 http://deb.debian.org/debian bookworm/main amd64 util-linux-extra amd64 2.38.1-5+deb12u1 [110 kB]
Get:21 http://deb.debian.org/debian bookworm/main amd64 util-linux amd64 2.38.1-5+deb12u1 [1,176 kB]
Get:22 http://deb.debian.org/debian bookworm/main amd64 libc-bin amd64 2.36-9+deb12u7 [607 kB]
Get:23 http://deb.debian.org/debian bookworm/main amd64 mount amd64 2.38.1-5+deb12u1 [134 kB]
Get:24 http://deb.debian.org/debian bookworm/main amd64 libnss-systemd amd64 252.26-1~deb12u2 [163 kB]
Get:25 http://deb.debian.org/debian bookworm/main amd64 libblkid1 amd64 2.38.1-5+deb12u1 [147 kB]
Get:26 http://deb.debian.org/debian bookworm/main amd64 libmount1 amd64 2.38.1-5+deb12u1 [165 kB]
Get:27 http://deb.debian.org/debian bookworm/main amd64 libseccomp2 amd64 2.5.4-1+deb12u1 [46.8 kB]
Get:28 http://deb.debian.org/debian bookworm/main amd64 libssl3 amd64 3.0.13-1~deb12u1 [2,022 kB]
Get:29 http://deb.debian.org/debian bookworm/main amd64 systemd-timesyncd amd64 252.26-1~deb12u2 [63.4 kB]
Get:30 http://deb.debian.org/debian bookworm/main amd64 libpam-systemd amd64 252.26-1~deb12u2 [225 kB]
Get:31 http://deb.debian.org/debian bookworm/main amd64 systemd amd64 252.26-1~deb12u2 [3,035 kB]
Get:32 http://deb.debian.org/debian bookworm/main amd64 libsystemd-shared amd64 252.26-1~deb12u2 [1,692 kB]
Get:33 http://deb.debian.org/debian bookworm/main amd64 systemd-sysv amd64 252.26-1~deb12u2 [42.3 kB]
Get:34 http://deb.debian.org/debian bookworm/main amd64 libuuid1 amd64 2.38.1-5+deb12u1 [28.6 kB]
Get:35 http://deb.debian.org/debian bookworm/main amd64 libcryptsetup12 amd64 2:2.6.1-4~deb12u2 [223 kB]
Get:36 http://deb.debian.org/debian bookworm/main amd64 libfdisk1 amd64 2.38.1-5+deb12u1 [193 kB]
Get:37 http://deb.debian.org/debian bookworm/main amd64 libsystemd0 amd64 252.26-1~deb12u2 [332 kB]
Get:38 http://deb.debian.org/debian bookworm/main amd64 postfix amd64 3.7.11-0+deb12u1 [1,510 kB]
Get:39 http://deb.debian.org/debian bookworm/main amd64 python3.11 amd64 3.11.2-6+deb12u2 [573 kB]
Get:40 http://deb.debian.org/debian bookworm/main amd64 libpython3.11-stdlib amd64 3.11.2-6+deb12u2 [1,799 kB]
Get:41 http://deb.debian.org/debian bookworm/main amd64 python3.11-minimal amd64 3.11.2-6+deb12u2 [2,067 kB]
Get:42 http://deb.debian.org/debian bookworm/main amd64 libpython3.11-minimal amd64 3.11.2-6+deb12u2 [814 kB]
Get:43 http://deb.debian.org/debian bookworm/main amd64 libgnutls30 amd64 3.7.9-2+deb12u3 [1,405 kB]
Get:44 http://deb.debian.org/debian bookworm/main amd64 udev amd64 252.26-1~deb12u2 [1,682 kB]
Get:45 http://deb.debian.org/debian bookworm/main amd64 libudev1 amd64 252.26-1~deb12u2 [108 kB]
Get:46 http://deb.debian.org/debian bookworm/main amd64 usrmerge all 37~deb12u1 [13.3 kB]
Get:47 http://deb.debian.org/debian bookworm/main amd64 tzdata all 2024a-0+deb12u1 [297 kB]
Get:48 http://deb.debian.org/debian bookworm/main amd64 fdisk amd64 2.38.1-5+deb12u1 [141 kB]
Get:49 http://deb.debian.org/debian bookworm/main amd64 less amd64 590-2.1~deb12u2 [132 kB]
Get:50 http://deb.debian.org/debian bookworm/main amd64 nano amd64 7.2-1+deb12u1 [690 kB]
Get:51 http://deb.debian.org/debian bookworm/main amd64 libuv1 amd64 1.44.2-1+deb12u1 [136 kB]
Get:52 http://deb.debian.org/debian bookworm/main amd64 libnghttp2-14 amd64 1.52.0-1+deb12u1 [72.4 kB]
Get:53 http://deb.debian.org/debian bookworm/main amd64 bind9-dnsutils amd64 1:9.18.24-1 [403 kB]
Get:54 http://deb.debian.org/debian bookworm/main amd64 bind9-host amd64 1:9.18.24-1 [305 kB]
Get:55 http://deb.debian.org/debian bookworm/main amd64 bind9-libs amd64 1:9.18.24-1 [1,413 kB]
Get:56 http://deb.debian.org/debian bookworm/main amd64 libc-l10n all 2.36-9+deb12u7 [675 kB]
Get:57 http://deb.debian.org/debian bookworm/main amd64 locales all 2.36-9+deb12u7 [3,902 kB]
Get:58 http://deb.debian.org/debian bookworm/main amd64 bsdextrautils amd64 2.38.1-5+deb12u1 [86.8 kB]
Get:59 http://deb.debian.org/debian bookworm/main amd64 distro-info-data all 0.58+deb12u2 [6,204 B]
Get:60 http://deb.debian.org/debian bookworm/main amd64 libcurl3-gnutls amd64 7.88.1-10+deb12u6 [385 kB]
Get:61 http://deb.debian.org/debian bookworm/main amd64 openssl amd64 3.0.13-1~deb12u1 [1,418 kB]
Get:62 http://deb.debian.org/debian bookworm/main amd64 python3-idna all 3.3-1+deb12u1 [41.0 kB]
Fetched 47.0 MB in 1s (66.4 MB/s)          
 \apt-listchanges: Reading changelogs...
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 19150 files and directories currently installed.)
Preparing to unpack .../base-files_12.4+deb12u6_amd64.deb ...
Unpacking base-files (12.4+deb12u6) over (12.4+deb12u2) ...
 /Setting up base-files (12.4+deb12u6) ...
Installing new version of config file /etc/debian_version ...
(Reading database ... 19150 files and directories currently installed.)
Preparing to unpack .../bash_5.2.15-2+b7_amd64.deb ...
Unpacking bash (5.2.15-2+b7) over (5.2.15-2+b2) ...
 \Setting up bash (5.2.15-2+b7) ...
update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
(Reading database ... 19150 files and directories currently installed.)
Preparing to unpack .../bsdutils_1%3a2.38.1-5+deb12u1_amd64.deb ...
Unpacking bsdutils (1:2.38.1-5+deb12u1) over (1:2.38.1-5+b1) ...
 |Setting up bsdutils (1:2.38.1-5+deb12u1) ...
(Reading database ... 19149 files and directories currently installed.)
Preparing to unpack .../libperl5.36_5.36.0-7+deb12u1_amd64.deb ...
Unpacking libperl5.36:amd64 (5.36.0-7+deb12u1) over (5.36.0-7) ...
 |Preparing to unpack .../perl_5.36.0-7+deb12u1_amd64.deb ...
Unpacking perl (5.36.0-7+deb12u1) over (5.36.0-7) ...
 /Preparing to unpack .../perl-base_5.36.0-7+deb12u1_amd64.deb ...
Unpacking perl-base (5.36.0-7+deb12u1) over (5.36.0-7) ...
 |Setting up perl-base (5.36.0-7+deb12u1) ...
(Reading database ... 19149 files and directories currently installed.)
Preparing to unpack .../perl-modules-5.36_5.36.0-7+deb12u1_all.deb ...
Unpacking perl-modules-5.36 (5.36.0-7+deb12u1) over (5.36.0-7) ...
 -Preparing to unpack .../libc6_2.36-9+deb12u7_amd64.deb ...
 \Unpacking libc6:amd64 (2.36-9+deb12u7) over (2.36-9+deb12u3) ...
 /Setting up libc6:amd64 (2.36-9+deb12u7) ...
(Reading database ... 19149 files and directories currently installed.)
Preparing to unpack .../tar_1.34+dfsg-1.2+deb12u1_amd64.deb ...
Unpacking tar (1.34+dfsg-1.2+deb12u1) over (1.34+dfsg-1.2) ...
 -Setting up tar (1.34+dfsg-1.2+deb12u1) ...
(Reading database ... 19149 files and directories currently installed.)
Preparing to unpack .../libsmartcols1_2.38.1-5+deb12u1_amd64.deb ...
Unpacking libsmartcols1:amd64 (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Setting up libsmartcols1:amd64 (2.38.1-5+deb12u1) ...
(Reading database ... 19148 files and directories currently installed.)
Preparing to unpack .../util-linux-extra_2.38.1-5+deb12u1_amd64.deb ...
Unpacking util-linux-extra (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Setting up util-linux-extra (2.38.1-5+deb12u1) ...
(Reading database ... 19147 files and directories currently installed.)
Preparing to unpack .../util-linux_2.38.1-5+deb12u1_amd64.deb ...
Unpacking util-linux (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
 \Setting up util-linux (2.38.1-5+deb12u1) ...
 |fstrim.service is a disabled or a static unit not running, not starting it.
(Reading database ... 19146 files and directories currently installed.)
Preparing to unpack .../libc-bin_2.36-9+deb12u7_amd64.deb ...
Unpacking libc-bin (2.36-9+deb12u7) over (2.36-9+deb12u3) ...
 /Setting up libc-bin (2.36-9+deb12u7) ...
(Reading database ... 19146 files and directories currently installed.)
Preparing to unpack .../mount_2.38.1-5+deb12u1_amd64.deb ...
Unpacking mount (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Preparing to unpack .../libnss-systemd_252.26-1~deb12u2_amd64.deb ...
Unpacking libnss-systemd:amd64 (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
 \Preparing to unpack .../libblkid1_2.38.1-5+deb12u1_amd64.deb ...
Unpacking libblkid1:amd64 (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Setting up libblkid1:amd64 (2.38.1-5+deb12u1) ...
(Reading database ... 19144 files and directories currently installed.)
Preparing to unpack .../libmount1_2.38.1-5+deb12u1_amd64.deb ...
Unpacking libmount1:amd64 (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Setting up libmount1:amd64 (2.38.1-5+deb12u1) ...
(Reading database ... 19143 files and directories currently installed.)
Preparing to unpack .../libseccomp2_2.5.4-1+deb12u1_amd64.deb ...
Unpacking libseccomp2:amd64 (2.5.4-1+deb12u1) over (2.5.4-1+b3) ...
Setting up libseccomp2:amd64 (2.5.4-1+deb12u1) ...
(Reading database ... 19142 files and directories currently installed.)
Preparing to unpack .../libssl3_3.0.13-1~deb12u1_amd64.deb ...
Unpacking libssl3:amd64 (3.0.13-1~deb12u1) over (3.0.11-1~deb12u1) ...
 \Preparing to unpack .../systemd-timesyncd_252.26-1~deb12u2_amd64.deb ...
Unpacking systemd-timesyncd (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
 |Preparing to unpack .../libpam-systemd_252.26-1~deb12u2_amd64.deb ...
Unpacking libpam-systemd:amd64 (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
Setting up libssl3:amd64 (3.0.13-1~deb12u1) ...
(Reading database ... 19142 files and directories currently installed.)
Preparing to unpack .../systemd_252.26-1~deb12u2_amd64.deb ...
Unpacking systemd (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
 /Preparing to unpack .../libsystemd-shared_252.26-1~deb12u2_amd64.deb ...
Unpacking libsystemd-shared:amd64 (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
 -Preparing to unpack .../libsystemd0_252.26-1~deb12u2_amd64.deb ...
Unpacking libsystemd0:amd64 (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
 \Setting up libsystemd0:amd64 (252.26-1~deb12u2) ...
Setting up libsystemd-shared:amd64 (252.26-1~deb12u2) ...
Setting up mount (2.38.1-5+deb12u1) ...
Setting up systemd (252.26-1~deb12u2) ...
(Reading database ... 19142 files and directories currently installed.)
Preparing to unpack .../systemd-sysv_252.26-1~deb12u2_amd64.deb ...
Unpacking systemd-sysv (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
 \Preparing to unpack .../libuuid1_2.38.1-5+deb12u1_amd64.deb ...
Unpacking libuuid1:amd64 (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Setting up libuuid1:amd64 (2.38.1-5+deb12u1) ...
(Reading database ... 19141 files and directories currently installed.)
Preparing to unpack .../00-libcryptsetup12_2%3a2.6.1-4~deb12u2_amd64.deb ...
 |Unpacking libcryptsetup12:amd64 (2:2.6.1-4~deb12u2) over (2:2.6.1-4~deb12u1) ...
Preparing to unpack .../01-libfdisk1_2.38.1-5+deb12u1_amd64.deb ...
Unpacking libfdisk1:amd64 (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Preparing to unpack .../02-libgssapi-krb5-2_1.20.1-2+deb12u2_amd64.deb ...
 /Unpacking libgssapi-krb5-2:amd64 (1.20.1-2+deb12u2) over (1.20.1-2+deb12u1) ...
Preparing to unpack .../03-libkrb5-3_1.20.1-2+deb12u2_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.20.1-2+deb12u2) over (1.20.1-2+deb12u1) ...
 -Preparing to unpack .../04-libkrb5support0_1.20.1-2+deb12u2_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.20.1-2+deb12u2) over (1.20.1-2+deb12u1) ...
Preparing to unpack .../05-libk5crypto3_1.20.1-2+deb12u2_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.20.1-2+deb12u2) over (1.20.1-2+deb12u1) ...
Preparing to unpack .../06-openssh-sftp-server_1%3a9.2p1-2+deb12u3_amd64.deb ...
Unpacking openssh-sftp-server (1:9.2p1-2+deb12u3) over (1:9.2p1-2+deb12u1) ...
 \Preparing to unpack .../07-openssh-server_1%3a9.2p1-2+deb12u3_amd64.deb ...
Unpacking openssh-server (1:9.2p1-2+deb12u3) over (1:9.2p1-2+deb12u1) ...
 |Preparing to unpack .../08-openssh-client_1%3a9.2p1-2+deb12u3_amd64.deb ...
Unpacking openssh-client (1:9.2p1-2+deb12u3) over (1:9.2p1-2+deb12u1) ...
 /Preparing to unpack .../09-postfix_3.7.11-0+deb12u1_amd64.deb ...
 \Unpacking postfix (3.7.11-0+deb12u1) over (3.7.6-0+deb12u2) ...
 |Preparing to unpack .../10-python3.11_3.11.2-6+deb12u2_amd64.deb ...
 /Unpacking python3.11 (3.11.2-6+deb12u2) over (3.11.2-6) ...
Preparing to unpack .../11-libpython3.11-stdlib_3.11.2-6+deb12u2_amd64.deb ...
Unpacking libpython3.11-stdlib:amd64 (3.11.2-6+deb12u2) over (3.11.2-6) ...
 \Preparing to unpack .../12-python3.11-minimal_3.11.2-6+deb12u2_amd64.deb ...
Unpacking python3.11-minimal (3.11.2-6+deb12u2) over (3.11.2-6) ...
 -Preparing to unpack .../13-libpython3.11-minimal_3.11.2-6+deb12u2_amd64.deb ...
Unpacking libpython3.11-minimal:amd64 (3.11.2-6+deb12u2) over (3.11.2-6) ...
 \Preparing to unpack .../14-libgnutls30_3.7.9-2+deb12u3_amd64.deb ...
Unpacking libgnutls30:amd64 (3.7.9-2+deb12u3) over (3.7.9-2) ...
 |Setting up libgnutls30:amd64 (3.7.9-2+deb12u3) ...
(Reading database ... 19140 files and directories currently installed.)
Preparing to unpack .../udev_252.26-1~deb12u2_amd64.deb ...
Unpacking udev (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
 -Preparing to unpack .../libudev1_252.26-1~deb12u2_amd64.deb ...
 \Unpacking libudev1:amd64 (252.26-1~deb12u2) over (252.17-1~deb12u1) ...
Setting up libudev1:amd64 (252.26-1~deb12u2) ...
(Reading database ... 19140 files and directories currently installed.)
Preparing to unpack .../usrmerge_37~deb12u1_all.deb ...
Unpacking usrmerge (37~deb12u1) over (35) ...
 |Setting up perl-modules-5.36 (5.36.0-7+deb12u1) ...
Setting up libperl5.36:amd64 (5.36.0-7+deb12u1) ...
Setting up perl (5.36.0-7+deb12u1) ...
Setting up usrmerge (37~deb12u1) ...
removed '/lib32'
rmdir: removing directory, '/usr/lib32'
 /removed '/libx32'
rmdir: removing directory, '/usr/libx32'
(Reading database ... 19140 files and directories currently installed.)
Preparing to unpack .../00-tzdata_2024a-0+deb12u1_all.deb ...
 -Unpacking tzdata (2024a-0+deb12u1) over (2023c-5) ...
 -Preparing to unpack .../01-fdisk_2.38.1-5+deb12u1_amd64.deb ...
Unpacking fdisk (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
Preparing to unpack .../02-less_590-2.1~deb12u2_amd64.deb ...
Unpacking less (590-2.1~deb12u2) over (590-2) ...
 \Preparing to unpack .../03-nano_7.2-1+deb12u1_amd64.deb ...
Unpacking nano (7.2-1+deb12u1) over (7.2-1) ...
 |Preparing to unpack .../04-libuv1_1.44.2-1+deb12u1_amd64.deb ...
Unpacking libuv1:amd64 (1.44.2-1+deb12u1) over (1.44.2-1) ...
Preparing to unpack .../05-libnghttp2-14_1.52.0-1+deb12u1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.52.0-1+deb12u1) over (1.52.0-1) ...
 /Preparing to unpack .../06-bind9-dnsutils_1%3a9.18.24-1_amd64.deb ...
Unpacking bind9-dnsutils (1:9.18.24-1) over (1:9.18.19-1~deb12u1) ...
Preparing to unpack .../07-bind9-host_1%3a9.18.24-1_amd64.deb ...
Unpacking bind9-host (1:9.18.24-1) over (1:9.18.19-1~deb12u1) ...
Preparing to unpack .../08-bind9-libs_1%3a9.18.24-1_amd64.deb ...
Unpacking bind9-libs:amd64 (1:9.18.24-1) over (1:9.18.19-1~deb12u1) ...
 \Preparing to unpack .../09-krb5-locales_1.20.1-2+deb12u2_all.deb ...
Unpacking krb5-locales (1.20.1-2+deb12u2) over (1.20.1-2+deb12u1) ...
Preparing to unpack .../10-libc-l10n_2.36-9+deb12u7_all.deb ...
Unpacking libc-l10n (2.36-9+deb12u7) over (2.36-9+deb12u3) ...
 |Preparing to unpack .../11-locales_2.36-9+deb12u7_all.deb ...
Unpacking locales (2.36-9+deb12u7) over (2.36-9+deb12u3) ...
 |Preparing to unpack .../12-bsdextrautils_2.38.1-5+deb12u1_amd64.deb ...
Unpacking bsdextrautils (2.38.1-5+deb12u1) over (2.38.1-5+b1) ...
 /Preparing to unpack .../13-distro-info-data_0.58+deb12u2_all.deb ...
Unpacking distro-info-data (0.58+deb12u2) over (0.58) ...
Preparing to unpack .../14-libcurl3-gnutls_7.88.1-10+deb12u6_amd64.deb ...
Unpacking libcurl3-gnutls:amd64 (7.88.1-10+deb12u6) over (7.88.1-10+deb12u3) ...
 -Preparing to unpack .../15-openssl_3.0.13-1~deb12u1_amd64.deb ...
Unpacking openssl (3.0.13-1~deb12u1) over (3.0.11-1~deb12u1) ...
 |Preparing to unpack .../16-python3-idna_3.3-1+deb12u1_all.deb ...
 /Unpacking python3-idna (3.3-1+deb12u1) over (3.3-1) ...
 -Preparing to unpack .../17-ssh_1%3a9.2p1-2+deb12u3_all.deb ...
Unpacking ssh (1:9.2p1-2+deb12u3) over (1:9.2p1-2+deb12u1) ...
Setting up systemd-sysv (252.26-1~deb12u2) ...
Setting up libc-l10n (2.36-9+deb12u7) ...
Setting up bsdextrautils (2.38.1-5+deb12u1) ...
Setting up distro-info-data (0.58+deb12u2) ...
Setting up libnghttp2-14:amd64 (1.52.0-1+deb12u1) ...
Setting up less (590-2.1~deb12u2) ...
 \Setting up libnss-systemd:amd64 (252.26-1~deb12u2) ...
Setting up krb5-locales (1.20.1-2+deb12u2) ...
Setting up locales (2.36-9+deb12u7) ...
 \Generating locales (this might take a while)...
 | done.UTF-8...
Generation complete.
Setting up libkrb5support0:amd64 (1.20.1-2+deb12u2) ...
Setting up tzdata (2024a-0+deb12u1) ...
 /
Current default time zone: 'Europe/Berlin'
Local time is now:      Wed Jul 10 11:01:22 CEST 2024.
Universal Time is now:  Wed Jul 10 09:01:22 UTC 2024.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up libuv1:amd64 (1.44.2-1+deb12u1) ...
 -Setting up systemd-timesyncd (252.26-1~deb12u2) ...
 /Setting up udev (252.26-1~deb12u2) ...
 /Setting up python3-idna (3.3-1+deb12u1) ...
 -Setting up libk5crypto3:amd64 (1.20.1-2+deb12u2) ...
Setting up libfdisk1:amd64 (2.38.1-5+deb12u1) ...
Setting up postfix (3.7.11-0+deb12u1) ...
 |
Postfix (main.cf) configuration was untouched.  If you need to make changes, 
edit /etc/postfix/main.cf (and others) as needed.  To view Postfix 
configuration values, see postconf(1).

After modifying main.cf, be sure to run 'systemctl reload postfix'.

 \Setting up nano (7.2-1+deb12u1) ...
Installing new version of config file /etc/nanorc ...
Setting up libpam-systemd:amd64 (252.26-1~deb12u2) ...
 /Setting up libcryptsetup12:amd64 (2:2.6.1-4~deb12u2) ...
Setting up libkrb5-3:amd64 (1.20.1-2+deb12u2) ...
Setting up libpython3.11-minimal:amd64 (3.11.2-6+deb12u2) ...
Setting up openssl (3.0.13-1~deb12u1) ...
Setting up python3.11-minimal (3.11.2-6+deb12u2) ...
 -Setting up libpython3.11-stdlib:amd64 (3.11.2-6+deb12u2) ...
Setting up fdisk (2.38.1-5+deb12u1) ...
Setting up libgssapi-krb5-2:amd64 (1.20.1-2+deb12u2) ...
Setting up python3.11 (3.11.2-6+deb12u2) ...
 |Setting up bind9-libs:amd64 (1:9.18.24-1) ...
Setting up openssh-client (1:9.2p1-2+deb12u3) ...
Setting up libcurl3-gnutls:amd64 (7.88.1-10+deb12u6) ...
 /Setting up bind9-host (1:9.18.24-1) ...
Setting up openssh-sftp-server (1:9.2p1-2+deb12u3) ...
Setting up openssh-server (1:9.2p1-2+deb12u3) ...
 \rescue-ssh.target is a disabled or a static unit not running, not starting it.
 -Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 145.
 \Setting up bind9-dnsutils (1:9.18.24-1) ...
Setting up ssh (1:9.2p1-2+deb12u3) ...
Processing triggers for systemd (252.26-1~deb12u2) ...
Processing triggers for man-db (2.11.2-2) ...
 |Processing triggers for dbus (1.14.10-1~deb12u1) ...
Processing triggers for debianutils (5.7-0.5~deb12u1) ...
 /Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for libc-bin (2.36-9+deb12u7) ...
 ✓ Updated Container OS
Reading package lists... Doneatience)   
Building dependency tree... Done
Reading state information... Done
Package libtbb2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtbbmalloc2

E: Package 'libtbb2' has no installation candidate
E: Unable to locate package libdc1394-22-dev

[ERROR] in line 17: exit code 0: while executing command $STD apt-get install -y {curl,sudo,mc,git,gpg,automake,build-essential,xz-utils,libtool,ccache,pkg-config,libgtk-3-dev,libavcodec-dev,libavformat-dev,libswscale-dev,libv4l-dev,libxvidcore-dev,libx264-dev,libjpeg-dev,libpng-dev,libtiff-dev,gfortran,openexr,libatlas-base-dev,libssl-dev,libtbb2,libtbb-dev,libdc1394-22-dev,libopenexr-dev,libgstreamer-plugins-base1.0-dev,libgstreamer1.0-dev,gcc,gfortran,libopenblas-dev,liblapack-dev,libusb-1.0-0-dev,jq}

### Please provide detailed steps to reproduce the issue.

install

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
