### ISSUE TITLE
Frigate bundled go2rtc doesn't persist configuration changes across LXC restarts

### ISSUE THREAD

**Issue by willgryan** [tteck/Proxmox#3369]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After making changes to the go2rtc configuration using the go2rtc config file editor @ ip_address:1984/editor.html, they don't persist after the Frigate LXC container restarts. 

go2rtc reports the configuration path is /dev/shm/go2rtc.yaml, which seems to imply it is being placed by default in the wrong location

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

1. Install Frigate LXC
2. Add stream to go2rtc using the go2rtc browser-based config file editor, then click "Save & Restart" on webpage
3. Verify stream can be viewed in go2rtc
5. Restart Frigate LXC
6. go2rtc configuration is now reset to default values

**Comment by tteck** [comment]
I don't utilize Frigate, so we'll have to wait for someone who does to chime in.
