### ISSUE TITLE
Grafana Update dont work

### ISSUE THREAD

**Issue by R-Rosenow** [tteck/Proxmox#3378]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I want to update my grafana lxc, but there is an error.

The solution in the error warning dosn#t help.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`   ______           ____                 
  / ____/________ _/ __/___ _____  ____ _
 / / __/ ___/ __  / /_/ __  / __ \/ __  /
/ /_/ / /  / /_/ / __/ /_/ / / / / /_/ / 
\____/_/   \__,_/_/  \__,_/_/ /_/\__,_/  
 
 - Updating Grafana   
[ERROR] in line 60: exit code 0: while executing command apt-get -y upgrade &> /dev/null

root@grafana:~# 

`

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
