### ISSUE TITLE
Unifi Network Controller Update 

### ISSUE THREAD

**Issue by mwckr** [tteck/Proxmox#3381]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Unifi Network Controller has been updated to 8.3.32, but the script still installs 8.2.93.
Release notes: https://community.ui.com/releases/UniFi-Network-Application-8-3-32/54f3b506-afcf-4a7c-aba6-01a884dd9003

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Update prompt in the application:
![Bildschirmfoto](https://github.com/user-attachments/assets/97986596-2201-4a19-847e-6b8cb945fa3e)

No new update in the LXC console when running the update script:
![Bildschirmfoto 1](https://github.com/user-attachments/assets/cd745b9e-6ec1-4ee9-be6a-093c9c8f5282)

### Please provide detailed steps to reproduce the issue.

1. Paste the update script (bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/unifi.sh)") into the LXC console
2. Confirm "yes" on dialogue prompt
3. Wait for the script to finish
4. No update available

**Comment by tteck** [comment]
UniFi Network Server is installed and updated via their apt repositories. 

https://github.com/tteck/Proxmox/blob/e3da97472e64584846fae33b8b2c572000efa85b/install/unifi-install.sh#L38-L43

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by mwckr** [comment]
> UniFi Network Server is installed and updated via their apt repositories.
> 
> https://github.com/tteck/Proxmox/blob/e3da97472e64584846fae33b8b2c572000efa85b/install/unifi-install.sh#L38-L43
> 
> 🧐 As this issue is unrelated to the script, it is considered closed.

Hi,

thanks for the swift reply. 

Just so I fully understand, that means that their repository hasn't been updated so the script can't find the update file, or am I supposed to do something in particular?

Thank you.

**Comment by chenks** [comment]
it would appear that unifi haven't updated their repository, which is strange considering it was released 6 days ago

**Comment by chenks** [comment]
> UniFi Network Server is installed and updated via their apt repositories.

can you confirm nothing has changed in terms of where the file is actually located?

on the UI page the update is listed at https://dl.ui.com/unifi/8.3.32/unifi_sysvinit_all.deb

in your script it refers to https://www.ui.com/downloads/unifi/debian however that results in a 404 error

**Comment by tteck** [comment]
Their repository is fine, just not up to date. File an issue with them.

If you're that impatient, update manually.

```
wget -q https://dl.ui.com/unifi/8.3.32/unifi_sysvinit_all.deb
dpkg -i unifi_sysvinit_all.deb
rm unifi_sysvinit_all.deb
```

**Comment by chenks** [comment]
> If you're that impatient, update manually.

it was more about checking that nothing had changed making your script out of date (ie the 404 link that results from the URL mentioned in the script.

patient/impatient has nothing to do with it.

**Comment by tteck** [comment]
As I stated, their repository is good. No issues with the script.

**Comment by chenks** [comment]
the repository has now been updated

**Comment by Scoff123** [comment]
I've also just tested this and can confirm the repo has been updated - the update and upgrade command results in this:

![image](https://github.com/user-attachments/assets/c450062d-1d01-44e6-83a0-772bafdc2901)
