### ISSUE TITLE
Handling of non-latin characters in LXC

### ISSUE THREAD

**Issue by arteee87** [tteck/Proxmox#3386]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I only tested this for qbittorrent script
Issue: because of LANG="C" in  /etc/default/locale, non-latin characters are cannot be used in paths or file names.
Fix: set LANG="en_US.UTF-8" in /etc/default/locale at the time of the creation of the LXC

LXC container created by the qbittorrent script is unable access any path with cyrillic symbols - every cyrillic symbol is replaced with "."
In terminal, cyrillic chars are replaced with their unicode id's

I've found this issue with qbittorrent - [issue 16127](https://github.com/qbittorrent/qBittorrent/issues/16127)
but it is fixed since 4.6.3.
Yet, after manually updating the qbittorrent to 4.6.5 did not fix the behavior.

Issue is present in both debian 12 LXC, ubuntu 24.04 (had to switch to due to the dependencies for qbittorrent 4.6.5)
Fix is the same for both.

Changing LANG="C" to LANG="en_US.UTF-8" in /etc/default/locale did fix the issue.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

1) make a qbittorrent lxc with the script in advanced mode for the root access
2) add a torrent with a cyrillic letters in the path/files - for example [this one](https://drive.google.com/file/d/1lfxGD-4qG-t8cFNVEsUcBc4fLxKBy4Rh/view?usp=sharing)
3) start loading it - dont have to wait for a full download - check your download dir - you'll have the "." instead of the correct characters.
4) change LANG="C" to LANG="en_US.UTF-8" in /etc/default/locale and reboot the container
5) delete the downloaded "..." dir, force re-check files in qbittorrent and start the download again
6) Path/files will have the correct characters.

**Comment by tteck** [comment]
The script sets the LXC `LANG` to whatever the host `$LANG` variable is.
https://github.com/tteck/Proxmox/blob/bf40c30fffee07424aba152aba05aa6403089725/misc/install.func#L88-L92

e.g.
```
root@server:~# echo "$LANG"
en_US.UTF-8
root@server:~# 
```

**Comment by tteck** [comment]
I'll check if this has changed.

**Comment by arteee87** [comment]
I have it set in proxmox host (did not manually edit /etc/default/locale)


![Снимок экрана 2024-07-16 174249](https://github.com/user-attachments/assets/9398d0c1-0257-4918-8e37-38aad9087950)

**Comment by tteck** [comment]
Working on...

**Comment by tteck** [comment]
Fixed

**Comment by tteck** [comment]
You can execute the following snippet in any other LXC console that is affected by this bug

```
locale_line=$(grep -v '^#' /etc/locale.gen | grep -E '^[a-zA-Z]' | awk '{print $1}' | head -n 1)
echo "LANG=${locale_line}" >/etc/default/locale
export LANG=${locale_line}
```
You can check by executing `locale` before and after
