### ISSUE TITLE
Webmin Install works, but Webmin Update fails

### ISSUE THREAD

**Issue by DrSchnagels** [tteck/Proxmox#339]
Hi there!
I tried your Webmin script on my Proxmox install today.
It installed an outdated version of webmin and it worked. But Webmin updated and then it failed to load again correctly.
Could you check this issue? 

Thanks a lot in advance,
Michael

**Comment by tteck** [comment]
Don't understand what the problem could be with updating 🤷🏻‍♂️ 
I updated the script to install the newest version (1.996) 
I'd uninstall Webmin (`bash /etc/webmin/uninstall.sh`) and reinstall
