### ISSUE TITLE
iVentoy script doesn't doesn't work on unprivileged container.

### ISSUE THREAD

**Issue by officiallymarky** [tteck/Proxmox#3390]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

I am not sure if this is a known issue, but I tried the install a few times and just tried privileged for science, and it worked.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

n/a

### Please provide detailed steps to reproduce the issue.

Default install works fine.

Advanced only works if you use privileged.

**Comment by tteck** [comment]
It only works privileged. It's not an issue. 

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by officiallymarky** [comment]
Might be a good idea to put a note on the description to say it's required.

Thanks for all your work, I love your scripts.

**Comment by kiguy2052** [comment]
I have to agree, it would have made solving this a lot easier if there was a note in the description for advanced mode users

**Comment by hogdanish** [comment]
> Might be a good idea to put a note on the description to say it's required.

Agreed, was scratching my head why the web interface kept giving me a ERR_CONNECTION_REFUSED error. I wouldn't otherwise know how to troubleshoot it if I hadn't stumbled across this issue.
