### ISSUE TITLE
Hardware Acceleration doesn't work because of inccorect chown of renderD128

### ISSUE THREAD

**Issue by vitstr** [tteck/Proxmox#3392]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Long story short:
After installing Jellyfin via a script from the repo and once I enabled hardware acceleration with QSV value (it's relevant for VAAPI as well) I found that I started getting errors in the logs like this:

```
[2024-07-17 02:25:47.505 +03:00] [ERR] FFmpeg exited with code 1
[2024-07-17 02:25:47.604 +03:00] [ERR] Error processing request. URL "GET" "/videos/6fb58150-1a2e-d9ff-b484-1df988fdf426/hls1/main/0.ts".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
```
During debugging, I found that the `renderD128` has an incorrect chown value and due to this I can run it with root claims only.

Before:
```
crw-rw---- 1 root _ssh 226, 128 Jul 15 00:30 renderD128
```

After:
```
crw-rw---- 1 root render 226, 128 Jul 15 00:30 renderD128
```

So, If anybody experiences the same problem I had, just run the command as root to fix the issue:
```bash
chown root:render /dev/dri/renderD128
```

PS: I don't know if the problem comes with the script from the repo, the problem may be on the jellyfin end. Just FYI.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### Please provide detailed steps to reproduce the issue.

- Install jellyfin in unprivileged LXC container
- Use the initial settings by default
- Enable hardware acceleration with QSV value
- Try to watch any movie with a device that doesn't support the current movie's format

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
