### ISSUE TITLE
Pi-Hole LXC Fails no DHCP 

### ISSUE THREAD

**Issue by tmanok** [tteck/Proxmox#34]
Hi Tteck,

Your Pi-Hole script interests me, I believe that you should add a section to your script to allow the user to manually configure the network for environments without DHCP. Otherwise the container fails to install. 

Cheers,

Tmanok

**Comment by tteck** [comment]
Sorry, 5 red X's isn't fun to see, but I _think_ very few use static routing without the use of dynamic routing upfront.

**Comment by tmanok** [comment]
Hi Tteck,

Ok, do you have any recommendations for how to edit the script manually for static IP configuration?
Cheers,

Tmanok

**Comment by tteck** [comment]
On line 146 of the `pihole_container.sh` you'll find `ip=dhcp`, available options are ip=(IPv4/CIDR|dhcp|manual)

**Comment by tmanok** [comment]
Perfect, thank you very much Tteck. 

Tmanok
