### ISSUE TITLE
Netbird error - no gpg key or sources.list.d

### ISSUE THREAD

**Issue by twist3dimages** [tteck/Proxmox#3401]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Even after adding Netbird's gpg key, i get the following message

```
Installing NetBird...
bash: line 3: /usr/share/keyrings/netbird-archive-keyring.gpg: No such file or directory
wget: write error: Broken pipe
bash: line 4: /etc/apt/sources.list.d/netbird.list: No such file or directory

```
### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/da69996b-9ede-4644-a5ef-2fef0a60e00b)

### Please provide detailed steps to reproduce the issue.

1) Run bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/add-netbird-lxc.sh)"
2) Select container to apply it to
3) Get this error
```
Installing NetBird...
bash: line 3: /usr/share/keyrings/netbird-archive-keyring.gpg: No such file or directory
wget: write error: Broken pipe
bash: line 4: /etc/apt/sources.list.d/netbird.list: No such file or directory

```

**Comment by tteck** [comment]
Probably won't work with Debian 11. Why Debian 11?

```
    _   __     __  ____  _          __
   / | / /__  / /_/ __ )(_)________/ /
  /  |/ / _ \/ __/ __  / / ___/ __  /
 / /|  /  __/ /_/ /_/ / / /  / /_/ /
/_/ |_/\___/\__/_____/_/_/   \__,_/

Installing NetBird...
 ✔ Installed NetBird.
 Reboot 111 LXC to apply the changes, then run netbird up in the LXC console
```

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by twist3dimages** [comment]
I'm not sure, it's whatever the default Proxmox is

**Comment by twist3dimages** [comment]
How would I go about fixing this if it's my system?

I'm not sure how it's not a script issue.... I already told you I added the gpg key via the terminal using
```
curl -sSL https://pkgs.netbird.io/debian/public.key | sudo gpg --dearmor --output /usr/share/keyrings/netbird-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/netbird-archive-keyring.gpg] https://pkgs.netbird.io/debian stable main' | sudo tee /etc/apt/sources.list.d/netbird.list
```

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/1498

**Comment by twist3dimages** [comment]
I'm on 12 then, which part of that am I supposed to look at?
