### ISSUE TITLE
Trouble with ErsatzTV update

### ISSUE THREAD

**Issue by jvonhoff** [tteck/Proxmox#3404]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the update script for ErsatzTV, it borks the installation.  I believe the offending lines are here:
```
if [ -d /opt/ErsatzTV/ErsatzTV_bak ]; then
  rm -rf /opt/ErsatzTV/ErsatzTV_bak
fi
mv /opt/ErsatzTV/ErsatzTV /opt/ErsatzTV/ErsatzTV_bak
wget -qO- "https://github.com/ErsatzTV/ErsatzTV/releases/download/${RELEASE}/ErsatzTV-${RELEASE}-linux-x64.tar.gz" | tar -xz -C /opt
mv "/opt/ErsatzTV-${RELEASE}-linux-x64" /opt/ErsatzTV
msg_ok "Updated ErsatzTV"

```

I believe lines 1, 2 & 4 above should have the first instance of "ErsatzTV" removed (/opt/ErsatzTV/ErsatzTV --> /opt/ErsatzTV) since I think the exercise is to rename `/opt/ErsatzTV` to be `/opt/ErsatzTV_bak` and then to unzip the newly-downloaded RELEASE folder as the new `/opt/ErsatzTV`.  Forgive me if I'm mistaken.

As written, line 4 appears to move the ErsatzTV _executable_ to the _bak, and then the `mv` on line 6 fails because you're moving the RELEASE folder over a non-empty `/opt/Ersatz`.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

* Install ErsatzTV using the script from Proxmox console.
* Inside the ErsatzTV LXC, run `update`

**Comment by tteck** [comment]
I will refactor the code
