### ISSUE TITLE
force locale of update scripts to avoid warnings and errors

### ISSUE THREAD

**Issue by alberanid** [tteck/Proxmox#3405]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Relying on host (Proxmox's) locale settings may produce warning in the output of the `update-lxcs-cron.sh` and `update-lxcs.sh` scripts.

For example, if the Proxmox host has the **LANG=it_IT.UTF-8** environment variable set (and the related locale was generated running `dpkg-reconfigure locales`), you may receive warnings like that when running `update-lxcs-cron.sh` from a cron job:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "it_IT.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

Similar warnings may appear if some _postinst_ deb script runs a perl script, for example (there are surely other cases).

**A more serious problem** could arise if the same locale is also set in the LXC and that would also change the output language of command like `apt-get update` and then the `grep` commands could fail and prevent the LXC update.

A possible, simple, solution is to just set the **LC_ALL=C** environment variable at the begin of those commands.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

**Comment by tteck** [comment]
I have not had any issues with updates giving warnings.
If `LC_ALL` is set, it will override all of the locale settings. 

What is the output of the command `locale`?

**Comment by tteck** [comment]
```
root@ubuntu-24:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
root@ubuntu-24:~# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-security InRelease
Reading package lists... Done
root@ubuntu-24:~# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ubuntu-24:~# 
```
The Proxmox VE LXC Updater script shows no warnings either.

**Comment by alberanid** [comment]
@tteck on a Proxmox host with LC_ALL set to it_IT.UTF-8, executing a command on a LXC that also has the same locale I observe:

```
#  pct exec 129 -- locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=it_IT.UTF-8
```

To make it clear why it can break the grep:

```
#  pct exec 129 -- bash -c 'apt update'
Trovato:1 http://archive.ubuntu.com/ubuntu noble InRelease
Scaricamento di:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Trovato:3 http://archive.ubuntu.com/ubuntu noble-security InRelease
Scaricamento di:4 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [266 kB]
Scaricamento di:5 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [301 kB]
Recuperati 693 kB in 1s (1.333 kB/s)
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
45 pacchetti possono essere aggiornati: eseguire "apt list --upgradable" per vederli.
```

As you can see the messages are in Italian, and the grep for `packages.*upgraded` would fail.

**EDIT TO EXPAND THE ANSWER:** the warnings, which are obviously less important, are not shown at every run, but only if some package is really updated and only if their postinst (or other) scripts run Perl or other programs that emit similar warnings about the locale.

**Comment by tteck** [comment]
Trying to understand because no one else has brought up this issue.
In your case, `LC_ALL=it_IT.UTF-8` is overriding `LANG=en_US.UTF-8` Have you tried `LC_ALL=`?

**Comment by tteck** [comment]
On my Proxmox host

```
root@server:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
root@server:~#
```

**Comment by tteck** [comment]
I don' t believe that a script change is necessary.
In your case, since you are using `LC_ALL=it_IT.UTF-8`:
```
pct exec 129 -- bash -c 'export LC_ALL=C.UTF-8 && apt update'
```

**Comment by alberanid** [comment]
> Trying to understand because no one else has brought up this issue

I think it's quite rare to change the locale of the Proxmox host.

To better clarify the situation, we have two issue:

1. the warnings are due to any mismatch between the locale set on the host and the one present on the LXC  (it may also happen if the host is set to en_US.UTF-8 and the LXC has the default C value) and are shown only when some specific packages are updated, triggering some Perl scripts and maybe other programs. In general, they are no big deal, just warnings that the LXC does not support the locale that was passed by the pct enter command.
2. what I called the "grep problem", which is triggered if a non-English language is set on the host and is also available in the LXC; I've looked again at the code and luckily it's less critical than I thought. You run `apt-get update 2>/dev/null | grep 'packages.*upgraded'; apt-get upgrade [...]` inside the LXC. I thought the two commands where separated by `&&`, but fortunately there's a `;`. So, if both the host and LXC are - for example - set to it_IT.UTF-8, you will get the output in Italian, and the grep will return nothing. As said, fortunately that just means that you will not have any output, but the update process goes on anyway.

> Have you tried `LC_ALL=`?

Yes, sure: if the host and all the LXCs have the same settings regarding the locale, you will have no warnings but you may still face the "grep" problem as described above.

In general, my point is: if you are running commands inside the LXC (especially commands that expects output in a specific language, like your grep), it would be better if the locale environment of the host is not passed to the LXC. For this reason, setting LC_ALL=C would be the reasonable thing to do.
