### ISSUE TITLE
SABnzbd upgarde not working

### ISSUE THREAD

**Issue by GHMCr** [tteck/Proxmox#3410]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

This the error when running:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/sabnzbd.sh)"

in the LXC container:

- Updating SABnzbd   
[ERROR] in line 65: exit code 0: while executing command python3 -m pip install -r requirements.txt &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/3300

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by GHMCr** [comment]
I originally created this LXC with the script.

**Comment by tteck** [comment]
Good, now follow the instructions in https://github.com/tteck/Proxmox/discussions/3300
