### ISSUE TITLE
Sonarr lxc not updating

### ISSUE THREAD

**Issue by GHMCr** [tteck/Proxmox#3411]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

when running: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/sonarr.sh)"

in the LXC i get an error:  ✗ No Sonarr Installation Found!

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
That suggests that you don't have the directory `/opt/Sonarr`
https://github.com/tteck/Proxmox/blob/80fb3ee841717c94088d9cb77bbaaf8c43186a88/ct/sonarr.sh#L57

**Comment by tteck** [comment]
```
   _____
  / ___/____  ____  ____  __________
  \__ \/ __ \/ __ \/ __ `/ ___/ ___/
 ___/ / /_/ / / / / /_/ / /  / /
/____/\____/_/ /_/\__,_/_/  /_/

 ✓ Updated Sonarr v4
```

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by GHMCr** [comment]
The LXC was created with this script (in january) and Sonarr is running. It is an older version thopugh an I want to update it.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/main/CHANGELOG.md#2024-01-03

**Comment by chenks** [comment]
> The LXC was created with this script (in january) and Sonarr is running. It is an older version thopugh an I want to update it.

you can update sonarr from with the app itself using the built-in update.
i've used that method since installing the LXC using the script.

not sure why you'd need to try and update from the command line.
