### ISSUE TITLE
[Keycloak] Problem with fresh installation

### ISSUE THREAD

**Issue by SyFizz** [tteck/Proxmox#3417]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,

On Proxmox VE 8.2.4, creating a Keycloak LXC works, but the software is broken.
It's impossible to create a Client or to go in the "Authentication" page.

On the "Authentication" page, the error is `Danger alert:Cannot read properties of undefined (reading 'find')`
When trying to create a OIDC client, the error is `Cannot read properties of undefined (reading 'login-protocol')`

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/bd976f2c-043b-4180-bf9c-94753e94b66c)
![image](https://github.com/user-attachments/assets/7ab2e3dd-76fe-4029-9205-8f6c87618a33)

### Please provide detailed steps to reproduce the issue.

1. Create a fresh Keycloak LXC with the script
2. Login with the admin/changeme combination
3. Try to click on "Authentication" button under "Configure" section or try to click on "Create" button, within the "Clients" page.

**Comment by tteck** [comment]
> Login with the admin/changeme combination

Where did you find this information?

**Comment by SyFizz** [comment]
> Where did you find this information?

You wrote it on #2922 
Yes, i could change it when executing the commands, but i kept it like that for testing purposes.

**Comment by tteck** [comment]
I can't get that far, installed three times. 🤷🏻‍♂️ 

![Screenshot 2024-07-23 10 37 15 AM](https://github.com/user-attachments/assets/582099e1-d2ac-4a1c-b5c7-e65684d06e77)

**Comment by SyFizz** [comment]
Because the default page after installation is /auth, you need to go to /admin

I installed version 21.0.2, this one works fine.

**Comment by tteck** [comment]
Can it be upgraded via the Keycloak GUI?

**Comment by tteck** [comment]
Thanks for the tip, I need to note that! All tabs seem to work for me.

![Screenshot 2024-07-23 11 38 44 AM](https://github.com/user-attachments/assets/2f2d8720-ee34-4d9e-bee4-d7f2157a1b20)
![Screenshot 2024-07-23 11 34 16 AM](https://github.com/user-attachments/assets/40731584-81d7-4031-a2a8-291360859953)
![Screenshot 2024-07-23 11 34 51 AM](https://github.com/user-attachments/assets/2ec0411b-3d37-4c60-a36d-2c20e91f3d61)
![Screenshot 2024-07-23 11 36 23 AM](https://github.com/user-attachments/assets/c0530d14-7ba4-4007-8474-2f9d42367a80)

**Comment by SyFizz** [comment]
How do you access it ?
Is it via localhost or via external IP ?

**Comment by tteck** [comment]
`IP:8080/admin`

**Comment by tteck** [comment]
Documentation updated.
