### ISSUE TITLE
Frigate - libtbb2 deprecated 

### ISSUE THREAD

**Issue by AlexTryHarder** [tteck/Proxmox#3420]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Tried both Ubuntu and Debian

Reading package lists... Doneatience)   
Building dependency tree... Done
Reading state information... Done
 -Package libtbb2 is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtbbmalloc2

E: Package 'libtbb2' has no installation candidate
E: Unable to locate package libdc1394-22-dev

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 20.04

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
