### ISSUE TITLE
Error during script run

### ISSUE THREAD

**Issue by Serhioromano** [tteck/Proxmox#3421]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I install Frigate and at the end I have

```
| Installing Openvino Object Detection Model (Resilience)   
[ERROR] in line 115: exit code 0: while executing command wget -q https://github.com/openvinotoolkit/open_model_zoo/raw/master/data/dataset_classes/coco_91cl_bkgr.txt -O openvino-model/coco_91cl_bkgr.txt
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by tteck** [comment]
Post issues in https://github.com/tteck/Proxmox/discussions/2711
