### ISSUE TITLE
NPM Update / Upgrade failed

### ISSUE THREAD

**Issue by Stoony1** [tteck/Proxmox#3429]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Guten Abend, ich nutze seit lagen den NPM, und wollte gestern Abend Updaten / Upgraden. 
Leider Kommt die auf den Screenshoot zu sehende Fehlermeldung, und der NPM ist danach nicht mehr erreichbar auch Reboot etc hilft nicht. Im LOG habe ich auch keine Infos gefunden die irgendwas Aussagen. 

![npm by tteck update fehler](https://github.com/user-attachments/assets/b7d60489-fd35-414d-9f09-3db10ab65982)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/3300

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/3311

🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by Stoony1** [comment]
Hat funktioniert vielen lieben dank.
