### ISSUE TITLE
SABnzbd install failing due to "no network connection"

### ISSUE THREAD

**Issue by BurntIce16** [tteck/Proxmox#3430]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The SABnzbd install script fails once attempting to verify a network connection. However, after installation has failed the container can ping various hosts successfully. While the network test is running the host machine is also able to ping a variety of hosts successfully. Verbose mode presents no additional insights.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![SABnzbd error](https://github.com/user-attachments/assets/39f6beb7-b519-4800-8dd8-a9b79ad635a3)

![SABnzbd ping](https://github.com/user-attachments/assets/1513e624-4a61-4ae1-9eed-39fe810fbe0c)

### Please provide detailed steps to reproduce the issue.

Run the install script with default settings.

**Comment by Mellowlynx** [comment]
Runs fine for me.
![image](https://github.com/user-attachments/assets/005a1750-da5b-40e9-af28-55b8b611fe77)

The ping you shared looks like from your PVE host, not the LXC, and it looks like the LXC has no connection.
Also, is **mediaLibrary** a local storage of some kind of network share? The LXC should be run from local storage.

**Comment by tteck** [comment]
That says No Network not No Internet. Looks like it is not being assigned an IP address from your DHCP server.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by BurntIce16** [comment]
If this helps anyone else, it turned out to be a DHCP issue. For some reason, still to be determined, my DHCP server stops assigning IP addresses around midnight, which coincided with the timing of this issue. Running it the next morning worked perfectly.

Thanks for the help 👍
