### ISSUE TITLE
Paperless-ngx updating to v2.11.2 with errors

### ISSUE THREAD

**Issue by pafade89** [tteck/Proxmox#3447]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

 ✓ Stopped all Paperless-ngx Services
 / Updating to v2.11.2   
[ERROR] in line 81: exit code 0: while executing command pip install -r requirements.txt &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Updated OS before use "update" command

**Comment by pafade89** [comment]
I just noticed that version v2.11.2 was installed nevertheless.

**Comment by DevJulian1966** [comment]
Same here, did try your recommendation from:
https://github.com/tteck/Proxmox/issues/3308#issuecomment-2199723227

Now I get:
`[ERROR] in line 76: exit code 0: while executing command wget -q https://github.com/paperless-ngx/paperless-ngx/releases/download/$RELEASE/paperless-ngx-$RELEASE.tar.xz`
instead.

Update to v2.11.2 still successfull, after restarting the service.

**Comment by tteck** [comment]
There are no issues with the install script or the update function.

```
    ____                        __                                     
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/                                         /____/        
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: paperless-ngx
Using Disk Size: 10
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Paperless-ngx LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python3 Dependencies
 ✓ Installed OCR Dependencies
 ✓ Installed JBIG2
 ✓ Installed Paperless-ngx
 ✓ Installed Natural Language Toolkit
 ✓ Set up PostgreSQL database
Would you like to add Adminer? <y/N> 
 ✓ Set up admin Paperless-ngx User & Password
 ✓ Created Services
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Paperless-ngx should be reachable by going to the following URL.
         http://192.168.86.250:8000 
```
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by pafade89** [comment]
@DevJulian1966 Thank you, [this](https://github.com/tteck/Proxmox/issues/3308#issuecomment-2199723227) solve my Problem 

@tteck But now my paperless-ngx does not automatically start after a successful update.

**Comment by pafade89** [comment]
> @tteck But now my paperless-ngx does not automatically start after a successful update.

@tteck Can you help why paperless does not start automatically anymore?

After manually updating Debian, I followed the step in issue #3300, but now I'm encountering the problem.
