### ISSUE TITLE
Home assistant in Proxmox

### ISSUE THREAD

**Issue by ashoktvm** [tteck/Proxmox#3462]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I was trying to install Home Assistant OS VM in Proxmox VE 8.2.2. But I get the below message
bash: line 22: pvesh: command not found
environment: line 118: pveversion: command not found
 ✗ This version of Proxmox Virtual Environment is not supported
Requires Proxmox Virtual Environment Version 8.1 or later.
Exiting..

What to do?

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by Nikishek** [comment]
I can confirm that from my side the script works. PVE 8.2.4.

**Comment by tteck** [comment]
Are you executing the install command in the Proxmox shell, or using SSH/Zsh?

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by ashoktvm** [comment]
> Are you executing the install command in the Proxmox shell, or using SSH/Zsh?

Proxmox shell
