### ISSUE TITLE
⚙️ **Initial Login**

### ISSUE THREAD

**Issue by jonm802** [tteck/Proxmox#3473]
⚙️ **Initial Login**
  
  The initial admin user can be added manually using the web frontend when accessed from localhost or automatically using environment variables.
  
  To add the initial admin user using environment variables, set <code class="highlighter-rouge">KEYCLOAK_ADMIN</code> for the initial admin username and <code class="highlighter-rouge">KEYCLOAK_ADMIN_PASSWORD</code> for the initial admin password.
  
  First, stop Keycloak
  ~~~bash
  systemctl stop keycloak.service
  ~~~
  then start Keycloak by coping & pasting the command below (only needed once)
  ~~~bash
  cd /opt/keycloak
  export KEYCLOAK_ADMIN=admin
  export KEYCLOAK_ADMIN_PASSWORD=changeme
  bin/kc.sh start-dev 
  ~~~

Then, go to `IP:8080/admin`

_Originally posted by @tteck in https://github.com/tteck/Proxmox/discussions/2922_

its not bin/kc.sh

should be 
/opt/keycloak/bin/kc.sh

**Comment by tteck** [comment]
If you're in the directory `/opt/keycloak`, what would it be? lol

🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
