### ISSUE TITLE
jellyseerr-install.sh npm error Override without name: sqlite3/node-gyp

### ISSUE THREAD

**Issue by Mikolaj-Walkowiak** [tteck/Proxmox#3476]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

yarn install throws this error,
 looking at the https://docs.jellyseerr.dev/getting-started/buildfromsource simply running 
` git checkout main`
before seems to fix it.

I've also used 
`CYPRESS_INSTALL_BINARY=0 yarn install --frozen-lockfile --network-timeout 1000000`
 but I don't think it fixed anything, because it also didn't work before checkout.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
`git checkout main` is already in the script https://github.com/tteck/Proxmox/blob/b66590f976ad2824a4d4474b332ac6bc7a66cec8/install/jellyseerr-install.sh#L43
Jellyseerr installs here with no issues. Depending on your machine, you may need to increase resources for the build process.

```
       __     ____
      / /__  / / /_  __________  ___  __________
 __  / / _ \/ / / / / / ___/ _ \/ _ \/ ___/ ___/
/ /_/ /  __/ / / /_/ (__  )  __/  __/ /  / /
\____/\___/_/_/\__, /____/\___/\___/_/  /_/
              /____/
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: jellyseerr
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Jellyseerr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Installed Jellyseerr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Jellyseerr should be reachable by going to the following URL.
         http://192.168.86.250:5055 
```

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by Mikolaj-Walkowiak** [comment]
Sorry, had to have some old version then. Thanks for answering :)

**Comment by tteck** [comment]
Just curious, what do you mean by "had to have some old version"?

**Comment by Mikolaj-Walkowiak** [comment]
Downloaded, since I didn't have those lines somehow.

**Comment by Mikolaj-Walkowiak** [comment]
Or maybe had a brain fart and started debugging myself too early seeing the git blame now :D
