### ISSUE TITLE
Default Settings for Nginx Proxy Manager LXC inconsistent

### ISSUE THREAD

**Issue by leonard2901** [tteck/Proxmox#3479]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

https://tteck.github.io/Proxmox/#nginx-proxy-manager-lxc

Nitpicking: The website states "Default Settings: 1GB RAM - 3GB Storage - 1vCPU" but the script actually configures 4GB Storage and 2 Cores:

> Using Disk Size: 4GB
> Allocated Cores 2
> Allocated Ram 1024

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

**Comment by tteck** [comment]
Corrected storage. 1vCPU is correct
https://github.com/tteck/Proxmox/blob/92452db3e5c21d5be4e9a074929e3a8ba7c69e88/ct/nginxproxymanager.sh#L188-L190
![Screenshot from 2024-08-06 17-13-03](https://github.com/user-attachments/assets/dcb6680f-5dcc-4050-ba8d-67d10e61c12b)
