### ISSUE TITLE
Error while installing NPM in LXC v3

### ISSUE THREAD

**Issue by HunorLaczko** [tteck/Proxmox#348]
_   _ _____  __  __ 
       | \ | |  __ \|  \/  |
       |  \| | |__) | \  / |
       |     |  ___/| |\/| |
       | |\  | |    | |  | |
       |_| \_|_| v3 |_|  |_|

Using Advanced Settings
Using CT Type Unprivileged
Using CT Password ******
Using CT ID 200
Using CT Name npn
Using Disk Size 3GB
Using 2vCPU
Using 1024MiB RAM
Using Bridge vmbr0
Using Static IP Address 10.10.100.70/24
Using Gateway IP Address 10.10.100.1
Using VLAN Tag NONE
Are these settings correct(y/n)? y
 ✓ Using local for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 200 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.10.100.70 
 ✓ Updated Container OS
 - Installing Dependencies...‼ ERROR 100@64 Unknown failure occured.

I get the following error while trying to install NPM with v3 version of the script. It's a relatively new Proxmox install, I did run the post-install script, using local-zfs. I managed to install it the v2 version of the scriot, but I couldn't set the id with that. Can you help with this error?

**Comment by tteck** [comment]
Well, v2 & v3 use the same `nginx-proxy-manager-install.sh` so that leaves it up to your network settings. I see it's connecting to your network, but is it connecting to the internet? You're using a CIDR Notation `/24` so you must have a Subnet Mask `255.255.255.0`?

**Comment by tteck** [comment]
I bet if you use "Default Settings" with v3 it'll also work

**Comment by dl09r** [comment]
I was having a similar issue.  How I resolved "my issue" was to build an debian LXC, change the source.list repos to something other than the default http://ftp.debian.yada.yada.yada.  Then I ran the setup .sh within the LXC and all was good.

@tteck Had the same happen with default settings.  It could be something with my setup but wasn't a big deal as I had another way to leverage your hard work.

**Comment by HunorLaczko** [comment]
Might have been something with the network settings, the default version ran without a problem. Thanks.

**Comment by tteck** [comment]
Yeah, if it installed using DHCP, (Default Settings) it's network related (settings).
