### ISSUE TITLE
mariadb Script

### ISSUE THREAD

**Issue by Nelson666** [tteck/Proxmox#3480]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi,

is it possible to add the adminer option again?

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Standard installation

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
