### ISSUE TITLE
qBittorrent lxc and nfs mounts

### ISSUE THREAD

**Issue by nautilus7** [tteck/Proxmox#3481]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi, I have setup a qBittorrent lxc using your script. I have made it privileged in order to use some nfs mounts from my NAS to download my files.

Everything works fine, except from when I start/restart the container. Every time it starts, all my torrents are "missing files" and I need to "force resume" them manually.

I believe the reason this happens is because the qBittorrent service starts before my nfs mount is actually mounted.

I noticed the qBittorrent service in the lxc is only requiring [network.target](https://github.com/tteck/Proxmox/blob/92452db3e5c21d5be4e9a074929e3a8ba7c69e88/install/qbittorrent-install.sh#L38) while the [suggested qBittorrent service](https://github.com/qbittorrent/qBittorrent/blob/master/dist/unix/systemd/qbittorrent-nox%40.service.in) does have more requirements.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by nautilus7** [comment]
I thought this is a bug. Isn't it? When the script does not work correctly, how would you call it?

**Comment by tteck** [comment]
The script installs the application without issues. The application utilizes the LXC storage without issues. However, using storage mounts and getting them to work seamlessly is outside the script's scope.

**Comment by nautilus7** [comment]
The systemd service from the qBittorrent devs has substantialy different/more requirements than the systemd service your script deploys. This results in non optimal use of the application as it requires rechecking all torrents on every restart.

Do you call it "installation without issues" ??? 

Creating a proper systemd service for the application is one of the core aspects of the script.

I understand that you're not going to make any fixes/changes for this, right?

Anyway, thanks for scripts.
