### ISSUE TITLE
Failed to set value 'vaapi=va:,kernel_driver=i915,driver=iHD' for option 'init_hw_device': Invalid argument

### ISSUE THREAD

**Issue by adaszko** [tteck/Proxmox#3489]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

This is probably going to be closed right away for whatever reason lol but here we go.

Jellyfin LXC script, trying to play any movie results in the movie never loading up.  ffmpeg logs:

```
[AVHWDeviceContext @ 0x6543173f52c0] No VA display found for any default device.
Device creation failed: -22.
Failed to set value 'vaapi=va:,kernel_driver=i915,driver=iHD' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument
```

The fix is as simple as ` chown :render /dev/dri/renderD128` but it needs to be redone after every reboot of the container so it would make sense to incorporate it into the script.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by adaszko** [comment]
It's this issue: https://github.com/jellyfin/jellyfin/issues/8217

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by adaszko** [comment]
This is beyond hilarious 😆

**Comment by tteck** [comment]
I know right, people can't follow clear guidelines.

**Comment by adaszko** [comment]
For the record, I made a mistake in the bug report.  I'm using all defaults -- which now I see is Ubuntu:
```
root@jellyfin:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

**Comment by tteck** [comment]
Did you set the FFmpeg path?

**Comment by adaszko** [comment]
I didn't change any defaults.  That includes ffmpeg path

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/2928

**Comment by adaszko** [comment]
> https://github.com/tteck/Proxmox/discussions/2928#discussioncomment-9344576

I don't see how installing random packages from the intel website is considered a better fix than a simple `chown :render`.

Also, how is this issues closed and we're still discussing on it?  Should I open a new one that doesn't have the mistakenly specified OS?

**Comment by adaszko** [comment]
For people coming here from a search engine:

Manually editing `/etc/systemd/system/jellyfin.service.d/jellyfin.service.conf` and adding:

```
[Service]
[...]
ExecStartPre=+/usr/bin/chown :render /dev/dri/renderD128
```

solved it for me.  Until it gets overwritten by the next update of course.
