### ISSUE TITLE
All Templates LXC - debian-12-turnkey-wordpress_18.1-1_amd64.tar.gz

### ISSUE THREAD

**Issue by kszere** [tteck/Proxmox#3493]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I don't know what enale verbose mode.

I have problem with this script. Not working.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/1fa12977-e06e-4e17-bdfa-8867925770e6)

### Please provide detailed steps to reproduce the issue.

commad:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/all-templates.sh)"
This will allow for the creation of one of the many Template LXC │ Containers. Proceed?: YES
debian-12-turnkey-wordpress_18.1-1_amd64.tar.gz; SELECT
[ERROR] 1@179 Unknown failure occured.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
   ___   ____  ______               __     __
  / _ | / / / /_  __/__ __ _  ___  / /__ _/ /____ ___
 / __ |/ / /   / / / -_)  ' \/ _ \/ / _ `/ __/ -_|_-<
/_/ |_/_/_/   /_/  \__/_/_/_/ .__/_/\_,_/\__/\__/___/
                           /_/

[INFO] LXC container '111' was successfully created, and its IP address is 192.168.86.78.

[INFO] Proceed to the LXC console to complete the setup.

[INFO] login: root
[INFO] password: va0plwBfhKQ=
```
Try deleting the template `debian-12-turnkey-wordpress_18.1-1_amd64.tar.gz` and try again. If that doesn't resolve the issue, I will need more info about your storage.

**Comment by tteck** [comment]
WordPress is also available in the TurnKey LXC Appliances script.
https://github.com/tteck/Proxmox/blob/9c88dcdbd64a4f302acb38f14aaff8efe8467bd0/turnkey/turnkey.sh#L87

**Comment by tteck** [comment]
Make sure not to use SSH.
It appears it can't find an IP
https://github.com/tteck/Proxmox/blob/2782502e0614fe7fc0c37c0a3871178086d710a5/misc/all-templates.sh#L179

🔁 If I cannot reproduce the problem on my side, I cannot address an issue that appears to be functioning correctly here.
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by kszere** [comment]
I must use eth0 with vmbr2.

**Comment by tteck** [comment]
My intention was to maintain the TurnKey scripts in their simplest form, contained within a single file, and with minimal options, if any. 
https://github.com/tteck/Proxmox/blob/2782502e0614fe7fc0c37c0a3871178086d710a5/misc/all-templates.sh#L80-L90

You can download the script and modify it to suit your needs.
