### ISSUE TITLE
Home Assistant Core LXC script broken

### ISSUE THREAD

**Issue by ctaylor4874** [tteck/Proxmox#3494]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the `Home Assistant Core LXC` script, I get the following error

```bash
unable to create CT 111 - unsupported Ubuntu version '24.04'
bash: line 182: exit: A problem occured while trying to create container.: numeric argument required
```

Proxmox Version:  8.1.3

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="1009" alt="Screenshot 2024-08-08 at 6 28 14 PM" src="https://github.com/user-attachments/assets/e117623d-9031-4388-bc7c-6f29486b0b96">

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/3472#discussioncomment-10240064
