### ISSUE TITLE
Adminer Unavailable on MariaDB LXC

### ISSUE THREAD

**Issue by woodmj74** [tteck/Proxmox#35]
Firstly - thank you for the awesome work here, had made stuff really accessible to me!

Have attempted this several times, with fresh attempts each time and come up against the same issue. Following the instructions here:
https://github.com/tteck/Proxmox#-mariadb-lxc-container-

Once completed, I can't access Adminer, everything else is fine.

Tried at a couple of points; Adminer is available once the container is spun up following the bash script in shell. Its available through all the steps until "⚠️ Reboot the lxc" - once executed I can't then access Adminer. Hitting the IP in the browser, the Apache holding page has gone.

MariaDB is fine and functional. Running ```sudo systemctl status apache2``` renders this:
```
* apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-02-16 21:48:45 GMT; 4min 28s ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 132 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)
        CPU: 32ms

Feb 16 21:48:45 mariadb systemd[1]: Starting The Apache HTTP Server...
Feb 16 21:48:45 mariadb apachectl[164]: (2)No such file or directory: AH02291: Cannot access directory '/var/>
Feb 16 21:48:45 mariadb apachectl[164]: (2)No such file or directory: AH02291: Cannot access directory '/var/>
Feb 16 21:48:45 mariadb apachectl[164]: AH00014: Configuration check failed
Feb 16 21:48:45 mariadb apachectl[132]: Action 'start' failed.
Feb 16 21:48:45 mariadb apachectl[132]: The Apache error log may have more information.
Feb 16 21:48:45 mariadb systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
Feb 16 21:48:45 mariadb systemd[1]: apache2.service: Failed with result 'exit-code'.
Feb 16 21:48:45 mariadb systemd[1]: Failed to start The Apache HTTP Server.
```

I've started playing around with a few things to try but TBH I'm great at following instructions but don't really get the details hence loving your hard work. Any suggestions or anything I can provide would be appreciated. :-)

**Comment by tteck** [comment]
Please run this one line at a time in the Mariadb LXC console
```yaml
mkdir /var/log/apache2
chmod 750 /var/log/apache2
chown root:adm /var/log/apache2
service apache2 start
```
Let me know if this is the solution

**Comment by woodmj74** [comment]
Wow - super amazingly quick response! 

Yes, that 's it. Thank you for that @tteck 

Happy to close the ticket and hopefully there's a history now for anyone else facing the same issue but wasn't sure if you'll be doing anything further as a consequence of this.

**Comment by tteck** [comment]
Thank you for bringing this to my attention! The issue has been resolved.

**Comment by FredericMa** [comment]
I experienced the same issue and following the steps above resolved it, so thanks for that!
I just wanted to let you know in case this should have been resolved in the script, since it doesn't seem to do the trick in that case.

**Comment by tteck** [comment]
@FredericMa thank you for bringing this to my attention. I left the fix out of V2 script... Oops
Most will just fix it themselves without reporting

**Comment by xairoo** [comment]
@tteck autostart for Adminer wasn't enabled at my setup. Simply run `systemctl enable apache2` to automatically start it after a reboot.

Anyway, thanks for your great work! 99,9999% of your Proxmox stuff is just perfect =)!

PS: Maybe it's a good option to ask for logging to RAM instead of disk, especially for Plex transcoding... SSD wear out... ;)
