### ISSUE TITLE
Feature Request: Add a support for OPNsense and OPNsense containers 

### ISSUE THREAD

**Issue by jega-ms** [tteck/Proxmox#3510]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Add a support for OPNsense and OPNsense containers 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Add a support for OPNsense and OPNsense containers 

### Please provide detailed steps to reproduce the issue.

 Add a support for OPNsense and OPNsense containers

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
