### ISSUE TITLE
Matterbridge script is faulty

### ISSUE THREAD

**Issue by Luligu** [tteck/Proxmox#3512]
### Please verify that you have read and understood the guidelines.

Done

### A clear and concise description of the issue.

Hi, I'm the author of Matterbridge.
Your script is creating a lot of issues with user, so please remove it or update it following the guidelines in the matterbridge package.

Installation: https://github.com/Luligu/matterbridge#installation
1) Under no circumstances you are allowed to build matterbridge on the user machine;
2) Matterbridge have to be installed globally from npm: npm install -g matterbridge
3) No need to update, it can be updated from the frontend: if you want to update from script use: npm install -g matterbridge

Daemon configuration: https://github.com/Luligu/matterbridge#run-matterbridge-as-a-daemon-with-systemctl-linux-only
It has to be exactly like this changing twice USER with appropriate values:
[Unit]
Description=matterbridge
After=network-online.target

[Service]
Type=simple
ExecStart=matterbridge -bridge -service
WorkingDirectory=/home/<USER>/Matterbridge
StandardOutput=inherit
StandardError=inherit
Restart=always
RestartSec=10s
TimeoutStopSec=30s
User=<USER>

[Install]
WantedBy=multi-user.target

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

All users reports issues with your script.

**Comment by tteck** [comment]
Has been resolved https://github.com/tteck/Proxmox/issues/3499

🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.
