### ISSUE TITLE
Vaultwarden LXC update failed

### ISSUE THREAD

**Issue by jcastro** [tteck/Proxmox#3515]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I installed Vaultwarden LXC several months ago, but when I tried to update to the newly released 1.32 version, I encountered an error. The description mentioned putting the script in verbose mode, but I couldn't figure out how to do it. I will update once I learn how to enable verbose mode.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="764" alt="image" src="https://github.com/user-attachments/assets/be94c938-baae-4fef-841b-0f6a8290af79">
<img width="916" alt="image" src="https://github.com/user-attachments/assets/96b6f37c-a104-42ae-9ea6-9ae5d826ade2">

### Please provide detailed steps to reproduce the issue.

Run the 'update' command on the Vaultwarden LXC container.

**Comment by tteck** [comment]
Did you set the resources to 4vCPU and 4GB RAM before trying to update?

**Comment by jcastro** [comment]
yes! it's actually way more than that 
<img width="413" alt="image" src="https://github.com/user-attachments/assets/dcb81d99-6ead-40a1-8b24-733b1aa15198">
Could you tell me how to run it in verbose mode? I can update with the full output!

**Comment by tteck** [comment]
The only way to update with verbose is to manually execute the commands.
Does the LXC have enough storage?

**Comment by tteck** [comment]
Update works with no issues on my end.

```
 _    __            ____ _       __               __         
| |  / /___ ___  __/ / /| |     / /___ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
                                                             

 ⚠️  Ensure you set 4vCPU & 4096MiB RAM minimum!!! 

 ✓ Stopped Vaultwarden
 ✓ Updated VaultWarden
 ✓ Cleaned
 ✓ Started Vaultwarden
 ✓ 1.32.0 Update Successful

 ⚠️  Ensure you set resources back to normal settings 

root@vaultwarden:~# 
```
I even created a new LXC to check the `cargo build` command.

```
 _    __            ____ _       __               __         
| |  / /___ ___  __/ / /| |     / /___ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
                                                             
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: vaultwarden
Using Disk Size: 6
Allocated Cores: 4
Allocated RAM: 5120
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Vaultwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Rust
 ✓ Built Vaultwarden 1.32.0
 ✓ Downloaded Web-Vault v2024.6.2b
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Set Container to Normal Resources
 ✓ Completed Successfully!

Vaultwarden should be reachable by going to the following URL.
         http://192.168.86.250:8000 
```

**Comment by jcastro** [comment]
Yep! it was because of the disk space... thanks!

**Comment by miloumeeloo** [comment]
It seems that rust keeps the old compiler toolchains used for previous updates and fill up disk space unnecessarily.
You can list them by running
`rustup show`
and remove the unused ones with, for example
`rustup toolchain remove 1.78.0-x86_64-unknown-linux-gnu 1.79.0-x86_64-unknown-linux-gnu 1.80.1-x86_64-unknown-linux-gnu`
@tteck Maybe these commands can be included in the script to avoid further update errors?
