### ISSUE TITLE
Changedetection stuck on browserless/playwright install step

### ISSUE THREAD

**Issue by mohammedmulazada** [tteck/Proxmox#3518]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Issue seems different from https://github.com/tteck/Proxmox/issues/1749

When running the changedetection install script with default settings:
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/changedetection.sh)"`

It will start but get stuck at the `Installing Browserless & Playwright` step.

![Screenshot 2024-08-13 at 12 06 27](https://github.com/user-attachments/assets/cbcc6dd1-e9dc-4087-9fd7-3fe7cc0bed7b)

When checking in verbose mode (debian 12), it seems like it gets stuck right after cloning browserless

![Screenshot 2024-08-13 at 12 16 47](https://github.com/user-attachments/assets/ab176302-5a07-4aba-b226-e8edd9de830c)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

- Run
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/changedetection.sh)"`
- Choose default settings
- Wait for error

**Comment by mohammedmulazada** [comment]
Hmmm, I left it for an hour or so and then it somehow finished installing. In that case it is not related to the script. Sorry for the noise!

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/commit/72dfc20090ada0e197e3f681e95b4c839c69814e
