### ISSUE TITLE
Mariadb LXC 

### ISSUE THREAD

**Issue by Themaxsti** [tteck/Proxmox#3521]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Installing Mariadb LXC using bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/mariadb.sh)"
Fails due to 504 error when trying to download from https://r.mariadb.com/downloads/mariadb_repo_setup

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Processing triggers for libc-bin (2.36-9+deb12u7) ...
 ✓ Installed Dependencies
 |curl: (22) The requested URL returned error: 504
/dev/fd/63: line 1: $'\E[?25h': command not found
/dev/fd/63: line 2: $'\E[01': command not found
/dev/fd/63: line 2: $'31m[ERROR]\E[m': command not found
/dev/fd/63: line 2: $'31m23\E[m:': command not found
/dev/fd/63: line 2: $'31m0\E[m:': command not found
/dev/fd/63: line 3: The: command not found

[ERROR] in line 23: exit code 0: while executing command $STD bash <(curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup)
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

### Please provide detailed steps to reproduce the issue.

Install from Script and it fails if you go advance or not.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    __  ___           _       ____  ____ 
   /  |/  /___ ______(_)___ _/ __ \/ __ )
  / /|_/ / __  / ___/ / __  / / / / __  |
 / /  / / /_/ / /  / / /_/ / /_/ / /_/ / 
/_/  /_/\__,_/_/  /_/\__,_/_____/_____/  
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: mariadb
Using Disk Size: 4
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a MariaDB LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed MariaDB
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
Google "504" error
