### ISSUE TITLE
Frigfate install problem

### ISSUE THREAD

**Issue by domoticauser** [tteck/Proxmox#3526]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

It looks that during the installing, it stops. No error.

![afbeelding](https://github.com/user-attachments/assets/1add91ad-3519-4b54-b896-a96a3c26f496)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

I used this script, bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/frigate.sh)"
proxmox 8.1.4

**Comment by tteck** [comment]
If it doesn't throw an error, WAIT!

🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by domoticauser** [comment]
I let it run all night, nut nothing happend.

Version, debian Linux 6.5.11-8-pve x86_64 is this what you need?
