### ISSUE TITLE
fail update ESPHome

### ISSUE THREAD

**Issue by gianlucaf81** [tteck/Proxmox#3532]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

trying to update esphome via "update" i get this error:

[ERROR] in line 66: exit code 0: while executing command pip3 install -U esphome &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/3499c329-8edb-4781-b699-fc82a378b355)

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/3300

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
