### ISSUE TITLE
Vaultwarden upgrade process missing Admin side

### ISSUE THREAD

**Issue by zelig2** [tteck/Proxmox#354]
When I run the Vaultwarden upgrade script it upgrades the Bitwarden elements but not the Vaultwarden admin side. I ran the script and it stated `This will Update Vaultwarden to v2022.6.2.` which is the current release name for Bitwarden Server. My Vaultwarden install is at 1.24.0 but it states there is a [1.25.1](https://github.com/dani-garcia/vaultwarden/releases/tag/1.25.1) release out now. Thanks for the scripts.

**Comment by tteck** [comment]
I'll look into this. Where do you find the Vaultwarden installed version at?

**Comment by zelig2** [comment]
When you go into the Admin page for Vaultwarden click the three lines in the upper right and select Diagnostics. There you can see the current version and if there’s an upgrade available.

**Comment by tteck** [comment]
On 2022/05/29, I did a major code refactoring to Vaultwarden LXC. I'd suggest you backup everything and reinstall. Meanwhile, I'm going to be creating a Vaultwarden update script (only for installs after 5/29) and renaming the existing update script to Web-vault update.

**Comment by tteck** [comment]
fixed with https://github.com/tteck/Proxmox/pull/355
