### ISSUE TITLE
Printed default settings don't reflect actual default settings

### ISSUE THREAD

**Issue by alexschneider** [tteck/Proxmox#3548]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

This isn't an issue with a specific script, but I noticed it when installing Jellyfin. I use a specific bridge and vlan tag for my containers, and I change them in the `default_settings` function before running the script because it's easier than having to click through every advanced setting menu (and I always read the scripts before I run them downloaded from the internet). However, those default settings (among others) seem to be hardcoded in `build.func` and don't reflect the actual default settings in the scripts. This leads to confusion when these settings are changed and not reflected in the pre-installation text. 

Ideally the `echo_default` function in `build.func` should reflect the actual default settings the script sets, instead of being hard coded.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/8797d5cd-cb66-43de-8384-8814ebc34311)

### Please provide detailed steps to reproduce the issue.

Modify any of the default settings that are hardcoded in `build.func` such as `PW`, `CT_ID`, `BRG`, `NET`, etc, and see that the output of `echo_default` don't reflect those modifications.

**Comment by tteck** [comment]
Why would you modify the default settings this way? 

>The basic setup adheres to default settings, while the advanced setup gives users the ability to customize these defaults.

**Comment by tteck** [comment]
![Screenshot 2024-08-18 7 01 21 PM](https://github.com/user-attachments/assets/683223d8-86eb-446b-90c4-931518fb6ee5)

**Comment by tteck** [comment]
To change the default settings, it's not in the `build.func` script.
https://github.com/tteck/Proxmox/blob/631ef46466dfc8feffe1bd358ee5289850f89b1d/ct/jellyfin.sh#L32-L54

**Comment by tteck** [comment]
>it's easier than having to click through every advanced setting menu

Really? Makes no sense to me. 🤷🏻‍♂️

**Comment by alexschneider** [comment]
It takes longer to do it through the advanced settings and sometimes I mess up by changing things I don't want to change, such as the operating system since the default isn't always the setting that gets prefilled when I click through since I have the memory of a goldfish. Sometimes I also bypass the setting I mean to change, so I have to go back and start over. So it makes more sense for me to edit the text file. 

I do change the default settings in the jellyfin.sh file, but the changes don't get reflected when the default settings get printed out (as in my screenshot - the vlan and bridge should be different), because the default settings are hardcoded in build.func. This lead to confusion for me but now that I know that the default settings are hardcoded, I know not to be confused. I filed the issue because this felt like a bug, but if it isn't, no worries. 


https://github.com/tteck/Proxmox/blob/631ef46466dfc8feffe1bd358ee5289850f89b1d/misc/build.func#L132C1-L155

```
echo_default() {
  echo -e "${DGN}Using Distribution: ${BGN}$var_os${CL}"
  echo -e "${DGN}Using $var_os Version: ${BGN}$var_version${CL}"
  echo -e "${DGN}Using Container Type: ${BGN}$CT_TYPE${CL}"
  echo -e "${DGN}Using Root Password: ${BGN}Automatic Login${CL}"
  echo -e "${DGN}Using Container ID: ${BGN}$NEXTID${CL}"
  echo -e "${DGN}Using Hostname: ${BGN}$NSAPP${CL}"
  echo -e "${DGN}Using Disk Size: ${BGN}$var_disk${CL}${DGN}GB${CL}"
  echo -e "${DGN}Allocated Cores ${BGN}$var_cpu${CL}"
  echo -e "${DGN}Allocated Ram ${BGN}$var_ram${CL}"
  echo -e "${DGN}Using Bridge: ${BGN}vmbr0${CL}"
  echo -e "${DGN}Using Static IP Address: ${BGN}dhcp${CL}"
  echo -e "${DGN}Using Gateway IP Address: ${BGN}Default${CL}"
  echo -e "${DGN}Using Apt-Cacher IP Address: ${BGN}Default${CL}"
  echo -e "${DGN}Disable IPv6: ${BGN}No${CL}"
  echo -e "${DGN}Using Interface MTU Size: ${BGN}Default${CL}"
  echo -e "${DGN}Using DNS Search Domain: ${BGN}Host${CL}"
  echo -e "${DGN}Using DNS Server Address: ${BGN}Host${CL}"
  echo -e "${DGN}Using MAC Address: ${BGN}Default${CL}"
  echo -e "${DGN}Using VLAN Tag: ${BGN}Default${CL}"
  echo -e "${DGN}Enable Root SSH Access: ${BGN}No${CL}"
  echo -e "${DGN}Enable Verbose Mode: ${BGN}No${CL}"
  echo -e "${BL}Creating a ${APP} LXC using the above default settings${CL}"
}
```
