### ISSUE TITLE
CommaFeed script broke

### ISSUE THREAD

**Issue by fbloemhof** [tteck/Proxmox#3551]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When executing the CommaFeed installation script you get this error:

```
[ERROR] in line 32: exit code 0: while executing command wget -q https://github.com/Athou/commafeed/releases/latest/download/commafeed.jar
```

CommaFeed got a new release and they changed a lot: https://github.com/Athou/commafeed/releases/tag/5.0.0

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by SorenHolm** [comment]
Just a FYI, running `update` in the console still yields errors like the bug report, leaving CommaFeed inaccessible. A reboot restores access but CommaFeed isn't updated. 

In the end I found it easier to run the helper script anew to set up a fresh CommaFeed instance and import my OPML backup file which took maybe 10 minutes including setting up my "Unread" app with the Fever API.

**Comment by tteck** [comment]
Yep, that's why it's listed as a breaking change.
https://github.com/tteck/Proxmox/blob/main/CHANGELOG.md

**Comment by SorenHolm** [comment]
Ah right, sorry, I thought that `Completed` meant the bug was fixed. 
My mistake :-)
