### ISSUE TITLE
Bazarr will only attempt upgrade, no installation

### ISSUE THREAD

**Issue by Puntjuh** [tteck/Proxmox#3557]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Upon running the command :  bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/bazarr.sh)"  from the Proxmox VE shell it will display a Window asking whether or not i want to update Bazarr, since i don't have an active bazarr installation i choose "NO". But that will cancel the installation. Upon trying to answer with "YES" it will report there is no active installation and then abort the script 

I have tried the same with Lidarr, which will do the exact same. It seems as it will only run the function: 

```
function update_script() {
header_info
if [[ ! -d /var/lib/lidarr/ ]]; then msg_error "No ${APP} Installation Found!"; exit; fi
msg_info "Updating $APP LXC"
apt-get update &>/dev/null
apt-get -y upgrade &>/dev/null
msg_ok "Updated $APP LXC"
exit
}
```

However, when i run the script line by line it will complain about an unexpected "(" in line 2 of the script. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Image of only displayed option:
![image](https://github.com/user-attachments/assets/f0550335-d4f9-4a6d-8670-0a5a77ea6d56)

if i answer yes: 
![image](https://github.com/user-attachments/assets/06b66c82-5a6c-4f5c-9ad1-7b87585bac7e)

if i answer no:
![image](https://github.com/user-attachments/assets/d08c26eb-30fe-4be8-96a6-3b56b94e68bf)

### Please provide detailed steps to reproduce the issue.

Run the installation command 

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/bazarr.sh)" `

**Comment by tteck** [comment]
Execute the script in the Proxmox shell, not the Sonarr LXC console.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
