### ISSUE TITLE
Kernel Cleanup Script - Stuck in GRUB recovery

### ISSUE THREAD

**Issue by menmob** [tteck/Proxmox#356]
I am not entirely sure if this is the correct place to put this, but here goes. 

I ran the kernel cleanup script on my Proxmox host (7+, I don't remember which version specifically), and I left it running in the background. 10 minutes later, the node has dropped off and on reboot it is stuck in the GRUB bash-like environment. Basic troubleshooting from google has not helped. Any ideas?

**Comment by tteck** [comment]
What do you mean by "I left it running in the background"? 
You left the shell screen while the script was running?

**Comment by menmob** [comment]
Yes, I left the SSH session open while doing other things and allowed the script to run. There was no forced power-off or sudden session being closed. I just got a popup from PuTTY that the session had been closed unexpectedly and I found the host unresponsive.

**Comment by tteck** [comment]
I have no idea. Sorry. Maybe Google "Repair the GRUB Bootloader"

**Comment by menmob** [comment]
No problem, figured I'd ask. Thanks for the scripts :)
