### ISSUE TITLE
Calibre-Web script error when using script to add Calibre-Web extras from LXC console (unbound variable)

### ISSUE THREAD

**Issue by BHam86** [tteck/Proxmox#3576]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

When selecting an additional feature from the Calibre-Web script I am presented with the following error:

`environment: line 141: options: unbound variable`

I'm fetching and running the script from the LXC console from PVE web UI.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Created a fresh LXC using `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/calibre-web.sh)"`
Installed with default settings.
Ran the same script from the LXC console via PVE UI to install additional features.
Selected gdrive option.
Script runs and immediately throws the error.

**Comment by tteck** [comment]
That _should_ fix the unbound variable.

**Comment by BHam86** [comment]
I keep getting the same error. I've manually downloaded the script on the LXC to confirm I'm getting the new version before running it.

**Comment by tteck** [comment]
I'll create a Calibre-Web LXC and test further.

**Comment by tteck** [comment]
@remz1337 beings this is one of your PR's, how about checking this.

**Comment by tteck** [comment]
I have no `unbound variable` error.


![Screenshot 2024-08-23 2 18 16 PM](https://github.com/user-attachments/assets/e2713a7c-91a3-4777-8723-54696620e3f9)

**Comment by tteck** [comment]
I installed `calibreweb[gdrive]`, no issues.

**Comment by tteck** [comment]
Clear browser cache

**Comment by BHam86** [comment]
Somehow it's just not working for me. I cleared my browser cache, switched browsers, switched to another PC, updated Proxmox, and created a new LXC on a different node for good measure. No dice... Any other suggestions? :)

**Comment by tteck** [comment]
Are you using SSH? I did not.

**Comment by BHam86** [comment]
Nope I'm running it from the LXC console in the PVE web UI.

**Comment by remz1337** [comment]
Just did a fresh install. No issues on my end installing additional dependencies (tested gdrive, goodreads, ldap and oauth)

**Comment by BHam86** [comment]
ran `pip install calibreweb[gdrive]`, and that works like a charm. Anything I'll be missing when I add it manually?
