### ISSUE TITLE
Plex V3 - installation error

### ISSUE THREAD

**Issue by zsmbrvr** [tteck/Proxmox#358]
I upgraded the system and rebooted.

Linux XXX 5.15.39-1-pve #1 SMP PVE 5.15.39-1 (Wed, 22 Jun 2022 17:22:00 +0200) x86_64 GNU/Linux

I tried to install PlexV3 but I get an error 

The script used was
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/plex-v3.sh)"

```
Using Default Settings
Using CT Type Privileged
Using CT Password Automatic Login
Using CT ID 106
Using CT Name plex
Using Disk Size 8GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
**Using Gateway Address NONE**
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 106 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.0.194
 ✓ Updated Container OS
 - Installing Dependencies...‼ ERROR 100@62 Unknown failure occured.
```
I wonder if the issue is with **Using Gateway Address NONE**

(BTW **occurred** is double r)

**Comment by tteck** [comment]
It appears it's not reaching the internet, DNS?

**Comment by zsmbrvr** [comment]
I tried to specify everything manually.

```
Using Advanced Settings
Using CT Type Privileged
Using CT Password Automatic Login
Using CT ID 106
Using CT Name plex
Using Disk Size 8GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address 192.168.0.155
Using Gateway IP Address 192.168.0.1
Using VLAN Tag NONE
Are these settings correct(y/n)? y

 ✓ Using local for Template Storage.
 ✓ Using local for Container Storage.
 ✓ Updated LXC Template List
 - Creating LXC Container...400 Parameter verification failed.
net0: invalid format - format error
net0.ip: invalid format - value does not look like a valid ipv4 network configuration


pct create <vmid> <ostemplate> [OPTIONS]
‼ ERROR 2@118 A problem occured while trying to create container.
```
I did manage to create a docker lxc. So I am not sure what's different.

**Comment by tteck** [comment]
`Using Static IP Address 192.168.0.155`
Static IP requires CIDR Notation (/24) `192.168.0.155/24`
https://github.com/tteck/Proxmox/issues/162#issue-1206599738

**Comment by zsmbrvr** [comment]
I realised. It still looks stuck.
Do I need a bridge for each container?

**Comment by tteck** [comment]
no
If it doesn't give an error, it's still working.

**Comment by zsmbrvr** [comment]
I am sure the issue is on my end.
This is my /etc/network/interfaces
```
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto enp3s0f0
iface enp3s0f0 inet dhcp

auto enp3s0f1
iface enp3s0f1 inet manual

auto vmbr0
iface vmbr0 inet static
        address 192.168.0.102/24
        gateway 192.168.0.1
        bridge-ports enp3s0f1
        bridge-stp off
        bridge-fd 0
```

**Comment by tteck** [comment]
Mine
```
root@proxmox:~# cat /etc/network/interfaces
auto lo
iface lo inet loopback

iface eno1 inet manual

auto vmbr0
iface vmbr0 inet static
        address 192.168.86.23/24
        gateway 192.168.86.1
        bridge-ports eno1
        bridge-stp off
        bridge-fd 0

iface wlo1 inet manual
```

**Comment by tteck** [comment]
Are you using the experimental Software Defined Network (SDN) integration?

**Comment by zsmbrvr** [comment]
No, what's that?
I've got multiple network devices.

**Comment by tteck** [comment]
Why is `source /etc/network/interfaces.d/*` in your `/etc/network/interfaces`?
That means that you have a SDN menu in Datacenter.
The [Software Defined Network (SDN) feature](https://pve.proxmox.com/pve-docs/chapter-pvesdn.html) allows you to create virtual networks (VNets) at the datacenter level.

**Comment by zsmbrvr** [comment]
Not sure, but the directory is empty anyway.

**Comment by zsmbrvr** [comment]
I tried the docker one again, and it ran fine.
I am not sure what's different between the two.

**Comment by tteck** [comment]
You're still getting `‼ ERROR 100@62 Unknown failure occured.` with the Plex LXC install?
Need to fix "occured", thanks

**Comment by zsmbrvr** [comment]
> It appears it's not reaching the internet, DNS?

IT'S ALWAYS DNS!
Tailscale MagicDNS is messing things up. I still don't understand how come your docker script was ok.

**Comment by tteck** [comment]
Safe to close this now that we know the issue?
