### ISSUE TITLE
Wireguard container not functioning after installation

### ISSUE THREAD

**Issue by Kroesss** [tteck/Proxmox#3581]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing the Wireguard-container with the helper-script (using default settings), the connection from my device could be set-up, but there was no traffic at all coming through. After help from some help from Reddit, it appears to be connected with the removal of pivpn. The Reddit-user suggested additional commands that install pivpn, and after that, everything worked out of the box.

Link to reddit-post with the solution; https://www.reddit.com/r/homelab/comments/1ezksad/comment/ljn2oz4/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

First install the wireguard-container with all default settings, then log into WGDashboard and create a configuration with a peer. Connect phone with the server and try to get any traffic (either a website or something from another element within the local network).

**Comment by tteck** [comment]
Have you tried with today's commits?  
BTW, your solution is using PIVPN.
