### ISSUE TITLE
Nginx Proxy Manager LXC

### ISSUE THREAD

**Issue by ralfrupf1976** [tteck/Proxmox#3586]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The script crashed while trying to update Nginx Proxy Manager. Within the LXC I typed "update" - the scripts starts and then:

✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.11.3
 | Setting up Enviroment   
[ERROR] in line 136: exit code 0: while executing command python3 -m pip install --no-cache-dir certbot-dns-cloudflare &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

See above - "update" does not work

**Comment by tteck** [comment]
~https://github.com/tteck/Proxmox/issues/2658~

**Comment by tteck** [comment]
Sorry, I read that wrong. Try this https://github.com/tteck/Proxmox/discussions/3300#discussioncomment-9923938

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/3311
