### ISSUE TITLE
Jellyfin v3 Broken

### ISSUE THREAD

**Issue by SergioRius** [tteck/Proxmox#359]
In file:
`https://github.com/tteck/Proxmox/blob/main/setup/jellyfin-install.sh`

It crashes @ line 75, trying to change ownership. It doesn't have permissions.

But some lines ahead, I see that line 101 ends unexpectedly:
`ExecStart = /usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELL>`

**Comment by tteck** [comment]
Thanks for pointing out the service file junk, fixed.
```
       _      _ _        __ _       
      | |    | | |      / _(_)      
      | | ___| | |_v3 _| |_ _ _ __  
  _   | |/ _ \ | | | | |  _| |  _ \ 
 | |__| |  __/ | | |_| | | | | | | |
  \____/ \___|_|_|\__, |_| |_|_| |_|
                   __/ |            
                  |___/             

Using Default Settings
Using CT Type Privileged
Using CT Password Automatic Login
Using CT ID 102
Using CT Name jellyfin
Using Disk Size 8GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 102 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.51 
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Hardware Acceleration
 ✓ Set Up Jellyfin Repository
 ✓ Installed Jellyfin
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Jellyfin Media Server should be reachable by going to the following URL.
             http://192.168.86.51:8096
```
I had no issues installing, maybe fork and comment out the "Hardware Acceleration" portion?

**Comment by tteck** [comment]
Any progress?

**Comment by SergioRius** [comment]
I think that the permissions fail could be caused by me changing the config
to an unprivileged container. Could be?

**Comment by tteck** [comment]
Yes, the LXC must be privileged.

**Comment by SergioRius** [comment]
> Yes, the LXC must be privileged.

What about mapping the video groups and media user?, like there:
https://www.reddit.com/r/jellyfin/comments/ul0i1a/running_jellyfin_on_lxc_unprivileged_promox_with/

That guide failed me installing the drivers, but worked fine with your apt for them ;)
