### ISSUE TITLE
Jellyfin not starting since todays update 10.9.10

### ISSUE THREAD

**Issue by crazyduck** [tteck/Proxmox#3592]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Yesterday Jellyfin installed fine with 10.9.9

I was playing around today with the LXC and did several reinstalls with the script.

Today an update to version 10.9.10 was released. Now Jellyfin wont start after fresh install, neither on recommended Ubuntu 22.04 nor on debian 12.

Journalctl throws:

```
Aug 25 23:34:28 jellyfin jellyfin[15712]: Unhandled exception. System.UnauthorizedAccessException: Access to the path '/etc/jellyfin/logging.default.json' is denied.
Aug 25 23:34:28 jellyfin jellyfin[15712]:  ---> System.IO.IOException: Permission denied
Aug 25 23:34:28 jellyfin jellyfin[15712]:    --- End of inner exception stack trace ---
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Bo>
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess a>
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess acces>
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, I>
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, I>
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at Jellyfin.Server.Helpers.StartupHelpers.InitLoggingConfigFile(IApplicationPaths appPaths)
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at Jellyfin.Server.Helpers.StartupHelpers.InitLoggingConfigFile(IApplicationPaths appPaths)
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Aug 25 23:34:28 jellyfin jellyfin[15712]:    at Jellyfin.Server.Program.<Main>(String[] args)
Au
```

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```root@jellyfin:~# systemctl status jellyfin.service 
× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─jellyfin.service.conf
     Active: failed (Result: signal) since Sun 2024-08-25 23:34:28 CEST; 10min ago
   Main PID: 15712 (code=killed, signal=ABRT)
        CPU: 109ms

Aug 25 23:34:28 jellyfin systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Aug 25 23:34:28 jellyfin systemd[1]: Stopped Jellyfin Media Server.
Aug 25 23:34:28 jellyfin systemd[1]: jellyfin.service: Start request repeated too quickly.
Aug 25 23:34:28 jellyfin systemd[1]: jellyfin.service: Failed with result 'signal'.
Aug 25 23:34:28 jellyfin systemd[1]: Failed to start Jellyfin Media Server.
root@jellyfin:~# 
```

### Please provide detailed steps to reproduce the issue.

Just do a fresh reinstall with the script.

**Comment by tteck** [comment]
It appears there's something wrong with the web client in their new 10.9.10 package. If you start Jellyfin without the web client (`/usr/bin/jellyfin --nowebclient`) it starts. No issues with 10.9.9

`ls /usr/share/jellyfin/web` everything is there.
`cat /etc/default/jellyfin` looks ok

**Comment by tteck** [comment]
Strange
I created a new Jellyfin LXC (version 10.9.10), then downgraded to version 10.9.9
```
wget -q https://repo.jellyfin.org/files/server/ubuntu/stable/v10.9.9/amd64/jellyfin-server_10.9.9%2Bubu2204_amd64.deb
dpkg -i jellyfin-server_10.9.9+ubu2204_amd64.deb
```
then I performed an `apt update && apt upgrade` which updated Jellyfin back to version 10.9.10, and it works now. This adds to my suspicion that their repository has a bad/incomplete 10.9.10 `.deb`

**Comment by di5cord20** [comment]
Thanks @tteck .  I have confirmed that the workaround you provided works.

**Comment by keichitokuna** [comment]
Hello,

Yesterday, i set up my first Proxmox server, and try the jellyfin script.
According to it, everything went fine, but i couldn't reach the WebUI.

Doing the downgrade and update as ttek says, solve my issue tonight.

Thanks

**Comment by crazyduck** [comment]
worked for me also, thanks for quick response.

For this particular version, perhaps do above steps by script?

**Comment by xekil** [comment]
> apt update && apt upgrade

Thanks, this worked for me too

**Comment by holocronology** [comment]
I had the same issue yesterday when setting up a fresh Jellyfin LXC. The fix/workaround above did work for me, but I will add a twist.

Initially I installed the Jellyfin LXC using the script. I then also installed the File Browser script onto the same Jellyfin LXC. It also would not pull up the web UI for File Browser. After initially killing the Jellyfin LXC and rebuilding it, adding File Browser, ensuring my network connections were OK, did I come here and find the above fix.

After applying the Jellyfin fix, File Browser still did not work properly. The webUI was not accessible. I eventually had to remove it and then reinstall it with the script after the Jellyfin Fix, for it to finally work correctly.

I assume the issues are linked in some way.

**Comment by MCarver1010** [comment]
Downgrading and then upgrading jellyfin didn't seem to work for me to resolve the web UI issue. The jellyfin server starts and I can access it from the android app, but the web UI is non-functional. I get this when I type the jellyfin command in the LXC.

`[16:28:02] [ERR] [1] Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings`

Appreciate it's not an issue with this script, just wondered if anybody has the same problem, or any suggestions.

**Comment by Toastyyy3** [comment]
Had the same issue and by the workaround it ran. However, when the container is shutdown it can not be booted again. I get the following error:

> safe_mount: 1425 No such file or directory - Failed to mount "/dev/ttyUSB1" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/ttyUSB1"
> safe_mount: 1425 No such file or directory - Failed to mount "/dev/ttyACM0" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/ttyACM0"
> safe_mount: 1425 No such file or directory - Failed to mount "/dev/ttyACM1" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/ttyACM1"
> run_buffer: 571 Script exited with status 17
> lxc_setup: 3948 Failed to run autodev hooks
> do_start: 1273 Failed to setup container "109"
> sync_wait: 34 An error occurred in another process (expected sequence number 4)
> __lxc_start: 2114 Failed to spawn container "109"
> TASK ERROR: startup for container '109' failed

When mounting /usr/lib/x86_64-linux-gnu/lxc/rootfs/ there was no dev directory. Creating it did not resolve the issue though. Furthermore there is no /dev/ttyACM0 and /dev/ttyACM1 on the root system, why does it try to mount them?

**Comment by tteck** [comment]
Fixed

**Comment by mysteriousHerb** [comment]
> Downgrading and then upgrading jellyfin didn't seem to work for me to resolve the web UI issue. The jellyfin server starts and I can access it from the android app, but the web UI is non-functional. I get this when I type the jellyfin command in the LXC.
> 
> `[16:28:02] [ERR] [1] Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings`
> 
> Appreciate it's not an issue with this script, just wondered if anybody has the same problem, or any suggestions.

I am having the same issue. but this only happens after i changed the IP address from DHCP, strangely.
what i meant is when first running the script the web gui works, then i shut off the lxc and change ip address, and then reboot and i can no longer access gui.
