### ISSUE TITLE
Tailscale alpine support

### ISSUE THREAD

**Issue by btrepp** [tteck/Proxmox#3594]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The new helper that adds tailscale is great, but it assumes a debian/ubuntu LXC
https://github.com/tteck/Proxmox/blob/253da053feff9c39142a58391eac08ccb6aa88f5/misc/add-tailscale-lxc.sh#L66

Alpine actually has tailscale in it's packages already https://pkgs.alpinelinux.org/packages?name=tailscale&branch=edge&repo=&arch=&maintainer=

Could the script somehow detect that the LXC is alpine, and instead of adding all the Debian packages, just run `apk add tailscale`?

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by btrepp** [comment]
Note for anyone else. It does sort of mess up the alpine lxcs if you do run it.

Fine if it's considered a feature, though it did cause some oddity trying to treat alpine as it had apt.

Hopefully at least the comment is searchable for others who have issues
