### ISSUE TITLE
After Rebooting the lxc , it doesnt boot up anymore

### ISSUE THREAD

**Issue by Timdelo** [tteck/Proxmox#36]
Hi,

Thanks a lot for all those scripts.
They seme to work fine, but only if i restart a working LXC, it doesn't want to boot anymore.
Running proxmox 6.2 at the moment.
Pihole does everything fine after a reboot.
Problem is : home assistant, nodered, mqtt..
Any advice?

**Comment by tteck** [comment]
Wow, 6.2, these scripts are designed to utilize LXC 4.0 which was released with PVE 7
To use an older version of LXC you'll have to edit your `.conf` file to change `cgroup2` back to `cgroup`

**Comment by Timdelo** [comment]
Thanks,
Conclusion: Yes I really need to update to 7.1  :-)
