### ISSUE TITLE
what is the password for pihokle

### ISSUE THREAD

**Issue by CoolSoulz** [tteck/Proxmox#3601]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

i dont know what the password for the pihole is

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

first install pihole and then done

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
