### ISSUE TITLE
wireguard update error

### ISSUE THREAD

**Issue by frezeen** [tteck/Proxmox#3609]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

wireguard script dont update if execute from wireguard lxc shell

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

launch wireguard script from lxc shell and reply yes to update it

**Comment by tteck** [comment]
Is your WireGuard installation before 2024-08-21?

**Comment by tteck** [comment]
## 2024-08-21

### Changed

- **WireGuard LXC** [(Commit)](https://github.com/tteck/Proxmox/commit/723365a79df7cc0fd29b1af8f7ef200a7e0921b1)
  - Refactor Code
  - Breaking Change


Update WireGuard via apt

🧐 As this issue is unrelated to the script, it is considered closed.
