### ISSUE TITLE
Error while updating paperless-ngx

### ISSUE THREAD

**Issue by dolomiti70** [tteck/Proxmox#3610]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I got the following error during the update with the script 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"
`✓ Stopped all Paperless-ngx Services`
` | Updating to v2.11.6   `
`[ERROR] in line 81: exit code 0: while executing command pip install -r requirements.txt &> /dev/null`

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

**Comment by dolomiti70** [comment]
Thanks for nothing

**Comment by tteck** [comment]
Don't be lazy!
https://github.com/tteck/Proxmox/issues?q=paperless
