### ISSUE TITLE
Frigate LXC, no update available

### ISSUE THREAD

**Issue by lasharor** [tteck/Proxmox#3625]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Frigate 0.14.1 is available per https://api.github.com/repos/blakeblackshear/frigate/releases/latest

but when trying to update the LXC by issuing the "update" command it says that no new updates are available. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

installed when 1.14.0 was available. 
Go into LXC console
issue update
 ✗ There is currently no update path available.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
It says "There is currently no update path available."

**Comment by fcaronte** [comment]
I noted this today, I was able to update using this trick (very suggested a lxc backup) you need to manually save somewhere else your config because with this dirty update will be replaced then when you are ready launch this command from the frigate console 

bash -c "$(wget -qLO - https://github.com
/tteck/Proxmox/raw/main/install/frigate-install.sh)"


But yes I'm interested to understand how should work the offical updater
![Screenshot_20240830_122300_Chrome](https://github.com/user-attachments/assets/0bdc1cfa-8a09-428c-b16c-fd717627bd01)

**Comment by xekil** [comment]
Same mistake, I opened a topic this morning but I made a mistake, I opened it on [Frigate Github](https://github.com/blakeblackshear/frigate/discussions/13427) .. How to update Frigate simply please? Thanks

**Comment by fcaronte** [comment]
> Same mistake, I opened a topic this morning but I made a mistake, I opened it on [Frigate Github](https://github.com/blakeblackshear/frigate/discussions/13427) .. How to update Frigate simply please? Thanks

Actually I explain how I do myself, then for a one click update I think you need to wait for an official way

**Comment by xekil** [comment]
> > Same mistake, I opened a topic this morning but I made a mistake, I opened it on [Frigate Github](https://github.com/blakeblackshear/frigate/discussions/13427) .. How to update Frigate simply please? Thanks
> 
> Actually I explain how I do myself, then for a one click update I think you need to wait for an official way

thanks, I saw that, but I also have a technique, it is to rebuild a container, that's what I did to go from version 13 to version 14 but I would like an official solution because it's a bit annoying to have to do that with each update ;)

**Comment by fcaronte** [comment]
> > > Same mistake, I opened a topic this morning but I made a mistake, I opened it on [Frigate Github](https://github.com/blakeblackshear/frigate/discussions/13427) .. How to update Frigate simply please? Thanks
> > 
> > Actually I explain how I do myself, then for a one click update I think you need to wait for an official way
> 
> thanks, I saw that, but I also have a technique, it is to rebuild a container, that's what I did to go from version 13 to version 14 but I would like an official solution because it's a bit annoying to have to do that with each update ;)

Ahaha yes I use your same trick from 13 to 14 and this time I try withou reinstall, let's see Witch is the official way to do correctly

**Comment by tteck** [comment]
To update Frigate, create a new container and transfer your configuration.

**Comment by fcaronte** [comment]
umh, seem a ""bit long"" is this lxc use a docker container? can't be update like when use portainer and choose new img version?

**Comment by ADHDSquir** [comment]
This LXC does not use Docker which is wonderful. That means there is one less layer between Frigate and the hardware. Before this great script, the solution was to create an LXC with Docker inside and then install Frigate in that Docker. What a mess trying to map everything through multiple layers!

**Comment by riemers** [comment]
Yeah LXC is indeed nice, it works out of the box. The update lxc containers helps with the o.s. layer if the update function would just download a new version + requirements that would maybe already work.  For now i just reran the install too on the same box and just copied my old config back. Otherwise i have to play around with the disks too as i didn't foresee that i have to split volumes. (i prefer not to loose my old recording if possible, yet not the end fo the world)

**Comment by fcaronte** [comment]
> This LXC does not use Docker which is wonderful. That means there is one less layer between Frigate and the hardware. Before this great script, the solution was to create an LXC with Docker inside and then install Frigate in that Docker. What a mess trying to map everything through multiple layers!

On an old notebook I need to use a custom frigate version and so I work with portainer and there go from version to other is easy. 
On main server I use this script and yes all this script are very useful, what could be performance side difference using natively Vs inside a docker privileged?
