### ISSUE TITLE
iventoy - not using default template causes unopened ports

### ISSUE THREAD

**Issue by solidguy01** [tteck/Proxmox#3676]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

running the helper script for iventoy while not using the default settings resulted in unopened ports, making the application inaccessible

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Using Advanced Settings
Using Distribution: ubuntu
Using ubuntu Version: 24.04
Using Container Type: 1
Using Root Password: ********
Container ID: 132
Using Hostname: iventoy
Using Disk Size: 20
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.1.132/24
Using Gateway IP Address: 192.168.1.1
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Enable Verbose Mode: yes

### Please provide detailed steps to reproduce the issue.

above are the settings used, if i did an nmap scan on the ip the only open port was port 22.

the script gave no errors while running it.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

https://github.com/tteck/Proxmox/issues/3390
