### ISSUE TITLE
[Homarr] Build failure

### ISSUE THREAD

**Issue by CrazyWolf13** [tteck/Proxmox#3684]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Build of the pages seems to hang / fail on my LXC:

here the full log: https://pastebin.com/j6imP7RG

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Here the most important logs:

- warn Restarted static page generation for /ro/401 because it took more than 60 seconds
- warn Restarted static page generation for /en/404 because it took more than 60 seconds
......
- warn Restarted static page generation for /et/404 because it took more than 60 seconds
- warn Restarted static page generation for /lt/404 because it took more than 60 seconds
- warn Restarted static page generation for /ro/404 because it took more than 60 seconds
Static worker unexpectedly exited with code: null and signal: SIGTERM

> Build error occurred
Error: Static page generation for /en/401 is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (/opt/homarr/node_modules/next/dist/build/index.js:697:39)
    at Worker.exportPage (/opt/homarr/node_modules/next/dist/lib/worker.js:88:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/homarr/node_modules/next/dist/export/index.js:519:32
    at async Span.traceAsyncFn (/opt/homarr/node_modules/next/dist/trace/trace.js:103:20)
    at async Promise.all (index 0)
    at async /opt/homarr/node_modules/next/dist/export/index.js:510:9
    at async Span.traceAsyncFn (/opt/homarr/node_modules/next/dist/trace/trace.js:103:20)
    at async /opt/homarr/node_modules/next/dist/build/index.js:1579:21
    at async Span.traceAsyncFn (/opt/homarr/node_modules/next/dist/trace/trace.js:103:20)
 /   ] - info Generating static pages (0/64)
[ERROR] in line 68: exit code 0: while executing command yarn build

### Please provide detailed steps to reproduce the issue.

Install an older version of homarr, try to update.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    __  __
   / / / /___  ____ ___  ____ ___________
  / /_/ / __ \/ __ `__ \/ __ `/ ___/ ___/
 / __  / /_/ / / / / / / /_/ / /  / /
/_/ /_/\____/_/ /_/ /_/\__,_/_/  /_/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: homarr
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Homarr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Installed Homarr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Homarr should be reachable by going to the following URL.
         http://192.168.86.250:3000 
```
```
- info Generating static pages (64/64)
- info Finalizing page optimization  

 \Route (pages)                              Size     First Load JS
┌   /_app                                  0 B             629 kB
├ ● /401                                   741 B           773 kB
├ ● /404                                   719 B           630 kB
├ λ /api/[...trpc]                         0 B             629 kB
├ λ /api/auth/[...nextauth]                0 B             629 kB
├ λ /api/download                          0 B             629 kB
├ λ /api/openapi.json                      0 B             629 kB
├ λ /api/trpc/[trpc]                       0 B             629 kB
├ λ /auth/invite/[inviteId]                2.91 kB         632 kB
├ λ /auth/login                            2.94 kB         632 kB
├ λ /b                                     382 B           846 kB
├ λ /b/[slug]                              387 B           846 kB
├ λ /b/[slug]/customize                    274 B           789 kB
├ λ /board                                 358 B           846 kB
├ λ /board/[slug]                          365 B           846 kB
├ λ /board/[slug]/customize                210 B           789 kB
├ λ /manage                                2.85 kB         791 kB
├ λ /manage/about                          16.1 kB         804 kB
├ λ /manage/boards                         4.98 kB         793 kB
├ λ /manage/tools/docker                   2.29 kB         790 kB
├ λ /manage/tools/swagger                  2.85 kB         791 kB
├   └ css/ad322974924d0826.css             23.1 kB
├ λ /manage/users                          3.64 kB         792 kB
├ λ /manage/users/[userId]/edit            27.4 kB         816 kB
├ λ /manage/users/create                   8.27 kB         796 kB
├ λ /manage/users/invites                  2.79 kB         791 kB
├ λ /onboard                               39.9 kB         669 kB
└ λ /user/preferences                      2.56 kB         775 kB
+ First Load JS shared by all              661 kB
  ├ chunks/framework-18c7e6fcf99e5daa.js   45.2 kB
  ├ chunks/main-2769de4978ba9a12.js        29.4 kB
  ├ chunks/pages/_app-b66c87d9fd92e390.js  553 kB
  ├ chunks/webpack-ea4f82cb74cd22f5.js     2.11 kB
  └ css/b16687c98a5af6ce.css               31.6 kB

ƒ Middleware                               98.4 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

 ✓ Updated Homarr
root@homarr:~# 
```
🧐 As this issue is unrelated to the script, it is considered closed.

Try increasing resources.

**Comment by CrazyWolf13** [comment]
@tteck  The issue WAS related to the script: https://github.com/ajnart/homarr/issues/2125.

The missing things were the following set env vars:
```bash
 export NEXTAUTH_URL="http://WILL_BE_OVERWRITTEN" turbo build
export DATABASE_URL="file:WILL_BE_OVERWRITTEN.sqlite "
```

**Comment by tteck** [comment]
I can build/update just the way the script is currently.
