### ISSUE TITLE
LXC

### ISSUE THREAD

**Issue by titof2375** [tteck/Proxmox#37]
Hello, I was able to install Vaultwarden LXC without any problem, the problem is for the https, I have an inaccessible site. here is the error ERR_HTTP2_PROTOCOL_ERROR.
did you have the problem?

**Comment by tteck** [comment]
I need to add better documentation (not my strong suit)
Vaultwarden needs to be behind a proxy (Nginx Proxy Manager) to obtain HTTPS and to allow clients to connect.

**Comment by titof2375** [comment]
yes absolutely, I go through nginx, after 15 min it works

**Comment by titof2375** [comment]
on the other hand for notioneye jue can not connect me with user admin and the mp Leave Blank.

<html>
<body>


Invalid credentials.
--



</body>
</html>

**Comment by tteck** [comment]
leave blank means put nothing in the password field
