### ISSUE TITLE
Error whit updating spoolman

### ISSUE THREAD

**Issue by Rozenlaan** [tteck/Proxmox#3712]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

✓ Stopped Spoolman Service
 \cp: cannot stat '.env.example': No such file or directory

[ERROR] in line 78: exit code 0: while executing command cp .env.example .env

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

update spoolman

**Comment by tteck** [comment]
Try again https://github.com/tteck/Proxmox/commit/389b03568d9742aa070585be077c7e680954e1de

**Comment by tteck** [comment]
@MickLesk can you take a look at this

**Comment by Rozenlaan** [comment]
thank you for your soon response: now I get: 

✓ Stopped Spoolman Service
 ✓ Updated Spoolman to v0.20.0
 /Job for spoolman.service failed because of unavailable resources or another system error.
See "systemctl status spoolman.service" and "journalctl -xeu spoolman.service" for details.

[ERROR] in line 82: exit code 0: while executing command systemctl start spoolman

root@spoolman:~
#root@spoolman:~# systemctl status spoolman.service
× spoolman.service - Spoolman
     Loaded: loaded (/etc/systemd/system/spoolman.service; enabled; preset: enabled)
     Active: failed (Result: resources) since Wed 2024-09-11 18:16:45 CEST; 3min 16>
        CPU: 0

Sep 11 18:16:45 spoolman systemd[1]: spoolman.service: Scheduled restart job, resta>
Sep 11 18:16:45 spoolman systemd[1]: Stopped spoolman.service - Spoolman.
Sep 11 18:16:45 spoolman systemd[1]: spoolman.service: Start request repeated too q>
Sep 11 18:16:45 spoolman systemd[1]: spoolman.service: Failed with result 'resource>
Sep 11 18:16:45 spoolman systemd[1]: Failed to start spoolman.service - Spoolman.

root@spoolman:~# journalctl -xeu spoolman.service
░░ Automatic restarting of the unit spoolman.service has been scheduled, as the res>
░░ the configured Restart= setting for the unit.
Sep 11 18:16:45 spoolman systemd[1]: Stopped spoolman.service - Spoolman.
░░ Subject: A stop job for unit spoolman.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit spoolman.service has finished.
░░ 
░░ The job identifier is 792 and the job result is done.
Sep 11 18:16:45 spoolman systemd[1]: spoolman.service: Start request repeated too q>
Sep 11 18:16:45 spoolman systemd[1]: spoolman.service: Failed with result 'resource>
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit spoolman.service has entered the 'failed' state with result 'resources'.
Sep 11 18:16:45 spoolman systemd[1]: Failed to start spoolman.service - Spoolman.
░░ Subject: A start job for unit spoolman.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit spoolman.service has finished with a failure.
░░ 
░░ The job identifier is 792 and the job result is failed.
lines 316-340/340 (END)

**Comment by MickLesk** [comment]
You get the error If you Update spoolman, Not by new Installation?

**Comment by Rozenlaan** [comment]
also by new installation

**Comment by Rozenlaan** [comment]
i have not tested it again after change made bij tteck

**Comment by MickLesk** [comment]
Ah i get it, the Developer of spoolman has removed the .env in one of the last Updates. Quickfix will be there tomorrow morning

**Comment by Rozenlaan** [comment]
thank you it is working again!
