### ISSUE TITLE
Error while updating nginxproxymanager

### ISSUE THREAD

**Issue by xijio** [tteck/Proxmox#3713]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I can't update nginxproxymanager using the update command or by running the script in the lxc console.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### Please provide detailed steps to reproduce the issue.

I tried to update nginxproxymanager from the lxc console:
```
root@nginxproxymanager:~# update
-bash: update: command not found
```
so then I used the whole script from the lxc console:
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginxproxymanager.sh)"`
and I get this error:
```
 / Installing pnpm   
[ERROR] in line 65: exit code 0: while executing command npm install -g pnpm@8.15 &> /dev/null
```

I see the steps above about enabling verbose mode, but I don't see any way to enable it for updates.  I googled and found that verbose mode is in the Advanced section which I think you can only select for initial installs.  So this report is two fold:

1) Enable verbose mode for updates (or make it more clear how to enable if it is available)
2) The pnpm error above

**Comment by tteck** [comment]
There is not an Alpine version in this repository.

**Comment by xijio** [comment]
It's running whatever the default is, I didn't know how to check. uname -a doesn't show it.

**Comment by tteck** [comment]
No issue here.

```
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________ __  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                                      /____/                            /____/             
 
 ✓ Stopped Services
 ✓ Cleaned Old Files
 ✓ Downloaded NPM v2.11.3
 ✓ Setup Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Started Services
 ✓ Cleaned
 ✓ Updated Successfully
root@nginxproxymanager:~# 
```

**Comment by xijio** [comment]
How do I run it in verbose mode to get more details of what's going wrong?

**Comment by tteck** [comment]
I would try
```
export NODE_OPTIONS=--openssl-legacy-provider
npm install -g pnpm@8.15
```

**Comment by xijio** [comment]
You're on to something, thank you for the suggestion:

```
root@nginxproxymanager:~# export NODE_OPTIONS=--openssl-legacy-provider
root@nginxproxymanager:~# npm install -g pnpm@8.15
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

Do you know what the right step to get this sorted is?  Should I backup the nginxproxymanager config and redeploy?

**Comment by tteck** [comment]
I will comment out `export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by tteck** [comment]
Try to update again

**Comment by xijio** [comment]
It updated this time, thank you!
