### ISSUE TITLE
nginxproxymanger.sh error updating

### ISSUE THREAD

**Issue by kuntz80** [tteck/Proxmox#3719]
### Please verify that you have read and understood the guidelines.

sort of

### A clear and concise description of the issue.

When running 
```
# /usr/bin/update
```
on Nginx Proxy Manager LXC container the script runs up until:
```
python3 -m pip install --no-cache-dir certbot-dns-cloudflare &>/dev/null
```
and throws an error stating this line (136) is at fault and exits.

(I don't have a copy of the error message as I restored by NPM container from a backup before coming here to report.)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

run **update** in Nginx Proxy Mager LXC container terminal

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/3311
