### ISSUE TITLE
No Update Option in Nextcloud Alpine Script

### ISSUE THREAD

**Issue by Basti-Fantasti** [tteck/Proxmox#3721]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the Alpine NextCloud Hub script inside the Alpine Nextcloud LXC container to check for, or perform updates, there's no Option to do so.

The Credentials can be shown and the Self-signed Certificates can be renewed

![grafik](https://github.com/user-attachments/assets/8e0853b1-abc4-4f6d-8b39-e88fc73e5916)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### Please provide detailed steps to reproduce the issue.

Run the install script inside the Alpine Nextcloud LXC container

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
