### ISSUE TITLE
MagicMirror script is not running on a ubuntu 24 on a container

### ISSUE THREAD

**Issue by HeisemerBub** [tteck/Proxmox#3725]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

when i will start the proxmox script this commands are coming:
![Image 002](https://github.com/user-attachments/assets/d48504e7-1878-4d99-924d-d5e0355a7f5c)

please can you fix this misstake
thanks

i startetd the script so:

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/magicmirror.sh)"
`

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

**Comment by tteck** [comment]
The mistake is, you don't understand how/where to execute the script.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
