### ISSUE TITLE
Tdarr Installing Error

### ISSUE THREAD

**Issue by oOStroudyOo** [tteck/Proxmox#3731]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Hello,

When trying to install Tdarr I get the following error:

```
 / Installing Tdarr   
[ERROR] in line 37: exit code 0: while executing command RELEASE=$(curl -s https://f000.backblazeb2.com/file/tdarrs/versions.json | grep -oP '(?<="Tdarr_Updater": ")[^"]+' | grep linux_x64 | head -n 1)
```

The LXC seems to build fine but Tdarr does not install, I've tried with default and advanced settings but get the same errors.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/709f3e36-6a0f-45f0-9c66-df5c47ed71ab)
![image](https://github.com/user-attachments/assets/f54ee6ea-cac4-4c22-830c-7f03d852981f)

### Please provide detailed steps to reproduce the issue.

Run the helper script.

**Comment by tteck** [comment]
Seems that it's an issue with their link site (backblaze).
https://docs.tdarr.io/docs/installation/windows-linux-macos#tdarr_updater-linux_x64

```
{
  "code": "download_cap_exceeded",
  "message": "Cannot download file, download bandwidth or transaction (Class B) cap exceeded. See the Caps & Alerts page to increase your cap.",
  "status": 403
}
```

**Comment by tteck** [comment]
Working now.
