### ISSUE TITLE
Home Assistant - no addon store available

### ISSUE THREAD

**Issue by Niemand112233** [tteck/Proxmox#3738]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing Home Assistant there should be under "settings -> addons" an addon-store. However, it is missing. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Which Home Assistant are you talking about?

**Comment by tteck** [comment]
Home Assistant OS VM is the ONLY version that has "add-ons" lol
🧐 As this issue is unrelated to the script, it is considered closed.
