### ISSUE TITLE
Commafeed update

### ISSUE THREAD

**Issue by abrazier** [tteck/Proxmox#3745]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The commafeed update script seems to be broken. The error message generated is below.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```__                                __              
  / __/  __ __  _    _/ /  _  __/ /
 / /   /  /  ` /  ` /  `/ /  /  / _ /   /
/ // // / / / / / / / / / / / /_/ / / /  /  / // /
___/_// // /// // //_,//    _/__/_,_/

 ✓ Stopped CommaFeed
 -environment: line 67: rsync: command not found

[ERROR] in line 67: exit code 0: while executing command rsync -a --exclude 'data/' commafeed-${RELEASE}-h2/ /opt/commafeed/```

### Please provide detailed steps to reproduce the issue.

Type update in the console.

**Comment by tteck** [comment]
Looks like a dependency issue. https://github.com/tteck/Proxmox/commit/9db6aa8fbb461a901439f2f8d5ef1ab7b48435c6

**Comment by tteck** [comment]
`apt-get install -y rsync` should get you going again

**Comment by abrazier** [comment]
> `apt-get install -y rsync` should get you going again

yep all good now, thanks!
