### ISSUE TITLE
Alpine NextCloud Hub Office Apps Not Included, Can't Install

### ISSUE THREAD

**Issue by blfriedman** [tteck/Proxmox#3747]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After successful default installation of Alpine NextCloud Hub on Proxmox VE 8.2.4. cannot install the "Hub bundle" or the Collabora Online - Built-in CODE server.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Versions:
Proxmox VE: 8.2.4
NextCloud: [Nextcloud Hub 8](https://nextcloud.com/) (29.0.6)

Error is shown below
![image](https://github.com/user-attachments/assets/a832dccd-5113-4c46-a199-96b2aa55e474)

### Please provide detailed steps to reproduce the issue.

1. Follow basic install directions using the one command from `https://tteck.github.io/Proxmox/#nextcloud-lxc` on the Proxmox VE shell.
2. After successful installation, run the same command from LXC console to get admin credentials for NextCloud, as directed.
3. Log in to the web interface of the NextCloud LXC as ncAdmin.
4. Click on the "N" in the upper right hand corner to get the drop-down menu and choose "+ Apps"
5. Click on the left side menu, "Office & Text"
6. Click on the "Download and Enable" button for the Collabora Online - Build-in CODE Server (see image above).  The actions fails with the error that the image size appears to be incorrect.
7. Similarly, if you choose on the left size menu "App Bundles" and choose the "Hub bundle" "Download and enable all" button, you will get a similar error: `An error occurred during the request. Unable to proceed.
Could not extract app richdocumentscode: Extracted file /var/tmp/nextcloud/oc_tmp_iKGmeM-folder/richdocumentscode/collabora/Collabora_Online.AppImage does not have the correct file size '220725248' (278353088 expected). Archive may be corrupted.`

**Comment by MickLesk** [comment]
I followed the steps 1:1 exactly as you listed them. It worked for me without any problems. After clicking on “download” it was there. Here you can see a screenshot of “My apps” (sorry it's in German, but I think you can understand it) 
<img width="1667" alt="image" src="https://github.com/user-attachments/assets/158085a6-efc5-4a7a-b48b-95d9b158fcd0">


Do you still have enough disk space available? 
Have you read the system requirements? Quote: 

> Linux running on x86-64 or arm64/aarch64
> A glibc based distribution/container (musl libc is not supported)
> Fontconfig (libfontconfig.so.1)
> Additional requirements can be found in [here](https://github.com/CollaboraOnline/richdocumentscode#richdocumentscode)
> The download is rather big so it is possible you will experience a time-out when installing via the web interface. You can use the OCC command install the built-in server from the command-line instead:
> 
> sudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode
> Where wwwrun is the user of your web server. This is www-data on Debian, Ubuntu and derivatives, wwwrun on SUSE based distributions, apache on Red Hat/Fedora and http on Arch linux and derivatives.
> 
> Updates can be done like this:
> 
> sudo -u wwwrun php -d memory_limit=512M ./occ app:update --all
> Of course, alternatively you could increase memory usage and PHP time-outs by default, see the [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)
> 
> Additional troubleshooting tips can be found [here](https://github.com/CollaboraOnline/richdocumentscode?tab=readme-ov-file#troubleshooting).

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
