### ISSUE TITLE
Jellyfin Media Server Script Issue

### ISSUE THREAD

**Issue by stilwellj1983** [tteck/Proxmox#3752]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I tried to run the Jellyfin Media Server script and I get the error 
`[ERROR] in line 624: exit code 0: while executing command pct start "$CTID"`
<img width="709" alt="Screenshot 2024-09-18 at 5 47 27 PM" src="https://github.com/user-attachments/assets/bb6eb76b-182f-4599-8de9-ecbbce3f6d52">

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### Please provide detailed steps to reproduce the issue.

1. copy the script command
2. paste the script command
3. run with default options

**Comment by tteck** [comment]
Looks like an issue with a device. What specs is the server?

**Comment by stilwellj1983** [comment]
RAM - 80 GiB
CPU - 32 x Intel(R) Xeon(R) CPU E5-2450 v2 @ 2.50GHz (2 Sockets)

**Comment by tteck** [comment]
That's an old CPU, without iGPU. Looks like any script that provides hardware acceleration is not going to work for you.

🧐 As this issue is unrelated to the script, it is considered closed.
