### ISSUE TITLE
Navidrome update error

### ISSUE THREAD

**Issue by miloumeeloo** [tteck/Proxmox#3754]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I receive this message when trying to update Navidrome to latest version:
`[ERROR] in line 58: exit code 0: while executing command RELEASE=$(curl -s https://api.github.com/repos/navidrome/navidrome/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')`
I'm actually running version 0.52.5 (c5560888)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
The command
```
curl -s https://api.github.com/repos/navidrome/navidrome/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }'
```
works fine here, outputs `0.53.1`

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by miloumeeloo** [comment]
Thanks. It works now. Don't know why it wasn't before.
