### ISSUE TITLE
MagicMirror install script

### ISSUE THREAD

**Issue by tworth04** [tteck/Proxmox#377]
Hey,

Your install script installs the latest nodejs (which generally i always go for the latest and greatest).  Problem is MagicMirror calls for nodejs v 16.  It works with 18, but there's compatibility issues with other modules, specifically mmpm.   I've linked the repo below for an idea of what it is, but basically it's a helper for magic mirror to modify the config/css/modules and also pulls all the modules together to install easier.

https://github.com/Bee-Mar/mmpm

**Comment by tteck** [comment]
Changed to v16
thanks
