### ISSUE TITLE
[ERROR] in line 58 if i update vaultwarden

### ISSUE THREAD

**Issue by gomble** [tteck/Proxmox#3777]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Want to update vaultwarden but getting this error if i type:  bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"

![image](https://github.com/user-attachments/assets/5c75f6ab-d98f-4ad9-8426-591c772c84f5)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

CPU(s) 16 x 12th Gen Intel(R) Core(TM) i7-1260P (1 Socket)
Kernel Version Linux 6.8.12-2-pve (2024-09-05T10:03Z)
Boot Mode EFI
Manager Version pve-manager/8.2.7/3e0176e6bb2ade3b
Repository Status Proxmox VE updates Non production-ready repository enabled! 

![image](https://github.com/user-attachments/assets/4511bf8d-7b1b-483e-9d69-6724dbf188d9)

### Please provide detailed steps to reproduce the issue.

Updating fails

**Comment by tteck** [comment]
`APK: command not found` sounds like you` re not utilizing Apline

**Comment by tteck** [comment]
OMG, your're in the Unifi container.
