### ISSUE TITLE
Wireguard- Tunnels turn off after reboot

### ISSUE THREAD

**Issue by CarmineCodes** [tteck/Proxmox#3791]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

after installing wireguard lxc using the scripts. the tunnels do not turn on after container reboot.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### Please provide detailed steps to reproduce the issue.

install container using script
do config to create tunnel and client configs
turn on tunnels
reboot container
tunnel turned off

**Comment by tteck** [comment]
Is that a script issue?

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/3632#discussioncomment-10592708
