### ISSUE TITLE
paperless-ngx update failed

### ISSUE THREAD

**Issue by ChristophCaina** [tteck/Proxmox#3793]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

script is failing with the following error:

```
 ✓ Stopped all Paperless-ngx Services
 - Updating to v2.12.1   
[ERROR] in line 81: exit code 0: while executing command pip install -r requirements.txt &> /dev/null
```

Paperless ngx interface is failing with a Bad Gateway error, but after a restart, it seems to be updated.
But the install script did not continue, so it is likely that some parts from the script are missing

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions/3300#discussioncomment-9923938
