### ISSUE TITLE
Cant update Home Assistant Container LXC

### ISSUE THREAD

**Issue by Kwan112** [tteck/Proxmox#38]
Hi

I cant update Home Assistant Container LXC

When i type ./update in Home Assistant Container LXC console, i get a '-bash: ./update: No such file or directory'

what to do?

**Comment by tteck** [comment]
You might be on an older install
type `ls` in the LXC console and share reusults

**Comment by Kwan112** [comment]
update.sh

my install is 6 days old.

it is updating now, while i typed ./update.sh

**Comment by Kwan112** [comment]
Thx alot

**Comment by tteck** [comment]
If you'd like to update to the newest Update Menu, run in the LXC console
```
bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/dev/misc/update-update.sh)"
```
