### ISSUE TITLE
Container WireGuard makes a DNS request every 5 seconds

### ISSUE THREAD

**Issue by daletman** [tteck/Proxmox#3800]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The WireGuard container does send a DNS request every 5 seconds to xrx4fcdff.homelan

I already opened an Issue on the WGDashboard repo:
https://github.com/donaldzou/WGDashboard/issues/403#issue-2549053888

### What settings are you currently utilizing?

Default Settings

**Comment by tteck** [comment]
And how is this a script issue?

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
