### ISSUE TITLE
frigate install problem

### ISSUE THREAD

**Issue by Sysoev86** [tteck/Proxmox#3803]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

>     ______     _             __
>    / ____/____(_)___ _____ _/ /____
>   / /_  / ___/ / __ `/ __ `/ __/ _ \
>  / __/ / /  / / /_/ / /_/ / /_/  __/
> /_/   /_/  /_/\__, /\__,_/\__/\___/
>              /____/
> 
> Using Advanced Settings
> Using Distribution: debian
> Using debian Version: 12
> Using Container Type: 0
> Using Root Password: ********
> Container ID: 126
> Using Hostname: frigate
> Using Disk Size: 20
> Allocated Cores: 4
> Allocated RAM: 4096
> Using Bridge: vmbr100
> Using IP Address: 192.168.100.126/24
> Using Gateway IP Address: 192.168.100.1
> Using APT-Cacher IP Address: Default
> Disable IPv6: yes
> Using Interface MTU Size: Default
> Using DNS Search Domain: Host
> Using DNS Server IP Address: Host
> Using Vlan: Default
> Enable Root SSH Access: yes
> Enable Verbose Mode: no
> Creating a Frigate LXC using the above advanced settings
>  ✓ Using local for Template Storage.
>  ✓ Using local-lvm for Container Storage.
>  ✓ Updated LXC Template List
>  ✓ LXC Container 126 was successfully created.
>  ✓ Started LXC Container
>  ✓ Set up Container OS
>  ✓ Network Connected: 192.168.100.126 
>  ✓ IPv4 Internet Connected
>  ✗ IPv6 Internet Not Connected
>  ✓ DNS Resolved github.com to 2a06:98c1:3121::1
> 2a06:98c1:3120::1
>  ✓ Updated Container OS
>  | Installing Dependencies (Patience)   
> [ERROR] in line 23: exit code 0: while executing command "$@" > /dev/null 2>&1
> The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.
> 

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

<img width="1382" alt="Снимок экрана 2024-09-28 в 20 36 11" src="https://github.com/user-attachments/assets/209d131f-4e25-4bc7-ba26-233b4dbdc303">

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
