### ISSUE TITLE
Whoogle version 0.9.0  available

### ISSUE THREAD

**Issue by anoo2niem** [tteck/Proxmox#3810]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hi,

There seems to be a new version available of Whoogle-search: 
https://pypi.org/project/whoogle-search/#pip

Updating  with the script returns 'Updated Successfully', however it stays on version 0.8.4.

I'm not sure if this is an issue with the script itself or upstream, apologies if it isn't.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Have you tried `systemctl restart whoogle.service`?
