### ISSUE TITLE
Updating Radarr - ✗ There is currently no update path available.

### ISSUE THREAD

**Issue by axel-devs** [tteck/Proxmox#3813]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Getting this error every time I try to update Radarr to v5.11.0.9244

I found #2770 but I'm unsure if it's something on my end. I verified /var/lib/radarr exists and, as far as I know, it hasn't been modified at all.

Default Settings / Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
