### ISSUE TITLE
Error while updating magic Mirror

### ISSUE THREAD

**Issue by f021930c** [tteck/Proxmox#3824]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When I try to update magic mirror 
` - Updating MagicMirror LXC   
[ERROR] in line 68: exit code 0: while executing command git pull &> /dev/null`

Same as this issue  https://github.com/tteck/Proxmox/issues/3688

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`https://i.imgur.com/VcAMYE1.png`

### Please provide detailed steps to reproduce the issue.

Excute update in MagicMirror lxc-console or excute bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/magicmirror.sh)" in lxc-console

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

You even listed the closed issue. Please read the guidelines.
