### ISSUE TITLE
Error updating Updating Home Assistant LXC

### ISSUE THREAD

**Issue by Hoosier-IT** [tteck/Proxmox#3826]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

[ERROR] in line 88: exit code 0: while executing command uv pip install ${BR}--upgrade homeassistant &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

                                _           _     _              _       ___               
  /\  /\___  _ __ ___   ___    /_\  ___ ___(_)___| |_ __ _ _ __ | |_    / __\___  _ __ ___ 
 / /_/ / _ \| '_ ` _ \ / _ \  //_\\/ __/ __| / __| __/ _` | '_ \| __|  / /  / _ \| '__/ _ \
/ __  / (_) | | | | | |  __/ /  _  \__ \__ \ \__ \ || (_| | | | | |_  / /__| (_) | | |  __/
\/ /_/ \___/|_| |_| |_|\___| \_/ \_/___/___/_|___/\__\__,_|_| |_|\__| \____/\___/|_|  \___|
                                                                                           
Updating to Stable Version
 ✓ Stopped Home Assistant
 / Updating Home Assistant   
[ERROR] in line 88: exit code 0: while executing command uv pip install ${BR}--upgrade homeassistant &> /dev/null

### Please provide detailed steps to reproduce the issue.

Running update in Home Assistant Core LXC cli:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homeassistant-core.sh)"

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/3817

https://github.com/tteck/Proxmox/blob/main/CHANGELOG.md#2024-10-03

**Comment by Hoosier-IT** [comment]
Thanks, sir!
