### ISSUE TITLE
Turnkey all-templates - Unknown failure occured.

### ISSUE THREAD

**Issue by hermann-san** [tteck/Proxmox#3829]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When executing the Turnkey all-templates script
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/all-templates.sh)"`
I get the below error message and the install routine doesn't properly start after trying to get the container IP. 
`[ERROR] 1@179 Unknown failure occured.`
Running non-turnkey scripts work (e.g. Yunohost).

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
 Get container storage
CONTAINER_STORAGE=$(select_storage container) || exit
info "Using '$CONTAINER_STORAGE' for container storage."
[INFO] Using 'local-zfs' for container storage.

# Download template
msg "Downloading LXC template (Patience)..."
Downloading LXC template (Patience)...
pveam download $TEMPLATE_STORAGE $TEMPLATE >/dev/null || die "A problem occured while downloading the LXC template."

# Create variable for 'pct' options
PCT_OPTIONS=(${PCT_OPTIONS[@]:-${DEFAULT_PCT_OPTIONS[@]}})
[[ " ${PCT_OPTIONS[@]} " =~ " -rootfs " ]] || PCT_OPTIONS+=(-rootfs $CONTAINER_STORAGE:${PCT_DISK_SIZE:-8})

# Create LXC
msg "Creating LXC container..."
Creating LXC container...
pct create $CTID ${TEMPLATE_STORAGE}:vztmpl/${TEMPLATE} ${PCT_OPTIONS[@]} >/dev/null ||
  die "A problem occured while trying to create container."

# Save password
echo "$NAME password: ${PASS}" >>~/$NAME.creds # file is located in the Proxmox root directory


# Start container
msg "Starting LXC Container..."
Starting LXC Container...
pct start "$CTID"
sleep 5

# Get container IP
set +eEuo pipefail
max_attempts=5
attempt=1
IP=""
while [[ $attempt -le $max_attempts ]]; do
  IP=$(pct exec $CTID ip a show dev eth0 | grep -oP 'inet \K[^/]+')
  if [[ -n $IP ]]; then
    break
  else
    warn "Attempt $attempt: IP address not found. Pausing for 5 seconds..."
    sleep 5
    ((attempt++))
  fi
done
die
[ERROR] 1@179 Unknown failure occured.
root@pve:~# 
```

### Please provide detailed steps to reproduce the issue.

1. Open the pve shell  (Proxmox version  8.2.4)
2. execute the script 
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/all-templates.sh)"`
3. select  ( ) debian-12-turnkey-moodle_18.0-1_amd64.tar.gz   or  ( ) debian-12-turnkey-moodle_18.0-1_amd64.tar.gz    or any other image and click OK
3. The image is downloading and attempting to configure after dowload 100% completed.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
   ___   ____  ______               __     __
  / _ | / / / /_  __/__ __ _  ___  / /__ _/ /____ ___
 / __ |/ / /   / / / -_)  ' \/ _ \/ / _ `/ __/ -_|_-<
/_/ |_/_/_/   /_/  \__/_/_/_/ .__/_/\_,_/\__/\__/___/
                           /_/

[INFO] LXC container '111' was successfully created, and its IP address is 192.168.86.75.

[INFO] Proceed to the LXC console to complete the setup.

[INFO] login: root
[INFO] password: R+vctyl4vEY=

root@server:~# 
```
