### ISSUE TITLE
Paperless-ngx

### ISSUE THREAD

**Issue by Matze1116** [tteck/Proxmox#3843]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I´m running Proxmox with the container Paperless-ngx
By typing "update" into the console i start updating paperless-ngx.

**It shows the following error message:**
    ____                        __                                
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/                                         /____/        
 
 ✓ Stopped all Paperless-ngx Services
 / Updating to v2.12.1   
[ERROR] in line 81: exit code 0: while executing command pip install -r requirements.txt &> /dev/null

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues?q=paperless
