### ISSUE TITLE
Jellyfin / It keeps getting stuck at the “Updating Container OS” stage.

### ISSUE THREAD

**Issue by ghost** [tteck/Proxmox#3845]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Please help me, I tried 4-5 times to install and nothing works.
It keeps getting stuck at the “Updating Container OS” stage.

![screenshot](https://github.com/user-attachments/assets/903d4b8b-cb76-4dd2-b11a-e233e3479589)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
🌐 It seems that you're facing a network problem, _probably_ linked to DNS.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by ghost** [comment]
It would be logical to answer how to fix it.

For some reason, users have a lot of such problems and there is no answer anywhere

**Comment by tteck** [comment]
My focus is on developing application LXC scripts, and maintaining said scripts. I do not specialize in, nor do I have the time to provide support for operational issues. I already stated what I think the issue is. It's up to you to fix it.

**Comment by tteck** [comment]
> I've been using this author's scripts for years, BUT this year the problems started, do you really update your scripts?

I find this insulting, and you ask for special help? No way.
All that you have to do is look at the commits to see if I really update my scripts. 
https://github.com/tteck/Proxmox/commits/main/

Good luck.

**Comment by ghost** [comment]
> > I've been using this author's scripts for years, BUT this year the problems started, do you really update your scripts?
> 
> I find this insulting, and you ask for special help? No way. All that you have to do is look at the commits to see if I really update my scripts. https://github.com/tteck/Proxmox/commits/main/
> 
> Good luck.

I didn't intend to offend you) I appreciate your work) I just thought you could help me, since I didn't make any changes and it's strange to me that the problem is in DNS.
So if there was a specific answer, it could help not only me, but also other users who will see this problem.

Thank you again for your work, be a little kinder to people)
