### ISSUE TITLE
Nextcloud LXC

### ISSUE THREAD

**Issue by damnsanga** [tteck/Proxmox#3848]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Setup of new NextCloud LXC using the helper script (bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nextcloudpi.sh)"
) giving the below from the Proxmox host CLI.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

[Error.txt](https://github.com/user-attachments/files/17267926/Error.txt)

### Please provide detailed steps to reproduce the issue.

The script failed on the first install attempt using the default installation.
The script has failed using advanced (twice with Debian 12, and twice with Ubuntu 24.04)

**Comment by tteck** [comment]
The script runs without any problems from this end.

```
    _   __          __  ________                ______  _ 
   / | / /__  _  __/ /_/ ____/ /___  __  ______/ / __ \(_)
  /  |/ / _ \| |/_/ __/ /   / / __ \/ / / / __  / /_/ / / 
 / /|  /  __/>  </ /_/ /___/ / /_/ / /_/ / /_/ / ____/ /  
/_/ |_/\___/_/|_|\__/\____/_/\____/\__,_/\__,_/_/   /_/   
                                                          
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: nextcloudpi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a NextCloudPi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed NextCloudPi
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

NextCloudPi Setup should be reachable by going to the following URL.
         https://192.168.86.250/ 
```

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
