### ISSUE TITLE
Frigate script

### ISSUE THREAD

**Issue by jazzygff** [tteck/Proxmox#3853]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

install fails on:
[ERROR] in line 57: exit code 0: while executing command wget -q https://github.com/blakeblackshear/frigate/archive/refs/tags/${RELEASE}.tar.gz -O frigate.tar.gz

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

> What settings are you currently utilizing?
Default Settings

> Which Linux distribution are you employing?
Debian 12

One of the two is incorrect.

**Comment by tteck** [comment]
I just tested
```
RELEASE=$(curl -s https://api.github.com/repos/blakeblackshear/frigate/releases/latest | jq -r '.tag_name')
wget -q https://github.com/blakeblackshear/frigate/archive/refs/tags/${RELEASE}.tar.gz -O frigate.tar.gz
```
no issue here.
