### ISSUE TITLE
paperless-ngx fails during login to Github

### ISSUE THREAD

**Issue by jdelliott** [tteck/Proxmox#3856]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I attempted to installed the paperless-ngx using the script. It failed with the following error:

`Setting up libxt6:amd64 (1:1.2.1-1.1) ...
Setting up libcups2:amd64 (2.4.2-3+deb12u8) ...
Setting up libpangoft2-1.0-0:amd64 (1.50.12+ds-1) ...
Setting up libpangocairo-1.0-0:amd64 (1.50.12+ds-1) ...
Setting up libgs10-common (10.0.0~dfsg-11+deb12u5) ...
Setting up librsvg2-2:amd64 (2.54.7+dfsg-1~deb12u1) ...
Setting up tesseract-ocr (5.3.0-2) ...
Setting up libavcodec59:amd64 (7:5.1.6-0+deb12u1) ...
Setting up libgs10:amd64 (10.0.0~dfsg-11+deb12u5) ...
Setting up libchromaprint1:amd64 (1.5.1-2+b1) ...
Setting up libavformat59:amd64 (7:5.1.6-0+deb12u1) ...
Setting up ghostscript (10.0.0~dfsg-11+deb12u5) ...
Setting up unpaper (7.0.0-0.1) ...
 -Processing triggers for man-db (2.11.2-2) ...
 /Processing triggers for libc-bin (2.36-9+deb12u8) ...
 ✓ Installed OCR Dependencies
 /Cloning into '/opt/jbig2enc'...
 \Username for 'https://github.com': 
 /ssword for 'https://github.com': 
 |remote: Repository not found.
fatal: Authentication failed for 'https://github.com/agl/jbig2enc/'

[ERROR] in line 67: exit code 0: while executing command $STD git clone https://github.com/agl/jbig2enc /opt/jbig2enc
root@riker:~# $STD git clone https://github.com/agl/jbig2enc /opt/jbig2enc`

Any ideas what I can do to resolve?

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
Looks like `https://github.com/agl/jbig2enc` has been removed.

**Comment by tteck** [comment]
Switched `jbig2enc` source to `https://github.com/ie13/jbig2enc`

**Comment by jdelliott** [comment]
tteck, you are amazing. I can't believe how quickly you responded when I had an issue. I've played around with Proxmox off and on for about 11 years, and have decided to really set up a system that will do a lot of the things that I want, in the last few weeks. Your scripts have saved me so much time, effort, and heartache.
