### ISSUE TITLE
Tianji installation failed PNPM

### ISSUE THREAD

**Issue by rettyZ** [tteck/Proxmox#3860]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

[ERROR] in line 66: exit code 0: while executing command $STD pnpm install

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

[error.txt](https://github.com/user-attachments/files/17283655/error.txt)

### Please provide detailed steps to reproduce the issue.

During each installation, no matter whether advanced or default

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by tteck** [comment]
It also states 
> (if Advanced Settings, please try Default Settings before creating an issue)

**Comment by rettyZ** [comment]
Yeah but like i said, it happens when i try default too, at first I tried the default settings but when it didn't work I tried using advanced and another system (+ verbose mode). The same error occurs every time.

**Comment by tteck** [comment]
Installing...

**Comment by tteck** [comment]
Sure enough, issues. @MickLesk can you take a look? 🙏🏻

**Comment by MickLesk** [comment]
> Sure enough, issues. @MickLesk can you take a look? 🙏🏻 


Yep, ive already debugged it today, its an pnpm issue, i try tomorrow another version and pull it 🙏

**Comment by tteck** [comment]
Temporally removed from website.

**Comment by MickLesk** [comment]
Fix some things, get the build time from about 30min to ~ 6 - 7 min with same ressources. 

@rettyZ pls check 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/tianji.sh)"

**Comment by tteck** [comment]
```
  _______               _ _ 
 /_  __(_)___ _____    (_|_)
  / / / / __ `/ __ \  / / / 
 / / / / /_/ / / / / / / /  
/_/ /_/\__,_/_/ /_/_/ /_/   
                 /___/      
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: tianji
Using Disk Size: 12
Allocated Cores: 4
Allocated RAM: 4096
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Tianji LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Node.js, pnpm & pm2
 ✓ Set up PostgreSQL
 ✓ Installed Tianji
 ✓ Customized Container
 ✓ Cleaned
 ✓ Set Container to Normal Resources
 ✓ Completed Successfully!

Tianji Setup should be reachable by going to the following URL.
         http://192.168.86.250:12345 
```
