### ISSUE TITLE
Turnkey Script

### ISSUE THREAD

**Issue by Ferdyverse** [tteck/Proxmox#3868]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Turnkey script does not ask for an id or a network device. So it fails for my setup cause there is no vmbr0

![image](https://github.com/user-attachments/assets/67bbe63d-93b2-484b-8d47-6c67d7dc74d9)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by Ferdyverse** [comment]
I know I should be able to change the settings afterwards but something like an ID I can only change via backup and restore. Maybe it is possible to add some minimal settings before creating the container

**Comment by tteck** [comment]
My intention is to maintain the TurnKey scripts in their simplest form, contained within a single file, and with minimal options, if any.
You can download the script, modify and execute.
https://github.com/tteck/Proxmox/blob/6bee7e291ed2894cc056aafb5a59199bd37d6ffe/turnkey/turnkey.sh#L109
