### ISSUE TITLE
Latest Lidarr Update might have broke something?

### ISSUE THREAD

**Issue by Simpuhl** [tteck/Proxmox#3872]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Lidarr doesn't even start, nor will it create any logs to say what is wrong.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

I enabled debug in the config for Lidar and rebooted, no logs get generated to view. I believe something might have happened with the latest stable update they pushed today.

### Please provide detailed steps to reproduce the issue.

Auto update to latest stable lidarr release.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.

```
    __    _     __               
   / /   (_)___/ /___  __________
  / /   / / __  / __ `/ ___/ ___/
 / /___/ / /_/ / /_/ / /  / /    
/_____/_/\__,_/\__,_/_/  /_/     
                                 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 111
Using Hostname: lidarr
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Lidarr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Lidarr
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Lidarr should be reachable by going to the following URL.
         http://192.168.86.250:8686 
```

![Screenshot 2024-10-09 6 19 47 PM](https://github.com/user-attachments/assets/843283ef-ed6d-4b49-9c6c-755eb6139cfd)

![Screenshot 2024-10-09 6 20 29 PM](https://github.com/user-attachments/assets/b604d62a-cd27-4635-9113-63221624e8cf)

**Comment by Simpuhl** [comment]
Thanks for checking
