### ISSUE TITLE
paperless user no longer gets created in LXC container

### ISSUE THREAD

**Issue by c00ntact** [tteck/Proxmox#3875]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have used your paperless script successfully for several month now. As of yesterday, the LXC container that is created no longer has the paperless user configured. As a result, the /op/paperless path has a "1000:1000" ownership. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

run the paperless-ngx.sh script with default settings on proxmox PVE 8.2.7

**Comment by tteck** [comment]
The script has never created the user `paperless`.

https://github.com/tteck/Proxmox/commits/main/install/paperless-ngx-install.sh

**Comment by c00ntact** [comment]
I am not sure how I missed that. Thank you.

**Comment by c00ntact** [comment]
BTW .. thank you VERY much for putting this together this is an AMAZING resource for all us "homelab" enthusiasts!!

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
