### ISSUE TITLE
Zabbix interface not as described.

### ISSUE THREAD

**Issue by jochendemuth** [tteck/Proxmox#3881]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

https://tteck.github.io/Proxmox/#zabbix-lxc 
says to find/connect to the zabbix interface after install as: "Zabbix Interface: IP:5454"

After my successful install I found the zabbix interface at "http://\<IP\>/zabbix/" 
A quick update could save others the trouble.

Thanks for providing these scripts! 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by MickLesk** [comment]
Is it just the description on the website? It is correctly stored in the LXC installer. 
And after successful installation, it also displayed it correctly. 

The website entry need to be adjusted by @tteck 

https://github.com/tteck/Proxmox/blob/6fbb8ab4a218638ca1c8c01f12ab0657c0f4a39b/ct/zabbix.sh#L69-L71

**Comment by tteck** [comment]
fixed
