### ISSUE TITLE
MagicMirror Server not working

### ISSUE THREAD

**Issue by bepp-boop** [tteck/Proxmox#3891]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I try to run the magic mirror in proxmox node but after running nothing happen and the execution just end, no setting, no set up pop up

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by tteck** [comment]
🌐 It seems that you're facing a network problem, _probably_ linked to DNS.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

One of the answers below is incorrect.
> What settings are you currently utilizing?
Default Settings

> Which Linux distribution are you employing?
Alpine
