### ISSUE TITLE
Homeassistant Core LXC issue because of not existing python3.12-dev

### ISSUE THREAD

**Issue by andipohl** [tteck/Proxmox#3892]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

break with all variants of OS.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Building dependency tree... Done
Reading state information... Done
Note, selecting 'python3-pip' instead of 'pip'
 |E: Unable to locate package python3.12-dev
E: Couldn't find any package by glob 'python3.12-dev'
E: Couldn't find any package by regex 'python3.12-dev'

[ERROR] in line 17: exit code 0: while executing command $STD apt-get install -y git curl sudo mc bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libturbojpeg0-dev ffmpeg liblapack3 liblapack-dev dbus-broker libpcap-dev libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libavfilter-dev libmariadb-dev-compat libatlas-base-dev pip python3.12-dev

### Please provide detailed steps to reproduce the issue.

Advanced wizard regardless with options.

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.

**Comment by tteck** [comment]
![Screenshot 2024-10-13 12 44 45 PM](https://github.com/user-attachments/assets/27d9f895-acf8-43d4-9a35-0c639c98b2d1)
![Screenshot 2024-10-13 12 45 33 PM](https://github.com/user-attachments/assets/4a36afeb-d781-4932-adc2-779007ffc9c9)
