### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by Kirdan62** [tteck/Proxmox#39]
Sorry bad english

Maria Db install HowTo:

GRANT ALL ON *.* TO 'admin'@'192.168.100.%' IDENTIFIED BY 'password' WITH GRANT OPTION;  <-- not working HA

GRANT ALL ON *.* TO 'admin'@'192.168.100.0/255.255.255.0' IDENTIFIED BY 'password' WITH GRANT OPTION;   <-- connect HA

Link: https://mariadb.com/kb/en/create-user/#host-name-component

**Comment by tteck** [comment]
> Using 255.255.255.255 is equivalent to not using a netmask at all. Netmasks cannot be used for IPv6 addresses.

Are you using IPv6? 
IPv4 should be ok using a netmask (192.168.100.%)

**Comment by Kirdan62** [comment]
It did not work for me with the input 192.168.2.%. No connection with the HA was established. Only after I used 192.168.2.0/255.255.255.0 a connection was established. I do not useIPv6.

DeepL Translator
