### ISSUE TITLE
Update zigbee2mqtt alpine

### ISSUE THREAD

**Issue by gomble** [tteck/Proxmox#3903]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

![image](https://github.com/user-attachments/assets/283cfbf0-a158-4c29-9458-ebe1e1b0379d)
I installed zigbee2mqtt alpine. It is a old Version: 1.37.1
Zigbee2mqtt is availabe in version:
![image](https://github.com/user-attachments/assets/db23c67b-0134-4ed6-acff-28c867ecf690)
Is it possible to update to the latest version?
If i run update command i am getting:
![image](https://github.com/user-attachments/assets/ad70d9a8-39a1-44c6-80aa-a02c2fc1d4fd)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by tteck** [comment]
Been discussed several times in discussions.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/1375

**Comment by tteck** [comment]
1.37.1 is the latest for Alpine
https://pkgs.alpinelinux.org/packages?name=zigbee2mqtt&branch=edge&repo=&arch=x86_64&origin=&flagged=&maintainer=

**Comment by gomble** [comment]
> 1.37.1 is the latest for Alpine https://pkgs.alpinelinux.org/packages?name=zigbee2mqtt&branch=edge&repo=&arch=x86_64&origin=&flagged=&maintainer=

@tteck There ist now 1.40.2
![image](https://github.com/user-attachments/assets/7a253351-b4db-4b6c-85b4-d556b6a45c0f)
but if it run your update script i am not getting 1.40.2

![image](https://github.com/user-attachments/assets/9ffc3135-b065-443e-881d-586a030d9dd0)

![image](https://github.com/user-attachments/assets/8dece4b2-5218-4ce7-8e94-ab1ecb0b033e)
