### ISSUE TITLE
Jellyseer Script Error

### ISSUE THREAD

**Issue by very-old-guy** [tteck/Proxmox#3904]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Trying to use Jellyfin Script and ALWAYS comes up with this error.  Tried on existing and new installs of Proxmox.  Also happens Default and Advanced and Ubuntu if I try to use that version

Overseer installs fine.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

 __  / / _ \/ / / / / / ___/ _ \/ _ \/ ___/ ___/
/ /_/ /  __/ / / /_/ (__  )  __/  __/ /  / /
\____/\___/_/_/\__, /____/\___/\___/_/  /_/
              /____/
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 206
Using Hostname: jellyseerr
Using Disk Size: 10
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.21.206/24
Using Gateway IP Address: 192.168.21.1
Using APT-Cacher IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Jellyseerr LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 206 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.21.206 fdd3:3810:8584:6cb3:be24:11ff:fe9a:b33c 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 4.237.22.38
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Yarn
 / Installing Jellyseerr (Patience)   
[ERROR] in line 44: exit code 0: while executing command CYPRESS_INSTALL_BINARY=0 yarn install --frozen-lockfile --network-timeout 1000000 &> /dev/null

### Please provide detailed steps to reproduce the issue.

Happends every time I try to install.

**Comment by MickLesk** [comment]
Please next time use the verbose mode. Then we see the full error. 

ive found the issue and fixed it. The developer now uses pnpm to install all dependencies. (Breaking Change). I test my installation and push the bugfix to ttecks repo later

**Comment by pafade89** [comment]
Hi @tteck 

now your script is working fine. The only thing I recognized is, if you using the picture cache internal for Jellyseerr you have to resize your disk from 8gb to approx. 15gb.

Cheers P

**Comment by tteck** [comment]
@pafade89 I thought you were getting `[ERROR] in line 68: exit code 0: while executing command output=$(git pull)`?

**Comment by pafade89** [comment]
> @pafade89 I thought you were getting `[ERROR] in line 68: exit code 0: while executing command output=$(git pull)`?

Yes of course. But after I resized the disk it worked for me. Should I replicate the error for you?

**Comment by tteck** [comment]
I made changes (https://github.com/tteck/Proxmox/commit/6e7b5d80220d77f94d410b7a537234a0da7d536e) based on your unedited post.

**Comment by pafade89** [comment]
I just restored an old LXC and only adjusted the RAM and processor cores according to your specifications. After that, I received the following error.
```
       __     ____
      / /__  / / /_  __________  ___  __________
 __  / / _ \/ / / / / / ___/ _ \/ _ \/ ___/ ___/
/ /_/ /  __/ / / /_/ (__  )  __/  __/ /  / /
\____/\___/_/_/\__, /____/\___/\___/_/  /_/
              /____/
 ✗ pnpm not found. Installing...
 \remote: Enumerating objects: 1586, done.
remote: Counting objects: 100% (1426/1426), done.
remote: Compressing objects: 100% (612/612), done.
remote: Total 1586 (delta 961), reused 1119 (delta 723), pack-reused 160 (from 1)
Receiving objects: 100% (1586/1586), 1.49 MiB | 13.31 MiB/s, done.
Resolving deltas: 100% (1006/1006), completed with 105 local objects.
From https://github.com/Fallenbagel/jellyseerr
   65def9d2..63dfe003  main                      -> origin/main
 * [new branch]        all-contributors/add-Bretterteig -> origin/all-contributors/add-Bretterteig
   31ca32df..9de304d1  develop                   -> origin/develop
   900e6110..dd2c752c  feat-server-type-setup    -> origin/feat-server-type-setup
 * [new branch]        feat-streaming-region     -> origin/feat-streaming-region
 * [new branch]        fix-avatarproxy           -> origin/fix-avatarproxy
 * [new branch]        fix-button-links-from-details-page -> origin/fix-button-links-from-details-page
 * [new branch]        fix-library-toggle        -> origin/fix-library-toggle
 * [new branch]        fix/user-warning-length-of-undefined -> origin/fix/user-warning-length-of-undefined
 * [new branch]        override-rules            -> origin/override-rules
 * [new branch]        pr-934                    -> origin/pr-934
 * [new branch]        remove-language-profiles  -> origin/remove-language-profiles
 * [new tag]           preview-fix-users-warning -> preview-fix-users-warning
 * [new tag]           preview-override-rules    -> preview-override-rules
 * [new tag]           v2.0.0                    -> v2.0.0
 * [new tag]           preview-jellyfin-emby-server-type -> preview-jellyfin-emby-server-type
 -
[ERROR] in line 78: exit code 0: while executing command pnpm build &> /dev/null
```

After doing the steps above again, but in this case with resizing the storage to 15 gb it works:

```
       __     ____
      / /__  / / /_  __________  ___  __________
 __  / / _ \/ / / / / / ___/ _ \/ _ \/ ___/ ___/
/ /_/ /  __/ / / /_/ (__  )  __/  __/ /  / /
\____/\___/_/_/\__, /____/\___/\___/_/  /_/
              /____/
 ✗ pnpm not found. Installing...
 -remote: Enumerating objects: 1586, done.
remote: Counting objects: 100% (1426/1426), done.
remote: Compressing objects: 100% (612/612), done.
remote: Total 1586 (delta 961), reused 1119 (delta 723), pack-reused 160 (from 1)
Receiving objects: 100% (1586/1586), 1.49 MiB | 13.54 MiB/s, done.
Resolving deltas: 100% (1006/1006), completed with 105 local objects.
 |From https://github.com/Fallenbagel/jellyseerr
   65def9d2..63dfe003  main                      -> origin/main
 * [new branch]        all-contributors/add-Bretterteig -> origin/all-contributors/add-Bretterteig
   31ca32df..9de304d1  develop                   -> origin/develop
   900e6110..dd2c752c  feat-server-type-setup    -> origin/feat-server-type-setup
 * [new branch]        feat-streaming-region     -> origin/feat-streaming-region
 * [new branch]        fix-avatarproxy           -> origin/fix-avatarproxy
 * [new branch]        fix-button-links-from-details-page -> origin/fix-button-links-from-details-page
 * [new branch]        fix-library-toggle        -> origin/fix-library-toggle
 * [new branch]        fix/user-warning-length-of-undefined -> origin/fix/user-warning-length-of-undefined
 * [new branch]        override-rules            -> origin/override-rules
 * [new branch]        pr-934                    -> origin/pr-934
 * [new branch]        remove-language-profiles  -> origin/remove-language-profiles
 * [new tag]           preview-fix-users-warning -> preview-fix-users-warning
 * [new tag]           preview-override-rules    -> preview-override-rules
 * [new tag]           v2.0.0                    -> v2.0.0
 * [new tag]           preview-jellyfin-emby-server-type -> preview-jellyfin-emby-server-type
 ✓ Updated Jellyseerr
```

**Comment by tteck** [comment]
@pafade89 Could I bother you again and ask if you would redo your second test (after resizing storage) I made more changes.

**Comment by pafade89** [comment]
@tteck Yes, absolutely, I'd be happy to help, and this is how it looks now.

```
       __     ____
      / /__  / / /_  __________  ___  __________
 __  / / _ \/ / / / / / ___/ _ \/ _ \/ ___/ ___/
/ /_/ /  __/ / / /_/ (__  )  __/  __/ /  / /
\____/\___/_/_/\__, /____/\___/\___/_/  /_/
              /____/
 ✗ pnpm not found. Installing...
 ✓ Updated Jellyseerr
```
