### ISSUE TITLE
Radarr script failing

### ISSUE THREAD

**Issue by popeter1** [tteck/Proxmox#3915]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

trying to run the radarr script following standard setting (debian 12 but bespoke container number and network settings) and failing
in verbose mode getting a 404 to a radarr url

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

✓ Installed Dependencies
 /--2024-10-17 22:19:52--  https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
Resolving radarr.servarr.com (radarr.servarr.com)... 2606:4700:3037::6815:369, 2606:4700:3036::ac43:8291, 104.21.3.105, ...
Connecting to radarr.servarr.com (radarr.servarr.com)|2606:4700:3037::6815:369|:443... connected.
 \404 Not Foundnt, awaiting response... 
2024-10-17 22:19:52 ERROR 404: Not Found.

[ERROR] in line 26: exit code 0: while executing command $STD wget --content-disposition 'https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'

### Please provide detailed steps to reproduce the issue.

run script as provided, default produces same error

**Comment by tteck** [comment]
The issue is on their end (404).
Nothing has changed https://wiki.servarr.com/radarr/installation/linux

**Comment by tteck** [comment]
Yep, they're having troubles
https://discord.com/channels/264387956343570434/728452258605301790

**Comment by tteck** [comment]
Keep trying, it will be back up soon.

**Comment by tteck** [comment]
🧐 As this issue is unrelated to the script, it is considered closed.
