### ISSUE TITLE
Nginx Proxy Manager LXC install script seems to misinstall certbot-dns-cloudflare

### ISSUE THREAD

**Issue by dullin** [tteck/Proxmox#3929]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After a clean installation of Nginx Proxy Manager LXC. installed with all the defaults (with the option N to use an older version of pnpm). I tried installing a wildcard cert for my domain using dns challenges.

This errors out with a weird error seen https://github.com/NginxProxyManager/nginx-proxy-manager/issues/4040 where the dns-cloudflare options are not recognized by certbot.

After investigating the command run by certbot and fiddling around, I got the error message that the dns-cloudflare plugin was not installed.

Diggin trough the script I saw that it was supposed to be installed, so I tried running the same command to install it and it fixed the issue.

I'm unsure what can mitigate the issue though, you might have more insights in your scripts. I tried re-creating another LXC container with the script to see if it was a one-off and it had the same error.

PS. THANK YOU for all your hard work. Those scripts are a godsend.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Command to test that the dns-cloudfare plugin is not recognized after a clean install 
```
certbot -v certonly --config '/etc/letsencrypt.ini' --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name 'npm-16' --agree-tos --email 'my@email.com' --domains '*.mydomain.tld' --dns-cloudflare
```

Gives the error 
```
The requested dns-cloudflare plugin does not appear to be installed
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.
```

To then reinstall the plugin, I used the same command as the install script
```
python3 -m pip install --no-cache-dir certbot-dns-cloudflare
```

Which downloaded and gave the following log showing that new things were added
```
root@nginxproxymanager:/# python3 -m pip install --no-cache-dir certbot-dns-cloudflare
Collecting certbot-dns-cloudflare
  Downloading certbot_dns_cloudflare-2.11.0-py3-none-any.whl (13 kB)
Collecting cloudflare<2.20,>=1.5.1
  Downloading cloudflare-2.19.4.tar.gz (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.4/118.4 kB 18.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools>=41.6.0 in /usr/lib/python3/dist-packages (from certbot-dns-cloudflare) (66.1.1)
Requirement already satisfied: acme>=2.11.0 in /usr/local/lib/python3.11/dist-packages (from certbot-dns-cloudflare) (2.11.0)
Requirement already satisfied: certbot>=2.11.0 in /usr/local/lib/python3.11/dist-packages (from certbot-dns-cloudflare) (2.11.0)
Requirement already satisfied: cryptography>=3.2.1 in /usr/local/lib/python3.11/dist-packages (from acme>=2.11.0->certbot-dns-cloudflare) (43.0.3)
Requirement already satisfied: josepy>=1.13.0 in /usr/local/lib/python3.11/dist-packages (from acme>=2.11.0->certbot-dns-cloudflare) (1.14.0)
Requirement already satisfied: PyOpenSSL!=23.1.0,>=17.5.0 in /usr/local/lib/python3.11/dist-packages (from acme>=2.11.0->certbot-dns-cloudflare) (24.2.1)
Requirement already satisfied: pyrfc3339 in /usr/local/lib/python3.11/dist-packages (from acme>=2.11.0->certbot-dns-cloudflare) (1.1)
Requirement already satisfied: pytz>=2019.3 in /usr/local/lib/python3.11/dist-packages (from acme>=2.11.0->certbot-dns-cloudflare) (2024.2)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from acme>=2.11.0->certbot-dns-cloudflare) (2.28.1)
Requirement already satisfied: ConfigArgParse>=1.5.3 in /usr/local/lib/python3.11/dist-packages (from certbot>=2.11.0->certbot-dns-cloudflare) (1.7)
Requirement already satisfied: configobj>=5.0.6 in /usr/local/lib/python3.11/dist-packages (from certbot>=2.11.0->certbot-dns-cloudflare) (5.0.9)
Requirement already satisfied: distro>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from certbot>=2.11.0->certbot-dns-cloudflare) (1.9.0)
Requirement already satisfied: parsedatetime>=2.4 in /usr/local/lib/python3.11/dist-packages (from certbot>=2.11.0->certbot-dns-cloudflare) (2.6)
Collecting jsonlines
  Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Collecting pyyaml
  Downloading PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (762 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.0/763.0 kB 70.7 MB/s eta 0:00:00
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3/dist-packages (from cryptography>=3.2.1->acme>=2.11.0->certbot-dns-cloudflare) (1.15.1)
Collecting attrs>=19.2.0
  Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 900.8 MB/s eta 0:00:00
Building wheels for collected packages: cloudflare
  Building wheel for cloudflare (setup.py) ... done
  Created wheel for cloudflare: filename=cloudflare-2.19.4-py2.py3-none-any.whl size=121049 sha256=7cd14f14724665e69efe1023e21d521659ac0db2242cbf1334f199b1d6fbacac
  Stored in directory: /tmp/pip-ephem-wheel-cache-7l1a_map/wheels/0d/4e/9d/1d94e28c2d0cc05560f82809165e8a7cde151dc29dc0adab35
Successfully built cloudflare
Installing collected packages: pyyaml, attrs, jsonlines, cloudflare, certbot-dns-cloudflare
Successfully installed attrs-24.2.0 certbot-dns-cloudflare-2.11.0 cloudflare-2.19.4 jsonlines-4.0.0 pyyaml-6.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

After that installation of the dns, the plugin is now detected and using the GUI works as it should.

### Please provide detailed steps to reproduce the issue.

Minimal version
* Run the Nginx Proxy Manager LXC script with all defaults on host
* In the container, run `certbot -v certonly --config '/etc/letsencrypt.ini' --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name 'npm-16' --agree-tos --email 'my@email.com' --domains '*.mydomain.tld' --dns-cloudflare` and see that it fails
* In the container, run `python3 -m pip install --no-cache-dir certbot-dns-cloudflare`
* In the container, rerun certbot command and see that the error for the missing plugin disapears

**Comment by tteck** [comment]
![Screenshot 2024-10-18 8 48 39 PM](https://github.com/user-attachments/assets/dc744e80-0cef-4829-b6af-658ea71175d5)

**Comment by tteck** [comment]
> I used the same command as the install script

That command is not in the script.

**Comment by dullin** [comment]
I am ashamed and will go back to reading the big red siren warnings. Thank you for your time.
