### ISSUE TITLE
Cockpit script output address not https

### ISSUE THREAD

**Issue by mastervash** [tteck/Proxmox#3938]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After successfully completing the script prints the URL where Cockpit should be reachable as an http address - which is of course unreachable. Cockpit only listens on https by default.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by tteck** [comment]
The Cockpit interface is reachable, you must have patience. Wait until the page fully loads.

**Comment by tteck** [comment]
It redirects all HTTP connections to HTTPS. Exceptions are connections from **localhost** and for certain URLs (`ping`). 
https://cockpit-project.org/guide/latest/cockpit.conf.5
Look for `AllowUnencrypted`
