### ISSUE TITLE
Overseerr Update script fails at line 70

### ISSUE THREAD

**Issue by JNR8** [tteck/Proxmox#3941]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running "update" from within the LXC Console the script fails at line 70 during the yarn build process. 
 
I have chcked the current Overseerr version installed (1.33.2) against the currently released version (also 1.33.2).  It seems that when there is no update available the script fails.  Although I could be wrong about that as it's just a guess.  

I have successfully used this script to update overseerr versions in the past.

I have also checked to see if there are any app or OS updates needing to be applied.  There are not.  The OS has all patches and software updates applied as of todays date.  

FYI:  although I used advanced settings during install of the LXC the only setting that is different from default is the static IP address.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
   ____
  / __ \_   _____  _____________  ___  __________
 / / / / | / / _ \/ ___/ ___/ _ \/ _ \/ ___/ ___/
/ /_/ /| |/ /  __/ /  (__  )  __/  __/ /  / /
\____/ |___/\___/_/  /____/\___/\___/_/  /_/

 /remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 142 (delta 72), reused 82 (delta 40), pack-reused 9 (from 1)
Receiving objects: 100% (142/142), 546.05 KiB | 13.00 MiB/s, done.
Resolving deltas: 100% (72/72), completed with 15 local objects.
 |From https://github.com/sct/overseerr
   b6fe5ac6..4aac4912  develop                 -> origin/develop
 * [new branch]        fix/add-ping-user-logs  -> origin/fix/add-ping-user-logs
 + 85bac28d...d9f39fab renovate/all-minor-patch -> origin/renovate/all-minor-patch  (forced update)
 + acbd0cdf...efa5df7e renovate/express-openapi-validator-5.x -> origin/renovate/express-openapi-validator-5.x  (forced update)
 + 8240b4c4...edd67b5c renovate/github-actions -> origin/renovate/github-actions  (forced update)
 + 73fc35bb...9ab9e998 renovate/major-github-actions -> origin/renovate/major-github-actions  (forced update)
 + 7f363069...814db208 renovate/major-nextjs-monorepo -> origin/renovate/major-nextjs-monorepo  (forced update)
 + 53e50977...fafa6342 renovate/major-semantic-release-monorepo -> origin/renovate/major-semantic-release-monorepo  (forced update)
 + 96609396...8fa267a3 renovate/prettier-3.x   -> origin/renovate/prettier-3.x  (forced update)
 + bc0342fb...1d706cdf renovate/svgr-webpack-8.x -> origin/renovate/svgr-webpack-8.x  (forced update)
 + 41da1645...d2a20511 renovate/typescript-5.x -> origin/renovate/typescript-5.x  (forced update)
 + 6033454a...f388887e renovate/yup-1.x        -> origin/renovate/yup-1.x  (forced update)
 |
[ERROR] in line 70: exit code 0: while executing command yarn build &> /dev/null'''
```

### Please provide detailed steps to reproduce the issue.

connect to lxc console
run "update" script.
wait for failure.

**Comment by tteck** [comment]
No issue here. Try increasing resources.

**Comment by JNR8** [comment]
Double RAM from 1gb to 2gb.  That worked nicely.  Thank you.
