### ISSUE TITLE
Turnkey Nextcloud script fails

### ISSUE THREAD

**Issue by lukasz-lobocki** [tteck/Proxmox#3943]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When spawning `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/turnkey/turnkey.sh)"` from pve shell, after selecting `nextcloud` it aborts with error. Shown below.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
[INFO] Using 'local' for template storage.
[INFO] Using 'local-lvm' for container storage.
Updating LXC template list...
Creating LXC container...
Starting LXC Container...
[ERROR] 1@212 Unknown failure occured.
  Logical volume "vm-103-disk-0" successfully removed.
root@pve:~#
```

### Please provide detailed steps to reproduce the issue.

There is a **workaround**. Script left the `debian-12-turnkey-nextcloud_18.1-1_amd64.tar.gz` template behind. I successfully installed it manually.

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
 ______              __ __           __   _  _______
/_  __/_ _________  / //_/__ __ __  / /  | |/_/ ___/
 / / / // / __/ _ \/ ,< / -_) // / / /___>  </ /__
/_/  \_,_/_/ /_//_/_/|_|\__/\_, / /____/_/|_|\___/
                           /___/

[INFO] LXC container '111' was successfully created, and its IP address is 192.168.86.77.

[INFO] Proceed to the LXC console to complete the setup.

[INFO] login: root
[INFO] password: zqzx018Roz0=

```

🧐 As this issue is unrelated to the script, it is considered closed.
