### ISSUE TITLE
photoprism webui

### ISSUE THREAD

**Issue by joaofgf** [tteck/Proxmox#395]
Installed successfully photoprism
 `Using Default Settings
Using CT Type Unprivileged NO DEVICE PASSTHROUGH
Using CT Password Automatic Login
Using CT ID 114
Using CT Name photoprism
Using Disk Size 8GB
Using 2vCPU
Using 2048MiB RAM
Using Bridge vmbr0
Using Static IP Address DHCP
Using Gateway Address NONE
Using VLAN Tag NONE
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 114 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.215 
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Golang
 ✓ Installed Tensorflow
 ✓ Cloned PhotoPrism
 ✓ Built PhotoPrism
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

PhotoPrism should be reachable by going to the following URL.
      http://192.168.1.215:2342 `

But the browser gives the error "connection denied"
thanks in advance

**Comment by tteck** [comment]
Looks like the [Authentication](https://docs.photoprism.app/getting-started/config-options/) requirements has changed 

do `nano /var/lib/photoprism/.env` and add `PHOTOPRISM_AUTH_MODE='password'` above `PHOTOPRISM_ADMIN_PASSWORD='admin'` then reboot LXC

Let me know if that works for you

**Comment by tteck** [comment]
Also, they now require that the initial admin PASSWORD, must have at least 8 characters
I set the install script to `PHOTOPRISM_ADMIN_PASSWORD='changeme'`

**Comment by joaofgf** [comment]
thank you very much. the problem remains
![image](https://user-images.githubusercontent.com/1038868/182226712-d6817c88-2401-401d-ac90-22b19e43caa8.png)
![image](https://user-images.githubusercontent.com/1038868/182226846-0f1c9f8c-f54d-43ca-b779-e830c8c932da.png)
rebooted and tried.
i also tried with the correct ip address.
thanks ;)

**Comment by tteck** [comment]
Is it running? `systemctl status photoprism`

**Comment by tteck** [comment]
Try `PHOTOPRISM_AUTH_MODE='public'` to see if you can get in

**Comment by joaofgf** [comment]
> Is it running? `systemctl status photoprism`

![image](https://user-images.githubusercontent.com/1038868/182252220-16b2a6c9-53b1-4b09-90b5-6b2f7dee51fa.png)

**Comment by joaofgf** [comment]
> Try `PHOTOPRISM_AUTH_MODE='public'` to see if you can get in

same result: connection refused.

**Comment by joaofgf** [comment]
maybe it's a local problem from my system?

**Comment by tteck** [comment]
I'll try and find time today to install it and test

**Comment by tteck** [comment]
It's not your system. Same issue here. I'm gonna pull it off of the list until I feel like trying to fix.
I'll keep you informed.

**Comment by joaofgf** [comment]
thank you very much.

**Comment by timdonovanuk** [comment]
FYI it looks like the .env file (/var/lib/photoprism/.env) is not being picked up by photoprism. 

If you do `/opt/photoprism/bin/photoprism config` you'll see it's missing many values that are set in the .env file. The first missing value that stops this running in the lxc is originals-path (PHOTOPRISM_ORIGINALS_PATH). You can see this by doing 

```
root@lxc-photoprism:/opt/photoprism# /opt/photoprism/bin/photoprism up
FATA[2022-08-07T21:11:23Z] invalid originals path, check configuration and permissions
```

and fix it by doing e.g. `export PHOTOPRISM_ORIGINALS_PATH="/tmp"`.

However, then it complains about the next missing env, import path. And so on :)

I cannot see why, as the `/etc/systemd/system/photoprism.service` file points to the right .env file.

**Comment by tteck** [comment]
If you're saying that the `.env` and the `config` should be the same then this would work
```
cat <<EOF >  /opt/photoprism/bin/photoprism config
PHOTOPRISM_AUTH_MODE="password"
PHOTOPRISM_ADMIN_PASSWORD="changeme"
PHOTOPRISM_HTTP_HOST="0.0.0.0"
PHOTOPRISM_HTTP_PORT="2342"
PHOTOPRISM_STORAGE_PATH="/var/lib/photoprism/storage"
PHOTOPRISM_ORIGINALS_PATH="/var/lib/photoprism/photos/Originals"
PHOTOPRISM_IMPORT_PATH="/var/lib/photoprism/photos/Import"
EOF
```

**Comment by timdonovanuk** [comment]
`/opt/photoprism/bin/photoprism config` is just a command that outputs the config that photoprism currently sees. Looks like photoprism uses env vars to drive all config values. The primary issue seems to be in/etc/systemd/system/photoprism.service, because it should load all the env vars but it does not.

**Comment by tteck** [comment]
oh, I see. Wonder why it's not picking up the `.env` file?

**Comment by timdonovanuk** [comment]
Not sure, is a weird one! I've found something about the file not being passed to child processes...not sure if that is related

https://serverfault.com/questions/828999/systemd-environment-and-environmentfile-not-working

It's possible to set the env vars directly in the service file. I tried, clearly typoed something and broke it. Time for bed :)

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment=

**Comment by cklam2** [comment]
Finally got it working. In `/etc/systemd/system/photoprism.service` removed the entire line with `EnvironmentFile` and replaced with individual Environment entries like so
```
[Service]
Type=forking
User=root
WorkingDirectory=/opt/photoprism
Environment="PHOTOPRISM_AUTH_MODE=public"
Environment="PHOTOPRISM_HTTP_HOST=0.0.0.0"
Environment="PHOTOPRISM_HTTP_PORT=2342"
Environment="PHOTOPRISM_STORAGE_PATH=/var/lib/photoprism/storage"
Environment="PHOTOPRISM_ORIGINALS_PATH=/var/lib/photoprism/photos/Originals"
Environment="PHOTOPRISM_IMPORT_PATH=/var/lib/photoprism/photos/Import"
ExecStart=/opt/photoprism/bin/photoprism up -d
ExecStop=/opt/photoprism/bin/photoprism down
```

I also had to remove the 2 .gz file from the root (_go1.18.3.linux-amd64.tar.gz_ and _libtensorflow-linux-avx2-1.15.2.tar.gz_) cause otherwise the app won't start either and will show an error about unrecognized character in go1.18.3.linux-amd64.tar.gz

Then called `systemctrl daemon-reload` and then `systemctl restart photoprism`.

**Comment by tteck** [comment]
Awesome! I'll make those changes.

Edit: Didn't work for me.

**Comment by cklam2** [comment]
Well, that is annoying. Yesterday that trick worked for me, also after restarts. But this morning the container crashed for some reason and it didn't want to start up anymore, with same message about Originals path. 

Tried several things a finally gave up on the environment variables.
Instead, created file `options.yml` in `/var/lib/photoprism` with following content:
```
AuthMode: password
AdminPassword: changeme

HttpPort: 2342
HttpHost: 0.0.0.0

StoragePath: /var/lib/photoprism/storage
OriginalsPath: /var/lib/photoprism/photos/Originals
ImportPath: /var/lib/photoprism/photos/Import
```

In the photoprism.service removed all environment related lines and changed ExecStart to the following:
`/opt/photoprism/bin/photoprism --config-path /var/lib/photoprism/ up -d`

Note: photoprism will look for a file called options.yml in the path so no need to specify that in the argument.

Did several restarts and that seems to work. Fingers crossed that it'll also survive potential crashes....

**Comment by cklam2** [comment]
Tested the above using the changes in my branch and it works.
Created a PR: https://github.com/tteck/Proxmox/pull/442

Please have a look when you have time :)

**Comment by cklam2** [comment]
Tip: for people who want to customize the configuration in `options.yml`, unfortunately the available fields are not documented. 
But you can find the complete list in this source file: [options.go](https://github.com/photoprism/photoprism/blob/release/internal/config/options.go)

**Comment by tteck** [comment]
Still not working for me. A `/opt/photoprism/bin/photoprism config` reveals 
```
|------------------------|-----------------------------------------------|
|         Value          |                     Name                      |
|------------------------|-----------------------------------------------|
| auth-mode              | password                                      |
| admin-password         |                                               |
| public                 | false                                         |
| log-level              | info                                          |
| debug                  | false                                         |
| trace                  | false                                         |
| config-path            | /root/.photoprism/storage/config              |
| options-yaml           | /root/.photoprism/storage/config/options.yml  |
| defaults-yaml          | /etc/photoprism/defaults.yml                  |
| settings-yaml          | /root/.photoprism/storage/config/settings.yml |
| originals-path         |                                               |
| originals-limit        |                                          1000 |
| resolution-limit       |                                           100 |
| storage-path           | /root/.photoprism/storage                     |
| sidecar-path           | /root/.photoprism/storage/sidecar             |
| albums-path            | /root/.photoprism/storage/albums              |
| backup-path            | /root/.photoprism/storage/backup              |
| cache-path             | /root/.photoprism/storage/cache               |
| cmd-cache-path         | /root/.photoprism/storage/cache/cmd           |
| thumb-cache-path       | /root/.photoprism/storage/cache/thumbnails    |
| import-path            |                                               |
| assets-path            | /opt/photoprism/assets                        |
| static-path            | /opt/photoprism/assets/static                 |
| build-path             | /opt/photoprism/assets/static/build           |
| img-path               | /opt/photoprism/assets/static/img             |
| templates-path         | /opt/photoprism/assets/templates              |
| temp-path              | /tmp/photoprism_00000000                      |
| workers                |                                             1 |
| wakeup-interval        | 15m0s                                         |
| auto-index             |                                           300 |
| auto-import            |                                           180 |
| read-only              | false                                         |
| experimental           | false                                         |
| disable-webdav         | false                                         |
| disable-settings       | false                                         |
| disable-places         | false                                         |
| disable-backups        | false                                         |
| disable-tensorflow     | false                                         |
| disable-faces          | false                                         |
| disable-classification | false                                         |
| disable-ffmpeg         | false                                         |
| disable-exiftool       | false                                         |
| disable-heifconvert    | true                                          |
| disable-darktable      | true                                          |
| disable-rawtherapee    | true                                          |
| disable-sips           | true                                          |
| disable-raw            | false                                         |
| raw-presets            | false                                         |
| exif-bruteforce        | false                                         |
| detect-nsfw            | false                                         |
| upload-nsfw            | false                                         |
| tensorflow-version     | 1.15.2                                        |
| tensorflow-model-path  | /opt/photoprism/assets/nasnet                 |
| default-locale         | en                                            |
| default-theme          | default                                       |
| app-icon               | logo                                          |
| app-name               | PhotoPrism                                    |
| app-mode               | standalone                                    |
| wallpaper-uri          |                                               |
| cdn-url                | /                                             |
| site-url               | http://localhost:2342/                        |
| site-author            |                                               |
| site-title             | PhotoPrism                                    |
| site-caption           | AI-Powered Photos App                         |
| site-description       |                                               |
| site-preview           | http://localhost:2342/static/img/preview.jpg  |
| imprint                | PhotoPrism® needs your                        |
|                        | support!                                      |
| imprint-url            | https://photoprism.app/membership             |
| content-uri            | /api/v1                                       |
| static-uri             | /static                                       |
| api-uri                | /api/v1                                       |
| base-uri               | /                                             |
| http-host              | 0.0.0.0                                       |
| http-port              |                                          2342 |
| http-mode              | release                                       |
| http-compression       |                                               |
| database-driver        | sqlite3                                       |
| database-server        | localhost                                     |
| database-host          | localhost                                     |
| database-port          |                                          3306 |
| database-name          | photoprism                                    |
| database-user          | photoprism                                    |
| database-password      |                                               |
| database-conns         |                                            20 |
| database-conns-idle    |                                            10 |
| darktable-bin          |                                               |
| darktable-cache-path   |                                               |
| darktable-config-path  |                                               |
| darktable-blacklist    | dng,cr3                                       |
| rawtherapee-bin        |                                               |
| rawtherapee-blacklist  |                                               |
| sips-bin               |                                               |
| heifconvert-bin        |                                               |
| ffmpeg-bin             | /usr/bin/ffmpeg                               |
| ffmpeg-encoder         | libx264                                       |
| ffmpeg-bitrate         |                                            50 |
| exiftool-bin           | /usr/bin/exiftool                             |
| download-token         | 18rhnj9b                                      |
| preview-token          | ********                                      |
| thumb-color            | sRGB                                          |
| thumb-filter           | lanczos                                       |
| thumb-size             |                                          2048 |
| thumb-size-uncached    |                                          7680 |
| thumb-uncached         | false                                         |
| jpeg-quality           |                                            85 |
| jpeg-size              |                                          7680 |
| face-size              |                                            50 |
| face-score             |                                      9.000000 |
| face-overlap           |                                            42 |
| face-cluster-size      |                                            80 |
| face-cluster-score     |                                            15 |
| face-cluster-core      |                                             4 |
| face-cluster-dist      |                                      0.640000 |
| face-match-dist        |                                      0.460000 |
| pid-filename           | /root/.photoprism/storage/photoprism.pid      |
| log-filename           | /root/.photoprism/storage/photoprism.log      |
|------------------------|-----------------------------------------------|
```
as you can see, wrong file paths

**Comment by cklam2** [comment]
You mean the web site is also not accessible?

If you just run the command from command line it would show the config for that instance, not the one which is launched through service. To see it also with command line you need to invoke like this:
`/opt/photoprism/bin/photoprism --config-path /var/lib/photoprism/ config`

which will show this output:
```
|------------------------|----------------------------------------------|
|         Value          |                     Name                     |
|------------------------|----------------------------------------------|
| auth-mode              | password                                     |
| admin-password         | ********                                     |
| public                 | false                                        |
| log-level              | info                                         |
| debug                  | false                                        |
| trace                  | false                                        |
| config-path            | /var/lib/photoprism                          |
| options-yaml           | /var/lib/photoprism/options.yml              |
| defaults-yaml          | /etc/photoprism/defaults.yml                 |
| settings-yaml          | /var/lib/photoprism/settings.yml             |
| originals-path         | /var/lib/photoprism/photos/Originals         |
| originals-limit        |                                         1000 |
| resolution-limit       |                                          100 |
| storage-path           | /var/lib/photoprism/storage                  |
| sidecar-path           | /var/lib/photoprism/storage/sidecar          |
| albums-path            | /var/lib/photoprism/storage/albums           |
... etc
```

**Comment by tteck** [comment]
Correct, the website isn't accessible.

**Comment by cklam2** [comment]
Found the issue. I see that you removed my 2 `rm` calls that I added explicitly to the script, see this commit [ee6b092866](https://github.com/tteck/Proxmox/commit/ee6b092866529e366e132bce1e8583ea5b9f5767), lines 100 and 115.

These were removing the 2 .gz files in the root cause if you don't, photoprism won't start up and will show this message:
```
INFO[2022-08-19T15:19:02Z] PhotoPrism® needs your support!              
INFO[2022-08-19T15:19:02Z] Visit https://photoprism.app/membership to learn more. 
ERRO[2022-08-19T15:19:02Z] template: go1.18.4.linux-amd64.tar.gz:188: unrecognized character in action: U+FFFD '�' 
```

I explained this in an earlier message.

**Edit:** see that you moved this to the end but the service already started. Calls didn't remove them though cause still see those 2 .gz file in the root. Anyway, if it did, would only work when you reboot the machine. Removal must be done before starting the service.

**Comment by tteck** [comment]
Got it. Thank you for all of your help!

**Comment by emanueletocci** [comment]
Hi, i have a similar problem... when i change "PHOTOPRISM_STORAGE_PATH" (in /var/lib/photoprism/.env) with my mount point /mnt/archivio_fv... service doesn't start. Using "systemctl status photoprim" i see dead state:
![immagine](https://github.com/tteck/Proxmox/assets/83188429/354e48b8-d153-4c9f-9bd3-1da373fb9a73)

![immagine](https://github.com/tteck/Proxmox/assets/83188429/267263e5-90f6-4b57-b5ec-df9b0b55ca8a)

Using any other paths, service starts. I tried using also /mnt/test which "test" is an empty folder not mapped. Why when I set PHOTOPRISM_STORAGE_PATH to my mounted path it doesn't work?

![immagine](https://github.com/tteck/Proxmox/assets/83188429/a34ba151-9479-48e6-8f00-1d56bcb66cf1)
![immagine](https://github.com/tteck/Proxmox/assets/83188429/3a877c37-ef9a-4701-b10a-d523e785f06e)

I've also tried to mount NFS path directly into /var/lib/photoprism/photos/storage bath I gaing the same result. 
The mount point /mnt/archivio_fv is correctly mounted inside the container:

![immagine](https://github.com/tteck/Proxmox/assets/83188429/f5297422-04c7-4105-a3a9-32b54d12050c)

![immagine](https://github.com/tteck/Proxmox/assets/83188429/e76c59a8-a087-4fbf-aaf4-3e939d8d81b6)
