### ISSUE TITLE
Wrong url to zoraxy homepage

### ISSUE THREAD

**Issue by lubeda** [tteck/Proxmox#3957]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

the link to zoraxy is wrong the correct url is https://zoraxy.aroz.org or https://github.com/tobychui/zoraxy

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

not relevant

**Comment by MickLesk** [comment]
I think you mean here: https://tteck.github.io/Proxmox/? 

In the install-script is the right github:
https://github.com/tteck/Proxmox/blame/612979a04059d215f570aaa1bdace88bc0ad4b53/install/zoraxy-install.sh#L32-L34

on the website is wrong, need to be changed by @tteck
