### ISSUE TITLE
What would be some cool apps to script

### ISSUE THREAD

**Issue by chechel-dima** [tteck/Proxmox#3975]
Good afternoon, thank you for making life easier for administrators and network engineers, I would also like to ask for some tools that will improve network security. 
Tools such as OpenVAS is a full-featured vulnerability scanne. https://github.com/greenbone/openvas-scanner
The Open Source Security Platform (wazuh.com)
Eramba Community (eramba.org) https://github.com/martinboller/eramba-build
I'd like to have these booklets as LXCs

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
