### ISSUE TITLE
paperless: v.2.13.0 Update failed ERROR 1@372 

### ISSUE THREAD

**Issue by strolbor** [tteck/Proxmox#3980]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I wanted to update my paperless to my Debian 11 LXC got an “unknown failure with code 1@372” and the update was terminated. The program does not work anymore
` ✓ Stopped Paperless-ngx
 - Updating to v2.13.0...‼ ERROR 1@372 Unknown failure occurred.`
The status after update:

`root@paperless-ngx ~ [3]# systemctl status paperless-webserver.service
● paperless-webserver.service - Paperless webserver
     Loaded: loaded (/etc/systemd/system/paperless-webserver.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-10-26 17:15:25 UTC; 7min ago
    Process: 1332 ExecStart=/usr/local/bin/gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application (code=exited, status=1/FAILURE)
   Main PID: 1332 (code=exited, status=1/FAILURE)
        CPU: 373ms

Oct 26 17:15:25 paperless-ngx gunicorn[1332]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Oct 26 17:15:25 paperless-ngx gunicorn[1332]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Oct 26 17:15:25 paperless-ngx gunicorn[1332]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Oct 26 17:15:25 paperless-ngx gunicorn[1332]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Oct 26 17:15:25 paperless-ngx gunicorn[1332]:   File "/opt/paperless/src/paperless/settings.py", line 58, in <module>
Oct 26 17:15:25 paperless-ngx gunicorn[1332]:     def __get_optional_int(key: str) -> int | None:
Oct 26 17:15:25 paperless-ngx gunicorn[1332]: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Oct 26 17:15:25 paperless-ngx gunicorn[1332]: ]
Oct 26 17:15:25 paperless-ngx systemd[1]: paperless-webserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 26 17:15:25 paperless-ngx systemd[1]: paperless-webserver.service: Failed with result 'exit-code'.
`

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - If the default Linux distribution is not adhered to, script support will be discontinued.
