### ISSUE TITLE
gotify update not implemented

### ISSUE THREAD

**Issue by oliv99** [tteck/Proxmox#3983]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

gotify, update not implemented/working (see below)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`   ______      __  _ ____
  / ____/___  / /_(_) __/_  __
 / / __/ __ \/ __/ / /_/ / / /
/ /_/ / /_/ / /_/ / __/ /_/ /
\____/\____/\__/_/_/  \__, /
                     /____/
 ✗ There is currently no update path available.
root@gotify:~# update
`

### Please provide detailed steps to reproduce the issue.

Release v2.4.0 has been installed about 10 month ago via tteck  script

in the container, type update
the message is There "is currently no update path available."

but https://github.com/gotify/server/releases/tag/v2.5.0 is available...

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)

**Comment by tteck** [comment]
There's no way to get there. Read the code.
