### ISSUE TITLE
paperless-ngx update to 2.13.0 terminates with error

### ISSUE THREAD

**Issue by sideshowbob84** [tteck/Proxmox#3985]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

hi,
i wanted to update my paperless instance. So i pasted the link
[bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"](url)
and got that error:
`[ERROR] in line 81: exit code 0: while executing command pip install -r requirements.txt &> /dev/null`

i am sorry, but i searched how to run the script in verbose mode but did no find it.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

update to 2.13.0 with the script

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.

https://github.com/tteck/Proxmox/issues/3793
