### ISSUE TITLE
Plex script installation stuck on "Updating container OS"

### ISSUE THREAD

**Issue by debasser1911** [tteck/Proxmox#3995]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Plex script installation stuck on "Updating container OS" (wait more than 5 hours). I've tried different network/DNS configurations, same result.
![image](https://github.com/user-attachments/assets/d1fcb365-9350-432a-9ec3-09799d70dfb4)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
You've got issues that are not script related.

🧐 As this issue is unrelated to the script, it is considered closed.
