### ISSUE TITLE
Idea: Script for Nextcloud

### ISSUE THREAD

**Issue by andre68723** [tteck/Proxmox#4]
Hi,

first, thanks for providing all the scripts, been using them since a while already also in the old now deleted repo.
It would be nice if you could add a script for Nextcloud. What I've found were the following options

VM
* https://github.com/nextcloud/vm would need to be converted from vmdk

*Docker*
* https://github.com/nextcloud/all-in-one (new)
* https://github.com/nextcloud/nextcloudpi (also VM, see https://docs.nextcloudpi.com/en/start-with-ncp-proxmox/ )

all-in-one looks the most interesting though.

PS: a simple docker/podman-setup script is also nice

Thanks, Andre

**Comment by tteck** [comment]
There's also a Turnkey Nextcloud CT template available for download through Proxmox Templates

![Screenshot 2022-01-04 6 49 15 AM](https://user-images.githubusercontent.com/21342670/148055076-9ce4eda0-a3e8-401b-aeb5-d5c226905522.png)

**Comment by andre68723** [comment]
interesting, but it's a bit older (nextcloud21) whereas it's now at 23  https://nextcloud.com/changelog/#latest23

I would assume the all-in-one above gets most ❤️  and care by the vendor itself

**Comment by tteck** [comment]
Is it possible to Upgrade via built-in updater?
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html

**Comment by tteck** [comment]
Also, if you really want Nextcloud AIO and you're running Home Assistant Container LXC or Docker LXC, go to the LXC console and paste
(for Docker)
```yaml
docker run -it \
--name nextcloud-aio-mastercontainer \
--restart always \
-p 80:80 \
-p 8080:8080 \
-p 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest
```
I'd resize the disk (+10gb)

**Comment by tteck** [comment]
Thanks for the suggestion, but I think they're plenty of options without the need for a new script.

**Comment by DSDV** [comment]
@tteck can you please reevaluate? 
the turnkey version is super out of date and updating is a pita. Also it comes bloated with webmin etc. 

since all your scripts are pretty "kiss" it would be nice to have every lxc/vm with the same management scripts and update/grade processes (:

**Comment by nacho-domatix** [comment]
+1 to this

**Comment by nacho-domatix** [comment]
nextcloudpi script might help
`curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash`
(didn't work out of the box with LXC for me)

**Comment by andre68723** [comment]
I am currently using docker with https://github.com/nextcloud/all-in-one and cloudflare Argo tunnel

Benefit - image is regularly updated

**Comment by nacho-domatix** [comment]
I don't like docker at all. That's why I'm using LXC :)

**Comment by DSDV** [comment]
> I don't like docker at all. That's why I'm using LXC :)

this <3 (i now use NC within a TrueNAS VM) but i would rather use a NC LXC than anything else
