### ISSUE TITLE
n8n - add Enviroment to decrase database

### ISSUE THREAD

**Issue by FeroX-Ron** [tteck/Proxmox#4010]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

#Please add this into n8n-install.sh after 47 -  Environment="N8N_SECURE_COOKIE=false"
Environment="DB_SQLITE_VACUUM_ON_STARTUP=true"
#Thank you

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

**Comment by tteck** [comment]
🛑 Failure to comply with the following guideline.
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
