### ISSUE TITLE
Omada LXC - Updating instructions

### ISSUE THREAD

**Issue by liveware-problems** [tteck/Proxmox#402]
I'm sure I read something before on updating the Omada LXC - the suggestion at that point was to backup the config, delete the LXC, create a new one, and restore the config.

I did this once before to upgrade to 5.3.1, however this did uncover an issue; I have the Omada API providing stats into my Home Assistant. and the API requires sending in the unique Site identifier, which is a 32-bit GUID. A new GUID was assigned when Omada was installed in the new container, hence my API queries failed and had to be updated with the new GUID to continue working.

To upgrade to 5.4.6, I simply executed the 2 key lines from the install shell script, and the update kept the config, and really key, the GUID:

```
wget -qL https://static.tp-link.com/upload/software/2022/202207/20220729/Omada_SDN_Controller_v5.4.6_Linux_x64.deb`
sudo dpkg -i Omada_SDN_Controller_v5.4.6_Linux_x64.deb &>/dev/null
```

Obviously the URL will change depending on the new version release date and version, but might be worth adding this to the Upgrade Instructions for Omada?

Thanks!

**Comment by tteck** [comment]
# Version 5.5.6
```
wget -qL https://static.tp-link.com/upload/software/2022/202208/20220822/Omada_SDN_Controller_v5.5.6_Linux_x64.deb
sudo dpkg -i Omada_SDN_Controller_v5.5.6_Linux_x64.deb
```

**Comment by mitchross** [comment]
Theres a new version FYI https://www.tp-link.com/us/support/download/omada-software-controller/#Controller_Software

**Comment by tteck** [comment]
# Version 5.6.3
```
wget -qL https://static.tp-link.com/upload/software/2022/202210/20221024/Omada_SDN_Controller_v5.6.3_Linux_x64.deb
sudo dpkg -i Omada_SDN_Controller_v5.6.3_Linux_x64.deb

**Comment by liveware-problems** [comment]
### Version 5.7.4

```
  wget -qL https://static.tp-link.com/upload/software/2022/202211/20221121/Omada_SDN_Controller_v5.7.4_Linux_x64.deb
  sudo dpkg -i Omada_SDN_Controller_v5.7.4_Linux_x64.deb
```

**Comment by maxigs** [comment]
# Version 5.8.4

```
wget -qL https://static.tp-link.com/upload/software/2023/202301/20230130/Omada_SDN_Controller_v5.8.4_Linux_x64.deb
dpkg -i Omada_SDN_Controller_v5.8.4_Linux_x64.deb
```

**Comment by mitchross** [comment]
# Version 5.9.9
```
wget -qL https://static.tp-link.com/upload/software/2023/202302/20230227/Omada_SDN_Controller_v5.9.9_Linux_x64.deb
dpkg -i Omada_SDN_Controller_v5.9.9_Linux_x64.deb
```

**Comment by chx0003** [comment]
### **New version 5.9.31:**
```
wget -qL https://static.tp-link.com/upload/software/2023/202303/20230321/Omada_SDN_Controller_v5.9.31_Linux_x64.deb
dpkg -i Omada_SDN_Controller_v5.9.31_Linux_x64.deb 
```
### Release Notes:

New Feature/Enhancement
1. Fully adapted to Omada APP version 4.7, supporting Internet and LAN Network configuration.
 
Bug Fixed
1. Fixed the bug that Switch ACLs containing IP-Port groups stopped working after upgrading to Omada Controller version 5.9.9. Reported [Here](https://community.tp-link.com/en/business/forum/topic/600862).
2. Fixed the bug that the Port Forwarding entry cannot be created when the first value of the starting port greater than that of the ending port. Reported [Here](https://community.tp-link.com/en/business/forum/topic/601188).
3. Fixed the incorrect display of the Welcome Information, Terms of Service, and Copyright of Portal.

**Comment by NOXITB** [comment]
wget -qL https://static.tp-link.com/upload/software/2023/202303/20230321/Omada_SDN_Controller_v5.9.31_Linux_x64.deb
sudo dpkg -i Omada_SDN_Controller_v5.9.31_Linux_x64.deb

**Comment by mitchross** [comment]
> wget -qL https://static.tp-link.com/upload/software/2023/202303/20230321/Omada_SDN_Controller_v5.9.31_Linux_x64.deb sudo dpkg -i Omada_SDN_Controller_v5.9.31_Linux_x64.deb

isnt this already linked above?

**Comment by Vendo232** [comment]
@tteck @chx0003 is it possible to create general script to look for latest .deb version and run the upgrade instead of the explicit version in command?

**Comment by tteck** [comment]
No, the path is unknown

**Comment by thpryrchn** [comment]
Here is something you can use to get latest URL and version from the URL...

```bash
latesturl=$(curl -fsSL "https://www.tp-link.com/us/support/download/omada-software-controller/" | grep 'x64.deb"' | head -n1 | sed 's/.*Controller\" href=\"//;s/\".*//')
latestversion=$(sed -e 's/.*ller_v//;s/_Li.*//' <<< "$latesturl")
echo "Latest version is $latestversion at $latesturl"
```
This currently returns: 
`Latest version is 5.9.31 at https://static.tp-link.com/upload/software/2023/202303/20230321/Omada_SDN_Controller_v5.9.31_Linux_x64.deb`

**Comment by tteck** [comment]
Both scripts have been updated.

To update Omada, run the following command in the Omada LXC console.
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/omada.sh)"
```
Compares versions
```
   ____                      __     
  / __ \____ ___  ____ _____/ /___ _
 / / / / __  __ \/ __  / __  / __  /
/ /_/ / / / / / / /_/ / /_/ / /_/ / 
\____/_/ /_/ /_/\__,_/\__,_/\__,_/  
 
Installed version (v5.9.31) is the same as the latest version (v5.9.31).
Omada Controller is already up to date
root@omada:~# 
```
Thanks @thpryrchn

**Comment by joostvdl** [comment]
Update script for latest version v5.13.23 is broken. Looks like the changed naming of deb file

**Comment by tteck** [comment]
Their website shows v5.13.22 as the latest release.
https://www.tp-link.com/us/support/download/omada-software-controller/v5/#Controller_Software

**Comment by tteck** [comment]
The command to check for the latest version also shows 5.13.22
```
curl -fsSL "https://www.tp-link.com/us/support/download/omada-software-controller/" | grep -o 'https://.*x64.deb' | head -n1
```

**Comment by liveware-problems** [comment]
interestingly I just logged onto my console and I get a version update notification:
![image](https://github.com/tteck/Proxmox/assets/32192569/f9ab3e8c-783f-4440-8f49-cd641e01a8d7)

**Comment by joostvdl** [comment]
If you look at the site source there is a new version available:

https://static.tp-link.com/upload/software/2024/202401/20240112/Omada_SDN_Controller_v5.13.23_linux_x64.deb
https://static.tp-link.com/upload/software/2023/202312/20231201/Omada_SDN_Controller_v5.13.22_Linux_x64.deb

Only difference I see is **_linux_** vs **_Linux_** 

But somehow the Curl command doesn't bring the new version.

**Comment by joostvdl** [comment]
Issue found.... it is not on the US site yet. It is on the NL site

https://www.tp-link.com/us/support/download/omada-software-controller/
vs
https://www.tp-link.com/nl/support/download/omada-software-controller/

**Comment by joostvdl** [comment]
Also the EN (GLobal) site, it is not there yet:

https://www.tp-link.com/en/support/download/omada-software-controller/

**Comment by tismofied** [comment]
Version 5.13.30.8 is out. Do I need to run the script again or just type "update" ?
