### ISSUE TITLE
Zigbee2MQTT LXC: Login/Password...?

### ISSUE THREAD

**Issue by Roellen** [tteck/Proxmox#4020]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I used the "Zigbee2MQTT LXC". But when opening the console of this LXC container Iam asked to login. 
But I don't know the username/password?

(I think I need to setup the configuration.yaml but... I don't have access to edit this file?)

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![login](https://github.com/user-attachments/assets/dadc8c4c-2433-4e7c-a038-53ac6b2909bf)

**Comment by tteck** [comment]
❗ It is crucial not to exit the Proxmox shell while running scripts. Leaving the shell during script execution will result in the script being interrupted.
