### ISSUE TITLE
HAOS Install - [ERROR]25@152 Unknown failure occurred.

### ISSUE THREAD

**Issue by FusionAge** [tteck/Proxmox#42]
```
[INFO] Using local-btrfs for Storage Location.
[INFO] Container ID is 100.
 Getting URL for Latest Home Assistant Disk Image... ✔ 
 Downloaded qcow2 Disk Image... ✔
 Extracting Disk Image... ✔ 
 Creating HAOS VM... [ERROR] 25@152 Unknown failure occured.
```
Fresh install of Proxmox VE 7.1-10. I did run your post VE 7 Install script.

**Comment by tteck** [comment]
I've never tested with `btrfs` I'm _guessing_ this is the issue. I just tested using `extfs` with no issues.

([ERROR] 25@152) Proxmox VE Storage Manager (pvesm) fails trying to allocate raw disk image. https://pve.proxmox.com/wiki/Storage:_BTRFS

Looks like the script will likely need to be modified to differentiate `zfs`/`extfs` and `btrfs` to either use `raw` or `subvol` format
I have no immediate solution  other than using a different filesystem. Sorry

**Comment by tteck** [comment]
🛑 **BTRFS** integration is currently a technology preview in Proxmox VE.
https://pve.proxmox.com/wiki/BTRFS

**Comment by tteck** [comment]
@FusionAge I'm wanting to modify the script to work with `btrfs`, would you be willing to test?

**Comment by FusionAge** [comment]
@tteck Happy to!
