### ISSUE TITLE
Home Assistant Container LXC (Podman) - HACS - Github failure

### ISSUE THREAD

**Issue by Crash123Crash123** [tteck/Proxmox#44]
After the command in lxc
`bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/misc/podman_hacs.sh)"`

I tried to integrate HACS. When I check all 4 boxes I get this error:

`Could not authenticate with GitHub, try again later.` Did I miss something?

**Comment by tteck** [comment]
![Screenshot 2022-02-28 9 37 49 AM](https://user-images.githubusercontent.com/21342670/156002342-ff24f7c0-59e9-4828-a1a8-4178cda6e981.png)
Must have been a Github issue, working now.

**Comment by tteck** [comment]
![Screenshot 2022-02-28 8 49 26 PM](https://user-images.githubusercontent.com/21342670/156089568-81a75809-3717-4c74-936a-29dcbae564ba.png)

**Comment by Crash123Crash123** [comment]
Thank you. I got it working at night. :-)
