### ISSUE TITLE
Update post-install command

### ISSUE THREAD

**Issue by panzer-arc** [tteck/Proxmox#440]
The location of the script has changed. I had to use this:
`bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/35c83337680bde52340488eaee51ea6cb395899b/misc/post-install.sh)"`

**Comment by tteck** [comment]
The path is correct in the repo.
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/post-install.sh)"
```

**Comment by panzer-arc** [comment]
Odd--when I run that, nothing appears to happen.

**Comment by panzer-arc** [comment]
I'm not sure why, but that command wouldn't work for me after a fresh install of Proxmox. It seems to work after using my posted command and running the script. May just have been an issue with my DNS proxy not resolving properly.
