### ISSUE TITLE
Show warning when executing scripts from /setup directly on proxmox

### ISSUE THREAD

**Issue by cklam2** [tteck/Proxmox#443]
Saw somewhere an announcement about a script to install photoprism on proxmox, Got very excited but was confused that photoprism wasn't listed in README.md (now know why). Browsed through the source code and found the script in /setup folder which I executed directly in the proxmox shell. After it finished, didn't see a new lxc container and when refreshed proxmox webpage, gave a nice error message.
Turns out that I should **not** run the one from /setup but from /ct instead. By doing that I screwed up proxmox web management pages.

In the /ct scripts a call to `pveversion` is made. Maybe can also invoke this in the /setup scripts, when proxmox detected, give a warning to user prior to continuing?

**Comment by tteck** [comment]
Thanks for your recommendation.
