### ISSUE TITLE
- Downloading Web-Vault v2022.6.2...‼ ERROR 22@103 Unknown failure occurred.

### ISSUE THREAD

**Issue by desolaris** [tteck/Proxmox#448]
Hi. 
The following error occurs during installation Vaultwarden Script

> Using Advanced Settings
> Using Debian Version: 11
> Using Container Type: 0
> Using Root Password: *******
> Using Container ID: 101
> Using Hostname: vaultwarden
> Using Disk Size: 6
> Allocated Cores: 2
> Allocated RAM: 2048
> Using Bridge: vmbr0
> Using IP Address: 192.168.1.3/24
> Using Gateway IP Address: 192.168.1.1
> Using MAC Address: Default
> Using Vlan: Default
> Creating a Vaultwarden LXC using the above advanced settings
>  ✓ Using stor for Template Storage.
>  ✓ Using local-lvm for Container Storage.
>  ✓ Updated LXC Template List
>  ✓ LXC Container 101 was successfully created.
>  ✓ Started LXC Container
>  ✓ Setup Container OS
>  ✓ Network Connected: 192.168.1.3 
>  ✓ Updated Container OS
>  ✓ Installed Dependencies
>  ✓ Installed Rust
>  ✓ Built Vaultwarden 1.25.2
>  - Downloading Web-Vault v2022.6.2...‼ ERROR 22@103 Unknown failure occurred.

**Comment by tteck** [comment]
Fixed. Thanks for reporting!
