### ISSUE TITLE
Docker LXC install prompt defaults

### ISSUE THREAD

**Issue by kchiem** [tteck/Proxmox#450]
https://raw.githubusercontent.com/tteck/Proxmox/main/setup/docker-install.sh

The prompts for installing Portainer and Docker Compose show "<Y/n>", which would suggest that "yes" is the default if one merely hits [enter], but that's not the case:

```
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
PORTAINER="Y"
else
PORTAINER="N"
fi
```

I would suggest:

```
case ${prompt} in
[Nn]*) PORTAINER=N;;
*) PORTAINER=Y;;
esac
```

**Comment by tteck** [comment]
fixed <y/N>

**Comment by kchiem** [comment]
That's r/holup material!

More accurately, it should be "<y/N>".
