### ISSUE TITLE
Debian LXC

### ISSUE THREAD

**Issue by luchaze** [tteck/Proxmox#455]
Getting an error during Debian LXC install script, used it multiple times succesfully in the past weeks. 
"
.....
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 105 was successfully created.
 ✓ Started LXC Container
 - Setting up Container OS ...bash: line 42: LANG: unbound variable
....
"
This line near the bottom of the script:
lxc-attach -n $CTID -- bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/setup/$var_install.sh)" || exit

the link gives a 404 error if i go there manually in the browser?

**Comment by tteck** [comment]
Do any of the other scripts give the `Setting up Container OS ...bash: line 42: LANG: unbound variable` error?

**Comment by tteck** [comment]
What's the output from running `locale` in the Proxmox shell?

**Comment by luchaze** [comment]
just tried the ubuntu, getting the same error. 
locale output is:
![image](https://user-images.githubusercontent.com/111460871/186912551-e6455ac4-acb3-45cc-99c2-4cddd55818f6.png)

but in any case shouldn't that link point somewhere? are you getting the 404 error? saw the ubuntu script has the same link near the bottom.

**Comment by luchaze** [comment]
haven't had any problems with your scripts before

**Comment by tteck** [comment]
The link at the bottom has nothing to do with this issue.
The issue is you don't have the proper locale set in Proxmox.

**Comment by tteck** [comment]
run `dpkg-reconfigure locales` in the Proxmox shell and set your locale (mine is set to `en_US.UTF-8`)

**Comment by luchaze** [comment]
ok, i ran the dpkg-reconfigure locales and configured as en_US.UTF-8 (i think it was already selected)
output from the locales command is still the same and still get the same error

**Comment by tteck** [comment]
On the second screen did you select `en_US.UTF-8`?

![Screenshot 2022-08-26 9 49 00 AM](https://user-images.githubusercontent.com/21342670/186918819-1a477201-bed1-4b6a-82a1-a4cac42e52f5.png)

**Comment by tteck** [comment]
You should see
```
root@pve:~# dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
root@pve:~# 
```

**Comment by luchaze** [comment]
Yep done all dat. 
![image](https://user-images.githubusercontent.com/111460871/186920483-85ffca05-082d-4aa0-abd5-be67404b9b5b.png)
![image](https://user-images.githubusercontent.com/111460871/186920520-687d8cfe-bbe5-4d4e-abe6-b2eeb9b77d99.png)
![image](https://user-images.githubusercontent.com/111460871/186920617-c4d4f48a-625e-4e3a-897f-2b3c8e158299.png)

**Comment by tteck** [comment]
locale should show:
```
root@pve:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by tteck** [comment]
what does `cat /etc/default/locale` show?

**Comment by luchaze** [comment]
#  File generated by update-locale
LANG=en_US.UTF-8

**Comment by tteck** [comment]
and running `locale` shows?

**Comment by luchaze** [comment]
![image](https://user-images.githubusercontent.com/111460871/186923511-c3cc0e6e-4f91-4d9e-b1e1-28f2055e09d9.png)

strange... also like i said, haven't had any problems before.

**Comment by tteck** [comment]
reboot

**Comment by luchaze** [comment]
yep was my tought aswell. just did full shutdown. same result.

**Comment by tteck** [comment]
what does `locale -a` show

**Comment by tteck** [comment]
also, what does `cat /etc/locale.gen` show?

**Comment by luchaze** [comment]
locale -a shows
![image](https://user-images.githubusercontent.com/111460871/186928301-36bd5a8c-741a-4a7c-aa44-f623b3cd655b.png)
cat /etc/locale.gen shows a long list, but the en_US.UTF-8 is uncommented

**Comment by tteck** [comment]
run `locale-gen` and then check `locale` again

**Comment by luchaze** [comment]
yep tried that, still the same. i'm looking for solutions on the internet aswell.
anyways seems like the problem is with my proxmox host, not your script then. so i'll figure it out. 
don't want to bother you with this any further. thanks for the help.

**Comment by luchaze** [comment]
ugh, it ended up being an ssh setting problem. was connected over ssh but usepam was set to no in the sshd.config file so it wasn't passing through locales correctly. LANGUAGE= is still empty on the locale command but the script works now. lol, linux always takes you down these rabbit holes. anyways thanks again for the help, just wanted to let you know problem is resolved.
