### ISSUE TITLE
Home Assistant OS VM broken since last haos_vm.sh update

### ISSUE THREAD

**Issue by vinceg77** [tteck/Proxmox#457]
VM Image download stops at 74%
It was working fine 3 days ago and I have noticed an update since.

![image](https://user-images.githubusercontent.com/51484329/186903369-7f316760-97c7-4843-90b4-3fcdbf58b6cf.png)

**Comment by tteck** [comment]
Are you using PVE 6 or PVE 7?

**Comment by vinceg77** [comment]
PVE 7.2-5

**Comment by tteck** [comment]
`haos_vm.sh` is for PVE 6
`haos-vm-v4.sh` is for PVE 7

**Comment by vinceg77** [comment]
Oups, my mistake, my local storage is full and do not allow download the entire file !
Anyway many thanks for your scripts, it is bread and butter
