### ISSUE TITLE
Mikrotik RouterOS VM link error

### ISSUE THREAD

**Issue by sian-jing** [tteck/Proxmox#459]
![image](https://user-images.githubusercontent.com/22487327/186932491-0ee44473-b84c-4405-88b4-eb7e3bb65e5f.png)
ct???
![image](https://user-images.githubusercontent.com/22487327/186932759-0af0673e-dfe7-4eab-afad-5f44b76fd276.png)
Thank u！

**Comment by tteck** [comment]
fixed, I really goofed that link up! lol...
thanks again
