### ISSUE TITLE
lxc in unprivilege

### ISSUE THREAD

**Issue by docop** [tteck/Proxmox#46]
Hi  Just to write about : thanks for your scripts, they look very great. They are put in bookmark for sure.  Look forward to see all them in unprivilege too.
thanks again

**Comment by tteck** [comment]
Most are already!

**Comment by tteck** [comment]
When you run a script for an install, it will ask privileged or unprivileged

**Comment by docop** [comment]
thanks again.  And on the nginx one, can it be used as a more <secure< way to log to pve or just mostly if set toward an external ip ?
