### ISSUE TITLE
Unable to install Node-RED LXC via script

### ISSUE THREAD

**Issue by rstuke82** [tteck/Proxmox#460]
Not sure what I am doing wrong, I am connected to my proxmox environment via ssh but I am getting error "environment: line 60: MENU: unbound variable" when executing 
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/node-red-v4.sh)"`
 and the container does not get created.
```
    _   __          __        ____           __
   / | / /___  ____/ /__ v4  / __ \___  ____/ /
  /  |/ / __ \/ __  / _ \   / /_/ / _ \/ __  /
 / /|  / /_/ / /_/ /  __/  / _, _/  __/ /_/ /
/_/ |_/\____/\__,_/\___/  /_/ |_|\___/\__,_/

Using Default Settings
Using debian Version: 11
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: Automatic Login
Using Container ID: 100
Using Hostname: node-red
Using Disk Size: 4GB
Allocated Cores 1
Allocated Ram 1024
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Using MAC Address: Default
Using VLAN Tag: Default
Creating a Node-Red LXC using the above default settings
environment: line 60: MENU: unbound variable
root@LLSP-PVE02:~#
```

**Comment by rstuke82** [comment]
Also tried ` bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginx-proxy-manager-v4.sh)"` and got the same error...

**Comment by tteck** [comment]
You have no storage location. What guide did you follow to install Proxmox?

**Comment by tteck** [comment]
Run `pvesm status -content rootdir | awk 'NR>1'` in the Proxmox shell and share the results

DO NOT USE SSH

**Comment by rstuke82** [comment]
Ok I see what happened, thank you.  I recently removed a node from my cluster that had my iso/template share.. fixed.  :)
