### ISSUE TITLE
HASS OS VM - Error creating HAOS VM 5@265 Unknown failure

### ISSUE THREAD

**Issue by cbloy** [tteck/Proxmox#464]
Trying to install hass os vm on existing 7.2-7 Proxmox using all defaults. I did install the post install Proxmox script. It appears that I have enough local disk

Using Default Settings
Using HAOS Version: 8.5
Using Virtual Machine ID: 103
Using Hostname: haos8.5
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using MAC Address: 00:60:2F:03:39:BE
Using VLAN: Default
Start VM when completed: yes
Creating a HAOS VM using the above default settings
 ✓ Using local-lvm for Storage Location.
 ✓ Virtual Machine ID is 103.
 ✓ https://github.com/home-assistant/operating-system/releases/download/8.5/haos_ova-8.5.qcow2.xz
 ✓ Downloaded haos_ova-8.5.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...‼ ERROR 5@265 Unknown failure occurred.

**Comment by tteck** [comment]
Are you using the Proxmox shell or SSH?

**Comment by cbloy** [comment]
Proxmox shell

**Comment by tteck** [comment]
Are there any disks in local-lvm under VM Disks?
![Screenshot 2022-08-29 11 51 45 AM](https://user-images.githubusercontent.com/21342670/187243683-d6eb15d1-3f0c-4f45-822c-973128f22e77.png)

**Comment by cbloy** [comment]
Yes, I do see one created today (for 103):
![image](https://user-images.githubusercontent.com/3522085/187249387-e8fa8ae0-b2cd-4b5c-9d70-d16cffa7f1c5.png)

**Comment by tteck** [comment]
remove it and run the script again

**Comment by cbloy** [comment]
Removing and rerunning the script resolved my issue!  Very impressed with your solution.  Great work and thanks for the quick responses!

**Comment by tteck** [comment]
👍🏻
