### ISSUE TITLE
WireGuard - error during install

### ISSUE THREAD

**Issue by jddayley** [tteck/Proxmox#465]
Updating Container OS...‼ ERROR 100@76 Unknown failure occurred.

**Comment by tteck** [comment]
```
74 → msg_info "Updating Container OS"
75 → apt-get update &>/dev/null
76 → apt-get -y upgrade &>/dev/null
77 → msg_ok "Updated Container OS"
```
Network Issue

**Comment by jddayley** [comment]
Thank you for the quick response.  You can close the issue as it was a network issue.

**Comment by tteck** [comment]
👍🏻

**Comment by tteck** [comment]
Do you think that[ adding extra network checks](https://github.com/tteck/Proxmox/discussions/468) to the script would have helped with finding your issue?

**Comment by jddayley** [comment]
I had an issue with my filesystem.  I use proxmox with a ceph
distributed file system.  One of the nodes was down and running very
slowly.  I think this is very specific to my installation.
