### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by titof2375** [tteck/Proxmox#48]
hello, you should make on your site an option for messages and ideas for your future development

**Comment by tteck** [comment]
Good idea, I've opened up Discussions to give this a test run.

**Comment by titof2375** [comment]
what is the difference between the home assistant in lxc?

**Comment by tteck** [comment]
Disappointed that you didn't ask in [Discussions](https://github.com/tteck/Proxmox/discussions)

But, answered [here](https://github.com/tteck/Proxmox/discussions/54)
