### ISSUE TITLE
Roll back Proxmox VE 7 Post Install

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#486]
Dear @tteck,

Thank you for all the work you have done. I've tested a lot of it during the last few months. Based on the different projects, I've decided to buy a licence from proxmox. In order to cleanly activate this, I need to be able to roll back the installation of the post install. Do you have a script I would be able to run to do this ? 

Thank you so much,
Jens

**Comment by tteck** [comment]
You can make all changes in the _Repositories_ tab
Disable the repositories in red and enable the Enterprise repo
 
![Screenshot 2022-09-06 6 10 23 AM](https://user-images.githubusercontent.com/21342670/188609599-efefa6f6-daa7-4361-97d4-c0e0c7e63b08.png)
