### ISSUE TITLE
CasaOS - script naming issue

### ISSUE THREAD

**Issue by lucagiudici** [tteck/Proxmox#495]
hi,
the link
 _**bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/CasaOS-v4.sh)"**_ 

is not working due a typo in the file name, it's actually all lowercase so shoudl be:
**_bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/casaos-v4.sh)"_**

cheers !

**Comment by tteck** [comment]
Thanks
