### ISSUE TITLE
n8n - ERROR 1@85 Unknown failure occurred

### ISSUE THREAD

**Issue by circa1741** [tteck/Proxmox#496]
Curl already installed in Proxmox server.

Creating a n8n LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 103 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.100.233 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 20.205.243.166
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 - Installing n8n (Patience)...‼ **ERROR 1@85 Unknown failure occurred.**

**Comment by tteck** [comment]
> Curl already installed in Proxmox server.

What does that have to do with anything?

No issue here
```
         ___        
        / _ \       
  _ __ | (_) |_v4_  
 |  _ \ > _ <|  _ \ 
 | | | | (_) | | | |
 |_| |_|\___/|_| |_|

Using Advanced Settings
Using Debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 102
Using Hostname: n8n
Using Disk Size: 3
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a n8n LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 102 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed n8n
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

n8n should be reachable by going to the following URL.
         http://192.168.86.252:5678 
```

**Comment by tteck** [comment]
Installed 3 times without issue.
You may need to increase vCPU and/or RAM for your machine. 🤷🏻‍♂️
