### ISSUE TITLE
Can't select either of my storage pools while trying to install the apps through LXC script

### ISSUE THREAD

**Issue by sharvinzlife** [tteck/Proxmox#498]
![image](https://user-images.githubusercontent.com/74328720/189536285-bc5cfa19-3021-4e6c-8b8b-0b52d944b82e.png)

The storage pools are not selectable, could anyone help me?

**Comment by tteck** [comment]
Spacebar to select
https://github.com/tteck/Proxmox/issues/394#issuecomment-1201338725

**Comment by sharvinzlife** [comment]
Sorry for the noob question, and thanks for your wonderful time helping me out! It worked like a charm. You're awesome!
