### ISSUE TITLE
adguard_container.sh UNKNOWN FAILURE OCCURED 

### ISSUE THREAD

**Issue by kpleines** [tteck/Proxmox#5]
I use Proxmox 7.0-8 
I tried to install adguard using your adguard_container.sh script. 
The container will be created and also started. The problem occured if the adguars_setup.sh script will install adguard.
Here the Errormessages:
`Starting LXC...
Setting up Container OS...
Updating Container OS...
Installing Prerequisites...
[ERROR:LXC] 100@36 Unknown failure occured.
[ERROR] 100@154 Unknown failure occured.
  Logical volume "vm-101-disk-0" successfully removed`

Hope this will help finding the error.

**Comment by tteck** [comment]
I'm unable to replicate. I just ran the script

![Screenshot 2022-01-04 10 46 34 AM](https://user-images.githubusercontent.com/21342670/148085729-3d11b2a9-f52b-437b-b72c-71c86b7cd71d.png)

**Comment by tteck** [comment]
Made a small change to see if it fixes your problem. Please try the script again.

**Comment by tteck** [comment]
**Closed due to not being a script issue**

**Comment by tteck** [comment]
Issue has been fixed
