### ISSUE TITLE
MeshCentral Install Fails

### ISSUE THREAD

**Issue by mon5termatt** [tteck/Proxmox#501]
`Using Advanced Settings`
`Using Debian Version: 11`
`Using Container Type: 1`
`Using Root Password: Automatic Login`
`Using Container ID: 203`
`Using Hostname: meshcentral`
`Using Disk Size: 2`
`Allocated Cores: 1`
`Allocated RAM: 512`
`Using Bridge: vmbr2`
`Using IP Address: dhcp`
`Using Gateway IP Address: Default`
`Using MAC Address: B6:54:04:DC:F1:C8`
`Using Vlan: Default`
`Creating a MeshCentral LXC using the above advanced settings`
 `✓ Using local for Template Storage.`
 `✓ Using local-lvm for Container Storage.`
 `✓ Updated LXC Template List`
 `✓ LXC Container 203 was successfully created.`
 `✓ Started LXC Container`
 `✓ Set up Container OS`
 `✓ Network Connected: 10.1.1.3 `
 `✓ Internet Connected`
 `✓ DNS Resolved github.com to 140.82.112.3`
 `✓ Updated Container OS`
 `✓ Installed Dependencies`
 `✓ Set up Node.js Repository`
 `✓ Installed Node.js`
 `- Installing MeshCentral...‼ ERROR 1@87 Unknown failure occurred.`

**Comment by tteck** [comment]
No issue here. Try increasing Cores and/or RAM 

```    __  ___          __    ______           __             __
   /  |/  /__  _____/ /_  / ____/__  ____  / /__________ _/ /
  / /|_/ / _ \/ ___/ __ \/ /   / _ \/ __ \/ __/ ___/ __  / / 
 / /  / /  __(__  ) / / / /___/  __/ / / / /_/ /  / /_/ / /  
/_/  /_/\___/____/_/ /_/\____/\___/_/ /_/\__/_/ v4\__,_/_/   

Using Advanced Settings
Using Debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: meshcentral
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a MeshCentral LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed MeshCentral
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

MeshCentral should be reachable by going to the following URL.
         http://192.168.86.252 
```

**Comment by mon5termatt** [comment]
strange. one moment

**Comment by mon5termatt** [comment]
yep doubled everything and it installed fine, odd seeing i was using the defaults.
