### ISSUE TITLE
Homepage - ERROR 1@90 Unknown failure occurred

### ISSUE THREAD

**Issue by kitzurea** [tteck/Proxmox#502]
Having trouble getting Homepage installed on my server and was hoping to get some attention brought to this issue. I did notice that there was a similar issue a couple days ago (#497) , and there has been an update to homepage since that issue. Thanks!

Creating a Homepage LXC using the above default settings
 ✓ Using tempDir for Template Storage.  //(Directory)
 ✓ Using newMain for Container Storage.  //(ZFS)
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.11.88 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 - Installing Homepage...‼ **ERROR 1@90 Unknown failure occurred.**

**Comment by tteck** [comment]
No issue here. Try increasing CORES and/or RAM
```
    __  __                                          
   / / / /___  ____ ___  ___  ____  ____ _____ ____ 
  / /_/ / __ \/ __ `__ \/ _ \/ __ \/ __ `/ __ `/ _ \
 / __  / /_/ / / / / / /  __/ /_/ / /_/ / /_/ /  __/
/_/ /_/\____/_/ /_/ /_/\___/ .___/\__,_/\__, /\___/ 
                          /_/   v4     /____/       
Using Advanced Settings
Using Debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 102
Using Hostname: homepage
Using Disk Size: 3
Allocated Cores: 4
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a Homepage LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 102 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Homepage
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Homepage Setup should be reachable by going to the following URL.
         http://192.168.86.252:3000 
```
