### ISSUE TITLE
Plex Media Server LXC - root password

### ISSUE THREAD

**Issue by diginfo** [tteck/Proxmox#509]
Hi;

Can't seem to find the root password for this :-)

**Comment by diginfo** [comment]
Also, seems impossible to add any network sources for media !

**Comment by tteck** [comment]
If you need a root password, and you didn't set one during install via advanced settings, the script didn't finish. Remove and start over making sure you see "✓ Completed Successfully!"

**Comment by diginfo** [comment]
Script finished, not root password shown !

<img width="534" alt="Screenshot 2022-09-16 at 9 44 41 PM" src="https://user-images.githubusercontent.com/6010010/190653428-b549048a-a7d9-4c77-b54f-af4abefe7d6f.png">

**Comment by diginfo** [comment]
OOps, it's auto login :-)

**Comment by diginfo** [comment]
but how do you add a library via cifs / nfs etc ?

**Comment by tteck** [comment]
Search?
https://github.com/tteck/Proxmox/discussions/143

**Comment by diginfo** [comment]
Thanks, yes I thought I might need to setup nfs / cifs & sort out mounting of the volumes.

Might be useful to mention this in the install notes ;-)

**Comment by diginfo** [comment]
anyway, thanks very much for all of you work on these helpers, excellent work & much appreciated.
