### ISSUE TITLE
Ubuntu LXC fails to install

### ISSUE THREAD

**Issue by pax2011** [tteck/Proxmox#510]
Using Advanced Settings
Using Ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: xxxxxxxx
Using Container ID: 111
Using Hostname: ubuntu
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using MAC Address: Default
Using Vlan: Default
Creating a Ubuntu LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
‼ ERROR 1@106 Unable to find a template when searching for 'ubuntu-22.04'.

**Comment by tteck** [comment]
You have network issues
Works here 🤷🏻‍♂️ 
```
   __  ____                __       
  / / / / /_v4__  ______  / /___  __
 / / / / __ \/ / / / __ \/ __/ / / /
/ /_/ / /_/ / /_/ / / / / /_/ /_/ / 
\____/_.___/\__,_/_/ /_/\__/\__,_/  

Using Advanced Settings
Using Ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: ubuntu
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: 192.168.86.253/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a Ubuntu LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

```

**Comment by tteck** [comment]
As the saying goes...
It’s not DNS
There’s no way it’s DNS
It was DNS
😉
