### ISSUE TITLE
Can't update Photoprism

### ISSUE THREAD

**Issue by nortuzar** [tteck/Proxmox#518]
**Describe the issue**
Running photoprism Build [220714-5d7448d2d](https://docs.photoprism.app/release-notes/)
Proxmox 7.2-7
Photoprism with 5 cores and 3 gb ram, installed on July

Run the script to update but nothing happens
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/photoprism-update.sh)"`

**Screenshots**
![image](https://user-images.githubusercontent.com/55258023/190872991-174bc24c-c8e4-4aad-805a-41d54908a120.png)

**Comment by tteck** [comment]
No issue here. Maybe a DNS issue?

Release Branch
```
  _____  _           _        _____      _               
 |  __ \| |         | |      |  __ \    (_)              
 | |__) | |__   ___ | |_ ___ | |__) | __ _ ___ _ __ ___  
 |  ___/|  _ \ / _ \| __/ _ \|  ___/  __| / __|  _   _ \ 
 | |    | | | | (_) | || (_) | |   | |  | \__ \ | | | | |
 |_|    |_| |_|\___/ \__\___/|_|   |_|  |_|___/_| |_| |_|
              UPDATE

 Using Release Branch
 Stopping PhotoPrism... ✔ 
 Cloning PhotoPrism release branch... ✔ 
 Building PhotoPrism release branch... ✔ 
 Cleaning... ✔ 
 Starting PhotoPrism... ✔ 

 Finished  
 
root@photoprism:~# 
```
Develop Branch
```
  _____  _           _        _____      _               
 |  __ \| |         | |      |  __ \    (_)              
 | |__) | |__   ___ | |_ ___ | |__) | __ _ ___ _ __ ___  
 |  ___/|  _ \ / _ \| __/ _ \|  ___/  __| / __|  _   _ \ 
 | |    | | | | (_) | || (_) | |   | |  | \__ \ | | | | |
 |_|    |_| |_|\___/ \__\___/|_|   |_|  |_|___/_| |_| |_|
              UPDATE

 Using Develop Branch
 Stopping PhotoPrism... ✔ 
 Cloning PhotoPrism develop branch... ✔ 
 Building PhotoPrism develop branch... ✔ 
 Cleaning... ✔ 
 Starting PhotoPrism... ✔ 

 Finished  
 
root@photoprism:~# 
```

**Comment by tteck** [comment]
You can run this `nslookup "github.com" | awk -F':' '/^Address: / { matched = 1 } matched { print $2}' | xargs` in the LXC console  to see if DNS resolves github,com to an IP

```
root@server:~# nslookup "github.com" | awk -F':' '/^Address: / { matched = 1 } matched { print $2}' | xargs
140.82.112.4
root@server:~# 
```

**Comment by nortuzar** [comment]
> 

Yesterday I installed pihole, will check that

Edit: Disable pihole and use cloudfare DNS, same problem
```
root@photoprism:~# nslookup "github.com" | awk -F':' '/^Address: / { matched = 1 } matched { print $2}' | xargs
20.201.28.151
```

**Comment by nortuzar** [comment]
Finally i reinstalled the LXC with the script and the update process works well.
Could be an error on the old script? Will see
