### ISSUE TITLE
Jellyfin install on 22.04 "Unknown failure occurred"

### ISSUE THREAD

**Issue by nacho-domatix** [tteck/Proxmox#528]
This happens when I use script to install Jellyfin on Ubuntu 22.04. 

Didn't happen with Ubuntu 20.04 (which I'm using now, and still better than the outdated Turnkey Jellyfin I was using previously). So it's fine to me, just let you know.

```
Creating a Jellyfin LXC using the above advanced settings
 ✓ Using fivetb for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 2002 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.164 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Setting Up Hardware Acceleration...‼ ERROR 100@79 Unknown failure occurred.

```
Many thanks for your amazing work, (almost) all my CT are created now with your scripts :)

**Comment by tteck** [comment]
Using Ubuntu 20.04 to support HDR tone mapping.
Good catch, I'll remove 22.04 as an option for now.
