### ISSUE TITLE
Home Assistant LXC (Podman) Yacht not working

### ISSUE THREAD

**Issue by love768952693** [tteck/Proxmox#531]
**Describe the issue**
After installation, Yacht cannot be used for related operations, including updating pull images.
Try shell podman pull docker.io/homeassistant/home-assistant:stable under lxc to pull the new version and complete the update of homeassistant.

It seems that the configuration between Yacht and Podman is not correct. Internal Server Error: undefined error message often appears in the web interface.

**Screenshots**

**Comment by tteck** [comment]
Run `systemctl enable --now podman.socket` in the LXC console to see if that fixes the problem

**Comment by tteck** [comment]
Looks like Yacht is going to be semifunctional at best with Podman. 🤷🏻‍♂️ 
I made it an optional install.

**Comment by love768952693** [comment]
> Looks like Yacht is going to be semifunctional at best with Podman. 🤷🏻‍♂️ I made it an optional install.

Still thank you very much, I have switched to the docker version.
