### ISSUE TITLE
Jellyfin Playback Failed

### ISSUE THREAD

**Issue by nacho-domatix** [tteck/Proxmox#533]
On a clean installation, with all video files stored in the container:

![image](https://user-images.githubusercontent.com/28144115/191513930-61786f84-42b9-4dab-a7fa-56c1d38fb395.png)

The files /etc/pve/lxc/<container-id>.conf has:
```
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/renderD128 none bind,optional,create=file
```
As it should, according to [Jellyfin website](https://jellyfin.org/docs/general/administration/hardware-acceleration.html#configuring-vaapi-acceleration-on-debianubuntu-from-deb-packages), but `ps aux | grep ffmpeg | grep accel` gives me no response.

Music files play fine.

Any thoughts?

**Comment by tteck** [comment]
Did you set FFmpeg path: `/usr/lib/jellyfin-ffmpeg/ffmpeg` in Jellyfin?

**Comment by nacho-domatix** [comment]
I didn't. And now it's ok.

Thank you very much :)
