### ISSUE TITLE
Debian/Ubuntu LXC - SSH 

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#557]
**Describe the issue**
@tteck, I really like what you have done. However, I'm bumping into a problem. I want to SSH to the LXC which works till it asks the password. I've changed the password within the LXC, with passwd command but still can't SSH to the LXC. Any idea why this is ?

**Comment by Petah-W** [comment]
I ran into this issue lately - assuming you are using the root account and accessing a new container via SSH: did you allow RootLogin in the SSH Configuration ?

in the Webgui logon to the container:

Nano /etc/ssh/sshd_config

make sure "PermitRootLogin yes" is configured

**Comment by Jens-Wymeersch** [comment]
@Petah69 I changed the password with `passwd` command as in debian it boots into the root and adjusted ` "PermitRootLogin yes" in  /etc/ssh/sshd_config` which did the trick.
@tteck however for Ubuntu it asks directly Username and PW, which I don't have. Any ideas ?

**Comment by Petah-W** [comment]
i think even in Ubuntu the username was root + password was the one set in the Create Container Wizard

**Comment by Jens-Wymeersch** [comment]
@Petah69 if you leave it at default, you can't change the password, but it logs in automatically.

**Comment by Jens-Wymeersch** [comment]
@Petah69 with Ubuntu, your fix doesn't work. I'm getting the following error after "PermitRootLogin yes" in /etc/ssh/sshd_config

![image](https://user-images.githubusercontent.com/70786498/192261853-fd10a65c-36db-4280-93a5-a48959b01359.png)

Any other idea ?
