### ISSUE TITLE
ZWaveJS2Mqtt update

### ISSUE THREAD

**Issue by ohuus** [tteck/Proxmox#56]
Thank you for providing all these useful scripts!

Could you add a zwavejs2mqtt update command like there is in zigbee2mqtt?

Thanks in advance:)

**Comment by tteck** [comment]
Is all the data stored in `/opt/zwavejs2mqtt/store`?
Meaning if that directory (store) is moved to a new instance of Zwavejs2MQTT everything would work as before?

**Comment by tteck** [comment]
To test this, create another Zwavejs2MQTT LXC
run this from the Proxmox Shell
```
bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/misc/zwave-copy-data.sh)"
```
select the **from** (original) Zwavejs2MQTT LXC and the **to** (new) Zwavejs2MQTT LXC to copt the data
(wait for "Successfully Transferred Data.")
then shutdown the original Zwavejs2MQTT LXC and start the new Zwavejs2MQTT LXC
everything _should_ run as before, but with a newer version of Zwavejs2MQTT

I'm trying to figure out a simple script to update. But this may work for now?
I have no Zwave devices, so making improvements to this script is difficult

**Comment by ohuus** [comment]
Fantastic! Works perfect. 
Thanks a lot for great help! 👍😊 Super fast solved.

**Comment by zelig2** [comment]
FYI, this is the update process I use on my container for ZWaveJS2MQTT:
```
curl -s https://api.github.com/repos/zwave-js/zwavejs2mqtt/releases/latest  \
| grep "browser_download_url.*zip" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i -
unzip zwavejs2mqtt-v*.zip zwavejs2mqtt
rm zwavejs2mqtt-v*.zip
```

**Comment by tteck** [comment]
@zelig2 that's for the packaged version (which I like) but had to switch to the NodeJS/yarn version to get start at boot working.
Know any secrets to get the packaged version to start at boot?

**Comment by zelig2** [comment]
Sure thing. I'm no expert but here's what I did. 

1. Created a user zwave in my container
`adduser zwave`

1. Moved the zwavejs2mqtt directory from root down to the `/` location
`mv /root/zwavejs2mqtt /`

1. Changed directory and file ownership to zwave
`chown zwave:zwave /zwavejs2mqtt`

1. Created a systemctl service file
`vi /etc/systemd/system/zwavejs2mqtt.service`
```
[Unit]
Description=ZWave-JS
Wants=network-online.target
After=network-online.target

[Service]
User=zwave
Group=zwave
WorkingDirectory=/zwavejs2mqtt
ExecStart=/zwavejs2mqtt/zwavejs2mqtt

[Install]
WantedBy=multi-user.target
```

5. Restarted and enabled the new service in systemctl
```
systemctl --system daemon-reload
systemctl enable zwavejs2mqtt.service 
systemctl start zwavejs2mqtt.service
systemctl start zwavejs2mqtt.service
```
And that last one should show you that the zwave service is running.

**Comment by tteck** [comment]
@zelig2 thank you for your help. We now have a update script!
