### ISSUE TITLE
 zigbee2mqtt update issue

### ISSUE THREAD

**Issue by stefansoeberg** [tteck/Proxmox#57]
Hi

I want to update from version 1.23 to version 1.24. But I am experiencing the following errors which I do not know how to handle.

`root@zigbee2mqtt:~# bash /opt/zigbee2mqtt/update.sh
Stopping Zigbee2MQTT...
Creating backup of configuration...
cp: cannot stat 'data': No such file or directory
Updating...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Installing dependencies...
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /root/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-06T10_42_59_257Z-debug.log
Restore configuration...
cp: cannot stat 'data-backup/*': No such file or directory
Starting Zigbee2MQTT...
Done!`

**Comment by tteck** [comment]
What happened to `/opt/zigbee2mqtt/data`?

**Comment by stefansoeberg** [comment]
root@zigbee2mqtt:~# /opt/zigbee2mqtt/data
-bash: /opt/zigbee2mqtt/data: Is a directory

**Comment by tteck** [comment]
List what's in `/opt/zigbee2mqtt/data` to do this run
```
cd /opt/zigbee2mqtt/data
```
then 
```
ls
```
share your results. Should look similar to
```yaml
configuration.yaml       database.db   extension    log
coordinator_backup.json  devices.yaml  groups.yaml  state.json
```
