### ISSUE TITLE
Home Assistant LXC USB Passthrough issue

### ISSUE THREAD

**Issue by Soffnop** [tteck/Proxmox#571]
Setup a Home Assistant LXC using the script, everything went fine.

I now want to allow USB Passthrough and ran the corresponding script, but get the following error when starting the container:

run_buffer: 321 Script exited with status 1
lxc_setup: 4408 Failed to run autodev hooks
do_start: 1275 Failed to setup container "101"
sync_wait: 34 An error occurred in another process (expected sequence number 4)
__lxc_start: 2074 Failed to spawn container "101"
TASK ERROR: startup for container '101' failed

**Comment by tteck** [comment]
Was the LXC created as Privileged?

**Comment by tteck** [comment]
I'm going to make a change, if the LXC is created Privileged, the script will automatically set up USB passthrough.

**Comment by tteck** [comment]
Change made

**Comment by Soffnop** [comment]
LXC was created as Unprivileged. I used your script for doing it

**Comment by tteck** [comment]
Select "Advanced" when asked "Use Default Settings?" then select "Privileged" (arrow down, spacebar, enter)
USB passthrough  will be automatically set up.

**Comment by Soffnop** [comment]
Thanks. Changed the container to privileged and everything works fine
