### ISSUE TITLE
Zigbee2MQTT v4 broken

### ISSUE THREAD

**Issue by bruno-dogancic** [tteck/Proxmox#575]
First off; thank you for making this nice piece of code it spares so much time!

Recently my router broke so I had to fiddle around and setup my new network, after doing so I have notices strange behavior with MQTT and Z2M LXC containers I had made with your scripts (older ones). I went to make new containers using the instructions only to find out the Z2M sctipt failed to finish installation of zigbee2mqtt, after restarting the process it finished without any errors but the container was "empty". I.e no z2m installed, no etc directory, no npm, no update script etc.

Didn't get time to go through the script to find the possible culprit, but when you get time take a look please.

Cheers,
Bruno

**Comment by tteck** [comment]
No issue here.
```
 _____   _       __             ___   __  _______  ____________
/__  /  (_)___ _/ /_  ___  ___ |__ \ /  |/  / __ \/_  __/_  __/
  / /  / / __  / __ \/ _ \/ _ \__/ // /|_/ / / / / / /   / /   
 / /__/ / /_/ / /_/ /  __/  __/ __// /  / / /_/ / / /   / /    
/____/_/\__, /_.___/\___/\___/____/_/  /_/\___\_\/_/   /_/     
   v4  /____/ 🐝

Using Advanced Settings
Using Container Type: 0
Using Root Password: Automatic Login
Using Container ID: 103
Using Hostname: zigbee2mqtt
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a Zigbee2MQTT LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 103 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Set up Zigbee2MQTT Repository
 ✓ Installed Zigbee2MQTT
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```
![Screenshot 2022-09-30 7 40 03 AM](https://user-images.githubusercontent.com/21342670/193262075-eb86fc81-92a5-47ed-b2e7-5a0fdd3c5de1.png)

**Comment by bruno-dogancic** [comment]
Never mind it. I've made a noobish mistake - never deal with home automation while having fever - my LXC was selected but I was still in pve terminal. Everything works just fine :smile:

**Comment by tteck** [comment]
Hope you get to feeling better! 😷

**Comment by bruno-dogancic** [comment]
> Hope you get to feeling better!

Hopefully will do.

It is funny how I thought to replicate the same steps with version 3 (that worked before and now), yet with version 3 all I did was executing commands in an appropriate places. :sweat_smile:
