### ISSUE TITLE
Photoprism LXC request

### ISSUE THREAD

**Issue by Shadoweee77** [tteck/Proxmox#58]
Hey,
Your scripts are awesome, especially for a beginner like me. Could You maybe consider adding Photoprism (https://photoprism.app/) LXC as well?
Thanks!

**Comment by tteck** [comment]
Something to test
```
bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/photoprism.sh)"
```
Not finished tidying things up, but...

`http://YOUR-IP-HERE:2342`

`admin`
`photoprism`

`nano /var/lib/photoprism/.env`

**Comment by heisenberg2980** [comment]
@tteck I found this issue by coincidence when I was trying to figure out how to change the folder path for storage and originals. If it is not mentioned anywhere else maybe you could add it to the main page indicating those folders as well as the admin password can be changed by updating the file `/var/lib/photoprism/.env` within the LXC.

Now a second question that might be a bit more tricky: I am trying to migrate photoprism from a Raspberry Pi to a Proxmox container, and after changing the path in the previous file to point to the correct path where the old photoprism were storing data photoprism is able to find the pictures (so half of the job is done, hurrah!!). Now I am trying to run `/opt/photoprism/bin/photoprism restore -i "sql-dump-file"` as specified in the photoprism restore instructions (https://docs.photoprism.app/user-guide/advanced/restore/) to avoid having to scan all the folders again (which took about a week on the Raspberry Pi), but it is not working. I guess that command is not valid for this instance of photoprism in a LXC, are you aware of any alternative to make the restore work or if this is even possible?

**Comment by tteck** [comment]
To be honest, I have no idea. Sorry. There's some good reading [here](https://github.com/photoprism/photoprism/discussions/772), but I'm guessing that you've already seen it.

**Comment by heisenberg2980** [comment]
@tteck thanks for the quick answer, I think I am missing something here because I though this process will create a LXC with docker containers inside for mariadb and photoprism, but I am trying to use the commands `docker` and `docker-compose` in the LXC and they are not found, can you explain how this process is setting up photoprism in the LXC? should docker and docker-compose commands work?

**Comment by tteck** [comment]
The installation method used is bare-metal, no docker. If you're wanting the Docker install method, create a Docker LXC and add docker containers.

**Comment by heisenberg2980** [comment]
> The installation method used is bare-metal, no docker. If you're wanting the Docker install method, create a Docker LXC and add docker containers.

Alright, that make sense. Is there any guide of how this bare-metal installation is done? I haven´t been able to find it in the photoprism website, and I am trying to execute some basics commands but they are failing, for example this is the error I am getting when trying to stop photoprism:

```
root@photoprism:/# /opt/photoprism/bin/photoprism stop
INFO[2022-05-03T15:19:30Z] looking for pid in /.photoprism/storage/photoprism.pid 
FATA[2022-05-03T15:19:30Z] open /.photoprism/storage/photoprism.pid: no such file or directory 
```

**Comment by tteck** [comment]
It's using systemd service to control that. `systemctl stop photoprism`
As for how the installation is done, following the install script will show the process 
`https://github.com/tteck/Proxmox/blob/main/setup/photoprism-install.sh`

**Comment by heisenberg2980** [comment]
Wow, that´s a long script, thank you for the effort to create it!

Sorry to bother you with one more question, but after some time reviewing the script and playing around with the container I haven´t been able to find a way to access the database. Running the command `/opt/photoprism/bin/photoprism config` I can see the database driver is sqlite3, but command `sqlite3` is not recognised, is there a way to access the database that photoprism uses?

**Comment by besforttt** [comment]
Hey @tteck, 

Thanks for all the scripts you are putting up and maintaining I've been using a lot of them!
Any chance you could add an option during the install process, or a different install script where photoprism uses mariadb server instead of sqlite3 ?
Or is there a simple way I can do that myself ?

Thanks in advance,
