### ISSUE TITLE
Network question (Internet NOT Connected)

### ISSUE THREAD

**Issue by 0x676e67** [tteck/Proxmox#587]
- # My network is in China
> ### I tried to execute nc -zw1 8.8.8.443 on the host in the same network, and it was OK
![image](https://user-images.githubusercontent.com/51810656/193440114-cb562faa-7081-48f9-8031-e6425985e73d.png)

> ### But I always get "Internet NOT Connected" on Proxmox VE
![image](https://user-images.githubusercontent.com/51810656/193440143-9be7ae22-979f-4ee7-97e4-f2dfcb6d2fcd.png)

> ### But the network seems to be normal, I have tested the results many times.
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/51810656/193440279-633704ed-68e6-487c-82e8-66600ad1c6b5.png">

> ### Until I fork the project and delete the script "if nc-zw1 8.8.8.443; then msg_ok "Internet Connected"; else msg_error "Internet NOT Connected"; exit 1; Fi;" After the normal use
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/51810656/193440528-b42aff76-75aa-4c5c-9ddd-106647d0e763.png">

**Comment by wmane** [comment]
I have the same problem on one machine with all LXC scripts. all machines on the same connection, just with one it's always "no internet!" and script cancels

btw have you modified all scripts in your fork? that would be great, because I have no idea how to script

edit: my network is in western Europe, but as I said, other machines on the same LAN are working fine with the LXC scripts, so idk

edit2: FINALLY it works. THANK YOU for forking. I was going nuts FOR WEEKS. Bless you king!

**Comment by tteck** [comment]
@gngpp First, you need to `nano /usr/share/perl5/PVE/API2/Disks/ZFS.pm` and delete line 345 `my $node = $param->{node};` as the variable was mistakenly duplicated. 

As for the "Internet NOT Connected", internet access is being obtained by the Proxmox VE OS until you see "Started LXC Container", from that point on, internet is obtained by the LXC OS. It appears that there may be some issue with using IPv6. I will test this (I only use IPv4).

**Comment by 0x676e67** [comment]
> @gngpp First, you need to `nano /usr/share/perl5/PVE/API2/Disks/ZFS.pm` and delete line 345 `my $node = $param->{node};` as the variable was mistakenly duplicated.
> 
> As for the "Internet NOT Connected", internet access is being obtained by the Proxmox VE OS until you see "Started LXC Container", from that point on, internet is obtained by the LXC OS. It appears that there may be some issue with using IPv6. I will test this (I only use IPv4).

Thank you for your reply, I also used ipv4 for my tests.

**Comment by 0x676e67** [comment]
> I have the same problem on one machine with all LXC scripts. all machines on the same connection, just with one it's always "no internet!" and script cancels
> 
> btw have you modified all scripts in your fork? that would be great, because I have no idea how to script
> 
> edit: my network is in western Europe, but as I said, other machines on the same LAN are working fine with the LXC scripts, so idk
> 
> edit2: FINALLY it works. THANK YOU for forking. I was going nuts FOR WEEKS. Bless you king!

I'm glad to help you

**Comment by wmane** [comment]
thank 

> @gngpp First, you need to `nano /usr/share/perl5/PVE/API2/Disks/ZFS.pm` and delete line 345 `my $node = $param->{node};` as the variable was mistakenly duplicated.
> 
> As for the "Internet NOT Connected", internet access is being obtained by the Proxmox VE OS until you see "Started LXC Container", from that point on, internet is obtained by the LXC OS. It appears that there may be some issue with using IPv6. I will test this (I only use IPv4).

thank you for your swift response

unfortunately I have as much knowledge of networking as I have of bash scripting, so I'm not of any help here probably. I appreciate your hard work!

**Comment by 0x676e67** [comment]
> After several tests, it is confirmed that the problem is caused by the use of ipv6 in the intranet. As long as the intranet ipv6 is turned off, everything will return to normal

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/51810656/193450851-16ca16d4-e500-4e23-b068-95544dca0e57.png">

**Comment by tteck** [comment]
That's what I suspected (IPv6), now fix that variable error.  😜

**Comment by wmane** [comment]
I can confirm it's working, now that I completely sanatized my openwrt router from ipv6

**Comment by 0x676e67** [comment]
So ipv6 does bring a lot of network problems at present

**Comment by tteck** [comment]
Now we know not to use IPv6, I'm closing this issue.

**Comment by tteck** [comment]
Would you test this to see if it works with IPv6?
```
ping -c 1 -q github.com >&/dev/null
if [ $? != "0" ]; then echo "Internet Not Connected"; else echo "Internet Connected"; fi
```

**Comment by gngpp** [comment]
> Would you test this to see if it works with IPv6?
> 
> ```
> ping -c 1 -q github.com >&/dev/null
> if [ $? != "0" ]; then echo "Internet Not Connected"; else echo "Internet Connected"; fi
> ```

<img width="955" alt="image" src="https://user-images.githubusercontent.com/51810656/194218392-f3755bc4-58ce-4227-a38e-4040dd5749dd.png">
problem

**Comment by gngpp** [comment]
> Repository

Consider using ping cloudflare.com. We can't ping github.com in mainland China

**Comment by 0x676e67** [comment]
> Would you test this to see if it works with IPv6?
> 
> ```
> ping -c 1 -q github.com >&/dev/null
> if [ $? != "0" ]; then echo "Internet Not Connected"; else echo "Internet Connected"; fi
> ```

Consider using ping cloudflare.com. We can't ping github.com in mainland China

**Comment by CharlieMaskell** [comment]
> Would you test this to see if it works with IPv6?
> 
> ```
> ping -c 1 -q github.com >&/dev/null
> if [ $? != "0" ]; then echo "Internet Not Connected"; else echo "Internet Connected"; fi
> ```

I can confirm that this works. I had the same problem and replacing the original network check:
```Bash
if nc -zw1 8.8.8.8 443; then  msg_ok "Internet Connected"; else  msg_error "Internet NOT Connected"; exit 1; fi;
```

With the following fixes the install for me:
```Bash
ping -c 1 -q github.com >&/dev/null
if [ $? != "0" ]; then msg_error "Internet Not Connected"; exit 1; else msg_ok "Internet Connected"; fi
```

**Comment by tteck** [comment]
@CharlieMaskell using IPv6?

**Comment by CharlieMaskell** [comment]
> @CharlieMaskell using IPv6?

Yes, my ProxMox server has IPv4 and IPv6 enabled. The created container would fail the network check and would return an IPv6 address on the Network Connected message.

I disabled IPv6 on ProxMox then the container would be created fine. However in saying that I have just tried to spin up another container without using the updated network check and it's worked. This time the Network Connected message has returned an IPv4 address and IPv6 address.

I'm now wondering whether it's something to do with the container not getting a DHCP lease quick enough and subsequently causing the network check to fail. Will continue to test and let you know if I find a definitive answer.

**Comment by CharlieMaskell** [comment]
Apologies in advance, I am currently learning Linux so bear with me.

IMO This does look to be a timing issue with DHCP.
I piped the current date time out to file using `date >> /root/date.txt` just before `if nc -zw1 8.8.8.8 443; then  msg_ok "Internet Connected"; else  msg_error "Internet NOT Connected"; exit 1; fi;`.

This outputted Thu 27 Oct 2022 10:28:09 PM UTC. I then ran `grep dhclient /var/log/syslog` on the container that failed to install and can see that the DHCPDISCOVER request happens at 10:28:08 and the DHCPOFFER, REQUEST, ACK happen at 10:28:10.

During my testing, I also had intermittent behaviour where sometimes it would work fine and other times it would not work. This also points to a timing issue. Maybe just need to add a retry mechanism on the internet connection check? Potentially could also force DHCP by running `dhclient` before running the connection test?

**Comment by tteck** [comment]
The current checks are
1) Network Check, to make sure it's connected to your local network (10 tries, every 3 seconds)
2) Internet Check, to make sure it's connected to the Internet (IPv4 works, IPv6 doesn't)
3) DNS Check, to make sure it resolves .com (well, we've all been there before)

All 3 are needed to successfully run the scripts
With only IPv4, it works. Add IPv6, you get a mixed bag of results.
I personally have IPv6 disabled in my router.

**Comment by CharlieMaskell** [comment]
Understood. Am just clearing up the inconsistent behaviour for others who might experience it if they have both IPv4 and IPv6 enabled. Essentially it is down to the container not getting an IPv4 address lease quick enough for the check.

I had previously disabled IPv6 within ProxMox, not my router, by editing /etc/default/grub and appending ipv6.disable=1 to GRUB_CMDLINE_LINUX_DEFAULT and GRUB_CMDLINE_LINUX. However, I soon reverted this because it broke the nginx-proxy-manager container as nginx is configured to bind to IPv6 Addresses ([::]:81, [::]:443, and [::]:80) as well as IPv4 addresses. The following exceptions get thrown when attempting to bind to IPv6 addresses:
```
socket() [::]:80 failed (97: Address family not supported by protocol)
socket() [::]:81 failed (97: Address family not supported by protocol)
socket() [::]:443 failed (97: Address family not supported by protocol)
```

Easy fix as I just re-enabled IPv6 on my ProxMox host and the container was happy as nginx could bind successfully.

Thanks for providing these scripts, they're extremely useful!

**Comment by dcseng** [comment]
> nano /usr/share/perl5/PVE/API2/Disks/ZFS.pm

It didn't work here. I have connections ipv4 and ipv6.:

![image](https://user-images.githubusercontent.com/4583389/201990214-ec3db75a-64ea-4017-a7aa-ef8b2b8d7594.png)

**Comment by dcseng** [comment]
I purged the container and try to execute the script so many times, with so many configurations.. the last one that works would be in DHCP mode and I input the gateway number, and now it kind of works. However, it is stuck in the setting up phase. Any clue?

![image](https://user-images.githubusercontent.com/4583389/202000197-ca0654f5-ff94-4d12-82a7-27726bec22d1.png)

Problem: 
![image](https://user-images.githubusercontent.com/4583389/202007045-4f5a729e-cfbc-4f5e-b99b-51940201ad05.png)

Partialy solution: 

![image](https://user-images.githubusercontent.com/4583389/202007415-91ab3e5a-0faf-49f2-b423-3554c4d1170e.png)

When you use wget  on script, you have to force to use ipv4:  "wget --inet4-only"

**Comment by tteck** [comment]
@camnop Wow,
1) either mount `usb-ssd1` or remove reference
2) read https://github.com/tteck/Proxmox/issues/591 and make changes
3) it's not stuck, leave it until it gives error.

**Comment by dcseng** [comment]
Hi @tteck , It is stuck. wget is trying to resolve the domain using an IPV6 connection and it gets stuck.  It should use the command "wget --inet4-only"
