### ISSUE TITLE
Installing Python...‼ ERROR 1@97 Unknown failure occurred

### ISSUE THREAD

**Issue by cyon30** [tteck/Proxmox#595]
Hello all

I am trying to install NGINX Proxy Manager LXC but I keep getting a Python error.

- Installing Python...‼ ERROR 1@97 Unknown failure occurred.

How can I fix this error?

**Comment by tteck** [comment]
I have no idea why there? 
https://github.com/tteck/Proxmox/blob/5d47b17d407174e5c7093e158d20fb9f7d89a602/setup/nginx-proxy-manager-install.sh#L97
No issue here.
```
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________  _  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                         v4           /____/                            /____/             

Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 101
Using Hostname: nginxproxymanager
Using Disk Size: 3
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a Nginx Proxy Manager LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 101 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python
 ✓ Installed Openresty
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Downloaded Nginx Proxy Manager v2.9.18
 ✓ Set up Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Created Service
 ✓ Customized Container
 ✓ Started Services
 ✓ Cleaned
 ✓ Completed Successfully!

Nginx Proxy Manager should be reachable by going to the following URL.
         http://192.168.86.252:81 
```
What type of machine are you using?

**Comment by cyon30** [comment]
Hi

I'm using an HP Proliant DL 390 G9 - 64 Gb Ram, 600 GB SAS, and 2 CPUs.

**Comment by tteck** [comment]
The only thing that I can think of is to throw more resources at it, both Cores and Ram. 🤷🏻‍♂️

**Comment by cyon30** [comment]
sorry, I'm not that good with Docker stuff. Still, learning but How do you do that if I rum the bash command?

**Comment by tteck** [comment]
Well good, because this isn't Docker.
When the scripts asks "Do you want to use default settings?" select "Advanced" then follow the prompts.

**Comment by cyon30** [comment]
`
    _   __      _               ____                           __  ___                                 
   / | / /___ _(_)___  _  __   / __ \_________  _  ____  __   /  |/  /___ _____  ____ _____ ____  _____
  /  |/ / __  / / __ \| |/_/  / /_/ / ___/ __ \| |/_/ / / /  / /|_/ / __  / __ \/ __  / __  / _ \/ ___/
 / /|  / /_/ / / / / />  <   / ____/ /  / /_/ />  </ /_/ /  / /  / / /_/ / / / / /_/ / /_/ /  __/ /    
/_/ |_/\__, /_/_/ /_/_/|_|  /_/   /_/   \____/_/|_|\__, /  /_/  /_/\__,_/_/ /_/\__,_/\__, /\___/_/     
      /____/                         v4           /____/                            /____/             

Using Advanced Settings
Using Container Type: 1
Using Root Password: DosAbc
Using Container ID: 105
Using Hostname: nginxproxymanager
Using Disk Size: 10
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: 10.59.0.1
Using MAC Address: Default
Using Vlan: Default
Creating a Nginx Proxy Manager LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using SAS for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 105 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.59.0.91 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Installing Python...‼ ERROR 1@97 Unknown failure occurred.
root@pve:~# `


Nope, Still not working

**Comment by cyon30** [comment]
Ok, Fine the problem. Firewall. 
![image](https://user-images.githubusercontent.com/20164240/193742698-94c804b1-bbd6-498c-90e7-f4252673ff3e.png)
