### ISSUE TITLE
InfluxDB v4 script failing

### ISSUE THREAD

**Issue by lmbd** [tteck/Proxmox#601]
**Describe the issue**
- Script seems to fail on my Proxmox 7.2.11
- Happens with default settings and advanced settings
**Screenshots**
![Screenshot 2022-10-05 at 13 10 26](https://user-images.githubusercontent.com/3472161/194047508-31b52ea0-cd66-41c7-b796-bcfe77952000.png)

**Comment by tteck** [comment]
Run from the Proxmox Shell, not SSH

**Comment by tteck** [comment]
I think I see where you went wrong. `root@adguard`

**Comment by lmbd** [comment]
Thanks. My fault!
