### ISSUE TITLE
Can't update Uptime Kuma

### ISSUE THREAD

**Issue by maiconjs** [tteck/Proxmox#602]
I'm trying to update Uptime Kuma through the script but I'm not successful. Here's the screen that appears when running the script:

![Sem título](https://user-images.githubusercontent.com/17902999/194091629-10a09bef-f20c-4e57-8ccb-c35dc10e7e2c.png)

**Comment by tteck** [comment]
Try running the script in the Uptime Kuma LXC console.

**Comment by maiconjs** [comment]
Working!

Thx
