### ISSUE TITLE
README.md Formatting Appears Broken

### ISSUE THREAD

**Issue by fordepowers** [tteck/Proxmox#607]
Hello! Love the scripts and have found them very useful.

Since October when the new README.md was introduced, appears to be a formatting problem with the markdown in GitHub:

![image](https://user-images.githubusercontent.com/46435250/194462346-44136b40-6374-49ad-8b94-10936c622a56.png)

It also affects the formatting from the GitHub static page that is generated:

![image](https://user-images.githubusercontent.com/46435250/194462570-c5fd88aa-72ce-4f02-b999-ecf00ef5c5ab.png)

Bringing this up because it doesn't appear intentional.

**Comment by tteck** [comment]
If you're talking about the arrows and lines, those were put there intentionally to separate each category's content.
