### ISSUE TITLE
grafana

### ISSUE THREAD

**Issue by titof2375** [tteck/Proxmox#61]
![image](https://user-images.githubusercontent.com/31250165/157518662-7f9fdd37-7755-4795-bfae-7c2296a722d5.png)
hello, I am you script is for grafana I come across this
my ip http://192.168.1.233:3000/

**Comment by tteck** [comment]
Looks like I forgot to start the server when switching to V2 script. Fixed

```
systemctl start grafana-server
```
```
systemctl enable grafana-server.service
```
```
systemctl status grafana-server
```

**Comment by titof2375** [comment]
it works

**Comment by sideshowbob84** [comment]
Hey had the same problem and the same fix working today. Was the fix somehow lost?
By the way thanks a lot for the wonderful scripts!

**Comment by tteck** [comment]
fixed
