### ISSUE TITLE
No Internet Connected

### ISSUE THREAD

**Issue by dbroome1978** [tteck/Proxmox#611]
When I try to install any container, it now fails due to not being able to access google's dns servers.

Is there anyway to remove this check or give an option to speficiy a different DNS server? I have the google ones blocked on my system

**Comment by tteck** [comment]
fork this repo and remove 
https://github.com/tteck/Proxmox/blob/256b71703121373df51756e7b2b0379489c8df9c/setup/adguard-install.sh#L62
or unblock Google's DNS servers
