### ISSUE TITLE
USB device not found at /dev/ttyUSB1

### ISSUE THREAD

**Issue by zelig2** [tteck/Proxmox#613]
I'm having a weird issue where a USB device isn't properly being created in the /dev folder. I'm running the `zwave-js-ui` script and it finished successfully. The service is running and all is happy except the desired ttyUSB node isn't created. It's bizzare as when I run my old ZWaveJS2MQTT container it shows up properly and I see it in my Zigbee2MQTT container (my only other privileged containers).

```
root@zwave-js-ui:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 05e3:0715 Genesys Logic, Inc. USB 2.0 microSD Reader
Bus 001 Device 008: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
Bus 001 Device 002: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 001 Device 007: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
Bus 001 Device 008 is the device I'm interested in using. It's a ZWave dongle using a Silicon Labs chip.
```
root@zwave-js-ui:~# dmesg | grep usb
...
[933382.150097] usb 1-6: new full-speed USB device number 8 using xhci_hcd
[933382.300469] usb 1-6: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[933382.300472] usb 1-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[933382.300474] usb 1-6: Product: CP2102N USB to UART Bridge Controller
[933382.300488] usb 1-6: Manufacturer: Silicon Labs
[933382.300489] usb 1-6: SerialNumber: 30870de74945eb118e90a552b003b68c
[933382.303242] usb 1-6: cp210x converter now attached to ttyUSB1
```
`dmesg` shows the USB device is attached to `ttyUSB1` which is normal and desired.
```
root@zwave-js-ui:~# ls -al /dev/serial/by-id/
total 0
drwxr-xr-x 2 root root 80 Oct  7 16:28 .
drwxr-xr-x 3 root root 60 Oct  7 16:50 ..
lrwxrwxrwx 1 root root 13 Oct  1 19:41 usb-1a86_USB2.0-Serial-if00-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root 13 Oct  7 16:28 usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_30870de74945eb118e90a552b003b68c-if00-port0 -> ../../ttyUSB1
```
So the `/dev/serial/by-id` folder shows the proper linkage too.
```
root@proxmox:/etc/pve/lxc# cat 115.conf 
## Zwave-JS-UI LXC
#### https%3A//tteck.github.io/Proxmox/
#<a href='https%3A//ko-fi.com/D1D7EP4GF'><img src='https%3A//img.shields.io/badge/%E2%98%95-Buy me a coffee-red' /></a>
arch: amd64
cores: 2
features: nesting=1
hostname: zwave-js-ui
memory: 1024
net0: name=eth0,bridge=vmbr0,hwaddr=86:C6:E1:83:B9:C5,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: hdd-img:115/vm-115-disk-0.raw,size=4G
swap: 512
lxc.cgroup2.devices.allow: a
lxc.cap.drop: 
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
```
This is where things get interesting. `/dev/ttyUSB0` is my Zigbee USB stick but there's nothing called out for `/dev/ttyUSB1`. I edited the `115.conf` file and added in a line similar to the one for USB0. That change in the configuration file fixed the issue. Back when I first started I used your autodev.sh script that pushed the all the /dev nodes over to the container but that script doesn't look to be active anymore. 

All this to say I fixed my problem but it could cause issues with other people who have multiple USB devices connected to their Proxmox server.

**Comment by tteck** [comment]
Thanks for the write up, I'll add `/dev/ttyUSB1` to the script for multiple USB devices.
The `autodev.sh` was renamed to `usb-passthrough.sh` and is still reachable
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/usb-passthrough.sh)"
```

**Comment by tteck** [comment]
Added to Zwave JS UI & Zigbee2MQTT
