### ISSUE TITLE
Add VLAN support

### ISSUE THREAD

**Issue by ZsZs73** [tteck/Proxmox#62]
At first, thanks for your effor maintaining these scripts.

Would you consider adding VLAN support for them?

One approach would be to make net0 interface parameters configurable by:
- option 1: replace the following string `name=eth0,bridge=vmbr0,ip=dhcp` with `$NETOPTS` in `export PCT_OPTIONS`, then add the following `: "${NETOPTS:=name=eth0,bridge=vmbr0,ip=dhcp}"` somewhere above the `export PCT_OPTIONS` in the script. This would set the default value for NETOPTS variable.
Then one could run the script as follows:
`export NETOPTS="name=eth0,bridge=vmbr0,ip=dhcp,tag=<VLANTAG>"; bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/ANYSCRIPT.sh)"`
- option 2: ask the user for the VLAN tag. 
  - No VLAN tag entered should result `-net0 name=eth0,bridge=vmbr0,ip=dhcp`
  - VLAN tag entered should result `-net0 name=eth0,bridge=vmbr0,ip=dhcp,tag=<VLANTAG>`

Certainly option 2 is more user friendly.
I can make a PR if you prefer.

**Comment by tteck** [comment]
A VLAN Tag can easily be set after script completion

![Screenshot 2022-03-10 8 18 20 AM](https://user-images.githubusercontent.com/21342670/157670082-ff175e35-f99c-4d28-91d0-57f9154c21bc.png)

**Comment by ZsZs73** [comment]
I get the following error:
```
     __  __  ____ _______ _______ 
    |  \/  |/ __ \__   __|__   __|
    | \  / | |  | | | |     | |   
    | |\/| | |  | | | |     | |   
    | |  | | |__| | | |     | |   
    |_|  |_|\___\_\ |_|     |_|   
                                                                                                                        

 Using Unprivileged Install
 Using Automatic Login
[INFO] Using vz1 for Template Storage.
[INFO] Using thin1 for Container Storage.
 Updating LXC Template List... ✔ 
 Creating LXC Container... ✔ 
[INFO] LXC Container 103 was successfully created.
 Starting LXC Container... ✔ 
 Setting up Container OS... ❌  No Network! ❌  No Network! ❌  No Network! ❌  No Network! ❌  No Network! ❌  No Network After 5 Tries
root@pve0:~# 
```
I guess that it is due to the fact that the LXC container is unable to get the IP config from the DHCP server without the VLAN tag set on the LXC at creation time.

**Comment by tteck** [comment]
You can't connect to your network without going through a VLAN?
for a test I'll give the MQTT script more tries (15) with 5 sec. intervals to connect.
So, if you'd like, try running the script again

**Comment by ZsZs73** [comment]
My switch drops all frames without VLAN tags.
With the raised tries/timeout I have enough time to set the VLAN tag manually as you proposed.

**Comment by tteck** [comment]
I'm glad you got it working! Would you suggest that I raise attempts to connect to 15 in all scripts?

**Comment by ZsZs73** [comment]
It would be nice. Thank you again!

**Comment by tteck** [comment]
Now, if you select manual DHCP, it'll give you plenty of time to set a VLAN tag. Then just hit enter when finished
