### ISSUE TITLE
Uptime Kuma - Frontend Version do not match backend version!

### ISSUE THREAD

**Issue by maiconjs** [tteck/Proxmox#621]
I updated Uptime Kuma but in about, I see the warning "Frontend Version do not match backend version!". I even reported it in the source as you can see here:

https://github.com/louislam/uptime-kuma/issues/2213

Reported to be a problem with the script. Should I ignore this warning or is this in fact a bug?

**Comment by tteck** [comment]
Thanks, fixed

**Comment by maiconjs** [comment]
Thank you very much. Everything working now.
