### ISSUE TITLE
PiMox HAOS VM: "bash: line 196: STORAGE_MENU: unbound variable"

### ISSUE THREAD

**Issue by Wri84** [tteck/Proxmox#623]
**Describe the issue**
On a fresh Pimox install I'm trying to run the script to automatically deploy a HAOS VM. While doing so I encounter the following error:

`bash: line 196: STORAGE_MENU: unbound variable`

The script exits afterwards and no VM is created

**Comment by tteck** [comment]
This means that you have no set storage for Disk Image

![Screenshot 2022-10-11 9 48 43 AM](https://user-images.githubusercontent.com/21342670/195109420-e12534b7-e12a-4a5e-9ce4-44b871c56963.png)

**Comment by Wri84** [comment]
In trying to recreate the VM manually, I encountered the same error and changed the setting afterwards. Now your script works just fine. Thanks for the quick help!
