### ISSUE TITLE
dashy dont save my config

### ISSUE THREAD

**Issue by nawak86** [tteck/Proxmox#63]
Hi

Thanks you for your work :
bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/dashy.sh)"

When I connect to the dashboard I make a modification and save it to disk and the modifications are lost, any idea?

ty

**Comment by tteck** [comment]
After getting everything setup the way you want in interactive mode and saved to disk, you have to go into update configuration and rebuild application.
It's a bug, https://github.com/Lissy93/dashy/discussions/533#discussioncomment-2308458

**Comment by nawak86** [comment]
ok thanks you it works ;) so i need to rebuild after each modifications ?

**Comment by tteck** [comment]
for now, yes

**Comment by nawak86** [comment]
ok ty for your works ;)
