### ISSUE TITLE
Ubuntu OS install ERROR 1@63 Unknown failure occurred.

### ISSUE THREAD

**Issue by norbertjoni** [tteck/Proxmox#630]
__  ____                __       
  / / / / /_v4__  ______  / /___  __
 / / / / __ \/ / / / __ \/ __/ / / /
/ /_/ / /_/ / /_/ / / / / /_/ /_/ / 
\____/_.___/\__,_/_/ /_/\__/\__,_/  

Using Advanced Settings
Using Ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: 
Using Container ID: 107
Using Hostname: proxymanager
Using Disk Size: 8
Allocated Cores: 4
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using MAC Address: Default
Using Vlan: 101
Creating a Ubuntu LXC using the above advanced settings
 ✓ Using RED_HDD for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.20.156 
 ✓ Internet Connected
‼ ERROR 1@63 Unknown failure occurred.
‼ ERROR 1@63 Unknown failure occurred.

**Comment by tteck** [comment]
DNS
https://github.com/tteck/Proxmox/blob/6b1e4466988d301ab0ad79e8deee2b74533fc877/setup/ubuntu-install.sh#L63

**Comment by tteck** [comment]
You can run `nslookup "github.com" | awk -F':' '/^Address: / { matched = 1 } matched { print $2}' | xargs` to check if DNS is ok.
It should resolve to a IP address.

**Comment by norbertjoni** [comment]
My DNS looks fine.

Creating a Ubuntu LXC using the above advanced settings
 ✓ Using RED_HDD for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.20.160 
 ✓ Internet Connected
‼ ERROR 1@63 Unknown failure occurred.
‼ ERROR 1@63 Unknown failure occurred.
root@proxmox:~# nslookup "github.com" | awk -F':' '/^Address: / { matched = 1 } matched { print $2}' | xargs
140.82.121.4

**Comment by norbertjoni** [comment]
It would be handy If the container creation got any error the LXC should be destroyed automatically.

**Comment by tteck** [comment]
DNS looks fine on `root@proxmox` but maybe not fine on `root@proxymanager` `Using Vlan: 101`

**Comment by tteck** [comment]
In your case, using "Advanced Settings" with a "Root Password" set, you can login to the LXC to help diagnose the issue.
If the LXC gets destroyed automatically after error, no chance of that.

**Comment by norbertjoni** [comment]
The issue was on my opnsense end.
