### ISSUE TITLE
Cannot acces photoprism lxc webgui

### ISSUE THREAD

**Issue by tuupos** [tteck/Proxmox#635]
After installing photoprism trough the script I cannot acces the new photoprism webpage the end of the script tells me to go to.  I don't use https just http and the port used is correct. 
2 weeks ago i installed it with no access problems. I don't know if the script got updated and broke something? I can ping the address with response and also automatic root login is fully functional. Just the webpage of photoprism is unreachable. I waited patiently and also no webgui. Anyone an idea?

**Comment by tuupos** [comment]
From the lxc console: curl -v http://localhost:2342  gives "connection refused". Same curl with port 22 gives no error and works.. 

Port problems?

**Comment by tteck** [comment]
Looking at...

**Comment by tteck** [comment]
Fixed...
For your install, run `systemctl stop photoprism && rm -rf /go1.19.2.linux-amd64.tar.gz && systemctl start photoprism` in the LXC console

**Comment by tuupos** [comment]
Wow, `systemctl stop photoprism && rm -rf /go1.19.2.linux-amd64.tar.gz && systemctl start photoprism` fixed it indeed. Many thanks !

**Comment by tuupos** [comment]
> Fixed... For your install, run `systemctl stop photoprism && rm -rf /go1.19.2.linux-amd64.tar.gz && systemctl start photoprism` in the LXC console

I guess this is not permanent? After rebooting the lxc container I need to run the command again? should I make a cronjob for this?

**Comment by tteck** [comment]
Nope, should be a one time deal. All it did was remove `go1.19.2.linux-amd64.tar.gz`

**Comment by tuupos** [comment]
Oh, I think it's my bad.... I did a mount on the storage folder to my synology NAS and it gives me the following error:

_msg="storage not writable"_

Will adjust my storage and see if it keeps happening... Thanks 1
