### ISSUE TITLE
Vaultwarden, change listen IP?

### ISSUE THREAD

**Issue by Calimerorulez** [tteck/Proxmox#64]
Hi,

I just tried to install the Vaultwarden LXC and (of course) it runs fine. I just want to change the listen IP from 127.0.0.1 to 0.0.0.0. But when I change the vaultwarden.env file, and restart the service, it does not change anything. daemon-reload doos not help either.

Can you give advice?
Thanks.

**Comment by tteck** [comment]
Can I ask why a non-routable meta-address vs a loopback address?

**Comment by Calimerorulez** [comment]
Well, I thought 0.0.0.0 is listening on all interfaces, while 127.0.0.1 is only listening for connections coming from localhost Linux-wise.

I can't connect to port 8000 from my local network, because Vaultwarden is listening on 127.0.0.1; I checked with netstat.

**Comment by Calimerorulez** [comment]
I've added `ROCKET_ADDRESS=0.0.0.0` to the .env file, and now the interface is reachable :)

**Comment by tteck** [comment]
It's already in the `.env` file just needs uncommented
