### ISSUE TITLE
Disabling subscription nag doesn't work anymore

### ISSUE THREAD

**Issue by SamTV12345** [tteck/Proxmox#640]
**Describe the issue**

After running the Post installation script (https://raw.githubusercontent.com/tteck/Proxmox/main/misc/post-pve-install.sh) I still get that prompt to buy a valid license. I downloaded the recent version of VE here: https://www.proxmox.com/de/downloads .

**Comment by tteck** [comment]
Delete browser cache

**Comment by SamTV12345** [comment]
That was the problem. Could you include a hint in the script for that?

**Comment by tteck** [comment]
Done
