### ISSUE TITLE
PostgreSQL install fails because of new v15 release

### ISSUE THREAD

**Issue by afentoe** [tteck/Proxmox#645]
postgress-install.sh fails with this error:

```
 - Installing PostgreSQL...bash: line 87: /etc/postgresql/14/main/pg_hba.conf: No such file or directory
‼ ERROR 1@87 Unknown failure occurred.
```

Reason:
PostgresSQL v15 has just been released and is automatically used for installation, so folder /etc/postgresql/14 does not exist.

Could you please update the script to support PostgreSQL v15?

Workaround for now:
- manually downloaded postgress-install.sh
- modified line 85:
`apt-get install -y postgresql-14 &>/dev/null`

**Comment by Merkalov** [comment]
i have the same error.

**Comment by tteck** [comment]
Thanks for reporting the issue. Has been fixed.

**Comment by afentoe** [comment]
Yes, I can confirm installation works fine now.
Thanks for the quick fix.
