### ISSUE TITLE
ZFS replication, ZFS snapshot, LXC backups broken

### ISSUE THREAD

**Issue by joshuazick1** [tteck/Proxmox#66]
I deployed some of your lxc docker containers onto my zfs storage pools, the only issue that I have is that any time Proxmox tries to snapshot the filesystem the entire container will go unresponsive until the process that is trying to make the snapshot is killed. So far this has affected zfs replication, snapshots in general and backups taken in snapshot or suspend mode.

This has killed my dreams of having a HA setup using ZFS replication on these containers. I have managed to get around the backup issue by setting to stop mode but this is much less than ideal.

**Comment by arsaboo** [comment]
Wondering if it is a Proxmox limitation or script limitation. Did you try running it on a non-ZFS storage just to rule that out?

**Comment by tteck** [comment]
> Note that interactions between fuse and the freezer cgroup can potentially cause I/O deadlocks.
https://pve.proxmox.com/wiki/Linux_Container#pct_options

Try unchecking "FUSE" in the features. 
![Screenshot 2022-03-10 7 18 16 PM](https://user-images.githubusercontent.com/21342670/157777467-77d44af2-8534-4abb-8011-ff0f47fd315d.png)
I can disable fuse-overlayfs storage driver for ZFS and you can test if you would like.

**Comment by tteck** [comment]
fuse-overlayfs has been disabled in the Home Assistant Container LXC script

**Comment by joshuazick1** [comment]
Disabling fuse on an already deployed container doesn't seem to be an option, the docker containers failed to start due to the fuse-overlay driver being missing.

I can confirm that backups and replication are functional with the updated script, however... the bootdisk size needs to be increased, base install is about 11.3G in size immediately after deployment.

```
root@homeassistant:/# alias duf='du -skxc .[!.]* * | sort -rn | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G T)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'
```
```
root@homeassistant:/var/lib/docker# duf|head
du: cannot access '.[!.]*': No such file or directory
10.8G	total
10.8G	vfs
7.0M	image
167.0K	volumes
73.0K	containers
28.0K	buildkit
6.0K	network
2.0K	plugins
1.0K	trust
1.0K	tmp
```

**Comment by tteck** [comment]
So, your recommendations are, eliminate fuse-overlayfs and increase disk size?
as it stands right now, the script isn't using fuse-overlayfs and disk size is set to 16G. Hopefully this will fit everyone's needs.

**Comment by alexdelprete** [comment]
This is a known, more general, problem with proxmox containers and Docker: Proxmox devs recommend and support Docker only in VMs, not LXCs. Seems the problem lies in the linux kernel. Hopefully this will be solved with future kernel versions.

If you search the proxmox forum you will find some discussions about this problem.

I use zfs but for Docker in the end I had to revert to a VM even if I preferred to use LXC. But backups weren't working with LXC, also with stop mode (and I didn't want to use STOP).

**Comment by alexdelprete** [comment]
Proxmox devs [recommend ](https://forum.proxmox.com/threads/docker-lxc-unprivileged-container-on-proxmox-7-with-zfs.99796/post-430630) to use VMs for Docker, not LXCs.

If you search the proxmox forum you will find some discussions about this problem.

I use zfs but for Docker in the end I had to revert to a VM even if I preferred to use LXC. But backups weren't working with LXC, also with stop mode (and I didn't want to use STOP).

In pve [docs](https://pve.proxmox.com/wiki/Linux_Container), you can read this note:

> If you want to run application containers, for example, Docker images, it is recommended that you run them inside a Proxmox Qemu VM. This will give you all the advantages of application containerization, while also providing the benefits that VMs offer, such as strong isolation from the host and the ability to live-migrate, which otherwise isn’t possible with containers.

And this about FUSE mounts:

> Because of existing issues in the Linux kernel’s freezer subsystem the usage of FUSE mounts inside a container is strongly advised against, as containers need to be frozen for suspend or snapshot mode backups.
