### ISSUE TITLE
Unprivileged Plex CT install fails attempting to enable hardware acceleration

### ISSUE THREAD

**Issue by vena** [tteck/Proxmox#661]
On Proxmox 7.2, plex-install.sh does not check whether unprivileged has been selected when enabling hardware transcoding, and the script errors out attempting to chgrp /dev/dri

`Setting Up Hardware Acceleration.../bin/chgrp: changing group of '/dev/dri': Operation not permitted`

**Comment by tteck** [comment]
Thanks for reporting, working on a fix

**Comment by tteck** [comment]
Would you be so kind and check if the fix works?

**Comment by vena** [comment]
all good! thank you!
