### ISSUE TITLE
Emby Media Server Utilizes Automatic Updates

### ISSUE THREAD

**Issue by LeidenSpain** [tteck/Proxmox#666]
HI,

I have installed the LXC of emby, and although it is indicated that "Emby Media Server Utilizes Automatic Updates", it always keeps the same version.
![image](https://user-images.githubusercontent.com/45803748/197626121-939b95ff-f5eb-43ff-9b6a-526a7f1b6680.png)

I have also tried to use apt upgrade, but it does not update either (the emby package does not update me)

What is the correct procedure to upgrade?

Regards

**Comment by tteck** [comment]
Try (in the LXC console)
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/emby-update.sh)"
```

**Comment by LeidenSpain** [comment]
THANKS

It has worked perfectly, thank you very much.

Now I have to fight with the graphic acceleration, because I am one of those who appears in white boxes.

Greetings and thanks
