### ISSUE TITLE
Creating Proxmox LXC Fails

### ISSUE THREAD

**Issue by MartinEngelbrecht** [tteck/Proxmox#667]
I have tried a number of the LXC scripts, Debian, Prometheus, and more and I get the same error message every time. I use the default and have tried Advanced as well. Both with same results
![image](https://user-images.githubusercontent.com/43524195/197697116-799d440f-42e9-4bd6-bfc7-a4327c5d31ac.png)

**Comment by tteck** [comment]
This means that you have no set storage for Container.

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/623

**Comment by MartinEngelbrecht** [comment]
Thanks for the reply, but yes, I have multiple storage areas for containers.
![image](https://user-images.githubusercontent.com/43524195/197700608-0ab07d92-651e-41fa-8619-f1917111d14d.png)

I have created 2 other containers from your scripts that work 100%, but was created on V3 of your scripts. Only the v4 is failing:
![image](https://user-images.githubusercontent.com/43524195/197700795-55b9ce94-96c4-47c5-a8d2-2871ddf37679.png)

**Comment by tteck** [comment]
What's the output of `pvesm status -content rootdir`?

**Comment by MartinEngelbrecht** [comment]
![image](https://user-images.githubusercontent.com/43524195/197702959-cddeea75-47e5-4d95-9dfd-65b546511c33.png)

**Comment by tteck** [comment]
Test this, remove 1 storage area for containers and see if the script runs

**Comment by MartinEngelbrecht** [comment]
Did that. Removed containers from the Local and Cont storage, get exactly the same message when running a script.

**Comment by tteck** [comment]
made changes, try now

**Comment by MartinEngelbrecht** [comment]
I should add, this error started showing up ever since I updated Proxmox to 7.2-11

**Comment by MartinEngelbrecht** [comment]
Nope, tried the debian LXC script now and still getting the same message

**Comment by tteck** [comment]
try a different script, select one that you haven't tried

**Comment by MartinEngelbrecht** [comment]
Just tried Grocy v4. Exactly the same message.
![image](https://user-images.githubusercontent.com/43524195/197711433-cf6584b8-8417-45e1-ab7c-c5355302ee9b.png)

**Comment by tteck** [comment]
Switch v4 with v3 and try

**Comment by MartinEngelbrecht** [comment]
Did that. Tried deConz. Same problem.
![image](https://user-images.githubusercontent.com/43524195/197712289-9c736b9c-ec75-42da-bb3b-6f0bfb38665f.png)

**Comment by tteck** [comment]
Use Advanced settings and use a different CTID, try 112

**Comment by MartinEngelbrecht** [comment]
Done, Still same message.
![image](https://user-images.githubusercontent.com/43524195/197712855-91383a0b-687c-48f1-bf27-38dcdcd125ff.png)

**Comment by tteck** [comment]
Dang, I'm out of ideas what the issue could be 🤷🏻‍♂️

**Comment by MartinEngelbrecht** [comment]
I have removed ALL contrainer storage except 1 Small. And ran a script and still get the same message. So to be honest, Im not a dev. but it doesnt look like a storage issue.

**Comment by tteck** [comment]
No it doesn't. You're using the Proxmox Shell and not SSH, correct?

**Comment by MartinEngelbrecht** [comment]
I have used both. Neither is working

**Comment by tteck** [comment]
I removed all error catching from `create_lxc.sh` and set `debian-v4.sh` in dev to use it.

```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/dev/ct/debian-v4.sh)"
```

**Comment by MartinEngelbrecht** [comment]
Found the problem. I had multiple storage as containers. But I didnt have any Container Template storage. When I ran your Dev Debian v4, it asked me for a container template storage. I went back, added a container template storage and now the script works

**Comment by MartinEngelbrecht** [comment]
Tested MQTT v4 as well and worked.
Thanks for your assistance and sorry I caused you some headaches.
Great job with these scripts. They are a huge help.

**Comment by tteck** [comment]
Glad we worked it out!

**Comment by MartinEngelbrecht** [comment]
For sure. If you didnt set a "debug" mode we wouldnt have. I think. So al lcredit goes to you.

**Comment by tteck** [comment]
I should have had you run `pvesm status -content vztmpl`

**Comment by MartinEngelbrecht** [comment]
Well now we know what the issue was. I have set up a container template storage on my production storage. So al lshould be good now. Thank you very much again

**Comment by tteck** [comment]
I've updated the validate storage check in main branch. It would help me tremendously if you'd be so kind and recreate your issue (remove template storage) and see if it catches it now. 🙏🏻

**Comment by MartinEngelbrecht** [comment]
Nice. Now I get a warning. That will help a lot.
![image](https://user-images.githubusercontent.com/43524195/197728922-68f20afb-7cff-4ab2-bd90-9df818e05383.png)

**Comment by tteck** [comment]
Thank you!!!

**Comment by MartinEngelbrecht** [comment]
Only a pleasure bud.
