### ISSUE TITLE
install fails for node-red-contrib-home-assistant in Node-Red LXC

### ISSUE THREAD

**Issue by nabulke** [tteck/Proxmox#668]
Hello,

I installed the Node-Red LXC without any issues on my Proxmox server. It is up and running.

Unfortunately I can't install the [node-red-contrib-home-assistant](https://flows.nodered.org/node/node-red-contrib-home-assistant) add on in node red.

Any help is appreciated

> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! code 127
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-clonebHPuDn/node_modules/fibers
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! command failed
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! command sh -c -- node build.js || nodejs build.js
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! gyp info it worked if it ends with ok
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! gyp info using node-gyp@3.8.0
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! gyp info using node@18.11.0 | linux | x64
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! gyp ERR! configure error 
> 2022-10-25T11:09:35.464Z [err] npm ERR! npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

[install log.txt](https://github.com/tteck/Proxmox/files/9859689/install.log.txt)

**Comment by tteck** [comment]
Why wouldn't you use the palette manager in node-red? 
Besides, `node-red-contrib-home-assistant-websocket` is the correct one needed.

**Comment by nabulke** [comment]
Thank you for the quick reply.

I used the palette manager in node-red. 

My error was to use the deprecated [node-red-contrib-home-assistant](https://flows.nodered.org/node/node-red-contrib-home-assistant) instead of the new [node-red-contrib-home-assistant-websocket](https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket) you mentioned in your comment. It is working now.

**Comment by tteck** [comment]
To actually answer your question, you need `git` installed (`apt install git`)
