### ISSUE TITLE
vaultwarden - 'rocket-worker-thread' panicked at 'OS can't spawn a new worker thread

### ISSUE THREAD

**Issue by zbuh** [tteck/Proxmox#67]
I'm getting this error after some time running.

Found some one with the same issue: https://bbs.archlinux.org/viewtopic.php?id=271728

Do we really need LimitNPROC ?

**Comment by tteck** [comment]
According to (https://github.com/dani-garcia/vaultwarden/wiki/Setup-as-a-systemd-service#service-fails-to-start) I'd have to say no. Have you tried commenting it out? `nano /etc/systemd/system/vaultwarden.service` then `systemctl daemon-reload` `systemctl restart vaultwarden.service`

**Comment by zbuh** [comment]
Yes. so far no issues.

**Comment by tteck** [comment]
I have removed the line `LimitNPROC=64` from the creation of `vaultwarden.service` in the script
