### ISSUE TITLE
Uptime Kuma's update script doesn' update

### ISSUE THREAD

**Issue by sendarion** [tteck/Proxmox#676]
Everything is in the title, this is what appears in the console when I launch the command:

✓ Stopped Uptime Kuma
bash: line 53: cd: /opt/uptime-kuma: No such file or directory
 ✓ Pulled Uptime Kuma 1.18.5
 ✓ Updated Uptime Kuma
 ✓ Started Uptime Kuma
 ✓ Done!

After that, Uptime Kuma is still in version 1.18.0.
Thx for your help <3

**Comment by tteck** [comment]
Did you run it in the Uptime Kuma LXC console?
> cd: /opt/uptime-kuma: No such file or directory

**Comment by sendarion** [comment]
I was reading to fast and only saw "run the following in the Proxmox Shell" a few lines up -_- thanks for the response, it works!
