### ISSUE TITLE
Podman Home Assistant Issue

### ISSUE THREAD

**Issue by lordalisat** [tteck/Proxmox#68]
Tried out the Home Assistant Podman LXC script. The script seems to pause on pulling the HA image because the disk gets full. Resizing the disk to 12 GiB worked (seems to require about 11.5 GiB). I am not sure why this is happening, as about 3 GiB should be well enough for the images I would think.

**Comment by tteck** [comment]
Thanks for reporting this. I increased the disk size to 16G

**Comment by lordalisat** [comment]
@tteck Sorry for commenting on the issue after closing. First off: thanks for the quick reply.
Second: Podman seems to have a weird interaction with ZFS systems, where it copies the docker image several times, based on something in the dockerfile. In short: the total size of the LXC after install with LVM disk requires about 3 GiB, with ZFS, it requires the aforementioned 11.5GiB.

**Comment by tteck** [comment]
Strange, I've heard that before with ZFS
https://github.com/tteck/Proxmox/issues/66#issuecomment-1064700874

**Comment by tteck** [comment]
@lordalisat fuse-overlayfs storage driver has been disabled because of ZFS replication. The increased size started afterwards.
So, it seems either no ZFS replication or an increase in disk size?
