### ISSUE TITLE
Ubuntu LXC Login

### ISSUE THREAD

**Issue by jjanderson** [tteck/Proxmox#685]
**Describe the issue**
Not really a bug, but just a query really.

I installed an Ubuntu LXC using your script. 

I set the root password, but then when I initiated the console, I could not log on.

I then left the password blank but still don't know the login details. 

Can you help?

Thanks

**Comment by tteck** [comment]
1) Make sure you stay on the shell until you see `✓ Completed Successfully!`
2) You misspelled the password during creation (I've done it)
