### ISSUE TITLE
File Browser Uninstall

### ISSUE THREAD

**Issue by Jens-Wymeersch** [tteck/Proxmox#688]
@tteck  I've just used the script to install File Browser on the shell of Proxmox which wasn't really the intent. Now I want to uninstall it but don't know which command I need to use. Can you help ?

**Comment by tteck** [comment]
```
systemctl stop filebrowser.service
systemctl disable filebrowser.service
rm -rf /usr/local/bin/filebrowser /root/filebrowser.db /etc/systemd/system/filebrowser.service
```

**Comment by tteck** [comment]
BTW, I actually use File Browser on Proxmox. Comes in handy 😉

**Comment by Jens-Wymeersch** [comment]
@tteck maybe I reconsider. Now trying to figure out a way to back up my mac's in the house. I tried Xenology but not totally that happy. I'm thinking of True NAS. Any suggestions ?

**Comment by tteck** [comment]
Look at Syncthing LXC and Daemon Sync Server LXC to see if one of those may work for you. 🤷🏻‍♂️
