### ISSUE TITLE
upgrade dashy to 2.0.5

### ISSUE THREAD

**Issue by nawak86** [tteck/Proxmox#70]
hi

I used your script to install Dashy in LXC. How can I update dashy 2.0.4 to 2.0.5 ?

thanks in advance

bye

**Comment by zelig2** [comment]
I run the following code in the Proxmox container:
```shell
cd /dashy
systemctl stop dashy
git pull origin master
yarn
yarn build
systemctl start dashy
systemctl status dashy
```
This code was based upon the Dashy updating guidance [here](https://dashy.to/docs/management/#updating). Just did this earlier today to upgrade Dashy to 2.0.5 with no troubles.

**Comment by tteck** [comment]
Update script created

**Comment by nawak86** [comment]
hi,

the script does not work I stay in 2.0.4 after the execution.

any idea ?

ty

**Comment by tteck** [comment]
Cache issue? I went from 2.0.3 to 2.0.5 first try it's kind of a one time trial
I changed the update script a little, try again

**Comment by tteck** [comment]
Besides, I can tell NO differences between versions. :(

**Comment by nawak86** [comment]
I copied each command one by one with the script it worked I'm in 2.0.5 except for one problem the conf hasn't been taken over I'm trying to get a backup but it doesn't take it

i try this cp -R /dashy/public/conf-1647302521.backup.yml /dashy/public/conf.yml

in your script :
cp -R /dashy/public/conf.yml conf.yml
make a copy in / directory

after you make this command :
cp -R conf.yml /dashy/public
rm -rf conf.yml

but before you change path with cd /dashy

you have a path problem with cp and rm command

sorry for my bad english

EDIT :

my f** bad i dont see cd ~ command

**Comment by nawak86** [comment]
so my question is how to restore a backup  :/

I already tried:
systemctl stop dashy
cp -R /dashy/public/conf-1647050947.backup.yml /dashy/public/conf.yml
systemctl start dashy

**Comment by nawak86** [comment]
ah ahh after restore i need to rebuild and its ok sorry i'm so bad :/

**Comment by tteck** [comment]
if using the update script, shouldn't have to rebuild

**Comment by nawak86** [comment]
but the script dont work with me. maybe you can add a log file for the future update.
it will be easier for you to see the error by pasting the log

**Comment by tteck** [comment]
If you manually ran line by line, the script should work for you now. Would be the same

**Comment by nawak86** [comment]
yes, thank you for your patience ;)
