### ISSUE TITLE
Heimdall dashboard won't update

### ISSUE THREAD

**Issue by panzer-arc** [tteck/Proxmox#702]
Command used:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/heimdalldashboard-all-update.sh)"

Output: 
Stopping Heimdall Dashboard... ✔ 
 Backing up Data... ✔ 
 Updating Heimdall Dashboard to v2.4.14... ✔ 
 Restoring Data... ✔ 
 Cleanup... ✔ 
 Starting Heimdall Dashboard... ✔ 
 Finished! 

Clearing cache and reloading the dashboard shows its still on version 2.4.13.

Thanks for all your amazing work! Your container templates are my go-to.

**Comment by tteck** [comment]
I think they forgot to bump the version in the app. I just did a fresh install
![Screenshot 2022-11-04 1 56 20 PM](https://user-images.githubusercontent.com/21342670/200044107-03d6c73c-8921-4134-b754-68ee2b50d15a.png)

**Comment by tteck** [comment]
https://github.com/linuxserver/Heimdall/blob/2.x/config/app.php#L17

Someone forgot to bump the version.
