### ISSUE TITLE
Arch LXC Setup 

### ISSUE THREAD

**Issue by squidds** [tteck/Proxmox#703]
Thanks for adding the Arch LXC setup script. It's a big help to get a container up and going quickly. I was able to get it up and running no problem, but people in the future may have an issue getting the container updated and ready for more software. 

[https://gist.github.com/squidds/59eaaa3d829c6ec1b935a93988caabda](https://gist.github.com/squidds/59eaaa3d829c6ec1b935a93988caabda)

steps needed to get pacman and mirrors running -

`pacman-key --init`

`pacman-key --populate archlinux`

`pacman -Sy archlinux-keyring && pacman -Su`

Not really a bug or issue, but it would help future users if there was a link to this process or if it was mentioned in the info for the script. Also, the mirrorlist didn't have any mirrors uncommented, not a big deal, but someone else may not know that is an issue and might believe it's broken.

**Comment by tteck** [comment]
Added info, thanks!
