### ISSUE TITLE
Photoprism scripts: replace "assets" folder instead of copying the new version inside the old folder

### ISSUE THREAD

**Issue by chx0003** [tteck/Proxmox#704]
In Photoprism scripts (install and update), the line that copies the `assets` folder should rename or delete the old folder and replace it with the new one, instead of copying the new folder inside the previous one.

Proxmox/setup/photoprism-install.sh
line 142: `cp -a assets/ /opt/photoprism/assets/ &>/dev/null`

Proxmox/misc/photoprism-update.sh
line 94: `sudo cp -a assets/ /opt/photoprism/assets/ &>/dev/null`

should be:
```
sudo mv /opt/photoprism/assets /opt/photoprism/assets.old &>/dev/null
sudo cp -R assets /opt/photoprism/ &>/dev/null
```

Also, the new versions of Photoprism use Go v1.19.3, the install script should be updated to include that version.
line 101: `wget https://golang.org/dl/go1.19.2.linux-amd64.tar.gz &>/dev/null`
line 102: `tar -xzf go1.19.2.linux-amd64.tar.gz -C /usr/local &>/dev/null `

should be: 
```
wget https://golang.org/dl/go1.19.3.linux-amd64.tar.gz &>/dev/null
tar -xzf go1.19.3.linux-amd64.tar.gz -C /usr/local &>/dev/null 
```

and line 199: `/go1.19.2.linux-amd64.tar.gz \`
should be:  `/go1.19.3.linux-amd64.tar.gz \`

Thanks and Regards!

**Comment by tteck** [comment]
Changes made, thanks!
