### ISSUE TITLE
Unable to Access Scrypted Port 10443

### ISSUE THREAD

**Issue by e8link** [tteck/Proxmox#705]
I'm trying to move my Scrypted installation from Home Assistant to its own VM.  

After install on promox I can see that the VM has received an IP address in Unifi.   But I can't connect to the web address using either Safari or Chrome on port 10443.

**Comment by tteck** [comment]
It's a container, are you using https?

**Comment by e8link** [comment]
Yes I'm using https. I did try disabling apparmor as a guess to the problem.  I noticed this is the first container I'm using on promox all the others are vm's.

**Comment by tteck** [comment]
There was a error in the script, sorry, it has been fixed.
Remove the old one and rerun the script.

**Comment by e8link** [comment]
Thank you!   It's working now.
