### ISSUE TITLE
Cant update Z2M - Please commit your changes or stash them before you merge

### ISSUE THREAD

**Issue by nortuzar** [tteck/Proxmox#708]
**Describe the issue**
Trying to update Zigbee2MQTT using the command
`cd /opt/zigbee2mqtt && bash update.sh
`

but found a git problem ( I guess)
```
root@zigbee2mqtt:/opt/zigbee2mqtt# cd /opt/zigbee2mqtt && bash update.sh
Stopping Zigbee2MQTT...
Creating backup of configuration...
Updating...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 85 (delta 53), reused 56 (delta 36), pack-reused 0
Unpacking objects: 100% (85/85), 230.54 KiB | 372.00 KiB/s, done.
From https://github.com/Koenkk/zigbee2mqtt
   48117fdd..e66fe853  master     -> origin/master
   60bf855e..cd22dafc  dev        -> origin/dev
 * [new tag]           1.28.2     -> 1.28.2
Updating 7dc48fb6..e66fe853
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting
```
Which command I need to make this work? 

Thanks for the great scripts!

**Comment by tteck** [comment]
Try `cd /opt/zigbee2mqtt && git stash && bash update.sh`

**Comment by nortuzar** [comment]
> Try `cd /opt/zigbee2mqtt && git stash && bash update.sh`

Did it, looks like it work, but now i cant access the GUI

`Unable to connect`
`
Firefox can’t establish a connection to the server at 192.168.1.54:9442.`

**Comment by tteck** [comment]
Try rebooting the LXC

**Comment by nortuzar** [comment]
Nothing.

I restore a backup and try again, same problem. At the end of the update there was the following message  (don't know if this could help)
![image](https://user-images.githubusercontent.com/55258023/200402693-7bd06ae5-4684-4602-9f97-72706c85b1c3.png)

**Comment by tteck** [comment]
Restore a backup and try `cd /opt/zigbee2mqtt && git commit && bash update.sh`
I wouldn't think that a npm update matters.

**Comment by nortuzar** [comment]
> Restore a backup and try `cd /opt/zigbee2mqtt && git commit && bash update.sh` I wouldn't think that a npm update matters.

```
root@zigbee2mqtt:~# cd /opt/zigbee2mqtt && git commit && bash update.sh
On branch master
Your branch is behind 'origin/master' by 95 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   data/configuration.yaml
        modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

do i need to use git pull first?

**Comment by tteck** [comment]
According to that, the normal `cd /opt/zigbee2mqtt && bash update.sh` should work. 
Have you updated before?

**Comment by nortuzar** [comment]
> According to that, the normal `cd /opt/zigbee2mqtt && bash update.sh` should work. Have you updated before?

to be fair maybe I did something extra in the past to make the update work.

Will try to backup the settings and restore on a new lxc

**Comment by nortuzar** [comment]
At the end I create a new LXC using your script

Then i use the script you post to copy the data

Now I have all my config on a new and update proof LXC 

Thanks for your help and awesome work

**Comment by tteck** [comment]
That copy data script comes in handy.
