### ISSUE TITLE
Nextcloud Pi Installation Error

### ISSUE THREAD

**Issue by JabelsBS** [tteck/Proxmox#718]
Hey, 

i tried to install with your Script and get a Error 4@82 Unknown failure occurred

What i did:
- Run `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nextcloudpi-v4.sh)"
` in the Shell of my Proxmox and wait.

![grafik](https://user-images.githubusercontent.com/64330818/201407510-8c611d7d-7c06-4d3e-b7b7-1961566471db.png)

I'm new to Proxmox, but if I can provied anything please let me know
I'm running Proxmox 7.2-11

There is a Nextcloud LXC after the Error but if try to use the shell of the LXC I need to Log in. 
![grafik](https://user-images.githubusercontent.com/64330818/201408765-88b3a752-bc72-4c10-bbb6-1142c94311a4.png)

Also there is no interface reachabel with the IP and Port :4443
![grafik](https://user-images.githubusercontent.com/64330818/201409127-c5b613b8-b2cf-45fc-95dc-2c09d6fb8f21.png)

**Comment by tteck** [comment]
The script never finished, so the LXC is useless. Stop and remove.
I just ran the script

```
    _   __          __  ________                ______  _ 
   / | / /__  _  __/ /_/ ____/ /___  __v4______/ / __ \(_)
  /  |/ / _ \| |/_/ __/ /   / / __ \/ / / / __  / /_/ / / 
 / /|  /  __/>  </ /_/ /___/ / /_/ / /_/ / /_/ / ____/ /  
/_/ |_/\___/_/|_|\__/\____/_/\____/\__,_/\__,_/_/   /_/   
                                                          
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: nextcloudpi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a NextCloudPi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed NextCloudPi
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

NextCloudPi Setup should be reachable by going to the following URL.
         https://192.168.86.252/ 
```
Maybe try adding more resources (use Advanced settings) 🤷🏻‍♂️

**Comment by tteck** [comment]
It failed at
https://github.com/tteck/Proxmox/blob/cbc9d446f038c98a4b137db324858a3cb53c07d3/setup/nextcloudpi-install.sh#L82

**Comment by JabelsBS** [comment]
I tried different settings. 

Setting static IP with default resources -> n.i.O.
Setting static IP with 10GB Disk size, 2 Cores, 3040 Ram -> n.i.O.
Setting 10GB Disk size, 2 Cores, 3040 Ram -> n.i.O.
Disable AdGuard and let it at default -> i.O. 

i don't get why AdGuard blocked that one Github contet and nothing else from Github

Thank you for youre Time and youre Patience!
