### ISSUE TITLE
vaultwarden no web interface

### ISSUE THREAD

**Issue by Neji77** [tteck/Proxmox#72]
Using Privileged Install
 Using Password (changeme)
[INFO] Using local for Template Storage.
[INFO] Using local-lvm for Container Storage.
 Updating LXC Template List... ✔ 
 Creating LXC Container... ✔ 
[INFO] LXC Container 105 was successfully created.
 Starting LXC Container... ✔ 
 Setting up Container OS... ✔ 
 Network Connected: 192.168.86.248  ✔ 
 Updating Container OS... ✔ 
 Installing Dependencies... ✔ 
 Installing Build Essentials... ✔ 
 Installing Rust... ✔ 
 Installing Node.js... ✔ 
 Building Vaultwarden (Patience)... ✔ 
 Building Web-Vault... (⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠋ audit: timing arborist:ctor Completed i
✔ 
 Create Systemd Service... ✔ 
 Cleanup... ✔ 

Successfully created Vaultwarden LXC to 105.
Vaultwarden should be reachable by going to the following URL.
         http://192.168.X.X:8000

i have no web interface with http://192.168.X.X:8000 
i also try to update with success but still no web interface

updating to v2.26.1... 
 Cleanup... 
 Starting Vaultwarden... 
 Finished Update

do you have any idea ?

i have no problem at all with others lxc (npm, esphome, mqtt, zigbee2mqtt)

**Comment by tteck** [comment]
Try this, `nano /etc/vaultwarden.env` and uncomment `ROCKET_ADDRESS=0.0.0.0` reboot and see if the interface is reachable

**Comment by Neji77** [comment]
yes thank you the interface is reachable now !
i cannot create account without https "This browser requires https to use the web vault ", i don't know if it is a normal behavior
However with NPM and https : it is ok !

**Comment by tteck** [comment]
Good! Yep, needs to be behind a proxy.
