### ISSUE TITLE
Umbrel doesn't install anything?

### ISSUE THREAD

**Issue by nacho-domatix** [tteck/Proxmox#722]
I tried to install some apps, even to update and nothing seems to be working. I tried two different LXC containers in case, but nothing. 
![image](https://user-images.githubusercontent.com/28144115/201491316-d3bc4dbf-55ff-4667-afb8-a6539792ccff.png)
![image](https://user-images.githubusercontent.com/28144115/201491321-a356497e-9d8b-4776-806b-921b23be8465.png)

**Comment by tteck** [comment]
Try `cd ~/umbrel/scripts && bash start`

**Comment by nacho-domatix** [comment]
> Try `cd ~/umbrel/scripts && bash start`

```
root@umbrel:~# cd ~/umbrel/scripts && bash start
This script requires "docker-compose" to be installed
```

**Comment by tteck** [comment]
I created a new Umbrel LXC and encountered the same results as you. A fresh install put it at version 0.5.3
I started the Umbrel OS with `cd ~/umbrel/scripts && bash start` and everything worked as it should. Even after a reboot.
So, I don't know what changed with Umbrel, but apparently a one time Umbrel OS start is now required.

**Comment by nacho-domatix** [comment]
I'm not sure I'm following you. I did a fresh install too, but the message I posted is what shows up when I do `cd ~/umbrel/scripts && bash start`. Am I missing something?

**Comment by tteck** [comment]
Your picture shows that you're on version 0.5.1, so I figured it wasn't a new install

**Comment by nacho-domatix** [comment]
I have three different versions. Two of them are 0.5.3

**Comment by tteck** [comment]
My version 0.5.3 worked using `cd ~/umbrel/scripts && bash start` and a reboot
You can also try a `systemctl enable --now umbrel-startup.service` and a reboot

**Comment by nacho-domatix** [comment]
`systemctl enable --now umbrel-startup.service` seems to be working. Amazing! Many thanks!! :)

**Comment by tteck** [comment]
a reboot is required before app installs
