### ISSUE TITLE
Blocky v0.20

### ISSUE THREAD

**Issue by panzer-arc** [tteck/Proxmox#724]
Blocky script needs adjusted for the latest release. Error message generated creating new blocky container:
 
`- Installing Blocky...tar: blocky_0.19_Linux_x86_64.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now` \
`‼ ERROR 2@87 Unknown failure occurred.`

**Comment by tteck** [comment]
Thanks for reporting! Is now fixed.
