### ISSUE TITLE
Grocy script need to be updated to PHP8

### ISSUE THREAD

**Issue by phellarv** [tteck/Proxmox#735]
After getting harassed the crap out of by the owner of the Grocy-project for not using PHP8 when trying to report a bug, I try here with a hope of a bit more humane reception when reporting a bug. Grocy has not supported PHP7 since 3.1. So please update the script to install PHP8.

Thanks a lot for the good work. I use several of the scripts for my proxmox instance.

**Comment by tteck** [comment]
Thank you for reporting! The script now installs PHP 8.1

**Comment by nihochuha** [comment]
Not shure, because Debian Bullseye LXC have no $lsb_release, and script not installing it
```
root@grocy:~# sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
sh: 1: lsb_release: not found

```

**Comment by tteck** [comment]
@nihochuha I have no idea what you're talking about?

```
   ____ __________  _______  __
  / __  / ___/ __ \/ ___/ / / /
 / /_/ / /  / /_/ / /__/ /_/ / 
 \__, /_/   \____/\___/\__, /  
/____/      v4        /____/   

Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: grocy
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using MAC Address: Default
Using Vlan: Default
Creating a grocy LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
➜ ✓ Installed PHP 8.1
 ✓ Installed grocy
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

grocy should be reachable by going to the following URL.
         http://192.168.86.252 
```
![Screenshot 2022-11-19 12 43 39 PM png](https://user-images.githubusercontent.com/21342670/202864481-8bb08077-6b0f-4432-a4a4-a5507f70a422.png)

**Comment by nihochuha** [comment]
@tteck maybe it's a some bug from previous version of this script, I've just updated PHP in grocy LXC from 7.4 to 8.1 manually, using your script step-by-step.
Got an error about $lsb_release shown above.

**Comment by tteck** [comment]
No bug, the script got updated. Check for added dependencies. Or better yet, create a new grocy LXC restore your `/data` 
https://github.com/grocy/grocy/issues/355

**Comment by slimline33** [comment]
I've got the following error on install grocy

Php 8.1

![Screenshot_2022-11-21-07-30-45-192_org connectbot](https://user-images.githubusercontent.com/3323812/202980913-99a2d79f-82e0-44b4-96eb-72a1799b8ced.jpg)

Sorry for Screenshot but my console will close on long press 😬

**Comment by slimline33** [comment]
Sorry. AdGuard blocked the traffic :D now it runs! Excellent!
