### ISSUE TITLE
Docker script not installing docker-compose?

### ISSUE THREAD

**Issue by jcastro** [tteck/Proxmox#736]
**Describe the issue**
Hi! Attaching a pic of my installation, as you can see I said yes to portainer and docker-compose. However when I go to my container terminal and type docker-compose I get command not found. Is this supposed to install docker-compose? If I do apt install docker-compose it actually shows a ton of packages to install

**Screenshots**
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/190036/202007669-d3192568-fb53-4dc8-a4a6-3168a6d30ee6.png">

**Comment by tteck** [comment]
It says "Installed Docker Compose v2.12.2"

**Comment by jcastro** [comment]
Yep, but when I go to the LXC terminal the docker-compose command is not available

**Comment by tteck** [comment]
⚠ Run Compose V2 by replacing the hyphen (-) with a space, using docker compose, instead of docker-compose.

It's in the instructions

**Comment by jcastro** [comment]
got it, thanks!
