### ISSUE TITLE
CrowdSec Script not working

### ISSUE THREAD

**Issue by rafasanz** [tteck/Proxmox#748]
After execute script:
- Setting up CrowdSec Repository...‼ ERROR 1@67 Unknown failure occured.

**Comment by tteck** [comment]
No issue here
```
   _____                      _  _____           
  / ____|                    | |/ ____|          
 | |     _ __ _____      ____| | (___   ___  ___ 
 | |    |  __/ _ \ \ /\ / / _  |\___ \ / _ \/ __|
 | |____| | | (_) \ V  V / (_| |____) |  __/ (__ 
  \_____|_|  \___/ \_/\_/ \__ _|_____/ \___|\___|

 ✓ Setup CrowdSec Repository
 ✓ Installed CrowdSec on octoprint
 ✓ Installed CrowdSec Common Bouncer
 ✓ Completed Successfully!
```

**Comment by rafasanz** [comment]
first i ran the script on pve proxmox

root@pve:~#   bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/crowdsec.sh)"
This will Install CrowdSec on pve. Proceed(y/n)?y

after few seconds i get this

<img width="494" alt="image" src="https://user-images.githubusercontent.com/102509029/203070327-764a7a4c-36a9-4f8e-a837-5d381351e9a4.png">

am i missing something?

**Comment by tteck** [comment]
Line 67:
https://github.com/tteck/Proxmox/blob/b28568d0ca5b8d3247126d4c0df7e7928ce48235/misc/crowdsec.sh#L67
Make sure you have an internet connection
Make sure nothing is blocking the URL

**Comment by tteck** [comment]
Home Assistant Core
```
   _____                      _  _____           
  / ____|                    | |/ ____|          
 | |     _ __ _____      ____| | (___   ___  ___ 
 | |    |  __/ _ \ \ /\ / / _  |\___ \ / _ \/ __|
 | |____| | | (_) \ V  V / (_| |____) |  __/ (__ 
  \_____|_|  \___/ \_/\_/ \__ _|_____/ \___|\___|

 ✓ Setup CrowdSec Repository
 ✓ Installed CrowdSec on ha-core
 ✓ Installed CrowdSec Common Bouncer
 ✓ Completed Successfully!
```

Proxmox may not allow CrowdSec to be installed on itself. I get the same error when trying to install on PVE

```
   _____                      _  _____           
  / ____|                    | |/ ____|          
 | |     _ __ _____      ____| | (___   ___  ___ 
 | |    |  __/ _ \ \ /\ / / _  |\___ \ / _ \/ __|
 | |____| | | (_) \ V  V / (_| |____) |  __/ (__ 
  \_____|_|  \___/ \_/\_/ \__ _|_____/ \___|\___|

 - Setting up CrowdSec Repository...‼ ERROR 1@67 Unknown failure occured.
root@proxmox:~# 
```

**Comment by tteck** [comment]
The query exits while having a non-zero status. Removing error handling will allow the script to finish. But not advisable since it installs on everything except PVE. IMHO, installing anything on Proxmox directly is bad practice.

**Comment by rafasanz** [comment]
That's right!! Creating on a LXC with debian 11 any problem at all
thanks!!

**Comment by malosaa** [comment]
FOr me still not working.

im running thi on a debian LXC container 
![image](https://user-images.githubusercontent.com/13116501/228838392-ce013269-394d-4fec-88be-9517c652157c.png)
