### ISSUE TITLE
Error after `bash -c "$(wget***`  (mariadb-v4.sh)

### ISSUE THREAD

**Issue by tomg1970** [tteck/Proxmox#751]
Hello,
I have the following problem that the newly created `mariadb-V4` lxc does not start.
I get this error.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/26352194/203145136-0712720d-7a3b-4710-a6ea-18cc60cd1e31.png">

**Comment by tteck** [comment]
Update Proxmox

**Comment by tomg1970** [comment]
Thank you. That was my problem.
Although I have just installed the proxmox the day before yesterday.

**Comment by tteck** [comment]
When `7.2-14` got released, they forgot ` binutils`
