### ISSUE TITLE
haos-vm: ‼ ERROR 1@260 Unknown failure occurred.

### ISSUE THREAD

**Issue by GnussonNet** [tteck/Proxmox#754]
**Describe the issue**
Newly updated Proxmox 7.2-15.
Running: `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm-v4.sh)" gives error` gives error: `‼ ERROR 1@260 Unknown failure occurred.` at "Creating HAOS VM..."

**Comment by tteck** [comment]
Check and see if you have a stray vm-_**VMID**_-disk-0 present. If so, remove it.

![260](https://user-images.githubusercontent.com/21342670/203175265-3e990f23-b0b6-4001-a138-032e7a28fd93.png)

**Comment by GnussonNet** [comment]
Works perfectly, thanks!

BTW, just a quick question, does this installation have USB passthrough? Or is it just for the LXC?

**Comment by tteck** [comment]
You pass a USB device differently in a VM

![Screenshot 2022-11-21 6 13 32 PM](https://user-images.githubusercontent.com/21342670/203177034-c032a590-c76b-4313-a762-837f3e0adf41.png)
