### ISSUE TITLE
post-pve-install.sh on pve-manager: 7.2-xx

### ISSUE THREAD

**Issue by ngadmini** [tteck/Proxmox#756]
Hi @tteck 

1. This line below not work on `pve-manager: 7.2-x with proxmox-widget-toolkit: 3.5.x`
https://github.com/tteck/Proxmox/blob/2abc2631429948e876905d4a29abb3752c4ff211/misc/post-pve-install.sh#L103

2. give value: **1** after running `apt --reinstall install proxmox-widget-toolkit`
`~# dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$' && echo "$?"` 
3. Command `sed -i '/data.status/{s/\!//;s/Active/NoMoreNagging/}'` give a false output, due to:  `proxmoxlib.js` line number 514 has been change as shown below: 
```
      ~# grep -PnB1 -A1 '^\t.*.toLowerCase.*{$' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js 
      513-                if (res === null || res === undefined || !res || res
      514:                    .data.status.toLowerCase() !== 'active') {
      515-                    Ext.Msg.show({
```
4. I've been write some various ways to getting rid nag message, . It might come in handy

Best Regards
nGadmini

**Comment by tteck** [comment]
I'm not seeing any issue with 7.2-15

![Screenshot 2022-11-22 6 47 04 AM](https://user-images.githubusercontent.com/21342670/203306759-dcb506da-f6ce-4045-9ed6-0262d76b194d.png)

**Comment by tteck** [comment]
With a fresh install of 7.3, a lower case "A" was necessary.
