### ISSUE TITLE
Nginx Proxy Manager /tmp/nginx/body

### ISSUE THREAD

**Issue by rogersa2k** [tteck/Proxmox#759]
**Describe the issue**
When the host boots the openresty and npm services fail to start due to a missing /tmp/nginx directory. If I create the path the services both start manually. If I reboot they fail again.

... systemd[1]: Starting The OpenResty Application Platform...
... nginx[224]: nginx: [emerg] mkdir() "/tmp/nginx/body" failed (2: No such file or directory)
... nginx[224]: nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed

I just deployed NPM via the script a few days ago.

**Comment by tteck** [comment]
Instead of me trying to figure out what you did, I'd suggest re-creating the LXC

**Comment by rogersa2k** [comment]
My bad. I usually keep notes on what I did:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nginx-proxy-manager-v4.sh)"

...   

Using Advanced Settings
Using Container Type: 1
Using Root Password: xxx
Using Container ID: 132
Using Hostname: npm101
Using Disk Size: 10
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using MAC Address: Default
Using Vlan: Default
Creating a Nginx Proxy Manager LXC using the above advanced settings
 ✓ Using xxx for Template Storage.
 ✓ Using xxx for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 132 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.165
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python
 ✓ Installed Openresty
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Yarn
 ✓ Downloaded Nginx Proxy Manager v2.9.19
 ✓ Set up Enviroment
 ✓ Built Frontend
 ✓ Initialized Backend
 ✓ Created Service
 ✓ Started Services
 ✓ Cleaned
 ✓ Completed Successfully!

Nginx Proxy Manager should be reachable by going to the following URL.
         http://192.168.1.165:81

**Comment by tteck** [comment]
That LXC shouldn't have issues
