### ISSUE TITLE
Cant open web ui for influx db.

### ISSUE THREAD

**Issue by tstill88** [tteck/Proxmox#760]
Ive installed the script via Influx DB using v1, everything reported OK but im not able to reach the web page via http://ip:8086

Are there any steps that i need to run before i can reach the ui?

**Comment by tteck** [comment]
Where did you see InfluxDB Interface IP:8086?

**Comment by tstill88** [comment]
Port 8086 is the default port for influx normally, am I wrong?

**Comment by tteck** [comment]
I thought Versions 1.3 and later do not support the web admin interface. 🤷🏻‍♂️  I've never used InfluxDB
