### ISSUE TITLE
Pages: Script Site Page 404

### ISSUE THREAD

**Issue by mhwilkes** [tteck/Proxmox#766]
**Describe the issue**
Looks like something is wrong with the GitHub Pages site for the proxmox scripts. Possibly may need a rebuild as I am getting 404 and have confirmed from multiple internet sources

**Comment by tteck** [comment]
Is it ok now?

**Comment by mhwilkes** [comment]
https://downforeveryoneorjustme.com/tteck.github.io.html
Showing that it is down for everyone

**Comment by tteck** [comment]
It's  up for me.

**Comment by tteck** [comment]
Try https://tteck.github.io/Proxmox/

**Comment by mhwilkes** [comment]
https://downforeveryoneorjustme.com/tteck.github.io?proto=https

Try that. Not up for me

**Comment by tteck** [comment]
[https://downforeveryoneorjustme.com](https://downforeveryoneorjustme.com/tteck.github.io?proto=https) doesn't work for github pages, it checks https://tteck.github.io

**Comment by tteck** [comment]
Try https://www.uptrends.com/tools/is-my-website-down

**Comment by mhwilkes** [comment]
Awesome, it looks like recently github.io pages were added to the HBlock list on adguard home so that seems to be the issue. Resolved!
