### ISSUE TITLE
Heimdall update breaks container

### ISSUE THREAD

**Issue by Deekerman** [tteck/Proxmox#771]
Heimdall just came out with a new update - https://www.reddit.com/r/selfhosted/comments/z3v68s/_/
Apparently they have overhauled a lot which seems to have made the update script not work. at least it gave me a bad gateway 502.

**Comment by tteck** [comment]
I didn't have an instance to update. I created a fresh install, that still works, so next I update that fresh install to see if the update script broke the install, worked as intended. I know that's not the best test but, that's all that I can do. 
Maybe someone else will chime in with their experience.

**Comment by Deekerman** [comment]
> I didn't have an instance to update. I created a fresh install, that still works, so next I update that fresh install to see if the update script broke the install, worked as intended. I know that's not the best test but, that's all that I can do. Maybe someone else will chime in with their experience.

does the new install build it on 2.5.1?

**Comment by tteck** [comment]
Yes. Seems there were issues with 2.5.0?

**Comment by 2600box** [comment]
Same experience, script says it updates to 2.5.1 and I cannot get the service up.

This seems to be the issue:

**EDIT:** confirmed, doing `apt update && apt upgrade -y` sorted it

```
root@heimdalldashboard:/opt/Heimdall# /usr/bin/php artisan serve --port 7990 --host 0.0.0.0
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.4.32". You are running 7.4.30.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.32". You are running 7.4.30. in /opt/Heimdall/vendor/composer/platform_check.php on line 24
```

**Comment by tteck** [comment]
https://github.com/linuxserver/Heimdall/releases/tag/v2.5.2

**Comment by Deekerman** [comment]
> apt update && apt upgrade -y

basically sorted it for me too. 

Thanks!
