### ISSUE TITLE
Whoogle Fails to Start

### ISSUE THREAD

**Issue by k0qed** [tteck/Proxmox#772]
After installing Whoogle using the whoogle-v4.sh script (default actions), the Whoogle service fails to start. I've removed the container and re-tried with the same results. Here's the output from systemctl status:

* whoogle.service - Whoogle-Search
     Loaded: loaded (/etc/systemd/system/whoogle.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-11-25 14:42:36 UTC; 18min ago
    Process: 12478 ExecStart=/usr/local/bin/whoogle-search --host 0.0.0.0 (code=exited, status=1/FAILURE)
   Main PID: 12478 (code=exited, status=1/FAILURE)
        CPU: 342ms

Nov 25 14:42:36 whoogle systemd[1]: whoogle.service: Main process exited, code=exited, status=1/FAILURE
Nov 25 14:42:36 whoogle systemd[1]: whoogle.service: Failed with result 'exit-code'.
Nov 25 14:42:36 whoogle systemd[1]: whoogle.service: Scheduled restart job, restart counter is at 6.
Nov 25 14:42:36 whoogle systemd[1]: Stopped Whoogle-Search.
Nov 25 14:42:36 whoogle systemd[1]: whoogle.service: Start request repeated too quickly.
Nov 25 14:42:36 whoogle systemd[1]: whoogle.service: Failed with result 'exit-code'.
Nov 25 14:42:36 whoogle systemd[1]: Failed to start Whoogle-Search.

Are there any other logs I can provide that would help?

Thanks

**Comment by tteck** [comment]
Thanks for reporting! Fixed

**Comment by k0qed** [comment]
Wow, that was fast! Works a charm. Thanks.
