### ISSUE TITLE
[ERROR] 255@116 when I install Plex

### ISSUE THREAD

**Issue by MrThiemann** [tteck/Proxmox#78]
Hey,
I would install Plex with your script. But when I use your command in Proxmox Shell, I became this error:

`
root@server:~# bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/plex_container.sh)"
This will create a New Plex Media Server LXC Container. Proceed(y/n)?y
[INFO] Using 'local-lvm' for Storage Location.
[INFO] Container ID is 100.
✔  Updating LXC Template List... 
✔  Downloading LXC Template... 
400 Parameter verification failed.
template: no such template
pveam download <storage> <template>
[ERROR] 255@116 A problem occured while downloading the LXC template.
environment: line 54: ROOTFS: unbound variable
root@server:~# `

maybe I'm wrong?
best regards from Germany, Karsten ;)

**Comment by tteck** [comment]
Don't know what's going on with downloading Ubuntu 21.10 template, I can't replicate the issue here.

**Comment by MrThiemann** [comment]
ok, thanks for the quick reply.
I then install ubuntu manually and then get plex via the "normal" way

**Comment by tteck** [comment]
You downloaded the template manually?

**Comment by MrThiemann** [comment]
no, I use your command in shell.
