### ISSUE TITLE
Technitium DNS LXC update script fails updating due to wrong version of .NET

### ISSUE THREAD

**Issue by besynnerlig** [tteck/Proxmox#780]
The latest Technitium version is 10 and it requires .NET version 7. The [update script](https://github.com/tteck/Proxmox/raw/main/misc/technitiumdns-update.sh) is targeting version 6 of .NET and Technitium fails to start after an update.

**Comment by tteck** [comment]
Would you test a46082ffaac6a9bcfce559d06b31ee30a9112cdb
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/technitiumdns-update.sh)"
```

**Comment by besynnerlig** [comment]
That worked for me updating Technitium from v9.1 to v10.0. Thanks!
