### ISSUE TITLE
502 After update to Paperless 1.10.0 from 1.9.2

### ISSUE THREAD

**Issue by poltrian** [tteck/Proxmox#789]
**Describe the issue**
I run the update Script to update from 1.9.2 to 1.1.0
After that i got a 502 when go to my paperless URL

**Comment by tteck** [comment]
It may take a minute or so for Paperless-ngx to become available. It's 1.10.0

**Comment by tteck** [comment]
All good?

**Comment by poltrian** [comment]
In paperless-schedule.service i got Paperless python3[114]: Unknown command: 'qcluster'
these service won't start. And i had to install django_celery_results'
'celery' to got the webservice to run

**Comment by tteck** [comment]
The update didn't finish. Run again

**Comment by poltrian** [comment]
in /opt/paperless ?

**Comment by tteck** [comment]
Run the update script from the lxc console. From root

**Comment by poltrian** [comment]
Run the script again, same result

**Comment by poltrian** [comment]
root@Paperless:~# sudo systemctl status paperless-scheduler.service
x paperless-scheduler.service - Paperless scheduler
     Loaded: loaded (/etc/systemd/system/paperless-scheduler.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-11-29 23:38:56 UTC; 17s ago
    Process: 114 ExecStart=python3 manage.py qcluster (code=exited, status=1/FAILURE)
   Main PID: 114 (code=exited, status=1/FAILURE)
        CPU: 516ms

Nov 29 23:38:55 Paperless systemd[1]: Started Paperless scheduler.
Nov 29 23:38:56 Paperless python3[114]: Unknown command: 'qcluster'
Nov 29 23:38:56 Paperless python3[114]: Type 'manage.py help' for usage.
Nov 29 23:38:56 Paperless systemd[1]: paperless-scheduler.service: Main process exited, code=exited, status=1/FAILURE
Nov 29 23:38:56 Paperless systemd[1]: paperless-scheduler.service: Failed with result 'exit-code'.

**Comment by tteck** [comment]
Is it finishing? If you look at the script, it overwrites `paperless-scheduler.service`
```
cat <<EOF >/etc/systemd/system/paperless-scheduler.service
[Unit]
Description=Paperless Celery beat
Requires=redis.service
[Service]
WorkingDirectory=/opt/paperless/src
ExecStart=celery --app paperless beat --loglevel INFO
[Install]
WantedBy=multi-user.target
EOF
```
it removes qcluster

**Comment by tteck** [comment]
Just to make sure... the update script has to run in the paperless lxc console, not the Proxmox shell

**Comment by poltrian** [comment]
Yes, I'm in paperless LXC. And the scheduler is running. But when i try to upload a document it still waiting and will not upload. i have no idea why the script not run correctly

**Comment by tteck** [comment]
Run the update script and show the output

**Comment by poltrian** [comment]
There is no output.... stopping paperless-ngx is the only

**Comment by tteck** [comment]
then?

**Comment by poltrian** [comment]
nothing more
![Bildschirmfoto vom 2022-11-30 01-11-11](https://user-images.githubusercontent.com/50879520/204676333-c72e8dc8-634d-4b83-84db-38c406f096fd.png)

**Comment by tteck** [comment]
```
    ____                        __                                     
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/           UPDATE                        /____/        
This will Update Paperless-ngx to v1.10.0. Proceed(y/n)?y
 ✓ Stopped Paperless-ngx
 ✓ paperless-task-queue.service Exists.
 ✓ Updated to v1.10.0
 ✓ Cleaned
 ✓ Finished Update

It may take a minute or so for Paperless-ngx to become available.

root@paperless-ngx:~# 
```
Something may be blocking you (network). Can you manually download the file?
```
wget https://github.com/paperless-ngx/paperless-ngx/releases/download/v1.10.0/paperless-ngx-v1.10.0.tar.xz
```
Did you change the hostname ?

**Comment by poltrian** [comment]
no the hostname is the same. What i have to do after extract these files?

**Comment by tteck** [comment]
You may have to dissect the update script and run it line by line to find where the issue is 🤷🏻‍♂️ 
https://raw.githubusercontent.com/tteck/Proxmox/main/misc/paperless-ngx-update.sh

**Comment by tteck** [comment]
Remove it. `rm paperless-ngx-v1.10.0.tar.xz`

**Comment by poltrian** [comment]
Thanks for your help, but i have no luck with paperless. There is no easy way to update, except your script., If i ask on Github or Matrix i got no or the wrong answer. No one can tell how to update paperless correctly and what's to. I have no problem to update my other Servers. But Paperless i have no luck with updates.

**Comment by tteck** [comment]
Did you use the Paperless-ngx LXC script from this repo to install it?

**Comment by poltrian** [comment]
No, installed step by step from the Paperless -ngx docs. But i updatet to 1.90 &1.91 and 1.92 with your script

**Comment by tteck** [comment]
Oof... yeah, that's an issue. Good luck.

**Comment by poltrian** [comment]
I’m on Ubuntu 22.04 could these be the problem?

**Comment by poltrian** [comment]
Got it work. I reinstalled some stuff from python and now your script works. Thanks again.
