### ISSUE TITLE
Filebrowser LXC not installing

### ISSUE THREAD

**Issue by dragosde** [tteck/Proxmox#802]
**Describe the issue**
Trying to install the Filebrowser LXC.

Pasting this command in the console:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/filebrowser.sh)"

It errors out with this:

- Installing FileBrowser...‼ ERROR 1@67 Unknown failure occured.

![Screenshot 2022-12-03 150322](https://user-images.githubusercontent.com/78012264/205459691-f274febc-f506-4155-b38d-2b5249973f47.png)

**Comment by tteck** [comment]
Can't replicate 🤷🏻‍♂️ 
```
  ______ _ _      ____                                  
 |  ____(_) |    |  _ \                                 
 | |__   _| | ___| |_) |_ __ _____      _____  ___ _ __ 
 |  __| | | |/ _ \  _ <|  __/ _ \ \ /\ / / __|/ _ \  __|
 | |    | | |  __/ |_) | | | (_) \ V  V /\__ \  __/ |   
 |_|    |_|_|\___|____/|_|  \___/ \_/\_/ |___/\___|_|   

 ✓ Installed FileBrowser on debian
 ✓ Created Service
 ✓ Completed Successfully!

FileBrowser should be reachable by going to the following URL.
         http://192.168.86.252:8080 

```

**Comment by dragosde** [comment]
Yeah, must be my system, DNS and such... Sorry to bother. 
Please close

**Comment by dragosde** [comment]
I haven't figured it out yet but it must be my system

**Comment by warmbo** [comment]
Same issue here on a fresh install attempt of Filebrowser into the Homepage LXC.

**Comment by tteck** [comment]
I've noticed that you may have to run the script several times before you get a successful install.  🤷🏻‍♂️

**Comment by timdonovanuk** [comment]
Run it 6 times, get `Installing FileBrowser...‼ ERROR 1@71 Unknown failure occured.`

Is there a way to be more verbose with the installer?

**Comment by tteck** [comment]
New release causing issues, working on

**Comment by tteck** [comment]
fixed
