### ISSUE TITLE
MQTT Install script fails with 'bash: line 221: SSH: unbound variable'

### ISSUE THREAD

**Issue by pkerspe** [tteck/Proxmox#808]
**Describe the issue**
When executing the V4 of the MQTT LXC install script using
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/mqtt-v4.sh)"`
in Proxmox V7 it starts capturing the input from the user, but when the installation is started, if fails with 'bash: line 221: SSH: unbound variable'

**Screenshots**
<img width="540" alt="Bildschirmfoto 2022-12-05 um 19 31 22" src="https://user-images.githubusercontent.com/9518308/205714547-865e8d3a-7172-4064-bfba-f3550958708a.png">

**Comment by tteck** [comment]
Fixed.

**Comment by tteck** [comment]
FYI, your static IP Address should be `192.168.178.3/24`

**Comment by pkerspe** [comment]
thanks for the quick fix!
Yeah, I noticed that missing block size config also later on :-)
