### ISSUE TITLE
HAOS VM - Getting error on Proxmox 7.3-3 Console

### ISSUE THREAD

**Issue by bearhntr** [tteck/Proxmox#809]
I have just installed using your script and found that Advanced setup was GREAT, only change I had to make before starting the VM for the first time (as Q35 UEFI) was I gave the HDD 32 additional GB.  Script completed with no errors, but when I started the VM, I get this error.  

![image](https://user-images.githubusercontent.com/100164602/205721139-c717795f-b9c2-48a6-a2e3-baeec8954505.png)

Also - see that the QEMU Agent is installed.  Are you going to be adding this, or have steps do add it to your install?  

![image](https://user-images.githubusercontent.com/100164602/205721429-68b9aee4-5674-49cb-8401-36455ce6159c.png)

I ask about that -- as I do not seem to be able to Shutdown or Stop the VM.

![image](https://user-images.githubusercontent.com/100164602/205721795-cbdfbdae-24e3-4ff1-a0cc-b30aa30e13e8.png)

Great work on the script - made the install so much easier, as I want to migrate to a VM for HomeAssistant.

**Comment by tteck** [comment]
I have no idea how you got to this point?
All I did was run the script, go through "Advanced" and select q35 and select "No" to "Start VM when completed" When the script ended, I added 32gb to the disk and started the VM. Simple

![Screenshot 2022-12-05 2 22 45 PM](https://user-images.githubusercontent.com/21342670/205724872-9b82f212-50b5-4d6e-9e3c-c32f1d838443.png)
![Screenshot 2022-12-05 2 12 46 PM](https://user-images.githubusercontent.com/21342670/205723710-5f8d961b-879a-4608-a431-eae5e466e2e6.png)
![Screenshot 2022-12-05 2 13 50 PM](https://user-images.githubusercontent.com/21342670/205723743-a4b4dcfb-08ea-47c0-a050-7f2140cfaf8b.png)

Edit: I ran the script twice. Once without adding 32gb before starting, then adding 32gb before starting. (the reason the pics don't look right 😉 )

**Comment by bearhntr** [comment]
@tteck 

  You Got Me....  :-(   

  I did the same thing.  I used the steps here:   https://www.wundertech.net/how-to-set-up-home-assistant-on-proxmox/

  Opened SHELL on the Proxmox box (where I have pfSense and 2x Windows VMs already running with no problems).  

  I stepped through the install, got to the end with no issues.  I then edited the HDD and gave it 32GB (total of 64GB) and during the step-through I gave it 4x cores and 8192 for RAM (to match the ThinClient I want to replace.  I did not even add the USB pass-through that I know I will need for ZWave, Bluetooth and Zigbee dongles.  
  
    I Started it, and I immediately get the "Guest has not initialized the display" error...but I get that on all of them at first...but eventually I will get the display.  Never for this VM and find that I have to "STOP" (force off the VM to get out of it)....no QEMU Guest Agent install - "Shutdown" does not work.  :-(

**Comment by tteck** [comment]
How did you set it to q35?

**Comment by bearhntr** [comment]
@tteck 

  I just deleted the VM and re-ran the script.  Here is what I see in the SHELL
  
  
![image](https://user-images.githubusercontent.com/100164602/205730014-8f4ec6bc-6950-4782-b681-6a2311e57cd2.png)

I made no changes other than what you see.  This time, I did not even add the +32GB HD.  I started the VM....and I get this:

![image](https://user-images.githubusercontent.com/100164602/205730224-b579c28d-28de-45bb-8a1d-1e84cca5ddcc.png)

Here is the Hardware for the VM:

![image](https://user-images.githubusercontent.com/100164602/205730323-86696ea0-938a-4e1f-a8df-e88ee2af717d.png)


So VMBR2 = the same port that the LAN port for the pfSense is using.  Should be able to do that, as the Windows (v7 and v10) VMs are also using that port and work just fine.

**Comment by tteck** [comment]
What file system are you using? 
You're not using thin provisioning?
Your Hard Disk & EFI Disk look strange.

**Comment by tteck** [comment]
What guide did you follow to install Proxmox?

**Comment by bearhntr** [comment]
> How did you set it to q35?

During the installation (step-through).  

I just removed it, again and rebooted the Host...  (Proxmox 7.3-3 - just installed all updates this past Saturday).

**Comment by tteck** [comment]
There's something strange with your Proxmox setup

**Comment by bearhntr** [comment]
> What guide did you follow to install Proxmox?

I do not remember, been months - I downloaded the .ISO and made a bootable USB.  Booted the Computer with it, and installed it.  Then disabled the Enterprise Repository.   Have had no issues -- I have to manually install any updates - but it does show them to me when there are some to install.  

pfSense, Win7 and Win10 are all installed q35 as UEFI with no issues.

**Comment by bearhntr** [comment]
![image](https://user-images.githubusercontent.com/100164602/205734030-564a9292-1469-4d0b-a825-4b85f6972f81.png)

**Comment by bearhntr** [comment]
![image](https://user-images.githubusercontent.com/100164602/205734205-e3f62c73-68ce-4003-854c-0e2a58103460.png)

**Comment by tteck** [comment]
Why did you delete local-lvm?

**Comment by bearhntr** [comment]
The installation guide I was using had me do that - so that I could see the whole disk capacity from the 500GB disk.

**Comment by tteck** [comment]
Network Chuck steered you wrong!

**Comment by bearhntr** [comment]
I have not had any issues with any of the other VMs that I have created on this server - a former OPNsense install, a DEBIAN 11 install and a UBUNTU install (all of them also using q35 with UEFI).  So - not sure what is different.  

I just ran your script and chose to use Defaults:

![image](https://user-images.githubusercontent.com/100164602/205735590-a91a6c59-4284-4701-838b-5b0208e107c3.png)

It completed and started the VM -- and I see this:

![image](https://user-images.githubusercontent.com/100164602/205735937-91cb0bc2-6208-468c-ad20-a4e31b09a948.png)

Also very strange -- as it pulled an IP address from the wrong network.

**Comment by tteck** [comment]
Bottom line... i440fx is the only way to get Home Assistant OS to work in that mess

**Comment by bearhntr** [comment]
Nevermind -  I see the IP issue -  It is using the vmbr0 and not vmbr2.

**Comment by bearhntr** [comment]
> Bottom line... i440fx is the only way to get Home Assistant OS to work in that mess

I am sorry - but that does not make any sense...  😥  As I have many other installs - since removed which all used q35 and UEFI with no issues.

**Comment by bearhntr** [comment]
![image](https://user-images.githubusercontent.com/100164602/205736835-950ec7a8-d0fe-480c-88e9-5306116d6e8b.png)

**Comment by tteck** [comment]
Without local-lvm, you have no thin provisioning.
I'd suggest starting over without Network Chuck's advise!
You'll be much better in the long run.

**Comment by bearhntr** [comment]
Even in my ESXi days - was never a fan of Thin-Provisioning.

**Comment by bearhntr** [comment]
Changed the vmbr to the right one, and now it has pulled an IP where I want it.

**Comment by bearhntr** [comment]
I appreciate the 'looksie', and the script -  It is running now with QEFI and i440fx.

  I need to test the USB pass-thru stuff with the dongles.

**Comment by bearhntr** [comment]
@tteck 

> Bottom line... i440fx is the only way to get Home Assistant OS to work in that mess

Looking at your script -- I see this, but I was never asked about "storage pool"

```
STORAGE_MENU+=( "$TAG" "$ITEM" "OFF" )
done < <(pvesm status -content images | awk 'NR>1')
VALID=$(pvesm status -content images | awk 'NR>1')
if [ -z "$VALID" ]; then
msg_error "Unable to detect a valid storage location."
  exit
elif [ $((${#STORAGE_MENU[@]}/3)) -eq 1 ]; then
  STORAGE=${STORAGE_MENU[0]}
else
  while [ -z "${STORAGE:+x}" ]; do
    STORAGE=$(whiptail --title "Storage Pools" --radiolist \
    "Which storage pool you would like to use for the HAOS VM?\n\n" \
    16 $(($MSG_MAX_LENGTH + 23)) 6 \
    "${STORAGE_MENU[@]}" 3>&1 1>&2 2>&3) || exit
  done
```

**Comment by tteck** [comment]
It only pops up if you have multiple storage locations for disk image.

**Comment by tteck** [comment]
If you would, try the script now in q35

**Comment by bearhntr** [comment]
@tteck 

> If you would, try the script now in q35

Just saw this - I was tired of sitting in front of the computer (as I had been there all day for work, and I needed a break).  I have just done this (I guess -- I re-ran this in the PROXMOX Shell)

**_bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/vm/haos-vm-v4.sh)"_**  )

and I got this:

![image](https://user-images.githubusercontent.com/100164602/205932141-aa4d6690-6985-4ef9-943f-9cd6ce88abda.png)


WOO HOO!!!!!     You Da Man!    It started up - has proper IP Address, and I changed nothing after the script ran.  

![image](https://user-images.githubusercontent.com/100164602/205932571-ee6bdcac-c60e-4d7e-97ee-cfdc410254a2.png)

**Comment by bearhntr** [comment]
Went to one of the VMs in that IP range - and ouila!!

![image](https://user-images.githubusercontent.com/100164602/205932860-a0a57c92-9f6a-4e18-b906-5818cbfb4b57.png)

**Comment by bearhntr** [comment]
I am contemplating re-doing the PROXMOX (as you suggested "without Network Chuck") - researching how best to back up all my VMs so that I can easily put them back - hopefully.   Although rebuilding them all is not out of the question (save the Windows 7 one - that one was a B*)

**Comment by tteck** [comment]
All of my backups go to an external USB NVME drive (formatted fat32 so any PC can see the files). I can re-install Proxmox, restore from backup in a matter of minutes.

**Comment by bearhntr** [comment]
> All of my backups go to an external USB NVME drive (formatted fat32 so any PC can see the files). I can re-install Proxmox, restore from backup in a matter of minutes.

How are you doing that?  Still learning the 'tricks' to Proxmox - did you just plug in a USB HDD (got plenty of those) and then what?

**Comment by tteck** [comment]
It's easy, first I created a directory (`mkdir /mnt/backups`) then found the location of my drive

![Screenshot 2022-12-06 9 16 09 AM](https://user-images.githubusercontent.com/21342670/205936099-576cea7f-4fb5-40c2-8735-64511b1b2fe7.png)

and mount it to the directory (`mount /dev/sdb1 /mnt/backups`) then add the directory through Datacenter

![Screenshot 2022-12-06 9 19 47 AM](https://user-images.githubusercontent.com/21342670/205936894-d1aa0f22-6b48-4596-bb6d-f86487a17d74.png)

**Comment by tteck** [comment]
I wanted the USB drive to mount at boot so that I didn't have to manually mount (`mount /dev/sdb1 /mnt/backups`) at every restart. So, I found the disk UUID (`blkid /dev/sdb1`)
```
root@server:~# blkid /dev/sdb1
/dev/sdb1: UUID="0EFB-13DF" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="Basic data partition" PARTUUID="3fc3c59a-b93a-11ec-afb4-b881988f15ab"
root@server:~# 
```
then edited fstab
```
nano /etc/fstab
UUID=0EFB-13DF /mnt/backups vfat defaults 0 0
```

**Comment by bearhntr** [comment]
@tteck 

  Thanks for that -- I have backups now of 3 of the 6 VMs on the box.  

  Do you think that I will have any issues restoring them - if I go back to the LOCAL-LVM model (default for PROXMOX) instead of the N-C model of having only LOCAL storage?

**Comment by tteck** [comment]
Shouldn't have any issues.

**Comment by bearhntr** [comment]
Well - no problems installing --  I completely rebuilt my Proxmox, and left everything as Default (using ZFS_Raid0) drive as I only have 1 HDD in box.  

Script installed with no issues -- now to see if I can configure.  (After I put my 2 Windows VMs back on Proxmox).

![image](https://user-images.githubusercontent.com/100164602/206729271-aa75faeb-56f8-49a2-8f51-798b5fd91031.png)

**Comment by bearhntr** [comment]
Looks like no issues -- pulled IP Address and started up (installed as q35 and UEFI).  Again - thanks for the updated script.

![image](https://user-images.githubusercontent.com/100164602/206731616-2c5938b6-555f-40f9-b65d-dd9e0f46c8ed.png)

![image](https://user-images.githubusercontent.com/100164602/206731774-87671921-c1bd-463c-8227-3c7b07077af5.png)

**Comment by bearhntr** [comment]
Well - this is not good - the EXT 1TB USB drive where I made backups -- I cannot get it to be seen to put them back.  :-(

![image](https://user-images.githubusercontent.com/100164602/206735058-047298cb-f419-4eec-8a1b-64e186d168d2.png)

**Comment by tteck** [comment]
check and make sure of the disk location

![image](https://user-images.githubusercontent.com/21342670/206735829-c6743e1e-4553-402c-aba8-e27eb6bb01d0.png)

**Comment by bearhntr** [comment]
I got it --  I was trying to add the wrong  /dev/sdb1  --  should have used the "mount point" -- /media/backups    -- Silly me.  🙄

![image](https://user-images.githubusercontent.com/100164602/206738952-af87a6fe-7892-45b1-8ef5-16375f1f9195.png)

**Comment by bearhntr** [comment]
This is what I was afraid of -- as my DISKS have changed --  does not look like they are going to restore  😥

![image](https://user-images.githubusercontent.com/100164602/206740160-52583454-c8e2-4994-9c6c-f1d1b80fbda7.png)

**Comment by bearhntr** [comment]
I rebooted - re-mounted and now it looks like it is going.  Weird!!!

![image](https://user-images.githubusercontent.com/100164602/206742017-0220acf9-1808-4559-8b33-6ce5786854ef.png)

**Comment by bearhntr** [comment]
Well --  DAMN!   It restored, but will not start!

**Comment by bearhntr** [comment]
Well that was fun - I am back....well at least with the first of 6 restores on the new Proxmox.  I had to run this in the Proxmox shell.  As I had used the VirGL video driver - which I have found does best for me in Windows installations.  Maybe I play with some others.

apt install libgl1 libegl1

**Comment by johny-mnemonic** [comment]
I have stumbled into the same issue. When I select the q35 type, it gets stuck and never connects to display.
What was your fix to make it working?
I tried changing the type of created VM to i440fx and that works, but I understood from above comments that you somehow made it working with q35 :monocle_face:
