### ISSUE TITLE
Non clickable menu

### ISSUE THREAD

**Issue by CajonCP4** [tteck/Proxmox#819]
**Describe the issue**
Hi, I'm working with:

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx-v4.sh)"

and after I choose the default set up it asks on what storage I want to install it, but I won't let me pick an option.

**Screenshots**
![Screenshot_20221208_210246](https://user-images.githubusercontent.com/66467472/206556565-fd6e57b5-fffa-4727-ab72-c047705f6d40.png)

**Comment by tteck** [comment]
Spacebar
https://github.com/tteck/Proxmox/issues/394

**Comment by CajonCP4** [comment]
I really tried everything else :D thanks
