### ISSUE TITLE
[Plex Media Server LXC ] Unable to automatic login / change password

### ISSUE THREAD

**Issue by carlreid** [tteck/Proxmox#83]
After deploying the Plex Media Server LXC, then rebooting the LXC, I am unable to login:

Attempt with console:
```
Ubuntu 21.10 plex tty1
plex login: root (automatic login)

Authentication failure
```

Attempt with shell, using `pct enter <cid>`
```
root@proxmox:~# pct enter 103
bash: /root/.bashrc: Permission denied
root@plex:~#
```

Attempting to change the password from CT:
```
root@plex:~# passwd root
New password: 
Retype new password: 
passwd: Authentication token manipulation error
passwd: password unchanged
root@plex:~#
```

I'm new to all this, so maybe I am just being stupid and missed something? Seems other templates work beautifully though 👌

**Comment by tteck** [comment]
I'd recommend removing CT and starting over

**Comment by carlreid** [comment]
How odd... I had removed the CT and started over a couple times before opening this issue, but literally just tried it again and it seems alright now 🤪

I'll re-open if I manage to hit again with some better reproduce steps.
