### ISSUE TITLE
Help updating kernel from HassOS vm script - not a bug

### ISSUE THREAD

**Issue by ASchneiderBR** [tteck/Proxmox#831]
Hello!

Sorry to bother but I'm sort of new to everything here and have been facing random crashes and restarts with the Home Assistant OS VM machine created with your script.

After a couple of days researching, I've found that this might be a problem with my Intel N5095A CPU and many users said that updating its kernel might help.

I did that using your script, from the node console, now I'm running kernel v6, perfect :)

But when I ask for the version inside my VM running HassOS, I get version `5.15.74`. Is there a way to update this, just like I did over the node level or it is OK to have it like this?

![image](https://user-images.githubusercontent.com/25224882/207038475-6d050192-4446-4c33-a49d-09f230dd3703.png)

![image](https://user-images.githubusercontent.com/25224882/207038721-989b2156-3b17-4391-9281-aef194199743.png)

Thanks!

**Comment by tteck** [comment]
The kernel in Home Assistant OS is "baked" in, can't change it. Hopefully by updating the PVE kernel will solve your issues.

**Comment by ASchneiderBR** [comment]
Got it, thanks. Have a great day!
