### ISSUE TITLE
Error when trying to install Nginx Proxy Manager LXC 

### ISSUE THREAD

**Issue by sendarion** [tteck/Proxmox#837]
Hello, an error appears during install after "Installed Yarn" :

![Capture d’écran 2022-12-15 175244](https://user-images.githubusercontent.com/113645394/207921230-94c40e09-6bb9-471d-b488-205dc8b98179.png)

**Comment by tteck** [comment]
It's not getting the release version

run in the shell to test (output should show `2.9.19`)
```
curl -s https://api.github.com/repos/NginxProxyManager/nginx-proxy-manager/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }'
```
There's no issues here.

**Comment by sendarion** [comment]
Indeed it shows 2.9.19 when I enter your command.
I tried again, and it finishes without a problem Oo.

Not sure what happended here but cool ^^" thanks for the quick response!

![Capture d’écran 2022-12-15 182339](https://user-images.githubusercontent.com/113645394/207926899-15eae177-2714-442d-b609-5a0b0d4d03c6.png)
