### ISSUE TITLE
Jellyfin install script error on Hard Accel

### ISSUE THREAD

**Issue by MysterJay** [tteck/Proxmox#841]
Using Advanced Settings
Using Ubuntu Version: 22.04
Using Container Type: 0
Using Root Password: seesmalls
Using Container ID: 202
Using Hostname: jellyfin
Using Disk Size: 16
Allocated Cores: 2
Allocated RAM: 3096
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: Yes
Creating a Jellyfin LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 202 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.1.233
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4 github.com 64
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Setting Up Hardware Acceleration...‼ ERROR 100@92 Unknown failure occurred.

-------------------------------------------------------------------------
The install script only has 2 commands in this section , so I attempted to run them by hand to help diagnose the issue.
  apt-get -y install \
    va-driver-all \
    ocl-icd-libopencl1 \
    beignet-opencl-icd &>/dev/null

This line fails with: Package     beignet-opencl-icd has no installation canidate.

**Comment by tteck** [comment]
Use Ubuntu 20.04

**Comment by TakeusV1** [comment]
Now, when i try to install jellyfin (in 20.04), the hardware acceleration configuration is not done anymore, why did you remove it? it's too convenient... How can I get it back?

**Comment by tteck** [comment]
If the LXC is created unprivileged, it skips hardware acceleration.

**Comment by TakeusV1** [comment]
Actually my original problem was something else, when I update the container (update the version of jellyfin [jellyfin-web...]), the hardware acceleration doesn't work anymore, do you have an idea?

**Comment by tteck** [comment]
Check the FFmpeg path: `/usr/lib/jellyfin-ffmpeg/ffmpeg`

**Comment by TakeusV1** [comment]
Yes, that's the first thing I checked, and it's not that, the path was still the

**Comment by tteck** [comment]
🤷🏻‍♂️  I don't know how a Jellyfin software update (apt update) could effect hardware settings.

Check your `/etc/pve/lxc/xxx.conf` to confirm the following is there
```
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
```

**Comment by TakeusV1** [comment]
**To recap**
```root@jellyfin:/usr/share/jellyfin/web# apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
#
# News about significant security updates, features and services will
# appear here to raise awareness and perhaps tease /r/Linux ;)
# Use 'pro config set apt_news=false' to hide this and future APT news.
#
The following packages will be upgraded:
  jellyfin-server jellyfin-web
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 80.9 MB of archives.
After this operation, 1,024 B disk space will be freed.
Do you want to continue? [Y/n]
Get:1 https://fra1.mirror.jellyfin.org/ubuntu focal/main amd64 jellyfin-server amd64 10.8.8-1 [38.6 MB]
Get:2 https://fra1.mirror.jellyfin.org/ubuntu focal/main amd64 jellyfin-web all 10.8.8-1 [42.3 MB]
Fetched 80.9 MB in 4s (20.8 MB/s)
(Reading database ... 21265 files and directories currently installed.)
Preparing to unpack .../jellyfin-server_10.8.8-1_amd64.deb ...
Stopping Jellyfin!
Unpacking jellyfin-server (10.8.8-1) over (10.8.7-1) ...
Preparing to unpack .../jellyfin-web_10.8.8-1_all.deb ...
Unpacking jellyfin-web (10.8.8-1) over (10.8.7-1) ...
Setting up jellyfin-web (10.8.8-1) ...
Setting up jellyfin-server (10.8.8-1) ...
Processing triggers for systemd (245.4-4ubuntu3.19) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
root@jellyfin:/usr/share/jellyfin/web#
```
**After this, when I start a video :** 
![Capture d’écran 2022-12-18 151439](https://user-images.githubusercontent.com/68923554/208303298-b9a9eb4a-5659-4864-9f6e-7322f3b7341f.png)
**But nothing seems to have changed in the encoding settings :**
![Capture d’écran 2022-12-18 151806](https://user-images.githubusercontent.com/68923554/208303378-73a2ec53-5a90-4789-b534-d993b7c18417.png)
**And everything looks good in the container configuration too :**
![Capture d’écran 2022-12-18 151854](https://user-images.githubusercontent.com/68923554/208303412-22c723ee-6767-477f-a069-cf0d3373ec3e.png)

**Comment by tteck** [comment]
Maybe [jellyfin-ffmpeg](https://github.com/jellyfin/jellyfin-ffmpeg/releases/) needs updating? What version do you have? `/usr/lib/jellyfin-ffmpeg/ffmpeg -version`

**Comment by TakeusV1** [comment]
![Capture d’écran 2022-12-18 154626](https://user-images.githubusercontent.com/68923554/208304780-6f097b8e-65b4-4ff7-9fe5-4fbd1a82e0d8.png)

**Comment by tteck** [comment]
4.4.1
Not saying that updating ffmpeg will fix it (I don't use Jellyfin) but it may be worth a try
```
apt-get install -y libxcb-randr0
wget -qL https://github.com/jellyfin/jellyfin-ffmpeg/releases/download/v5.1.2-5/jellyfin-ffmpeg5_5.1.2-5-focal_amd64.deb
sudo dpkg -i jellyfin-ffmpeg5_5.1.2-5-focal_amd64.deb
rm jellyfin-ffmpeg5_5.1.2-5-focal_amd64.deb
```

**Comment by TakeusV1** [comment]
it doesn't solve the problem ):

**Comment by tteck** [comment]
even after a reboot?

**Comment by TakeusV1** [comment]
yes

**Comment by tteck** [comment]
I'm out of ideas, sorry.

**Comment by tteck** [comment]
`/usr/lib/jellyfin-ffmpeg/ffmpeg -version` shows 5.1.2

**Comment by TakeusV1** [comment]
yes
