### ISSUE TITLE
- Building Vaultwarden 1.26.0 (Patience)...‼ ERROR 101@115 Unknown failure occurred.

### ISSUE THREAD

**Issue by GRaNTMaTT** [tteck/Proxmox#863]
I am trying to use the vaultwarden-v4.sh script to create a Vw lxc on my PVE. I have tried this multiple times, but it always fails on the Building Vaultwarden step and I cannot figure out why. Is there some sort of log I can look at to see what is causing the failure?

Creating a Vaultwarden LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs-nvme for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 103 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.20.178 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 192.30.255.112
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Rust
 **- Building Vaultwarden 1.26.0 (Patience)...‼ ERROR 101@115 Unknown failure occurred.**

Anyone else?

**Comment by tteck** [comment]
No issues here

```
 _    _____   __  ____  _______       _____    ____  ____  _______   __
| |  / /   | / / / / / /_  __/ |     / /   |  / __ \/ __ \/ ____/ | / /
| | / / /| |/ / / / /   / /  | | /| / / /| | / /_/ / / / / __/ /  |/ / 
| |/ / ___ / /_/ / /___/ /   | |/ |/ / ___ |/ _, _/ /_/ / /___/ /|  /  
|___/_/  |_\____/_____/_/ v4 |__/|__/_/  |_/_/ |_/_____/_____/_/ |_/   

Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 113
Using Hostname: vaultwarden
Using Disk Size: 6
Allocated Cores: 2
Allocated RAM: 3072
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Vaultwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Rust
 ✓ Built Vaultwarden 1.26.0
 ✓ Downloaded Web-Vault v2022.12.0
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Set Container to Normal Resources
 ✓ Completed Successfully!

Vaultwarden should be reachable by going to the following URL.
         http://192.168.86.252:8000 
```
All that I can suggest is throw all the resources you have at it 
Plenty of reading here https://github.com/tteck/Proxmox/issues?q=vaultwarden

**Comment by GRaNTMaTT** [comment]
Ok, I increased the CPU count to 4 and bumped the RAM to 4GB and I am getting further along, but getting a new error.

bash: line 195: SSH_ROOT: unbound variable

 _    _____   __  ____  _______       _____    ____  ____  _______   __
| |  / /   | / / / / / /_  __/ |     / /   |  / __ \/ __ \/ ____/ | / /
| | / / /| |/ / / / /   / /  | | /| / / /| | / /_/ / / / / __/ /  |/ / 
| |/ / ___ / /_/ / /___/ /   | |/ |/ / ___ |/ _, _/ /_/ / /___/ /|  /  
|___/_/  |_\____/_____/_/ v4 |__/|__/_/  |_/_/ |_/_____/_____/_/ |_/   

Using Advanced Settings
Using Debian Version: 11
Using Container Type: 1
Using Root Password: Lag1976
Using Container ID: 103
Using Hostname: vaultwarden
Using Disk Size: 6
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using MAC Address: Default
Using Vlan: Default
Creating a Vaultwarden LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs-nvme for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 103 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.20.187 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 192.30.255.113
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Rust
 ✓ Built Vaultwarden 1.26.0
 ✓ Downloaded Web-Vault v2022.12.0
 ✓ Created Service
bash: line 195: SSH_ROOT: unbound variable

**Comment by tteck** [comment]
Where are you getting the `vaultwarden-v4.sh` from? Because the one you're running doesn't have a few options, 
like `Using DNS Search Domain`, `Using DNS Server IP Address`,  `Enable Root SSH Access` and `Enable Verbose Mode`. Look at the output from mine. (above)

EDIT: Best to run the one from this repo
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/vaultwarden-v4.sh)"
```

**Comment by tteck** [comment]
`Using Debian Version: 11` was removed September 13 with https://github.com/tteck/Proxmox/pull/506 So, the one you're using is ***old***

**Comment by GRaNTMaTT** [comment]
Got it working by re-downloading the script :)

Is there no way to run this LAN only without a reverse proxy for SSL? I just want to run this on my LAN and use a VPN to connect devices outside the network without opening ports on my firewall.

**Comment by tteck** [comment]
Maybe (Google?). I have mine going through a reverse proxy.

**Comment by GRaNTMaTT** [comment]
Do you have to open ports on your firewall to make it work?

**Comment by tteck** [comment]
I forward port 80 and 443 from my router to my Nginx Proxy Manager LXC IP.
