### ISSUE TITLE
To Update Vaultwarden

### ISSUE THREAD

**Issue by danny1605** [tteck/Proxmox#865]
update is no longer possible, with the following command to the latest version.

bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/vaultwarden-update.sh)"

![Screenshot 2022-12-23 115450](https://user-images.githubusercontent.com/59099140/209324125-b0b2496d-21a1-4089-881f-50c5a7f89081.png)

**Comment by tteck** [comment]
No issues here

![Screenshot 2022-12-23 6 00 13 AM](https://user-images.githubusercontent.com/21342670/209326162-e2453a93-d887-433c-9ad2-a9c37fe8be61.png)

```
This will Update Vaultwarden to 1.26.0 (Ensure you set 2vCPU 3072MiB RAM Min.). Proceed(y/n)?y
 Stopping Vaultwarden... 
 Updating (Building) to 1.26.0 (Patience)... 
 Starting Vaultwarden 1.26.0... 
 Cleaning up... 
 Finished Update (Ensure you set resources back to normal settings)
root@vaultwarden:~# 
```

![Screenshot 2022-12-23 6 08 00 AM](https://user-images.githubusercontent.com/21342670/209326197-27aa860a-ec31-415a-9dd5-eecbfd92421b.png)

**Comment by danny1605** [comment]
the second time it worked, I do not know, sorry. Please close the issue. thx
