### ISSUE TITLE
Updating Vaultwarden don't work 

### ISSUE THREAD

**Issue by damadorPL** [tteck/Proxmox#866]
root@vaultwarden:~# bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/vaultwarden-update.sh)"

 __      __         _ _                         _            
 \ \    / /        | | |                       | |           
  \ \  / /_ _ _   _| | |___      ____ _ _ __ __| | ___ _ __  
   \ \/ / _  | | | | | __\ \ /\ / / _  |  __/ _  |/ _ \  _ \ 
    \  / (_| | |_| | | |_ \ V  V / (_| | | | (_| |  __/ | | |
     \/ \__,_|\__,_|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|
                        1.27.0 UPDATE                                                                                                                        

This will Update Vaultwarden to 1.27.0 (Ensure you set 2vCPU 3072MiB RAM Min.). Proceed(y/n)?y
 Stopping Vaultwarden... 
 Updating (Building) to 1.27.0 (Patience)... 
root@vaultwarden:~# 

Just break after one second - tested even with 8 CPU / 8 GB ram ...

**Comment by damadorPL** [comment]
ok - seems that removing vaultwarden dir form home in LXC fixed it :) 

script should check for dir and remove it before redownload and update

**Comment by tteck** [comment]
Why was anything pertaining to Vaultwarden in `/home`?
