### ISSUE TITLE
Vaultwarden import database

### ISSUE THREAD

**Issue by tomdh76** [tteck/Proxmox#87]
I have used the script and a running LXC container after changing in the env file ROCKET ADRESS. 
I now want to use my old db sqlite in the new LXC container but cannot find the location of the database folder. I tried changing the data folder in the env file to home/data but after starting vaultwarden in the shell it states that .env file is not found?

**Comment by tteck** [comment]
Have a look in `/var/lib/vaultwarden/data` and see if that's what you're looking for

**Comment by tomdh76** [comment]
Thx! that was the location. I had to change ownership from root to vaultwarden. The strang thing is that also while this is working I still see this error when starting vaultwarden

[INFO] No .env file found.

[2022-03-23 21:34:58.220][vaultwarden][ERROR] Data folder 'data' doesn't exist.
[2022-03-23 21:34:58.220][vaultwarden][ERROR] Create the data folder and try again.

**Comment by tteck** [comment]
Did you put the `.env` back to original?

**Comment by tomdh76** [comment]
I put back the original .env file and have now only the info "no .env file found" but it actually reads the env file.

**Comment by tteck** [comment]
My `.env` file is owned by root
```
root@vaultwarden:~# ls -l /etc/vaultwarden.env
-rw-r--r-- 1 root root 18095 Mar 11 13:16 /etc/vaultwarden.env
```
