### ISSUE TITLE
Balooning of storage for docker in LXC when using ZFS as storage backend

### ISSUE THREAD

**Issue by rallegade** [tteck/Proxmox#875]
---------------------------------------------------------
ZFS and VFS is not a good combo
----------------------------------------------------------
The Docker instance in LXC is having issues when utilizing VFS on a ZFS storage backend, which leads to huge ballooning of storage use.
This in terms also leads to a huge bootdisk size over time (22GB vs 3GB on VM's for my containers) which also defeats the purpose of using LXC in the first place.

To overcome this please move away from VFS and to fuse-overlay instead if the storage for the LXC is ZFS.

---------------------------------------------------------
Temp manual fix for the issue
----------------------------------------------------------
install the necessary components
```
apt update && apt upgrade -y
apt install fuse-overlayfs docker.io
```
Change storage driver used by docker
`sudo nano /etc/docker/daemon.json`

add the following to the file
```
{
  "storage-driver": "fuse-overlayfs"
}
```
Shut down the container

On the Proxmox host edit /etc/pve/lxc/"containernumber".conf
add the following line to the end of the config
`lxc.mount.entry: /dev/fuse dev/fuse none bind,create=file,rw,uid=165536,gid=165536 0 0`

inside the LXC remember to remove the old VFS (located in /var/lib/docker/vfs)

---------------------------------------------------------
Fix on long term
----------------------------------------------------------
Would it maybe be possible to add a function to the install script which looks at the storage backend to where the LXC is stored?
And then make it use the appropriate storage driver.

**Comment by tteck** [comment]
Testing this now
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker-v4.sh)"
```
https://github.com/tteck/Proxmox/discussions/869

**Comment by tteck** [comment]
If you would create a new Docker LXC and test that would help immensely.

**Comment by rallegade** [comment]
I will do that

**Comment by rallegade** [comment]
I can confirm that it does work.

Tested it with UISP docker, which will use over 50GB on VFS with ZFS backend.
Down to a normal 5GB with the fixed script.

**Comment by tteck** [comment]
Great! I will push it to the main branch if you can't recommend any changes.

**Comment by rallegade** [comment]
Nope.
Seems good to me!

**Comment by timdonovanuk** [comment]
A word of caution - running docker using fuse-overlay is strongly not recommended by the Proxmox team, and several native PVE features like snapshots, backups and migration may not work or may end up in data corruption. It is even written in the PVE docs as a warning:

`Because of existing issues in the Linux kernel’s freezer subsystem the usage of FUSE mounts inside a container is strongly advised against, as containers need to be frozen for suspend or snapshot mode backups.`

https://pve.proxmox.com/pve-docs/pve-admin-guide.html#pct_container_storage

I will still be using it, but just wanted to let people know the potential issues. Straight up snapshots throw an error for me:


```
failed to open /var/lib/docker/fuse-overlayfs/a8361096cb649bacd97ad73f3357659ec5f676531a17de7bb19002db809f70ad/merged: Permission denied
TASK OK
```

**Comment by huuub** [comment]
Created an docker container priviliged using zfs storage. Wanted to take a snapshot but it keeps running. So I stopped it after 2 minutes. Should take 3 seconds??
When shutting it down it does work and takes 3 seconds

**Comment by tteck** [comment]
🤞🏻  https://forum.proxmox.com/threads/lxc-zfs-docker-overlay2-driver.122621/#post-535670

**Comment by huuub** [comment]
Hmm indeed. used your script again. It is using overlayed
`docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /root/.docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.85-1-pve
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 8GiB
 Name: media
 ID: 128acf07-802d-4e02-93a1-f4cd16e72326
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**Comment by huuub** [comment]
Seems to work indeed! Privileged and unPrivileged
