### ISSUE TITLE
Home Assistant OS fail 

### ISSUE THREAD

**Issue by sp2003** [tteck/Proxmox#885]
```
    __  __                        ___              _      __              __     ____  _____
   / / / /___  ____ ___  ___ v4  /   |  __________(_)____/ /_____ _____  / /_   / __ \/ ___/
  / /_/ / __ \/ __ `__ \/ _ \   / /| | / ___/ ___/ / ___/ __/ __ `/ __ \/ __/  / / / /\__ \
 / __  / /_/ / / / / / /  __/  / ___ |(__  |__  ) (__  ) /_/ /_/ / / / / /_   / /_/ /___/ /
/_/ /_/\____/_/ /_/ /_/\___/  /_/  |_/____/____/_/____/\__/\__,_/_/ /_/\__/   \____//____/

Using Advanced Settings
Using HAOS Version: 9.4
Virtual Machine ID: 105
Using Machine Type: i440fx
Using Hostname: haos
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using MAC Address: 00:60:2F:13:60:1F
Using Vlan: Default
Start VM when completed: yes
Creating a HAOS VM using the above advanced settings
 ✓ Using VM for Storage Location.
 ✓ Virtual Machine ID is 105.
 ✓ https://github.com/home-assistant/operating-system/releases/download/9.4/haos_ova-9.4.qcow2.xz
 ✓ Downloaded haos_ova-9.4.qcow2.xz
 ✓ Extracted KVM Disk Image
 - Creating HAOS VM...‼ ERROR 255@280 Unknown failure occurred.
root@server:~#
```

the script hangs at this line, can it be fixed?

`pvesm alloc $STORAGE $VMID $DISK0 4M 1>&/dev/null`

**Comment by tteck** [comment]
You have a _stray_ `vm-105-disk-0`
Remove it and run the script again.

![Screenshot 2022-12-31 12 32 40 PM](https://user-images.githubusercontent.com/21342670/210151468-474f29d9-4867-4a76-a57a-7cf254f56f35.png)

**Comment by sp2003** [comment]
![Immagine 2022-12-31 184721](https://user-images.githubusercontent.com/34820831/210151769-ebadd4fc-0847-461d-80e9-5e1dd0508c10.png)
![Immagine 2022-12-31 184806](https://user-images.githubusercontent.com/34820831/210151771-8349cffb-b7b4-46b9-9d34-27291325ad8f.png)


already checked, there is no 105 VM

il comando di installazione l'ho inviato via SSH e dalla webUI

**Comment by tteck** [comment]
Try it again and give it a different VMID, maybe 110

**Comment by tteck** [comment]
Oh, I see you're using VM as storage. What is VM's storage type? Try using `local-lvm`

**Comment by sp2003** [comment]
VM it' s a SMB folder on nas (VM100)
local-lvm is full, there is no more space

now whit 110 as machine number

`Creating HAOS VM...‼ ERROR 2@280 Unknown failure occurred.`

**Comment by tteck** [comment]
Have you ever created a VM on SMB folder on nas before?

**Comment by tteck** [comment]
You're trying to create a VM on a VM?

**Comment by sp2003** [comment]
yes, VM foldere is a shared folder from VM100 whit openmediavault

in VM folder , the script created
![Immagine 2022-12-31 192251](https://user-images.githubusercontent.com/34820831/210152516-109f2205-2a41-45be-9685-f16b4505badb.png)

**Comment by tteck** [comment]
Makes no sense to me, but good luck.

**Comment by marove2000** [comment]
I ran into the same error. Identified problem was using local-zfs -> this does not work with the script

**Solution/Workaround:**

You have to create a storage where the qcow image can be installed, then move image to zfs.

1. Datacenter -> Storage -> Add Directory
![image](https://github.com/tteck/Proxmox/assets/16056973/e76b2bce-746e-40d2-a997-db4cff81c42d)
2. Use local-qcow for installation
3. go to your new created vm (stop it) -> Hardware -> Left click on your hard disk (scsi0) -> Disk Action -> Move Storage
![image](https://github.com/tteck/Proxmox/assets/16056973/8371578d-ca80-4679-8610-9dca4dc5892d)
4. Move your storage to local-zfs
![image](https://github.com/tteck/Proxmox/assets/16056973/4b1faf70-c726-434d-8fba-96a81e634222)
5. optional: You can delete local-qcow afterwards again

**Comment by Dodoooh** [comment]
@marove2000 you are the saviour of my frustrated evening thank you!

@tteck is there a reason why local-zfs is no longer supported? previously it worked with ZFS

**Comment by tteck** [comment]
@Dodoooh would you try again https://github.com/tteck/Proxmox/commit/bf40c30fffee07424aba152aba05aa6403089725

**Comment by Dodoooh** [comment]
> @Dodoooh would you try again [bf40c30](https://github.com/tteck/Proxmox/commit/bf40c30fffee07424aba152aba05aa6403089725)

I still get this error: 
`[ERROR] in line 448: exit code 0: while executing command pvesm alloc $STORAGE $VMID $DISK0 4M >&/dev/null`


I have cleaned up the VM Disks, there are none with this ID, in a other try I have also selected a new ID in advanced which I have never used before
