### ISSUE TITLE
Error Installing Shinobi

### ISSUE THREAD

**Issue by xtremeideaz** [tteck/Proxmox#886]
Hello, 

Please help, I'm having a problem installing Shinobi using the proxy script.

Here's my log.

   _____ __    _             __    _ 
  / ___// /_  (_)___v4____  / /_  (_)
  \__ \/ __ \/ / __ \/ __ \/ __ \/ / 
 ___/ / / / / / / / / /_/ / /_/ / /  
/____/_/ /_/_/_/ /_/\____/_.___/_/   
                                     
Using Default Settings
Using ubuntu Version: 22.04
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: Automatic Login
Using Container ID: 100
Using Hostname: shinobi
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Shinobi LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 100 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.0.158 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed FFMPEG
 ✓ Cloned Shinobi
 ✓ Installed Database
 - Installing Shinobi...‼ ERROR 1@139 Unknown failure occurred.
root@vira:~#

**Comment by tteck** [comment]
Can't replicate 

```
   _____ __    _             __    _ 
  / ___// /_  (_)___v4____  / /_  (_)
  \__ \/ __ \/ / __ \/ __ \/ __ \/ / 
 ___/ / / / / / / / / /_/ / /_/ / /  
/____/_/ /_/_/_/ /_/\____/_.___/_/   
                                     
Using Advanced Settings
Using Ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: password
Using Container ID: 112
Using Hostname: shinobi
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Shinobi LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed FFMPEG
 ✓ Cloned Shinobi
 ✓ Installed Database
 ✓ Installed Shinobi
 ✓ Cleaned
 ✓ Completed Successfully!

Shinobi Setup should be reachable by going to the following URL.
         http://192.168.86.252:8080/super 
```
https://github.com/tteck/Proxmox/blob/14dcfe29f6b6ad98f52238bc03b1ad904e046f0d/install/shinobi-install.sh#L139

Maybe try giving it a few more resources 🤷🏻‍♂️

**Comment by xtremeideaz** [comment]
i ran it a couple of times and it keeps stopping at "Installing Shinobi.."

Will try it on another system..

**Comment by Beef-Tech** [comment]
@xtremeideaz Didn't reproduce your error too.
Since I'm working also on a fork for my Pimox install, I can suggest you to remove `&>/dev/null` redirections in the code block around your issue.
With that, you will be able to get the exact error that occurs in your install.

**Comment by tteck** [comment]
Try running this in verbose mode

```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/shinobi-v5.sh)"
```

**Comment by tteck** [comment]
>  I can suggest you to remove `&>/dev/null` redirections in the code block around your issue.

That's one reason for the v5 script, easier troubleshooting. _Verbose Mode_ in the v5 script shows everything.
