### ISSUE TITLE
Unable to Update server with new script

### ISSUE THREAD

**Issue by yey3men2** [tteck/Proxmox#889]
I'm getting this error my LXC Ct has 3 vCPU and 4 GB of Ram:

 ⚠️  Ensure you set 2vCPU & 3072MiB RAM MIMIMUM!!! 

 ✓ Stopped Vaultwarden
 - Updating VaultWarden to 1.27.0 (Patience)...‼ ERROR 128@333 Unknown failure occurred.

**Comment by tteck** [comment]
I always update mine at 6vCPU & 4GB RAM, it's resource hungry!
The script is ok, just tested it

**Comment by yey3men2** [comment]
how do I update to the latest version? I'm trying to invite a new user but I'm getting this error:
![image](https://user-images.githubusercontent.com/85719537/210269097-7e2648d1-cba4-453e-a332-c23deb806d27.png)


thank you for all your help! I also bump the CPU to 8 and still unable to upgrade with the script.

**Comment by yey3men2** [comment]
![image](https://user-images.githubusercontent.com/85719537/210269301-a95caa60-f2c3-4edf-9ef9-e339708cc4bc.png)

**Comment by tteck** [comment]
You're failing at
https://github.com/tteck/Proxmox/blob/96bafed52efa5fad957bd12cecde87d7a7154cb0/ct/vaultwarden-v5.sh#L333

DNS?

**Comment by yey3men2** [comment]
I can clone it running that line so I don't think is DNS.

thanks again

**Comment by yey3men2** [comment]
![image](https://user-images.githubusercontent.com/85719537/210269936-9620c4e3-e010-4318-9528-3c467c1e62cd.png)

**Comment by yey3men2** [comment]
![image](https://user-images.githubusercontent.com/85719537/210270600-2c0ce13c-ac19-4d51-a991-ea65371fcd12.png)

**Comment by yey3men2** [comment]
I created a new Container and moved my data to the one one. 

Thanks again, I use a lot of your helper scripts they are awsome and save me a lot of time.
