### ISSUE TITLE
Unable to update Vaultwarden

### ISSUE THREAD

**Issue by andyw73** [tteck/Proxmox#890]
When trying to update Vaultwarden an error is generated " ERROR 128@333 Unknown failure occured". the web update works without issues. Once the process fails the container is unresponsive however a reboot of the container allows normal operation.

![vaultwarden error](https://user-images.githubusercontent.com/90845783/210342592-86da18b6-3d22-4945-a207-516a9bb423cf.png)

**Comment by tteck** [comment]
Do you have this directory `/opt/vaultwarden`?

**Comment by tteck** [comment]
failing here
https://github.com/tteck/Proxmox/blob/a0f9a1c20de708094229dfca90e924e1ac980018/ct/vaultwarden-v5.sh#L333

**Comment by tteck** [comment]
I just can't replicate it here

```
 _    __            ____ _       __               __         
| |  / /___ ___v5__/ / /| |     / /___ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
                                                             

 ⚠️  Ensure you set 2vCPU & 3072MiB RAM MIMIMUM!!! 

 ✓ Stopped Vaultwarden
 ✓ Updated VaultWarden
 ✓ Cleaned
 ✓ Started Vaultwarden
 ✓ 1.27.0 Update Successful

 ⚠️  Ensure you set resources back to normal settings 

root@vaultwarden:~# 
```
I use 6vCPU and 4GB RAM

**Comment by tteck** [comment]
I removed redirects from the Vaultwarden Update. Should show you exactly where it's failing

**Comment by andyw73** [comment]
Sorry for delay in responce. I increased cpu cores to 4 however they were already set to two and left memory @ 3072
![vaultwarden error1](https://user-images.githubusercontent.com/90845783/210402407-185bba37-5775-4830-9385-75d26b999297.png)
 and run the script again. The update is giving a warning saying "vaultwarden" already exists. I have a vaultwarden file in root as well as in the opt folder you mentioned in previous comment, please see attached.

**Comment by tteck** [comment]
Looks correct
```
root@vaultwarden:~# cd ..
root@vaultwarden:/# ls
bin   dev  home  lib32  libx32      media  opt   root  sbin  sys  usr  vaultwarden
boot  etc  lib   lib64  lost+found  mnt    proc  run   srv   tmp  var
root@vaultwarden:/# cd /opt/vaultwarden
root@vaultwarden:/opt/vaultwarden# ls
bin  data  web-vault
root@vaultwarden:/opt/vaultwarden# 
```
Check for `vaultwarden` directory in `root`

```
root@vaultwarden:~# cd
root@vaultwarden:~# ls
vaultwarden
root@vaultwarden:~# 
```
if you have one, remove it.

**Comment by tteck** [comment]
The script will now remove the `vaultwarden` directory in `root` if found before updating

**Comment by andyw73** [comment]
That has resolver the issue and Vaultwarden has now updated. Thank you for you assistance and for providing these great vm's and containers.
