### ISSUE TITLE
Pre-install question

### ISSUE THREAD

**Issue by mellowism** [tteck/Proxmox#892]
Hi, 

I hope it's alright if I ask a question before trying it myself. 
I've used some of your helper scripts with great success before, so I am planning on rebuilding my server using some of your scripts later this evening. 

Last night after I updated Proxmox to 7.3-4 my docker installations all failed to start (see [here ](https://forum.proxmox.com/threads/since-pve-7-3-4-update-all-docker-container-disappeared-from-lxc-containers.120123/) for more info) 

Will your docker LXC installation script take this in account, or is it perhaps not relevant at all? 

One solution seems to be to add [VFS as storage driver](https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/) manually.

Thanks in advance!

**Comment by tteck** [comment]
For ZFS, use "Advanced" settings and select "Fuse Overlayfs"
