### ISSUE TITLE
Issue deploying Omada controller

### ISSUE THREAD

**Issue by digilink** [tteck/Proxmox#894]
**Describe the issue**
When trying to deploy the Omada controller, it errored out with "Unkown failure occured" 

Steps taken to reproduce: 

1. bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/omada-v4.sh)"
2. Selected "Advanced" settings from setup TUI
3. Selected Ubuntu 22.04 as base OS
4. Left unprivileged (default) 
5. Set root password/container ID
6. Left hostname at default (omada) 
7. Left disk size at default (8GB)
8. Left CPU cores at default (2) 
9. Left RAM at default (2048)
10. Selected my bridge/used DHCP 
11. No gateway IP (DHCP)
12. Host DNS domain/server
13. default MAC
14. No VLAN
15. Enable root SSH
16. Enable verbose mode
17. Selected storage locations for template and container

Install errors out when trying to install Mongodb from the looks of it. 

Screenshot attached

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/16581598/210432097-3eca2e03-738f-4716-8988-4817e4c74f37.png">

**Comment by tteck** [comment]
Can't replicate

```
   ____                      __     
  / __ \____ ___v4____ _____/ /___ _
 / / / / __  __ \/ __  / __  / __  /
/ /_/ / / / / / / /_/ / /_/ / /_/ / 
\____/_/ /_/ /_/\__,_/\__,_/\__,_/  

Using Advanced Settings
Using Ubuntu Version: 20.04
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 113
Using Hostname: omada
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Omada LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 113 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Omada Controller
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Omada should be reachable by going to the following URL.
         https://192.168.86.252:8043 
```

**Comment by tteck** [comment]
You used Ubuntu 22.04 as base OS, Default is Ubuntu 20.04

If having trouble, always fall back to Default settings to see if the issue persists

**Comment by digilink** [comment]
Went to Ubuntu 20.04, deployed successfully.
