### ISSUE TITLE
Wireguard Dashboard Removed from V5 Script

### ISSUE THREAD

**Issue by RamboFR05TY** [tteck/Proxmox#896]
Hi TTeck love the scripts but just wanted to confirm the reason for the dashboard removal from V5 of the script?

I thought i was loosing my mind reinstalled it like 20 times

**Comment by tteck** [comment]
![dashboard](https://user-images.githubusercontent.com/21342670/210543640-6d28efcb-6057-48cd-9e47-48f012ad810a.png)

**Comment by RamboFR05TY** [comment]
My apologies for not actually reading that fully i didn't see the part to run the exact same command in the container for the dashboard
