### ISSUE TITLE
Any chance of  a Home Assistant Supervised LXC?

### ISSUE THREAD

**Issue by danmed** [tteck/Proxmox#9]
I'm having serious issues manually creating this and was hoping you had a script that would do it for me... Any luck?

**Comment by tteck** [comment]
Sorry, can **not** be done and meet the requirements set in [ADR-014](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) 
I'd suggest either HAOS or HA Container
