### ISSUE TITLE
Wireguard install script - seems to be changed?

### ISSUE THREAD

**Issue by MorphyDK** [tteck/Proxmox#903]
**Describe the issue**
Ran the Wireguard Installer from Server - Networking .

Also I dont see any installer for the Dashboard anymore?
Before after the installation of the LXC, you were prompted with a link to your WG server where you could add clients via Web GUI. 

I dont see that part anymore?

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/896

**Comment by MorphyDK** [comment]
Ahhhhhh f .. my life...  

THANKS <3   :)

Love your work!
