### ISSUE TITLE
Home Assistant Container LXC ISSUE

### ISSUE THREAD

**Issue by mlo-Tek** [tteck/Proxmox#913]
**Describe the issue**
After trying to run the script for the Home Assistant Container LXC Script the first mirror pops up (where to choose if installing HA or not). While selecting "YES" the following error pops up:

"bash: -c: line 398: syntax error near unexpected token"

Running the latest proxmox version 7.3.4

**Comment by tteck** [comment]
Thanks for reporting! FIXED

**Comment by hAMMERlized** [comment]
Thanks. That was fast ;)

By the way, is there any reason for deleting the script for installing HACS? I can only see the script in the podman LXC instructions. 

Oh and could you explain what you mean with "Initializing" for the HA Core only LXC? I'm trying to use this one for the first time. The only difference to the HA Container LXC is that the Core LXC is without portioner, right? Sorry for that dump questions.

**Comment by tteck** [comment]
> By the way, is there any reason for deleting the script for installing HACS? I can only see the script in the podman LXC instructions.

The ***-v5.sh script serves both to create the LXC (Proxmox Shell) and provide support for the App (LXC Console)
You will find "Install HACS" there

> explain what you mean with "Initializing" for the HA Core only LXC?

When the venv is created, you need to start it the first time a certain way. It creates the configuration file, ect...

**Comment by tteck** [comment]
> The only difference to the HA Container LXC is that the Core LXC is without portioner, right? 

No, with Core it's not ran containerized (Docker) it's ran in a virtual environment (venv)

**Comment by mlo-Tek** [comment]
Yep, found it myself. Deleted the post but u were faster.

> When the venv is created, you need to start it the first time a certain way. It creates the configuration file, ect...

Can you tell where the config.yaml is? Or the data folder at all? Actually i'm trying to find it. Maybe you should explain that in 1 sentence in the description. Thanks.

EDIT: Nevermind, found it!

Thanks for your patience :)

**Comment by mlo-Tek** [comment]
Anyway, thanks for this good work. I've donated you some coffee. Keep up the good work!

**Comment by tteck** [comment]
Thank you!
