### ISSUE TITLE
READ Before Creating a Script Issue

### ISSUE THREAD

**Issue by tteck** [tteck/Proxmox#914]
**Run scripts within the Proxmox shell directly instead of using an SSH terminal.**

The `***.sh `script serves both to create the LXC (Proxmox Shell) and provide support for the App (LXC Console)

We'll use WireGuard LXC as an example,

![Screenshot 2023-01-07 7 15 34 PM](https://user-images.githubusercontent.com/21342670/211175007-065931e7-2c57-4ea2-9208-c5b6ccc5a633.png)

To create a new Proxmox WireGuard LXC, run the command below in the **Proxmox Shell**.
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/wireguard.sh)"
```
![Screenshot 2023-01-07 7 03 28 PM](https://user-images.githubusercontent.com/21342670/211174834-a582e78f-0d5e-4c50-a638-a2b2998aaf87.png)

To Update WireGuard or Install a Dashboard, run the command below in the **LXC Console**.
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/wireguard.sh)"
```
![Screenshot 2023-01-07 7 04 41 PM](https://user-images.githubusercontent.com/21342670/211174843-ef6ce2a4-0e67-4e5f-b74d-2fa082758202.png)
![Screenshot 2023-01-07 7 05 33 PM](https://user-images.githubusercontent.com/21342670/211174845-290b7b75-eab4-4624-b017-aa023b41178a.png)

Same Command, different results

**Comment by tteck** [comment]
Another example, Home Assistant Core

![Screenshot 2023-01-07 7 52 47 PM](https://user-images.githubusercontent.com/21342670/211175986-cdf9ae72-570d-4432-9594-787793edb19c.png)
To create a new Proxmox Home Assistant Core LXC, run the following in the **Proxmox Shell**.
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homeassistant-core-v5.sh)"
```
![Screenshot 2023-01-07 7 54 11 PM](https://user-images.githubusercontent.com/21342670/211176041-3f7795e2-f92f-4235-a35c-4621572adc92.png)


To Initialize (**first start**), Update or Install HACS, run the following in the **LXC Console**.
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homeassistant-core-v5.sh)"
```
![Screenshot 2023-01-07 7 55 36 PM](https://user-images.githubusercontent.com/21342670/211176047-4de5df1c-c81a-4208-8bb1-59dae69d3956.png)
![Screenshot 2023-01-07 7 56 35 PM](https://user-images.githubusercontent.com/21342670/211176054-790018b9-6fe4-4607-b367-89a6235a9c42.png)



Again, Same Command, different results

**Comment by tteck** [comment]
If the message "To update *********, run the command below in the **LXC Console**" is not present before the command, it indicates that the app can be updated either by using the package manager or through its graphical user interface.

**Comment by tteck** [comment]
`silent()` function is defined (line 24), which takes a command as an argument and runs it in the background, directing standard output and standard error to `/dev/null` (the null device).
To troubleshoot the error message "`[ERROR] in line 24: exit code *: while executing command "$@" > /dev/null 2>&1`" run the script in verbose mode to identify the actual problem.

**Comment by tteck** [comment]
**Run scripts within the Proxmox shell directly instead of using an SSH terminal.**

**Comment by itguy327** [comment]
Running this bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/cronicle.sh)"
in LXC console to create Cronicle worker results in "No Cronicle installation found"

Not sure what I'm doing wrong, but thank you for your work

**Comment by tteck** [comment]
@itguy327  fixed

**Comment by itguy327** [comment]
Thank you

**Comment by itguy327** [comment]
> @itguy327 fixed

Not sure what this means or if there is a way to manually correct it.

 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 - Installing Cronicle Worker...environment: line 97: hostname: unbound variable

**Comment by tteck** [comment]
fixed

**Comment by itguy327** [comment]
Sweet!
Works great. Thank you !!

**Comment by SpartanTech** [comment]
I think im supposed to post this here?
![image](https://github.com/tteck/Proxmox/assets/3395163/c88fdd61-8e28-4253-a84e-bfe4cebd5be8)
Cant figure out whats going wrong.

**Comment by kzaoaai** [comment]
anyway to skip the first prompt for the update-lxcs script? maybe a "-f" or "-y". This would be useful in scheduling automatic updates

**Comment by kzaoaai** [comment]
> anyway to skip the first prompt for the update-lxcs script? maybe a "-f" or "-y". This would be useful in scheduling automatic updates

nevermind, using the YES command works:
`yes | bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/update-lxcs.sh)"`

**Comment by saltyautomation** [comment]
When installing CasaOS I received the following. I was using the proxmox shell not SSH. 

- Installing CasaOS (Patience)...
[ERROR] in line 24: exit code 1: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

**Comment by tteck** [comment]
> The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

**Comment by tteck** [comment]
No issue here.

```
   ______                 ____  _____
  / ____/___ __________ _/ __ \/ ___/
 / /   / __ `/ ___/ __ `/ / / /\__ \ 
/ /___/ /_/ (__  ) /_/ / /_/ /___/ / 
\____/\__,_/____/\__,_/\____//____/  
                                     
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: casaos
Using Disk Size: 8
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Fuse Overlayfs (ZFS): no
Enable Verbose Mode: no
Creating a CasaOS LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed CasaOS
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

CasaOS Setup should be reachable by going to the following URL.
         http://192.168.86.253  
```

**Comment by saltyautomation** [comment]
Is there a flag to get more details if a script is failing?

   ______                 ____  _____
  / ____/___ __________ _/ __ \/ ___/
 / /   / __ `/ ___/ __ `/ / / /\__ \ 
/ /___/ /_/ (__  ) /_/ / /_/ /___/ / 
\____/\__,_/____/\__,_/\____//____/  
                                     
Using Default Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 107
Using Hostname: casaos
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Fuse Overlayfs (ZFS): No
Enable Verbose Mode: No
Creating a CasaOS LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 107 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.10.200.39 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 - Installing CasaOS (Patience)...
[ERROR] in line 24: exit code 1: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

root@vhost1:~# pveversion
pve-manager/7.4-13/46c37d9c (running kernel: 5.15.107-2-pve)

**Comment by tteck** [comment]
Advanced > Verbose Mode

**Comment by saltyautomation** [comment]
CasaOS v0.4.3 is running at:
 ─────────────────────────────────────────────────────
++ error_handler 35 '$STD bash <(curl -fsSL https://get.casaos.io)'
++ local exit_code=1
++ local line_number=35
++ local 'command=$STD bash <(curl -fsSL https://get.casaos.io)'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m35\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD bash <(curl -fsSL https://get.casaos.io)\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m35\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD bash <(curl -fsSL https://get.casaos.io)\033[m'

[ERROR] in line 35: exit code 1: while executing command $STD bash <(curl -fsSL https://get.casaos.io)
++ [[ 35 -eq 24 ]]
+ exit

**Comment by tteck** [comment]
Typically, the error you've provided suggests the presence of DNS problems.

**Comment by saltyautomation** [comment]
I would agree. When I logged into the container and ran 
`bash <(curl -fsSL https://get.casaos.io) `
manually it installed fine. So I will chalk it up to something on my end related to dns. However I did not change anything in the container.

**Comment by palofi** [comment]
Hi ,I got this error when i was trying to create HomeAssistant  in Proxmox shell via this command :
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/homeassistant.sh)"`



✓ Installed Portainer 2.18.4
+ msg_info 'Pulling Home Assistant 2023.8.1 Image'
+ local 'msg=Pulling Home Assistant 2023.8.1 Image'
+ echo -ne ' - \033[33mPulling Home Assistant 2023.8.1 Image...'
 - Pulling Home Assistant 2023.8.1 Image...+ docker pull ghcr.io/home-assistant/home-assistant:stable
stable: Pulling from home-assistant/home-assistant
31e352740f53: Pull complete 
33f5e249bef8: Pull complete 
1dae939b7a5a: Pull complete 
ea80e3cc140f: Pull complete 
298f7ed72a98: Pull complete 
b110fa8f4a90: Pull complete 
ea22d747df54: Pull complete 
7615e6f1c861: Pull complete 
647f8ffdfa7a: Pull complete 
53e8f9e5f926: Pull complete 
4f4fb700ef54: Pull complete 
13d3b8db2ad8: Pull complete 
f63939dd0568: Pull complete 
91e5d3ab1fd9: Pull complete 
a9d89dcce658: Pull complete 
6cd5862f6fc8: Pull complete 
9a92e6454d24: Pull complete 
5cdcbd582f91: Pull complete 
364ec5dc3961: Pull complete 
5c8ab023ecb1: Pull complete 
107560edfc30: Pull complete 
93936a5b922b: Pull complete 
bc8b1e4a8879: Pull complete 
35c623d2744f: Extracting [==================================================>]  342.7MB/342.7MB
54c8947bcb7e: Download complete 
2cc268e8e9f9: Download complete 
7159326bb70f: Download complete 
e27edb3928fe: Download complete 
failed to register layer: open /usr/local/lib/python3.11/site-packages/zhaquirks/tuya/ts011f_switch.py: read-only file system
++ error_handler 75 '$STD docker pull ghcr.io/home-assistant/home-assistant:stable'
++ local exit_code=1
++ local line_number=75
++ local 'command=$STD docker pull ghcr.io/home-assistant/home-assistant:stable'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m75\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD docker pull ghcr.io/home-assistant/home-assistant:stable\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m75\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD docker pull ghcr.io/home-assistant/home-assistant:stable\033[m'

[ERROR] in line 75: exit code 1: while executing command $STD docker pull ghcr.io/home-assistant/home-assistant:stable
++ [[ 75 -eq 24 ]]
+ exit 


Can you please tell me what I am doing wrong ?

**Comment by tteck** [comment]
@palofi 
The script runs without any problems from this end. 
> failed to register layer: open /usr/local/lib/python3.11/site-packages/zhaquirks/tuya/ts011f_switch.py: read-only file system

**Disk or Hardware Issues:** A read-only file system could be an indication of hardware problems. Check for any hardware-related issues that might be causing the file system to become read-only.

**Comment by runben** [comment]
Hi ,I got this error when i was trying to create Paperless-ngx in Proxmox shell via this command:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"

Creating a Paperless-ngx LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 215 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.0.44 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 20.233.83.145
 ✓ Updated Container OS
 ✓ Installed Python3
 ✓ Installed Dependencies
 ✓ Installed OCR Dependencies
 ✓ Installed JBIG2
 - Installing Paperless-ngx (Patience)...
[ERROR] in line 24: exit code 2: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.

Verbose Mode:

Downloading numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 9.4/17.3 MB 39.7 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 465, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/network/download.py", line 183, in __call__
    for chunk in chunks:
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
++ error_handler 88 '$STD pip install -r requirements.txt'
++ local exit_code=2
++ local line_number=88
++ local 'command=$STD pip install -r requirements.txt'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m88\033[m: exit code \033[01;31m2\033[m: while executing command \033[33m$STD pip install -r requirements.txt\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m88\033[m: exit code \033[01;31m2\033[m: while executing command \033[33m$STD pip install -r requirements.txt\033[m'

[ERROR] in line 88: exit code 2: while executing command $STD pip install -r requirements.txt
++ [[ 88 -eq 24 ]]
+ exit

Can you please tell me what I am doing wrong? I gave 20GB disk space, just FYI.
