### ISSUE TITLE
100@22 Unknown failure occurred during proxmox/grafana lxc install

### ISSUE THREAD

**Issue by peterwup** [tteck/Proxmox#919]
While intsllation of grafana:
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/grafana-v5.sh)"`

I got the following: 

`Using Default Settings
Using Container Type: Unprivileged NO DEVICE PASSTHROUGH
Using Root Password: Automatic Login
Using Container ID: 104
Using Hostname: grafana
Using Disk Size: 2GB
Allocated Cores 1
Allocated Ram 512
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway Address: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Grafana LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using pve2 for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 104 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: fd00::2883:16ff:fe8e:d522 
 ✗ Internet NOT Connected
Would you like to continue anyway? <y/N> y
 ⚠️  Expect Issues Without Internet
 ✗ DNS Lookup Failure
 ✓ Updated Container OS
 - Installing Dependencies...‼ ERROR 100@22 Unknown failure occurred.`
 
 Tried it with manual installation but same result. 
 Only an IPv6 address is requested. 
 I have installed today NodeRed, MQTT influx, mosquito ... but there insatallation worked fine. 
 Any idea what I can do ?

**Comment by tteck** [comment]
Disable IPv6 
No Internet

**Comment by peterwup** [comment]
found the problem: no free IPv4 address in my network anymore. Sorry.
