### ISSUE TITLE
Wiki.js template gets nodjs18 which is not compatible with wikijs 2.x

### ISSUE THREAD

**Issue by Seqway** [tteck/Proxmox#922]
Hello,
i successfully used your bash script for wikijs-v5-install.sh
Everything went finde but after the configuration of wiki.js the process files with the command:

`Jan 09 21:29:51 wikijs node[1012]: 2023-01-09T21:29:51.796Z [MASTER] error: Package subpath './public/extractFiles' is not defined by "exports" in /opt/wikijs/node_modules/extract-files/package.json`

I realised that nodejs18 was installed by the template but the version 2.x of wikjs is not yet compatible with 18 version. You can read it also of their homepage:
[Wiki.js 2.x is not compatible with Node.js 18.](https://docs.requarks.io/install/requirements)

Please check

**Comment by tteck** [comment]
Thanks for reporting! FIXED
