### ISSUE TITLE
Bug when deploying Pihole LXC

### ISSUE THREAD

**Issue by barthdvs** [tteck/Proxmox#923]
Hi, first of all : thanks for your amazing work. 👍 

I just want to report a problem in the post lxc creation process : 
when running this sh:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/pihole-v5.sh)"
the CT is empty, without curl, Pi-Hole, etc.

After some researsh, i found that the url : 
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/v5/ct/pihole-v5.sh)" isn't working anymore

I have to change this line to make it work on my fork repo:

![image](https://user-images.githubusercontent.com/102857359/211800267-84060e9e-8686-48ef-bf03-3b2f4f77a243.png)

**Comment by tteck** [comment]
Thank you for reporting! FIXED
