### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by wommy** [tteck/Proxmox#933]
hard to link to individual scripts from https://tteck.github.io/Proxmox/

how can i help manifest the build process for https://github.com/tteck/Proxmox/commit/6305ae42ffe1edeeba38da214ef7a05562157d10

**Comment by tteck** [comment]
Right now there's no way to link to individual scripts

**Comment by wommy** [comment]
yup i know

but i see of no reason why https://tteck.github.io/Proxmox/#Home_Assistant or https://tteck.github.io/Proxmox/#Home_Assistant_OS_VM couldnt work

**Comment by tteck** [comment]
It's just not setup that way, yet.

**Comment by wommy** [comment]
> It's just not setup that way, yet.

yeah i know that hence me asking 

> how can i help manifest the build process for [6305ae4](https://github.com/tteck/Proxmox/commit/6305ae42ffe1edeeba38da214ef7a05562157d10)
