### ISSUE TITLE
fresh changedetection install apparently worked, but /opt/changedetection is empty and service down

### ISSUE THREAD

**Issue by smtdev** [tteck/Proxmox#946]
Hi,

What the title says. I have successfully installed the changedetection script, however, for some strange reason, the `/opt/changedetection` folder is empty and the service is not running on `[IP]:5000`. This is the first time this has happened with these scripts, so I am not sure what might have caused the issue. Any help would be greatly appreciated.

Steps to reproduce:

- Installed changedetection script
- Checked `/opt/changedetection` folder and service on `[IP]:5000`

Expected outcome:
`/opt/changedetection` folder should not be empty and service should be running on `[IP]:5000`

Actual outcome:
`/opt/changedetection` folder is empty and service is not running on `[IP]:5000`

Environment:

Operating system and version: Proxmox 7.3-3
Version of the script: Latest

Thank you.

**Comment by tteck** [comment]
Run `python3 -m pip install dnspython==2.2.1` in the LXC Console and reboot
(dnspython updated to 2.3.0 on JANUARY 15, 2023 and broke many things)

Script FIXED
