### ISSUE TITLE
Tailscale installing issue

### ISSUE THREAD

**Issue by raub21** [tteck/Proxmox#956]
I ran the script many times on different containers on proxmox and I keep getting the following error:
`This script will add Tailscale to an existing LXC Container ONLY
Did you replace 106 with your LXC ID? Proceed(y/n)?y
-s: line 47: /etc/pve/lxc/102.conf: No such file or directory
‼ ERROR 1@47 Unknown failure occured.
root@debian:~# `
![image](https://user-images.githubusercontent.com/69120711/213771179-5c5d0cd9-3f7a-460a-9bed-fffa635c7c87.png)
I know the file exists.

**Comment by tteck** [comment]
You don't run the command in a LXC console

![tailscale](https://user-images.githubusercontent.com/21342670/213774308-e8343cbb-57d0-4252-be11-2a809c4c1be9.png)

Working as intended!

```
  ______      _ __                __        
 /_  __/___ _(_) /_____________ _/ /__      
  / / / __ `/ / / ___/ ___/ __ `/ / _ \     
 / / / /_/ / / (__  ) /__/ /_/ / /  __/     
/_/  \__,_/_/_/____/\___/\__,_/_/\___/      
                                            
This script will add Tailscale to an existing LXC Container ONLY
Did you replace 106 with your LXC ID? Proceed(y/n)?y
Installing Tailscale...
Installed Tailscale
 ✔ Completed Successfully!
 Reboot 111 LXC to apply the changes, then run tailscale up in the LXC console
```
