### ISSUE TITLE
Shutdown Issue with latest Deluge Installation

### ISSUE THREAD

**Issue by skl283** [tteck/Proxmox#957]
I've installed deluge with the latest lxc-v5 Script and if i shutdown the lxc, it hangs several minutes (i think till a timeout is reached) - the system is only installed via script, nothing changed. I only get a blank/black screen - nothing happens.

Don't know how to find the issue - every other Script or LXC from you works (without the shutdown issue).

Do you have an idea what this could be the problem or to get more information to solve this?

PVE Versions are all updatet and Host is fresh reboot ;-)

**Comment by tteck** [comment]
I noticed that also. It seems it's been an ongoing issue, https://github.com/linuxserver/docker-deluge/issues/105
in our case, the `systemctl stop deluged.service` is the issue stopping. I'll see if I can come up with a remedy.
Of course you can use "Stop" instead of "Shutdown"
