### ISSUE TITLE
Docker script fails at network step - network is present.

### ISSUE THREAD

**Issue by Bugmaniac71** [tteck/Proxmox#972]
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker-v5.sh)"

Docker v5 - Creates bare container but exits saying No Network! Network is def present. Where to look please?

**Comment by Bugmaniac71** [comment]
____             __            
   / __ \____  _____/ /_v5__  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Fndpthbd01?
Using Container ID: 100
Using Hostname: docker
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
(ZFS) Enable Fuse Overlayfs: Yes
Enable Verbose Mode: Yes
Creating a Docker LXC using the above advanced settings
+ '[' yes == yes ']'
+ FEATURES=fuse=1,keyctl=1,nesting=1
++ mktemp -d
+ TEMP_DIR=/tmp/tmp.CogM64yDk2
+ pushd /tmp/tmp.CogM64yDk2
+ export ST=yes
+ ST=yes
+ export VERBOSE=yes
+ VERBOSE=yes
+ export STD=
+ STD=
+ export SSH_ROOT=no
+ SSH_ROOT=no
+ export CTID=100
+ CTID=100
+ export PCT_OSTYPE=debian
+ PCT_OSTYPE=debian
+ export PCT_OSVERSION=11
+ PCT_OSVERSION=11
+ export PCT_DISK_SIZE=4
+ PCT_DISK_SIZE=4
+ export 'PCT_OPTIONS=
  -features fuse=1,keyctl=1,nesting=1
  -hostname docker
  
  
  -net0 name=eth0,bridge=vmbr0,ip=dhcp
  -onboot 1
  -cores 2
  -memory 2048
  -unprivileged 1
  -password Fndpthbd01?
'
+ PCT_OPTIONS='
  -features fuse=1,keyctl=1,nesting=1
  -hostname docker
  
  
  -net0 name=eth0,bridge=vmbr0,ip=dhcp
  -onboot 1
  -cores 2
  -memory 2048
  -unprivileged 1
  -password Fndpthbd01?
'
++ wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/ct/create_lxc.sh
+ bash -c '#!/usr/bin/env bash
if [ "$VERBOSE" == "yes" ]; then set -x; fi
YW=$(echo "\033[33m")
BL=$(echo "\033[36m")
RD=$(echo "\033[01;31m")
GN=$(echo "\033[1;92m")
CL=$(echo "\033[m")
CM="${GN}✓${CL}"
CROSS="${RD}✗${CL}"
BFR="\\r\\033[K"
HOLD="-"

function msg_info() {
  local msg="$1"
  echo -ne " ${HOLD} ${YW}${msg}..."
}

function msg_ok() {
  local msg="$1"
  echo -e "${BFR} ${CM} ${GN}${msg}${CL}"
}
function msg_error() {
  local msg="$1"
  echo -e "${BFR} ${CROSS} ${RD}${msg}${CL}"
}

msg_info "Validating Storage"
VALIDCT=$(pvesm status -content rootdir | awk '\''NR>1'\'')
if [ -z "$VALIDCT" ]; then
  msg_error "Unable to detect a valid Container Storage location."
  exit 1
fi
VALIDTMP=$(pvesm status -content vztmpl | awk '\''NR>1'\'')
if [ -z "$VALIDTMP" ]; then
  msg_error "Unable to detect a valid Template Storage location."
  exit 1
fi

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s expand_aliases
alias die='\''EXIT=$? LINE=$LINENO error_exit'\''
trap die ERR

function error_exit() {
  trap - ERR
  local reason="Unknown failure occurred."
  local msg="${1:-$reason}"
  local flag="${RD}‼ ERROR ${CL}$EXIT@$LINE"
  echo -e "$flag $msg" 1>&2
  exit $EXIT
}

function select_storage() {
  local CLASS=$1
  local CONTENT
  local CONTENT_LABEL
  case $CLASS in
  container)
    CONTENT='\''rootdir'\''
    CONTENT_LABEL='\''Container'\''
    ;;
  template)
    CONTENT='\''vztmpl'\''
    CONTENT_LABEL='\''Container template'\''
    ;;
  *) false || die "Invalid storage class." ;;
  esac

  local -a MENU
  while read -r line; do
    local TAG=$(echo $line | awk '\''{print $1}'\'')
    local TYPE=$(echo $line | awk '\''{printf "%-10s", $2}'\'')
    local FREE=$(echo $line | numfmt --field 4-6 --from-unit=K --to=iec --format %.2f | awk '\''{printf( "%9sB", $6)}'\'')
    local ITEM="  Type: $TYPE Free: $FREE "
    local OFFSET=2
    if [[ $((${#ITEM} + $OFFSET)) -gt ${MSG_MAX_LENGTH:-} ]]; then
      local MSG_MAX_LENGTH=$((${#ITEM} + $OFFSET))
    fi
    MENU+=("$TAG" "$ITEM" "OFF")
  done < <(pvesm status -content $CONTENT | awk '\''NR>1'\'')

  if [ $((${#MENU[@]} / 3)) -eq 1 ]; then
    printf ${MENU[0]}
  else
    local STORAGE
    while [ -z "${STORAGE:+x}" ]; do
      STORAGE=$(whiptail --title "Storage Pools" --radiolist \
        "Which storage pool you would like to use for the ${CONTENT_LABEL,,}?\n\n" \
        16 $(($MSG_MAX_LENGTH + 23)) 6 \
        "${MENU[@]}" 3>&1 1>&2 2>&3) || die "Menu aborted."
    done
    printf $STORAGE
  fi
}

[[ "${CTID:-}" ]] || die "You need to set '\''CTID'\'' variable."
[[ "${PCT_OSTYPE:-}" ]] || die "You need to set '\''PCT_OSTYPE'\'' variable."

[ "$CTID" -ge "100" ] || die "ID cannot be less than 100."

if pct status $CTID &>/dev/null; then
  echo -e "ID '\''$CTID'\'' is already in use."
  unset CTID
  die "Cannot use ID that is already in use."
fi

TEMPLATE_STORAGE=$(select_storage template) || exit
msg_ok "Using ${BL}$TEMPLATE_STORAGE${CL} ${GN}for Template Storage."

CONTAINER_STORAGE=$(select_storage container) || exit
msg_ok "Using ${BL}$CONTAINER_STORAGE${CL} ${GN}for Container Storage."

msg_info "Updating LXC Template List"
pveam update >/dev/null
msg_ok "Updated LXC Template List"

TEMPLATE_SEARCH=${PCT_OSTYPE}-${PCT_OSVERSION:-}
mapfile -t TEMPLATES < <(pveam available -section system | sed -n "s/.*\($TEMPLATE_SEARCH.*\)/\1/p" | sort -t - -k 2 -V)
[ ${#TEMPLATES[@]} -gt 0 ] || die "Unable to find a template when searching for '\''$TEMPLATE_SEARCH'\''."
TEMPLATE="${TEMPLATES[-1]}"

if ! pveam list $TEMPLATE_STORAGE | grep -q $TEMPLATE; then
  msg_info "Downloading LXC Template"
  pveam download $TEMPLATE_STORAGE $TEMPLATE >/dev/null ||
    die "A problem occured while downloading the LXC template."
  msg_ok "Downloaded LXC Template"
fi

DEFAULT_PCT_OPTIONS=(
  -arch $(dpkg --print-architecture))

PCT_OPTIONS=(${PCT_OPTIONS[@]:-${DEFAULT_PCT_OPTIONS[@]}})
[[ " ${PCT_OPTIONS[@]} " =~ " -rootfs " ]] || PCT_OPTIONS+=(-rootfs $CONTAINER_STORAGE:${PCT_DISK_SIZE:-8})

msg_info "Creating LXC Container"
pct create $CTID ${TEMPLATE_STORAGE}:vztmpl/${TEMPLATE} ${PCT_OPTIONS[@]} >/dev/null ||
  die "A problem occured while trying to create container."
msg_ok "LXC Container ${BL}$CTID${CL} ${GN}was successfully created."'
++ echo '\033[33m'
+ YW='\033[33m'
++ echo '\033[36m'
+ BL='\033[36m'
++ echo '\033[01;31m'
+ RD='\033[01;31m'
++ echo '\033[1;92m'
+ GN='\033[1;92m'
++ echo '\033[m'
+ CL='\033[m'
+ CM='\033[1;92m✓\033[m'
+ CROSS='\033[01;31m✗\033[m'
+ BFR='\r\033[K'
+ HOLD=-
+ msg_info 'Validating Storage'
+ local 'msg=Validating Storage'
+ echo -ne ' - \033[33mValidating Storage...'
 - Validating Storage...++ awk 'NR>1'
++ pvesm status -content rootdir
+ VALIDCT='local-zfs     zfspool     active        62143732              96        62143636    0.00%'
+ '[' -z 'local-zfs     zfspool     active        62143732              96        62143636    0.00%' ']'
++ pvesm status -content vztmpl
++ awk 'NR>1'
+ VALIDTMP='local         dir     active        64010624         1867008        62143616    2.92%'
+ '[' -z 'local         dir     active        64010624         1867008        62143616    2.92%' ']'
+ set -o errexit
+ set -o errtrace
+ set -o nounset
+ set -o pipefail
+ shopt -s expand_aliases
+ alias 'die=EXIT=$? LINE=$LINENO error_exit'
+ trap die ERR
+ [[ -n 100 ]]
+ [[ -n debian ]]
+ '[' 100 -ge 100 ']'
+ pct status 100
++ select_storage template
++ local CLASS=template
++ local CONTENT
++ local CONTENT_LABEL
++ case $CLASS in
++ CONTENT=vztmpl
++ CONTENT_LABEL='Container template'
++ local -a MENU
++ read -r line
+++ awk 'NR>1'
+++ pvesm status -content vztmpl
+++ echo local dir active 64010624 1867008 62143616 2.92%
+++ awk '{print $1}'
++ local TAG=local
+++ echo local dir active 64010624 1867008 62143616 2.92%
+++ awk '{printf "%-10s", $2}'
++ local 'TYPE=dir       '
+++ echo local dir active 64010624 1867008 62143616 2.92%
+++ awk '{printf( "%9sB", $6)}'
+++ numfmt --field 4-6 --from-unit=K --to=iec --format %.2f
++ local 'FREE=   57.88GB'
++ local 'ITEM=  Type: dir        Free:    57.88GB '
++ local OFFSET=2
++ [[ 38 -gt '' ]]
++ local MSG_MAX_LENGTH=38
++ MENU+=("$TAG" "$ITEM" "OFF")
++ read -r line
++ '[' 1 -eq 1 ']'
++ printf local
+ TEMPLATE_STORAGE=local
+ msg_ok 'Using \033[36mlocal\033[m \033[1;92mfor Template Storage.'
+ local 'msg=Using \033[36mlocal\033[m \033[1;92mfor Template Storage.'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mUsing \033[36mlocal\033[m \033[1;92mfor Template Storage.\033[m'
 ✓ Using local for Template Storage.
++ select_storage container
++ local CLASS=container
++ local CONTENT
++ local CONTENT_LABEL
++ case $CLASS in
++ CONTENT=rootdir
++ CONTENT_LABEL=Container
++ local -a MENU
++ read -r line
+++ pvesm status -content rootdir
+++ awk 'NR>1'
+++ echo local-zfs zfspool active 62143720 96 62143624 0.00%
+++ awk '{print $1}'
++ local TAG=local-zfs
+++ echo local-zfs zfspool active 62143720 96 62143624 0.00%
+++ awk '{printf "%-10s", $2}'
++ local 'TYPE=zfspool   '
+++ echo local-zfs zfspool active 62143720 96 62143624 0.00%
+++ awk '{printf( "%9sB", $6)}'
+++ numfmt --field 4-6 --from-unit=K --to=iec --format %.2f
++ local 'FREE=   57.88GB'
++ local 'ITEM=  Type: zfspool    Free:    57.88GB '
++ local OFFSET=2
++ [[ 38 -gt '' ]]
++ local MSG_MAX_LENGTH=38
++ MENU+=("$TAG" "$ITEM" "OFF")
++ read -r line
++ '[' 1 -eq 1 ']'
++ printf local-zfs
+ CONTAINER_STORAGE=local-zfs
+ msg_ok 'Using \033[36mlocal-zfs\033[m \033[1;92mfor Container Storage.'
+ local 'msg=Using \033[36mlocal-zfs\033[m \033[1;92mfor Container Storage.'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mUsing \033[36mlocal-zfs\033[m \033[1;92mfor Container Storage.\033[m'
 ✓ Using local-zfs for Container Storage.
+ msg_info 'Updating LXC Template List'
+ local 'msg=Updating LXC Template List'
+ echo -ne ' - \033[33mUpdating LXC Template List...'
 - Updating LXC Template List...+ pveam update
+ msg_ok 'Updated LXC Template List'
+ local 'msg=Updated LXC Template List'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mUpdated LXC Template List\033[m'
 ✓ Updated LXC Template List
+ TEMPLATE_SEARCH=debian-11
+ mapfile -t TEMPLATES
++ pveam available -section system
++ sort -t - -k 2 -V
++ sed -n 's/.*\(debian-11.*\)/\1/p'
+ '[' 1 -gt 0 ']'
+ TEMPLATE=debian-11-standard_11.6-1_amd64.tar.zst
+ pveam list local
+ grep -q debian-11-standard_11.6-1_amd64.tar.zst
+ DEFAULT_PCT_OPTIONS=(-arch $(dpkg --print-architecture))
++ dpkg --print-architecture
+ PCT_OPTIONS=(${PCT_OPTIONS[@]:-${DEFAULT_PCT_OPTIONS[@]}})
+ [[  -features fuse=1,keyctl=1,nesting=1 -hostname docker -net0 name=eth0,bridge=vmbr0,ip=dhcp -onboot 1 -cores 2 -memory 2048 -unprivileged 1 -password Fndpthbd01?  =~  -rootfs  ]]
+ PCT_OPTIONS+=(-rootfs $CONTAINER_STORAGE:${PCT_DISK_SIZE:-8})
+ msg_info 'Creating LXC Container'
+ local 'msg=Creating LXC Container'
+ echo -ne ' - \033[33mCreating LXC Container...'
 - Creating LXC Container...+ pct create 100 local:vztmpl/debian-11-standard_11.6-1_amd64.tar.zst -features fuse=1,keyctl=1,nesting=1 -hostname docker -net0 name=eth0,bridge=vmbr0,ip=dhcp -onboot 1 -cores 2 -memory 2048 -unprivileged 1 -password 'Fndpthbd01?' -rootfs local-zfs:4
+ msg_ok 'LXC Container \033[36m100\033[m \033[1;92mwas successfully created.'
+ local 'msg=LXC Container \033[36m100\033[m \033[1;92mwas successfully created.'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mLXC Container \033[36m100\033[m \033[1;92mwas successfully created.\033[m'
 ✓ LXC Container 100 was successfully created.
+ LXC_CONFIG=/etc/pve/lxc/100.conf
+ cat
+ '[' 1 == 0 ']'
+ msg_info 'Starting LXC Container'
+ local 'msg=Starting LXC Container'
+ echo -ne ' - \033[33mStarting LXC Container...'
 - Starting LXC Container...+ pct start 100
+ msg_ok 'Started LXC Container'
+ local 'msg=Started LXC Container'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mStarted LXC Container\033[m'
 ✓ Started LXC Container
++ wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/install/docker-v5-install.sh
+ lxc-attach -n 100 -- bash -c '#!/usr/bin/env bash
if [ "$VERBOSE" == "yes" ]; then set -x; fi
YW=$(echo "\033[33m")
RD=$(echo "\033[01;31m")
BL=$(echo "\033[36m")
GN=$(echo "\033[1;92m")
CL=$(echo "\033[m")
RETRY_NUM=10
RETRY_EVERY=3
NUM=$RETRY_NUM
CM="${GN}✓${CL}"
CROSS="${RD}✗${CL}"
BFR="\\r\\033[K"
HOLD="-"
set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s expand_aliases
alias die='\''EXIT=$? LINE=$LINENO error_exit'\''
trap die ERR
silent() { "$@" > /dev/null 2>&1; }
function error_exit() {
  trap - ERR
  local reason="Unknown failure occurred."
  local msg="${1:-$reason}"
  local flag="${RD}‼ ERROR ${CL}$EXIT@$LINE"
  echo -e "$flag $msg" 1>&2
  exit $EXIT
}

function msg_info() {
  local msg="$1"
  echo -ne " ${HOLD} ${YW}${msg}..."
}

function msg_ok() {
  local msg="$1"
  echo -e "${BFR} ${CM} ${GN}${msg}${CL}"
}

function msg_error() {
  local msg="$1"
  echo -e "${BFR} ${CROSS} ${RD}${msg}${CL}"
}

msg_info "Setting up Container OS "
sed -i "/$LANG/ s/\(^# \)//" /etc/locale.gen
locale-gen >/dev/null
while [ "$(hostname -I)" = "" ]; do
  echo 1>&2 -en "${CROSS}${RD} No Network! "
  sleep $RETRY_EVERY
  ((NUM--))
  if [ $NUM -eq 0 ]; then
    echo 1>&2 -e "${CROSS}${RD} No Network After $RETRY_NUM Tries${CL}"
    exit 1
  fi
done
msg_ok "Set up Container OS"
msg_ok "Network Connected: ${BL}$(hostname -I)"

set +e
alias die='\'''\''
if nc -zw1 8.8.8.8 443; then msg_ok "Internet Connected"; else
  msg_error "Internet NOT Connected"
    read -r -p "Would you like to continue anyway? <y/N> " prompt
    if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]; then
      echo -e " ⚠️  ${RD}Expect Issues Without Internet${CL}"
    else
      echo -e " 🖧  Check Network Settings"
      exit 1
    fi
fi
RESOLVEDIP=$(nslookup "github.com" | awk -F'\'':'\'' '\''/^Address: / { matched = 1 } matched { print $2}'\'' | xargs)
if [[ -z "$RESOLVEDIP" ]]; then msg_error "DNS Lookup Failure"; else msg_ok "DNS Resolved github.com to $RESOLVEDIP"; fi
alias die='\''EXIT=$? LINE=$LINENO error_exit'\''
set -e

msg_info "Updating Container OS"
$STD apt-get update
$STD apt-get -y upgrade
msg_ok "Updated Container OS"

msg_info "Installing Dependencies"
$STD apt-get install -y curl
$STD apt-get install -y sudo
msg_ok "Installed Dependencies"

get_latest_release() {
  curl -sL https://api.github.com/repos/$1/releases/latest | grep '\''"tag_name":'\'' | cut -d'\''"'\'' -f4
}

DOCKER_LATEST_VERSION=$(get_latest_release "moby/moby")
PORTAINER_LATEST_VERSION=$(get_latest_release "portainer/portainer")
DOCKER_COMPOSE_LATEST_VERSION=$(get_latest_release "docker/compose")

msg_info "Installing Docker $DOCKER_LATEST_VERSION"
DOCKER_CONFIG_PATH='\''/etc/docker/daemon.json'\''
mkdir -p $(dirname $DOCKER_CONFIG_PATH)
if [ "$ST" == "yes" ]; then
VER=$(curl -s https://api.github.com/repos/containers/fuse-overlayfs/releases/latest | grep "tag_name" | awk '\''{print substr($2, 2, length($2)-3) }'\'')
cd /usr/local/bin
curl -sSL -o fuse-overlayfs https://github.com/containers/fuse-overlayfs/releases/download/$VER/fuse-overlayfs-x86_64
chmod 755 /usr/local/bin/fuse-overlayfs
cd ~
echo -e '\''{\n  "storage-driver": "fuse-overlayfs",\n  "log-driver": "journald"\n}'\'' > /etc/docker/daemon.json
else
echo -e '\''{\n  "log-driver": "journald"\n}'\'' > /etc/docker/daemon.json
fi
$STD sh <(curl -sSL https://get.docker.com)
msg_ok "Installed Docker $DOCKER_LATEST_VERSION"

read -r -p "Would you like to add Portainer? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]; then
  PORTAINER="Y"
else
  PORTAINER="N"
fi

if [[ $PORTAINER == "Y" ]]; then
  msg_info "Installing Portainer $PORTAINER_LATEST_VERSION"
  docker volume create portainer_data >/dev/null
 $STD docker run -d \
    -p 8000:8000 \
    -p 9000:9000 \
    --name=portainer \
    --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer-ce:latest
  msg_ok "Installed Portainer $PORTAINER_LATEST_VERSION"
fi

read -r -p "Would you like to add Docker Compose? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]; then
  DOCKER_COMPOSE="Y"
else
  DOCKER_COMPOSE="N"
fi

if [[ $DOCKER_COMPOSE == "Y" ]]; then
  msg_info "Installing Docker Compose $DOCKER_COMPOSE_LATEST_VERSION"
  DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
  mkdir -p $DOCKER_CONFIG/cli-plugins
  curl -sSL https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_LATEST_VERSION/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
  chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
  msg_ok "Installed Docker Compose $DOCKER_COMPOSE_LATEST_VERSION"
fi

PASS=$(grep -w "root" /etc/shadow | cut -b6)
if [[ $PASS != $ ]]; then
  msg_info "Customizing Container"
  rm /etc/motd
  rm /etc/update-motd.d/10-uname
  touch ~/.hushlogin
  GETTY_OVERRIDE="/etc/systemd/system/container-getty@1.service.d/override.conf"
  mkdir -p $(dirname $GETTY_OVERRIDE)
  cat <<EOF >$GETTY_OVERRIDE
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin root --noclear --keep-baud tty%I 115200,38400,9600 \$TERM
EOF
  systemctl daemon-reload
  systemctl restart $(basename $(dirname $GETTY_OVERRIDE) | sed '\''s/\.d//'\'')
  msg_ok "Customized Container"
fi
if [[ "${SSH_ROOT}" == "yes" ]]; then
  sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" /etc/ssh/sshd_config
  systemctl restart sshd
fi

msg_info "Cleaning up"
$STD apt-get autoremove
$STD apt-get autoclean
msg_ok "Cleaned"'
++ echo '\033[33m'
+ YW='\033[33m'
++ echo '\033[01;31m'
+ RD='\033[01;31m'
++ echo '\033[36m'
+ BL='\033[36m'
++ echo '\033[1;92m'
+ GN='\033[1;92m'
++ echo '\033[m'
+ CL='\033[m'
+ RETRY_NUM=10
+ RETRY_EVERY=3
+ NUM=10
+ CM='\033[1;92m✓\033[m'
+ CROSS='\033[01;31m✗\033[m'
+ BFR='\r\033[K'
+ HOLD=-
+ set -o errexit
+ set -o errtrace
+ set -o nounset
+ set -o pipefail
+ shopt -s expand_aliases
+ alias 'die=EXIT=$? LINE=$LINENO error_exit'
+ trap die ERR
+ msg_info 'Setting up Container OS '
+ local 'msg=Setting up Container OS '
+ echo -ne ' - \033[33mSetting up Container OS ...'
 - Setting up Container OS ...+ sed -i '/en_US.UTF-8/ s/\(^# \)//' /etc/locale.gen
+ locale-gen
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 9 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 8 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 7 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 6 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 5 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 4 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 3 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 2 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 1 -eq 0 ']'
++ hostname -I
+ '[' '' = '' ']'
+ echo -en '\033[01;31m✗\033[m\033[01;31m No Network! '
✗ No Network! + sleep 3
+ (( NUM-- ))
+ '[' 0 -eq 0 ']'
+ echo -e '\033[01;31m✗\033[m\033[01;31m No Network After 10 Tries\033[m'
✗ No Network After 10 Tries
+ exit 1
+ exit
root@pve:~# bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/docker-v5.sh)"^C
root@pve:~# 
root@pve:~#

**Comment by tteck** [comment]
It's not getting an IP assigned from your router

**Comment by tteck** [comment]
No issues with script

```
    ____             __            
   / __ \____  _____/ /_v5__  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 111
Using Hostname: docker
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: 192.168.86.252/24
Using Gateway IP Address: 192.168.86.1
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: Default
Using Vlan: Default
Enable Root SSH Access: No
(ZFS) Enable Fuse Overlayfs: No
Enable Verbose Mode: No
Creating a Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 111 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.252 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker v20.10.23
Would you like to add Portainer? <y/N> 
Would you like to add Docker Compose? <y/N> 
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

```
