### ISSUE TITLE
Can't connect to Heimdall Dashboard via http://<ip address>:7990

### ISSUE THREAD

**Issue by circa1741** [tteck/Proxmox#98]
Heimdall Dashboard LXC creation was successful.

 Using Unprivileged Install
 Using Password (changeme)
 Using Automatic DHCP
[INFO] Using local for Template Storage.
[INFO] Using local for Container Storage.
 Updating LXC Template List... ✔ 
 Creating LXC Container... ✔ 
[INFO] LXC Container 112 was successfully created.
 Starting LXC Container... ✔ 
 Setting up Container OS... ✔ 
 Network Connected: 192.168.1.106 2605:a601:ab63:e200:8ea:1bff:fea0:b6e2  ✔ 
 Updating Container OS... ✔ 
 Installing Dependencies... ✔ 
 Installing PHP... ✔ 
 Installing Heimdall Dashboard v2.4.8... ✔ 
 Creating Service... ✔ 
 Cleanup... ✔ 

Successfully created Heimdall Dashboard LXC to 112. 
Heimdall Dashboard should be reachable by going to the following URL.
         http://<ip address>:7990

Pinging the correct ip address is successful. Navigating to the correct ip address and regular http port returns the "Apache2 Debian Default Page" indicating that the web server is running. However, navigating to the provided Heimdall Dashboard URL with the correct ip address and port is **not connecting**.

**Comment by tteck** [comment]
~IPV6 messing with it?~

**Comment by tteck** [comment]
I found the issue...
Do `nano /etc/systemd/system/heimdall.service` and change `WorkingDirectory=/opt/Heimdall-2.4.6` to `WorkingDirectory=/opt/Heimdall-2.4.8` then `sudo systemctl enable --now heimdall.service`
Sorry about that

**Comment by tteck** [comment]
Script has been fixed. Thank you for reporting the issue.

**Comment by circa1741** [comment]
Thank you very much.
