### ISSUE TITLE
Paperless-ngx - login credentials missing

### ISSUE THREAD

**Issue by ThoHilde** [tteck/Proxmox#989]
**Describe the issue**
After installing paperless-ngx via script you are not able to login with the standard admin:admin and there is no other username:pw combination provided.

**Comment by tteck** [comment]
![paperless](https://user-images.githubusercontent.com/21342670/214944803-2dd3d0fb-af9a-43e2-85ca-24f1c1f4e483.png)

**Comment by richardjlyon** [comment]
Running the command command again to show the credentials appears to attempt to reinstall it, not show the credentials.

What credentials should be used to log in?

**Comment by richardjlyon** [comment]
Opening the LXC Console produces a prompt to log in. There's nowhere to run the command to show the credentials to login.

I'm sure this is all very obvious to you, but it's not very helpful for those of us who are relatively unfamiliar with proxmox. Thank you for your effort, how ever, even if Ibeing unable to log in means I can't benefit from it.

**Comment by tteck** [comment]
> Opening the LXC Console produces a prompt to log in

If you didn't set a password using Advanced settings, the script didn't finish successfully. 
It is crucial not to exit the Proxmox shell while running scripts. Leaving the shell during script execution will result in the script being interrupted.
