### ISSUE TITLE
Omada v5 LXC Advanced Mode Ubuntu 22.04/22.10

### ISSUE THREAD

**Issue by nireins** [tteck/Proxmox#998]
Hi, 
i see this error: 

+ wget -qL https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.23_amd64.deb
+ dpkg -i mongodb-org-server_3.6.23_amd64.deb
Selecting previously unselected package mongodb-org-server.
(Reading database ... 20474 files and directories currently installed.)
Preparing to unpack mongodb-org-server_3.6.23_amd64.deb ...
Unpacking mongodb-org-server (3.6.23) ...
dpkg: dependency problems prevent configuration of mongodb-org-server:
 mongodb-org-server depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1 is not installed.

dpkg: error processing package mongodb-org-server (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.10.2-2) ...
Errors were encountered while processing:
 mongodb-org-server
++ EXIT=1
++ LINE=94
++ error_exit
++ trap - ERR
++ local 'reason=Unknown failure occurred.'
++ local 'msg=Unknown failure occurred.'
++ local 'flag=\033[01;31m‼ ERROR \033[m1@94'
++ echo -e '\033[01;31m‼ ERROR \033[m1@94 Unknown failure occurred.'
‼ ERROR 1@94 Unknown failure occurred.
++ exit 1
+ exit

this my advanved settings:

OS: Ubuntu 22.04 / Ubuntu 22.10 (testet width both)
Type: 1 privileg
Set Root Password: "may password"
Container ID: 145
Hostname: omada
Diskspace: 8 GB
CPU Cores: 2
RAM: 2048 MB
Bridge: vmbr0
static ipv4: dhcp
Gateway: blank
Ipv6: no
MTU, DNS, DNS Server, MAC, VLAN: blank
Root SSH: yes
Verbose Mode: yes

What is wrong?

Can you help me, please?

**Comment by tteck** [comment]
Have you tried 20.04?

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/issues/894

**Comment by nireins** [comment]
> Have you tried 20.04?

yes. that´s ok and functionally. 

But why can´t i use OS 22.04 or 22.10?

**Comment by tteck** [comment]
Package libssl1.1 is deprecated in =>22.04

**Comment by nireins** [comment]
> Package libssl1.1 is deprecated in =>22.04

Ah ok, I wasn't aware of that. All right, thanks for the information.

One more question: Can I make suggestions/requests for new LXC containers under "pull requests"? or where can i do that?

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/discussions

**Comment by nireins** [comment]
> https://github.com/tteck/Proxmox/discussions

thanks
